### ISSUE TITLE
Encryption for EventBus

### ISSUE THREAD

**Issue by cescoffier** [eclipse-vertx/vert.x#1275]
Initial ticket: Encryption for EventBus #574:

For being able to run a vertx-cluster on a LAN, where other nodes are present (they should not be able to read the event bus communication) encryption for the server node traffic is necessary.

**Comment by dstroyrofworlds** [comment]
Was 2 days into a new Vertx project at my job - then realized this and had to drop it. Back to Play.

**Comment by johr** [comment]
What are the components involved in securing the event bus communication?
- securing cluster manager communication
- securing direct communication between the nodes
- ...

maybe https://github.com/vert-x3/issues/issues/28 is a prerequisite? It supports replacing the default transport of the event bus by a secured one.

Any comments on this?

**Comment by cescoffier** [comment]
No it does not requires a pluggable transport, at least not in the implementation I've in mind.
It just had a couple of callbacks to encrypt the headers, playload and decrypt them on the other side.

**Comment by johr** [comment]
Ok. So the encryption would be on a per message basis (not on the underlying transport), letting a handler decide what to do with the message. 
If you encrypt the headers and payload, then the whole message is secured?
I mean there goes just enrypted data over the wire; no (other) parts of the message are in plain text? (I guess so.)

If you are talking about callbacks, it may not be necessary to devote them just to encryption
but doing it more generically like "handleMessageContent()". Then this callback could be used
for other transformations too.
What comes into my mind: there is already the possibility to provide a custom MessageCodec.
There could be an "EncryptingMessageCodec". But surely, if one wants to have encryption 
as a separate feature (maybe there need to be done other things compared to the MessageCodec processing) then this would be the right way. Don't know if a MessageCodec would be on a per message basis.

**Comment by davidafsilva** [comment]
I would rather not rely on any kind of manual encryption mechanism built as part of vert.x. I would prefer to delegate to the underlying transport protocol (e.g. by using public-key crypto) and/or platform (netty), or at least had the option to choose between strategies.

On the other hand, this approach might make it hard if one wants to support some degree of flexibility regarding the channel encryption, since theoretically not all of them would actually require it (e.g. endpoints/nodes within the same DMZ) and the ([sometimes not-so-negligible](https://github.com/netty/netty/issues/832)) runtime and configuration overhead is unnecessary. I don't mess around with netty in a long time, so this might not even apply and also, this is ~~probably~~ just wishful thinking :smiley:

**Comment by johr** [comment]
There need not be "manual encryption". A default implementation for encryption could be provided, maybe also some mechanism (strategy) to configure encryption for specific bus-addresses. Surely the default implementation could be just using eg. asymmetric encryption (public/private keys).

Doing encryption on a per messsage basis on a specific address has the advantage, that there could be different (even none) encryption schemes active on different addresses (as davidafsilva already noted). The encryption is then regarded as being on top of vertx-event-bus, handled by the application logic. 

Additionally one could build authorization for addresses on top of this, depending on the authenticated node on the other side. Eg. there could be a map saying which node (identified by its certificate) is allowed to send which messages (eg. commands).

Encrypting just the event-bus, it is still possible that other nodes that should not be able to understand the message, could still record the encrypted messages. To overcome this "problem" (if it is one) the cluster has to be secured too, so the message is not even sent to these other nodes.

**Comment by cescoffier** [comment]
As @johr said, yes message-based encryption gives more flexibility. We have some cases where the encryption "key" depends on the address. However, it can be done "in-between": between the event bus TCP socket and the application. If you encrypt in the application, you loose the codec support.

I guess there is two features here:

* make the event bus TCP socket use SSL (and provision the certificates)
* encrypt the message individually (bit more flexible in some case)

**Comment by johr** [comment]
I don't know what you mean by "loosing codec support" if encryption is done on the received/sent message.
So I see these places where encryption could be handled
- low-level on the TCP socket using TLS
- "in beetween" using callbacks the application could register to and which are called at appropriate points in the process of getting the message from the wire to the application (maybe not only devoted to encryption-handling, but to generic message-processing)
- in the application, on the fully received/sent message

The last point is already possible with the current vertx-code (maybe using a custom message codec or just working on layer above).

I not to forget: handling security in the cluster-manager communication (shared maps, membership, ...).

**Comment by davidafsilva** [comment]
@johr sure, i can see the flexibility and use-cases for a message-based encryption approach, i truly don't mind the flexibility (surely i can make use of that as well!) :)
I do prefer mutual authentication via asymmetric crypto, that's all.

@cescoffier decomposition of this ticket into two features sounds good to me, i can work with any of them, not having any kind of support for encryption is what really bothers me. 

Nice discussion, cheers!

**Comment by johr** [comment]
:-) 
@cescoffier What comes into my mind regarding message-based encryption is: Is there a disatvantage compared to encrypting the transport? Encrypting the message-header and payload - means that the whole message is encrypted?

**Comment by davidafsilva** [comment]
Well, message-based encryption is theoretically more complex, can be slightly more expensive (computation) and subject to be poorly done<sup>[[1]](#user-content-note1)</sup> since there's not really a standard way of doing it<sup>[[2]](#user-content-note2)</sup>, which can also imply that you don't have some of the desired properties, such as protection against message tampering and forgery. 

Of course, TLS has also its own drawbacks, end-to-end vs hop-to-hop, protocol dependent, etc. 

<span id="note1"><sup>[1]</sup></span> one can argue that this is very relative, we can suffer from this pretty much anywhere, even robust frameworks/systems/protocols can hide serious problems. 
<span id="note2"><sup>[2]</sup></span> there a couple of protocol extensions that i'm aware of, such as WS-Security for SOAP, there might be others, but i'm really familiar with

**Comment by cescoffier** [comment]
As said on this thread previously, this issue covers two different features:

1. Being able to implement low-level message based processing (such as encryption, but not only).
2. Being able to configure the event bus TCP sockets to use SSL

I've started working on the second point in https://github.com/cescoffier/vert.x/tree/eventbus-tcp-options

It provides `EventBusOptions` that let you configure SSL connection. I would like to implement some more tests before opening the PR.

**Comment by johr** [comment]
OK. I understand (we just use other words). I will have a look.

One remaining thing: 
Maybe I am wrong, but what I wanted to emphasise is that there are also the map containing membership of the cluster and shared maps that need to be secured. 
afaik this is solely the responsibility of the ClusterManager (eg hazelcast). So there needs to be encryption too, whereas 2. just covers the eventbus communication, which does not use eg. hazelcast to send messages to other nodes, but uses direct TCP communication. Does this make sense?

**Comment by cescoffier** [comment]
@johr Absolutely, this is mentioned in the documentation I've written in the branch mention above. Ignite and HZ cluster managers have example of configuration in their default configuration. I need to check for JGroups.

**Comment by johr** [comment]
Checked your PR.
Fine. For the first time we can enforce encryption on the event-bus direct communication by just setting it in some options. Before there was no possibility to influence the behaviour with respect to encryption, not by configuration nor programmatically.
(The hazelcast cluster manager always had the option to change some configuration to enforce security.)

The only thing that is left for a one-stop experience, is programmatically configuring the cluster manager security. Presumably this would be another issue (like message encryption is). 
As it seems for hazelcast it can be even done programmatically http://docs.hazelcast.org/docs/3.5/manual/html/ssl.html . Could be exposed in the ClusterManager Interfaces with a default method maybe for break existing implementations of the interface?

**Comment by cescoffier** [comment]
I guess the level of encryption you want in the cluster manager depends on your use case. It's hard to provide an API for this, as it can be very hard to configure. A simple "setSSL" is not enough as parameters would be required, and these parameters would likely depend on the implementation. 

I think we should emphasize in the doc that the cluster manager **must** be secured for the time being and open another issue to analyze if it can be improved.

Message-based encryption / processing will also be tracked in another issue.

**Comment by cescoffier** [comment]
Issue for the cluster manager: https://github.com/eclipse/vert.x/issues/1324
Issue for the message-based processing: https://github.com/eclipse/vert.x/issues/1325

**Comment by johr** [comment]
Ok. Thanks.
So a better solution could be (like in Vertx or Eventbus creation) to provide some option-object containing detail about eg. the encryption to be used.

Whether it should be part of the api (as a separate method) depends if encryption schemes are already provided by the current ClusterManager implementations. The common set of supported encryption schemes (or a subset of these) could be defined as the encryption schemes, that every ClusterManager instance has to implement.

**Comment by dan-lind** [comment]
@cescoffier For TLS on the event bus, can you please include the possibility to restrict what TLS protocol versions that is accepted? PR #1276 seems related although it has not been merged yet.

**Comment by malte-behrendt** [comment]
Thanks for working on EventBus encryption! 

However, I can not make it work for me:

Setup:
- two Verticles (Ping/Pong) from the EventBus SSL Example

Working:
a) deployment on one machine, no clustering, SSL enabled
b) deployment on two machines, Hazelcast clustering, SSL disabled

Failing:
a) deployment on two machines, Hazelcast clustering, SSL enabled

Log message:
- "DEBUG: Cluster connection closed: localhost:44035 holder io.vertx.core.eventbus.impl.clustered.ConnectionHolder@b80002b"

I tried using different keys/certificates, keystore + trusted keystores, enabling/disabling client auth requirement. Nothing worked so far.

Questions:
1. How do I get more log messages from Netty/EventBus-Impl/Hazelcast?
2. Any idea what could be the issue with clustering + SSL?

**Comment by cescoffier** [comment]
Can you provide a simple reproducer ?

**Comment by mikepii** [comment]
Looks like TLS event bus encryption is now included in vertx-core (I'm using 3.6.3), I just tried it in a small test.

https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/examples/EventBusExamples.java
