### ISSUE TITLE
Configure LogDelegateFactory through file

### ISSUE THREAD

**Issue by michel-kraemer** [eclipse-vertx/vert.x#1295]
`JULLogDelegateFactory` can be configured through a system property and a file `vertx-default-jul-logging.properties`. I wonder if it would make sense to also make `LoggerFactory` configurable through the system property `vertx.logger-delegate-factory-class-name` as well as a file (probably called `vertx-logger-factory.properties` with a single property `vertx.logger-delegate-factory-class-name`) or through the Java service mechanism maybe. 

This would make it easier to pre-configure the required logger by placing a file in the classpath. This would even work in a fat jar where system properties can only be set by the caller.

What do you think?

**Comment by michel-kraemer** [comment]
I can submit a pull request of course if you like me to.

**Comment by vorburger** [comment]
Not directly related, just FYI: https://github.com/eclipse/vert.x/issues/2298 proposes making the `LogDelegateFactory` instance configurable programmatically through an API, probably `VertxOptions`.
