### ISSUE TITLE
Extend cluster manager SPI to allow encryption configuration

### ISSUE THREAD

**Issue by cescoffier** [eclipse-vertx/vert.x#1324]
Do it make sense to extend the cluster manager SPI to allow enforcing the cluster manager security (encryption) by API / option.

See https://github.com/eclipse/vert.x/issues/1275#issuecomment-192456333.

**Comment by johr** [comment]
Concerning hazelcast, it seems http://docs.hazelcast.org/docs/3.5/manual/html/ssl.html that encryption of communictation is just available for the Enterprise version.

**Comment by cescoffier** [comment]
You can configure the encryption. That should work on the "community" edition (I didn't check).

**Comment by bsneubm** [comment]
Unfortunately hazelcast dropped support for the security features in the community edition (I guess starting with 3.2). I've spent half a day of researching and found hints in the code that there must be a package that isn't available in the community edition and additional comments in this thread: https://github.com/hazelcast/hazelcast/issues/1896

I'm currently going with jgroups:
- TCP (adjust hosts in TCPPING to your environment): [jgroups-tcp.txt](https://github.com/eclipse/vert.x/files/308631/jgroups-tcp.txt)
- UDP: [jgroups-udp.txt](https://github.com/eclipse/vert.x/files/308632/jgroups-udp.txt)

create key: keytool -genseckey -alias myKey -keypass changeit -storepass changeit -keyalg AES -keysize 128 -keystore defaultStore.keystore -storetype JCEKS

**Comment by johr** [comment]
so having to look for an alternative to hazelcast ...
