### ISSUE TITLE
Add processing hooks in the clustered event bus

### ISSUE THREAD

**Issue by cescoffier** [eclipse-vertx/vert.x#1325]
This issue proposes to add "hooks" in the clustered event bus to intercept the messages just before they are written on the wire, and just after they have been read from the wire.

It would allow customizing the binary format or apply message-based encryption. 

See #1275 for more details.

**Comment by johr** [comment]
Encryption / Processing maybe could be provided as lambda in the "encodeToWire()", "decodeFromWire()" methods of a MessageCodec.

**Comment by johr** [comment]
using MessageCodec:
pro:
- processing could be different depending on the specific codec used, therefor it can be controlled by the application

cons:
- normally eg. encryptions should be used for all message-codecs

One way of using a message-codec for encryption is to have some meta-message codec which does encryption:

EncryptedMessage<S> ... denoting a message of type S that is encrypted (sender)
DecryptedMessage<R> ... denoting a message of type R that is decrypted (receiver)

MessageCodec<EncryptedMessage<S>, DecryptedMessage<R>> ... acutally looksup the message-codecs for S resp. R to do the encoding / decoding and than applies encryption (resp. the provided lambda) / decryption.
I'm not sure about the details of this, maybe there should not even be an additional "DecryptedMessage" type, .... it mainly about the idea on how this could be done.

An approach where the processing is done between the wire and the MessageCodec's decode- / encode - toWire could be a better choice.

**Comment by cescoffier** [comment]
The "interception" should be done after the message codec (so you have a buffer as input) and on the other side after the message codec.

This is a very low level interception.

**Comment by johr** [comment]
But we should not loose the possibility to have different encryption schemes (even none) depending on the address the message is sent to / received on (as you noted in https://github.com/eclipse/vert.x/issues/1275#issuecomment-189130097 )
