### ISSUE TITLE
Raw WebSocket (via /websocket) always returns binary (instead of text)

### ISSUE THREAD

**Issue by a-reisberg** [eclipse-vertx/vert.x#1330]
I have a simple sockjs echo server written with vertx using `sockJS.write(Buffer.buffer(msg))` where `msg` is a `String`. Now, on the client side, if I use `sockJS` client, then the `onmessage` gives me an echo `String`. However, when I use `websocket` and connect to `/websocket`, then the echo is a `blob` instead.

I tested with ws://echo.websocket.org  and they echo a `String` instead of a `blob`. Shouldn't `vertx` behave in the same way?

Thanks!

**Comment by a-reisberg** [comment]
The protocol [specification](http://sockjs.github.io/sockjs-protocol/sockjs-protocol-0.3.3.html) also seems to suggest that the server should send back text (which makes sense since `sockjs` only supports text).

**Comment by a-reisberg** [comment]
See https://github.com/sockjs/sockjs-protocol/issues/92 for clarification.

**Comment by aesteve** [comment]
:+1: 

I mentionned it here :

https://groups.google.com/forum/#!searchin/vertx/sockjs$20text/vertx/eDF54XNK7IA/YawJtjgyCgAJ

**Comment by guss77** [comment]
I have the same problem, unfortunately, The Vert.x SockJS implementation is part of `vertx-web`, so issues on is should be opened here: https://github.com/vert-x3/vertx-web/issues , but also there is already a drive-by pull request with a change to allow sending text messages through the `SockJSSocket` to the underlying raw Websocket transport.

Also, unfortunately, the committer appears to be not interested in following up on that PR with things like unit tests (that are required for any change). The PR is scheduled for 4.0 but with no unit tests its unlikely to be merged.

**Comment by vietj** [comment]
which PR are you referring to @guss77 ?

**Comment by vietj** [comment]
so it seems that according to https://github.com/sockjs/sockjs-protocol/issues/92 we should use text for WebSocke transport for SockJS ?

**Comment by vietj** [comment]
let's close this issue move the discussion to the vertx-web issue

**Comment by vietj** [comment]
see https://github.com/vert-x3/vertx-web/issues/1228
