### ISSUE TITLE
SSL Insecure Cipher Suites

### ISSUE THREAD

**Issue by creativeprogramming** [eclipse-vertx/vert.x#1507]
Please configure the default SSL settings to remove following cipher suites or give us some documentation on how to disable ciphers

Testing a vert-x server with https://www.ssllabs.com/ssltest/ had this result:

![image](https://cloud.githubusercontent.com/assets/954291/16728202/4d0cc146-4765-11e6-8b29-adc49b0765dc.png)

**Comment by creativeprogramming** [comment]
I mean, is there any option to remove a chiper suite for a vertx user?

Im asking for a 

`  public HttpServerOptions removeCipherSuite(String suite) {}`  method

or for a 

`  public HttpServerOptions overrideCipherSuites(List<String> suites) {}`

in addition to the already exposed:

`  public HttpServerOptions addEnabledCipherSuite(String suite) {}`

**Comment by darkredz** [comment]
I think with the latest 3.4 version there's still no such methods to disabled cipher suite. +1 for adding this

**Comment by vietj** [comment]
perhaps we hsould also revise the default cipher suites

**Comment by vietj** [comment]
a contribution is welcome by the way!

**Comment by patton73** [comment]
Any news about ciphers handling? I searched the documentation and the api but it does not seems that we can disable weak ciphers. 
Thanks.

**Comment by vietj** [comment]
@patton73 you can use http://vertx.io/docs/apidocs/io/vertx/core/net/TCPSSLOptions.html#getEnabledCipherSuites-- clear the set and add your own or removed from the set

**Comment by patton73** [comment]
Well ok at least there is a way to operate on ssl ciphers. 
But it's not good to expose the state this way. Insted an api should be provided as @creativeprogramming said last year. Do you think is better to open a new feature request about that?
Thanks.

**Comment by manish-panwar** [comment]
Guys,

I just started my server with SSL enabled, and httpServerOptions.getEnabledCipherSuites() returns empty. I wonder where/how those default cipher gets added into server options.

**Comment by vietj** [comment]
@patton73 there are operations to add enabled cipher suites, I think what is missing is a setter for the set, there are only adders

**Comment by vietj** [comment]
@manish-panwar actually you need to provide your own list and if you provide it, it will replace the default engine ssl cipher suite (which are different wether you use JDK SSL or native OpenSSL).

**Comment by zqmmqz** [comment]
Hi @vietj , wondering how to set the preferred server cipher suite order? I assumed addEnabledCipherSuites() would specify the order, however the result of a SSL report shows no preferred order.
<img width="422" alt="image" src="https://user-images.githubusercontent.com/86329318/123051488-b343b680-d3b6-11eb-9c24-8d9b5935905a.png">

**Comment by zqmmqz** [comment]
a dumb question, if I don't specify any cipher suites then the SSL report lists these ciphers. Are these the default cipher suites configured for vertx app and is there a documentation that I can check? 

If I want to specify cipher suite, am I supposed to use the ciphers only in this list? (I think yes, because when I add ciphers that are not in this list, I can run into issue)
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/86329318/123052419-aa071980-d3b7-11eb-8fb9-db144d42d3d1.png">

**Comment by vietj** [comment]
the enabled cipher suites is only used when it is not empty and thus it should be fully populated.

the list is sorted although it is a set.

there is no prepolutation of the cipher suite because, the default cipher suite depends on the SSL provider that vertx uses, e.g it could be the JDK SSL engine or Open SSL instead which will likely have different suites.

**Comment by vietj** [comment]
@zqmmqz when no cipher is added, then this is either the JDK ssl cipher suite or the OpenSSL cipher suite

**Comment by vietj** [comment]
I improved the documentation that was lacking clarity on the override and the fact that the default suites depends on the SSL engine.

**Comment by zqmmqz** [comment]
Thanks for the clarification. Does it mean the preferred cipher order is also dependent on the SSL engine I use? Is it configurable on the vertx side?

I know the cipher suites added by the addEnabledCipherSuites() is sorted, however the output shows no server preferred order
<img width="579" alt="image" src="https://user-images.githubusercontent.com/86329318/123166599-731e1b80-d42a-11eb-9989-397760a89f27.png">

i would expect that the server choose the ciphers by the order of the `enabledCipherSuites` I set like in this picture (this is a result on a non-vertx server)
<img width="416" alt="image" src="https://user-images.githubusercontent.com/86329318/123167064-f3dd1780-d42a-11eb-9902-28c484bc3ecb.png">

**Comment by vietj** [comment]
you can either configure the JDK ciphers or OpenSSL using your system tools

**Comment by zqmmqz** [comment]
@vietj could you please provide an example setting up the JdkSSLEngineOptions and OpenSSLEngineOptions? now I understand that I need to set up either to enable the advanced settings, however I couldn't figure out what format/information to follow from the doc and code

**Comment by vietj** [comment]
those options will not configured the cipher suites (I think actually they should instead of the options but well)
