### ISSUE TITLE
Vertx eventbus cluster issue - version 3.x (cluster host listen on all interfaces)

### ISSUE THREAD

**Issue by pavanrangain** [eclipse-vertx/vert.x#1529]
Follow up to the thread https://groups.google.com/forum/#!topic/vertx/Lh7uc4s_pOg

Please note that i have gone through few of posts like
https://groups.google.com/forum/#!searchin/vertx/cluster$20eventbus/vertx/RisJt07-_IE/Cij3VeALCQAJ
and
https://groups.google.com/forum/#!searchin/vertx/cluster$20eventbus/vertx/UWS0WAwHO6k/NQfkErPVAwAJ

and few more. So this issue is not related to port being blocked by firewall...

Now coming to the issue if we use vertx as API and try to use it in cluster creating vertx object using
Vertx.clusteredVertx(options, handler)

Then if the cluster host is not set on the VertxOptions it defaults to "localhost" even if the cluster is enabled. Thus the only interface its listening on is localhost and two separate machines cannot send/publish messages to each other over eventbus. 

If we want to listen on all interfaces and set clusterhost as "0.0.0.0" then too the eventbus send/publish is not working. The reason being in "ClusteredEventBus"
the "serrverId" is created with combination of host, port. On both the machines it would end up with same values ("0.0.0.0" : <port>)

With this configuration when we do send/publish a message in ClusteredEventBus -> sendToSubs we have a check if the serverID is same as current nodes serverid 

if (!sid.equals(serverID)) {  //We don't send to this node

This is true for as all nodes which have been configured with cluster host as "0.0.0.0". So the message would never be propagated to the remote host/nodes

May be we can use a unique ID auto generated or some other mechanism to get the "serverid" to keep it unique across a cluster configured to listen on all interfaces.

**Comment by ernestojpg** [comment]
Hi, I'm also suffering for this problem.
It is a real pain having to calculate and pass the host IP when starting the application.
Why don't we use the IP from the Cluster Manager? Hazelcast obtains that IP automatically ...

**Comment by tsegismont** [comment]
We can't fix this without breaking cluster manager backward compatibility. We will fix that in Vert.x 4 while reworking the clustering SPI.

**Comment by WolfgangFahl** [comment]
Currently this is a showstopper for my project since i can't finde a workaround and the message 
`WARN  i.v.c.e.i.clustered.ConnectionHolder - Connecting to server localhost:53612 failed` is not helping what so ever - there needs to be a lot more debug information in a failure situation like this.

**Comment by tsegismont** [comment]
Fixed in #3491
