### ISSUE TITLE
Safe jackson module registration

### ISSUE THREAD

**Issue by grossws** [eclipse-vertx/vert.x#1558]
Currently `mapper` and `prettyMapper` can be customized because they are `public static` fields but such customization can be a bit fragile (because of visibility issues) even if no concurrent modification happens. 

I propose to add method `Json.customize(Consumer<? super ObjectMapper> customizer)` which will pass `mapper` and `prettyMapper` to customizer to allow user safe customization (like registering modules for e.g. guava serialization/deserialization) and either 
- make these field `public volatile` (to preserve backward compatibility for ones who modified mappers in these fields);
- make them `private volatile` and provide accessors;
- make them `private`, provide accessors and use them under syncronized/rwlock.

Also I propose register modules from `com.fasterxml.jackson.databind.Module` SPI by default for `mapper` and `prettyMapper` using `ObjectMapper#findAndRegisterModules` method.

If this proposal makes sence for project maintainers I can make pull requests.

**Comment by vietj** [comment]
Hi,

I would be happy to have such request for visiblity concerns

however I think we should first try to understand how Jackson encourages to json mapper safe publication between threads.

is that something you can investigate @grossws ?

**Comment by grossws** [comment]
IIRC, `ObjectMapper` is effectively thread-safe after all configuration done. In CDI apps it's usually is application scoped which allows safe publication through CDI's synchronization. I'll look into it to recheck that I recall true and share in this ticket.
