### ISSUE TITLE
Make JsonObject and JsonArray extend a common class

### ISSUE THREAD

**Issue by jlprat** [eclipse-vertx/vert.x#1586]
Currently both JsonObject and JsonArray are 2 completely independent classes, but they do share some method signatures. It could be beneficial to make both classes extend some common interface (for example JsonData).
The main shared methods that could belong to this common class are:
- int size()
- String encode()
- String encodePrettily()
- boolean isEmpty();

Adding this hierarchy, could enable users send/receive JsonData objects in/to the EventBus without the need for casting if any of these methods needs to be called.

**Comment by Narigo** [comment]
I remember we had something like this in Vert.x 2 - I expect that this
change was done on purpose. Anyone knows why that was done?

Am 29.08.2016 13:00 schrieb "Josep Prat" <notifications@github.com>:

**Comment by jlprat** [comment]
If it wasn't on purpose, I could do a Pull Request with those changes

**Comment by jan-zajic** [comment]
+1

**Comment by jan-zajic** [comment]
@jlprat @Narigo @purplefox i made PR #1884.
