### ISSUE TITLE
Ignore result on AsyncResult

### ISSUE THREAD

**Issue by aesteve** [eclipse-vertx/vert.x#1654]
Labels : _Enhancement_ , _Question_

Yes, this sounds silly !!

An example should speak by itself : 

``` java
@Override
public void start(Future<Void> future) {
  server.listen(res -> {
    if (res.failed()) {
      future.fail(res.cause());
    } else {
      future.complete();
    }
  });
}
```

Here we can't use `future.completer()` since `listen`'s argument is `Handler<AsyncResult<Integer>>`. But sometimes (and this is the best example I have in mind), the result doesn't matter, what matters is "did it succeed or not ?".

What would be the best way to implement it in your opinion ?

1/ `Future.completeWithNoResult()`

Implementation

``` java
public interface Future<T> {
  // ...
  public Handler<AsyncResult<Void>> completeWithNoResult() {
    return ar -> {
      if (ar.succeeded()) {
        complete(); // or complete(null);
      } else {
        fail(ar.cause());
      }
    };
  }
}
```

Usage : 

``` java
server.listen(future.completeWithNoResult());
```

2/ `AsyncResult.withoutResult`

Implementation

``` java
public interface AsyncResult<T> {
  public AsyncResult<Void> ignoreResult() {
   // depends on the implementation ? 
  }
}
```

Usage :  ??? (not sure it's accurate on this use-case)

3/ Static utility method : `???.ignoringResult`

Implementation

``` java
interface Utils {
  static Handler<AsyncResult<?>> ignoringResult(Handler<AsyncResult<Void>> handler) {
    return ar -> {
      if (ar.succeeded()) {
        handler.handle(Future.succeededFuture());
      } else {
        handler.handle(ar);
      }
    };
  }
}
```

Usage : 

``` java
server.listen(ignoringResult(future.completer()));
```

**Comment by tsegismont** [comment]
This would work:

  @Override
  public void start(Future<Void> startFuture) throws Exception {
    server = getVertx().createHttpServer(new
HttpServerOptions().setPort(8080)).requestHandler(request -> {
      request.response().end("Hi!");
    });
    Future<HttpServer> listenFuture = Future.future();
    server.listen(listenFuture.completer());
    listenFuture.<Void>map(httpServer ->
null).setHandler(startFuture.completer());
  }



2016-09-28 13:16 GMT+02:00 Arnaud Esteve <notifications@github.com>:

**Comment by aesteve** [comment]
Thanks for the tip !!

But could it be possible to add it as first-level Vert.x support ?

Maybe another suggestion : 

```java
public interface Future<T> {
  public<R> Handler<AsyncResult<R>> completer(Function<R, T> mapper) {
    return ar -> {
      if (ar.failed()) {
        fail(ar.cause());
      } else {
        complete(mapper.apply(ar.result());
      }
    }
  }
}
```

So that we can call directly : 

```java
server.listen(future.<Void>completer(server -> null));
```

as a shorthand ? I guess the `complete` + `map` pattern can be a quite interesting sugar addition.

**Comment by aesteve** [comment]
This would work, too (inspired by your implementation) :

```java
  default Handler<AsyncResult<Void>> completerNoResult() {
    return this.<Void>map(res -> null).completer();
  }
```

**Comment by aesteve** [comment]
Maybe : 

```java
startFuture.<HttpServer>map(s -> null).completer()
```

works, too ? (and avoids the `setHandler` boilerplate)

**Comment by tsegismont** [comment]
@vietj wdyt?

2016-10-06 8:56 GMT+02:00 Arnaud Esteve <notifications@github.com>:

**Comment by vietj** [comment]
what is the exact problem you are trying to solve here ?

**Comment by aesteve** [comment]
Sometimes you don't want to do something with the result but just want to check the completion or failure. 

This means you want to use Future<Void> as a replacement for any other kind of future. 

The most obvious example is the one I presented in the first message i.e.

**Comment by vietj** [comment]
and what do you do with this result ?

**Comment by aesteve** [comment]
Nothing... @vietj isn't the example with `server.listen` clear enough ?

If you're using a third party library, you're dependant on the contract of the library's designer.

Imagine a REST API, mapped onto a Storage service (say Mongo, ...), the `insert` method will probably return the inserted document.

Some REST implementations will return the id of the inserted document, thus "will do something with the result". Some REST implementations will simply return HTTP 204.

I'm not saying this is crucial, at all. But I don't understand what is unclear to you. `server.listen`within a Verticle sounds like a crystal clear example to me.

**Comment by vietj** [comment]
this has become irrelevant with vertx 4
