### ISSUE TITLE
LocalEventBus for sending thread-safe references implementing Sharable

### ISSUE THREAD

**Issue by ghost** [eclipse-vertx/vert.x#1663]
First of - I'm am more than willing to code this myself through a pull-request. Question is only: has this been already discussed to death? Would there be any demand? Would this be in-line with your design?

Justification: Sending huge immutable/threadsafe objects over the EventBus is currently an unnecessary chore, both for the programmer himself, and the server (potentially introducing many irrelevant de/encodings and allocations). Simply allowing the programmer to declare "I hereby solemnly swear I know what I'm doing" by implementing a mixin interface, and enabling him/her to explicitly pass such a reference on a LocalEventBus (or predefined channel of the "normal" EventBus) would vanish the issue.

There already exists a LocalMap that accomplishes virtually the same effect, arguably in a much less "vertexy" way, resulting in less elegant APIs. So no new risks would be introduced, and due to the "opt-in" nature the programmer would have only himself to blame if hell freezes over ;)

**Comment by vietj** [comment]
you mean that you would implement a Shareable message codec that is returned by CodecManager when an object implements this interface ?

makes sense to me: simple and does the job.

**Comment by silmeth** [comment]
Wouldn’t it also require, as indicated in the issue’s title, implementation of a new `LocalEventBus`, as `EventBus` can be shared in a cluster or between the server and a frontend js application? Sending a reference to a local object on a jvm’s heap makes sense only between threads of the same jvm process (and I believe that’s why `Shareable` let’s you put an object on a `LocalMap`, and not on a `clusterWideMap`.

**Comment by zardii** [comment]
Well - in other words, wouldn't this require some form of segregation to ensure this kind of behavior ootb is available only on the same machine? Or are we missing something crucial here?

**Comment by vietj** [comment]
a shareable MessageCodec would do nothing on `transform()` and make a lookup in defaultCodecMap on `encodeToWire`

**Comment by tsegismont** [comment]
Closing as won't fix. A solution could be to use a default selector https://github.com/eclipse-vertx/vert.x/issues/4365
