### ISSUE TITLE
Support UNIX Domain Sockets in HttpClient

### ISSUE THREAD

**Issue by InfoSec812** [eclipse-vertx/vert.x#1674]
Netty already supports DomainSockets/DomainChannels, so I was hoping it might be possible to implement support (via HttpOptions/SocketOptions) to support UNIX Domain sockets (AF_UNIX)??? We do this quite often for secured APIs across docker containers. We mount the socket file as a volume in the container and then the different applications communicate via the UNIX Domain socket. We have also taken to communicating with the Docker daemon itself in this manner instead of exposing the Docker HTTP API.

My suggestion for implementation would be one of the following:

Add an overloaded method for Vertx.create(Net/Http)(Client/Server) which could take a "Path" object to point to the location for the UNIX domain socket..

Add logic to the Net/HTTP Client/Server implementations to parse a URL of the format "unix+http://" or "unix+socket://"

Probably many more questions to be answered, but that should be a good start.

**Comment by vietj** [comment]
@InfoSec812 where is this unix+http:// format described ?

**Comment by vietj** [comment]
I actually talked about this last week with someone because of the docker client use case

**Comment by vietj** [comment]
see https://github.com/vert-x3/issues/issues/188 also

**Comment by vietj** [comment]
ah but it's you :-)

so it's expected to be discussed at F2F meeting next week, is that something you could contribute ?

**Comment by vietj** [comment]
and I told you to open an issue here :-)

**Comment by vietj** [comment]
see also https://github.com/eclipse/vert.x/pull/1388

**Comment by InfoSec812** [comment]
@vietj The format I was conceptualizing was the same one used by Twisted (The Python NIO framework). It is described [HERE](http://twistedmatrix.com/documents/13.1.0/core/howto/endpoints.html#auto9) under Server endpoint types.

**Comment by InfoSec812** [comment]
@vietj Is the F2F meeting going to be on-line via something Google Hangout? I'd be happy to attend depending on the timing.

**Comment by vietj** [comment]
@InfoSec812 we will for sure take minutes and make slides available, can't promise for hangout

**Comment by samart** [comment]
https://docs.docker.com/engine/reference/api/docker_remote_api/

thats my use case for this.

**Comment by vietj** [comment]
@samart yes that's a very valid use case

**Comment by samart** [comment]
@vietj , we plan to look at implementations like  https://github.com/gesellix/unix-socket-factory with apache http client :( until something emerges natively for vert.x http client

**Comment by vietj** [comment]
note that you can workaround using docker registry via socket domains with proper configuration.

**Comment by samart** [comment]
You mean http?  Yes, but trying to avoid exposing http for our docker daemons as it's a security and certificate mgmt. issue.   Also, don't want to muck w/iptables to effect local access only, hence the domain socket preference.  Other option is to write this service in golang, but trying to stay w/vert.x for now.

**Comment by InfoSec812** [comment]
https://netty.io/4.0/api/io/netty/channel/unix/package-summary.html

**Comment by dhimandeepak** [comment]
Any plans on adding this support in vert.x http client?

**Comment by vietj** [comment]
we might support epoll for 3.5

**Comment by vietj** [comment]
Domain socket support will be provided by https://github.com/eclipse/vert.x/issues/2135, I will rename this issue so it only scopes HTTP server and client

**Comment by vietj** [comment]
http server supports it

**Comment by jamesdbloom** [comment]
Is there any update on this?

**Comment by vietj** [comment]
not yet but it is still a, important feature. I've done some experiments locally and it might be back-portable to 3.x
