### ISSUE TITLE
Request: Make the ending of the response in HttpServerRespone.sendFile() optional

### ISSUE THREAD

**Issue by xkr47** [eclipse-vertx/vert.x#1719]
Would you see any problems in extending HttpServerResponse.sendFile() with a flag `boolean autoEnd` or similar that would allow one to do:

```java
response.sendFile("file", false, (t) -> {
    if (t == null) {
        response.end("\r\nThis file was brought to you by vert.x");
    }
});
```
? One would naturally have to take care of setting the `Content-Length` header oneself in this case.

Right now, sendFile() automatically ends the response and trying to write anything in the callback (rightfully) throws an exception.

**Comment by tsegismont** [comment]
You could create an AsyncFile with Vert.x FS and then pump the content to
HttpResponse. When it's done, add your special line and end the response.

2016-11-16 15:54 GMT+01:00 Jonas Berlin <notifications@github.com>:

**Comment by xkr47** [comment]
Definately. But I'm looking on how to improve vertx-web/StaticHandlerImpl and vert.x in general of course. Based on the naming of the method `sendFile` it sounds like it's using the operating system sendfile implementation when available, thus decreasing cpu usage. Afaik in Linux, sendfile(2) does not implicate closing of the involved file descriptors, so it should be possible to get performance benefits at least in this case.

**Comment by xkr47** [comment]
I do agree that ending the response is a sensible default of course.

**Comment by xkr47** [comment]
Sorry
