### ISSUE TITLE
Socket idle-closed in middle of slowly progressing sendFile() response

### ISSUE THREAD

**Issue by xkr47** [eclipse-vertx/vert.x#1720]
I tried streaming music to a music player from vertx using `sendFile()`, but the connection is closed after the time given idleTimeout (I have 60 seconds) set in HttpServerOptions has passed after the request started.

I tracked the socket closing down and it seems this triggers the closing:
`channelIdle(ctx, event);` in `io.netty.handler.timeout.IdleStateHandler.AllIdleTimeoutTask`. I guess some other piece of code forgets to mark the connection "busy" while sendFile is active..

vert.x 3.3.3, netty 4.1.1.Final

**Comment by vietj** [comment]
can you run wireshark to monitor the TCP activity over the wire ?

it could be also that lot of data is sent to the client at once and it buffers more than 60 seconds of music and then the buffer is full which cause no data to be sent.

**Comment by xkr47** [comment]
Ok wireshark showed a lot of data at the beginning and then got throttled by "tcp window full" but kept sending packets of 65kB (local TCP connections allows big packets) every 3.5 seconds or so. Fits the ~140kbit/s quality of the music. At 60.015 seconds after response was sent I got a ClosedChannelException to the sendFile result handler. The data kept flowing though on wireshark. At 290.893 seconds the FIN flag was finally raised in a packet sent from the server and data flow stopped. Finally at 341.009 the buffer was empty in the music player and the client responded with FIN, completing the closure of the connection.

So I did a new test. I created a 120G sparse file using the command `truncate -s 120000000000 zero`. I'm testing on the same machine, so throughput is about 1GB/s so 120G is enough for >100 seconds, well above the 60 seconds idle timeout.

I then ran wget against the url serving that file, downloading at maximum speed all the time. Here's the result:

```
--2016-11-20 19:21:17--  http://localhost:8200/zero
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8200... connected.
HTTP request sent, awaiting response... 200 OK
Length: 120000000000 (112G) [application/octet-stream]
Saving to: ‘/dev/null’

/dev/null            70%[=============>      ]  78.56G  1.09GB/s    in 79s     

2016-11-20 19:22:36 (1023 MB/s) - Connection closed at byte 84356054245. Retrying.
```

So the connection still breaks even when sending at full speed.

For reference, the documentation of `idleTimeout` is:

> Set the idle timeout, in seconds. zero means don't timeout. This determines if a connection will timeout and be closed if no data is received within the timeout.

If the Linux sendfile syscall is used to send the file (I didn't manage to find out), then it means that it's not actually possible to monitor whether there is activity on the socket or not in software since the operating system is transfering the whole file in a single call.

I don't know if the bug is in vertx or in netty but the idle timeout originated from netty. If either is indeed using syscalls for the transfer then I guess the idle timeout should be disabled for the time of the syscall..

So I wrote a workaround to use AsyncFile + pump instead -- speed dropped to 300MB/s but no more idle problems..

**Comment by xkr47** [comment]
Another workaround would be to disable the idle timeout and track the idle state myself, then I could still use sendFile..

**Comment by vietj** [comment]
can you provide a reproducer for this case, so one can have a look at it ?

**Comment by xkr47** [comment]
@vietj sure, here you go: https://github.com/xkr47/vertx-i1720

**Comment by xkr47** [comment]
This method is apparently used for implementing sendFile by netty: `java.nio.channels.FileChannel.transferTo(...,  socket);` which in the implementation calls a native function with the filedescriptor of the socket, so highly probable that it uses the sendfile operating system call.

**Comment by vietj** [comment]
yes indeed you are right

**Comment by sandipsahoo2k2** [comment]
So any solutions ? I am also facing similar issue

**Comment by vietj** [comment]
someone needs to investigate it!
