### ISSUE TITLE
Add new CLI arg to support external JSON VertxOptions

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vert.x#1729]
When starting Vert.x applications with the CLI, you can't point to a JSON file for `VertxOptions`. This would be useful for users who need to set nested options (e.g, setting custom HTTP headers in Hawkular metrics options).

The launchers classes support a few nested objects, but not deeply nested ones.

As a workaround, Java/Groovy developers packaging apps in fat jars may extend the `Launcher` class and implement `io.vertx.core.impl.launcher.VertxLifecycleHooks#beforeStartingVertx`.

**Comment by stream1984** [comment]
+1

2016年12月1日 +0800 PM11:06 Thomas Segismont <notifications@github.com>，写道：

**Comment by cescoffier** [comment]
+1, I can have a look, it's easy to add to the launcher.

**Comment by tsegismont** [comment]
We need to be careful with the command line arguments interaction.
Currently, after #beforeStartingVertx method is called, the command code
can override user settings.

2016-12-05 8:51 GMT+01:00 Clement Escoffier <notifications@github.com>:
