### ISSUE TITLE
Traffic shaping support

### ISSUE THREAD

**Issue by tomasBriza** [eclipse-vertx/vert.x#1749]
Is there any support for traffic shaping (global or per urls)? For my needs would be enough to some how set netty GlobalTrafficShapingHandler, but I'm not able to find any way how to do it.

Thanks

**Comment by vietj** [comment]
Hi, this is currently not supported we could expose the netty pipeline setup though to allow such usage

**Comment by tomasBriza** [comment]
Hi, thanks for your quick response, yes exposed pipeline setup will solve my problem!

**Comment by vietj** [comment]
I think we have cases like this, for example there is a PR about setting up ha-proxy support for HTTP that could probably fit this way and proxy support could be also related to that

**Comment by dineshjoshi** [comment]
@vietj I know this is an old issue. If I'd like to make a contribution should I make a PR against v3.8.5 as I don't think 4.0 is out yet.

**Comment by vietj** [comment]
@dineshjoshi you are welcome to give a try

**Comment by vietj** [comment]
cleanup
