### ISSUE TITLE
EventBus interceptors should be able to intercept on both send and receipt

### ISSUE THREAD

**Issue by emmanuelidi** [eclipse-vertx/vert.x#1783]
Currently, the eventbus interceptor can only inspect and transform messages on send. The interceptor does not have the ability to perform complementary operations on message delivery. 

A use-case would be for distributed tracing technologies where tracing of intra-cluster communication is the goal. One would want to "start" a trace on message send and "close" the trace on delivery (or, perform further trace-state management if a response is expected).

PR forthcoming.

**Comment by MazizEsa** [comment]
Not yet merge to master?

**Comment by vietj** [comment]
it needs some rework but it could eventually be

**Comment by MazizEsa** [comment]
@vietj Another thing, is there anyway as a workaround to achieve this so far? @emmanuelidi too.

**Comment by vietj** [comment]
what is your use case ?

**Comment by MazizEsa** [comment]
I have a case where when the message passby to the event bus, it must be validated and checked before being published to other subscriber. After an approval process, we will publish those message to the subscribers.

**Comment by vietj** [comment]
in your case I think you should create a MessageProducer that wraps the EventBus MessageProducer and performs this validation.

**Comment by MazizEsa** [comment]
Just to clarify, will this work if the message comes from bridged sockjs server? We plan to intercept and stop it from publishing when the message come in.

**Comment by vietj** [comment]
yes I think it should

**Comment by DrJonnie** [comment]
Hi, any progress on this this? It would be really awesome. In my current project i would
like to use this feature to transparently propagate a tenant identification between event loop contexts.

**Comment by emmanuelidi** [comment]
I've stopped using Vert.x so, unfortunately, the window of time for me to work on this has come and gone

**Comment by vietj** [comment]
@DrJonnie here is a PR that rebases @emmanuelidi contribution with some lifting https://github.com/eclipse-vertx/vert.x/pull/2632 it shall be in 3.6
