### ISSUE TITLE
Add support for BigInteger/BigDecimal in JsonObject

### ISSUE THREAD

**Issue by jvz** [eclipse-vertx/vert.x#1919]
My primary use case here is that the default way that Jackson serializes/deserializes `java.time.Instant` is as a `BigDecimal` for the seconds since epoch plus nanos (or whatever the most accurate clock time it can convert to). Thus, when I try to use `JsonObject` normally, I can't deserialize what was serialized before without disabling the timestamp as nanos options in Jackson ahead of time.

Adding a gamut of methods like `getBigInteger(String)` et al. would be useful, too, but I think this would be more appropriately implemented via better dynamic conversion so that, for example, calling `json.getBigDecimal("foo")` would still work if the `foo` field was stored as a `Double` instead. Similarly, calling `json.getDouble("foo")` would likely call `Number::doubleValue` or similar to do an auto conversion.

**Comment by pmlopes** [comment]
@jvz if you're using `JsonObject` to serialize `java.time.Instant` then you'll get a `ISO 8601` String as per `RFC-7493` and vert.x implementation.

**Comment by jvz** [comment]
The default setting in Jackson is to output as a BigDecimal, and that setting is not overridden by vert.x.

**Comment by pmlopes** [comment]
@jvz you referred to `JsonObject` in this class java.time.Instant will be encoded to an `ISO` date:

http://vertx.io/docs/apidocs/io/vertx/core/json/JsonObject.html#getInstant-java.lang.String-
http://vertx.io/docs/apidocs/io/vertx/core/json/JsonObject.html#put-java.lang.String-java.time.Instant-

**Comment by jvz** [comment]
I think the issue was when I had my own DTO class which I marshalled and unmarshalled through `JsonObject.mapFrom()` and `JsonObject.mapTo()` since I was using Java in these verticles.
