### ISSUE TITLE
Enable `permessage-deflate` and `deflate-frame` compression on WebSockets

### ISSUE THREAD

**Issue by silmeth** [eclipse-vertx/vert.x#2010]
Enabling compression on WebSockets is a very desirable feature for applications with a lot of repetitive data over WS. And modern browsers support WS compression.

Vert.x uses Netty 4.1 which [has support for `permessage-deflate` and `deflate-frame` compression extensions](http://netty.io/4.1/api/io/netty/handler/codec/http/websocketx/extensions/compression/package-summary.html) for WebSockets for its WS implementation, yet Vert.x does not give one any mean to enable them (or at least I haven’t seen a way to do it).

Is Vert.x using Netty’s implementation of WebSocket, or does it make its own implementation? Would it be possible to use Netty’s compression extensions?

**Comment by vietj** [comment]
@silmeth Vert.x uses Netty so it could be configured on the Http options

**Comment by silmeth** [comment]
On which Http options? I see no related things on [HttpServerOptiona](http://vertx.io/docs/apidocs/io/vertx/core/http/HttpServerOptions.html), and I have no idea where else should I search.

There are no `WebSocketServerOptions` in Vertx, and simple enabling compression on `HttpServer` in Vertx does not switch WebSocket compression on.

**Comment by silmeth** [comment]
Also, I’ve asked about [enabling WebSocket compression on StackOverflow](https://stackoverflow.com/questions/42697411/websocket-compression-in-vert-x), unfortunately got no answer there either.

**Comment by vietj** [comment]
you can add it on HttpServerOptions and HttpClientOptions

**Comment by silmeth** [comment]
Can you show me how exactly can I do that?

**Comment by pvub** [comment]
@silmeth @vietj I have a vert.x based websocket server which will need an ability to enable 'permessage-deflate' on both the Client and Server HttpClient. Is there a change that addressed this? I didn't see the changes from https://github.com/eclipse/vert.x/pull/2045 didn't get merged into master yet. Is there any other way I can enable 'permessage-deflate'?

**Comment by silmeth** [comment]
@pvub After looking through linked PR and later ones (that one wasn’t merged because of agreement signing problems), it seems this feature will finally land in 3.5.1. See PR #2165. Yay!

**Comment by silmeth** [comment]
Updating: according to #2165 it did not land in 3.5.1 and is planned for 3.6.0. Not so yay. Well, waiting for 3.6.0…

**Comment by vietj** [comment]
yes unfortunately it missed it

**Comment by silmeth** [comment]
Seems this has been resolved in #2546 and is now part of 3.6. Closing.

**Comment by vietj** [comment]
thanks @silmeth
