### ISSUE TITLE
Feature request: Expose netty's SSL Handshake Timeout to the Vertx user

### ISSUE THREAD

**Issue by kpachar** [eclipse-vertx/vert.x#2118]
Hello,
This is a feature request; it will be nice to be able to set the ssl handshake timeout.

Thank you!

https://github.com/eclipse/vert.x/blob/38a19afe50917de3783bdd1512f2314b71cc1750/src/main/java/io/vertx/core/net/impl/NetClientImpl.java#L208

https://netty.io/4.0/api/io/netty/handler/ssl/SslHandler.html#setHandshakeTimeout-long-java.util.concurrent.TimeUnit-

**Comment by tsegismont** [comment]
Isn't there a default timeout? Why isn't sufficient?

2017-09-08 17:17 GMT+02:00 Pradyumna Achar <notifications@github.com>:

**Comment by kpachar** [comment]
@tsegismont Yes, there is a default, but it is insufficient for certain very low bandwidth networks.

**Comment by tsegismont** [comment]
Would you like to contribute the change?

2017-09-10 17:29 GMT+02:00 Pradyumna Achar <notifications@github.com>:

**Comment by vietj** [comment]
I'm wondering if that's not conflicting with the current default idle timeout, i.e the idle timeout set before the handshake could fill the same purpose

**Comment by BillyYccc** [comment]
It looks like that the present idleTimeout implement only can be triggerd by the scenario neither read nor write was performed. https://github.com/eclipse/vert.x/blob/af1c846ea46b499b249c6829c4c32385b3022a23/src/main/java/io/vertx/core/net/impl/NetServerImpl.java#L146
I'm confused how to make idle timeout fill the same purpose as handshake timeout, could you give more specific details?

**Comment by vietj** [comment]
I think actually it's better to differentiate both like you did, so you should not both of idle timeout

**Comment by luengnat** [comment]
@vietj can you target this for 3.6.0?

**Comment by BillyYccc** [comment]
Feel sorry for the delay... Please take a look at https://github.com/eclipse-vertx/vert.x/pull/2714.
