### ISSUE TITLE
WriteStream is missing callback for asynchronous end() completion

### ISSUE THREAD

**Issue by mkulak** [eclipse-vertx/vert.x#2122]
So far [WriteStream](/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/streams/WriteStream.java#L61) has only  synchronous 'end()` methods:
```
 void end();
 void end(T t) {
```
I.e. after I called `end()` it is safe to assume that stream is actually closed.

This means that [AsyncFile](/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/file/impl/AsyncFileImpl.java#L122) cannot properly implement this interface cause in order to end asyncfile's writestream you need to close file, which is asynchronous operation. This causes troubles when you download url to file and try to use file immediately after receiving download completion callback: [web-client #691](/vert-x3/vertx-web/issues/691) 
 
**Suggestion:**
1. Add method `void end(Handler<AsyncResult<Void>> handler)` to `WriteStream` interface (with default implementation to not break existing code).
2. Make AsyncFile use this method for asynchronously closing underlying file.

This will open a way to actually fix problem with web-client (by enabling `StreamingBodyCodec` to wait for actual `end()` completion event.

I made aforementioned changes locally. Can open a PR. Need a comment from maintainers whether it's a proper fix or I am missing something.

**Comment by vietj** [comment]
`end()` is asynchronous, it's just that we don't provide a notification when the `end()` has been processed.
