### ISSUE TITLE
Feature: Support merging VertxOptions instances

### ISSUE THREAD

**Issue by sfitts** [eclipse-vertx/vert.x#2203]
The Launcher method `beforeStartingVertx` gives you an opportunity to modify the supplied VertxOptions instance, but this must be done by modifying the provided `options` instance directly.  In our Launcher extension we read "override" options from a JSON file and it would be nice to have an easy way to override the existing options settings with the contents of the JSON file.

We used to do this using `VertxOptionsConverter.fromJson`, but that class is now package private, so that doesn't work anymore.  There are constructors on VertxOptions that allow for the overlay of either JSON or another VertxOptions instance, but those don't work for overlaying an existing instance.

Something along the lines of `fromJson` or `fromOptions` as instance methods on VertxOptions would be great.

**Comment by vietj** [comment]
we can eventually make the converter public again to not get in your way, but those are subject to change (i.e not part of public API)

**Comment by sfitts** [comment]
Understood.  Given the way the launcher currently works it seems that having an instance level "override" method on VertxOptions would be a nice addition to the API (at some point).  For now I just created a cover class in the correct package to work around the visibility issue.

**Comment by tsegismont** [comment]
@sfitts I just pushed a PR which allows to provide an external Vert.x options file (#2673)

Can you take a look? It should solve your problem and we can close this issue.

**Comment by sfitts** [comment]
@tsegismont Thanks.  I took a look and while it looks good we wouldn't be able to use it for our purposes.

When I said we load the options from a file I was... simplifying things a bit.  What we actually do is have a search path which includes both a resource embedded in our server's JAR and an override directory on disk.  Files found in these locations are merged to produce the final result (which is a JsonObject, we're using `mergeIn` to help with this).

So here we'd have to perform our loading and merging and then we'd have to convert that back to a string to pass to `setVertxOptions`.  Certainly possible, but seems easier to keep the `beforeStartingVertx`.  Especially given that our Launcher has to do a few other things as well, so getting rid of that override doesn't get rid of the Launcher.  Of course if we completely lose the options converter class then that's what we'll do.

That said, I agree that it solves the basic version of this issue, so feel free to close it.

**Comment by tsegismont** [comment]
@sfitts thanks for the feedback. Indeed, your use case sounds like a more advanced one and justifies creating your own `Launcher`
