### ISSUE TITLE
the MulticastReciver doesn't work for Udp under some configurations

### ISSUE THREAD

**Issue by zhhkof** [eclipse-vertx/vert.x#2206]
I type the code refer to the web http://vertx.io/docs/vertx-core/java/#_multicast , but when I sent the data buffer to 230.0.0.1 for a test, the MulticastReciver's handler doesn't print the data string.
the Sender class code:
```java
public class McS {
    public static void main(String[] args) throws UnknownHostException, SocketException {
        DatagramSocket socket = Vertx.vertx().createDatagramSocket(new DatagramSocketOptions().setReuseAddress(true).setMulticastNetworkInterface(NetworkInterface.getByInetAddress(InetAddress.getByName("192.168.16.4")).getName()));
        Buffer buffer = Buffer.buffer("content");
        socket.send(buffer, 1234, "230.0.0.1", asyncResult -> {
            System.out.println("Send succeeded? " + asyncResult.succeeded());
        });
    }
}
```
the Receiver class code:
```java
public class Mc {
    public static void main(String[] args) throws UnknownHostException, SocketException {
        DatagramSocket socket = Vertx.vertx().createDatagramSocket(new DatagramSocketOptions().setReusePort(true).setReuseAddress(true).setMulticastNetworkInterface(NetworkInterface.getByInetAddress(InetAddress.getByName("192.168.16.4")).getName()));
        socket.listen(1234, "192.168.16.4", asyncResult -> {
            if (asyncResult.succeeded()) {
                // join the multicast group
                socket.listenMulticastGroup("230.0.0.1", asyncResult2 -> {
                    System.out.println("Listen succeeded? " + asyncResult2.succeeded());
                });
                socket.handler(packet -> {
                    // Do something with the packet
                    System.out.println("mul+:"+packet.data().toString());
                });
            } else {
                System.out.println("Listen failed" + asyncResult.cause());
            }
        });
    }
}
```

**Comment by vietj** [comment]
can you run the Vert.x Core DatagramTest on your machine ? specially the testMulticastJoinLeave test

**Comment by zhhkof** [comment]
@vietj Thanks for your response，and I have run the the Vert.x Core DatagramTest. testMulticastJoinLeave on my Mac and Win7 machines both.

for win7, jdk1.8_131, when I run the test method with default  hostIp of listen(..) 0.0.0.0, the result was failed. if I change it to 127.0.0.1 will be ok.

for Mac, yesterday I ran the code with jdk1.8_60. today I update it to 1.8_151. When the hostIp of listen(..) is 0.0.0.0 and the IFace'ip is my machine's LAN IP, it can receive the multicast packet. But when I set the hostIp to the LAN IP just like 192.168.5.6, the same with IFace'ip, the receiver cannot get multicast packets anymore.

The following is assertError log:
[listen(use localip)-multicastReciveAssert-masOS10.13.1-jdk8_151.log.zip](https://github.com/eclipse/vert.x/files/1473382/listen.use.localip.-multicastReciveAssert-masOS10.13.1-jdk8_151.log.zip)
[win7-listen(0.0.0.0)-jdk1.8_131.log.zip](https://github.com/eclipse/vert.x/files/1473383/win7-listen.0.0.0.0.-jdk1.8_131.log.zip)

**Comment by vietj** [comment]
@zhhkof I'm not able also to make it work on my machine (OSX), but if I do the same in Java I get the same result, so I think it's not Vert.x specific

**Comment by ViToni** [comment]
@zhhkof The behaviour for MacOS X might be due the default (non-)routing of multicast. Might want to try this and then check again:
http://www.thomasqvarnstrom.com/2015/06/multicasting-routing-on-mac.html

**Comment by vietj** [comment]
@zhhkof thanks for the info

**Comment by ejatx231** [comment]
So bank in at my account bank...

On Dec 22, 2017 6:23 AM, "Julien Viet" <notifications@github.com> wrote:

@zhhkof <https://github.com/zhhkof> thanks for the info

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/eclipse/vert.x/issues/2206#issuecomment-353472821>, or mute
the thread

**Comment by elliotvargas** [comment]
I'm currently using Vertx 3.9.2 and I'm seeing exactly the same problem. When I bind the datagram socket to any address besides 0.0.0.0 the multicast messages don't come through. If I send unicast UDP it works.

**Comment by QingMings** [comment]
> I'm currently using Vertx 3.9.2 and I'm seeing exactly the same problem. When I bind the datagram socket to any address besides 0.0.0.0 the multicast messages don't come through. If I send unicast UDP it works.

 I'm using Vertx 3.9.2 and same problem on  mac ,

**Comment by vietj** [comment]
see https://github.com/eclipse-vertx/vert.x/issues/3540
