### ISSUE TITLE
Improve host address resolution

### ISSUE THREAD

**Issue by ncoolz** [eclipse-vertx/vert.x#2254]
DnsResolverProvider loads hosts file when only in [constructor](https://github.com/eclipse/vert.x/blob/3.4.2/src/main/java/io/vertx/core/impl/resolver/DnsResolverProvider.java#L99) of DnsResolverProvider. The problem is that when hosts file is modified, vertx does not recognize it because of no load of hosts file(except in the constructor).

I think there is no way to dynamically load it again while vertx is running. Is there any way to solve it?

**Comment by vietj** [comment]
not at the moment, I think we could have something for this

**Comment by vietj** [comment]
I think we should allow to set directly a DnsResolverProvider on the Vertx options and provide this option directly on the provider

**Comment by vietj** [comment]
Changed this to a more general issue.

We want also to perform Round Robin DNS load balancing on the client when it returns multiple addresses (https://www.digitalocean.com/community/tutorials/how-to-configure-dns-round-robin-load-balancing-for-high-availability)

**Comment by yurgisbaykshtis** [comment]
PR to enable round robin dns load balancing option: https://github.com/eclipse-vertx/vert.x/pull/2902

**Comment by tsegismont** [comment]
Closing this one for now. We will implement DNS load balancing only in 3.9.6 (see #3821)
