### ISSUE TITLE
peerCertificateChain() should return java.security.cert.X509Certificate

### ISSUE THREAD

**Issue by luengnat** [eclipse-vertx/vert.x#2320]
peerCertificateChain() should return ```java.security.cert.X509Certificate``` instead of  ```javax.security.cert.X509Certificate```.  ```javax.security.cert.X509Certificate``` is supposed to be deprecated.  (https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLSession.html#getPeerCertificateChain())

**Comment by vietj** [comment]
which class are you referring to ?

**Comment by luengnat** [comment]
HttpServerRequest.peerCertificateChain()

**Comment by vietj** [comment]
which class should it return instead of `javax.security.cert.X509Certificate`, because what you said above does not make sense yet

**Comment by luengnat** [comment]
It should return ```java.security.cert.X509Certificate``` Look at ```SSLSession.getPeerCertificates()```. It is a replacement for ```SSLSession.getPeerCertificateChain()```.

**Comment by vietj** [comment]
`SSLSession.getPeerCertificateChain()` uses the `java.security.cert.Certificate` type and not `java.security.cert.X509Certificate` (although internally it seems those are stored as `java.security.cert.X509Certificate`).

that being said you can get the `SSLSession` from `HttpConnection` and use either method.

I would rather in the future remove these methods in favor of using the `SSLSession`

**Comment by vietj** [comment]
yes this is the class taht should be used, this method could change in 4.0, I will keep this issue and scope it to 4.0
