### ISSUE TITLE
No access to peerCertificateChain on the client side

### ISSUE THREAD

**Issue by luengnat** [eclipse-vertx/vert.x#2321]
-  ```response.netSocket().peerCertificateChain()``` will just make HTTPS stop working correctly
- ```request.connection().peerCertificateChain()``` works but it is not intuitive as you need to gain access to request.connection() where on the server side, you can just do ```request.peerCertificateChain()```

**Comment by vietj** [comment]
can you provide a reproducer ? note that now you can get the `SSLSession` from the connection

**Comment by vietj** [comment]
`response.netSocket()` transforms the current http connection into a `NetSocket` (for instance after an HTTP CONNECT), so you should really use `request.connection().peerCertificateChain()`

**Comment by vietj** [comment]
I think we can also add the `peerCertificateChain()` method on `HttpClientResponse` as well to make it more obvious
