### ISSUE TITLE
Investigate client getting callbacks on the GlobalEventExecutor instead of the event loop thread

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#2324]
```
WARN  io.netty.util.concurrent.DefaultPromise - An exception was thrown by io.vertx.core.net.impl.ChannelProvider$$Lambda$219/1676533407.operationComplete()
java.lang.IllegalStateException: Uh oh! Event loop context executing with wrong thread! Expected null got Thread[globalEventExecutor-1-78,5,main]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:193)
	at io.vertx.core.http.impl.ConnectionManager$ConnQueue.connectionFailed(ConnectionManager.java:362)
	at io.vertx.core.http.impl.ConnectionManager$ConnQueue.access$1900(ConnectionManager.java:194)
	at io.vertx.core.http.impl.ConnectionManager$ChannelConnector.lambda$connect$2(ConnectionManager.java:528)
	at io.vertx.core.net.impl.ChannelProvider.lambda$connect$0(ChannelProvider.java:42)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:34)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:431)
	at io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run(GlobalEventExecutor.java:233)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vietj** [comment]
note this might not happen with Vert.x HttpClient in 3.5.1 as the connection manager has been partly rewritten.

**Comment by vietj** [comment]
also happens from MQTT:

```
10:21:41.572 [globalEventExecutor-1-7] WARN  i.n.util.concurrent.DefaultPromise - An exception was thrown by io.vertx.core.net.impl.ChannelProvider$$Lambda$152/1354547765.operationComplete()
java.lang.IllegalStateException: Uh oh! Event loop context executing with wrong thread! Expected null got Thread[globalEventExecutor-1-7,5,main]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:323)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:200)
	at io.vertx.core.net.impl.NetClientImpl.failed(NetClientImpl.java:269)
	at io.vertx.core.net.impl.NetClientImpl.lambda$doConnect$7(NetClientImpl.java:230)
	at io.vertx.core.net.impl.ChannelProvider.lambda$connect$0(ChannelProvider.java:43)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:34)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:431)
	at io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run(GlobalEventExecutor.java:233)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

see https://github.com/vert-x3/vertx-mqtt/issues/67#issuecomment-357884903

**Comment by vietj** [comment]
this seems to happen from a connection failure and it seems it does not happen consistently

**Comment by vietj** [comment]
I think this is coming from `Boostrap.PendingRegistrationPromise` class:

```
        protected EventExecutor executor() {
            if (registered) {
                // If the registration was a success executor is set.
                //
                // See https://github.com/netty/netty/issues/2586
                return super.executor();
            }
            // The registration failed so we can only use the GlobalEventExecutor as last resort to notify.
            return GlobalEventExecutor.INSTANCE;
        }
```

**Comment by vietj** [comment]
this seems to be fixed in Netty with https://github.com/netty/netty/issues/2586

**Comment by vietj** [comment]
see also https://github.com/netty/netty/issues/2586

**Comment by vietj** [comment]
so this would happen when an exception happens in `abstract void init(Channel channel) throws Exception;`

at this moment the promise is resolved with the global executor.

**Comment by vietj** [comment]
Actually I rather suspect `AbstractBoostrap#initAndRegister()` that is called from Bootstrap and potentially returns a promise using the gobal event executor:

```
            // as the Channel is not registered yet we need to force the usage of the GlobalEventExecutor
            return new DefaultChannelPromise(channel, GlobalEventExecutor.INSTANCE).setFailure(t);
```

**Comment by morganmcc** [comment]
Is there a way to work around this? I have encountered this with a coroutine Verticle that acts as a STOMP client.

**Comment by vietj** [comment]
do you have a reproducer @morganmcc ?

**Comment by vietj** [comment]
thanks

**Comment by morganmcc** [comment]
Sorry for the delay. Here is a paired-down version of the Verticle we are using for doing testing of a STOMP server (metrics, config stuff, and logic outside of Vertx has been removed). We are running many instances of this on one box to simulate large numbers of clients.  We changed to this co-routine implementation from a more traditional one in order to avoid blocking and potentially get a larger number of simulated clients on one box. I'm kind of new to Vert-x, so I'm wondering if we are doing something wrong, but when running tests we so see that exact resume error. I'm trying to dig out a stack trace.


`package test.harness

import io.vertx.core.Future
import io.vertx.core.Handler
import io.vertx.core.buffer.Buffer
import io.vertx.core.json.JsonObject
import io.vertx.core.logging.LoggerFactory
import io.vertx.ext.stomp.*
import io.vertx.kotlin.coroutines.CoroutineVerticle
import io.vertx.kotlin.coroutines.await
import io.vertx.kotlin.coroutines.dispatcher
import kotlinx.coroutines.experimental.Job
import kotlinx.coroutines.experimental.cancelAndJoin
import kotlinx.coroutines.experimental.channels.Channel
import kotlinx.coroutines.experimental.delay
import kotlinx.coroutines.experimental.launch
import java.util.*
import java.util.concurrent.ThreadLocalRandom
import java.util.concurrent.TimeUnit

fun ClosedRange<Int>.randomVal(rand: Random) = rand.nextInt((endInclusive + 1) - start) + start

data class StompSession(val client: StompClient, val connection: StompClientConnection, val subscribeDestination: String) {
    fun close() {
        if (!client.isClosed) {
            client.close()
        }
        if (connection.isConnected) {
            connection.close()
        }
    }
}

/**
 * This Verticle represents a test STOMP client agent, it will retain the serial number of the agent
 * and continuously monitor its connection and respond to basic requests, and provide
 * a periodic.
 */
class AgentVerticleTest(
    serialNumber: Long
) : Handler<Frame>, CoroutineVerticle() {

    companion object {
        const val NOTIFY_SECONDS: Long = 86400
        const val REBOOT_SECONDS: Long = 86400
        const val NOTIFY_DEST = "notify-destination"
        const val RANDOM_BOOT = true
        const val RETRY_INITIAL: Int = 60
        const val RETRY_MAX: Int = 30720
        const val RETRY_MULTIPLIER: Int = 2000
    }

    private val log = LoggerFactory.getLogger(this.javaClass.simpleName)

    private var channel = Channel<String>()

    private val endpointId = "00D09E-$serialNumber"

    private val clientOptions = StompClientOptions(buildOptions())
        .setLogin(endpointId)
        .setPasscode(endpointId)

    @Volatile
    private var reconnectJob: Job? = null

    @Volatile
    private var periodicJob: Job? = null

    @Volatile
    private var rebootJob: Job? = null

    @Volatile
    var session: StompSession? = null

    /**
     * Start connecting to the USP Controller and keep the connection up. Send me
     */
    override suspend fun start() {
        log.info("Starting - $endpointId")


        // start the connect loop, using a loop and channel here
        // for reconnects and continually checking
        initStompSession()

        if (NOTIFY_SECONDS > 0) {
            periodicJob = launch(vertx.dispatcher()) {
                delay(ThreadLocalRandom.current().nextLong(NOTIFY_SECONDS), TimeUnit.SECONDS)
                while (true) {
                    send(NOTIFY_DEST, "PERIODIC!")
                    delay(NOTIFY_SECONDS, TimeUnit.SECONDS)
                }
            }
        }

        if (REBOOT_SECONDS > 0) {
            rebootJob = launch(vertx.dispatcher()) {
                while (true) {
                    val rebootDelay = when (RANDOM_BOOT) {
                        true -> ThreadLocalRandom.current().nextLong(REBOOT_SECONDS)
                        false -> REBOOT_SECONDS
                    }
                    delay(rebootDelay, TimeUnit.SECONDS)
                    send(NOTIFY_DEST, "REBOOT!")
                }
            }
        }

        reconnectJob = launch(vertx.dispatcher()) {
            var retries = 0
            val minDelay = RETRY_INITIAL
            val maxInterval = RETRY_MAX

            for (msg in channel) {
                when (msg) {
                    Frame.Command.CONNECT.name -> {
                        // When the channel receives a connect message we just try to initialize the STOMP session
                        initStompSession()
                    }
                    Frame.Command.CONNECTED.name -> {
                        // If we successfully connected, we reset the retries
                        retries = 0
                    }
                    else -> {
                        // Otherwise the message on the channel is an error, so we close the session
                        log.error("$endpointId - $msg")
                        session?.close()
                        // Increment the retries counter and retry after a delay using exponential back-off
                        //  This is the same basic algorithm as specified in TR-181 for USP
                        retries++
                        val delay = minDelay * ((RETRY_MULTIPLIER / 1000) shl (retries - 1))
                        val sleepSeconds = minOf(maxInterval, (0..delay).randomVal(ThreadLocalRandom.current()))
                        log.info("$endpointId - Reconnect in $sleepSeconds seconds")
                        delay(sleepSeconds.toLong(), TimeUnit.SECONDS)
                        channel.send(Frame.Command.CONNECT.name)
                    }
                }
            }
        }
    }

    override suspend fun stop() {
        reconnectJob?.cancelAndJoin()
        periodicJob?.cancelAndJoin()
        rebootJob?.cancelAndJoin()
    }

    private suspend fun initStompSession() {
        try {
            session = connect()
        } catch (e: Throwable) {
            launch(vertx.dispatcher()) {
                channel.send(e.message!!)
            }
        }
    }

    private suspend fun connect(): StompSession {
        val client = StompClient.create(this.vertx, this.clientOptions)

        // add our exception handler
        client.exceptionHandler { th ->
            log.error("$endpointId - Failed: $th.message")
            // for every error frame the client will disconnect
            launch(vertx.dispatcher()) {
                channel.send(th.message!!)
            }
        }

        // a little logging in case of error frames for greater visibility
        client.errorFrameHandler { event ->
            log.error("$endpointId - Error Frame detected: $event")
            // for every error frame the client will disconnect
            launch(vertx.dispatcher()) {
                channel.send(event.bodyAsString)
            }
        }

        // add header to indicate the endpointId..
        client.writingFrameHandler { frame ->
            if (Frame.Command.CONNECT == frame.command || Frame.Command.STOMP == frame.command) {
                frame.addHeader("endpoint-id", endpointId)
            }
        }

        // spy the receive frames for connected to get the subscribe-to-dest field
        val f = Future.future<String>()
        client.receivedFrameHandler { frame ->
            // if this is a connected command retrieve the subscribe-to-dest
            if (Frame.Command.CONNECTED == frame.command) {
                f.complete(frame.getHeader("subscribe-dest"))
            }
        }

        log.info("Connecting to Stomp Server: {0}", client.options().login)
        val connectFuture = Future.future<StompClientConnection>()
        client.connect { ar ->
            if (ar.succeeded()) connectFuture.complete(ar.result())
            else connectFuture.fail(ar.cause())
        }

        val connection = connectFuture.await()
        connection.connectionDroppedHandler { _ ->
            log.error("$endpointId - Connection dropped")
            // for every error frame the client will disconnect
            launch(vertx.dispatcher()) {
                channel.send("DROPPED")
            }
        }

        // wait until the connection is complete
        val subscribeTo = f.await()
        // create the subscription
        connection.subscribe(subscribeTo, this)

        launch(vertx.dispatcher()) {
            channel.send(Frame.Command.CONNECTED.name)
        }
        return StompSession(client, connection, subscribeTo)
    }


    /**
     * Parse the record to make sure its valid, then execute the request in a coroutine.
     */
    override fun handle(frame: Frame) {
        // stay out of the event loop
        launch(vertx.dispatcher()) {
            try {
                val replyToDest = frame.getHeader("reply-to-dest")
                val respRecord = execute(frame.bodyAsString)
                send(replyToDest, respRecord)
            } catch (e: Exception) {
                log.error("Failed to process request: ", e.message)
                launch {
                    val errorFrame = Frames.createErrorFrame(
                        e.message,
                        emptyMap(),
                        ""
                    )
                    session?.connection?.disconnect(errorFrame)
                    channel.send(e.message!!)
                }
            }
        }
    }

    private fun send(destination: String, message: String) {
        session?.connection?.send(destination, Buffer.buffer(message.toByteArray()))
    }

    /**
     * Build the response from the request
     */
    private fun execute(req: String): String {
        return when (req) {
            "PING" -> "PONG"
            "HELLO" -> "GOODBYE"
            else -> "FOOBAR"
        }
    }

    private fun buildOptions(): StompClientOptions {
        // determine stop connection settings
        val port = this.config.getInteger("stompPort", 61613)!!
        val host = this.config.getString("stompHost", "127.0.0.1")!!
        val localAddress = config.getString("localAddress", null)

        val tcpKeepAlive = config.getBoolean("tcpKeepAlive", false)!!
        val options = StompClientOptions()
            .setHost(host)
            .setPort(port)
            .setAcceptedVersions(listOf("1.2"))
        // bind to a particular address
        val heartBeatClient = config.getLong("heartbeat", null)
        val heartBeatExpected = config.getLong("heartbeatExpected", null)
        if (null != heartBeatClient && null != heartBeatExpected) {
            options.heartbeat = JsonObject().put("x", heartBeatClient).put("y", heartBeatExpected)
        }
        if (null != localAddress) {
            options.localAddress = localAddress
        }
        options.isTcpKeepAlive = tcpKeepAlive

        return options
    }
}
`
