### ISSUE TITLE
Remove timer callbacks from the metrics SPI

### ISSUE THREAD

**Issue by jotak** [eclipse-vertx/vert.x#2352]
In the upcoming `vertx-micrometer-metrics` module, timer metrics are not implemented. They were not implemented either in the Hawkular module.

If this metric is not relevant / not seen as useful, it should probably be deprecated. The related API methods are:

- `VertxMetrics.timerCreated`
- `VertxMetrics.timerEnded`

As far as I know they're only implemented in `vertx-dropwizard-metrics`

In the opposite way, if it is decided to keep them, we should probably open an issue in `vertx-micrometer-metrics` to implement it.

**Comment by vietj** [comment]
so shouldn't this issue be a question rather than a statement ?

**Comment by vietj** [comment]
also I believe if we do it, we would just remove it and not bother with deprecations

**Comment by jotak** [comment]
@vietj I cannot add labels such as "Question", but yes, it is.

**Comment by tsegismont** [comment]
@vietj I asked @jotak to file this issue. In fact I had asked him to file an issue in `vertx-micrometer-metrics` to remember implementing those metrics... But then he told me you said in a previous review that they were useless and wanted to remove them.

As for deprecation, my understanding during F2F was that we would try to avoid removing right away and deprecate for like, two versions.

**Comment by vietj** [comment]
concerning deprecation : that's SPI, not API, so it's different

**Comment by tsegismont** [comment]
ok so how do we turn this question into a PR? Should we write to the vertx-dev?

**Comment by vietj** [comment]
I think this conversation is fine, prepare a PR for the concerned modules

**Comment by vietj** [comment]
well actually removing them would create a breaking change for dropwizard

**Comment by tsegismont** [comment]
You must be kidding me. You troll 😏

**Comment by vietj** [comment]
no, it's a mistake, I'm sorry for that.

that being said I don't understand the initial motivation for removing it. Is it very complicated to implement or you think it's really useless ?

**Comment by tsegismont** [comment]
It's not complex to implement but you said in a conversation with Joel that they were not useful and we agree. See https://github.com/eclipse/vert.x/issues/2352#issuecomment-375706571

**Comment by vietj** [comment]
yes i would remove it too, but it might cost us more (complaints, justifications) to remove it (breaking change) than keeping it or being a NOOP. we can remove it later.

**Comment by vietj** [comment]
again I'm sorry to have make you spend some time there. just make them noop and open an issue for removing later. so it's kinda deprecated but it's not a user facing API.

**Comment by jotak** [comment]
Maybe we can implement a deprecation mechanism in dropwizard module: disable these metrics by default, but provide a config flag to re-enable it? Or is it an overkill?

**Comment by vietj** [comment]
overkill :-)

**Comment by vietj** [comment]
I think the best thing to do would be to figure out whether people actually uses it or not.

**Comment by tsegismont** [comment]
@jotak, can you drop an email in the vertx forum to:
- explain we'd like to deprecate the SPI callbacks and remove them in a
couple version
- ask if anyone does anything relevant with the derived metric

Thanks

**Comment by tsegismont** [comment]
@jotak I may have missed/deleted it. Have you sent the message to the forum?

**Comment by jotak** [comment]
@tsegismont sorry I didn't see your comment
That was posted 29th of March, 0 answer: https://groups.google.com/forum/?fromgroups#!topic/vertx/zfbbYNINCX0

**Comment by tsegismont** [comment]
@jotak thanks for the heads up. So I guess this means we can go ahead and merge @vietj ?

**Comment by tsegismont** [comment]
So can I go ahead and create the "4.0.0" milestone? :stuck_out_tongue_winking_eye:

**Comment by vietj** [comment]
sure thing

**Comment by tsegismont** [comment]
Done
