### ISSUE TITLE
Json#decodeValue cannot deserialize a JSON null/number/boolean from a Buffer

### ISSUE THREAD

**Issue by GeorgeMH** [eclipse-vertx/vert.x#2361]
### Version

* vert.x core: 3.5.1

### Context

An EOFException is unexpectedly thrown when deserializing a JSON primitive (null, Integer, String) from a vert.x `Buffer`. Unrolling the buffer into a String prior to deserialization works as expected.

### Do you have a reproducer?

* https://github.com/GeorgeMH/vertx-json-eof-bug

### Steps to reproduce

1. Call `Json.encodeToBuffer(42)`
2. Call `Json.decodeValue(buffer, Integer.class)` on the buffer created in step 1.
### Extra

* N/A

**Comment by vietj** [comment]
I can see it, it seems that as the parser does not know the length of the integer then it fails because of EOFExceptinon, but I think the parser should somehow check there are still more bytes to read, so I suspect an issue with Jackson, but that would be a quite gross and obvious issue.

**Comment by vietj** [comment]
the following gives the same:

```
    Json.mapper.readValue((DataInput) new DataInputStream(new ByteArrayInputStream("42".getBytes())), Integer.class);
```

**Comment by vietj** [comment]
I don't understand how jackson can parse numbers from an InputStream...

**Comment by vietj** [comment]
by comparison this works:

```
    Json.mapper.readValue(new ByteArrayInputStream("42".getBytes()), Integer.class);
```

so I think that we should not cast it to a `DataInput`

**Comment by vietj** [comment]
reported here https://github.com/FasterXML/jackson-databind/issues/1985 - I will fix it by forcing the casting to `InputStream` rather than `DataInput`
