### ISSUE TITLE
Clustered event bus traffic security [doc issue]

### ISSUE THREAD

**Issue by manikantag** [eclipse-vertx/vert.x#2372]
Hi, I'm new to Vert.x and going through documentation. Not sure where to report doc issues.

I m going through '**Security notes**' (https://vertx.io/docs/vertx-core/java/#_clustered_event_bus_traffic), and it is mentioned: 

> ### Clustered event bus traffic
> When clustering the event bus between different Vert.x nodes on a network, the traffic is sent un-encrypted across the wire, so do not use this if you have confidential data to send and your Vert.x nodes are not on a trusted network.

But in '**Configuring the event bus**' (https://vertx.io/docs/vertx-core/java/#_configuring_the_event_bus) section, it is mentioned we can provide keystore for secure communication.

> ### Configuring the event bus
> ...

	VertxOptions options = new VertxOptions()
	    .setEventBusOptions(new EventBusOptions()
	        .setSsl(true)
	        .setKeyStoreOptions(new JksOptions().setPath("keystore.jks").setPassword("wibble"))
	        .setTrustStoreOptions(new JksOptions().setPath("keystore.jks").setPassword("wibble"))
	        .setClientAuth(ClientAuth.REQUIRED)
	    );

> The previous snippet depicts how you can use SSL connections for the event bus, instead of plain TCP connections.

So, which is correct? I can confirm this by running Vert.x in cluster mode with keystore and see the traffic over the wire myself. But wanted to get the confirmation from the experienced users/authors. Thanks.

**Comment by manikantag** [comment]
Also, another doc bug is here: https://vertx.io/docs/vertx-core/java/#_specifying_a_handler_on_the_client_request

It is saying:

> Specifying a handler on the client request
> Instead of providing a response handler in the call to create the client request object, alternatively, you can **not** provide a handler when the request is created and set it later on the request object itself, using handler, for example:

But, we can provide the handler later as well, right?

**Comment by vietj** [comment]
this is correct for the client handler @manikantag

**Comment by vietj** [comment]
@manikantag yes it should say that it cannot be trusted by default

**Comment by manikantag** [comment]
@vietj I m getting confused about your comments. 

> this is correct for the client handler @manikantag

Do you mean the document is correct regarding client handler?

> @manikantag yes it should say that it cannot be trusted by default

So, does that mean, by default the traffic is not encrypted. But if we provide keystores then the traffic will be encrypted?
