### ISSUE TITLE
Use CloudFlare 1.1.1.1 as default DNS fallback instead Google's public DNS 8.8.8.8 and 8.8.8.4

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#2409]
See https://blog.cloudflare.com/announcing-1111/

**Comment by phraktle** [comment]
It's very sneaky to try to use different network settings than what the system DNS configuration indicates. I would consider it broken behavior, but confusing at the very least in a production environment.

**Comment by codingchili** [comment]
@phraktle this is a fallback if the system DNS configuration is missing/unset.

See docs here: https://vertx.io/docs/apidocs/io/vertx/core/dns/AddressResolverOptions.html#setServers-java.util.List-

**Comment by vietj** [comment]
I believe we should still use cloud flare DNS over Google's

**Comment by vietj** [comment]
we shall do this switch in 4.1.0 I think

**Comment by phraktle** [comment]
> @phraktle this is a fallback if the system DNS configuration is missing/unset.

I wish that was true. See #3861. 

But even if it worked correctly, I don't see why a framework like this should have an opinion on what network providers to use. What problem are you trying to solve? What if a DNS server is set but name resolution is failing?

**Comment by vietj** [comment]
closing this as this is hardcoded in Netty.
