### ISSUE TITLE
Use cases for multithreaded worker verticles

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vert.x#2431]
[**M**ulti**T**hreaded worker verticles](https://vertx.io/docs/vertx-core/java/#_multi_threaded_worker_verticles) are an extension to worker verticles. Like with usual worker verticles, events are handled on worker pool threads. But they can be executed by different threads concurrently, which means the verticle must manage its own state to be visible between threads.

There are many parts of Vert.x which simply doesn't support them. For example, you can't create an HTTP server on a MT worker verticle.

Also, we have seen many new users, in particular those experienced with Spring or Java EE, starting directly with MT worker verticles and adding as many threads as possible with the impression it would help get the best performance results. But this is really counter-productive.

**We are looking for relevant use cases for MT worker verticles**. If you are using them, can you please describe in a comment to this issue what you are doing and why you couldn't do with standard (event loop) or usual worker verticles?

We want to determine if MT worker verticles do more harm than good. Ultimately, if they are simply an anti-pattern, we could deprecate and remove them after a few releases.

Looking forward to your feedback, thanks.

**Comment by vietj** [comment]
there is no relationship @fzakaria . Vert.x uses biased locking in many places, the main reason is to allow to use Vert.x outside of the event loop, e.g

- you start an HTTP server from a main thread
- you send an HTTP server response from another thread than the event loop thread (async thread)
- you send an EventBus message from any thread
- you send a websocket message from any thread
- etc...

**Comment by philrykoff** [comment]
I have build a system where user defined code ("scripts", actually Groovy code) is being executed using ScriptEngine. Right now, it is using executeBlocking, as the user defined code might be blocking. I planned to refactor them to use a worker verticle and move to an Eventbus based invokation. Multi threaded worker verticle, as multiple scripts might need to be executed simultaneously. But as executeBlocking works, I am as of yet unsure about the benefits of multi threading workers vs. executeBlocking. Maybe this is a use case (rfc), but an edge case anyhow.

**Comment by vietj** [comment]
@philrykoff executeBlocking with ordered = false has similar behavior I think, tasks are not queued and can be execute concurrently, if they share state, they will access this state concurrently.

**Comment by tsegismont** [comment]
>  Multi threaded worker verticle, as multiple scripts might need to be executed simultaneously.

@philrykoff for this use case, you don't really need a MT worker verticle. You could [deploy multiple instances](https://vertx.io/docs/vertx-core/java/#_specifying_number_of_verticle_instances) of a worker verticle and achieve the same results.

Julien, who joined the project earlier than I did, thinks what you describe was the reason MT worker verticles were introduced. But it seems to me that the benefit (relieving the  developer from specifying the number of verticles in DeploymentOptions) does not balance the drawbacks (newcomers mistakenly using it as first choice).

**Comment by philrykoff** [comment]
Shouldn't it be enough to extend the documentation a bit, then?

The documentation for https://vertx.io/docs/apidocs/io/vertx/core/DeploymentOptions.html#setMultiThreaded-boolean- does not help at all, it basically paraphrases / repeats the method's name. It could include a warning, about what use cases not to use it for.

**Comment by tsegismont** [comment]
@philrykoff the [website doc](https://vertx.io/docs/vertx-core/java/#_multi_threaded_worker_verticles) has a warning but yes, the Javadoc could be enhanced. I don't think it's enough though.

**Comment by vietj** [comment]
@tsegismont imho beyond relieving the number of instances, it's also about capacity planning and getting the number right. When you deploy a verticle you specify the number of instances and if the number of instances is not right, then you need to undeploy the verticles and redeploy it with more or less instances. MT verticles defines the concurrency of the verticle (i.e how many numbers it can handle simultaneously) by the worker pool associated with it (which can be a named worker pool).

**Comment by vietj** [comment]
that being said, it is also interesting to have a precise number of instances for distributing the load in a cluster and here using a MT verticles will not provide weighted load balancing.

**Comment by vietj** [comment]
I think the multi worker effect with the event bus can be achieved with regular verticle + executeBlocking with parallel = true

**Comment by tsegismont** [comment]
> parallel = true

You mean `ordered=false` ?

Anyway, I think we could do 2 things for 3.6:
- update the Javadoc as [suggested](https://github.com/eclipse-vertx/vert.x/issues/2431#issuecomment-387461824) by @philrykoff 
- document an alternative to MT worker verticles (provide a worker pool name/size in `DeploymentOptions` and set the number of instances accordingly)

And then drop MT worker verticles in 4.0.

**Comment by vietj** [comment]
@tsegismont yes ordered = false <=> parallel = true in my mind :-) .

beside that totally agreeing with you, the only case I see useful for multi-worker is event bus message handling and this can be totally done with `executeBlocking` having an `ordered` argument set to `false` (we should try to test for this to be 100% sure though).

thanks for bringing this concern up and the whole discussion around the actual need of this feature.

**Comment by vietj** [comment]
@TechPriest-alpha there is no firm call yet. Can you try rewrite this using a single event-loop verticle that inside the code uses executeBlocking with ordered flag = false ? or can you provide a small project that reproduces your setup so we can try ourselves ?

**Comment by TechPriest-alpha** [comment]
@vietj of course, I'll try to provide better example, it would take couple of days though.
Cant't just take code from current project due to NDA.

**Comment by vietj** [comment]
yes sure, I meant mock-up style :-)

**Comment by TechPriest-alpha** [comment]
Hi!
@tsegismont , thank you for the suggestion, actually we've overlooked such option. It seems launching DAO workers in multiple instances allows to achieve same goals without need to use multi-threaded workers.
And just to double-check: do I understand correctly, that Vert.x will have no issues dealing with 1000-1500 verticles instead of 200-300 if we launch say 100 instances of each required worker?

So far my concerns about MT Workers have been resolved :)
Still, by the end of tomorrow I should be able to provide basic 'mock' project just to illustrate flows we were using MT approach for.
If there are any inquiries about our use cases remaining: I'll be happy to answer them.

**Comment by vietj** [comment]
@TechPriest-alpha that won't be an issue, the bottleneck will always be the worker pool size. The reproducer will be welcome

**Comment by TechPriest-alpha** [comment]
Thank you, @vietj .

I've uploaded example here: https://github.com/TechPriest-alpha/example. It illustrates general concepts used in our application.
Tests try to simulate two dominant use cases: one where several users of the API perform roughly same set of actions and other where workload 'shifts' between different user sessions.
Just to clarify: 'workers' in our case are more like business-logic units combining several transactional data access scenarios (i.e. access check, data manipulation and audit record).
Also worth to note that no verticles have session-specific state, so there is no need for complex synchronization logic.
So far single-instance non-MT workers test clearly falls behind in terms of time required to handle concurrent requests.
But MT and multi-instance workers seem to behave equally.
If 'executeBlocking' is used to handle requests originally processed by workers - picture generally is the same as in MT / multi-instance cases.

Feel free to tell me if there any clarifications and or adjustments are required.
