### ISSUE TITLE
Support for Consumer Groups

### ISSUE THREAD

**Issue by tanneess** [eclipse-vertx/vert.x#2432]
Hi,

First of all great work on vert.x, it is really enjoyable to work with and such a powerful tool in such a small package. But recently I came across a missing vert.x feature that if implemented would make the appeal of vert.x's event bus much greater.

As far as I can see there is no direct support for Consumer Groups in vert.x, and this is a real pity.

By consumer groups I mean a set of consumers that would listen to published messages on a same address but with only at most one of these consumers getting the message. This would allow us to do load balancing for published messages. Load balancing already works out of the box for send messages (point-to-point), and without it published messages have only limited useful use cases. 

Without this, published message processing does not scale horizontally as all messages must be processed by every single verticle register as consumer (i.e. no load balancing).

Having Consumer Groups would make the event bus allot more powerful and should not be that hard to implement. I suppose that it would be possible to set this up with existing tools, but it would require to 
1. hand craft an API for subscribing to consumer groups, 
2. have verticles that manage these groups subscription and message distribution
3. hold the subscription information in a distributed data structure. 

All possible but better provided by a vert.x api.

In code, I am looking for something like that

```java
vertx.eventBus.consumer("order.completed.event", ProductStatsVerticle.class, message->{
    /* do some great things*/
})
```

Where the name of ProductStatsVerticle.class is used as the name of the consumer group. Variants with a String consumer group name should also exist.

I'd like to have some opinions on this. Maybe there are already 3rd party implementation that could be inspiring, or a pattern that easily permits this feature?

Best regards,
Thim.

**Comment by manish-panwar** [comment]
I am not very clear on what do you mean by 

> consumers that would listen to published messages on a same address but with only at most one of these consumers getting the message

Why no to use #send if message has to be processed by 1 consumer.

**Comment by vietj** [comment]
it seems that you would like published messages behave like sent messages ? can you clarify the problem you need to solve with this feature ? if you need consumer group, then just register a single publisher and do the dispatch yourself or send messages and not publish them. So it's not clear in my mind what you are trying to solve.

**Comment by tsegismont** [comment]
@manish-panwar @vietj I believe what @tanneess would like is to be able to make a difference between consumers registered by different instances of the same verticle and consumers registered by different verticles. Let's take an example:

- In verticle A, you receive shopping orders and persist them in a database
- In verticle B, you log every new order to an audit service
- In verticle C, you process every new order and send them to shipment service

To make those verticles work together, you can make verticle A publish a message, which verticle B and C will both process. That works just fine as long as you only have 1 instance of B and C.

But if you have multiple instances B or C, then the order could be logged in audit several times, or shipped several times.

Can you confirm @tanneess ?

**Comment by tanneess** [comment]
@tsegismont this is exactly what I mean. The idea is that we would like to have an event driven architecture where verticle A does not know what happens after it has done it's job. It does not need to know that the verticle B requires to be informed in order to make the audits. The best way to do this in Vert.x is to publish a message on the event bus, but this does not scale horizontally.

**Comment by vietj** [comment]
@tsegismont thanks for the explanation

**Comment by vietj** [comment]
so one way to achieve it, is to forward the message using send, when A receives a published message it sends (forward) it to its private group where it gets load balanced to the group

**Comment by tanneess** [comment]
@vietj  this will not scale horizontally because A needs to be the sole Verticle forwarding the publication to the private Group.

If A is the only Verticle  forwarding the Event to it's private group using send, A will be a bottleneck. If you have several instances of A:
- The model is broken as each event will be forwarded several times
- You still will not have scaled because every single instance of A will have to process every single Event coming on "order.accepted.event" address.

**Comment by vietj** [comment]
@tanneess 

- we are assuming there is one single instance of A
- with a consumer group mechanism then the message dispatching would be done internally in a single point and the processing done by A would be equivalent to this

**Comment by vietj** [comment]
@tanneess in case of clustering the receiver does the dispatch as it seems all the consumers a a choosable iterable.

**Comment by vietj** [comment]
so in case of clustering there is a double dispatch

**Comment by vietj** [comment]
anyway I'm not opposed to this, just trying to see if that really has to be something internal to vertx and how it would fit.

**Comment by tanneess** [comment]
@sonofingo, than you for this proposed solution, it could be of use for a quick work arround to the problem. However this solution will not scale horizontally. Don’t get me wrong, in the beginning adding new Verticle will make increase throughput but only to a point.
In the proposed solution there is allot that will not scale as every Verticle needs to process every Message. Not all will finish the message processing but allot of work will be duplicated by all verticles. Here is a list of the duplicated work
- Network trafic (not really Verticle work but still a problem as the Message is distributed several times)
- Message parsing 
- Message body hashCode computation
- Idempotent put into distributed Map (this will also increase load on the Clustering Manager)

This partial solution kinds of demonstrate one of the reasons why this needs to be solved by Vert.x, we would both benefit from having a clear path for solving this common issue. A good place to have it is inside the already existing EventBus.

**Comment by tanneess** [comment]
@vietj I really see this as a must have inside Vert.x for three reasons.

1) I see this need for Grouped Consumer arise more and more often. This is probably due to the Micro-Service push where allot of people want there services to just do their job and not care about what happens next. In order to do this some chose to use an Event Bus. Good news Vert.x already has one, bad news you cannot out of the box scale horizontally with events. You can with point to point messages, but when doing point to point your service must be aware of where to send the Events. So in the example above, your OrderService needs to know that there is an AuditService, that can be reached at a specific address and that it needs to be called. So this kinds of defeats the purpose of having an EventBus.
It would be great to just be able to do it in Vert.x using one extra parameter to the EventBus.consume method.

2) You could implement Consumer Groups with the tools that Vert.x offers, but this would be incompatible with Vert.x existing EventBus features. 
	- Publish should be replaced by Send
	- Consumption address would be different than send address

3. The only solution I can come up with using existing tools that scales horizontally is as follow:

Given
- ConsumerGroup: a group of consumers that should be regarded by Vert.x as one consumer
- MemberVerticle: a Vertical wanting to consume Events as part of ConsumerGroup
- ConsumerGroupAddress: the address where the MemberVerticles can receive the event’s for ConsumerGroup
- EventAddress: the address used to send the event.
- RegistrationStore: a data structure shared by all ConsumerGroupVerticles. This store contains the registration information needed to route the Events.
- Publisher: the publisher of the Event

One way to do it would be to
1. Have MemberVerticles send registrations requests to the ConsumerGroup.
2. Have the ConsumerGroupVerticle store the registrations in the RegistrationStore. If this is the first registration for ConsumerGroup, a mapping between ConsumerGroup and ConsumerGroupAddress must be made in the RegistrationStore
3. Have the ConsumerGroupVerticle reply to the MemberVerticles with ConsumerGroupAddress
4. Have the MemberVerticles listen to ConsumerGroupAddress
5. Have ConsumerGroupVerticle listen to EventAddress and forward Events to ConsumerGroupAddress.
6. Have Publisher send (and not publish) the Event to the EventAddress.

This solution is quite complicated and requires the reimplementation some feature of the EventBus (like registration and message routing). 


All in all I think Vert.x will win from having this as an out of the box feature and the Vert.x users would win from having a clean and reliable path for having Grouped Consumers.

**Comment by vietj** [comment]
@tanneess thanks for your perspective, we will study your proposal carefully

**Comment by sonofingo** [comment]
Hi again,

@tanneess, How would you ensure that exactly one consumer in every consumer group on the same address actually receives and processes a message? 

From my perspective, as an old enterprise integration guy, what you are wanting is a pattern usually called "router" or "dynamic router" (see http://camel.apache.org/dynamic-router.html). The problem is that routing increases the amount of logic and processing on the producer side and you need some sort of feedback for knowing that a message at least has been received and sometimes even processed. Having this type of logic built in to the Vert.x event bus will likely increase its complexity quite a bit. 

As it is today "publish" in Vert.x aligns with the pattern "publish subscribe channel" where the Vert.x producer does a broadcast and does not need to care about if any consumer has received the message. The "send" in Vert.x aligns with the pattern "point to point channel" where in the case of Vert.x the only responsibility of the Vert.x producer is to find one consumer to send to, but it is not a pattern for "guaranteed delivery". 

From my experience starting with the pattern for a "idempotent consumer" actually scales reasonably well. Of course up to some limit but if you are running in a cloud like AWS the network latency is very low. Another thing I have used to increase performance is to have the producer first storing the message in a shared data map and then calculating the hash code and send that as the message on the event bus. The consumers that actually then does the final processing will fetch the full message from the shared data map. Instead of the Vert.x shared data map one could for example use Redis to improve performance. In the case of Redis you could also build a cluster manager for Vert.x that uses Redis directly and that way the shared data in Vert.x is really fast.

Regards

**Comment by tanneess** [comment]
@sonofingo In the Consumer Group case, the producer wants to keep the same fire and forget properties of the vert.x publish. Only the Consumer want to be sure that the message does not go through the same business logic more than once.

In vert.x API this could have as little impact as having one extra parameter in the consume method of the event bus (as state in my first post). How much complication it would add to Vert.x I do not know.

**Comment by tanneess** [comment]
@sonofingo Thank you for the DynamicRouter proposal as it seems to be solving the issue. 

It also illustrate my point about having to re-implement an EventBus on top of the EventBus. Every component here is talking to the Router and only the Router is talking to the EventBus.

I still believe this feature should be a part of Vert.x's EventBus, but maybe that another Route would be to have it as part of a Vert.x extension.

In the mean time thank you @sonofingo for this proposal. It will definitely help us solve this issue if Consumer Groups do not land in Vert.x by the time we need it.

**Comment by vietj** [comment]
@sonofingo would you mind contributing this and capture it in the vertx cookbook as a recipe for this problem ?

**Comment by charithdesilva** [comment]
Hi folks, Did you have any development on this? I'm hitting on the exact issue as described by @tanneess

**Comment by vietj** [comment]
we advise to use the solution advocated by @sonofingo

**Comment by charithdesilva** [comment]
@vietj Thanks, appreciate your quick return.., and while I'm thanking @sonofingo for the shared solution, is there any roadmap to incorporate the solution to VertX itself. (I have been pushing through VertX as the microservices chassis, however, this issue is becoming a deal killer for me. I'm after a roadmap/ timeline..etc.)

**Comment by vietj** [comment]
@charithdesilva I think this could be part of event-bus building blocks library
