### ISSUE TITLE
Invalid SSL configuration does not callback the server listen method handler

### ISSUE THREAD

**Issue by broundee** [eclipse-vertx/vert.x#2435]
When HTTP server is initialized with invalid SSL configuration (e.g. invalid path to keystore file), it does not call the listen handler, breaking the async calls chain.

Example:

```kotlin
import io.vertx.core.AbstractVerticle
import io.vertx.kotlin.core.net.JksOptions
import io.vertx.kotlin.core.http.HttpServerOptions

class RestVerticle : AbstractVerticle() {
    override fun start(startFuture: Future<Void>) {
        val jksOptions = JksOptions(path = "invalid_path", password = "somePassword")
        val httpServer = vertx.createHttpServer(HttpServerOptions(ssl = true, keyStoreOptions = jksOptions))
        httpServer.requestHandler({}).listen(8083, "127.0.0.1", {
            // This handler is never called
            if (it.succeeded())
                startFuture.complete()
            else
                startFuture.fail(it.cause())
        })
    }
}
```

In addition to that, the verticle deployment code does not call the deployment completion handler.

Example:

```kotlin
import io.vertx.core.AbstractVerticle
import io.vertx.kotlin.core.net.JksOptions
import io.vertx.kotlin.core.http.HttpServerOptions

class MainVerticle : AbstractVerticle() {
    override fun start(startFuture: Future<Void>) {
        Future.future<String>().also { future ->
            // Future completer is never called
            vertx.deployVerticle(RestVerticle(), DeploymentOptions(worker = true), future.completer())
        }.compose({ startFuture.complete() }, startFuture)
    }
}
```

So far I see that the problem might be caused by the fact that `actualServer` is not set to anything at the point of [this check](https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/HttpServerImpl.java#L539), but `listening` is already set to `true`, so `executeCloseDone` above is not called either.

**Comment by vietj** [comment]
thanks for reporting.

**Comment by vietj** [comment]
works fine in master, reported as a synchronous exception in 3

**Comment by vietj** [comment]
I think we will leave it like that for 3.x because it would be a regression with how applications might handle currently.
