### ISSUE TITLE
Hard-coded HTTPS scheme regardless of SSL usage

### ISSUE THREAD

**Issue by hirokiht** [eclipse-vertx/vert.x#2506]
https://github.com/eclipse/vert.x/blob/a6114607b00cf584fc149e9f687019f4af182925/src/main/java/io/vertx/core/http/impl/Http2ClientConnection.java#L325

The https scheme is passed even if ssl is not used, should be easy to fix by checking via isSsl() then use "http" or "https" accordingly

**Comment by vietj** [comment]
fixed
