### ISSUE TITLE
Use of wildcards in Pump

### ISSUE THREAD

**Issue by MrQubo** [eclipse-vertx/vert.x#2531]
The declaration of static pump function from Pump class should be changed to allow use of wildcards.
Instead of
```java
static <T> Pump pump(ReadStream<T> rs, WriteStream<T> ws)
```
it should be
```java
static <T> Pump pump(ReadStream<? extends T> rs, WriteStream<? super T> ws)
```

**Comment by vietj** [comment]
we don't support wildcards in the code generators
