### ISSUE TITLE
Vertx/Netty is appending "=" in query parameter.

### ISSUE THREAD

**Issue by manish-panwar** [eclipse-vertx/vert.x#2544]
We are using Vertx 3.5.0 **WebClient** API to make HTTP call to remote server and given below is how my input URI look like :

> /server/path?jREJBBB5x2AaiSSDO0/OskoCztDZBAAAAAADV1A4

In **HttpClientContext** Vertx is calling **io.netty.handler.codec.http.QueryStringEncoder**, which append "=" even though it wasn't there in actual input provided to Vertx.

`QueryStringEncoder enc = new QueryStringEncoder(request.uri);
      request.queryParams().forEach(param -> enc.addParam(param.getKey(), param.getValue()));
      requestURI = enc.toString();`

**From QueryStringEncoder:**

`if (value != null) {
            this.uriBuilder.append('=');
            appendComponent(value, this.charsetName, this.uriBuilder);
        }`

**So actual URI received by remote server looks like below:**

> /server/path?jREJBBB5x2AaiSSDO0%2FOskoCztDZBAAAAAADV1A4=

If you notice in above URL, Vertx is encoding the parameter and also appending extra "=" at the end.

This issue isn't there if we use **HttpClient** API instead of **WebClient** API. Unfortunately the remote server doesn't like this extra "=" added to query and encoded query, and fails hard. This remote system can't be updated to handle this behavior because if doesn't belong to us.

Moving back to HttpClient will be very expensive to us because of amount of code change. Looking forward to your feedback. We are open for suggestions, and we can create a PR once agreed upon the solution.

Here is sample reproducer - https://github.com/manish-panwar/vertx-issue-2544-reproducer-

**Comment by manish-panwar** [comment]
One more thing to note, we work as a proxy, so we can't control on how input URI is provided, or how remote system handles it, we are are suppose to pass the things the way they are received.

**Comment by arushi315** [comment]
Any update on this issue?
Hi @vietj could you please provide some insight on this? 
Appreciate your time.

**Comment by vietj** [comment]
can you move this issue to the vertx-web repository instead https://github.com/vert-x3/vertx-web ?

**Comment by vietj** [comment]
closing it as it's the wrong repo

**Comment by ramtech123** [comment]
Vertx-web ticket for this issue - https://github.com/vert-x3/vertx-web/issues/1041
