### ISSUE TITLE
RecordParser should have an option to limit the record size

### ISSUE THREAD

**Issue by richardf** [eclipse-vertx/vert.x#2560]
When using RecordParser's delimited mode, it would be nice to somehow limit the maximum buffer size, to prevent misbehaving/malicious clients from exhausting server resources.

This could be achieved by exposing the buffer length, like so:
```java
RecordParser rp = RecordParser.newDelimited("\n", System.out::println);
socket.handler(buffer -> {
   rp.handle(buffer);
   if (rp.getBufferSize() > config().getInteger("maxRecordSize")) {
      System.out.println("big record, eh?");
      socket.close();
   }
});
```

Another option would be to check the record size in RecordParserImpl.parseDelimited() and throw an exception, that could be handled inside the exceptionHandler:
```java
RecordParser rp = RecordParser.newDelimited("\n", System.out::println);
rp.setMaxRecordSize(10);
rp.exceptionHandler(throwable -> {
   System.out.println("big record, eh?");
   socket.close();
});
```

Thoughts?

**Comment by tsegismont** [comment]
Option /2 sounds good to me. Netty's line based frame decoder does not even let you create an instance without providing a max length for frames.

**Comment by richardf** [comment]
Thanks for the feedback. Going to work on a PR
