### ISSUE TITLE
io\vertx\core\http\impl\HttpServerImpl  maybe error listen port

### ISSUE THREAD

**Issue by yangyi438** [eclipse-vertx/vert.x#2565]
public synchronized HttpServer listen(int port, String host, Handler<AsyncResult<HttpServer>> listenHandler) {
    if (requestStream.handler() == null && wsStream.handler() == null) {
      throw new IllegalStateException("Set request or websocket handler first");
    }
    if (listening) {
      throw new IllegalStateException("Already listening");
    }
    listenContext = vertx.getOrCreateContext();
    listening = true;
    serverOrigin = (options.isSsl() ? "https" : "http") + "://" + host + ":" + port;
    List<HttpVersion> applicationProtocols = options.getAlpnVersions();
    if (listenContext.isWorkerContext()) {
      applicationProtocols =  applicationProtocols.stream().filter(v -> v != HttpVersion.HTTP_2).collect(Collectors.toList());
    }
    sslHelper.setApplicationProtocols(applicationProtocols);
    synchronized (vertx.sharedHttpServers()) {
      this.actualPort = port; // Will be updated on bind for a wildcard port
      id = new ServerID(port, host);
      HttpServerImpl shared = vertx.sharedHttpServers().get(id);
      if (shared == null || port == 0) {
        serverChannelGroup = new DefaultChannelGroup("vertx-acceptor-channels", GlobalEventExecutor.INSTANCE);
        ServerBootstrap bootstrap = new ServerBootstrap();
        bootstrap.group(vertx.getAcceptorEventLoopGroup(), availableWorkers);
        applyConnectionOptions(bootstrap);
        sslHelper.validate(vertx);
        bootstrap.childHandler(new ChannelInitializer<Channel>() {
          @Override
            protected void initChannel(Channel ch) throws Exception {
              if (requestStream.isPaused() || wsStream.isPaused()) {
                ch.close();
                return;
              }
              ChannelPipeline pipeline = ch.pipeline();
              if (sslHelper.isSSL()) {
                io.netty.util.concurrent.Future<Channel> handshakeFuture;
                if (options.isSni()) {
                  VertxSniHandler sniHandler = new VertxSniHandler(sslHelper, vertx);
                  pipeline.addLast(sniHandler);
                  handshakeFuture = sniHandler.handshakeFuture();
                } else {
                  SslHandler handler = new SslHandler(sslHelper.createEngine(vertx));
                  pipeline.addLast("ssl", handler);
                  handshakeFuture = handler.handshakeFuture();
                }
                handshakeFuture.addListener(future -> {
                  if (future.isSuccess()) {
                    if (options.isUseAlpn()) {
                      SslHandler sslHandler = pipeline.get(SslHandler.class);
                      String protocol = sslHandler.applicationProtocol();
                      if ("h2".equals(protocol)) {
                        handleHttp2(ch);
                      } else {
                        handleHttp1(ch);
                      }
                    } else {
                      handleHttp1(ch);
                    }
                  } else {
                    HandlerHolder<HttpHandlers> handler = httpHandlerMgr.chooseHandler(ch.eventLoop());
                    handler.context.executeFromIO(() -> handler.handler.exceptionHandler.handle(future.cause()));
                  }
                });
              } else {
                if (DISABLE_H2C) {
                  handleHttp1(ch);
                } else {
                  IdleStateHandler idle;
                  if (options.getIdleTimeout() > 0) {
                    pipeline.addLast("idle", idle = new IdleStateHandler(0, 0, options.getIdleTimeout()));
                  } else {
                    idle = null;
                  }
                  // Handler that detects whether the HTTP/2 connection preface or just process the request
                  // with the HTTP 1.x pipeline to support H2C with prior knowledge, i.e a client that connects
                  // and uses HTTP/2 in clear text directly without an HTTP upgrade.
                  pipeline.addLast(new Http1xOrH2CHandler() {
                    @Override
                    protected void configure(ChannelHandlerContext ctx, boolean h2c) {
                      if (idle != null) {
                        // It will be re-added but this way we don't need to pay attention to order
                        pipeline.remove(idle);
                      }
                      if (h2c) {
                        handleHttp2(ctx.channel());
                      } else {
                        handleHttp1(ch);
                      }
                    }

                    @Override
                    public void userEventTriggered(ChannelHandlerContext ctx, Object evt) throws Exception {
                      if (evt instanceof IdleStateEvent && ((IdleStateEvent) evt).state() == IdleState.ALL_IDLE) {
                        ctx.close();
                      }
                    }

                    @Override
                    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
                      super.exceptionCaught(ctx, cause);
                      HandlerHolder<HttpHandlers> handler = httpHandlerMgr.chooseHandler(ctx.channel().eventLoop());
                      handler.context.executeFromIO(() -> handler.handler.exceptionHandler.handle(cause));
                    }
                  });
                }
              }
            }
        });

        addHandlers(this, listenContext);
        try {
          bindFuture = AsyncResolveConnectHelper.doBind(vertx, SocketAddress.inetSocketAddress(port, host), bootstrap);
          bindFuture.addListener(res -> {
            if (res.failed()) {
              vertx.sharedHttpServers().remove(id);   //fixme    //async to remove
            } else {
              Channel serverChannel = res.result();
              HttpServerImpl.this.actualPort = ((InetSocketAddress)serverChannel.localAddress()).getPort();
              serverChannelGroup.add(serverChannel);
              VertxMetrics metrics = vertx.metricsSPI();
              this.metrics = metrics != null ? metrics.createMetrics(this, new SocketAddressImpl(port, host), options) : null;
            }
          });
        } catch (final Throwable t) {
          // Make sure we send the exception back through the handler (if any)
          if (listenHandler != null) {
            vertx.runOnContext(v -> listenHandler.handle(Future.failedFuture(t)));
          } else {
            // No handler - log so user can see failure
            log.error(t);
          }
          listening = false;
          return this;
        }
        vertx.sharedHttpServers().put(id, this);    //fixme  //syn put
        actualServer = this;
      } else {
        // Server already exists with that host/port - we will use that
        actualServer = shared;
        this.actualPort = shared.actualPort;
        addHandlers(actualServer, listenContext);
        VertxMetrics metrics = vertx.metricsSPI();
        this.metrics = metrics != null ? metrics.createMetrics(this, new SocketAddressImpl(port, host), options) : null;
      }
      actualServer.bindFuture.addListener(future -> {
        if (listenHandler != null) {
          final AsyncResult<HttpServer> res;
          if (future.succeeded()) {
            res = Future.succeededFuture(HttpServerImpl.this);
          } else {
            res = Future.failedFuture(future.cause());
            listening = false;
          }
          listenContext.runOnContext((v) -> listenHandler.handle(res));
        } else if (future.failed()) {
          listening  = false;
          // No handler - log so user can see failure
          log.error(future.cause());
        }
      });
    }
    return this;
  }

has two line code use //fixme

we use async to remove id when happends error
but use sync to put id later on
may the error happends before the  (vertx.sharedHttpServers().put(id, this);    //fixme  //syn put)
then rarely
first remove
second put.
it while listen error
but sharedHttpServers has the id

**Comment by vietj** [comment]
can you provided a reproducer for this potential race condition ?

**Comment by yangyi438** [comment]
VertxOptions option = new VertxOptions().setEventLoopPoolSize(4);
        option.setClustered(false);
        option.setEventLoopPoolSize(4);
        Vertx vertx = Vertx.vertx(option);
        DeploymentOptions deploymentOptions = new DeploymentOptions().setInstances(2);
        deploymentOptions.setInstances(2);
        vertx.deployVerticle(new AbstractVerticle() {
            @Override
            public void start() throws Exception {
                vertx.createHttpServer().requestHandler(req -> {
                    req.response().end("hello Im first");
                    }).listen(8080);
                };
            }
            );
        vertx.deployVerticle(new AbstractVerticle() {
            @Override
            public void start() throws Exception {
                vertx.createHttpServer().requestHandler(req -> {
                    req.response().end("hello Im second");
                }).listen(8080);
            };
        });

    }
8080 port is in use
8081 is free

now 4 thread will run int start

 private final Map<ServerID, HttpServerImpl> sharedHttpServers = new HashMap<>();

 is not  thread safe

第一个线程first run want to use 8080
then
get synchronized lock  vertx.sharedHttpServers()
vertx.sharedHttpServers().put(id, this);
then give back synchronized lock vertx.sharedHttpServers()
because of 8080 is in use
if the future will run this code

if (res.failed()) {
              vertx.sharedHttpServers().remove(id);
            }

thread 2 also want to listen 8080 

and get synchronized lock  vertx.sharedHttpServers()

thread 2  run code
HttpServerImpl shared = vertx.sharedHttpServers().get(id);
 
shared is not null 

thread 2 will think it is be use 
and run code

else {
        // Server already exists with that host/port - we will use that
        actualServer = shared;
        this.actualPort = shared.actualPort;
        addHandlers(actualServer, listenContext);
        VertxMetrics metrics = vertx.metricsSPI();
        this.metrics = metrics != null ? metrics.createMetrics(this, new SocketAddressImpl(port, host), options) : null;
      }

The binding was not actually successful ---> 8080 
thread 2 Not yet run code
 if (res.failed()) {
              vertx.sharedHttpServers().remove(id);
            } 

then

thread 2 will give bavk lock vertx.sharedHttpServers()

thread 3 get lock vertx.sharedHttpServers()

and run this code  want listen 8081

vertx.sharedHttpServers().put(id, this);

threa 1 and thread 3  concurrent
want to remove and put
HashMap is not Thread safe

then whill happends Exception

Thread 2  run the  not right code

there are two number of error may be happend

Although the odds are low

**Comment by yangyi438** [comment]
第一个线程 is chinese  means Thread 1

**Comment by yangyi438** [comment]
oh no
The previous explanation is wrong and this is the final explanation

    VertxOptions option = new VertxOptions().setEventLoopPoolSize(4);
    option.setClustered(false);
    option.setEventLoopPoolSize(4);
    Vertx vertx = Vertx.vertx(option);
    DeploymentOptions deploymentOptions = new DeploymentOptions().setInstances(2);
    deploymentOptions.setInstances(2);
    vertx.deployVerticle(new AbstractVerticle() {
        @Override
        public void start() throws Exception {
            vertx.createHttpServer().requestHandler(req -> {
                req.response().end("hello Im first");
                }).listen(8080);
            };
        }
        );
    vertx.deployVerticle(new AbstractVerticle() {
        @Override
        public void start() throws Exception {
            vertx.createHttpServer().requestHandler(req -> {
                req.response().end("hello Im second");
            }).listen(8080);
        };
    });

}
8080 port is in use
8081 is free

now 4 thread will run int start

private final Map<ServerID, HttpServerImpl> sharedHttpServers = new HashMap<>();

is not thread safe

 thread 1 first run want to use 8080
then
get synchronized lock vertx.sharedHttpServers()
vertx.sharedHttpServers().put(id, this);
then give back synchronized lock vertx.sharedHttpServers()
because of 8080 is in use
if the future will run this code

if (res.failed()) {
vertx.sharedHttpServers().remove(id);
}

thread 2 also want to listen 8080

and get synchronized lock vertx.sharedHttpServers()

thread 2 run code
HttpServerImpl shared = vertx.sharedHttpServers().get(id);

shared is not null

thread 2 will think it is be use
and run code

else {
// Server already exists with that host/port - we will use that
actualServer = shared;
this.actualPort = shared.actualPort;
addHandlers(actualServer, listenContext);
VertxMetrics metrics = vertx.metricsSPI();
this.metrics = metrics != null ? metrics.createMetrics(this, new SocketAddressImpl(port, host), options) : null;
}

The binding was not actually successful ---> 8080
thread  1  Not yet before thread 2 run code
if (res.failed()) {
vertx.sharedHttpServers().remove(id);
}

then

thread 2 will give bavk lock vertx.sharedHttpServers()

thread 3 get lock vertx.sharedHttpServers()

and run this code want listen 8081

vertx.sharedHttpServers().put(id, this);

threa 1 and thread 3 concurrent
want to remove and put
HashMap is not Thread safe

then whill happends Exception

Thread 2 run the not right code

there are two number of error may be happend

Although the odds are low

**Comment by shenliuyang** [comment]
Use close()  instead of  vertx.sharedHttpServers().remove(id);

**Comment by vietj** [comment]
this is indeed racy

**Comment by vietj** [comment]
I don't get what you deploymentOptions are for since they are not used in your example

**Comment by yangyi438** [comment]
package io.example;

import io.vertx.core.*;

import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;


/**
 * Created by yangyi on 2018/7/25.
 */
public class TestWebServer {
    public static void main(String[] args) throws IOException {
        VertxOptions option = new VertxOptions().setEventLoopPoolSize(4);
        option.setClustered(false);
        option.setEventLoopPoolSize(4);
        Vertx vertx = Vertx.vertx(option);
        ServerSocket serverSocket = new ServerSocket(8080);
        
        vertx.deployVerticle(new AbstractVerticle() {
            @Override
            public void start() throws Exception {
                vertx.createHttpServer().requestHandler(req -> {
                    req.exceptionHandler(
                            event -> {
                                event.printStackTrace();
                            }
                    );
                    req.response().end("hello Im first 8080");
                    }).listen(8080);
                };
            }
            );
        vertx.deployVerticle(new AbstractVerticle() {
            @Override
            public void start() throws Exception {
                vertx.createHttpServer().requestHandler(req -> {
                    req.response().end("hello Im second 8081");
                }).listen(8081);
            };
        }
        );
        try {
            Thread.sleep(10000L);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

    }
}

sorry see this code example , i use idea debug ,I can use the debug function of idea to reproduce
see the images
![image](https://user-images.githubusercontent.com/31379097/60972305-955f2180-a358-11e9-98ed-69b858df5f94.png)
and 
![image](https://user-images.githubusercontent.com/31379097/60972485-f71f8b80-a358-11e9-93f1-f6e84dfe0caf.png)
2 thread put and remve  the same HashMap

**Comment by vietj** [comment]
yes there can be occasional races, we will fix them :-)
