### ISSUE TITLE
SslHandler should use ref-count buffer

### ISSUE THREAD

**Issue by luengnat** [eclipse-vertx/vert.x#2575]
Currently, it uses PartialPooledByteBufAllocator. Therefore, it does not pool the buffer which results in extra memory allocation.

**Comment by vietj** [comment]
can you provide a PR ?

**Comment by luengnat** [comment]
@vietj  can you recommend how to fix this? I don't quite understand why PartialPooledByteBufAllocator is used without pooling.

**Comment by vietj** [comment]
actually have you verified that buffers are not pooled ? I think they are

**Comment by vietj** [comment]
The doc of `PartialPooledByteBufAllocator` says:

A `io.netty.buffer.ByteBufAllocator` which is partial pooled. Which means only direct `io.netty.buffer.ByteBuf`s are pooled. The rest is unpooled.

What is unpooled are the buffers used by Vert.x and wrapped with Vert.x buffers.

**Comment by vietj** [comment]
I can see that with JDK ssl engine, buffers are not direct so indeed they are likely not pooled. With other engines it should be pooled.

**Comment by vietj** [comment]
indeed, that's what is happening.

I'm wondering if we should try to not use this allocator by default and use it when it's needed.

**Comment by vietj** [comment]
closing for now, it is not clear what should be done because we need to distinguish buffers for write and for read. Buffer for reads are not pooled on purpose because they are then transformed into Vert.x buffers that are not pooled

**Comment by vietj** [comment]
Please reopen if needed with a more detailed description
