### ISSUE TITLE
/io/vertx/core/http/impl/HttpServerImpl.java should be able to asynchronously accept/reject Websocket handshake 

### ISSUE THREAD

**Issue by itsmichaelwang** [eclipse-vertx/vert.x#2585]
HttpServerImpl synchronously accepts or rejects the Websocket handshake:
```
conn.handleWebsocketConnect(ws);
          if (!ws.isRejected()) {
            ChannelHandler handler = ctx.pipeline().get(HttpChunkContentCompressor.class);
            if (handler != null) {
              // remove compressor as its not needed anymore once connection was upgraded to websockets
              ctx.pipeline().remove(handler);
            }
            ws.connectNow();
          } else {
            ch.writeAndFlush(new DefaultFullHttpResponse(HTTP_1_1, ws.getRejectedStatus()));
          }
```
I think we should probably make it async, in case we have an async operation (i.e. hitting an OAuth server with a token) that rejection depends on.

**Comment by vietj** [comment]
yes that's something we spotted a while ago and I think there might be already an issue for that with a prior discussion.

**Comment by vietj** [comment]
that would be an api breaking change so it's scoped to 4

**Comment by vietj** [comment]
fixed by https://github.com/eclipse-vertx/vert.x/issues/2858
