### ISSUE TITLE
Gracefully close HttpServer

### ISSUE THREAD

**Issue by llfbandit** [eclipse-vertx/vert.x#2602]
Logging issue to gracefully close HTTP server.

Meaning :
- Stop listening and accepting incoming requests.
- Leave inflight requests ending normally before completly close the server.

Discussed recently here : https://groups.google.com/forum/#!topic/vertx/A7GhZ6bmOmU

**Comment by tsegismont** [comment]
Closed by https://github.com/eclipse-vertx/vert.x/pull/5189
