### ISSUE TITLE
Extra chunk for request with no content.

### ISSUE THREAD

**Issue by FroMage** [eclipse-vertx/vert.x#2607]
The following code produces an extra 0 end trailer chunk that makes HTTP clients parse it as a second invalid response:

```java
		Vertx vertx = Vertx.vertx();
		HttpServer server = vertx.createHttpServer();
		server.requestStream().toObservable().subscribe(req -> {
			System.err.println("Got request");
			req.response().setChunked(true).setStatusCode(204).end();
		});
		server.rxListen(9001, "localhost").subscribe(s -> System.err.println("started"), Throwable::printStackTrace);
```

My guess is that if there is no body, there should not be any trailer end chunk.

Related to #1986 (was only for HEAD).

https://tools.ietf.org/html/rfc7231#section-6.3.5 indicates:

     A 204 response is terminated by the first empty line after the header
     fields because it cannot contain a message body.

Perhaps there are other HTTP status codes that can't contain a message body?

**Comment by vietj** [comment]
taht should be easy to fix

**Comment by vietj** [comment]
1xx code should not contain response body

**Comment by FroMage** [comment]
I found the following conditions where the spec forbids a body:

```
(status >= 100 && status < 200)
				|| status == Status.NO_CONTENT.getStatusCode()
				|| status == Status.NOT_MODIFIED.getStatusCode()
```

**Comment by vietj** [comment]
currently I do have:
```
    boolean isChunked = chunked && !head
      && status != HttpResponseStatus.NO_CONTENT
      && status.code() / 100 > 1;
```

**Comment by FroMage** [comment]
+1
