### ISSUE TITLE
Consider passing websocket close code / reason to the WebSocket closeHandler

### ISSUE THREAD

**Issue by queer** [eclipse-vertx/vert.x#2615]
Since the `closeHandler` callback is just a `Handler<Void>`, dealing with close codes / reasons requires you to add extra code into the `frameHandler` to explicitly check for close frames to get the code / reason, making `closeHandler` have limited utility for non-trivial use-cases. 

Example use-case:

I'm using vert.x to write a wrapper for the [Discord](https://discordapp.com) API. Part of this entails opening a websocket connection to their gateway to receive real-time events. As the gateway may give a variety of close codes / reasons under different circumstances (server restarting, sending a malformed payload, ...), it would be significantly more convenient to be able to handle this in the `closeHandler` rather than needing to have a special case in the `frameHandler`.

**Comment by vietj** [comment]
@queer that's a good idea, however this would be a breaking change, so it might be considered to do in it Vert.x 4.0

**Comment by queer** [comment]
@vietj Would it be possible to just add an overload of `closeHandler` for this case? I understand you might not want to do this, just that it would possibly avoid making it a fully-breaking change.

**Comment by SamOphis** [comment]
+1 this, it's actually a little bothersome not being able to see the close code or the reason and an overload would be perfect

**Comment by vietj** [comment]
adding an overload would be confusing for, however I agree there is need for a solution for Vert.x 3.x, either as a breaking change or as another handler.

**Comment by vietj** [comment]
Overload will confuse the codr generator for rxjava, that’s the main reason.

Let’s break this in 4.0 as there is a work around with frame.

**Comment by nailgilaziev** [comment]
> adding an overload would be confusing for, however I agree there is need for a solution for Vert.x 3.x, either as a breaking change or as another handler.

Hello, Does you have solution for 3.x for now or we need to use handler/frameHandler for it?

**Comment by SamOphis** [comment]
@nailgilaziev you need to use a frameHandler for it until v4 (at least as far as @vietj has said)

**Comment by vietj** [comment]
I believe it should rather be available on the `WebSocketBase` interface as properties that are set when the close frame is received

**Comment by vietj** [comment]
See https://github.com/eclipse-vertx/vert.x/issues/3047
