### ISSUE TITLE
Unidiomatic Ruby example on the home page

### ISSUE THREAD

**Issue by roryokane** [eclipse-vertx/vert.x#2633]
On the home page at https://vertx.io/:

> We provide _idiomatic_ APIs for every language that Vert.x supports.
>
> […]
>
> #### Ruby
>
> ~~~ruby
> $vertx.create_http_server().request_handler() { |req|
>   req.response()
>     .put_header("content-type", "text/plain")
>     .end("Hello from Vert.x!")
> }.listen(8080)
> ~~~

This Ruby example is formatted non-idiomatically, with unnecessary parentheses and the `{}` block syntax. It would be better to write it like this:

~~~ruby
$vertx.create_http_server.request_handler do |req|
  req.response
    .put_header("content-type", "text/plain")
    .end("Hello from Vert.x!")
end.listen(8080)
~~~

(It is not very idiomatic to use global variables `$vertx` either, but I don’t know enough about Vert.x to say it isn’t justified.)

I would have made this a pull request, but I can’t find the code for the Vert.x website in any eclipse-vertx GitHub repo.

**Comment by jponge** [comment]
Hi @roryokane the website repo is at https://github.com/vert-x3/vertx-web-site

**Comment by vietj** [comment]
thanks @jponge for the guidance
