### ISSUE TITLE
Exception not propagated from VertxHandler to WebSocket exceptionHandler

### ISSUE THREAD

**Issue by pvub** [eclipse-vertx/vert.x#2641]
Hello Team,

While investigating a random websocket disconnect issue, I found that the VertxHandler::exceptionCaught() does not propagate the exception all the way to the websocket exceptionHandler. Due to this, when websocket disconnect happens due to an exception, the application's exceptionHandler never logs it, and only gets notified about the close(). 

Version: 3.5.3
Uses vertx-rx and netty's per-message deflate extension.

This is the code I am referring to in VertxHandler:

```
  @Override
  public void exceptionCaught(ChannelHandlerContext chctx, final Throwable t) throws Exception {
    Channel ch = chctx.channel();
    // Don't remove the connection at this point, or the handleClosed won't be called when channelInactive is called!
    C connection = getConnection();
    if (connection != null) {
      ContextImpl context = conn.getContext();
      context.executeFromIO(() -> {
        try {
          if (ch.isOpen()) {
            ch.close(); ---------> Channel is silently cosed
          }
        } catch (Throwable ignore) {
        }
        connection.handleException(t); -----> this here doesn't reach the app's websocket exception handler
      });
    } else {
      ch.close();
    }
  }

```

Is this a known issue? Else, can you please take a look and advice a potential fix?

Thank you,
Udai.

**Comment by vietj** [comment]
can you try with latest vertx snapshots (3.5 and master) ? we fixed this issue recently in vertx both branch https://github.com/eclipse-vertx/vert.x/issues/2610

**Comment by vietj** [comment]
that being said, it sounds different than https://github.com/eclipse-vertx/vert.x/issues/2610

**Comment by vietj** [comment]
can you make a reproducer project ?

**Comment by pvub** [comment]
Will try to get a reproducer. I stumbled into this while investigating a random websocket disconnect due to a bad continuous frame, while using permessage-deflate extension. I'll need to hack a test-server for this.

**Comment by vietj** [comment]
I think you are referring to this code:

https://github.com/eclipse-vertx/vert.x/commit/a7ff4670ce6b19448604f42afdfd1925d64c5bd6#diff-8fbbe2635535500a0f2852a14fc3f426R759

that now properly handles the websocket exception on the client

**Comment by vietj** [comment]
sure, please try with 3.5 branch and master branch

**Comment by vietj** [comment]
@pvub thanks, please report here your findings.

**Comment by pvub** [comment]
Yes, that looks like a fix for this.
