### ISSUE TITLE
Shared data in both local and clustered mode

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vert.x#2654]
Providing shared data structures (locks, counters, async maps) in both local and cluster modes, even when Vert.x is clustered.

**Comment by vietj** [comment]
what is this issue about ?

**Comment by tsegismont** [comment]
@vietj just updated the issue description.

See https://groups.google.com/d/msg/vertx/hk4MtsQCM90/mMFiZSylAQAJ

I asked the user to comment in this issue.

**Comment by tsegismont** [comment]
Closed in #2830
