### ISSUE TITLE
AsyncFile setReadLength 

### ISSUE THREAD

**Issue by ahasani** [eclipse-vertx/vert.x#2655]
Hi,

Could we have `AsyncFile.setReadLength` for streaming/pumping where result can be bigger than max buffer size ie > 2GB.

Cheers

**Comment by vietj** [comment]
can you elaborate more ?

**Comment by vietj** [comment]
I see what you mean now, so readPos and readLength restrict the streaming of the file to a portion

**Comment by ahasani** [comment]
Correct. So read stream would be the same like sendfile without the cost of reopening the file. Having different filechannel for read and write would also leads to inconsistency.

**Comment by vietj** [comment]
I'm wondering if we should not have a synchronous slice operation for an AsyncFile that does that.

**Comment by ahasani** [comment]
Just wonder that you should mate :-). You already have a readFrom, you should have a readTo or readLength. And for big chunk or file without streaming we are at the mercy of buffer length which is limited. Your underlying implementation is already asyncfilechannel anyway. Reading from readPos is also synchronuos.

Cheers

**Comment by ahasani** [comment]
AsyncFile already have a read method that set position and length why i can not stream read it in similar fashion?

**Comment by adietish** [comment]
@vietj what's the plan here? go for a simple #setReadLength or the slicing (which I'd love to get the idea of) that you mentioned?

**Comment by vietj** [comment]
@adietish setReadLength is what we should have given we have setReadPos for consistency

**Comment by adietish** [comment]
@vietj ok, cool. In the doing.

**Comment by ahasani** [comment]
Well this is good news, thanks guys really appreciate this. Then AsyncFile will have ability to serve HTTP RANGE request and or storage block request properly without have to resort to sendFile which is expensive in terms of opening/closing the file.

**Comment by vietj** [comment]
keep in mind that sendFile also does zero copy IO (when there is no compression / SSL) and AsyncFile does not.

**Comment by ahasani** [comment]
@vietj  Noted thanks, this is why many have been asking Vertx team to expose socket and file channels to users. In this regard Vertx is pretty opinionated mostly for the good reasons though, for us not to create many blocking codes. But when we do file I/O its inherently blocking, having channels exposed we can implement zero copy easily. Anyhow this is a great progress mate. Really appreciate Cheers

**Comment by adietish** [comment]
@vietj @ahasani please have a look at https://github.com/eclipse-vertx/vert.x/pull/2757 which implements AsyncFile#setReadLenght (and tests)

**Comment by ahasani** [comment]
Hi, @adietish

Me is nobody mate dont have the capability to review, will run/test and use it with remote possibility to improve it.  its all up @vietj 

Thanks mate, Cheers

**Comment by adietish** [comment]
@vietj dare to please review my patch?

**Comment by adietish** [comment]
@ahasani #2757 was merged, AsyncFile now offers #setReadLength to limit the number of bytes being read from the file.
@vietj This issue can now be closed.
