### ISSUE TITLE
Websocket client HTTP header response callback

### ISSUE THREAD

**Issue by swinterberger** [eclipse-vertx/vert.x#2662]
Would the vert.x team be open to a PR which exposes yet another callback to be passed into httpClient.websocket that allows a user to receive the HTTP headers returned by the sever after the websocket handshake succeeds?

The issue is that we load balance on the server end based on a cookie, the cookie is auto generated by HAProxy when not present in a request and it includes the name of the backend node the request should route to.  We need this cookie for session identity because we occasionally open multiple websocket channels from a single client.  It makes our lives easier if secondary websocket channels can be forwarded to the same backend node as the original, or if we have to reconnect the initial channel.

I was unable to get this information back even via reflection because it is quickly discarded so I had to fork and modify the code to add a handler.  Since I see no other issues related to this, maybe we are an oddity therefore I am curious if the PR would be welcome.  Feel free to close if not and we will maintain our fork.

**Comment by swinterberger** [comment]
@vietj that was actually the first way I had it but wasnt sure if keeping that data attached to the WebSocketBase indefinitely was ideal.  I will switch it back to a getter and I have to add some unit tests.  

I will try to find time to wrap that up today or over the weekend.

**Comment by vietj** [comment]
@swinterberger just make it present during the Handler<AsyncResult<WebSocket>> callback and drop the data after, say it in the javadoc. It's fine.

**Comment by vietj** [comment]
response headers are now provided on `WebSocketBase`
