### ISSUE TITLE
Can we upgrade netty to support Java11

### ISSUE THREAD

**Issue by gillbates** [eclipse-vertx/vert.x#2665]
Dear Vertx Team,

since Java11 is already out there. When we run with vertx, it will always pop out following words in logs:

> cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module

since netty has already fixed this issue, can we update it also?

cheers,
gb

**Comment by vietj** [comment]
I mean that vertx itself does not use Unsafe, its only via  Netty, since we have a more recent version it should be ok, although we are not using the very latest version.
