### ISSUE TITLE
Allow to put object that doesn't implement Shareable into LocalMap

### ISSUE THREAD

**Issue by mkpaz** [eclipse-vertx/vert.x#2666]
`Shareable` interface is used in two ways:
* to verify object before putting it into map;
* to create a copy of mutable object before returning it;

The first is worthless. It actually doesn't help to write safe code because there is no way to define whether object thread-safe or not. Rather it's an obstacle because now it's impossible to share any object that comes from 3rd-party library without implementing some kind of holder. For instance what I want to share a DataSource. A dependency injector? There are many thread-safe classes in Java world around Vert.x and no one of them implement `io.vertx.core.shareddata.Shareable`.

If you want to warn about how dangerous is to share object state between threads, please, do it in the docs. Since Vert.x is unopinionated, do not force to write boilerplate code just to avoid unnecessary checks.

**Comment by Tembrel** [comment]
Some specific examples: Guava's `Immutable`-prefixed types should be allowed as keys and values in shared data maps, and anything annotated with ErrorProne's `@Immutable`.

**Comment by tsegismont** [comment]
`LocalMap` is a convenience and it does a few reasonable checks to make sure non shareable objects are incidentally used as keys or values.

Vert.x is indeed unopiniated, so if you work with immutable objects, it is totally fine to create your own concurrent map. This map can be provided as a constructor argument for the verticle or held in a singleton.

**Comment by Tembrel** [comment]
Well ... yeah, but it would be __more__ convenient if it understood that true immutability implies local shareability, i.e., copy by reference. That's not opinion, that's what true immutability implies.
