### ISSUE TITLE
Quest for database cache

### ISSUE THREAD

**Issue by leenux** [eclipse-vertx/vert.x#2674]
Can I use database cache and  how to do?same as spring  boot @Cacheable

**Comment by tsegismont** [comment]
Vert.x is not a framework and it will not automatically cache database query results with an annotation.

Vert.x as a `SharedData` API which you can use to store database query results in an `AsyncMap`. `AsyncMap` has methods to put data with expiration (`ttl`).

In verticle `start` method:

```java
    vertx.sharedData().getAsyncMap("database-results", ar -> {
      if (ar.succeeded()) {
        AsyncMap asyncMap = ar.result();
        // store asyncMap in verticle
      } else {
        // handle failure
      }
    });
```

then

```java
        asyncMap.get(query, ar -> {
          if (ar.succeeded()) {
            // Use result from cache
            if (ar.result() != null) {
              // Use result from cache 
            } else {
              // Query from database and put in cache with put ttl
            }
          }
        });
```

I would recommend to post further questions to the user forum, not all community members are subscribed to GH issues. See https://vertx.io/community

**Comment by leenux** [comment]
Thank you @tsegismont 
I know we should put the question on the forum, but it's very difficult for Chinese developers to visit the forum. I'm sorry for the trouble.

**Comment by tsegismont** [comment]
@leenux I understand. Then I would suggest to use the [`vert-x3/issues`](https://github.com/vert-x3/issues) repository rather than the actual project issues, which we use for bug reports.
