### ISSUE TITLE
vertx-js example causes warning

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vert.x#2679]
Moved from https://github.com/vert-x3/vertx-web/issues/1017

### Version

* vert.x core: 3.5

### Context

Following the [very first example](https://vertx.io/docs/vertx-core/js/#_in_the_beginning_there_was_vert_x) on the vertx documenation js version causes the following warning on the console:

`WARNING: You're already on a Vert.x context, are you sure you want to create a new Vertx instance?`

Code looks to be work fine until you start to use some clustering API-s, where they just won't function as expected. I believe because we're on a differently configured context by now.

### Do you have a reproducer?

```javascript
var Vertx = require("vertx-js/vertx");
var vertx = Vertx.vertx();
```

### Solution

As I found out from the examples the vertx variable is already defined js verticles, so the above initialization is not required.

If this is true in every cases then the documentation should be updated to reflect this, otherwise it should be more clear describing when the vertx is already defined and when not.

Many thanks

**Comment by tsegismont** [comment]
[7e5276eec](https://github.com/eclipse-vertx/vert.x/commit/7e5276eec5b76a0f72a108a448e0daefe89bf508?diff=split&w=1) partially solves this issue: the redundant `Vert.x` instance has been removed in `FileSystem` examples. 

Now we need to override the parts of the docs where a Vert.x instance is created in order to show a specific configuration aspect. For example:

```java
var vertx = Vertx.vertx({
  "addressResolverOptions" : {
    "servers" : [
      "192.168.0.1",
      "192.168.0.2:40000"
    ]
  }
});
```

This name resolver example could be replaced by a sample JSON options file to be used with the new `-option` CLI argument.

**Comment by vietj** [comment]
thanks for this @tsegismont

**Comment by tsegismont** [comment]
Eventually fixed with https://github.com/eclipse-vertx/vert.x/commit/062c54e06ce7fb99fa1d9d159939d5ea0f8da19a and https://github.com/vert-x3/vertx-lang-js/commit/83e559480f49176d87f755505e296be0cdacb9e3
