### ISSUE TITLE
Redeploy inside docker container fails

### ISSUE THREAD

**Issue by CharlieTap** [eclipse-vertx/vert.x#2682]
I'm trying to create a development environment inside Docker for Vert.x, I have the file system mounted and the file watcher is successfully detecting changes. However when a change occurs the redeploy task ./gradlew classes fails with the following:

INFO: Redeploying!
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

Despite the failure Vert.x subsequently reboots but with the stale code as the recompilation never occurs. Whats odd is if there was an issue with the wrapper it would have occurred when the container boots as its started with the command: ./gradlew clean run

Any help would be much appreciated

**Comment by tsegismont** [comment]
@CharlieTap can you post your question to the user forum? We use issues for bug reporting, not than usage questions (not everyone in the community is subscribed to GH issues, you have better chances of getting an answer on the forum). Thank you
