### ISSUE TITLE
Have some plan to support game server？

### ISSUE THREAD

**Issue by zl810881283** [eclipse-vertx/vert.x#2687]
I just learning about vert.x. I think it is suitable for PvP MMO game server for its speed.

Anyone use vert.x for game server?

Or official support plan?

**Comment by vietj** [comment]
can you ask this rather on the google group https://groups.google.com/forum/#!forum/vertx or on twitter with `@vertx_project` handle ?

**Comment by vietj** [comment]
we don't plan to provide game server support

**Comment by vietj** [comment]
maybe @pmlopes can provide more insights on this though
