### ISSUE TITLE
Support for distributed queues

### ISSUE THREAD

**Issue by acabarbaye** [eclipse-vertx/vert.x#2691]
Could the `ClusterManager` be extended to expose [shared/distributed queues](https://docs.hazelcast.org/docs/3.0/manual/html/ch02s02.html) provided by underneath cluster managers in the same way as `AsyncMap`?

**Comment by vietj** [comment]
this feature seems specific to Hazelcast and I don't think it would exposed equally well with other cluster manager implementations.

WDYT @tsegismont ?

**Comment by tsegismont** [comment]
@vietj right.

We should refrain from adding new features to the clustering SPI. It raises the bar for community implementations. And clustering should provide clustered eventbus mostly, not every possible shared data structure.
