### ISSUE TITLE
NetServer not using every eventloop thread

### ISSUE THREAD

**Issue by wkgcass** [eclipse-vertx/vert.x#2701]
Hi,
I'm writing a tcp server using vertx NetClient, however i found that even if i start multiple servers and listen at the same time, the handler won't using every eventloop thread.

Here's the example code:

vertx: 3.5.3

```java
package com.netease.connectiontest;

import io.vertx.core.Vertx;
import io.vertx.core.VertxOptions;
import io.vertx.core.net.NetServer;

public class TestMain {
    public static void main(String[] args) {
        Vertx vertx = Vertx.vertx(new VertxOptions().setEventLoopPoolSize(4));
        for (int i = 0; i < 4; ++i) {
            NetServer server = vertx.createNetServer();
            server.connectHandler(sock -> {
                sock.write("Hello world\r\n");
                sock.handler(buf -> {
                    System.out.println(Thread.currentThread());
                });
            });
            server.listen(8080);
        }
    }
}
```

then repeating telnet -> send some msg -> quit telent

The result I imagine would be printing vert.x-eventloop-thread-(0 to 3), however the output ranges from 1 to 3, where 0 was never printed.

I check the source code and found that when the first `server.listen` is called, it tries to resolve the local socket host, even if the host is set to 0.0.0.0. The resolve process will start a UDP sock for DNS. The UDP sock will use the second EventLoop element inside the PowerOfTwoEventExecutorChooser.

`io.netty.util.concurrent.DefaultEventExecutorChooserFactory` line 56:

```java
        @Override
        public EventExecutor next() {
            return executors[idx.getAndIncrement() & executors.length - 1];
        }
```

`executors[0]` will be used by the first tcp server
`executors[1]` will be used by the udp sock
`executors[2]` will be used by the second tcp server
`executors[3]` will be used by the third tcp server

then

`executors[0]` will be used by the last tcp server, where it's the same as the first one. And the DNS lookup will not bu used very often, so the result would be: one event loop thread not doing anything.

I'm wondering whether this is a bug? This is easy to fix, just set the event loop to 5. But if the vertx is upgraded, I must check whether there are any new process fetching event loop from the `chooser`.

And I don't see it very clear that: why the event loop should be set to 2 * cores. If all libs i'm using are async (async-mysql-client/webclient/redisclient and so on), I think I won't get better performance when setting event loop size to ${a number > cores} than ${= cores} (or change it to ${cores - 1} if considering soft interrupt).

Looking forward to your reply~thx
^_^

**Comment by vietj** [comment]
we should have the UDP sock reuse the same event loop instead of creating a new one.

**Comment by vietj** [comment]
actually it is using the correct event loop, what happens is that you are not running your code inside a verticle but from a main thread.

Doing:

```
public class Main {
  public static void main(String[] args) {
    Vertx vertx = Vertx.vertx(new VertxOptions().setEventLoopPoolSize(4));
    for (int i = 0; i < 4; ++i) {
      vertx.getOrCreateContext().runOnContext(v -> {
        NetServer server = vertx.createNetServer();
        server.connectHandler(sock -> {
          sock.write("Hello world\r\n");
          sock.handler(buf -> {
            System.out.println(Thread.currentThread());
          });
        });
        server.listen(8080);
      });
    }
  }
}
```

**Comment by vietj** [comment]
Doing this would work as well:

```
public class Main {
  public static void main(String[] args) {
    Vertx vertx = Vertx.vertx(new VertxOptions().setEventLoopPoolSize(4));
    vertx.deployVerticle(() -> new AbstractVerticle() {
      @Override
      public void start() throws Exception {
        NetServer server = vertx.createNetServer();
        server.connectHandler(sock -> {
          sock.write("Hello world\r\n");
          sock.handler(buf -> {
            System.out.println(Thread.currentThread());
          });
        });
        server.listen(8080);
      }
    }, new DeploymentOptions().setInstances(4));
  }
}
```
