### ISSUE TITLE
File descriptor leak when using WebClient

### ISSUE THREAD

**Issue by kjstouffer** [eclipse-vertx/vert.x#2705]
Enviornment Information:
```
------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_172 (Oracle Corporation 25.172-b11)
OS:           Mac OS X 10.14.1 x86_64
```
Reproducer: https://github.com/kjstouffer/vertx-fd-issue-repro (README with more detailed information)

FD open/close log generated by http://file-leak-detector.kohsuke.org/ : [files-2-loops.log](https://github.com/eclipse-vertx/vert.x/files/2566586/files-2-loops.log)

This issue only happens when an exception happens (a Timeout in this case), but not in every combination of timeout / number of requests. for example, with number of request set to `10` and timeout set to `8000`ms, the issue does not appear (only 2 requests fail), however, when the number of requests is `20` and timeout set to `8000`ms, the issue does appear (12 requests fail).

I'm wondering if I'm doing something wrong in my reproducer or if there's a bug in the underlying implementation that's supposed to close / free sockets.

**Comment by vietj** [comment]
can you open this issue on the vertx-web repository instead ?
