### ISSUE TITLE
io.vertx.core.net.SocketAddress.NetworkMetrics#bytesRead and bytesWritten do not contain headers

### ISSUE THREAD

**Issue by heyile** [eclipse-vertx/vert.x#2715]
default void bytesWritten(S socketMetric, SocketAddress remoteAddress, long numberOfBytes) {
  }
  default void bytesRead(S socketMetric, SocketAddress remoteAddress, long numberOfBytes) {
  }
the numberOfBytes only contains the body length.

   numberOfBytes  equals  buff.getBytes().length

    HttpClient localhost = http2Client.getNow(8080, "localhost", "", resp -> {
      resp.bodyHandler(buff -> {
        System.out.println(buff.getBytes().length);
      });

**Comment by heyile** [comment]
is it a design or a bug ?

**Comment by heyile** [comment]
https://github.com/heyile/vertx-demo/tree/h1AndH2c

**Comment by vietj** [comment]
you mean for HTTP request and responses ?

**Comment by heyile** [comment]
@vietj  yes

**Comment by heyile** [comment]
maybe it's better to contains the length of headers ?

**Comment by vietj** [comment]
I agree, however I don't know how this could be achieved since these are decoded by Netty

**Comment by vietj** [comment]
so we lose the length

**Comment by vietj** [comment]
and also encoded by netty

**Comment by heyile** [comment]
:-} ok, thanks a lot. @vietj
