### ISSUE TITLE
AsyncFile should accept empty buffer writes instead of throwing an IllegalStateException

### ISSUE THREAD

**Issue by heyile** [eclipse-vertx/vert.x#2730]
@vietj  I need some help.

**pom:**
```
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-core</artifactId>
      <!--<version>3.5.3</version>-->
      <version>3.6.0.CR1</version>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-boringssl-static</artifactId>
      <version>2.0.12.Final</version>
    </dependency>
```

**server:** 
```

public class HttpServerDownloadTest {
    public static void main(String[] args) {
        HttpServerOptions httpServerOptions = new HttpServerOptions();
        httpServerOptions.setUseAlpn(true)
                .setSsl(true)
                .setPemKeyCertOptions(new PemKeyCertOptions().setKeyPath("tsl/server-key.pem").setCertPath("tsl/server-cert.pem"));
        Vertx vertx = Vertx.vertx();
        HttpServer httpServer = vertx.createHttpServer(httpServerOptions);
        httpServer.requestHandler(request -> {
            request.bodyHandler(body -> {
                System.out.println("server : " + body.toString());
            });
            String file = "filePath";
            request.response().headers().set("Content-Disposition", attachment;filename=tempFileEntity.txt");
            request.response().sendFile(file);
        });
        httpServer.listen(8080, "localhost", req -> {
            if (req.succeeded()) {
                System.out.println("bind port :" + req.result().actualPort());
            } else {
                System.out.println("bind port error");
            }
        });
    }
}
```

**client:**
```

public class HttpClientTest {
    public static void main(String[] args) {
        Vertx vertx = Vertx.vertx();
        String filePath = "filePath";
        HttpClientOptions http2ClientOption = new HttpClientOptions();
        http2ClientOption.setProtocolVersion(HttpVersion.HTTP_2)
                .setUseAlpn(true)
                .setHttp2ClearTextUpgrade(false)
                .setTrustAll(true)
                .setSsl(true)
                .setDefaultPort(8080)
                .setDefaultHost("localhost");
        HttpClient httpClient = vertx.createHttpClient(http2ClientOption);
        HttpClientRequest httpClientRequest = httpClient.request(HttpMethod.POST, "", res -> {
            res.pause();
            vertx.fileSystem().open(filePath, new OpenOptions(), ares -> {
                AsyncFile file = ares.result();
                Pump pump = Pump.pump(res, file);
                res.endHandler(v1 -> {
                    System.out.println("end...");
                    file.flush().close(v2 -> {
                        System.out.println(" download success");
                    });
                });
                pump.start();
                res.resume();
            });
        });
        httpClientRequest.setChunked(true);
        httpClientRequest.end("hello");
    }
}

```
**when I start the server and client. the file download successfully. but it will throw an exception**

```
十一月 22, 2018 9:55:03 上午 io.vertx.core.http.impl.HttpClientResponseImpl
严重: io.vertx.core.VertxException: Connection was closed
十一月 22, 2018 9:55:03 上午 io.vertx.core.http.impl.HttpClientResponseImpl
严重: java.lang.IllegalStateException: Cannot save zero bytes
end...
 download success
```

**How can I avoid this exception or can I ignore this exception?**

**Comment by vietj** [comment]
I don't have this error running the reproducer

**Comment by vietj** [comment]
but I had to fix the file pathes

**Comment by vietj** [comment]
String filePath = "src/main/java/com/rkd/to.txt";
and
            String file = "src/main/java/com/rkd/from.txt";

**Comment by vietj** [comment]
a full stack trace would be helpful too

**Comment by heyile** [comment]
@vietj  thanks very much.
It's very strange that you can not make a reproducer.  maybe you can  try  to add an exceptionHandler.
client:
```
        HttpClientRequest httpClientRequest = httpClient.request(HttpMethod.POST, "", res -> {
            res.pause();
            vertx.fileSystem().open(filePath, new OpenOptions(), ares -> {
                AsyncFile file = ares.result();
                Pump pump = Pump.pump(res, file);
               // here add a exception handler
                res.exceptionHandler(e -> {
                    System.out.println("in :");
                    e.printStackTrace();
                });
                res.endHandler(v1 -> {
                    System.out.println("end...");
                    file.flush().close(v2 -> {
                        System.out.println(" download success");
                    });
                });
                pump.start();
                res.resume();
            });
        });
```
**the logging is showed as bellow:**
十一月 23, 2018 8:37:19 上午 io.vertx.core.http.impl.HttpClientResponseImpl
严重: io.vertx.core.VertxException: Connection was closed
java.lang.IllegalStateException: Cannot save zero bytes
	at io.vertx.core.file.impl.AsyncFileImpl.doWrite(AsyncFileImpl.java:374)
	at io.vertx.core.file.impl.AsyncFileImpl.doWrite(AsyncFileImpl.java:182)
	at io.vertx.core.file.impl.AsyncFileImpl.write(AsyncFileImpl.java:190)
	at io.vertx.core.file.impl.AsyncFileImpl.write(AsyncFileImpl.java:53)
	at io.vertx.core.streams.impl.PumpImpl.lambda$new$1(PumpImpl.java:59)
	at io.vertx.core.http.impl.HttpClientResponseImpl.handleChunk(HttpClientResponseImpl.java:211)
	at io.vertx.core.http.impl.Http2ClientConnection$Http2ClientStream.handleData(Http2ClientConnection.java:217)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:225)
	at io.vertx.core.streams.impl.InboundBuffer.drain(InboundBuffer.java:217)
	at io.vertx.core.streams.impl.InboundBuffer.lambda$fetch$1(InboundBuffer.java:265)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
in :
end...
 download success

**Comment by heyile** [comment]
JAVA version:
C:\Users\h00451788>java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
OS: both with win7  win10

**Comment by heyile** [comment]
the  software I use to develop is  IntelliJ IDEA Community

**Comment by adietish** [comment]
@heyile @vietj I can reproduce it.
note: the file path had to be changed in both, the client and the server.
I'm lacking vertx knowledge but I see the following:
AsyncFileImpl#write(Buffer buffer) is called twice. The first occurrence correctly writes the bytes, no error occurrs. The 2nd occurrence then treats an EmptyByteBuf (wrapped in netty/UnreleasableByteBuf within vertx/BufferImpl) which has a length of 0.
A few steps further down #doWrite therefore throws the illegal state ex:
```
  private void doWrite(ByteBuffer buff, long position, long toWrite, Handler<AsyncResult<Void>> handler) {
    if (toWrite == 0) {
      throw new IllegalStateException("Cannot save zero bytes");
    }
```

**Comment by heyile** [comment]
@adietish  yes,  there is a EmptyByteBuf suddenly appear  in the pending stack. I first find the problem in the 3.5.3, but do not know why. And now, I avoid it by replace PumpImpl.
```
  public PumpImpl(ReadStream<T> readStream, WriteStream<T> writeStream) {
    this.readStream = readStream;
    this.writeStream = writeStream;
    drainHandler = v -> readStream.resume();
    dataHandler = data -> {
      if (data instanceof Buffer) {
        if (((Buffer) data).length() == 0) {
          return;
        }
      }
      writeStream.write(data);
      incPumped();
      if (writeStream.writeQueueFull()) {
        readStream.pause();
        writeStream.drainHandler(drainHandler);
      }
    };
  }
```

**Comment by vietj** [comment]
I think writing an empty byte buff should just be allowed in AsyncFile

**Comment by vietj** [comment]
so it's related to HTTP/2 ?

**Comment by heyile** [comment]
@vietj  yes, http1 do not have this problem

**Comment by vietj** [comment]
ok thanks, I will simply add a test for writing zero bytes

**Comment by heyile** [comment]
@vietj  thanks a lot

**Comment by adietish** [comment]
@vietj sure, I'd love to try to.
