### ISSUE TITLE
AsyncMap keys, values not available through reactivex/core

### ISSUE THREAD

**Issue by stergiom** [eclipse-vertx/vert.x#2733]
> Related to: #2020
> Methods available: [core/shareddata/AsyncMap](https://vertx.io/docs/apidocs/io/vertx/core/shareddata/AsyncMap.html)
> Methods not available: [reactivex/core/shareddata/AsyncMap](https://vertx.io/docs/apidocs/io/vertx/reactivex/core/shareddata/AsyncMap.html)

- Is there a way to gain access to these methods from `reactivex/core` even if they are not the rx variant?
- Will there be an observable returning rx variant?

**Comment by vietj** [comment]
I think we could expose them using the gen ignore that permits this for RX

**Comment by stergiom** [comment]
It agrees with `keys` and `values`, but the CodeGenProcessor seems to be running into trouble with `entries`;

```
SEVERE: io.vertx.codegen.CodeGenProcessor - Could not generate model for io.vertx.core.shareddata.AsyncMap#entries(io.vertx.core.Handler<io.vertx.core.AsyncResult<java.util.Map<K,V>>>): type io.vertx.core.Handler<io.vertx.core.AsyncResult<java.util.Map<K,V>>> is not legal for use for a parameter in code generation
```

Related to this functionality, it would be nice to see;
- An _AsyncList_ (and _AsyncSet_) tie back to Hazelcast's (and others') [distributed list](https://docs.hazelcast.org/docs/latest-development/manual/html/Distributed_Data_Structures/List.html)/set, for the same reasons that AsyncMap makes sense.
- Access to [EventListener](https://docs.hazelcast.org/docs/latest-development/manual/html/Distributed_Events/Distributed_Object_Events/Listening_for_Map_Events.html) functionality of data structures for cases where it would make more sense to be notified of certain events while still being able to interact with structures when needed.

For scenarios where nodes are transient and the cluster is not dealing with very large data structures, nodes being able to access what they need when joining, –then be notified of changes while they are about is a nice convenience. Distributed-data-structure-generated-events for these cases could lessen the likelihood of having to maintain separate pub/sub channels (or other forms of explicit notification).

**Comment by vietj** [comment]
there are some generics that cannot be mapped in codegen like extends/super

**Comment by tsegismont** [comment]
>
> Related to this functionality, it would be nice to see;
>
>    - An *AsyncList* (and *AsyncSet*) tie back to Hazelcast's (and
>    others') distributed list
>    <https://docs.hazelcast.org/docs/latest-development/manual/html/Distributed_Data_Structures/List.html>/set,
>    for the same reasons that AsyncMap makes sense.
>
> I'm not inclined to go this route. The reason is not all cluster managers
are based on data grids, so in the end the community need to maintain
features which do not really fit.

Given Hazelcast in recent versions officially supports async versions of
its data structures, you can use them easily with vert.x (with a small
adapter to get back on the event loop).


>
>    - Access to EventListener
>    <https://docs.hazelcast.org/docs/latest-development/manual/html/Distributed_Events/Distributed_Object_Events/Listening_for_Map_Events.html>
>    functionality of data structures for cases where it would make more sense
>    to be notified of certain events while still being able to interact with
>    structures when needed.
>
> Same here.

If you're willing to contribute, I believe the best option is to create a
Vert.x client for Hazelcast data grid. I can help with that.

**Comment by vietj** [comment]
+1 @tsegismont
