### ISSUE TITLE
Undocumented breaking change in HttpServerResponse::setChunked(true) from 3.5.3 to 3.5.4

### ISSUE THREAD

**Issue by johansnow** [eclipse-vertx/vert.x#2739]
In Vertx 3.5.3 chunked transfer encoding could be enabled by 
1. Call response.setChunked(true)
2. Call response.headers().setAll(responseToProxiedRequest.headers().remove("content-length"))

In Vertx 3.5.4 the above call order breaks with
> IllegalStateException: You must set the Content-Length header to be the total size of the message body BEFORE sending any data if you are not using HTTP chunked encoding.
Please note that headers().remove("content-length") was not a requirement for getting/retaining chunked transfer encoding in 3.5.3. That call just adds clarity by leading to an IllegalStateException whenever chunked transfer encoding is not enabled.

Vertx 3.5.4 require that the call order be reversed. I.e.
1. Call response.headers().setAll(responseToProxiedRequest.headers().remove("content-length"))
2. Call response.setChunked(true)

I would not expect the behaviour of 3.5.4 unless chunked transfer-encoding was enabled and disabled by setting the appropriate header (with a call to header().set("transfer-encoding", "chunked")), rather than controlling it through a separate instance method.

Given the presence of the setChunked instance method , I do expect the behaviour of 3.5.3: That only explicit calls to setChunked can enable and disable chunked transfer encoding, and that the appropriate transfer-encoding header be set accordingly.

According to https://greenbytes.de/tech/webdav/rfc2616.html#rfc.section.4.4:
> Messages MUST NOT include both a Content-Length header field and a non-identity transfer-coding. If the message does include a non-identity transfer-coding, the Content-Length MUST be ignored

Neither Vertx 3.5.3, nor 3.5.4 removed or prevented the content-length header from being set when chunked transfer encoding is enabled. I don't see a problem with it, because I can control this behaviour in my implementation. But if you really do feel that it is desireable for headers().setAll to be an implicit call to setChunked(false),  then I strongly believe you should do the same whenever the content-length header is set. I also believe you should change the documentation by
1. Adding a note about this breaking change in the release notes for 3.5.4
2. Changing the documentation for both ::setChunked and headers::setAll to clearly state that calls to these methods are inter-dependent as well as document the impact of different method call ordering.

**Comment by vietj** [comment]
can you show the code that makes this behavior ?

it might be a regression and not intentional.

**Comment by johansnow** [comment]
Certainly. It should be possible to slim the reproduction test case down by removing the proxied request. I wrote it this way while trying to figure out what was going wrong, because it closely resembles our production use-case.

Simply locate the two lines with "responseToClient.setChunked(true)" (one commented, one used) to get to the heart of the issue.

```
import io.reactivex.Observable;
import io.vertx.core.DeploymentOptions;
import io.vertx.core.VertxOptions;
import io.vertx.junit5.Timeout;
import io.vertx.junit5.VertxExtension;
import io.vertx.junit5.VertxTestContext;
import io.vertx.reactivex.core.Vertx;
import io.vertx.reactivex.core.http.*;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;

@ExtendWith(VertxExtension.class)
public class ChunkTester {
	static Logger logger = LogManager.getLogger(ChunkTester.class);

	static Vertx vertx = Vertx.vertx();

	@Test
	@Timeout(value = 5, timeUnit = TimeUnit.SECONDS)
	public void testCallOrder(VertxTestContext context) {
		logger.debug("Test A started");
		System.out.println("foo!");

		var serviceServer = vertx.createHttpServer()
			.requestHandler(proxyToService -> {
				var r = proxyToService.response();
				String response = "Lorem ipsum dolor sit amet consecseomthing or other.";
				r.putHeader("content-length", "" + response.length());
				r.putHeader("content-type", "text/plain");
				r.end(response);
			});

		var proxyServer = vertx.createHttpServer()
			.requestHandler(clientToProxy -> {
				HttpServerResponse responseToClient = clientToProxy.response();

				var requestToService = vertx.createHttpClient()
					.get(8081, "127.0.0.1", "/");

				requestToService.handler(serviceResponse -> {
					System.out.println("Headers set by service, with headers " + serviceResponse.headers().getDelegate().entries());
					responseToClient.setChunked(true);	// works in Vertx 3.5.3. build with 3.5.4 for IllegalStateException
					responseToClient.headers().setAll(serviceResponse.headers().remove("content-length"));
					// responseToClient.setChunked(true);	// With Vertx 3.5.4, must be called after .headers().setAll

					/*
					responseToClient.headers().set("content-length", "123");	// but 3.5.4 does not modify transfer-encoding when setting only the content-length header (same as 3.5.3)
					*/

 					serviceResponse.handler(data -> {
						System.out.println("Proxy received data from service");

						responseToClient.write(data);
					});
					serviceResponse.endHandler((VOID) -> {
						responseToClient.end();
					});
					serviceResponse.exceptionHandler(t -> {
						context.failNow(t);
					});
				});

				requestToService.end();
			});


		serviceServer.rxListen(8081)
			.flatMap(service -> proxyServer.rxListen(8080))
			.doOnSuccess(proxy -> {
				System.out.println("service and proxy listening");

				var request = vertx.createHttpClient()
					.get(8080, "127.0.0.1", "/");

				request.handler(proxyResponse -> {
					System.out.println("Headers set by proxy: " +
						proxyResponse.headers().getDelegate().entries());

					proxyResponse.handler(data -> {
						System.out.println("client received proxy data");

					});
					proxyResponse.endHandler(VOID -> {
						context.completeNow();
					});
					proxyResponse.exceptionHandler(t -> {
						context.failNow(t);
					});
				});

				request.end();
			})
			.subscribe();

	}
}
```

**Comment by vietj** [comment]
can you give a try with 3.6.0 (available in central) to see how it behaves ?

**Comment by johansnow** [comment]
Vertx 3.6.0 behaves the same way as 3.5.4, so the issue is still present.

**Comment by tsegismont** [comment]
Outdated
