### ISSUE TITLE
EventBusMetrics  add messageSent(String address, Boolean publish, Boolean local, Boolean remote, ServerID sid)  method

### ISSUE THREAD

**Issue by hedyn** [eclipse-vertx/vert.x#2740]
Add
`void messageSent(String address, Boolean publish, Boolean local, Boolean remote, ServerID sid) `
 method to the EventBusMetrics class to help track the delivery of event bus messages across cluster nodes

**Comment by vietj** [comment]
good idea, wdyt @jotak @tsegismont ?

**Comment by tsegismont** [comment]
@hedyn can you elaborate on how would you use it to build metrics?

I'm reluctant to introduce a type like `ServerID` in the metrics SPI (I'm not even sure we'd keep it in Vert.x 4, due to #1529)

**Comment by vietj** [comment]
a mere String or SocketAddress would be fine ?

**Comment by tsegismont** [comment]
`String` would be better. In Vert.x 4, I'm not sure the `host:port` combo will be the server id

**Comment by jotak** [comment]
I guess it could have potentially unbounded values, so it's a new label that wouldn't be enabled by default in the micrometer implementation, but yes, no objection for that.

**Comment by hedyn** [comment]
> @hedyn can you elaborate on how would you use it to build metrics?
> 
> I'm reluctant to introduce a type like `ServerID` in the metrics SPI (I'm not even sure we'd keep it in Vert.x 4, due to #1529)

@tsegismont I just want to know which cluster node the message was sent to, can be ServerID or String
