### ISSUE TITLE
Deprecate the HttpClient request/response methods that use an Handler<HttpClientResponse>

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#2743]
HttpClient request/response methods are using in Vert.x 3 patterns using an Handler<HttpClientResponse>. For obvious reasons we want to use instead Handler<AsyncResult<HttpClientResponse>> in Vert.x 4. The WebClient provides already this in Vert.x 3.x and it is the advocated client for high level operations so we don't need to provide replacement for these operations, only to deprecate them.

This issue tracks the deprecation happening in Vert.x 3.6

**Comment by xenv** [comment]
In the document, `getNow()` is still written, but it's deprecated. It's not clear how to migrate to new methods, from the comment or document.

**Comment by vietj** [comment]
@xenv you should use the Vert.x WebClient instead, this has been clarified in the recent javadoc : https://vertx.io/docs/vertx-web-client/java/

**Comment by vietj** [comment]
note that you can keep using it @xenv, however these methods will break in Vert.x 4.0 to use an `Handler<AsyncResult<HttpClientResponse>>` instead of `Handler<HttpClientResponse>` (which would make programming with the client easier)

**Comment by HiranmayaGundu** [comment]
@vietj we use this handler to write test cases for our vertx routes, and we don't really need the additional dependency for test cases. Is there a way to migrate to using `Handler<AsyncResult<HttpClientResponse>>`?  This pattern was advocated for in this blog post: https://vertx.io/blog/unit-and-integration-tests/

**Comment by vietj** [comment]
you can use the vertx-web-client instead that remains unchanged in 4.0
