### ISSUE TITLE
[Request] Add global MessageCodec

### ISSUE THREAD

**Issue by ufoscout** [eclipse-vertx/vert.x#2762]
It would be good to be able to register a global MessageCodec to be used when a specific codec for a message is not provided.
As of today (Vertx 3.6.0) when a message without a registered MessageCodec is sent through the event bus, a RuntimeError is thrown. Nevertheless, most of the time a silent fallback to a default codec would be enough.

For example, in our current application, we want that all messages are sent in Json format; we have tens of different messages and we are forced to register for each of them a specific codec.

**Comment by vietj** [comment]
you mean a default codec ?

**Comment by ufoscout** [comment]
@vietj I mean a single generic message codec able to handle messages of whatever class type.

In this situation:
```
// My app sends 100 different types of messages on the bus
class MyMessageType1 {...}
class MyMessageType2 {...}
...
class MyMessageType100 {...}

// To make it work I have to register 100 default MessageCodec(s)
var bus = vertx().eventbus();

bus.registerDefaultCodec(MyMessageType1.class, new MyMessageType1_codec());
bus.registerDefaultCodec(MyMessageType2.class, new MyMessageType2_codec());
...
bus.registerDefaultCodec(MyMessageType100.class, new MyMessageType100_codec());
```
However, in my case ALL of the MessageCodecs are exactly the same! they always serialize/deserialize using vertx.Json. So I ended up having a single MessageCodec that I have to manually register for each message type. This is the (kotlin) code of it:
```kotlin
class JsonMessageCodec<T>(private val clazz: Class<T>): MessageCodec<T, T> {

    override fun encodeToWire(buffer: Buffer, customMessage: T) {
        buffer.appendString(Json.encode(customMessage))
    }

    override fun decodeFromWire(position: Int, buffer: Buffer): T {
        val length = buffer.getInt(position)
        val end_position = position + length
        val jsonStr = buffer.getString(position , end_position)
        return Json.decodeValue(jsonStr, clazz)
    }
    ...
}
```

Using this generic JsonMessageCodec, the eventbus setup becomes a long list of boilerplate code (pseudo code):
```
// Register 100 the same MessageCodec
var bus = vertx().eventbus();

bus.registerDefaultCodec(MyMessageType1.class, new JsonMessageCodec(MyMessageType1.class));
bus.registerDefaultCodec(MyMessageType2.class, new JsonMessageCodec(MyMessageType2.class));
...
bus.registerDefaultCodec(MyMessageType100.class, new JsonMessageCodec(MyMessageType100.class));
```

Instead of that, it would be good if it was possible to do something like:
```
var bus = vertx().eventbus();
// Here the fallback codec is used for all the messages that do not have a specific MessageCodec
bus.registerFallbackCodec(new JsonMessageGlobalCodec{});
```

The structure of this "global" codec should be a little different than the existing MessageCodec, in fact, the class type to convert from/to should be in the methods parameter. For example:
```kotlin
class JsonMessageCodec: GlobalMessageCodec {

    override fun encodeToWire<T>(clazz: Class<T>, buffer: Buffer, customMessage: T) {
        buffer.appendString(Json.encode(customMessage))
    }

    override fun decodeFromWire<T>(clazz: Class<T>, position: Int, buffer: Buffer): T {
        val length = buffer.getInt(position)
        val end_position = position + length
        val jsonStr = buffer.getString(position , end_position)
        return Json.decodeValue(jsonStr, clazz)
    }
    ...
}
```

**Comment by StephenOTT** [comment]
I ran into this problem the other day...

Registering a codec is slightly annoying... but a nice annotation would be good for this so you can detect and auto register...

But i think the large problem is the need to use DeliveryOptions to set which codec to use.

@vietj why does the EB require you to dictate which codec to use?  Is there no "best guess" option based on the class?

It would seem that when registering a codec it would be logical to have the option to set the class against the codec.  I understand that "technically" you could register many codecs for the same class.  But would seem to have a more common usage where you want to set the default codec for a class.  So when you send that class over the EB, you dont need to set the codec every time.

**Comment by vietj** [comment]
@StephenOTT you can register a codec that will work for a given type without the need of `DeliveryOptions` with `EventBus#registerDefaultCodec(Class<T> clazz, MessageCodec<T, ?> codec)`. This will perform a lookup based on the body class an use it.

**Comment by StephenOTT** [comment]
@vietj thanks, but this still requires you to register each class?  Is there no way to set this up as a interface?  So that any class that implements the interface will used by the codec?

**Comment by vietj** [comment]
@StephenOTT you are right but I was answering your concern about specifying the codec name in the options.

Actually I gave thought about iterating the class hierarchy for codec lookup, i.e look at the current class and the parent classes up to `Object.class` and then also interfaces. I think that would give more flexibility although lookup might be more expensive.

**Comment by StephenOTT** [comment]
What are you thoughts on just having a vertx provided interface that is something like "EventBusable".  The real use case here is really just being able to have type safety but still sending JsonObjects through the eB. If you just heard code support for a interface then in the majority of cases people don't need a lookup

**Comment by vietj** [comment]
I think that if we iterate over the classes then anyone can have its own EventBusuable like interface and it will provide more flexiblity.

**Comment by StephenOTT** [comment]
Agreed. But if speed becomes a issue from iterating, having a interface would be more than satisfactory.

**Comment by rodrigoSaladoAnaya** [comment]
Can you check  #3280

**Comment by vietj** [comment]
Can you have a look at https://github.com/eclipse-vertx/vert.x/pull/4117 ?

**Comment by tsegismont** [comment]
Closing as won't fix. A solution could be to use a default selector https://github.com/eclipse-vertx/vert.x/issues/4365
