### ISSUE TITLE
3.6.0 -- HttpServerRequest.pause() no longer prevents end of empty stream

### ISSUE THREAD

**Issue by sfitts** [eclipse-vertx/vert.x#2763]
There appears to be a behavior change between 3.5.3 and 3.6.0 which unfortunately has broken our server.  I'm hoping it was an unintended consequence of the stream changes related to fetch() and not a purposeful semantic change in what `pause` means.

In one of the routes in our server we install a handler which calls `pause` on the `HttpServerRequest` instance that is being processed (we use `context.request().pause()`).  We do this so that we can install our own end handler and proxy the request to a different stream.  Once that's done we resume the request and let it proceed as normal.

In 3.5.3 this works fine -- the sequence of calls (at a high level) go something like this:

1) `handleMessage` called on `Http1xServerConnection` with the initial client request.
1) `pause` called on the `HttpServerRequestImpl` instance
    * Internally this used to set both the `paused` and `queuing` flags to `true`.
1) `handleMessage` called on `Http1xServerConnection` with the LastHttpContent marker
    * Because of the fact that `queuing` is `true` this would defer processing of this until `resume`
1) At this point we set up the request proxying and resume the request (this includes installing a new end handler).

In 3.6.0 we see:

1) `handleMessage` called on `Http1xServerConnection` with the initial client request.
1) `pause` called on the `HttpServerRequestImpl` instance
    * Internally this calls `pause` on the `pendingQueue` (which is actually created at this point), but does *not* set the `paused` flag to `true`.
1) `handleMessage` called on `Http1xServerConnection` with the LastHttpContent marker
    * There is no code which prevents this from being immediately processed, even though the request has been paused.  This causes the request to be marked as "ended".
1) Now when we attempt to establish the alternate handlers for the request we get a failure since the request has ended.

The upshot is that pause doesn't seem to be respected.  It is also a bit odd that there appears to be no code which sets the `paused` flag in `HttpServerRequestImpl` to true (there is still code that checks for this, but nothing sets it, not even the called to `pause()`).

**Comment by sfitts** [comment]
Looks like the core of this change came in with https://github.com/eclipse-vertx/vert.x/commit/9854d3e229a88696c5c36307026b216a883e060a.  This is also where the HttpServerRequestImpl stopped calling `pause` on the connection (unless it actually has to enqueue data).  

Processing of the end mark bypasses the pause in all cases.  See also Http1xServerConnection.handleContent where it will process the end mark even if the request enqueues the buffer given to it via `handleContent` at line 155.

**Comment by vietj** [comment]
could you provide a reproducer quickly ?

**Comment by vietj** [comment]
does your request have a body ?

**Comment by vietj** [comment]
so what is missing is to allow the end handler to be set and called when the request has already ended ?

I think the main change is that now, when a stream is empty, then pause does not stop the end handler to be called.

**Comment by sfitts** [comment]
I'll work on putting together a reproduction (hopefully once I pull this out of our server the timing will remain similar).  The initial test I was doing was with a request that had no body (and I think that's the easy way to see the behavior, though the code in `handleContent` makes it seem like it should be possible to see even with some content if that comes quickly enough.

**Comment by vietj** [comment]
when a request has a body, then the request should not be considered as ended and the end handler could still be set, otherwise it's a bug

**Comment by sfitts** [comment]
> I think the main change is that now, when a stream is empty, then pause does not stop the end handler to be called.

Correct.  When paused end processing used to be deferred and now it isn't (and looking at `handleContent`, I'm not sure the stream has to be empty).

**Comment by sfitts** [comment]
Since I'm proxying requests from a browser meant for another application I can't really control whether the request has a body or not.  If you are saying I can't get the old behavior then I think I'm going to have a major problem (since I don't see how to create a working proxy without it).

**Comment by vietj** [comment]
my take is that if an ended request can have the end handler set and called then it should be fine.

if the request has an actual body, then the request will be effectively paused and behave like before.

**Comment by sfitts** [comment]
Here's the reproduction -- https://gist.github.com/sfitts/737501b3f059d7fdef6e5a27219f14fa.  On 3.5.3 both tests pass.  On 3.6.0 `testPausedEmpty` fails.

Sorry for the JUnit dependency, quickest way I could get this going.

After looking at this some more we could probably live with the behavior where setting the end handler on the request would result in it being called immediately.  It makes the timing a bit tricky with the initialization of the Pump (which in our real code forwards to a client request), but it would probably be workable if that's the only choice (I'd still prefer that it be deferred to the resume as it is now).

I also confirmed that the POST case (aka request with content) does not have an issue.  The code I was worried about above does run, but the request ignores the handleEnd call since it knows it is paused.

BTW, I think that the private field `HttpServerRequstImpl.paused` can be removed.  It is never set to `true` and the only places it is checked  (lines 131 and 166) also check the state of the pending queue (which is the real indicator of paused state now).  Seems odd to have a field that looks like it controls that state, but doesn't.

**Comment by vietj** [comment]
I think the current behavior is indeed a change. The main reason of this change indeed is for RX adapters (when an RX stream is subscribed, the subscription can be terminated without an item to be requested).

I think you can accommodate this easily in your application.

If you set the end handler when pausing (i.e before end is called), then when the end handler is called and it has not been resumed yet, it means that the request is finished and you can simply go ahead with the proxy request and perform the request without a body to send.

Otherwise it means that the request might have buffers and you can resume the request like before.

WDYT ?

**Comment by vietj** [comment]
thanks for spotting the paused field, indeed when looking back at the code I saw that it was useless (and there are chances that the JVM JIT removes it at runtime).

**Comment by sfitts** [comment]
Well... it's going to require that we completely restructure the area of code in question (so possible, but unfortunately not easy).  However, another alternative might just be to treat the fact that the request is ended (which we can check) as an indicator that it must not have had any content and proceed accordingly.  This might open us up to corner cases where the premature end actually indicates an error and not just an empty request, but I'm not sure if that's possible.

Regarding `paused` -- yeah I doubt it's an actual issue at runtime, just threw me for a loop when I was trying to reason out what the code was doing -- so it's more of a human issue than a computer one.

**Comment by sfitts** [comment]
OK, that works and is easy.  At this point since the behavior change is intentional (and needed for Rx, which we use, so yea!) you can probably just close this.  Sorry for the churn.  Not sure if this is something that needs documenting or not (our use case is admittedly a bit obscure).

**Comment by vietj** [comment]
I think it should be clarified.

**Comment by vietj** [comment]
let's keep this open for now as place holder for documenting it.

**Comment by vietj** [comment]
I think also later we want to have a pipe method on ReadStream so that is handled automatically, i.e

readStream.pipe(writeStream).

that setup the pump.

so if the read stream is paused but the end handler has been called (empty case) then this just end the WriteStream.

I've found pump to be complicated to use, specially with error handlers that must stop the pumps (specially if you are doing bidi HTTP proxying).

**Comment by sfitts** [comment]
That would be very helpful (and I agree wrt Pump, very useful, but also hard to get all the corner cases right).

**Comment by vietj** [comment]
@sfitts see https://github.com/vert-x3/wiki/wiki/RFC:-Stream-pipe-API

**Comment by brasseld** [comment]
Hello guys,

I'm still not sure about this, but it seems that the same is appearing when pausing an `HttpClientResponse`. `endHandler` is called even if the response is in pause-state.

Looking for a reproducer.

**Comment by vietj** [comment]
thanks

**Comment by brasseld** [comment]
Hi @vietj 

I did not have time to work on a reproducer but it seems that the issue is occuring when the client is receiving a single frame of data with "transfer-encoding: chunked" set with no payload.

Here is the netty log when everything is working as expected:

```
15:50:42.278 [vert.x-eventloop-thread-1] DEBUG i.n.handler.logging.LoggingHandler - [id: 0x815b6035, L:/127.0.0.1:53456 - R:localhost/127.0.0.1:53454] WRITE: 305B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 50 4f 53 54 20 2f 66 61 6c 6c 62 61 63 6b 2f 6d |POST /fallback/m|
|00000010| 79 5f 74 65 61 6d 20 48 54 54 50 2f 31 2e 31 0d |y_team HTTP/1.1.|
|00000020| 0a 43 6f 6e 74 65 6e 74 2d 4c 65 6e 67 74 68 3a |.Content-Length:|
|00000030| 20 33 31 0d 0a 43 6f 6e 74 65 6e 74 2d 54 79 70 | 31..Content-Typ|
|00000040| 65 3a 20 74 65 78 74 2f 70 6c 61 69 6e 3b 20 63 |e: text/plain; c|
|00000050| 68 61 72 73 65 74 3d 49 53 4f 2d 38 38 35 39 2d |harset=ISO-8859-|
|00000060| 31 0d 0a 48 6f 73 74 3a 20 6c 6f 63 61 6c 68 6f |1..Host: localho|
|00000070| 73 74 3a 35 33 34 35 34 0d 0a 55 73 65 72 2d 41 |st:53454..User-A|
|00000080| 67 65 6e 74 3a 20 41 70 61 63 68 65 2d 48 74 74 |gent: Apache-Htt|
|00000090| 70 43 6c 69 65 6e 74 2f 34 2e 35 2e 37 20 28 4a |pClient/4.5.7 (J|
|000000a0| 61 76 61 2f 31 2e 38 2e 30 5f 31 39 32 29 0d 0a |ava/1.8.0_192)..|
|000000b0| 41 63 63 65 70 74 2d 45 6e 63 6f 64 69 6e 67 3a |Accept-Encoding:|
|000000c0| 20 67 7a 69 70 2c 64 65 66 6c 61 74 65 0d 0a 58 | gzip,deflate..X|
|000000d0| 2d 47 72 61 76 69 74 65 65 2d 54 72 61 6e 73 61 |-Gravitee-Transa|
|000000e0| 63 74 69 6f 6e 2d 49 64 3a 20 66 64 39 62 36 65 |ction-Id: fd9b6e|
|000000f0| 61 38 2d 37 66 32 37 2d 34 36 32 62 2d 39 62 36 |a8-7f27-462b-9b6|
|00000100| 65 2d 61 38 37 66 32 37 65 36 32 62 33 36 0d 0a |e-a87f27e62b36..|
|00000110| 0d 0a 54 68 69 73 20 69 73 20 61 20 64 75 6d 6d |..This is a dumm|
|00000120| 79 20 72 65 71 75 65 73 74 20 70 61 79 6c 6f 61 |y request payloa|
|00000130| 64                                              |d               |
+--------+-------------------------------------------------+----------------+
15:50:42.279 [vert.x-eventloop-thread-1] DEBUG i.n.handler.logging.LoggingHandler - [id: 0x815b6035, L:/127.0.0.1:53456 - R:localhost/127.0.0.1:53454] FLUSH
15:50:42.279 [vert.x-eventloop-thread-1] DEBUG i.n.handler.logging.LoggingHandler - [id: 0x815b6035, L:/127.0.0.1:53456 - R:localhost/127.0.0.1:53454] ACTIVE
15:50:42.280 [qtp496425074-38] INFO  / - RequestHandlerClass from context returned com.github.tomakehurst.wiremock.http.StubRequestHandler. Normalized mapped under returned 'null'
15:50:42.292 [vert.x-eventloop-thread-1] DEBUG i.n.handler.logging.LoggingHandler - [id: 0x815b6035, L:/127.0.0.1:53456 - R:localhost/127.0.0.1:53454] READ: 222B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d |HTTP/1.1 200 OK.|
|00000010| 0a 4d 61 74 63 68 65 64 2d 53 74 75 62 2d 49 64 |.Matched-Stub-Id|
|00000020| 3a 20 31 65 64 35 63 66 64 63 2d 32 64 61 61 2d |: 1ed5cfdc-2daa-|
|00000030| 34 66 34 61 2d 61 31 35 30 2d 33 35 65 30 33 64 |4f4a-a150-35e03d|
|00000040| 61 66 36 65 61 35 0d 0a 43 6f 6e 74 65 6e 74 2d |af6ea5..Content-|
|00000050| 45 6e 63 6f 64 69 6e 67 3a 20 67 7a 69 70 0d 0a |Encoding: gzip..|
|00000060| 56 61 72 79 3a 20 41 63 63 65 70 74 2d 45 6e 63 |Vary: Accept-Enc|
|00000070| 6f 64 69 6e 67 2c 20 55 73 65 72 2d 41 67 65 6e |oding, User-Agen|
|00000080| 74 0d 0a 54 72 61 6e 73 66 65 72 2d 45 6e 63 6f |t..Transfer-Enco|
|00000090| 64 69 6e 67 3a 20 63 68 75 6e 6b 65 64 0d 0a 53 |ding: chunked..S|
|000000a0| 65 72 76 65 72 3a 20 4a 65 74 74 79 28 39 2e 32 |erver: Jetty(9.2|
|000000b0| 2e 32 36 2e 76 32 30 31 38 30 38 30 36 29 0d 0a |.26.v20180806)..|
|000000c0| 0d 0a 41 0d 0a 1f 8b 08 00 00 00 00 00 00 00 0d |..A.............|
|000000d0| 0a 41 0d 0a 03 00 00 00 00 00 00 00 00 00       |.A............  |
+--------+-------------------------------------------------+----------------+
15:50:42.292 [vert.x-eventloop-thread-1] DEBUG i.n.handler.logging.LoggingHandler - [id: 0x815b6035, L:/127.0.0.1:53456 - R:localhost/127.0.0.1:53454] READ COMPLETE
15:50:42.293 [vert.x-eventloop-thread-1] DEBUG i.n.handler.logging.LoggingHandler - [id: 0x815b6035, L:/127.0.0.1:53456 - R:localhost/127.0.0.1:53454] READ: 7B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 0d 0a 30 0d 0a 0d 0a                            |..0....         |
+--------+-------------------------------------------------+----------------+
15:50:42.293 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "HTTP/1.1 200 OK[\r][\n]"
15:50:42.293 [vert.x-eventloop-thread-1] DEBUG i.n.handler.logging.LoggingHandler - [id: 0x815b6035, L:/127.0.0.1:53456 - R:localhost/127.0.0.1:53454] READ COMPLETE
```

And here when the issue is coming:

```
15:54:27.360 [vert.x-eventloop-thread-1] DEBUG i.n.handler.logging.LoggingHandler - [id: 0x1917b494, L:/127.0.0.1:53794 - R:localhost/127.0.0.1:53792] WRITE: 305B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 50 4f 53 54 20 2f 66 61 6c 6c 62 61 63 6b 2f 6d |POST /fallback/m|
|00000010| 79 5f 74 65 61 6d 20 48 54 54 50 2f 31 2e 31 0d |y_team HTTP/1.1.|
|00000020| 0a 43 6f 6e 74 65 6e 74 2d 4c 65 6e 67 74 68 3a |.Content-Length:|
|00000030| 20 33 31 0d 0a 43 6f 6e 74 65 6e 74 2d 54 79 70 | 31..Content-Typ|
|00000040| 65 3a 20 74 65 78 74 2f 70 6c 61 69 6e 3b 20 63 |e: text/plain; c|
|00000050| 68 61 72 73 65 74 3d 49 53 4f 2d 38 38 35 39 2d |harset=ISO-8859-|
|00000060| 31 0d 0a 48 6f 73 74 3a 20 6c 6f 63 61 6c 68 6f |1..Host: localho|
|00000070| 73 74 3a 35 33 37 39 32 0d 0a 55 73 65 72 2d 41 |st:53792..User-A|
|00000080| 67 65 6e 74 3a 20 41 70 61 63 68 65 2d 48 74 74 |gent: Apache-Htt|
|00000090| 70 43 6c 69 65 6e 74 2f 34 2e 35 2e 37 20 28 4a |pClient/4.5.7 (J|
|000000a0| 61 76 61 2f 31 2e 38 2e 30 5f 31 39 32 29 0d 0a |ava/1.8.0_192)..|
|000000b0| 41 63 63 65 70 74 2d 45 6e 63 6f 64 69 6e 67 3a |Accept-Encoding:|
|000000c0| 20 67 7a 69 70 2c 64 65 66 6c 61 74 65 0d 0a 58 | gzip,deflate..X|
|000000d0| 2d 47 72 61 76 69 74 65 65 2d 54 72 61 6e 73 61 |-Gravitee-Transa|
|000000e0| 63 74 69 6f 6e 2d 49 64 3a 20 33 36 61 62 39 63 |ction-Id: 36ab9c|
|000000f0| 65 37 2d 33 63 62 61 2d 34 35 31 33 2d 61 62 39 |e7-3cba-4513-ab9|
|00000100| 63 2d 65 37 33 63 62 61 63 35 31 33 32 38 0d 0a |c-e73cbac51328..|
|00000110| 0d 0a 54 68 69 73 20 69 73 20 61 20 64 75 6d 6d |..This is a dumm|
|00000120| 79 20 72 65 71 75 65 73 74 20 70 61 79 6c 6f 61 |y request payloa|
|00000130| 64                                              |d               |
+--------+-------------------------------------------------+----------------+
15:54:27.361 [vert.x-eventloop-thread-1] DEBUG i.n.handler.logging.LoggingHandler - [id: 0x1917b494, L:/127.0.0.1:53794 - R:localhost/127.0.0.1:53792] FLUSH
15:54:27.361 [vert.x-eventloop-thread-1] DEBUG i.n.handler.logging.LoggingHandler - [id: 0x1917b494, L:/127.0.0.1:53794 - R:localhost/127.0.0.1:53792] ACTIVE
15:54:27.362 [qtp496425074-38] INFO  / - RequestHandlerClass from context returned com.github.tomakehurst.wiremock.http.StubRequestHandler. Normalized mapped under returned 'null'
15:54:27.373 [vert.x-eventloop-thread-1] DEBUG i.n.handler.logging.LoggingHandler - [id: 0x1917b494, L:/127.0.0.1:53794 - R:localhost/127.0.0.1:53792] READ: 229B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d |HTTP/1.1 200 OK.|
|00000010| 0a 4d 61 74 63 68 65 64 2d 53 74 75 62 2d 49 64 |.Matched-Stub-Id|
|00000020| 3a 20 32 61 32 65 64 61 65 61 2d 61 66 66 37 2d |: 2a2edaea-aff7-|
|00000030| 34 35 39 64 2d 39 32 65 37 2d 62 39 30 33 34 30 |459d-92e7-b90340|
|00000040| 37 30 65 63 33 37 0d 0a 43 6f 6e 74 65 6e 74 2d |70ec37..Content-|
|00000050| 45 6e 63 6f 64 69 6e 67 3a 20 67 7a 69 70 0d 0a |Encoding: gzip..|
|00000060| 56 61 72 79 3a 20 41 63 63 65 70 74 2d 45 6e 63 |Vary: Accept-Enc|
|00000070| 6f 64 69 6e 67 2c 20 55 73 65 72 2d 41 67 65 6e |oding, User-Agen|
|00000080| 74 0d 0a 54 72 61 6e 73 66 65 72 2d 45 6e 63 6f |t..Transfer-Enco|
|00000090| 64 69 6e 67 3a 20 63 68 75 6e 6b 65 64 0d 0a 53 |ding: chunked..S|
|000000a0| 65 72 76 65 72 3a 20 4a 65 74 74 79 28 39 2e 32 |erver: Jetty(9.2|
|000000b0| 2e 32 36 2e 76 32 30 31 38 30 38 30 36 29 0d 0a |.26.v20180806)..|
|000000c0| 0d 0a 41 0d 0a 1f 8b 08 00 00 00 00 00 00 00 0d |..A.............|
|000000d0| 0a 41 0d 0a 03 00 00 00 00 00 00 00 00 00 0d 0a |.A..............|
|000000e0| 30 0d 0a 0d 0a                                  |0....           |
+--------+-------------------------------------------------+----------------+
mars 08, 2019 3:54:27 PM io.vertx.core.http.impl.HttpClientResponseImpl
GRAVE: java.lang.NullPointerException
15:54:27.377 [vert.x-eventloop-thread-1] DEBUG i.n.handler.logging.LoggingHandler - [id: 0x1917b494, L:/127.0.0.1:53794 - R:localhost/127.0.0.1:53792] READ COMPLETE
```

You can notice the single response chunk in the second case...

Hope it helps.

**Comment by vietj** [comment]
can you test with 3.7 SNAPSHOT ?

**Comment by brasseld** [comment]
Works well!

Seems that this commit does the trick: https://github.com/eclipse-vertx/vert.x/commit/f50a925e0cb1f6adf82faddc934f66d65eac042a#diff-32ecf8117eae6e770cf187ca69a0b356

**Comment by vietj** [comment]
thanks for reporting!
