### ISSUE TITLE
FileResolver isBundleUrlDirectory is not correct for DirBundleFile

### ISSUE THREAD

**Issue by spnettec** [eclipse-vertx/vert.x#2768]
`
private boolean isBundleUrlDirectory(URL url) {
    return url.toExternalForm().endsWith("/") ||
      getClassLoader().getResource(url.getPath().substring(1) + "/") != null;
  }

if url is exist
getClassLoader().getResource(url.getPath().substring(1) + "/")  always return non null

`

**Comment by cescoffier** [comment]
On which OSGi implementation do you see this behavior?

**Comment by spnettec** [comment]
Equinox 4.9
