### ISSUE TITLE
Deserialize object by it's base class

### ISSUE THREAD

**Issue by dtolstyi** [eclipse-vertx/vert.x#2769]
Is it possible to send / receive an object using polymorphism and knowing only it's base class?

Example:
```kotlin
abstract class Base(open val param1: String)
class Child(override val param1: String, val param2: Int): Base(param1)
```
Now, I would like to make a generic receiver that will get all classes that extend `Base` class:
```kotlin
vertx.eventBus().consumer<Base>("coordinator") { message ->
...
```
When I'm trying to do something similar to this I'm receiving an error that deserialization process has failed to decode my data into `Base` class as far as there are unrecognized fields (`param2` in this example).

Is it somehow possible to use polymorphism with `vert.x EventBus`?

**Comment by vietj** [comment]
no, it is not possible, it would be better that you use composition over inheritance in such cases

**Comment by vietj** [comment]
question

**Comment by dtolstyi** [comment]
> no, it is not possible, it would be better that you use composition over inheritance in such cases

Thank you for reply Julien @vietj. Could you show a small piece of code as an example of composition that could work in case like this? Thank you!

**Comment by vietj** [comment]
basically the idea is that there is a container class that can hold the Base class and the codec when it serialize / unserialize will handle the case according to the Base sub class

**Comment by dtolstyi** [comment]
I see. So we should have `MessageCodec` for each sub-class. Thank you for the idea. I will take a look how it can be applied in my case.

**Comment by vietj** [comment]
that's another way to do it @dtolstyi but I think it forces to have the Base class to be abstract (which is fine I think)
