### ISSUE TITLE
HttpClient race condition when getting a connection from the pool being closed

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#2773]
Currently there is a race condition with the `HttpClient` between a client request and a connection close. The pool delivers the client request in the next tick and the connection might be removed from the pool between this the schedule and the delivery. At this moment the client does not know the connection was closed and is never aware of the connection close.

We should avoid a next tick in this situation, i.e when the client request is fulfilled with a valid connection, it should be called immediately to avoid the race.

Currently the fact that the connection pool can hold connections with multiples context does not allow to run the pool requests on the pool and thus the situation is hard to avoid without a re-check before the connection is delivered. A better solution might be to attach a vertx context on the pool and consider all connections will use the same context, this would allow to eliminate the race easily.

**Comment by wujimin** [comment]
infact, in my reproduce case, netty know write failed, and already notified caller (vertx)
but vertx invoke netty write with VoidPromoise, so missed the notification:
io.vertx.core.net.impl.ConnectionBase#writeToChannel(java.lang.Object)
```
  public void writeToChannel(Object obj) {
    writeToChannel(obj, voidPromise);
  }
```

**Comment by vietj** [comment]
Yes but that's fine, as the Http1xClientConnection should set the response in progress at the same time it's writing the chunk. The issue is that the connection is removed from the pool and given to the Http1xClientConnection as closed and that should not happen. If it would not happen then the write operation would occur before the connection is actually closed and the connection close will notify the responseInProgress that it failed

**Comment by vietj** [comment]
This issue makes me realise that when we we should notify the pool waiter synchronously to avoid any race condition. The pool task progress has been redesigned so it always happens on the event loop thread and the event loop has to be set for the pool (otherwise we cannot predict the thread the connection will use if we ever use the waiter thread and this will introduce a potential race).

A branch with the work has been pushed here https://github.com/vietj/vert.x/tree/bilto-fix

**Comment by vietj** [comment]
@wujimin the issue you is fixed in this branch https://github.com/vietj/vert.x/tree/bilto-fix , I tried with your reproducer and now we don't have this race anymore
