### ISSUE TITLE
Deprecate Future#completer

### ISSUE THREAD

**Issue by okou19900722** [eclipse-vertx/vert.x#2778]
after this issue (#1827) finished. should we deprecate `Future.completer` and change the examples in documents?

**Comment by vietj** [comment]
I don't think it's necessary, Future will not be used anymore in v4 and in v3 there will already be a bunch of other more useful deprecations for the user.

**Comment by vietj** [comment]
however I think it's worth adding a note on the method that now the future is an handler and can be used directly.

**Comment by vietj** [comment]
and the method actually returns this.

**Comment by vietj** [comment]
I think we should deprecate in 3.x and remove in v4, it's not something one should use now.
