### ISSUE TITLE
A Question about Transaction For Mongo&MySQL

### ISSUE THREAD

**Issue by MrXionGe** [eclipse-vertx/vert.x#2781]
I'm from an old note.--Here--https://groups.google.com/forum/?fromgroups=#!topic/vertx/duFVIcSR0zg%5B1-25%5D
This is a small idea. About transaction...
In future versions. Will we add some new methods? For simpler transaction usage.
And I didn't find a good way to use transactions in VertX.
Recently I've been using VertX and Mongo.VertX much more interesting than SpringBoot.It's just that there's a problem here in transactions.

**Comment by vietj** [comment]
closing as it's a question

**Comment by vietj** [comment]
normally you can do transactions with mysql, as you are pointing to a thread, it's not clear what you mean

**Comment by vietj** [comment]
Hi,

I think the best is to open a feature request in the vertx-mongo-client project then

Julien
