### ISSUE TITLE
Vertx-config when using Spring Config Server Store not interpolating variable properties

### ISSUE THREAD

**Issue by Swatikp** [eclipse-vertx/vert.x#2784]
I am using vert.x ConfigRetrieverOptions as type "spring-config-server" to fetch properties from config server in my vert.x application.

I have property file in my config server that has some interpolated values like:
key1=hello
key2=${key1}/world

When I am trying to fetch key2, instead of returning "hello/world" ConfigRetriever.getConfig is giving me as it is value without interpolating i.e. ${key1}/world

Is there anything else I need to do in vert.x to support this feature(String Interpolation)

**Comment by vietj** [comment]
can you open this issue in the vertx-config project ? https://github.com/vert-x3/vertx-config
