### ISSUE TITLE
HttpClient pool improvements

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#2787]
A few improvements done to the HttpClient and the pool:

- the client suffers from races when a connection is closed while being delivered to the client request (see https://github.com/eclipse-vertx/vert.x/issues/2773)
- TCP idle timeout now is not handled anymore with pool events but instead when a TCP idle event happens, it is ignored when the connection is in the pool
- the activate/passivate connection has been removed (since it's not used anymore for TCP idle)
- the coupling of the pool to channel has been removed as it was not necessary
- 

The main change is that now the pool methods update the pool state and the corresponding events (deliver a connection to a waiter, connect to an endpoint, keep the waiter list bounded) are handled on the event-loop thread to avoid races. To accomodate this, now the pool has a context instead of having a context per connection.

**Comment by jeho0815** [comment]
Hi，can we set a minIdle connections. Sometimes we may send a lots of request at the same time, especially via https, has many ssl handshake time out errors.

**Comment by vietj** [comment]
can you elaborate more @jeho0815 ?
