### ISSUE TITLE
Virtual memory usage is high, when Java Heap or real memory usage is much lower

### ISSUE THREAD

**Issue by constantOut** [eclipse-vertx/vert.x#2789]
Hello guys, Vertx is an awesome piece of software, thanks for your effort.
However I have a problem which I described in the subject. My web server is extremely simple and the only thing it does is sends received URL to Kafka after basic validation. I understand that Kafka client might be the root cause, but I have found similar issue with like https://www.tikalk.com/posts/2018/04/30/vertx-memory-usage-with-intensive-network/

**Comment by tsegismont** [comment]
Are you running your app on Linux? Virtual memory is a usually an
irrelevant metric (see
https://stackoverflow.com/questions/561245/virtual-memory-usage-from-java-under-linux-too-much-memory-used
)

It would be nice if you could elaborate a bit more on the actual problem.
Thanks

**Comment by constantOut** [comment]
Well yes, I am running on Linux. It uses about 20GB of virtual memory and that's the only problem I have. App itself uses less than 2GB real memory and jvm heap usage is oscillating around 1,3GB. So it's surprising to me how it managed to use so much virtual memory.

**Comment by tsegismont** [comment]
Try pmap has explained in the linked article to find out what's behind this
amount of virtual memory. In practice though, the os is most probably able
to use only the relevant pages.
