### ISSUE TITLE
JsonParser should not resume or pause the source wrapped read stream when it is ended

### ISSUE THREAD

**Issue by abelhegedus** [eclipse-vertx/vert.x#2790]
We have implemented streaming Json from an AsyncFile as shown in [this example](https://github.com/vert-x3/vertx-examples/blob/master/core-examples/src/main/java/io/vertx/example/core/jsonstreaming/JsonStreamingExample.java). This has worked nicely before 3.6.0 but now results in a `java.lang.IllegalStateException: File handle is closed` in 3.6.2.

Based on some debugging, the following happens:
1. `io.vertx.core.parsetools.impl.JsonParserImpl#end` [calls](https://github.com/eclipse-vertx/vert.x/blob/3.6.2/src/main/java/io/vertx/core/parsetools/impl/JsonParserImpl.java#L210) `io.vertx.core.parsetools.impl.JsonParserImpl#checkPending` which will [call](https://github.com/eclipse-vertx/vert.x/blob/3.6.2/src/main/java/io/vertx/core/parsetools/impl/JsonParserImpl.java#L225) the `endHandler`.
2. `endHandler` [closes](https://github.com/vert-x3/vertx-examples/blob/3.6.1/core-examples/src/main/java/io/vertx/example/core/jsonstreaming/JsonStreamingExample.java#L60) the AsyncFile
3. `io.vertx.core.streams.ReadStream#resume` is [called](https://github.com/eclipse-vertx/vert.x/blob/3.6.2/src/main/java/io/vertx/core/parsetools/impl/JsonParserImpl.java#L248) (on the already closed stream)
4. the `exceptionHandler` is [called](https://github.com/eclipse-vertx/vert.x/blob/3.6.2/src/main/java/io/vertx/core/parsetools/impl/JsonParserImpl.java#L259) with the above exception

As far as I can see, issue #2584 and PR #2583 seems to be related.

Is the example outdated? Should we handle file closing in some other way?

**Comment by vietj** [comment]
can you provide a reproducer for the issue ?

**Comment by vietj** [comment]
what is actually calling resume ? it is not clear

**Comment by abelhegedus** [comment]
> what is actually calling resume ? it is not clear

I have added stable links to the original comments.

> can you provide a reproducer for the issue ?

I can do that, though I think the linked example should reproduce the issue as well.

**Comment by vietj** [comment]
ok, we will check the example

**Comment by KowalczykBartek** [comment]
Just wanted to let you know :) making this small change in **io.vertx.core.parsetools.implJsonParserImpl**

```java
if (currentToken == null) {
  if (ended) {
    if (endHandler != null) {
      endHandler.handle(null);
    }
    return; // <-- here we need to skip rest of the method if file reading is ended
  }
  break;
}
``` 
allows to read entire file (and AsyncFileImpl is also closed). Unfortunately there is no tests for parser implementation so I am not sure whether it doesn't breaks something other :|

**Comment by vietj** [comment]
there is `io.vertx.core.parsetools.JsonParserTest` also it is needed to add a new test borrowed from the example that fails
