### ISSUE TITLE
Stream pipe API

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#2792]
Currently the advocated way to transfer data between streams is to use the pump API. This API only cares about transferring data and leave the aspects of stream life cycle and error management to the developer, which can be difficult to implement when a write stream is obtained asynchronously.

The stream API is a new API that will pipe a read stream to a write stream using the well known pump mechanism and will also take care of other aspects to provide a simple and effective solution to the developer.

The previous pump API will still be supported but not advocated anymore in the doc in favor of the pipe API.

**Comment by azagniotov** [comment]
@vietj This is great, we really need this and having this behavior as part of the framework makes so much more sense than implementing it yourself
