### ISSUE TITLE
HttpServer closes the connection prematurely when sending a large file with HTTP/1.1 without keep-alive

### ISSUE THREAD

**Issue by sfitts** [eclipse-vertx/vert.x#2794]
Version:  3.6.2

When sending a file larger than 1MB the server will prematurely disconnect if the client has set the `Connection` header to close.

Here is the reproduction -- https://gist.github.com/sfitts/052d0805ad4d70af701ecef7ce9c8a7f

See also the discussion here -- https://groups.google.com/forum/#!topic/vertx/vL49FCY2mG4

**Comment by vietj** [comment]
thanks for the reproducer @sfitts

**Comment by vietj** [comment]
can you make this reproducer without vertx web ?

**Comment by vietj** [comment]
I was able to reproduce it

**Comment by vietj** [comment]
the response was closed prematurely when sending a large file indeed
