### ISSUE TITLE
MongoDB rxFindWithOptions returns no results

### ISSUE THREAD

**Issue by dodalovic** [eclipse-vertx/vert.x#2800]
Hi, I'm trying to run natural language search. I have collection `tag`, and that collection has `text` field, with text index on it. 

When I connect via shell, and run the query: 

```javascript
 db.tag.find(
    { $text: { $search: "tag" } },
    { score: { $meta: "textScore" } }
).sort( { score: { $meta: "textScore" } } )
```
I get expected results back. When I do the same from the vert.x kotlin app: 

```kotlin
threadMongoClient.rxFindWithOptions(
            "tag",
            json("\$text" to json("\$search" to msg.body())),
            FindOptions()
                .setSort(json("score" to json("\$meta" to "textScore")))
                .setFields(json("score" to json("\$meta" to "textScore")))
                .setLimit(5))
        ).subscribe({ matches ->
            msg.reply(JsonArray(matches))
        }, { err ->
            log.error("Could not retrieve similar tags", err)
            msg.fail(500, err.message)
        })
```
I always get 0 results back for the same input  - "tag" string in this case. 

Is there some obvious mistake I'm making?

Many thanks for wonderful work!!!

**Comment by dodalovic** [comment]
@karianna, @johnoliver Any hint? Thanks!

**Comment by vietj** [comment]
can you recreate this issue in https://github.com/vert-x3/vertx-mongo-client/ instead ?

**Comment by dodalovic** [comment]
@vietj https://github.com/vert-x3/vertx-mongo-client/issues/167

**Comment by vietj** [comment]
thanks!
