### ISSUE TITLE
Allow ObjectMapper to be configured on a per Vertical basis

### ISSUE THREAD

**Issue by StephenOTT** [eclipse-vertx/vert.x#2807]
There are cases where you want to setup a Verticle with a specific ObjectMapper configurations (additional configs, modules, etc).

But we dont want to change the global mapper, but we are also using items (like the Web Client) that use the global mapper.

Would be great if Abstract Verticle allowed you to control the specific mapper being used.

**Comment by vietj** [comment]
that's actually not possible since the mapper is used in `JsonObject` in a static manner

**Comment by StephenOTT** [comment]
@vietj what could be a alternative?  Right now having a completely static single mapper can be troublesome due to the way OM requires registration of modules for handling of data types.

**Comment by vietj** [comment]
you create an abstract base verticle with a method like:

```
public JsonObject decode(String json) {
   return new JsonObject(mapper.readValue(json, Map.class));
}
```

where mapper is a field in this verticle.

**Comment by StephenOTT** [comment]
@vietj is this a override within the abstract verticle?

Is the decode being called automatically by anything executing within the verticle? or is this is supposed to manually used?

**Comment by vietj** [comment]
it's supposed to be called manually instead of new JsonObject(json)

**Comment by StephenOTT** [comment]
Okay.  Are there any thinking to change this in the future?  With that setup that you describe is means all of the automatic conversions to and from pojos are lost and the dev has to remember to do it manually in each scenario.  Does not have to be at a verticle level.  Could be at certain instant levels as well such as a WebClientOptions configuration

**Comment by vietj** [comment]
@StephenOTT it is not clear actually what you want to achieve, can you describe your use cases ?
