### ISSUE TITLE
Avoid excessive handler creation while Send-Reply which slowes down communication (Cluster Mode)

### ISSUE THREAD

**Issue by OSI-Califronia** [eclipse-vertx/vert.x#2808]
We have to deal with many messages send via send/reply strategy over a clustered eventbus. Vertx registeres a new handler for each call which causes in heavy load in cluster manager (we use zookeeper cluster manager) which has to create a new entry for each message and propagate it to all cluster memebers (< 600 instances). This could be avoid and we implement our own Reply Strategy which uses send strategy of vertx inside. We register only one reply consumer/handler while start of each verticle/eventbus instance. It's address is send as header via send and while reply this address is used.

maybe its possible to integrate this into vertx core.

**Comment by tsegismont** [comment]
Reply handlers are not send to the cluster manager. They are registered
only on the sending node. The recipient will reply using the same
connection and does not perform any handler lookup.
