### ISSUE TITLE
how to customize eventloop thread name and calculate how many eventloopContext created

### ISSUE THREAD

**Issue by wujimin** [eclipse-vertx/vert.x#2811]
currently:
* we create multiple vertx instances in one process
* sometimes our code is not so good, that caused create unnecessary eventloopContext

so we extend VertxImpl in vertx 3.5.3 and previous versions (https://github.com/apache/servicecomb-java-chassis/blob/master/foundations/foundation-vertx/src/main/java/io/vertx/core/impl/VertxImplEx.java):
* give vertx a name, and make eventloop thread name prefix relate to vertx name
* calculate how many eventloopContext created
![image](https://user-images.githubusercontent.com/16874843/51855264-c7ab3280-2367-11e9-8dff-a690b607382b.png)

but when i try this in 3.6.3-SNAPSHOT, i fount that constructor changed from package to private, so i can not do what we want.
someone help me to resolve this? thanks.

**Comment by vietj** [comment]
can you provide a PR that reverts this ?

**Comment by vietj** [comment]
only 2.

for 1, that's something we need to consider differently I think.

**Comment by wujimin** [comment]
so how to resolve 1?
reflect to change thread name is so ugly.

**Comment by vietj** [comment]
I think we need to think about the right way, at least it is not possible in 3.6 to do it as it requries some time

**Comment by vietj** [comment]
the Vertx 4 thread factory allows to do that
