### ISSUE TITLE
Feature/question - access id of current event loop tick

### ISSUE THREAD

**Issue by ORESoftware** [eclipse-vertx/vert.x#2816]
I am looking for a feature to determine if a method call x is in the same event loop tick as a previous method call y. If it's the same tick, I will use code like this to make sure the call gets run on the next tick:

```java
private void putCallOnNextTickIfNecessary(int previousTickId, Runnable v, Whatever w) {
  
  if(vertx.weAreInNewTick(previousTickId)){
      v.run(w);
      return;
   }

  vertx.runOnContext(new Handler<Void>() {
    public void handle(Void event) {
         v.run(w);
    }
  });
}
```

this kind of thing will make sure APIs are always sync or always async to make them consisent. Doing this in Node.js is known as avoiding Zalgo.

Anyway, my question is, how do we implement `vertx.weAreInNewTick(previousTickId)`?

What that method would do is get the id of the current tick and if that id is greater than the previous tick, return true. But not sure if we can do this yet?

**Comment by vietj** [comment]
Hi,

I'm not sure it's easy to implemnet.

What's your reasoning doing this ? maybe you can do without.

Julien

**Comment by ORESoftware** [comment]
@vietj the rationale is to make sure APIs are always async.  A library could always wrap the users code in the vertx.runOnContext callback, but that might be less performant, if the call was already async. 
Here is the logic:

* if callback was fired asynchronously, firing the next callback now
* if callback was fired synchronously, wrap the next callback in vertx.runOnContext

this will lead to more performant and consistent APIs / libraries. The only question is how to determine if a callback was fired synchronously or asynchronously!

**Comment by vietj** [comment]
which APIs are you referring to ?

can you give example of what is a callback fire synchronous and asynchronous ?

**Comment by ORESoftware** [comment]
@vietj  sure a simple example would be:

```java
async.parallel(Arrays.asList(
  v -> {
     v.done(null);  // sync callback
  },
  v -> {
     vertx.runOnContext(event -> v.done(null));  // async callback
  }
))
```

**Comment by ORESoftware** [comment]
here's the library I am porting:
https://github.com/caolan/async

**Comment by vietj** [comment]
I see.

do you have a repo with code and show a unit test that has a case where doing a tick check would make a difference ?

Julien

**Comment by ORESoftware** [comment]
@vietj I can create that for you by tomorrow. But in general when working async code and an event loop, you want to make sure your API is consistent. For example, in Node.jsj:

```js
 // event loop tick id = 1
async.parallel([
   cb => cb(null),     // 3 tasks all fired synchronously
   cb => cb(null),
   cb => cb(null)
], (err, results) => {
   // fired in the same tick (id = 1)
});
```

but then if we do this:

```js
 // event loop tick id = 1
async.parallel([
   cb => cb(null),     // 3 tasks all fired synchronously
   cb => cb(null),
   cb => process.nextTick(cb, null)
], (err, results) => {
   // fired in the next tick (id = 2)
});
```

ideally the API always fires the final callback in a future tick of the event loop, if that changes arbitrarily (id=1 or id>1), then it can lead to really bad bugs.

So whoever writes the async library, can be responsible and ensure that the library always fires the final callback in a future tick of the event loop. It must always be a future tick, to be consistent.

**Comment by vietj** [comment]
can you manage this in the library using thread local to know whether or not you are already in a task ?

**Comment by ORESoftware** [comment]
@vietj that's too expensive - what I am hoping is that when vertx launches the next tick, it has a simple integer id. each tick of the event loop has an id. So it would just be `vertx.getCurrentTickId()`.

**Comment by vietj** [comment]
is there such API in node js ?

**Comment by ORESoftware** [comment]
@vietj  yes but it's not exposed yet, they are planning to expose it.

**Comment by ORESoftware** [comment]
@vietj  one way to do this is like so:
https://github.com/watson/tick-id/issues/1

but I currently in the process of getting nodejs core to support it, so that we don't have to manually add a listener.
