### ISSUE TITLE
Why is NetServerImpl sharing the thread pool pattern

### ISSUE THREAD

**Issue by zb564739784** [eclipse-vertx/vert.x#2817]
The listen method in the NetServerImpl class : 

ServerBootstrap bootstrap = new ServerBootstrap();
bootstrap.group(availableWorkers);
sslHelper.validate(vertx);

Threads that handle other IO events and tasks in addition to accept can easily block

**Comment by tsegismont** [comment]
Can you please provide a reproducer to demonstrate the bug?

**Comment by vietj** [comment]
@zb564739784 the `availableWorkers` here is an event loop group of the various event loops that can serve the connection requests.
