### ISSUE TITLE
Why does deploy use a new thread callback in the DeploymentManager class

### ISSUE THREAD

**Issue by zb564739784** [eclipse-vertx/vert.x#2818]
Why is it wasteful to create a new context, but only callContext

           ` if (deployCount.incrementAndGet() == verticles.length) {
                reportSuccess(deploymentID, callingContext, completionHandler);
              }`

Isn't that a waste of an eventloop thread? There's nothing to do!

**Comment by tsegismont** [comment]
Can you please elaborate, not sure what you mean.
