### ISSUE TITLE
How to trap errors thrown in a verticle - specifically within route handlers

### ISSUE THREAD

**Issue by ORESoftware** [eclipse-vertx/vert.x#2819]
I posted this question on StackOverflow:
https://stackoverflow.com/questions/54498162/how-to-catch-errors-in-asynchronous-code-using-vert-x

Maybe I missed it in the docs but I think it's an important feature and I am wondering if Vertx attempts to solve this one.

**Comment by vietj** [comment]
@ORESoftware it is not clear what you mean, do you mean you want to associate an asynchronous error with an HTTP request ?

**Comment by ORESoftware** [comment]
@vietj yeah when an HTTP request comes in and the event triggers a sequence of code, if an exception occurs, I want to associate that exception with that HTTP request.

In Node.js this is solved with Domains - not solved very well, but mostly solved.
In Golang, each request is given its own Goroutine, so if an error is trapped with that Goroutine with defer, we have a ref to the request/response pair.

**Comment by vietj** [comment]
in Vert.x v4 we will provide a equivalent solution for this using tracing (https://github.com/vert-x3/wiki/wiki/RFC:-context-tracing).

there is currently a branch for this in my GitHub repository.

Julien

**Comment by ORESoftware** [comment]
@vietj  cool - with Node.js I can explain how Domains work if you don't know. Domains simply work by wrapping every async function callback with a try/catch. Luckily it's a very simple approach. With vertx, all the async APIs simply have to receive a context, wrap a call with try/catch, and if there is an error, pass back the context.

**Comment by vietj** [comment]
I see.

initially we tried an approach like domains but it does not work well because vertx integrates with non vertx libraries.

so the context tracing approach is different, it provides a context per HTTP request and this context is statically available in the application.

so you can use the context to reliably share information attached to an HTTP request.

**Comment by ORESoftware** [comment]
@vietj  are you saying each tick of the event loop is associated with an HTTP request, 1:1? That seems wrong but I don't know.

**Comment by vietj** [comment]
no it is not.

I am saying that in v4, each HTTP request will have its own io.vertx.core.Context instance which can be used to track the activity of the HTTP request.

**Comment by ORESoftware** [comment]
hmmm ok I don't fully understand yet, but will follow along later, thanks
