### ISSUE TITLE
Handler/callback registration guarantee?

### ISSUE THREAD

**Issue by ORESoftware** [eclipse-vertx/vert.x#2821]
Say I have a simple API, like so:

```java
x.doSomething(v -> {
   v.done(null, 5);
});

v.onDone((err,value) ->{
   System.out.println("This gets fired after v.done() is called");
});
```

Given the above code, my question is - using Vertx with Java, is there a guarantee that v.onDone will be called in a deterministic amount of time?

for example, assume that `v.done()` looks like:

```java
class V {
  ArrayList<Object> onDoneHandlers  = new ArrayList<>();
  
  public void onDone(Object cb){
    this.onDoneHandlers.add(cb);
  }

  public void done(Object err, Integer result){
     var v = this;
     new Thread(() -> {
        Thread.sleep(50);
        v.onDoneHandlers.get(0).run(err, result)
    }).start();
 }

}
```

so by using a thread, we delay, in the hopes that  v.onDone() in the same scope will be registered, but I don't believe there is any such guarantee, when it comes to basic Java threads. So I assume that using an event loop will give us such a guarantee, where vanilla Java threads wouldn't.  Is there some documentation that explains how this guarantee works?

**Comment by vietj** [comment]
what do you mean by deterministic amount of time ?

also your question talk about scope, which scope are you referring to ?

**Comment by ORESoftware** [comment]
by scope I meant:

{
  // scope
  x.doSomething(v -> {
     v.done(null, 5);
  });

  v.onDone((err,value) ->{
     System.out.println("This gets fired after v.done() is called");
  });

}

(scope is what's in the brackets, in the current method body, or whatever. Ultimately my question is how to ensure that callbacks get registered, if the callback registration happens afterwards.
