### ISSUE TITLE
Add fails method to TestContext async object

### ISSUE THREAD

**Issue by ORESoftware** [eclipse-vertx/vert.x#2825]
I am seeing this:

![screenshot from 2019-02-08 19-46-12](https://user-images.githubusercontent.com/11139560/52516118-5165c600-2bda-11e9-94b3-8dba99c20869.png)

I would think there would be a method that tells the test case that there is failure?
should we just throw an error?

**Comment by tsegismont** [comment]
See https://vertx.io/docs/apidocs/io/vertx/ext/unit/TestContext.html#fail--

**Comment by tsegismont** [comment]
@ORESoftware can you please send usage questions to the forum and avoid cross posting on Stackoverflow and GitHub issues? Thanks

See https://vertx.io/community/

**Comment by ORESoftware** [comment]
@tsegismont np, I can do that. I guess I assumed the forum is for discussion and ideas. This issue here is a genuine feature request -

![screenshot from 2019-02-09 00-14-55](https://user-images.githubusercontent.com/11139560/52518487-e0d1a000-2bff-11e9-9649-79a776d2a35f.png)

Looks like you missed what was in the screenshot I shared originally.
