### ISSUE TITLE
Feature request - non-blocking locking akin to synchronized block

### ISSUE THREAD

**Issue by ORESoftware** [eclipse-vertx/vert.x#2827]
I asked this question on SO:

https://stackoverflow.com/a/54607357/1223975

Is there a good way to implement an asynchronous version of synchronized keyword? Obviously synchronous blocks the current thread.

For example:

```java
  public static boolean getLockSync(Runnable r) {

    if (isLocked) {
      r.run();
      return true;
    }

    synchronized (My.lock) {  // this is blocking, could block for more than 1-2 ms
      isLocked = true;
      r.run();
      isLocked = false;
      return false;
    }

  }
```
I can return a boolean from this block - it's synchronous. Is there a way to do this asynchronously?

Something like this:

```java
  public static void getLockAsync(Runnable r) {

    if (isLocked) {
      CompletableFuture.runAsync(r);
      return;
    }

    Object.onLockAcquisition(My.lock, () -> {  // this is non-blocking
           isLocked = true;
           r.run();
           isLocked = false;
           Object.releaseLock(My.lock);
     });

  }
```
I made up the Object.onLockAcquisition method, but looking for something like that.

Object.wait() and Object.notify() are for threads, I don't think a non-blocking locking system will play well with traditional synchronization primitives

**Comment by tsegismont** [comment]
Your question on SO has been answered, Vert.x provides an asynchronous lock API. So I'm not sure what's the feature request.

**Comment by ORESoftware** [comment]
@tsegismont my only request would be to expose the local (non-networked) lock API as a first-class call, if it's not already

**Comment by tsegismont** [comment]
Ok then it's on the roadmap for Vert.x 4 (and may be brought forward to 3.7).
