### ISSUE TITLE
Use JsonArray along with JsonObject

### ISSUE THREAD

**Issue by ORESoftware** [eclipse-vertx/vert.x#2828]
I looked through the source code, and therefore I believe this is a request not a question.
Say we have a SQLConnection conn:

```java
   conn.query("select * from bagel", res -> {
        JsonObject o = res.result().toJson();
        ctx.response().end(o.toString());
   });
```

however it's pretty obvious that this query is going to return a list (of rows), so always putting everything in a JsonObject is not very refined. **I would hope for something like this instead:**

```java
   conn.query("select * from bagel", res -> {
        JsonArray o = res.result().toJsonArray();
        ctx.response().end(o.toString());
   });
```

but that call doesn't seem to exist. I looked through the source, I see this for toJson();

```java
ResultSetConverter.toJson(this, obj);
```

which converts into:

```java
  public static void toJson(ResultSet obj, JsonObject json) {
    toJson(obj, json.getMap());
  }
```

which calls:

```java
public static void toJson(ResultSet obj, Map<String, Object> json) {
    JsonArray array;
    if (obj.getColumnNames() != null) {
      array = new JsonArray();
      obj.getColumnNames().forEach((item) -> {
        array.add(item);
      });
      json.put("columnNames", array);
    }

    if (obj.getNext() != null) {
      json.put("next", obj.getNext().toJson());
    }

    json.put("numColumns", obj.getNumColumns());
    json.put("numRows", obj.getNumRows());
    if (obj.getOutput() != null) {
      json.put("output", obj.getOutput());
    }

    if (obj.getResults() != null) {
      array = new JsonArray();
      obj.getResults().forEach((item) -> {
        array.add(item);
      });
      json.put("results", array);
    }

    if (obj.getRows() != null) {
      array = new JsonArray();
      obj.getRows().forEach((item) -> {
        array.add(item);
      });
      json.put("rows", array);
    }

  }
```

the above code is very if/elsey - I think it would be nice to see a toJsonArray and toJson method?

if it couldn't be converted to an array, it would throw an Exception, which is fine. If it's an array and you attempt to convert it to a single object, then it would also throw.

Is this a good idea? All I see right now is:

![screenshot from 2019-02-12 18-28-26](https://user-images.githubusercontent.com/11139560/52682370-0d353700-2ef4-11e9-8614-43651404df7c.png)

**Comment by okou19900722** [comment]
ResultSet is annotated with @DataObject，if you will use it as a param in `vertx-service-proxy`, it's require a method called `toJson` with empty params to return a JsonObject.

see https://github.com/vert-x3/vertx-service-proxy/blob/9d2a5641085a81d17adb67663fa4eefed760fef8/src/main/java/io/vertx/serviceproxy/generator/model/ProxyModel.java#L67-L74

**Comment by ORESoftware** [comment]
I am confused.

What is the quickest way to create a `JsonArray` from a ResultSet? i guess thats what I want to know.

**Comment by okou19900722** [comment]
Maybe `getRows()` is what you want

**Comment by tsegismont** [comment]
See the docs for [executing queries](https://vertx.io/docs/vertx-sql-common/java/#_executing_queries) and traversing the rows:

```
List<String> columnNames = resultSet.getColumnNames();

List<JsonArray> results = resultSet.getResults();

for (JsonArray row : results) {

  String id = row.getString(0);
  String fName = row.getString(1);
  String lName = row.getString(2);
  int shoeSize = row.getInteger(3);

}
```

**Comment by tsegismont** [comment]
@ORESoftware please see https://vertx.io/community/

This is the Vert.x core library repository, if you're not sure how to use the best course of action is going to the user forum first. Thank you.

**Comment by ORESoftware** [comment]
@tsegismont  this is a feature request, I am looking for this call:

```java
JsonArray o = res.result().toJsonArray();
```

**Comment by okou19900722** [comment]
`getRows()` is what you want

**Comment by ORESoftware** [comment]
Yes that provides:

```java
        List<JsonObject> o = res.result().getRows();
```

but I guess it's just surprising that we can't do this:

```java
JsonArray o = res.result().toJsonArray();
```

**Comment by okou19900722** [comment]
Maybe `getRows()` should return a JsonArray, but `List<JsonObject>` is clearer.
If you really need JsonArray, you can use:
```java
JsonArray o = new JsonArray(res.result().getRows());
```
