### ISSUE TITLE
Should be a json() convenience method on ctx.response()

### ISSUE THREAD

**Issue by ORESoftware** [eclipse-vertx/vert.x#2829]
I am looking this:

![screenshot from 2019-02-12 23-49-12](https://user-images.githubusercontent.com/11139560/52695290-f3f6af80-2f20-11e9-9dfb-82f7be7c341a.png)

I just want to write json to the response. I assume the right way to do this now is something like:

```java     
 ctx.response().end(r.result().toJson().toString());
```

but I wonder if there could exist a json() method or sendJson() method that could accept various different kinds of JSON library types and handle them.

**Comment by pmlopes** [comment]
@ORESoftware Yes json and many more will be added with 4.0 as it has already been planned during the roadmap.

The umbrella issue is here: https://github.com/vert-x3/vertx-web/issues/1109
