### ISSUE TITLE
HttpClientRequest.get/getNow is deprecated, what should I use instead?

### ISSUE THREAD

**Issue by arniu** [eclipse-vertx/vert.x#2831]

**Comment by okou19900722** [comment]
you must press the warning.
 it's will be change to `get/getNow(Handler<AsyncResult<HttpResponse>> handler)` from `get/getNow(Handler<HttpResponse> handler) ` in `4.x`

**Comment by tsegismont** [comment]
@arniu what do you use the `HttpClient` for? In most cases, you should prefer the [Vert.x Web Client](https://vertx.io/docs/vertx-web-client/java/) over the `HttpClient` (which is more low-level stuff).

**Comment by petarov** [comment]
@tsegismont I'm utilizing the `HttpClient` in a Vert.x based HTTP proxy server. I'm still unsure of the full impact of the 4.x changes (still need to review the `AsyncResult<HttpResponse>` change). 

Would you also recommend the Vert.x Web Client for an HTTP proxy server implementation?

**Comment by arniu** [comment]
@tsegismont Just testing the app created by [vertx-starter](http://start.vertx.io/).

**Comment by tsegismont** [comment]
@arniu then the Vert.x Web Client will do just fine

**Comment by tsegismont** [comment]
@petarov if you have an entire code base working with `HttpClient` then, when upgrading to Vert.x 4, I would advise to:
- start using the new methods with `Handler<AsyncResult<HttpResponse>>` params for production
- evaluate the Web Client for your use case

We had good feedback on the HTTP proxy with the Web Client but YMMV.
