### ISSUE TITLE
Add static method JsonObject.from()

### ISSUE THREAD

**Issue by ORESoftware** [eclipse-vertx/vert.x#2832]
I believe this can create a JsonObject from a string:

```java
 JsonObject o = new JsonObject(`{"foo":"bar"}`);
```

however, I expected this to work:

```java
 JsonObject o = JsonObject.from(`{"foo":"bar"}`);
```

but there is no `from()` static method...this would be a nice-to-have.

**Comment by pmlopes** [comment]
How would the static method be better than the constructor? They both achieve the same result.

**Comment by ORESoftware** [comment]
@pmlopes because people don't know what the constructor does necessarily..I am just telling you I would expect the from method to exist

**Comment by pmlopes** [comment]
The current constructor already achieves the same result and is documented. Your IDE would also let you figure out the behaviour by showing all the possible combinations. Adding a new static factory method would bring confusion as there will be multiple way to achieve the same result.

If you want to have full control then you still can by using the `JSON` object:

```java
Json.decodeValue(json, List.class)
```

Which explicitly lets you decode a value into the desired container class.
