### ISSUE TITLE
i dont underestand this behavior

### ISSUE THREAD

**Issue by javad-salehi** [eclipse-vertx/vert.x#2849]
@Override
    public void start(Future<Void> future) throws Exception {
        System.out.println("start : "+Thread.currentThread().getName());
        vertx.setPeriodic(1000,res->{
           System.out.println("1 : "+Thread.currentThread().getName());
            try {
                Thread.currentThread().sleep(2000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        });
        vertx.setPeriodic(400 , res->{
           System.out.println("2 : " + Thread.currentThread().getName());
        });
        future.complete();
    }
verticle is worker verticle , DeplpymentOptions().setWorker(true).
why the second operation (setPriodic) synced with first.
if the first operation have a long time process why the second operation must w8ing for it , while we used worker thread and worker threads used for long operation.
plz explain this behavor , sorry my english is not good.TY.

**Comment by dgoetsch** [comment]
Worker verticles don't parallelize their work, that's their most important feature. You are blocking the worker for more than the periodic interval on the first call, the periodics are looping as tightly as they can to keep up with the simulated load.

Try printing the thread name in both periodic calls. Also try removing the call to thread.sleep.

**Comment by vietj** [comment]
thanks @dgoetsch
