### ISSUE TITLE
Can not close file while upload empty file or zero size file

### ISSUE THREAD

**Issue by fishjam** [eclipse-vertx/vert.x#2856]
- reproduce step
  - start [upload server sample](https://github.com/vert-x3/vertx-examples/tree/master/web-examples/src/main/java/io/vertx/example/web/upload) in vertx-examples.
  -  don't choose file or choose empty file(size is 0) and upload
  -  after upload, check program's open file with lsof( on linux ) or processexplore(on windows)
  - can see the remain uploaded file handle
![image](https://user-images.githubusercontent.com/1870684/53576904-a67c7280-3baf-11e9-877f-eb8bb8c161b7.png)

- preliminary analysis
  - it seems that the HttpServerFileUploadImpl.streamToFileSystem does not set the file variable,  it's null, and can not close while handleComplete. But I'm not sure about it now.

**Comment by fishjam** [comment]
Another error scenarios:
  - If cancel the upload while uploading, then can not close the file,
  - Example: close the browser while upload a big file

**Comment by fishjam** [comment]
1. zero file issue can fixed by change 
"context.owner().fileSystem().open(filename...) to "context.owner().fileSystem().openBlocking", this can guarantee the file is not null when handleComplete called.

**Comment by vietj** [comment]
can you provide a reproducer test to help ?

**Comment by fishjam** [comment]
@vietj , I reproduce this issue by vertx-examples. you can find it at [upload Server](https://github.com/vert-x3/vertx-examples/tree/master/web-examples/src/main/java/io/vertx/example/web/upload).

**Comment by vietj** [comment]
can you provide a PR with a test for vertx-core reproducing it ?

**Comment by fishjam** [comment]
OK, I will try to write a test for reproduce this issue in vertx-core. 
But according my analysis,  zero file can be fixed in vertx-core, but exception while uploading, maybe need change both vertx-core and vertx-web.

**Comment by fishjam** [comment]
@vietj I create PR [2857](https://github.com/eclipse-vertx/vert.x/pull/2857), please confirm it.
But it only can reproduce scenario 1: empty file or zero size file

**Comment by vietj** [comment]
it seems indeed there is a race condition when the file is empty, the asynchronous file is opened after the empty content is uploaded leaving a file open.

**Comment by vietj** [comment]
working on a fix

**Comment by vietj** [comment]
fixed by https://github.com/eclipse-vertx/vert.x/issues/2859 would you mind to check ?
