### ISSUE TITLE
Deprecate EventBusOptions delegates in VertxOptions

### ISSUE THREAD

**Issue by gofabian** [eclipse-vertx/vert.x#2873]
We had a 2 days effort because the API is misleading:

	VertxOptions options = new VertxOptions()
		.setClustered(true)
		.setClusterHost("10.x.y.z")
		.setClusterPort(60000);
	
	System.out.println(options);
	
	options
		.setEventBusOptions(new EventBusOptions()
			.setSsl(true)
			.setKeyStoreOptions(new JksOptions())
		);
	
	System.out.println(options);

This will result in:

    VertxOptions{..., eventbus={"clustered":true,"host":"10.x.y.z","port":60000,"ssl":false, ...}
    VertxOptions{..., eventbus={"clustered":false,"host":"localhost","port":0,"ssl":true, ...}

But I expected:

    VertxOptions{..., eventbus={"clustered":true,"host":"10.x.y.z","port":60000,"ssl":false, ...}
    VertxOptions{..., eventbus={"clustered":true,"host":"10.x.y.z","port":60000,"ssl":true, ...}

In my opinion the API should be changed in order to reduce the confusion. If I configure an option it should not be changed after setting other options.

Workaround #1:

	VertxOptions options = new VertxOptions()
		// set event bus options at first
		.setEventBusOptions(new EventBusOptions()
			.setSsl(true)
			.setKeyStoreOptions(new JksOptions()))
		.setClustered(true)
		.setClusterHost("10.x.y.z")
		.setClusterPort(60000);

Workaround #2:

	VertxOptions options = new VertxOptions()
		.setClustered(true)
		.setClusterHost("10.x.y.z")
		.setClusterPort(60000);
	
	// do not overwrite event bus options but change the default one
	options.getEventBusOptions()
		.setSsl(true)
		.setKeyStoreOptions(new JksOptions());

**Comment by vietj** [comment]
@gofabian I agree with you this should be changed in vertx 4 and perhaps we need to remove the top level setters on VertxOptions

**Comment by vietj** [comment]
we do have something similar with metrics and file system options

**Comment by tsegismont** [comment]
+1

I believe this was added because initially we didn't have the -options arg
on the command line (externalized options).

It's less useful now. If we do this we should deprecate the corresponding
options in 3.7 though

**Comment by vietj** [comment]
yes pretty much like FileSystemOptions

**Comment by tsegismont** [comment]
I'll take of it then

Le jeu. 14 mars 2019 à 18:01, Julien Viet <notifications@github.com> a
écrit :

**Comment by vietj** [comment]
what do you mean ?

**Comment by vietj** [comment]
we can't remove that in 3.7 only mark it as deprecated and remove it in master

**Comment by tsegismont** [comment]
Yes, I didn't mean anything else.

**Comment by vietj** [comment]
😅 that was not clear enough to me :-)

**Comment by tsegismont** [comment]
Closed in #2883
