### ISSUE TITLE
web socket responses are not being sent on eventBus.Message

### ISSUE THREAD

**Issue by GortiPavan** [eclipse-vertx/vert.x#2875]
I would like to use a single socket connection, to send multiple messages to Socket server and receive the response from the socket server and reply via **eventBus.Message.** 

```public class SocketClient extends AbstractVerticle {

    @Override
    public void start(Future<Void> startFuture) {

        HttpClient client = vertx.createHttpClient();
        client.websocket(9090, "localhost", "/socketDuplicate", webSocket -> {
            this.vertx.eventBus().<String>consumer("/socketClient")
                    .toFlowable()
                    .subscribe(message ->
                            webSocket.writeBinaryMessage(Buffer.buffer(message.body())).handler(buffer -> {
                                System.out.println("Buffer is " + buffer.toString() + " for request " + message.body());
                                message.reply(buffer.toString());
                            }));
            startFuture.complete();
        });
    }
}
```

but the response from the socket server is not being sent via message.reply.
I tried with HTTP client, that seems to be working fine. 
To replicate: https://github.com/pavanGorti/vertx_socket_issue_replicate (expected & actual output are in README.md)

Please point out where am I going wrong.

**Comment by vietj** [comment]
I think the main issue here is that you overwrite the handler each time you write a message.

what you should do instead is send the message to the websocket and add the Message in a FIFO queue

you set a single handler on the websocket and when you receive a message you retrieve the Message from the FIFO queue and reply to it.
