### ISSUE TITLE
JsonArray: Shall we remove `Objects.requireNonNull` when `add` some value

### ISSUE THREAD

**Issue by arniu** [eclipse-vertx/vert.x#2876]

**Comment by vietj** [comment]
you mean as opposed to `addNull()` ?

**Comment by vietj** [comment]
that's actually an interesting question, because doing something like:

```
String s = getSomeString();
if (s == null) {
  array.addNull();
} else {
  array.add(s);
}
```

is not a great thing.

But perhaps I'm missing something there.

**Comment by vietj** [comment]
cc @pmlopes @tsegismont @jponge any opinion on this ?

**Comment by tsegismont** [comment]
+1 to improve usability

Le mer. 13 mars 2019 à 09:25, Julien Viet <notifications@github.com> a
écrit :

**Comment by arniu** [comment]
In my opinion, checking null here is just to carry coals to Newcastle.

When `null` should be processed for special, we may add some other value, or take some other action. In the case, it's good for nothing just to throw a `NullPointerException` here. 

When `null` is acceptable, just add it. In this case, checking null is obviously unnecessary.

So, we may remove `Objects.requireNonNull` and let users handle it.

**Comment by jponge** [comment]
Null is part of the JSON spec, so `add(null)` should add a JSON null.

**Comment by vietj** [comment]
this is changed to allow null now - see https://github.com/eclipse-vertx/vert.x/issues/2880
