### ISSUE TITLE
LoggerFactory doesn't work for static final logger

### ISSUE THREAD

**Issue by uicodefr** [eclipse-vertx/vert.x#2882]
I try to use Log4j2 as my Logger using the LoggerFactory of vertx.
And after many tests, I found the problem but I don't understand it.

I use vertx in version 3.6.3

My code :
```
public class MainVerticle extends AbstractVerticle {

    private static final Logger LOGGER = LoggerFactory.getLogger(MainVerticle.class);

    @Override
    public void start(Future<Void> startFuture) throws Exception {

        // Show the logger use by Vertx
        System.out.println("Logger: " + System.getProperty("vertx.logger-delegate-factory-class-name"));
        LoggerFactory.initialise();
        System.out.println("LoggerDelegate1: " + LOGGER.getDelegate().getClass());
        System.out.println("LoggerDelegate2: " + LoggerFactory.getLogger("toto").getDelegate().getClass());

```

The result in my console :
```
:run
Starting vert.x application...
bb1bc572-859c-430b-a200-bd8b256da26a-redeploy
Logger: io.vertx.core.logging.Log4j2LogDelegateFactory
LoggerDelegate1: class io.vertx.core.logging.JULLogDelegate
LoggerDelegate2: class io.vertx.core.logging.Log4j2LogDelegate
```

My config seems good because the System property has the good value.
But all my loggers are static final in my class, so they use JUL instead of Log4j2.
It is a bug ?

**Comment by vietj** [comment]
you need to set the system property as a JVM argument so it has the right value before the JVM starts.

**Comment by uicodefr** [comment]
> 
> you need to set the system property as a JVM argument so it has the right value before the JVM starts.

I did it like that :
```
run {
  args = ['run', mainVerticleName, "--redeploy=$watchForChange", "--launcher-class=$mainClassName", "--on-redeploy=$doOnChange",
    "-Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory"]
}
```
in my file "build.gradle"

It is wrong ?

**Comment by vietj** [comment]
I think the logger -D argument must passed before `run` in the CLI arguments to be taken in account by the JVM

**Comment by uicodefr** [comment]
I'm giving up, I did not succeed to configure gradle correctly for using log4J2 with the vertx logger.
By seeking solutions, I found this : https://github.com/eclipse-vertx/vert.x/issues/2774
So, I'm going to use log4j2 directly.

Merci pour ton aide.

**Comment by vietj** [comment]
yes it is discouraged to use vertx logger, but we won't push users to do so in 3.x, only in 4

**Comment by adamdickmeiss** [comment]
OK. So apps use log4j or similar. But Vert.x itself.. If we want to check that out in version 4. What then?

FWIW, I have it to still work with the delegation if I ensure it's the first thing happening in static main. So good for now.

**Comment by tsegismont** [comment]
@uicodefr I'm not a Gradle expert but I believe the argument in your snippet is given to the JVM watching for redeploy, not the JVM actually deploying the verticles. Perhaps @jponge or @cescoffier can confirm
