### ISSUE TITLE
some confuse about setTimer

### ISSUE THREAD

**Issue by User979269852** [eclipse-vertx/vert.x#2887]
recently such a problem came to me,I write my code like this:
public void test(){
vertx.setTimer(10000,handle -> {
try{
// do something;
test();
} catch(e){
test();
}
});
}
but amazingly I found that the timer would exit after it work for several times. Do anyone know why? Thanks a lot.

**Comment by vietj** [comment]
what do you mean by "exit" ?

**Comment by User979269852** [comment]
I wish the timer all the time.but “something “happened and the timer did not work in next 10s,I wonder what “something” was
