### ISSUE TITLE
This code still does not understand

### ISSUE THREAD

**Issue by zb564739784** [eclipse-vertx/vert.x#2890]
// Need to set context before constructor is called as writehandler　registration needs this
    ContextImpl.setContext(handler.context);

**Comment by vietj** [comment]
not sure what you are trying to achieve, can you elaborate more ?

**Comment by zb564739784** [comment]
I down ! 
`// Need to set context before constructor is called as writehandler　registration needs this
ContextImpl.setContext(handler.context);`

setting EventLoopSize > Verticle Size
Ｏ（∩＿∩）Ｏ
