### ISSUE TITLE
Vert.x deployment issue on new verticle with new library

### ISSUE THREAD

**Issue by RaiBnod** [eclipse-vertx/vert.x#2906]
I have a verticle which can deploy other verticles as services. And on the deployment of new verticle having new dependency like `vertx-circuit-breaker` (this library exist only on the new verticle that is going to be deployed) shows error like this:

`Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: io/vertx/circuitbreaker/CircuitBreaker`

But when we include that library on main verticle from where we are deploying new verticle, it works perfectly fine.

The dependencies of new verticle is not able to resolve dynamically by the verticle from where we are deploying other verticles as services.

**Comment by vietj** [comment]
how do you deploy the verticle ? if you want to add extra class path you need to make it isolated or use the Maven service factory https://github.com/vert-x3/vertx-examples/tree/master/maven-service-factory-examples

**Comment by RaiBnod** [comment]
No my question was not how do you deploy the verticle. Deploying new verticle shows issue of `NoClassDefFoundError` while we are using new extra libraries on the verticle which is going to be deployed.

**In the above example:**

If `maven-service-factory-verticle` uses extra dependency than on `maven-service-factory-api` (Try to include `vertx-circuit-breaker` on `maven-service-factory-verticle`), it shows the error like:

`Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: io/vertx/circuitbreaker/CircuitBreaker`

on the deployment. And after adding those all dependencies of `maven-service-factory-verticle` to the `maven-service-factory-api`, it solves the problem.

**Comment by RaiBnod** [comment]
@vietj do you have any response?
