### ISSUE TITLE
bareCommand.getJsonFromFileOrString can not read classpath file

### ISSUE THREAD

**Issue by misaka19002** [eclipse-vertx/vert.x#2913]
"-conf" can only read non-classpath configuration files.
Maybe we should check the "jsonFileOrString" ,if starting with “classpath:”read configuration file from classpath.

**Comment by tsegismont** [comment]
Good idea. To be consistent with the Filesystem API, it would be better to avoid the `classpath:` prefix and look for the file on filesystem first, classpath second.

**Comment by 1024bits** [comment]
@tsegismont  agree.

**Comment by 1024bits** [comment]
Is there any plan to do this？

**Comment by tsegismont** [comment]
Not a priority right now. Would you like to contribute the changes?
