### ISSUE TITLE
Vertx.getOrCreateContext unexpected behaviour

### ISSUE THREAD

**Issue by glassfox** [eclipse-vertx/vert.x#2914]
Hi guys,
After 3.7.0 upgrade my system provides unexpected behavior with the data in a Context.
Currently I working for reproduction test. (Will take some time).
Following some inputs:
1. In start() method of Verticle initialized object and set to actual context via Context.put().
2. Later in code, I trying to get this object from context (context.get()), but its null.
3. This is a web application and data over via Router.

**Comment by vietj** [comment]
any news about this @glassfox

**Comment by glassfox** [comment]
will take some time @vietj
