### ISSUE TITLE
routingContext.request().resume() ends current request

### ISSUE THREAD

**Issue by gentritgojani** [eclipse-vertx/vert.x#2926]
Version
vert.x core: 3.7.0
vert.x web: 3.7.0
Context
When using routingContext.request().pause() and routingContext.request().resume() I'm getting "Request has already been read" exception. When using vert.x 3.5 it is working fine.

Steps to reproduce
Here is my AuthHandler which is the first hander in my Router. It checks if there is a valid session and if yes it calls routingContext.next() to continue to the next handlers https://gist.github.com/gentritgojani/b9935ecd146cc0c2f5a8f36f177e459a

When using vert.x 3.5 it works fine but in vert.x 3.7 in my next handler I'm getting "Request has already been read" exception.

Here is the implementation of resume method of HttpServerRequestImpl in vert.x 3.5
https://gist.github.com/gentritgojani/8e165258d06dc723c27131c47e45de63

and here is the implementation of resume method of HttpServerRequestImpl in vert.x 3.7
https://gist.github.com/gentritgojani/30de75d9b72005ad7a12e5a24c002d62

In my case !pending.resume() is returning true so then doEnd() is called.

**Comment by vietj** [comment]
can you move this issue to the vertx-web project instead ?

**Comment by gentritgojani** [comment]
I created this issue there but @pmlopes asked me to move it here https://github.com/vert-x3/vertx-web/issues/1257

**Comment by vietj** [comment]
ok, can this be reproduced without vertx-web then ?
