### ISSUE TITLE
message by message

### ISSUE THREAD

**Issue by vincent78** [eclipse-vertx/vert.x#2932]
how can i get the message chain ,i want to know the pre message info (headers).

first i want add outInterceptor (EventBusImpl.addOutboundInterceptor) so it can run by handler,but i find the OutboundDeliveryContext.replierMessage is private  .in the handler ,i can't get the replierMessage.

second i find the EventBusImpl.sendReply has the input param(replierMessage) but not used.

:)

what can it do to get the replierMessage.headers  ,i will logger the  message invoked chain

**Comment by vietj** [comment]
replier message is the message sending a reply and not the actual message
