### ISSUE TITLE
MessageProducerImpl runs out of credits when using send() in publish-mode

### ISSUE THREAD

**Issue by Crokoking** [eclipse-vertx/vert.x#2933]
The MessageProducerImpl uses a credit-system to not overfeed the receiver. The credits get added back by a receiver via the credit-address. 
But this mechanism is only active in send=true mode. In publish mode the credits still get subtracted and checked - but never refilled. So as soon as the producer runs out of credits, its send() method stops working altogether.

**Comment by Crokoking** [comment]
Ahh, my mistake - i should be using write() instead of send(). That should probably throw an excepion

**Comment by vietj** [comment]
likely send should throw an IllegalStateException ?

**Comment by Crokoking** [comment]
The MessageProducer javadoc for send() says "This method actually sends a message using the send semantic regardless this producer is a sender or a publisher". So the intent was for send to still be usable.

**Comment by vietj** [comment]
yes, I'm wondering why we did that

**Comment by Crokoking** [comment]
Might actually be nicer for the publisher to be its own interface

**Comment by anelam** [comment]
I ran into the same problem.
What is the best practise to use the publish mechanism now?

**Comment by vietj** [comment]
you need to use the publish method on sender, I think that we should clarify this and perhaps remove these methods in vertx 4

**Comment by anelam** [comment]
Okay thanks.

But what about a fix in the current version?
The `MessageProducerImpl` knows if it is a sender or publisher.

**Comment by vietj** [comment]
the MessageProducer send methods have been deprecated in 3.8 and removed in 4.0, please don't use them

**Comment by vietj** [comment]
see https://github.com/eclipse-vertx/vert.x/issues/3004 https://github.com/eclipse-vertx/vert.x/issues/3005

**Comment by vietj** [comment]
send should never be used for publishing message
