### ISSUE TITLE
[Scala API] Handlers cannot be unset

### ISSUE THREAD

**Issue by sumnulu** [eclipse-vertx/vert.x#2938]
Example:
`response.handler(null)`  will not work as intended (to release the reference) because scala api will wrap it with a new function 

 io.vertx.scala.core.http.HttpClientResponse#handler
```
  def handler(handler: Handler[io.vertx.core.buffer.Buffer]): HttpClientResponse = {
    asJava.asInstanceOf[JHttpClientResponse].handler({x: Buffer => handler.handle(x)})
    this
  }
```

As a work around one must cast it to the Java class

**Comment by tsegismont** [comment]
@sumnulu thanks for reporting. This is the repository for Vert.x core development, do you mind to re-open the issue in https://github.com/vert-x3/vertx-lang-scala/issues/new ? Thanks. There are higher chances it's not missed by @pflanzenmoerder

**Comment by sumnulu** [comment]
closing, thanks.
ref: https://github.com/vert-x3/vertx-lang-scala/issues/81
