### ISSUE TITLE
Ambiguous Exception on Timeouts

### ISSUE THREAD

**Issue by dave-fl** [eclipse-vertx/vert.x#2947]
This is on 3.7.1 BUILD-SNAPSHOT

If configuring the HttpClient like so.

    HttpClientOptions httpClientOptions = new HttpClientOptions()
				.setConnectTimeout(connectTimeout).setIdleTimeoutUnit(TimeUnit.MILLISECONDS).setIdleTimeout(idleTimeout)
				.setTcpQuickAck(true)
				.setReusePort(true);

When the timeout does take place.

			httpClientRequest.handler(response -> {
				serverResponse.setStatusCode(response.statusCode());
				response.pipeTo(serverResponse);
			});

			httpClientRequest.exceptionHandler(throwable -> {
				throwable.printStackTrace();
				serverResponse.end();
			});

There is no TimeoutException.  The exception used is `io.vertx.core.VertxException: Connection was closed`

Is there anyway to determine if the connection was closed by the client itself (as a result of the timeout) or if it was terminated by the server.

**Comment by vietj** [comment]
have you tried using setTimeout on HttpClientRequest ? it might be more suitable to what you are doing.

**Comment by dave-fl** [comment]
That seems to use a different exception (which prints a more detailed message, but it is still a generic exception that might be good enough, still not a timeout).

What is nice about setting them on the options is that I get the same settings across all uses of the client and within my app I guarantee that each Verticle has at most 1 http client instance (used in multiple places).  The alternative is that I'd have to wrap the client with this possible work around.

**Comment by dave-fl** [comment]
Can do that - but not as clean.

If adding
```
    handleException(new TimeoutException(msg) {
      @Override
      public synchronized Throwable fillInStackTrace() {
        return this;
      }
    });
```

to `handleIdle`.  should `super.handleIdle()` still be called?

**Comment by dave-fl** [comment]
If a number of calls are wrapped in a timer in Rx, and that timer happens before other timers e.g. midflight what happens to those requests?

**Comment by dave-fl** [comment]
@vietj Going to work around it.
