### ISSUE TITLE
Properties for HttpMethod

### ISSUE THREAD

**Issue by VictorQRS** [eclipse-vertx/vert.x#2952]
For vert-x3/vertx-web#460, I need to know if a HttpMethod is **safe** (leads to a read-only operation: GET, HEAD, OPTIONS), **idempotent** (does not have any side-effect: all safe one plus PUT and DELETE) or **migh have a body**(POST, PUT, DELETE, TRACE, CONNECT, PATCH).

Although, I could add an utility on vertx-web, it would be more appropriate to add these properties together with HttpMethod.

Sources:
- Safe: https://developer.mozilla.org/en-US/docs/Glossary/safe
- Idempotent: https://developer.mozilla.org/en-US/docs/Glossary/idempotent
- MighHaveBody: https://tools.ietf.org/html/rfc7231#section-4.3

**Comment by jekkel** [comment]
Note that `GET` requests also "might have a  body" although "without defined semantics". It's not forbidden and I've seen APIs using it.

**Comment by VictorQRS** [comment]
Well, in that case, I can remove the MighHaveBody method as this seems more related to the request than to the type of HTTP method. Also, I might be able to live without it.

I will remove it as soon as possible.

@jekkel Are the rest of the methods OK?

**Comment by jekkel** [comment]
Conceptually: yes. Technically this somewhat crosses a line: To my understanding the core type `HttpMethod` represents a protocol element whereas your changes apply semantics regarding how those element values "should" or are expected to be used. Following the vertx philosophy of being "unopinionated" I'd prefer attaching this information externally to vertx core, maybe in the rerouting handler module your changes are meant to ease the implementation for. Adding the body expectation there also wouldn't do any harm then. But this is my personal taste and I'd relay this decision to the project members/maintainers.

**Comment by VictorQRS** [comment]
What do you think? @pmlopes

**Comment by pmlopes** [comment]
Although I understand this, I think that probably this should be an utility set of functions. For 2 reasons:

1. Like @jekkel said, lets keep vert.x KISS
2. When working with polyglot languages languages who don't know about enums (e.g.: JavaScript) they will be denied the possibility of using these methods.

Then having something like:

```java
@VertxGen
public interface HttpMethodXXX {
  static boolean isIdempotent(HttpMethod method);
  static boolean isSafe(HttpMethod method);
...
```

**Comment by VictorQRS** [comment]
Fair points. I should add this utility set of functions to vertx-web in this case, right?

**Comment by pmlopes** [comment]
I would say yes. I believe there's an utilization class already there, maybe it can be there if this just to be used by the handlers.
