### ISSUE TITLE
Couchbase SDK with Vert.x and Netty server issues

### ISSUE THREAD

**Issue by himanshumps** [eclipse-vertx/vert.x#2958]
I am **suspecting and do not have sample application to create the issue** that there is an issue while using couchbase SDK with vert.x and some dependency injection(like spring-boot-autoconfigure, guice).

If the couchbase SDK connects to cluster before the vert.x httpserver creation, the SDK starts a netty server and the same netty server is getting used while vert.x create the new HttpServer.

The reason I am suspecting that is because when I use reactive extensions with vert.x, I see cb-io threads being used for the processing of normal rxjava code. If the vert.x http server would have started, I would have seen the io- pool for processing of rxjava code.

Also I am seeing this at the start of the code which is making me suspect that this being the cause.

`11:38:44.173 [vert.x-eventloop-thread-2] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 162448 (auto-detected)`

**Comment by tsegismont** [comment]
I'm not sure what you mean by the same Netty server is used, given a Vert.x HTTP server and Couchbase client are involved.

You will see Couchbase client threads in logs if you do not hop back on the event loop after interacting with the client. See https://vertx.io/docs/vertx-rx/java2/#_scheduler_support

**Comment by himanshumps** [comment]
@tsegismont I have now changed the implementation to hop back to vertx event loop thread using the observeOn ... But my query still remains .. If there are two netty server running, how to use rxjava to use a specific instance of vertx. Couchbase creates an IO pool which may be causing the delay in case of load testing.

**Comment by vietj** [comment]
@himanshumps can you provide a reproducer so we can examine the issue and provide guidance ?

**Comment by himanshumps** [comment]
I am not able to recreate the issue ... Let me try to put a sample app together with local couchbase instance and some test data. I will share the application code in another 2-3 hours.

**Comment by himanshumps** [comment]
I am not able to recreate the issue with the test program. You can close this issue for now. I will keep trying to recreate the issue and if able to do it, will open another issue

**Comment by vietj** [comment]
thanks let us know.
