### ISSUE TITLE
Why Vert.x json renames my object properties?

### ISSUE THREAD

**Issue by AhmedMKamal** [eclipse-vertx/vert.x#2959]
I have a data class like the following

```
data class User(val id: String,
                val name: String,
                val isVerified: Boolean)
```

When I'm trying to serialize it using `io.vertx.core.json.Json.encode(user)`, I expect the result to be

```
{
  "id": "",
  "name": "",
  "isVerified": false
}
```

but I got

```
{
  "id": "",
  "name": "",
  "verified": false
}
```

**Comment by jekkel** [comment]
AFAIK vert.x uses Jackson underneath for data binding. And this behaviour looks like Jacksons way of converting bean properties to field names. So I guess you'd have to file a bug over there.

**Comment by AhmedMKamal** [comment]
Okay, I did, thanks.
