### ISSUE TITLE
Misleading function name

### ISSUE THREAD

**Issue by Warkst** [eclipse-vertx/vert.x#2960]
I had trouble setting up a basic authentication example and discovered by debugging that calling `routingContext.request().setExpectMultipart(true);` was the point of failure. I noticed that my call had no effect because the request wasn't using a valid multipart content type. I find it misleading to have a setter-like function which does not behave at all like a setter and, even worse, fails **silently** (see all the `if` with no matching `else`):

https://github.com/eclipse-vertx/vert.x/blob/11f52fc973f21d6a262f61b979aac0ef941ab55c/src/main/java/io/vertx/core/http/impl/HttpServerRequestImpl.java#L439

I suggest modifying the code so that if `expect` is `true` but setting the value can not be carried out, a runtime exception is thrown to warn the developer that the code is not behaving as expected. Alternatively, please at least include proper documentation that explains why this call may fail.

**Comment by vietj** [comment]
Hi, I think it makes sense indeed to throw an IllegalStateException, can you contribute a PR with tests ?

**Comment by Warkst** [comment]
@vietj I've created a fork and implemented the suggestion, but I'm unsure how to write a good test. Could you point me towards an already existing test that is similar, so that I use it as a reference?

**Comment by vietj** [comment]
there are plenty of good tests existing from HTTP test, simply study some of them that might be similar to your case.

**Comment by Warkst** [comment]
Sorry it took a while, I had some issues to get the build running locally. I also forgot to sign off on the commit, and didn't make an eclipse foundation account until after submitting the PR and noticing the red cross on the first check... @vietj would you take a look and let me know how to proceed from here?

**Comment by vietj** [comment]
see https://github.com/eclipse-vertx/vert.x/issues/3346
