### ISSUE TITLE
Cannot close file if one of the write operations fails

### ISSUE THREAD

**Issue by aygalinc** [eclipse-vertx/vert.x#2963]
Version :  
Vert.x : 3.7.0
Vert.x - Web : 3.7.0

I test thing with vert.x and I discover that :
-> If file transfer start , create file & fill it.
-> If disk size becomes full.
-> BodyHandler does not trigger an Http response.
-> The guilty seems to be the wich call close on the file but because it remains byte to write, closed is defered & never called, callback never called. 
https://github.com/eclipse-vertx/vert.x/blob/ba47fac59a4b78ff858b3858e7971083a2edce97/src/main/java/io/vertx/core/http/impl/HttpServerFileUploadImpl.java#L166-L180

because close will defer to :
https://github.com/eclipse-vertx/vert.x/blob/645f6d4d41e0301155501b1e287ac49d6e60573b/src/main/java/io/vertx/core/file/impl/AsyncFileImpl.java#L521-L531

and the because of writesOutstanding != 0 (some byte left because we cannot write the all things), close is defered and never called because the completion handler which is the only part who called the defered method is always in failure (no space on disk) : 
https://github.com/eclipse-vertx/vert.x/blob/645f6d4d41e0301155501b1e287ac49d6e60573b/src/main/java/io/vertx/core/file/impl/AsyncFileImpl.java#L163-L189
 
Reproducer : 
I have create a tempory partition on an unbuntu desktop (sudo mount -t tmpfs -o size=90M tmpfs /media/testUpload/) and try to download a file greater that 90Mo.

**Comment by aygalinc** [comment]
Have you some news about the fix i provide ?

**Comment by vietj** [comment]
I schedule this for study at 3.8.4

**Comment by vietj** [comment]
sorry for long delay, I think this is because this is a very difficult case to test

**Comment by aygalinc** [comment]
Thx for the update. The work that i have done is proposed in #2965 .
