### ISSUE TITLE
Vertx http request queuing

### ISSUE THREAD

**Issue by himanshumps** [eclipse-vertx/vert.x#2981]
Hi,

We have taken the vert.x hello world application and run that as a standalone application

Git Repo: https://github.com/himanshumps/web-examples.git
Maven Command: mvn clean install exec:java -Dexec.mainClass="io.vertx.example.web.helloworld.Server"

When we run the load test with a single user, we get the following response:

> Percentage of the requests served within a certain time (ms)
>   50%      3
>   66%      4
>   75%      4
>   80%      5
>   90%      5
>   95%      7
>   98%      9
>   99%     15
>  100%     65 (longest request)

When the same test is ran with 10 user, we get the following:

> Percentage of the requests served within a certain time (ms)
>   50%     28
>   66%     33
>   75%     38
>   80%     42
>   90%     59
>   95%     85
>   98%    148
>   99%    235
>  100%    252 (longest request)

When the same test is ran with 100 users, we get the following:

> Percentage of the requests served within a certain time (ms)
>   50%    455
>   66%    566
>   75%    651
>   80%    682
>   90%    874
>   95%   1177
>   98%   1354
>   99%   1406
>  100%   1949 (longest request)

As you can see from the test, as we increase the load on the application, the response time increases exponentially. 

Are the request getting queued up ?

When we used LoggerHandler, we can see the response time on the server is 0-3 ms. So where is the additional time going?

The similar results were seen when we ran it in a docker container with 1 core CPU and 4GB of RAM.

**Comment by vietj** [comment]
I don't know much about "ab" tool, when I run it, I can see it pausing for a long time and sometimes timing out (for some reason I ignore) : `ab -n 10000 -c 100 http://localhost:8080/` this supposedly runs 10000 requests with 100 connections.

```
MacBook-Pro-de-julien:~ julien$ ab -n 10000 -c 100 http://localhost:8080/ 
This is ApacheBench, Version 2.3 <$Revision: 1826891 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        
Server Hostname:        localhost
Server Port:            8080

Document Path:          /
Document Length:        12 bytes

Concurrency Level:      100
Time taken for tests:   0.753 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      760000 bytes
HTML transferred:       120000 bytes
Requests per second:    13279.40 [#/sec] (mean)
Time per request:       7.530 [ms] (mean)
Time per request:       0.075 [ms] (mean, across all concurrent requests)
Transfer rate:          985.58 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    3   0.8      3       6
Processing:     0    4   1.4      4      19
Waiting:        0    4   1.4      3      18
Total:          1    7   1.4      7      20

Percentage of the requests served within a certain time (ms)
  50%      7
  66%      8
  75%      8
  80%      8
  90%      9
  95%     10
  98%     11
  99%     12
 100%     20 (longest request)
MacBook-Pro-de-julien:~ julien$ ab -n 10000 -c 100 http://localhost:8080/ 
This is ApacheBench, Version 2.3 <$Revision: 1826891 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
apr_socket_recv: Operation timed out (60)
Total of 6444 requests completed
MacBook-Pro-de-julien:~ julien$ 
```

So I cannot really comment because my run gives mixed results (fairly good and one that does not complete).

When I use `wrk` tool in a similar fashion, I always get good results consistently (with similar setup):

```
MacBook-Pro-de-julien:~ julien$ wrk -c 100 -d 40 --latency http://localhost:8080
Running 40s test @ http://localhost:8080
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.55ms    1.23ms  22.46ms   79.50%
    Req/Sec    20.07k     2.34k   26.23k    68.50%
  Latency Distribution
     50%    2.24ms
     75%    2.93ms
     90%    4.19ms
     99%    6.75ms
  1597762 requests in 40.01s, 115.80MB read
Requests/sec:  39937.60
Transfer/sec:      2.89MB
```

Note that logging handler is a bottleneck in the benchmark and slows it down by a large margin.

When I disable it, I get better results:

```
MacBook-Pro-de-julien:~ julien$ wrk -c 100 -d 40 --latency http://localhost:8080
Running 40s test @ http://localhost:8080
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.55ms    3.83ms 130.22ms   99.25%
    Req/Sec    37.21k     3.83k   48.97k    84.34%
  Latency Distribution
     50%    1.28ms
     75%    1.36ms
     90%    1.58ms
     99%    3.40ms
  2954835 requests in 40.01s, 214.16MB read
Requests/sec:  73860.16
Transfer/sec:      5.35MB
```

**Comment by vietj** [comment]
You should give `wrk` a try and see how it behaves for you.
