### ISSUE TITLE
Spring Async + Vert.x issue - Vert.x thread / Netty eventloop blocked (may be a bug)

### ISSUE THREAD

**Issue by himanshumps** [eclipse-vertx/vert.x#2991]
Hi,

When an async spring task is getting executed, vertx/netty threads are blocked.

Reproducer Code: https://github.com/himanshumps/springVertxAsyncIssue.git

To see the issue in action: 

Once the application is deployed successfully, add a breakpoint at https://github.com/himanshumps/springVertxAsyncIssue/blob/0aa025a6f97a052545e74c1fff008473235c7d73/src/main/java/io/vertx/example/async/AsyncJob.java#L29 , wait for breakpoint to become active and then try to access https://localhost:8443/

Result: The https://localhost:8443/ will keep on processing and will not complete with status code 200 until we move forward the breakpoint.

**Comment by tsegismont** [comment]
What is the type of your breakpoint? By default breakpoints block all the JVM, but they can be configured to block only the thread involved.

**Comment by himanshumps** [comment]
The job is scheduled on a different task executor so only that thread will get blocked and vertx event loop should be running.
