### ISSUE TITLE
Vert.x have few RPS at slow Flowable

### ISSUE THREAD

**Issue by auryn31** [eclipse-vertx/vert.x#2992]
I'm currently developing a framework comparison. Among other things I have vert.x with me. However, I have a problem, which I do not understand, respectively can solve.

If I set the duration of an observable to about 100ms, I get only 8 requests per second with vert.x. I have 145 rps with Helidon or Quarks. 
If the response time is not reduced, vert.x also reacts to about 150 rps.

the code can be found here: 
https://github.com/auryn31/spring-async-rest-example/tree/master/reactive-backend/reactive-vertx

does anyone have an idea what I'm doing wrong? or is vert.x just slower with such requests?

Thanks

**Comment by vietj** [comment]
your DataService for Vert.x blocks the event loop thread.

I made a PR https://github.com/auryn31/spring-async-rest-example/pull/1 that makes a version of the DataService that uses the Vert.x scheduler for RxJava which give expected performance.

The original version was blocking the event loop with a thread sleep which will severely limit the performances. You can read this guide that explains the event loop more in details http://www.julienviet.com/advanced-vertx-guide/#_demystifying-the-event-loop

Now setting a timeout of 10 millis I get with the following results

Vert.x:

```
MacBook-Pro-de-julien:~ julien$ wrk -c 400 -d 10 http://localhost:8080/cars
Running 10s test @ http://localhost:8080/cars
  2 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   154.91ms   51.61ms 521.16ms   92.05%
    Req/Sec   830.37    374.32     1.30k    59.89%
  15418 requests in 10.01s, 10.51MB read
  Socket errors: connect 151, read 192, write 0, timeout 0
Requests/sec:   1540.26
Transfer/sec:      1.05MB
```

Helidon:

```
MacBook-Pro-de-julien:~ julien$ wrk -c 400 -d 10 http://localhost:8080/cars
Running 10s test @ http://localhost:8080/cars
  2 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   481.59ms  160.09ms   1.43s    83.55%
    Req/Sec   248.22     75.87   400.00     68.18%
  4481 requests in 10.07s, 3.43MB read
  Socket errors: connect 151, read 241, write 0, timeout 0
Requests/sec:    445.11
Transfer/sec:    348.59KB
```

I should have run the benchmark on two different machines (my bad) but I didn't have time to do it, I just wanted to fix quickly this benchmark.

Please don't hesitate to ask if you need more information or find something odd.

**Comment by auryn31** [comment]
thanks a lot :-)
