### ISSUE TITLE
Provide a compability with clickhouse ODBC

### ISSUE THREAD

**Issue by kostya05983** [eclipse-vertx/vert.x#2995]
Hello, Our company wants to use a driver for clickhouse with vertx. And we want to use ODBC driver for it. But vertx doesn't have a support of this driver. We want to develop lib and add such support. What are the requirements to take this library to vertx in future?  And what do you think about this? Maybe we shouldn't do this and use another way.
https://github.com/yandex/clickhouse-odbc
Thank you for help

**Comment by vietj** [comment]
@kostya05983 is there a java version of this library ?

**Comment by arsis1** [comment]
@kostya05983 Dose the vertx-clickhouse driver project is on going ? I wish to use it.

**Comment by kostya05983** [comment]
I figured out,@vietj, clickhouse has a jdbc driver, which we can use when configure jdbcClient. I close issue, because we can communicate through jdbc. @arsis1 you can use vertx jdbcClint for communication with clickhouse.
