### ISSUE TITLE
SSL handshake: Decouple from event loop

### ISSUE THREAD

**Issue by himanshumps** [eclipse-vertx/vert.x#2996]
In our application, we have used LoggerHandler (https://vertx.io/docs/apidocs/io/vertx/ext/web/handler/LoggerHandler.html) and we see that the time reported by it for the health URL is 0-2 msec. But when we run the test using jmeter, we see that it is taking much longer for end to end processing. We are running the application in docker container with 1 core CPU and 4 GB of RAM.

I am **suspecting** it is due to handshake taking time as the LoggerHandler is the last in the chain before the response is written out.

How can we move the SSL handshake to a different executor or dedicated eventloop for SSL handshake so that other eventloops doesn't participate in SSL handshake ?

If needed I can share a reproducer with jmeter job.

**Comment by himanshumps** [comment]
Attached is the jmx file that can be run and opened using the jmeter(greater than or equal to 4.0). It starts 100 thread at once calling the URL https://localhost:8443/. In the jmx file, the view results are disabled. You can enable them if you want to running the test in GUI mode.

[HTTP_Request.zip](https://github.com/eclipse-vertx/vert.x/files/3310111/HTTP_Request.zip)

The jmeter script can be invoked via command line (preferred) and it creates a report in the reports folder. 

`jmeter -n -t "HTTP_Request.jmx" -l test.jtl -e -o reports/`

Attached is the sample code that we used on docker container with 1 core CPU and 4 GB of RAM.

[vertxDocker.zip](https://github.com/eclipse-vertx/vert.x/files/3310246/vertxDocker.zip)


We are using unsigned certificates in test application but we are using signed certificates in case of real application.

This is the result from the jmeter report that is generated.
![jmeterResult](https://user-images.githubusercontent.com/22702284/59847681-cc0cd200-9380-11e9-92c1-d92c795cefed.png)

**Comment by vietj** [comment]
I don't think it is possible to achieve this, have you tried using tcnative SSL that provides a more CPU efficient SSL implementation ?

**Comment by himanshumps** [comment]
I did try that. I did modify the code to use tcnative and epoll with OpenSSL but I did not see much performance improvement. 
The code is very basic and can be tweaked to use OpenSSL and tcnative. 
Let me know if you want me to do that.

**Comment by himanshumps** [comment]
@vietj  Were you able to reproduce it at your end ?

**Comment by vietj** [comment]
I don't think it's possible to offload SSL to another thread

**Comment by vietj** [comment]
it's more a general Netty question. I netty can do it then we could use it in vertx

**Comment by vietj** [comment]
closing this for now as it does not seem to be possible
