### ISSUE TITLE
HttpClient doesn't handle 307 HTTP redirect

### ISSUE THREAD

**Issue by paulmfarrar** [eclipse-vertx/vert.x#3003]
I'm using Vert.x for HTTP POST/PUT client requests, some of which receive a 307 redirection response from the server. These requests fail to redirect as described in the RFC and the original POST/PUT payload is not cached for redirection. RFC description of the behaviour is here: https://tools.ietf.org/html/rfc7231#section-6.4.7.

I found the change made to the HttpClientRequestImpl class that specifically removes payload caching, https://github.com/eclipse-vertx/vert.x/pull/2305. The change appears to have been based on an outdated RFC and the 307 behaviour is quite different.

I will attempt to create a pull request for a possible fix and submit it. I believe that caching of the original payload body should be optionally defined by the user agent, caching all payloads could place a high resource load. 

I have attempted workarounds but at the moment I can't see a possibility of using the Vert.x build in redirectHandler method to proceed with 307 responses. Instead in my current dev project I plan to handle 307 responses manually by optionally caching the payload and making a brand new HTTP request.

**Comment by vietj** [comment]
you can set your own redirect handler on Vertx HttpClient : 

```
client.redirectHandler(response -> {

  // Only follow 301 code
  if (response.statusCode() == 301 && response.getHeader("Location") != null) {

    // Compute the redirect URI
    String absoluteURI = resolveURI(response.request().absoluteURI(), response.getHeader("Location"));

    // Create a new ready to use request that the client will use
    return Future.succeededFuture(client.getAbs(absoluteURI));
  }

  // We don't redirect
  return null;
});
```

explained in the doc https://vertx.io/docs/vertx-core/java/

**Comment by paulmfarrar** [comment]
Yes, I have used the ability to set my own redirect handler. The problem is that when the redirected request is a PUT or POST the original request data isn't available to send on in the redirection. Even having cached the data myself there isn't a way to write the cached data to the new request in the redirect handler as there is no handler assigned to the request.

In the "30x redirection handling" section of the Vertx Java documentation it says "on a 307 status code, follow the redirection with the same HTTP method and the cached body" - from my tests I find that this doesn't work. The caching was removed in https://github.com/eclipse-vertx/vert.x/pull/2305.

I'll try to put a test together to demonstrate the issue but I need to finish my workaround first.

**Comment by vietj** [comment]
@paulmfarrar yes I see what you mean, the documentation should be updated and this is the kind of redirection you should handle yourself because it is not good to cache such buffers and if you do it yourself then you can provide again the source of data

**Comment by paulmfarrar** [comment]
@vietj yes thanks the documentation seems to be misleading. When trying to handle the redirection myself I found it hard to write the cached data to the HttpClientRequest that is returned from my redirect handler. Do you have any tips on how I can do it?

I tried to write the cached data to the request in the redirect handler but because there is no handler assigned to the request yet it throws an exception. 

When the request is returned from the redirect handler it flows back into the Vertx code and I can't inject my cached data anywhere. I tried to create a delegate HttpClientRequest and return that with data injected but the `io.vertx.core.http.impl.HttpClientRequestImpl#doHandleResponse` method casts the request from the redirectHandler call to be a `HttpClientRequestImpl`. I then tried to subclass `HttpClientRequestImpl` but it doesn't have a public constructor so I couldn't.

If you have any guidance on how to inject cached data into the HttpClientRequest returned from the redirectHandler() call I'd be grateful.

**Comment by vietj** [comment]
that's a good point @paulmfarrar indeed the redirect handler should return a request that is not yet in progress. One possibility is to do like you said but the cast make it impossible to work, so I will try to see if the current implementation can work with only `HttpClientRequest` and if that works we can have it in 3.8 release

**Comment by vietj** [comment]
See https://github.com/eclipse-vertx/vert.x/issues/3024 I haven't added any specific test however you can try with 3.8 branch and report
