### ISSUE TITLE
MessageProducer.close throws NullPointerException

### ISSUE THREAD

**Issue by anatec-deryck** [eclipse-vertx/vert.x#3007]
The implementation of MessageProducer.close() calls `close(null)`, which results in a NullPointerException trying to call the handler.

This simple example demonstrates the problem:

`Vertx vertx = Vertx.vertx();`
`MessageProducer<Object> publisher = vertx.eventBus().publisher("endpoint");`
`publisher.close();`

Also, since `end()` also just calls `close()`, it also throws a NullPointerException.

**Comment by anatec-deryck** [comment]
Ok, I just compared the master branch with the 3.7, and it looks like the problem with close() has been addressed, as it no longer just calls close(null).

However, end() still directly calls close(null), so still has the problem.

**Comment by anatec-deryck** [comment]
Also, just had NPE thrown from the `MessageProducerImpl.finalize()` method as it also calls `close()` in v3.7.1.

**Comment by vietj** [comment]
this is actually fixed in 3.8 as you said, I will add specific tests for this though
