### ISSUE TITLE
Jackson mapper instances are public and should be not exposed

### ISSUE THREAD

**Issue by jmcgill-public** [eclipse-vertx/vert.x#3013]
`io.vertx.core.json.Json#mapper `and` io.vertx.core.json.Json#prettyMapper` are public and static. 
In the runtime environment any code that has access to the Json class can manipulate the mapper globally.

**Comment by vietj** [comment]
yes this will be made private in Vert.x 4 and deprecated in 3.x - see https://github.com/vert-x3/wiki/wiki/RFC:JSON-improvements

**Comment by vietj** [comment]
just renamed this issue so it better describe the actual issue

**Comment by javenwang** [comment]
How do we register Jackson modules without mappers?
https://github.com/FasterXML/jackson-module-kotlin/blob/master/README.md#usage

**Comment by vietj** [comment]
for 3.x this is what you should use

**Comment by javenwang** [comment]
We couldn’t register Jackson modules if mappers become private in 4.x, is that right?

**Comment by vietj** [comment]
I think we would provide a way to register them but not on the JSON class itself, rather to the specific Jackson databinding class

**Comment by vietj** [comment]
the JSON class will not be able to contain classes from jackson-databinding class

**Comment by doctorpangloss** [comment]
Having access to the mapper is actually really nice, because it's so straightforward and clear.

**Comment by vietj** [comment]
@doctorpangloss it will remain accessible but not on the JSON class itself, rather to a specific data-binding class, the idea in vertx 4 is that it runs without jackson-databind on the classpath and most JSON operations work

**Comment by cpdyj** [comment]
Ah... Now is there anyway to register module for jackson?

**Comment by vietj** [comment]
in 3.x you should use the public instance for now and later we will provide something for it when the current rework of jackson integration is achieved in master

**Comment by vietj** [comment]
done already.
