### ISSUE TITLE
WorkerContext.wrapTask() bug?

### ISSUE THREAD

**Issue by 618lf** [eclipse-vertx/vert.x#3027]
final <T> Runnable wrapTask(T arg, Handler<T> hTask, PoolMetrics metrics) {
    Object metric = metrics != null ? metrics.submitted() : null;
    return () -> {
      if (metrics != null) {
        metrics.begin(metric);
      }
      boolean succeeded = executeTask(arg, hTask);
      if (metrics != null) {
        metrics.end(metric, succeeded);
      }
    };
  }

metrics.begin(metric)  return usage.time() but it do not stop.

**Comment by 618lf** [comment]
I use vertx-dropwizard-metrics in vertx 3.7.1. The metrics is PoolMetricsImpl.

**Comment by vietj** [comment]
right this seems like a bug

**Comment by vietj** [comment]
see https://github.com/eclipse-vertx/vert.x/issues/3031
