### ISSUE TITLE
[Worker pool - ExecuteBlocking] Queing delay too high

### ISSUE THREAD

**Issue by MeYoGui** [eclipse-vertx/vert.x#3028]
Hello,

During some load testing on our architecture based on VertX I found some issues concerning the use of ExecuteBlocking. I don't know yet if it comes from our way of doing or if something weird is going on.

**1. Context**

We are calling an endpoint that is in charge of execute some I/O (a rest call to a third party). For that we are executing that I/O in a executeBlocking() method (using vertx.executeBlocking() with ordered = false).
_Unfortunately, we can't use the Vertx webclient for that purpose_

**2. Configuration**

We are using **4 event loops** (fix to 4 as we have only 2 CPU on our hardware) and a **worker pool size of 100** using 4 verticles.
The I/O blocking process is executed in a average of **200ms**.
The load test is using JMeter (on the same local machine) using 1000 threads that will call this specific endpoint (using HTTP).

For the **verticle deployment** we are using a specific Verticle that is in charge of deploying the "business verticles" based on configuration via  vertx.deployVerticle. The business verticle to deploy is configured that way :
* worker : false
* workerpoolName : myWorkerPoolName (I changed that name for this issue :))
* workerPoolSize : 100
* instances : 4

**3. Where is the potential problem ?**

The average response time of the call is around 2 seconds. 
The delay is caused by the time to send the blocking task to the worker pool.

Here are some metrics about this specific worker pool (exposed by DropWizard) :
vertx_pools_worker_xxx_worker_pool_queue_delay{quantile="0.5",} **1.752741364**
vertx_pools_worker_xxx_worker_pool_queue_delay{quantile="0.75",} **1.816608618**
vertx_pools_worker_xxx_worker_pool_queue_delay{quantile="0.95",} **2.275382375**
vertx_pools_worker_xxx_worker_pool_queue_delay{quantile="0.98",} **2.3868914240000003**
vertx_pools_worker_xxx_worker_pool_queue_delay{quantile="0.99",} **2.4479487690000004**
vertx_pools_worker_xxx_worker_pool_queue_delay{quantile="0.999",} **2.510801675**
vertx_pools_worker_xxx_worker_pool_queue_delay_count 80628.0

As we can see in the metrics most of the queue_delay is around 2 seconds.

Here is a snapshot (from JVisualVM of the worker pool during the load test) :
![image](https://user-images.githubusercontent.com/4062869/61062626-8e71f680-a3cc-11e9-836e-dbddb9876edf.png)

As we can see the worker pool is busy but it seems that some threads are waiting sometimes (indicating that he seems not "over charged"). (we've tried adding more threads in the pool but it didn't change anything, more threads were waiting, that's all).

The event loops are not blocked (we don't have any warnings, and we've set the warning to 100ms).

We've set timers to correlate data for the queuing delay and we've noticed the same numbers (2 seconds delay for a process to be executed).

Here is a trace (from Jaeger) displaying the duration for one specific call during load testing : 
![image](https://user-images.githubusercontent.com/4062869/61063300-bc0b6f80-a3cd-11e9-9bad-d68f47fdda35.png)

We can see that the process inside the execute blocking is taking around 200ms but before that the process was doing nothing but waiting to be processed.

**Questions :** 
* Do we have missed a configuration ? 
* Is there something we're doing wrong ?
* How can we explain that delay ?
* Can we avoid the queuing delay in some way ?

**Notes**
* This kind of contention is not happening with lower concurrency (like 100 threads)
* We've tried to have one worker pool per verticle (so 4 worker pool) to avoid potential contention but it didn't change anything at first sight.
* We can't have more than 2 CPU on our hardware
* We are using Vertx 3.7.1

Thank you and don't hesitate to ask me anything that can help you investigate this.

**Comment by vietj** [comment]
so in short you are reporting that vertx is under using worker executor pools ?

**Comment by vietj** [comment]
can you share a reproducer ?

**Comment by MeYoGui** [comment]
Actually, I did try with another profiler as it was kind of weird to see all that "waitings". (used JProfiler instead). 
**Results** : threads are not waiting, they are in I/O (most of the time) and are just waiting less than 1% of the time.

The problem here is maybe just as simple as : the queuing is occurring because we are processing a lot in the worker pool and it starts to delayed processing as too many request are coming from the load test.

I will just close this as I don't see any problem with Vertx core anymore on that.

**Comment by vietj** [comment]
thanks for reporting, blocking can indeed create queuing in the application and you need to see it as a resource for scalability
