### ISSUE TITLE
Javadoc for Filesystem.mkdirs incorrect

### ISSUE THREAD

**Issue by philippguertler** [eclipse-vertx/vert.x#3029]
Javadoc says that the operation will fail when the directory already exists.
https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/file/FileSystem.java#L486

This is incorrect. Internally Files.createDirectories is used, which does not fail when the directory already exists.

**Comment by vietj** [comment]
I've done a quick check and it fails for me, do you have a reproducer ?

**Comment by philippguertler** [comment]
Sure: https://github.com/philippguertler/vertx-3029-repro
This should throw an error but instead `Done!` is printed out.

**Comment by philippguertler** [comment]
Btw I like the current functionality more. I'd like it more if the javadoc was changed.

**Comment by vietj** [comment]
actually you seem right

**Comment by vietj** [comment]
mkdir and mkdirs don't behave the same

**Comment by vietj** [comment]
under the hood all this uses the java API that behave differently createDirectory/createDirectories

**Comment by vietj** [comment]
I'll update doc accordingly

**Comment by philippguertler** [comment]
Thanks!

**Comment by vietj** [comment]
see https://github.com/eclipse-vertx/vert.x/issues/3030
