### ISSUE TITLE
The main class io.vertx.core.Launcher could not be found or loaded

### ISSUE THREAD

**Issue by crazyliuzc** [eclipse-vertx/vert.x#3034]
Vertx version=3.7.1

When I use cmd.exe to enter the command "vertx version", the console outputs 3.7.1,
but when I use git bash.exe to enter the same command, the console error 
"The main class io.vertx.core.Launcher could not be found or loaded"

**Comment by tsegismont** [comment]
Have you tried `./vertx.bat version`? Git Bash for Windows shouldn't be used for anything else than git and basic file manipulation.
