### ISSUE TITLE
Add new static method to create Future<T> objects that is compatible with "var" declarations

### ISSUE THREAD

**Issue by anatec-deryck** [eclipse-vertx/vert.x#3037]
At the moment, the only way to create a typed `Future<T>` is to have an explicitly-typed declaration of the variable, namely:
```
Future<Void> myFuture = Future.future();
```
If you attempt to use the Java 10 `var` keyword, the result is a value of type `Future<Object>`.

It would therefore be useful to add a new static method to `Future` (or `Promise` in 3.8), similar to the following:
```
static <T> Future<T> future(Class<T> clazz) {
    Future<T> future = factory.future();
    return future;
}
```
Using this new method allows for the following code, where the inferred type is now `Future<Void>`:
```
var myFuture = Future.future(Void.class);
```
The impact of this change seems minimal, given that it is really just a compile-time type checking fix.

Regards,
Deryck Brown

**Comment by doctorpangloss** [comment]
p.s. instead of `clazz` the arg for what this is doing is usually called `witness`.

Additionally you may consider

`var future = Future.<Void>future()`.

**Comment by vietj** [comment]
agreed with @doctorpangloss this is a defect of Java language and we should not use an artificial argument instead.

**Comment by vietj** [comment]
also with Vert.x 4, this has less sense since the API will return Futures in the places an handler is required in 3.
