### ISSUE TITLE
HttpClient doesn't handle 308 redirect

### ISSUE THREAD

**Issue by steve-scx** [eclipse-vertx/vert.x#3038]
Is there a reason?

Seems like it's supposed to be handled like a 301.

**Comment by vietj** [comment]
currently I think it is not handled because it requires to use POST if the original method was POST which means the client must buffer the entire request body.

**Comment by vietj** [comment]
I think we should add this in the documentation of the HttpClient.

**Comment by oddio** [comment]
What about making it handle 308 GET requests properly, and only leaving the problematic POST requests unsupported out-of-the-box?

**Comment by vietj** [comment]
that's also feasible I think as long as it's clearly documented.

do you mind contributing this ?

**Comment by oddio** [comment]
Thanks @shenzhou-6!

**Comment by vietj** [comment]
thanks for the contribution
