### ISSUE TITLE
Is it okay to share the Vert.X EventLoop with the AWS SDK?

### ISSUE THREAD

**Issue by miere** [eclipse-vertx/vert.x#3045]
Hi guys.

I've been recently migrating one service from Undertow to Vert.x and the experience so far have been great. We make massive usage of AWS SDK 2 and as both uses Netty under the hood, and Netty event loop can handle hundreds of millions of requests, I was wondering if is it okay to share Vert.x's Netty EventLoop with AWS SDK 2's `NettyNioHttpAsyncClient`?

Below you can find a copy of what we did on your configuration.
```kotlin
val awsRegion = Region.of( env("AWS_REGION", "us-east-1") )
val credentialsProvider = DefaultCredentialsProvider.create()
val nettyHttpClient = NettyNioAsyncHttpClient.builder()
    .eventLoopGroup(SdkEventLoopGroup.create(vertx.nettyEventLoopGroup()))
        .build()
```

I guess worth mention that `nettyHttpClient` will also be shared by all of our AWS clients.
```kotlin
    @Producer
    fun kinesisClient() = KinesisAsyncClient.builder()
        .httpClient(nettyHttpClient)
        .credentialsProvider(credentialsProvider)
        .region(awsRegion)
            .build()!!

    @Producer
    fun dynamoDbClient() = DynamoDbAsyncClient.builder()
        .httpClient(nettyHttpClient)
        .credentialsProvider(credentialsProvider)
            .build()!!
```

Here are versions we've been using on our Kotlin (on OpenJDK 11) project:
```yaml
properties:
  version.vertx: 3.8.0
  version.aws: 2.7.8
  version.netty: 4.1.34.Final
```

**Comment by vietj** [comment]
Yes it is fine you can look also at this project (still a WIP) to get inspiration https://github.com/reactiverse/aws-sdk . Also you can read this guide about Netty resources https://github.com/vietj/advanced-vertx-guide

**Comment by vietj** [comment]
thanks for your feedback

**Comment by miere** [comment]
Thanks, mate. I'll look into that.
