### ISSUE TITLE
Documentation promotes use of deprecated method getNow

### ISSUE THREAD

**Issue by VictorQRS** [eclipse-vertx/vert.x#3055]
The core documentation on [how to make requests](https://vertx.io/docs/vertx-core/java/#_making_requests) says to use xxxNow to make request from a client, but those methods are deprecated, e.g., [getNow](https://vertx.io/docs/apidocs/io/vertx/core/http/HttpClient.html#getNow-io.vertx.core.http.RequestOptions-io.vertx.core.Handler-).

**Comment by vietj** [comment]
yes you should use the WebClient, perhaps we should change the deprecated text to specify that people can use `WebClient` (which is the current deprecated text) or continue to use this but it would break in Vert.x 4

**Comment by VictorQRS** [comment]
@vietj Should I make a PR to fix it?

**Comment by vietj** [comment]
that would be very nice @VictorQRS
