### ISSUE TITLE
Future.future(Handler<Promise<T>> handler) not handle exception.

### ISSUE THREAD

**Issue by cpdyj** [eclipse-vertx/vert.x#3056]
I see that issue #1568.
Why don't make the Future fail when the handler throws an Exception?
Should I create a pr resolve that?
Code: [Here!](https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/Future.java#L37)

Expanded, should I make all `Future` auto fail when `Future.handler` throws an `Exception` ?
Thank you.

**Comment by vietj** [comment]
that would be a behavior similar to what we do have in `executeBlocking` so +1 for this behavior. You are welcome to do a PR that we can review.

**Comment by cpdyj** [comment]
Oh, no. I think I fall in wrong. The handler can't handle exception. But I can make `Future.future` auto fail when it throws an Exception.
:)

**Comment by vietj** [comment]
I mean that when the handler passed to Future.future thrown an exception then it returns a failed future

**Comment by cpdyj** [comment]
Ok, I commit a pull request. 
Thanks for review.
