### ISSUE TITLE
HttpServer#close does not disconnect established connections

### ISSUE THREAD

**Issue by Jotschi** [eclipse-vertx/vert.x#3058]
I have just upgraded Gentics Mesh from Vert.x 3.7.1 to 3.8.0 and only a single test in our testsuite is failing. The test simulates a server crash by first establishing a websocket connection and stopping the used HttpServer. Previously an error was thrown since the connection was severed. The client would now reconnect. This is no longer the case. With Vert.x 3.8.0 the connection is not severed and I can see in Wireshark that the continuously send text frames are accepted with an ACK.

I use `HttpServer#close` with an handler so I'm sure the server should be stopped. The failure handler is not invoked.

```
@Override
public void stop(Promise<Void> promise) throws Exception {
	server.close(rh -> {
		if (rh.failed()) {
			promise.fail(rh.cause());
		} else {
			promise.complete();
		}
	});
}
```

I can try to create a reproducer if needed.

**Comment by vietj** [comment]
a reproducer would be great, thanks

**Comment by Jotschi** [comment]
I was not able to reproduce the issue with just Vert.x Core - I'll investigate further. Maybe it is an issue in my application. I'll reopen the issue if I find an issue in Vert.x.

**Comment by vietj** [comment]
@Jotschi thanks keep us informed
