### ISSUE TITLE
Consider Netty upgrade to resolve security vulnerability in HTTP/2

### ISSUE THREAD

**Issue by bripkens** [eclipse-vertx/vert.x#3068]
For details of vulnerability see the following disclosure:
https://www.kb.cert.org/vuls/id/605641/

Netty is already released fixes as `4.1.39.Final`. See:
https://netty.io/news/2019/08/13/4-1-39-Final.html

AFAIK vertx-core needs to be updated in order to update vertx-web, right?

**Comment by pmlopes** [comment]
Release 3.8.1 fixed the issue.
