### ISSUE TITLE
run command should honour "-options"

### ISSUE THREAD

**Issue by pradeepsixer** [eclipse-vertx/vert.x#3069]
Vertx core manual for Java [shows that run command takes in](https://vertx.io/docs/vertx-core/java/#_run_verticles) `-options` CLI option. However, if I were to provide that by running a jar, it does not consider the path to json file passed in as CLI option.

Example,
`java -jar app.jar --options <vertx_options.json>` runs with default VertxOptions rather than the options set within vertx_options.json

Also, neither `RunCommand` and `BaseCommand` has `-options` CLI option listed within them. It would be really helpful to honour the option, instead of having to specify everything as system properties prefixed with `-Dvertx.options.`

**Comment by pradeepsixer** [comment]
I can try creating a PR for this, if adding this makes sense.

**Comment by tsegismont** [comment]
@pradeepsixer can you provide a reproducer? There is [a test](https://github.com/eclipse-vertx/vert.x/blob/48e46021c93859134bcd1e316f65f940f6aa7186/src/test/java/io/vertx/core/LauncherTest.java#L486) for `-options` and I personally used `-options` with success in a project recently.

**Comment by pmlopes** [comment]
Another example where it works is here: https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/es4x/es4x.dockerfile#L26

Note that it uses `--options` double dash

**Comment by pradeepsixer** [comment]
Was using an older version of Vert.x (3.5.4), and looks like that did not support the `options`. Sorry about the confusion.

**Comment by tsegismont** [comment]
@pradeepsixer thanks for letting us know
