### ISSUE TITLE
Recovering From Failure Faster?

### ISSUE THREAD

**Issue by micah-williamson** [eclipse-vertx/vert.x#3071]
I am using the WebClient with Vert.x 3.7.1 to send around 2mm requests in batches of 5k spread over several nodes (backed by a queue). I am finding in most cases it takes only 1-2 seconds to send each batch, but occasionally I am receiving a "Stream reset: 2" message, which causes the entire batch to take over 60s to complete.

Out of 2mm sends, I only received this message 250 times, and I am ok with dropping those requests entirely. The issue is the time it takes to recover from a stream reset.

Is it possible to have requests fail faster, or to recover from STREAM_RST quicker?

Thank you.

**Comment by vietj** [comment]
it seems weird that it takes 60 seconds which is the default client HTTP/2 keep alive timeout value.

can you provide a reproducer case ?

**Comment by iamchairs** [comment]
I have been trying to all morning. It's unfortunately only happened in production and I can't replicate it in a dev or local environment. It does seem coincidental that it's 60s, in fact they all seems to timeout around 60s, but i wasn't sure what configuration that would be. Most requests happen within a second, so i'm wondering if i'm safe reducing that keepalive to 10s or lower.

Still working on creating a reproducible example.

**Comment by vietj** [comment]
can you try change the timeout to see if there is a correlation ?

when an HTTP/2 connection receives a stream reset for one of its streams that should not affect the connection and other stream should continue working fine.

**Comment by vietj** [comment]
after thinking about your case, I think you can set handlers on the HttpConnection interface, in particular I would be interested by

- goAwayHandler : the connection might have received a go away frame but is not removed from the pool
- removeSettingsHandler : the server might have sent a new settings with a `0` concurrency to protect itself
