### ISSUE TITLE
NPE when undeploying several instances of the same verticle that share the same isolationGroup

### ISSUE THREAD

**Issue by HugoCrd** [eclipse-vertx/vert.x#3074]
Hi Vert.x folks!

Vert.x 3.8.0 fails undeploying verticles when more than 1 instance were deployed with `VertxMavenFactory`.
This is because these instances share the same `isolationGroup`.
The issue seems to have been introduced in this commit: https://github.com/eclipse-vertx/vert.x/commit/38111ed7f6edc185e8d8677bbfceb000d7a9b8e4
A NPE is thrown from here: https://github.com/eclipse-vertx/vert.x/blob/740804cdd985145c68a852671ae8a709c2039970/src/main/java/io/vertx/core/impl/DeploymentManager.java#L713

In the code above, icl is `null` after been cleaned when undeploying the first instance.

Here is a reproducer:
https://github.com/Melusyn/vertx-maven-factory-classloader-bug/

I first described this here: https://groups.google.com/forum/#!topic/vertx/TAD99dtEU10

Thanks a lot for having a look at it :)
Best!
Hugo

**Comment by vietj** [comment]
thanks!
