### ISSUE TITLE
http response endHandler not called on request with `connection: close`

### ISSUE THREAD

**Issue by steven-aerts** [eclipse-vertx/vert.x#3077]
After upstepping from vert.x version 3.6.2 to 3.7.1 we noticed that the endHandler for http 1.1 responses is not called anymore when the client asks for the connection to be closed with a `connection: close` header.

We can reproduce the issue with the following test in `io.vertx.core.http.HttpTest`:
```java
  @Test
  public void testResponseEndHandlersConnectionClose() {
    waitFor(2);
    server.requestHandler(req -> {
      req.response().endHandler(v -> complete());
      req.response().end();
    }).listen(onSuccess(server ->
      client.request(HttpMethod.GET, DEFAULT_HTTP_PORT, DEFAULT_HTTP_HOST, "/", onSuccess(res -> {
        assertEquals(200, res.statusCode());
        complete();
      }))
      .putHeader(HttpHeaders.CONNECTION, "close")
      .end()));
    await();
  }
```

A `git bisect` points to 645f6d4 by @vietj.
As this is a rather big change it is unclear to us where it is introduced exactly.

**Comment by vietj** [comment]
it looks like a regression for a case that was not tested
