### ISSUE TITLE
Proper handling of host names ending with a dot in client connections

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#3080]
Currently `NetClient` and `HttpClient` don't properly handle host names ending with a dot.

TLS peer host should be the un-dotted version instead of the provided name otherwise it results in unexpected handshake failures.

The hosts based resolution should use the un-dotted version when doing a lookup in the list to resolve correctly the name.

**Comment by ctron** [comment]
I think the change in 27c3a13 breaks the DNS resolution. A dot in the end is a valid thing, as it specifies that the hostname is "fully qualified". So there is a difference between `foo.com` and `foo.com.`. Stripping away the final dot will break using a fully qualified name and lead to wrong DNS resolutions.

The trailing dot must only be removed for the SNI verification.

**Comment by vietj** [comment]
@ctron the `peerAddress` is only used for SSL, the `remoteAddress` is kept as is

**Comment by vietj** [comment]
actually you are right it might fail for HTTP but not for TCP client

**Comment by vietj** [comment]
I commented on the PR about the changes and how it does not affect DNS resolution.
