### ISSUE TITLE
Support mapping in ReadStream

### ISSUE THREAD

**Issue by indiketa** [eclipse-vertx/vert.x#3081]
It would be very useful to provide a mapping method in ReadStreams (like `pipeTo`).

Idea and use case:
```
ReadStream<String> rs;
ReadStream<Integer> rs.map(Integer::parseInt);
```
Signatures:
```
interface ReadStream <T> {
  <T2> ReadStream<T2> map(Function<T, T2> transformation);
  <T2> ReadStream<T2> map(Function<T, Future<T2>> transformation);
}
```

I think it could be implemented by default as a simple delegation in ReadStream (like pipe*).

**Comment by vietj** [comment]
I would prefer to have this outside Vert.x Core for several reasons:

- if we start to have `map` operation, then people will complain and ask to implement `flatMap` (map is trivial, flatMap is not) etc...
- we do have vertx-rx that is great for such use cases

**Comment by indiketa** [comment]
- Totally agree implementing `flatMap` is not trivial and could lead to potential `Future<Headache>`
- I think Vert-rx is _great_ but with some considerations: some libs are not fully rxfied: dealing with  `io.vertx.core.Vertx` and `io.vertx.rxjava.core.Vertx` is a bit harsh sometimes.

We will continue using a class to do this kind of integration:

`new MappedReadStream<>(retriever.configStream(), Configuration::toProperties);`

Thank you vietj!

**Comment by tsegismont** [comment]
@indiketa I had started a side project and took some time to share on GitHub: https://github.com/tsegismont/streamutils

For now you have to build it yourself but if there is some interest if could propose it to the [Reactiverse](https://reactiverse.io/).

I would appreciate your feedback.
