### ISSUE TITLE
Vert.x 4.0 ClusteredEventBus support HTTP/HTTP2

### ISSUE THREAD

**Issue by leotu** [eclipse-vertx/vert.x#3084]
Version 3.X only support transport in socket  (ConnectionHolder/NetSocket).
If it would also provide HTTP/HTTP2 as it transportation or have a mechanism (i.e, abstract/interface class) let us to write our own implementation.

Leverage  HTTP/HTTP2 work better in K8S or Proxy/Gateway integrated well.

**Comment by vietj** [comment]
@leotu that's something we could have as SPI indeed

**Comment by tsegismont** [comment]
@leotu can you elaborate on why HTTP/2 transportation would be better than raw TCP on K8S?

**Comment by leotu** [comment]
Currently ClusteredEventBus holds address's IP and send/received message by raw TCP is sticky one server when it connected, and it's load-balance just simple round robin mode.

If we can use K8S Istio sidecar Envoy(https://www.envoyproxy.io/) POD's ip as ClusteredEventBus hold IP, the LB strategy delegate to Istio. The message sent using HTTP/HTTP2 the failed-over and load-balance would be simply. Raw TCP socket connection is not easy to do LB when each message sending or failed over to another server.

**Comment by tsegismont** [comment]
@leotux we have looked into Istio integration already and came to conclusion it would be more problems than solutions. For example, there are a few use cases that we couldn't support (publish/subscribe, reply after reply).

In Vert.x 4.x we have have planned to make [revisit the clustering SPI](https://github.com/vert-x3/wiki/wiki/Vert.x-Roadmap#clustering-40). You then should be able to plug your own logic for node selection.

**Comment by leotu** [comment]
Great!  4.X should resolve: Blue-green deployment, A/B testing and Canary release.

**Comment by tsegismont** [comment]
No, it won't give you a solution for these problems out-of-the-box. But it
should pluggable enough to let you implement it.
