### ISSUE TITLE
hight response time for the first web request received after the server has no work load for a while

### ISSUE THREAD

**Issue by hunter686** [eclipse-vertx/vert.x#3085]
We working on a project using vert.x 3.8 and openapi3 contract and we have noticed that our server vert.x takes long time to answer a web request if the server has not received http requests for a while.

Do we have some option in vert.x to help us to make vert.x answer faster if the server has not received requests for a while

**Comment by vietj** [comment]
can you investigate what is the root cause of this ?

**Comment by hunter686** [comment]
> can you investigate what is the root cause of this ?
@vietj 
In fact, this is the question I would like to ask. I want to know if vert.x generate some sort of cache in jvm when it begins to handle http requests, which can explain that it takes long time to handle the first http requests.

**Comment by vietj** [comment]
there is no such thing

**Comment by hunter686** [comment]
@vietj 
I have made some more tests and it seems that I have a DNS issue.  I use insommia to test request and I see 
`Connection 47 seems to be dead!
 Closing connection 47
  Trying {{IP_OF_MY_SERVER}}...
 TCP_NODELAY set`

Here is the snippet for creation of my server 
`vertx.createHttpServer(httpServerOptions)
                          .requestHandler(mRouter)
                          .listen(httpConfig.getInteger("port", 8080), httpConfig.getString("host","localhost"), ar -> {
                            if (ar.succeeded()) {
                              LOGGER.info(String.format("Server started - port: %d host : %s - config : %s", httpConfig.getInteger("port", 8080), httpConfig.getString("host", "localhost"), mConfig.getString("api.name", "unknown")));
                              future.complete();
                            } else {
                              Throwable exception = ar.cause();
                              LOGGER.error("Error : Server not started : ", exception);
                              future.fail(exception);
                            }
                          })
                );`

I have also tried to create server without host
`vertx.createHttpServer(httpServerOptions)
                          .requestHandler(mRouter)
                          .listen(httpConfig.getInteger("port", 8080), ar -> {
                            if (ar.succeeded()) {
                              LOGGER.info(String.format("Server started - port: %d host : %s - config : %s", httpConfig.getInteger("port", 8080), httpConfig.getString("host", "localhost"), mConfig.getString("api.name", "unknown")));
                              future.complete();
                            } else {
                              Throwable exception = ar.cause();
                              LOGGER.error("Error : Server not started : ", exception);
                              future.fail(exception);
                            }
                          })
                );`
