### ISSUE TITLE
Unable to create new native thread

### ISSUE THREAD

**Issue by jkjunior** [eclipse-vertx/vert.x#3086]
I'm trying to manage 10k connections with a 100ms blocking code in a worker verticle. 

Then I'm trying to create a worker pool with 10k size but It can't create 10k native threads.

Am I missing something? Am I doing it wrong? Is it possible to switch from worker verticle to Akka's Actors?

Thanks to advance

**Comment by ZuiSong** [comment]
You can't create 10k native threads.This is determined by OS .
With 100ms blocking code,  how about change it to non blocking  ?
By the way, in  blocking code case, you can never manage 10k  active connections

**Comment by vietj** [comment]
do your 10k connections needs to execute the 100ms blocking tasks simultaneously ?

you should consider using the `EventBus` with worker verticles to achieve this with a reasonable number of worker instances and worker pool size.

This might create latency on your HTTP requests depending on how many of these 10k connections needs to use workers concurrently.

You can reduce latency creating a cluster with Vert.x and deploying extra worker instances on the cluster. Your 10K connections will then load balance their tasks on the cluster giving you the scalability you might need.

**Comment by jkjunior** [comment]
I'm using a 100ms blocking code to simulate a long lived HBase (Big Data) operation and waiting for a result, since we have this avarage operation time.

@vietj Are you saying to create a cluster of worker poll?

I tried to replace the workes, using the Vert.x Sync instead. I got a better result, but when i tried to use Fibers itself (without Vert.x) I got better performance.
