### ISSUE TITLE
immutable Json in Vertx

### ISSUE THREAD

**Issue by imrafaelmerino** [eclipse-vertx/vert.x#3087]
For future releases, it could be great to be able to work with an immutable Json in Vertx, with a more declarative and functional API than the current. I think that performance would improve because no defensive copy of a Json would be needed before sending a message to the bus.
I propose to consider [json-values](https://github.com/imrafaelmerino/json-values) as an alternative to the current Json object.

**Comment by vietj** [comment]
by curiosity have you benchmarked Vert.x's JsonObject against json-values for different use cases ?

**Comment by imrafaelmerino** [comment]
I've only carried out a benchmark using Json objects of different sizes so far, but I'm going to keep working on this, and I'll keep the [project doc](https://imrafaelmerino.github.io/json-values/#performance) updated. Both mutable and immutable implementations can use different underlying data structures. Find below some results using Java HashMap and ArrayList and collections from Eclipse Collections for the mutable implementation. The immutable implementation uses persistent data structures from Scala, but again, it could be any other persistent data structure. It's on my to-do list to perform the same benchmark in terms of foot-print.
Any feedback would be really appreciated.

```
Benchmark                                                           Mode   Samples    Mean          Mean error    Units
parse_string_jackson_obj_10000                                      avgt     10    1356624.227      442088.003    ns/op
parse_string_jsonvalues_mutable_eclipse_collections_obj_10000       avgt     10    2212575.403     1160516.788    ns/op
parse_string_jsonvalues_mutable_obj_10000                           avgt     10    1295379.624       67240.388    ns/op
parse_string_jsonvalues_immutable_obj_10000                         avgt     10    4047304.291      936095.812    ns/

parse_string_jackson_obj_100000                                     avgt     10   35630406.739    23015218.199    ns/op
parse_string_jsonvalues_mutable_eclipse_collections_obj_100000      avgt     10   10999830.101      544504.730    ns/op
parse_string_json_values_mutable_obj_100000                         avgt     10   15452070.507     1523005.400    ns/op
parse_string_jsonvalues_immutable_obj_100000                        avgt     10   45034250.352    11901240.411    ns/op


parse_string_jackson_obj_1000000                                    avgt     10   319011320.738    176763458.970   ns/op
parse_string_jsonvalues_mutable_eclipse_collections_obj_1000000     avgt     10   166773500.095    28255130.625    ns/op
parse_string_jsonvalues_mutable_obj_1000000                         avgt     10   414601294.875    216932693.384   ns/op
parse_string_jsonvalues_immutable_obj_1000000                       avgt     10   1320324870.750   734454321.103   ns/op
```

**Comment by vietj** [comment]
@imrafaelmerino how can it be used currently with Vert.x ? do you provide bridge for `JsonObject` and `JsonArray`
