### ISSUE TITLE
CompositeFuture.java, Future deprecation

### ISSUE THREAD

**Issue by rakotomandimby** [eclipse-vertx/vert.x#3094]
Hi all, 
In https://github.com/vert-x3/wiki/wiki/3.8.0-Deprecations-and-breaking-changes, Future are announced deprecated.

But [CompositeFuture.java](https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/CompositeFuture.java) still makes heavy use of Futures.

To be more precise, I'm am trying to use microservices based on https://github.com/cescoffier/vertx-microservices-examples and it involves [CompositeFuture](https://github.com/cescoffier/vertx-microservices-examples/blob/master/aggregation-http/A/src/main/java/io/vertx/microservices/A.java#L88)

**Comment by okou19900722** [comment]
You may have made a mistake. Future still exists, but it is no longer created with `Future.future()`, but instead created with `promise.future()`

the break change note that:

```
// Deprecated
Future<String> fut = Future.future();
vertx.setTimer(1000, id -> fut.complete("hello");
return fut;

// Now you should do this
Promise<String> promise = Promise.promise();
vertx.setTimer(1000, id -> promise.complete("hello");
return promise.future();
```
all this code return a Future

**Comment by rakotomandimby** [comment]
@okou19900722 , OK I got it.
