### ISSUE TITLE
Vertx Graphql Preview Status warning - is it not production ready yet?

### ISSUE THREAD

**Issue by techyrajeev** [eclipse-vertx/vert.x#3095]
<img width="876" alt="Screen Shot 2019-09-06 at 3 45 56 PM" src="https://user-images.githubusercontent.com/4118032/64420780-a52b8580-d0bd-11e9-98e7-aea795407a22.png">

I was thinking to use Graphql along with Vertx but then I saw above warning.

Vertx Graphql **Tech Preview Status** warning - when will it be stable or production ready?
Are there any major upgrade or drastically new api changes are coming?

**Comment by tsegismont** [comment]
Vert.x Web GraphQL is a "new" module in the Vert.x stack. New modules are always labelled tech preview for a few minor releases.

At this moment, there are no major upgrades nor drastically changes planned.
