### ISSUE TITLE
Want a way to custom usage of SniHandler

### ISSUE THREAD

**Issue by whitemay** [eclipse-vertx/vert.x#3097]
### Version

- vert.x core: 3.8.0
- vert.x web: 3.8.0

### Context

I noticed that SniHandler accept a param of type AsyncMapping in public constructor. Any way to use it in SNI duration to get key&certs asynchronously?

My idea is to pass an custom AsyncMapping object in NetServerOptions so pipeline can use it, as alternative to inner class AsyncMappingAdapter, which did nothing about async. This AsyncMapping.map() may return a Promise immediately and try to load key&certs asynchronously.

This AsyncMapping may co-work with the KeyCertOption, to make sure SSLHelper.map will get the key&certs for sni name. 

Or is there a way to change the channel pipeline from user code?

Sure this issue is related to let's encrypt certs, or likely usage.

**Comment by vietj** [comment]
You can provide your own `KeyCertOptions` implementation that would allow to do that by providing an `keyManagerMapper` which resolves any valid `X509KeyManager` for a given SNI name. This has been used by existing implementation to implement dynamic SNI mapping such as Let's Encrypt.

**Comment by whitemay** [comment]
@Override
        public Future<SslContext> map(String input, Promise<SslContext> promise) {
            final SslContext context;
            try {
                context = mapping.map(input);
            } catch (Throwable cause) {
                return promise.setFailure(cause);
            }
            return promise.setSuccess(context);
        }

**Comment by whitemay** [comment]
Below is code of AsyncMappingAdapter.

        @Override
        public Future<SslContext> map(String input, Promise<SslContext> promise) {
            final SslContext context;
            try {
                context = mapping.map(input);
            } catch (Throwable cause) {
                return promise.setFailure(cause);
            }
            return promise.setSuccess(context);
        }

The question is when KerCertOptions works, Caller will blocked. But loading cert dyanmiclly is a long run process.

**Comment by vietj** [comment]
I think in Vert.x 4 we could change the `KeyCertOptions` to be asynchronous instead of being synchronous:

```
  default BiFunction<String, Handler<AsyncResult< X509KeyManager >>> keyManagerMapper(Vertx vertx) throws Exception;
```
