### ISSUE TITLE
when sender  many msg before consumer register,after register consumer , send msg but bus dont work 

### ISSUE THREAD

**Issue by jr981008** [eclipse-vertx/vert.x#3103]
Vertx vertx = Vertx.vertx(new VertxOptions().setEventLoopPoolSize(2));

        MessageProducer<Object> s = vertx.eventBus().sender("a", new DeliveryOptions().setSendTimeout(1));
        for (int i = 0; i < 1000000; i++) {

            s.write("b");
        }
        System.out.println("done");
//        vertx.eventBus().send("a", "b");
        vertx.deployVerticle(x.class.getName(), r -> {

            s.write("b");
            s.write("b");
            s.write("b");
        });
        Thread.sleep(1000);
        System.out.println("done2");
        s.write("b");
        s.write("b");
        s.write("b");

public class x extends AbstractVerticle {
    @Override
    public void start() throws Exception {
        vertx.eventBus().consumer("a", r -> {
            System.out.println(r.body());
        });
    }
}

I hope systemout like   :
done 
done2 
b
b
b

but  is:
done
done2

**Comment by tsegismont** [comment]
@jr981008 the eventbus does not persist messages, you must deploy your consumer before you start sending.

**Comment by jr981008** [comment]
I still don't understand why when I send msg num  < bus  credit  ,after i deploy my consumer i can receive msg which sending after i deploy sonsumer  ,but when  this num >bus credit ,what puzzles me is that I don’t receive the message I sent after I deploy the consumer, not before.

**Comment by jr981008** [comment]
@tsegismont  thanks

**Comment by jr981008** [comment]
I still don't understand why when I send msg num < bus credit ,after i deploy my consumer i can receive msg which sending after i deploy sonsumer ,but when this num >bus credit ,what puzzles me is that I don’t receive the message I sent after I deploy the consumer, not before. I don't care msg send before i deploy consumer，

**Comment by tsegismont** [comment]
Can you post your question to the user forum? You are more likely to get some help from the community because not everyone subscribes to github issues.
