### ISSUE TITLE
HeadersEndHandler no longer include all headers

### ISSUE THREAD

**Issue by TorRanfelt** [eclipse-vertx/vert.x#3104]
In 3.6.3 it was possible to add a HeadersEndHandler that will work on the headers AFTER SessionHandler's set-cookie header has been added. This is needed to add SameSite=Lax and Max-Age to the header since the SessionHandler doesn't offer these attributes.

```
router.route().handler { ctx ->
ctx.addHeadersEndHandler {
                    ctx.response().headers().entries().stream()
                        .filter { header -> header.key == "set-cookie" && header.value.startsWith("$SESSION_COOKIE_NAME=") }.findAny()
                        .ifPresent { header ->
                            val sessionTimeoutInSeconds = SESSION_TIMEOUT / 1000
                            header.setValue("${header.value}; SameSite=Lax; Max-Age=$sessionTimeoutInSeconds")
                        }
}
}
router.route().handler(CookieHandler.create())
```

After 3.8.1 this doesn't work anymore because CookieHandler stopped being anything more than a next() call: https://github.com/vert-x3/wiki/wiki/3.8.1-Deprecations-and-breaking-changes

This can't be achieved by manipulating the cookie since custom attributes isn't an option.

In the end I hacked my way around it by making a ServerCookie wrapper:
```
private class Bar(private val foo: ServerCookie) : ServerCookie by foo {
    override fun encode(): String {
        return foo.encode() + "; SameSite=Lax"
    }
}
router.route().handler { ctx ->
            ctx.response().headersEndHandler {
                val foo = ctx.getCookie(SESSION_COOKIE_NAME) as ServerCookie
                ctx.removeCookie(SESSION_COOKIE_NAME)
                ctx.response().addCookie(Bar(foo))
            }
}
```

I would like to again have the option to view and change headers AFTER every handler has already chipped in; including the SessionHandler.

Ideally I would also like to be able to add custom attributes to cookies.

Ideally times two I would like to be able to add custom attributes to SessionHandler so I don't have to fish out any cookie or header.

**Comment by pmlopes** [comment]
Cookies are now handled by core so there's no way to do that on web anymore.

**Comment by TorRanfelt** [comment]
I get that by design this doesn't work anymore. But how do you think one should go about adding custom attributes like SameSite=Lax for session-cookie in vertx without making hacks?
As far as I can tell some new functionality is needed, and the three I can think of are the ones I listed.

1. Being able to change header after they have been added. - What you would expect from a routingcontext.addHeadersEndHandler().

2. Allow custom attributes for cookies.

3. Allow custom attributes for session-cookie in SessionHandler.

I actually think all three would be ideal.

**Comment by pmlopes** [comment]
The issue is that the cookie object comes from netty which doesn't support the attribute you're interested `SameSite`. Requests have been done upstream but they want only to support it on the next major release.

Now you could propose an vertx core fix stating why this is important and the corner cases needed to be addressed. For example I assume this would only be applicable to server cookies sent but not parses in.
