### ISSUE TITLE
Azure B2C requires a parameter for the ".well-known" discovery address

### ISSUE THREAD

**Issue by smil2k** [eclipse-vertx/vert.x#3106]
I'm using **AzureADAuth.discover** to load the JWKs array. 

Azure AD B2C requires the "profile" also as a query parameter like this:  
https://bla.b2clogin.com/bla.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_Simple

Unfortunately the configuration "site" 
will get appended with ".well-known/openid-configuration" unconditionally, therefore it is not possible to use OAuth2 discovery with Azure AD B2C. 

As a hack, I've added "&x=" to the end of the above line, this way the added suffix is handled as a parameter and the service returns the right profile. 

It would be good to either check for ".well-known" before appending the path or make it possible to append query parameters from the config.

**Comment by pmlopes** [comment]
Please move the issue to vertx auth.

**Comment by smil2k** [comment]
https://github.com/vert-x3/vertx-auth/issues/293
