### ISSUE TITLE
Attach a handler to HttpClientRequest without using a deprecated method ?

### ISSUE THREAD

**Issue by jbtrystram** [eclipse-vertx/vert.x#3115]
Hello ! 

I am setting up some test code using the HttpClient class. Here is what I came up with, following the documentation : 
```
            // httpClient is already configured with the host, port and other values. 

            httpClient.post(String.format("my/api/endpoint"))
                   .putHeader("Content-Type", " application/json")
                   .putHeader("Authorization", "Bearer"+token)
                   .end(res -> {
                        // handling the request
                       log.info("yay !")
                    });
```

However i got an exception saying that i did not attached a handler to my request.  I used `.Handler<HttpClientResponse> handler)` to work around it, but it is a deprecated method. 

What is the correct / recent way to do it ? 

Also, the vertx.core manual suggest using the deprecated method and I did not find an up to date example here. 

Thanks !

**Comment by vietj** [comment]
you can use the `WebClient` instead, you can still continue the `HttpClient` with deprecated methods but those will break in Vert.x 4
