### ISSUE TITLE
Websocket compression seems broken

### ISSUE THREAD

**Issue by zenios** [eclipse-vertx/vert.x#3119]
I am using the latest vertx milestone 4.0.0-milestone3 and it seems that websocket compression is not working.

ChannelRead of WebSocketServerExtensionHandler responsible for deciding whether to enable compression is not being called (I assume its because its added late to the netty pipeline) 

Most probably this happened due to this commit https://github.com/eclipse-vertx/vert.x/commit/713c1a834dfcfc943f482d628f5c9d0e6474b1e8 that moved initializeWebsocketExtensions inside HttpHandlers which is applied via executeFromIO (Hence my assumption that its added late to the pipeline)

**Comment by vietj** [comment]
can you provide a test case for this @zenios ?

**Comment by zenios** [comment]
Any similar test cases that i could look at and understand what exactly is
needed?

**Comment by zenios** [comment]
In order to make sure that compression initialisation actually works we have to verify that response headers of websocket upgrade request contains Sec-WebSocket-Extensions: permessage-deflate

Unfortunately i could not find a way to inspect the response headers through vertx websocket client.

**Comment by vietj** [comment]
yes we should have such API as it has been requested by others

**Comment by zenios** [comment]
Nevertheless i made a pull request including a test case and a fix

**Comment by vietj** [comment]
it's very fine this way
