### ISSUE TITLE
Cannot remove server cookies without getting cookie list first

### ISSUE THREAD

**Issue by pyranja** [eclipse-vertx/vert.x#3122]
Hi,

https://github.com/eclipse-vertx/vert.x/issues/3050 introduced a regression in cookie handling for the `HttpServerResponseImpl#removeCookie()` method. It is not using the `HttpServerResponseImpl#cookies()` accessor and therefore skips parsing of cookies.
The cookie map is then `null` and the method behaves as if the cookie is not found, failing silently by returning `null`.
The same bug is present in `Http2ServerResponseImpl#removeCookie()`.

![image](https://user-images.githubusercontent.com/2890900/66050538-b08f9680-e52d-11e9-8a04-7cfba3ff76da.png)

I'm working around it by first calling `getCookie()` to initialize the cookie map, then remove it.

As far as I can see the provided session handler might be affected, because it uses `removeCookie`.

I'd like to provide a PR to address this, but cannot give an ETA unfortunately due to time constraints :man_shrugging: .

**Comment by vietj** [comment]
can you provide a reproducer quickly @pyranja ?

**Comment by vietj** [comment]
@pmlopes ?

**Comment by vietj** [comment]
oh right, I will have a try at it.
