### ISSUE TITLE
Deadlock in ASyncFileImpl/PipeImpl (using vertx-web-client and request.sendStream(asyncFile))

### ISSUE THREAD

**Issue by ylemoigne** [eclipse-vertx/vert.x#3124]
Hi,

Using vertx 3.8.1
Using something like (kotlin+coroutine) :

        val props = vertx.fileSystem().propsAwait(path)
        val file = vertx.fileSystem().openAwait(path, openOptionsOf(read = true))
        val response = client.post(4443, "localhost", "/endpoint")
                    .putHeader("content-length", props.size().toString())
                    .sendStreamAwait(file)

It happens that the call never return, but it's random (Never when I tried to extract a reproducer, almost always in the real context, of course).

To investigate, I've copied `PipeImpl` and `ASyncFileImpl` and added some trace. (Modified version in attached files with output)

It's seems like at some time, something has kept the monitor of `ASyncFileImpl` instance, preventing the `resume` call  to execute the method.

[AsyncFileImpl.java.txt](https://github.com/eclipse-vertx/vert.x/files/3685925/AsyncFileImpl.java.txt)
[PipeImpl.java.txt](https://github.com/eclipse-vertx/vert.x/files/3685926/PipeImpl.java.txt)
[output.txt](https://github.com/eclipse-vertx/vert.x/files/3685918/output.txt)

**Comment by vietj** [comment]
do you mean thread deadlock ?

**Comment by ylemoigne** [comment]
It seems to (a call to a synchronized method do not enter in the method)

**Comment by vietj** [comment]
when it happens can you do a thread dump and most it here  ? that will be very helpfull

**Comment by ylemoigne** [comment]
Yes. I've joined the output of trace corresponding the thread dump.

[thread-dump.txt](https://github.com/eclipse-vertx/vert.x/files/3687901/thread-dump.txt)
[output-thread-dump.txt](https://github.com/eclipse-vertx/vert.x/files/3687912/output-thread-dump.txt)

**Comment by ylemoigne** [comment]
Hi, do you have any suggestion for a workaround ?

**Comment by vietj** [comment]
@ylemoigne not yet time to investigate sorry

**Comment by vietj** [comment]
see https://github.com/eclipse-vertx/vert.x/issues/3140

**Comment by ylemoigne** [comment]
Ok, I've patched a local copy and it works !
Thanks You !

**Comment by vietj** [comment]
See also https://github.com/eclipse-vertx/vert.x/commit/41cd0da5c1ada622d6ae4508cb68cc7d46299a1b

**Comment by vietj** [comment]
good to see it works @ylemoigne that being said it looks like you are using two different event loops an that should not be the case, you should check your application

**Comment by vietj** [comment]
perhaps you are using an `HttpClient` shared ?
