### ISSUE TITLE
Using native transport and a UNIX domain socket with the HTTP server causes netty warnings

### ISSUE THREAD

**Issue by campbells-snap** [eclipse-vertx/vert.x#3125]
Hello,

When binding an HTTP server to a UNIX domain socket, Netty prints out warnings upon each connection as so:

```
Oct 04, 2019 3:48:03 PM io.netty.bootstrap.AbstractBootstrap setChannelOption
WARNING: Unknown channel option 'io.netty.channel.epoll.EpollChannelOption#TCP_QUICKACK' for channel '[id: 0x7a807bb7]'
Oct 04, 2019 3:48:03 PM io.netty.bootstrap.AbstractBootstrap setChannelOption
WARNING: Unknown channel option 'io.netty.channel.epoll.EpollChannelOption#TCP_CORK' for channel '[id: 0x7a807bb7]'
```

This appears to be caused by [one of the configure functions](https://github.com/eclipse-vertx/vert.x/blob/3ba5f621b4689db9223d562842af09b5c36cdf6f/src/main/java/io/vertx/core/net/impl/transport/EpollTransport.java#L146) in EpollTransport, which always set the `TCP_QUICKACK` and `TCP_CORK` options, even on a UNIX domain socket.

This occurred with `netty-transport-native-epoll` version `4.1.39.Final` (same version as vert.x imports) and with vert.x version `3.8.1`.

**Comment by vietj** [comment]
normally those options are supported, but internally it seems not used.

**Comment by campbells-snap** [comment]
These options don't seem to be present for UNIX sockets - `io.netty.channel.epoll.EpollSocketChannelConfig.getOptions` lists a bunch of options (including `TCP_CORK` and `TCP_QUICKACK`), while `io.netty.channel.epoll.EpollDomainSocketChannelConfig.getOptions` doesn't.

In IntelliJ when I go to find the references to `TCP_QUICKACK`, I can only see `EpollSocketChannelConfig` and `EpollTransport` (from vert.x)

**Comment by vietj** [comment]
indeed, this is quite weird, we should remove them until they are added
