### ISSUE TITLE
WebClient request not fail when connection reset

### ISSUE THREAD

**Issue by cpdyj** [eclipse-vertx/vert.x#3127]
When I send a get request use webClient. (Over socks5 proxy) before server response( It's a long poll.) I shutdown socks5. Console print a fatal error: 远程强制关闭连接( I'm using zh-cn locale, English means: Remote peer force reset connection) 
But the callback not called. No more log on console ( I use log4j DEBUG level )
How to get the exception and retry the request? 
Thank you.
(I am too tired to fix-up the issues format and syntax error. Sorry)

**Comment by vietj** [comment]
can you provide a reproducer @cpdyj ?

**Comment by cpdyj** [comment]
Sorry, code is some complex... Before I finish. You can try use `sendMulitpartForm()` with `postAbs()`
In my code, first request is `getAbs()` with no body and it's ok. But after that all request is `postAbs()` with `sendMulitpartForm()` and boom! : )
Thank you

**Comment by vietj** [comment]
can you try debug and see what is happening or provide a reproducer ?

**Comment by cpdyj** [comment]
I debug it. In `HttpContext`
I add a breakpoint in `io.vertx.ext.web.client.impl.HttpContext.execute()` [link](https://github.com/vert-x3/vertx-web/blob/4ebaed7fe045a34c9475050aad5fadd516818184/vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpContext.java#L280) 

normal: `PREPARE_REQUEST SEND_REQUEST RECEIVE_RESPONSE DISPATCH_RESPONSE`
get request if I cut network: `PREPARE_REQUEST SEND_REQUEST FAILURE`
post req I cut network: `PREPARE_REQUEST SEND_REQUEST ... nothing happend` (I have set timeout(10000))

I can't continue debug because code goto `HttpContext:469` [link](https://github.com/vert-x3/vertx-web/blob/4ebaed7fe045a34c9475050aad5fadd516818184/vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpContext.java#L469)

```java
stream.pipeTo(req, ar -> {
  if (ar.failed()) {           //========== never called.
    responseFuture.tryFail(ar.cause());
    req.reset();
  }
});
```

**Comment by cpdyj** [comment]
![image](https://user-images.githubusercontent.com/13687964/66264948-80533b00-e840-11e9-84b2-4503077abe14.png)

```kotlin
webClient.postAbs(urlGen.invoke(command)).timeout(timeout).sendMultipartForm(awsl(list, mapper)) {
    // handle response
    handleResponse(it, resultType, event)
}
```

```kotlin
fun awsl(args: List<Pair<String, Any?>>, mapper: ObjectMapper): MultipartForm = MultipartForm.create().apply {
    args.forEach { (key, value) ->
        if (isSimpleType(value)) {
            attribute(key, value.toString())
        } else {
            attribute(key, mapper.writeValueAsString(value))
        }
    }
}
```

```kotlin
private fun <T : ResultType> handleResponse(
    it: AsyncResult<HttpResponse<Buffer>>,
    resultType: Class<T>,
    event: Promise<T>
) {
    val logger= logger("handleResponse")
    logger.debug { it }
    if (it.succeeded()){
        try {
            val r = mapper.readValue(it.result().bodyAsString(), resultType)!!
            r.okOrThrow()
            event.tryComplete(r)
        } catch (e: Exception) {
            event.tryFail(e)
        }
    }else{
// !!! never called. Althought network is shutdown before connection( But if I send GET, it's correct)
        event.tryFail(it.cause())
    }
}
```

**Comment by cpdyj** [comment]
Notice I 'm using SOCKS5-Proxy:
```kotlin
webClient.create(vertx,WebClientOptions().setProxyOptions().setType(SOCKS5),setHost("127.0.0.1").setPort(17654))
```

**Comment by cpdyj** [comment]
Ok, @vietj 4.0.0-milestone1 hasn't this problem... 3.8.x have.

**Comment by vietj** [comment]
@cpdyj can you provide a reproducer project for this so we can try ?

**Comment by vietj** [comment]
this seem the same issue than https://github.com/vert-x3/vertx-web/issues/1520
