### ISSUE TITLE
Discard old messages

### ISSUE THREAD

**Issue by oleg-kiriyenko** [eclipse-vertx/vert.x#3128]
Hi,

I have written simple test. One verticle (reply) is service that process some complex jobs (modelled with simple Thread.sleep(10000) => 10 seconds). Other verticle (sender) sends 2 messages to be processed with 5 second timeout. So when reply verticle receives second message sender is not interested in response (because all timeouts gone) but those messages still come and we need to do "hard job" to process it. 

Output is here:

Reply started
Message received: ping1
Reply address: __vertx.reply.1
Failed to receive reply: Timed out after waiting 5000(ms) for a reply. address: __vertx.reply.1, repliedAddress: service.address
Failed to receive reply: Timed out after waiting 5000(ms) for a reply. address: __vertx.reply.2, repliedAddress: service.address
Sender done
Message received: ping2
Reply address: __vertx.reply.2

How can we discard old messages (which have been timeouted on sender end)? So that message ping2 will not be processed. 

If we look at code of message sender it creates HandlerRegistration and unregister it on timeout (in sendAsyncResultFailure). So the task is to check on reply verticle if reply address is still registered on event bus. But I haven't found any API to do it. 

The problem is getting more important if sender will try to repeat request on timeout. So we will end up with service bloated with old messages and while we process old messages new messages wil also be timeouted!

Test code:

import io.vertx.core.*;
import io.vertx.core.eventbus.DeliveryOptions;
import io.vertx.ext.unit.TestContext;
import io.vertx.ext.unit.junit.VertxUnitRunner;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.io.IOException;

@RunWith(VertxUnitRunner.class)
public class TimeoutSenderTest {

    private static final String SERVICE_ADDRESS = "service.address";

    private Vertx vertx;

    private final ReplyVerticle reply = new ReplyVerticle();

    @Before
    public void setUp(TestContext context) throws IOException {
        vertx = Vertx.vertx();
        final DeploymentOptions replyOptions = new DeploymentOptions().setWorker(true);
        vertx.deployVerticle(reply, replyOptions, context.asyncAssertSuccess());
    }

    @After
    public void tearDown(TestContext context) {
        vertx.close(context.asyncAssertSuccess());
    }

    @Test
    public void testSender(TestContext context) {
        final DeploymentOptions senderOptions = new DeploymentOptions().setWorker(true);
        final SenderVerticle sender = new SenderVerticle();
        vertx.deployVerticle(sender, senderOptions, context.asyncAssertSuccess());
    }

    private class ReplyVerticle extends AbstractVerticle {

        @Override
        public void start(Promise<Void> startPromise) {
            vertx.eventBus().<String>consumer(SERVICE_ADDRESS).handler(msg -> {
                try {
                    System.out.println("Message received: " + msg.body());
                    System.out.println("Reply address: " + msg.replyAddress());
                    //Model long processing
                    Thread.sleep(10000);
                    msg.reply("pong to " + msg.body());
                } catch (InterruptedException e) {}
            });
            startPromise.complete();
            System.out.println("Reply started");
        }

    }

    private class SenderVerticle extends AbstractVerticle {

        @Override
        public void start(Promise<Void> startPromise) {
            CompositeFuture.join(sendMessage(1), sendMessage(2)).setHandler(ar -> {
                startPromise.complete();
                System.out.println("Sender done");
            });
        }

        private Future<String> sendMessage(int count) {
            return Future.future(promise -> {
                //Five second timeout
                final DeliveryOptions options = new DeliveryOptions().setSendTimeout(5000);
                vertx.eventBus().request(SERVICE_ADDRESS, "ping" + count, options, ar -> {
                    if (ar.succeeded()) {
                        System.out.println("Reply received: " + ar.result().body());
                    } else {
                        System.out.println("Failed to receive reply: " + ar.cause().getMessage());
                    }
                    promise.complete();
                });
            });
        }
    }
}

**Comment by tsegismont** [comment]
You could send headers together with the message. In the headers, add a timestamp of expiry date.

On the receiver side, check the timestamp/expiry date in the headers before processing.

**Comment by tsegismont** [comment]
Here's the doc for sending headers with the message: https://vertx.io/docs/vertx-core/java/#_setting_headers_on_messages

**Comment by tsegismont** [comment]
Can you please post any further question to the user forum? Most community members do not subscribe to GH issues.
