### ISSUE TITLE
Blocking Code vs Fibers

### ISSUE THREAD

**Issue by onthegit** [eclipse-vertx/vert.x#3129]
Hello authors and coders,

although this is  not an issue, I am interested in what would be your opinion on calling ExecuteBlocking for  small blocking code vs running  the code on Vertx Sync Fibers..

Example:
Running vertx instances using AbstractVehicle (event-loop), and running other vertx instances on SyncVerticle (quasar fibers) on same  server. Would it be more efficient to run the small blocking code (aritmetic operations and rounding.. BigDecimal, etc) on SyncVerticle and returning the result via event-bus to the  AbstractVerticle instances, 
or simply running executeBlocking{} on AbstractVerticle instance to run this small blocking code? Which is better for large scale?

**Comment by tsegismont** [comment]
Using vertx-sync does not mean you can block the event loop. It changes the
way you implement the verticle: it looks like blocking imperative but it's
still asynchronous and non-blocking underneath.

If you want to execute blocking code, you have to use executeBlocking or
worker verticles.

**Comment by tsegismont** [comment]
Please send further questions to the user forum, there are higher chances
you get answers from the community (not everyone subscribes to GH).

Thank you

Le lun. 7 oct. 2019 à 10:41, Thomas SEGISMONT <tsegismont@gmail.com> a
écrit :

> Using vertx-sync does not mean you can block the event loop. It changes
> the way you implement the verticle: it looks like blocking imperative but
> it's still asynchronous and non-blocking underneath.
>
> If you want to execute blocking code, you have to use executeBlocking or
> worker verticles.
>
