### ISSUE TITLE
Do not lock the handler calls in AsyncFile

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#3140]
Currently the `AsyncFile` implementation calls the file handlers in a synchronized block. This synchronization is only useful for reading the handler and should not be used when calling them.

**Comment by BorisJineman** [comment]
Cool, the commit fixed the issue I observed in Vert.X 3.7.1 when pumping an AsyncFile into HttpServerResponse in another Vertx Context thread ( not the conn's Context thread.).
:+1:
