### ISSUE TITLE
Delay vert.x shutdown till Hazelcast AsyncMap remove operation is completed

### ISSUE THREAD

**Issue by naveen140990** [eclipse-vertx/vert.x#3147]
Hi,
 
I am using vert.x version 3.7.1 and stuck in an issue while triggering cleanup during vert.x shutdown.

I am gracefully shutting down vert.x process(soft kill using kill 9 <PID>). I have called closeHandler with a handler on ServerWebSocket which gets invoked while graceful shutdown.
In Handler, I am triggering a remove operation on clustered AsyncMap of Hazelcast. As remove() is asynchronous call, handler completes execution and eventually MainVerticle is stopped(including stopping Hazelcast on node).

Because of above scenario, I am getting below error in callback of remove operation and I could not complete cleanup of connected users.
com.hazelcast.core.HazelcastInstanceNotActiveException: State: PASSIVE Operation: class com.hazelcast.map.impl.operation.RemoveOperation

I was thinking of using setTimer() in MainVerticle's stop method to simulate some constant delay but that sounds ugly.

Can someone suggest a better way to handle this?

**Comment by naveen140990** [comment]
I spent some time on above and seems there is some issue here.

I have a MainVerticle which deploys WebsocketVerticle. Webosocket verticle is responsible for websocket connections. In my current scenario, 10000 users were connected to websocket and then I killed machine(kill 9 <PID>).  stop() method of Webosocket verticle got called immediately and subsequently closeHandler  of ServerWebSocket  got invoked. This closeHandler actually removes records from shared AsyncMap. 

Execution of below sample Handler completes .

class CloseHandler implements Handler<Void> {
        public CloseHandler() {
            super();
        }
        @Override
        public void handle(Void event) {
            try {
                cleanupUser('userId');  ------> This implementation actually removes from AsyncMap 
                logger.info("cleanup done");
            } catch (Exception e) {
                logger.error("error while closing socket for ", e);
            }
        }
    }

remove operation of AsyncMap is handled asynchronously inside cleanupUser method.  While this operation is still in progress for 10k users, stop() method of MainVerticle is invoked. And after this invocation,  I am getting below errors:

com.hazelcast.core.HazelcastInstanceNotActiveException: State: PASSIVE Operation: class com.hazelcast.map.impl.operation.RemoveOperation

com.hazelcast.core.HazelcastInstanceNotActiveException: State: SHUT_DOWN Operation: class com.hazelcast.map.impl.operation.RemoveOperation

Is there an issue or I am doing something seriously wrong?

**Comment by tsegismont** [comment]
A snippet with (simplified) code would help to better understand. But from
what I understand, cleaningUpser is a non blocking op which takes time to
complete.
In this case, it would be better to invoke in the verticle stop method and
complete the stop future/promise only when data has been fully removed from
the async map.

Le mer. 16 oct. 2019 à 20:56, Naveen Katiyar <notifications@github.com> a
écrit :

**Comment by naveen140990** [comment]
You got that right, but it would need some logic to track connected users on machine and then check if remove operation was success, and after that complete future/promise in vertical stop(). That would be my last resort.

But I am struggling to understand why MainVerticle stop() is invoked few seconds  after all closeHandlers are executed, but before remove operation is  completed in async map.

First Run stop() Invocation time :
17 Oct 2019 01:27:09,616 vert.x-eventloop-thread-3 [INFO ]    verticles.WebsocketVertical                         - stopping WebsocketVertical
17 Oct 2019 01:27:19,512 vert.x-eventloop-thread-1 [INFO ]    verticles.MainVerticle                              - stopping Main verticle

Second Run stop() Invocation time :
17 Oct 2019 01:42:04,526 vert.x-eventloop-thread-3 [INFO ]    verticles.WebsocketVertical                         - stopping WebsocketVertical
17 Oct 2019 01:42:07,390 vert.x-eventloop-thread-1 [INFO ]    verticles.MainVerticle                              - stopping Main verticle

Please find code snippet of verticles below, there could be some syntactical errors.

`public class Main {
    public static void main(String[] args) {
        System.out.println("inside main");
        HazelcastClusterManager mgr = new HazelcastClusterManager();

        VertxOptions options = new VertxOptions().setClusterManager(mgr);
        Vertx.clusteredVertx(options, e -> {
            if (e.succeeded()) {
                Vertx vertx = e.result();
                try{
                    DeploymentOptions deploymentOptions=new DeploymentOptions();
                    vertx.deployVerticle(new MainVerticle(),deploymentOptions, e1 -> {
                        System.out.println("deployed producer");
                    });
                }catch (Exception ex){
                    System.out.println("error in starting chat-websocket"+ex.getMessage());
                }
            }
        });
    }


@Singleton
public class MainVerticle extends AbstractVerticle {
    public MainVerticle() {
        super();
        logger.info("Main Verticle Called");    
    }
    @Override
    public void start() {
        deployVericle(websocketVertical,false).subscribe(id -> {
            logger.info("deployed : {}", id);
        }, err -> {
            err.getCause().printStackTrace();
        });
    }

    private ObservableFuture<String> deployVericle(AbstractVerticle name, boolean isWorker) {
        ObservableFuture<String> completionHandler = io.vertx.rx.java.RxHelper.observableFuture();
        DeploymentOptions options = new DeploymentOptions();
        options.setWorker(isWorker);
        options.setConfig(config);
        //TODO: read worker pool size from override
        options.setWorkerPoolSize(20);
        vertx.deployVerticle(name, options, completionHandler.toHandler());
        return completionHandler;
    }

    @Override
    public void stop(Future<Void> stopFuture) throws Exception {
        logger.info("stopping Main verticle");
        stopFuture.complete();
    }
}


@Singleton
public class WebsocketVertical extends AbstractVerticle {
    private static final Logger logger = LoggerFactory.getLogger(WebsocketVertical.class);
    private NewConnectionHandler newConnectionHandler;

    @Inject
    public WebsocketVertical( NewConnectionHandler newConnectionHandler) {
        super();
        this.newConnectionHandler = newConnectionHandler;
    }

    @Override
    public void start() {
        logger.info("vertical starting");
        HttpServerOptions options = new HttpServerOptions();
        options.setMaxWebsocketFrameSize(6553600);
        HttpServer server = vertx.createHttpServer(options);
        Router router = Router.router(vertx);
        router.route().handler(BodyHandler.create());
        router.get("/connect").handler(newConnectionHandler);

        server.requestHandler(router::accept).listen(config().getInteger("http.port", 8090),
                config().getString("http.host", "0.0.0.0"), httpServerAsyncResult -> {
                    if (httpServerAsyncResult.succeeded()) {
                        logger.info("Server is running on port {}", httpServerAsyncResult.result().actualPort());
                    } else {
                        logger.error("server start failed", httpServerAsyncResult.cause());
                    }
                });
        logger.debug("verical started with node id : {}", ((VertxInternal) vertx).getClusterManager().getNodeID());
    }

    @Override
    public void stop(Future<Void> stopFuture) {
        logger.info("stopping verticle");
        stopFuture.complete();
    }

}

@Singleton
public class NewConnectionHandler implements Handler<RoutingContext> {
    final Logger logger = LoggerFactory.getLogger(this.getClass());
    private Vertx vertx;
    private EventBus eventBus;
    private AsyncMap<String, GlobalSession> globalMap;

    @Inject
    public NewConnectionHandler(Vertx vertx) {
        super();
        this.vertx = vertx;
        this.eventBus = vertx.eventBus();
        ObservableFuture<AsyncMap<String, GlobalSession>> mapObserbable = RxHelper.observableFuture();
        this.vertx.sharedData().getClusterWideMap(Constants.GLOBAL_USER_SESSION_MAP_NAME,
                mapObserbable.toHandler());
        mapObserbable.subscribe(map -> {
            globalMap = map;
        }, onError -> {
            onError.printStackTrace();
        });
    }

    @Override
    public void handle(RoutingContext routingContext) {
        logger.trace("new socket request with body {}", routingContext.request().params());
        ServerWebSocket socket = routingContext.request().upgrade();
        logger.info("upgrade successfull for user {}");
       //........
        socket.closeHandler(new CloseHandler());
      //........
    }
    
    class CloseHandler implements Handler<Void> {
        public CloseHandler() {
            super();
        }
        @Override
        public void handle(Void event) {
            try {
                logger.info("close event received for {}");
                cleanupUser();
            } catch (Exception e) {
                logger.error("error in closing socket {}");
                logger.error("error while closing socket for ", e);
            }
        }

        private ObservableFuture<GlobalSession> cleanupUser() {
            logger.debug("cleaning up user and destroying session");
            ObservableFuture<GlobalSession> mapResult = RxHelper.observableFuture();
            globalMap.remove("anyUserId", mapResult.toHandler());
            logger.info("successfully removed closed connection {}");
            return mapResult;
        }
    }
}`

**Comment by tsegismont** [comment]
Le mer. 16 oct. 2019 à 22:58, Naveen Katiyar <notifications@github.com> a
écrit :

> You got that right, but it would need some logic to track connected users
> on machine and then check if remove operation was success, and after that
> complete future/promise in vertical stop(). That would be my last resort.
>
> But I am struggling to understand why MainVerticle stop() is invoked few
> seconds after all closeHandlers are executed, but before remove operation
> is completed in async map.
>
Because the close handler returns before the operation is completed.
Perhaps in the webscocket verticle you can keep track of the number of
connected users (using connection and close handlers).
Then instead of completing the verticle stop method immediately, you defer
until the number of connected user is down to zero.

HTH

**Comment by naveen140990** [comment]
Ok, for alternative solution as is suggested by you, I will have to differentiate between a normal socket close and a socket close triggered due to soft kill. I am not yet sure, how to to do that. But that's a different issue.

My current concern is, Even if all Close Handlers are executed, stop call of MainVerticle verticle  waits for few seconds. May be in anticipation of background tasks of AsyncMap removal. But this wait is not sufficient enough and most of the time stop() method of MainVerticle is invoked before async remove of all users is completed.

There seems to be some logic is vertx, which defers stop() method invocation of MainVerticle .

Please allow me to post below logs of my test:

17 Oct 2019 11:40:12,327 vert.x-worker-thread-11 [INFO ]    verticles.BinaryMessageProducerVerticle             - stopping producer verticle
17 Oct 2019 11:40:12,339 vert.x-eventloop-thread-3 [INFO ]    verticles.WebsocketVertical                         - stopping WebsocketVertical
17 Oct 2019 11:40:20,873 vert.x-eventloop-thread-1 [INFO ]    verticles.MainVerticle                              - stopping Main verticle


At 11:40:12, I kill my vert.x machine and first two verticle's stop is invoked immediately. But stop method of MainVerticle is  invoked at 11:40:20 i.e. after 8 seconds.

So there is something in vertx which defers stop method invocation by 8 seconds but this time is not enough as async remove from AsyncMap takes longer, say 10 seconds. So this seems problematic to me.

Please revert , in case I am not clear enough to explain my concern.

**Comment by naveen140990** [comment]
Also, all closeHandlers are executed by 11:40:14 i.e. after 2-3 seconds when vert.x machine is killed.

**Comment by tsegismont** [comment]
When leaving the cluster gracefully, Vert.x communicates with Hazelcast. It's only really closed when HZ tells us the node has been removed from the cluster. This process may take some time (as HZ will rebalance data among other nodes).

**Comment by naveen140990** [comment]
Ok, that make sense.
So does that mean Hazelcast is prematurely telling to vert.x that node is out of cluster and probbaly also closing its resources? As in this case, there are several remove operation pending on AsyncMap.

I think vert.x should check if any handlers (which it has attached to AsyncMap operations and vert.x is aware of this), are not completed(with success or failure), then it should delay it's shutdown call to hazelcast during graceful shutdown.

**Comment by tsegismont** [comment]
I don't believe there's anything wrong in the Vert.x / HZ shutdown process. The code is sending operations to a clustered map while the node is being removed from the cluster.

Vert.x will not remove the node from the cluster until the verticle stop method future is completed. So, as advised in a previous comment, make sure this future is not completed until the clean up method completes.

**Comment by naveen140990** [comment]
Ok, Got your point. Will do that way.
Thanks for your support!
