### ISSUE TITLE
JsonObjectMessageCodec has inconsistent behavior in handling local vs. remote message sending & receiving.

### ISSUE THREAD

**Issue by jenoosia** [eclipse-vertx/vert.x#3154]
`JsonObjectMessageCodec` has inconsistent support for JsonObjects depending on whether they are being passed through the event bus **locally** or **remotely** (through the wire). 

If a `JsonObject` contains a `BigDecimal` or `List` field, it will encounter issues when going through the event bus **locally**. For `BigDecimal` fields, an error will be thrown. For `List` fields, it will be converted into a `JsonArray` instead. This is inconsistent from the behavior if the same JsonObject is passed through the wire/remotely. 

We've found the root cause to be in how the `encodeFromWire() / decodeFromWire()` and `transform()` methods were implemented in `JsonObjectMessageCodec`. The relevant source is reproduced below:

```
  @Override
  public void encodeToWire(Buffer buffer, JsonObject jsonObject) {
    Buffer encoded = jsonObject.toBuffer();
    buffer.appendInt(encoded.length());
    buffer.appendBuffer(encoded);
  }

  @Override
  public JsonObject decodeFromWire(int pos, Buffer buffer) {
    int length = buffer.getInt(pos);
    pos += 4;
    return new JsonObject(buffer.slice(pos, pos + length));
  }

  @Override
  public JsonObject transform(JsonObject jsonObject) {
    return jsonObject.copy();
  }
```

For **remote** sending/receiving of messages, the `JsonObject` is encoded into a byte buffer and decoded back into a new `JsonObject`, which results in a byte-perfect copy of the message.

For **local** sending/receiving of messages, `JsonObject.copy()` is used to create a deep copy of the object instead. This, however, has some side effects that result in the above highlighted issues with certain field types, resulting in either an error, or an inconsistent copy of the original message.

Digging further, the issue seems to be that `JsonObject.copy()` in turn uses `Json.checkAndCopy()`, which has processing logic that affects the List & BigDecimal handling. Snippet reproduced here:

```
    if (val == null) {
      // OK
    } else if (val instanceof Number && !(val instanceof BigDecimal)) {
      // OK
    } else if (val instanceof Map) {
      if (copy) {
        val = (new JsonObject((Map)val)).copy();
      } else {
        val = new JsonObject((Map)val);
      }
    } else if (val instanceof List) {
      if (copy) {
        val = (new JsonArray((List)val)).copy();
      } else {
        val = new JsonArray((List)val);
      }
    } else {
      throw new IllegalStateException("Illegal type in JsonObject: " + val.getClass());
    }
```

Based on this, `BigDecimal` values will throw an `IllegalStateException`, `Map` becomes `JsonObject` and `List` becomes a `JsonArray`. I can understand the rationale here, as Vert.x is meant to be a polyglot framework and these types are Java-specific. 

**However, this results in `JsonObjectMessageCodec` having behavior that is inconsistent, depending on if the verticles are co-located locally or are clustered remotely.**

The reason why we discovered this is because we went through a refactoring exercise to consolidate certain related services together, and the first step was to combine previously-remote verticles into a group of child verticles under the same main verticle. Suddenly, event bus calls that used to be working fine were throwing errors.

As `JsonObjectMessageCodec` is a baked-in codec for handling JsonObject messages in `CodecManager`, we couldn't override it or replace it. What we ended up doing was to register a custom codec whose `transform()` method mimics the byte buffer logic in `encodeFromWire()` / `decodeFromWire()`:

```
    @Override
    public JsonObject transform(JsonObject jsonObject) {
        return new JsonObject(jsonObject.toBuffer());
    }
```

However, this also means we need to ask all our services to register this custom codec.

I'm raising this issue because I think it's worth reviewing the implementation for `JsonObjectMessageCodec` and consider if there are any improvements to be made, especially in the consistency of local v remote message handling. Thanks.

**Comment by arkmic35** [comment]
Any follow-up? JsonObjects may contain Maps or JsonObjects as children. Maybe it doesn't impact most of people, but it causes issues when trying to use JSON schema validators

**Comment by vietj** [comment]
we made change in Vert.x 4 to `JsonObject` / `JsonArray` on the internal structure and now the copy/read/write does happen.

When the number is copied locally indeed we get a `BigDecimal`, when the number is written/read, the number will be a `Double` because the current jackson parser is configured for speed. We could make this configurable to instead deserialize to `BigDecimal`.

`BigInteger` will be handled remotely.
