### ISSUE TITLE
How to debug a vertx project ? 

### ISSUE THREAD

**Issue by arniu** [eclipse-vertx/vert.x#3159]
When I debug a vertx project created by [Vert.x Starter](https://start.vertx.io/), execution will not pause at any breakpoint.

Any one can help me? Thanks very much.

**Comment by vietj** [comment]
run the JVM in debug mode and debug as any java program

**Comment by arniu** [comment]
but execution will not pause at any breakpoint

**Comment by arniu** [comment]
I did.

When I debug through the `runShadow` task, all is fine.

While `run` fails.

**Comment by arniu** [comment]
I guess, `Launcher` may not pass debug options down to the JVM.
