### ISSUE TITLE
Maven surefire plugin

### ISSUE THREAD

**Issue by erayerdem** [eclipse-vertx/vert.x#3161]
I created a vert.x project using https://start.vertx.io/ . I  tried  build project using ./mvnw clean package command .  ı get an exception .  
 Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project starter: There are test failures.  

I changed  surefire plugin version and it worked . vert.x project default version hava a problem . 2.19.1 working perfectly

**Comment by vietj** [comment]
can you report this issue to https://github.com/vert-x3/vertx-starter
