### ISSUE TITLE
Suggestion: Improving ReactiveX APIs

### ISSUE THREAD

**Issue by lwlee2608** [eclipse-vertx/vert.x#3169]
Given a scenario, I want to make some legacy synchronous API calls. In this example, I will simply call Thread.sleep() to represent that.
In order not to block the event-loop, I will need to use `rxExecuteBlocking` api provided by `vertx`

```
vertx.rxExecuteBlocking( future -> {
    try {
        Thread.sleep(3000);
        future.complete("ExampleResult");
    } catch (Exception e) {
        future.fail(e);
    }
}) 
... chain to other rxjava operation
```
In our project, where we exclusively code with RxJava
Ideally, we would prefer 
```
vertx.rxExecuteBlocking( () -> {
    Thread.sleep(3000);
    return "ExampleResult";
})
```
or perhaps, chain it as method reference
```
private String synchronousCall() throws Exception{
    Thread.sleep(3000);
    return "ExampleResult";
}
...
vertx.rxExecuteBlocking(this::synchronousCall);
```

In order to achieve this, we wrapped the `rxExecuteBlocking` with our own spin, replacing `Handler<Promise<T>>` with `Callable` (and also overload it with `Runnable` that so that it can return void)

```
public Maybe<Object> rxExecuteBlocking(Callable caller){
    return vertx.rxExecuteBlocking( objectFuture -> {
        try {
            objectFuture.complete(caller.call());
        } catch (Throwable e) {
            objectFuture.fail(e);
        }
    });
}
```

I think it would make these rx APIs slightly more align with the Reactive programming paradigm. But that's just my two cents. It's not a deal-breaker.

**Comment by okou19900722** [comment]
you can use `vertx.setTimer` instead of `Thread.sleep`. eg:
```
vertx.setTimer(3000, r -> future.complete("ExamplesResult"))
```

**Comment by lwlee2608** [comment]
@okou19900722, that's not the point... Thread.sleep is just an example. Normally it would be some other legacy synchronous API

**Comment by vietj** [comment]
can you reopen this issue at https://github.com/vert-x3/vertx-rx ?
