### ISSUE TITLE
Feature Request: JsonArray.add(int index, Object value)

### ISSUE THREAD

**Issue by rzorzorzo** [eclipse-vertx/vert.x#3171]
this is easy to add and is available in most json libs
PS: and for JsonArray.set(int index, Object value)
methods add and set have the same semantics as in java's List

**Comment by vietj** [comment]
we might have `JsonArray` extends `List` in v4

**Comment by rogelio-o** [comment]
If JsonArray extends List, add method is not going to be fluent (it's not going to return itself) because the signature will not be compatible with List interface. I mean, `JsonArray add(Object value)`is not going to be posible anymore. Is this acceptable?

I can work on it :)

**Comment by vietj** [comment]
I think @pmlopes has a coming PR for it soon.
