### ISSUE TITLE
Intermittent MetricsTest testDatagram failure

### ISSUE THREAD

**Issue by julianladisch** [eclipse-vertx/vert.x#3177]
MetricsTest#testDatagram1 and/or MetricsTest#testDatagram2 fail intermittently in at least one out of five runs:
`MetricsTest.lambda$testDatagram$95:830->AsyncTestBase.assertEquals:241 expected:<1> but was:<0>`
Example: https://travis-ci.org/eclipse-vertx/vert.x/jobs/607323914#L14311

**Comment by vietj** [comment]
that needs to be checked, it might be a test error or a bug in the implementation.

**Comment by vietj** [comment]
the weird thing is that peer1Metrics writes should never be 1.
