### ISSUE TITLE
Vert.x 3 Python Native Support

### ISSUE THREAD

**Issue by interviewBubble** [eclipse-vertx/vert.x#3180]
I am getting that vert.x 3 official doc doesn't have any documentation for Python.
We are trying to use our Python projects into Vert.x system.
Python system are Machine Learning based projects.

Can anyone help us, how can we use Python ML projects using Vert.x 3.

**Comment by ZuiSong** [comment]
you can use Http protectl or use EventBus  connect to vertx project and python project

https://vertx.io/docs/vertx-tcp-eventbus-bridge/java/

**Comment by tsegismont** [comment]
Vert.x does not support Python anymore (no maintainer). Use the EB bridge as advised by @ZuiSong

**Comment by WolfgangFahl** [comment]
You might want to try https://github.com/dapangmao/vertx-python-client

**Comment by vietj** [comment]
is this project referenced in vertx-awesome ?
