### ISSUE TITLE
SocketAddressImpl constructor leads to NullPointerException if the InetSocketAddress is unresolved

### ISSUE THREAD

**Issue by jaikiran** [eclipse-vertx/vert.x#3181]
As reported here https://github.com/quarkusio/quarkus/issues/5247, the stacktrace shows that constructing a `io.vertx.core.net.impl.SocketAddressImpl` leads to a `NullPointerException` if the passed `InetSocketAddress` is "unresolved". 

This is due to the code in `SocketAddressImpl` which looks like:

```
this(address.getPort(), address.getAddress().getHostAddress());
```
The `address.getAddress()` can return null (as stated in its javadoc) if the address is unresolved. I think a better/safer way to instantiate this would be to:
```
this(address.getPort(), address.getAddress() == null ? address.getHostString() : address.getAddress().getHostAddress());
```

**Comment by vietj** [comment]
I think in this case, it should return null instead of a `SocketAddress`. Do you know how that could be reproduced easily locally so we can test it ?

**Comment by jaikiran** [comment]
> Do you know how that could be reproduced easily locally so we can test it ?
I suspect this happens if the host name (of the client) happens to be an internal network name and not exposed to the outside world. That's a guess based on the use case which seems to have triggered this. It's a bit late in the night for me here, so I haven't had a chance to experiment with it and reproduce this in a more isolated fashion. I'll probably find some time tomorrow evening and see if I can provide an isolated reproducer for this.

**Comment by vietj** [comment]
@jaikiran thanks, it would be interested to know if we can reproduce it with easily with a network setting
