### ISSUE TITLE
Could you tell me how to support Socket.IO？

### ISSUE THREAD

**Issue by qinfensky** [eclipse-vertx/vert.x#3188]
Previously, using Socket.IO in Node.js was a very convenient way to implement a chat room, but now I want to use Vert.x, and I don't know how to integrate Socket.IO into Vert.x, to see a project netty-socketio. Can you integrate it into Vert.x?

**Comment by pmlopes** [comment]
Currently, there's no official support for socket.io, we do however support sockjs. Both projects are different and have different goals. We do however want to have socket.io support but integration work needs to be done.

**Comment by qinfensky** [comment]
@pmlopes Thank you for your contribution. I wish I could see you integrate Socket.IO into Vert.x sooner.
