### ISSUE TITLE
I want to integrate with other libraries

### ISSUE THREAD

**Issue by qinfensky** [eclipse-vertx/vert.x#3190]
I want to integrate some libraries into Vert.x, such as netty-socket.io,. I don't see in the documentation how to wrap a library as a mod, for Vert.x. Where should I start?

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by vietj** [comment]
you can read this guide that explains how to integrate Netty libraries in Vert.x : https://github.com/vietj/advanced-vertx-guide
