### ISSUE TITLE
Context duplicate breaks equality check

### ISSUE THREAD

**Issue by zenios** [eclipse-vertx/vert.x#3198]
In many parts of vertx (vertx-sql-client) a context equality check (context == Vertx.currentContext) is done in order to know if we are running in the same event loop else runOnContext

With the introduction of context duplicate this equality check is not functioning correctly

**Comment by vietj** [comment]
right, we should use something else instead

**Comment by vietj** [comment]
well actually it is kind of correct to do that because it means that the callback will not be executed on the right context

**Comment by vietj** [comment]
but we should instead test the event loop and use the provided context to create a promise to return the result

**Comment by zenios** [comment]
Else in terms of getting rid duplicated context or another way of equality?.

If its the second we will gave a hard time finding all the equality checks
in the code

**Comment by vietj** [comment]
so we should have something like (pseudo code):

```java
public Future<Something> method() {
   ContextInternal current = vertx.getOrCreateContext();
   Promise<Something> promise = current.promise();
   if (ctx.nettyEventLoop().inEventLoop()) {
      method(promise);
   } else {
      ctx.runOnContext(promise, this::method);
   }
   return promise.future();
}

private void method(Handler<AsyncResult<Something>> promise) {
   ...
}
```

**Comment by vietj** [comment]
there are chances also we should use `PromiseInternal` as we are dealing with Netty operations but I'm not sure yet

**Comment by zenios** [comment]
The problem with that approach is that it will be difficult to find all the
context equality checks done in code.

Is there any possibility of getting rid duplicated context?

From my understanding it was introduced for metrics spi and in order to
shade context local data.

Can we make the context data a stack?
I.e push a new context data onto the stack and when finished pop it?

**Comment by vietj** [comment]
this should be done only in entry point of the client, it is used for distributing tracing

**Comment by vietj** [comment]
no we cannot make it a stack because the same context (not duplicate) can be used concurrently by many different requests

**Comment by vietj** [comment]
we simply need to find them all and do it :-)

**Comment by zenios** [comment]
Ok i will start with sql client.can we make a helper for that pseudo code
inside contextinternal?

**Comment by vietj** [comment]
I think this means quite some changes internally first because we need to use Promise and possibly PromiseInternal for this

**Comment by vietj** [comment]
I will have a look soon when all pending PR are merged, thanks for offering your help

**Comment by zenios** [comment]
Let me know and i will start working in it.thanks

**Comment by vietj** [comment]
I will have a look at using Promise in the client so we can do that and also we can have hte Future based interface for this client which is a 4.0 item that has been postponed so far

**Comment by vietj** [comment]
Likely I think we should define how this work for any kind of API and make this idiom as you said easier to implement

**Comment by knotenpunkt** [comment]
A question: how should i now check, if i am on the correct context?
and if im not on the correct context, how should i now run Code on the correct context.

it seems that 
```
if(savedContext==getOrCreateContext())
{
    savedContext.runOnContext(...)
}
```
doesnt do the trick anymore.

and can you ajdjust your documentation?

lg knotenpunkt

**Comment by vietj** [comment]
Simply use `runOnContext()` @knotenpunkt

**Comment by knotenpunkt** [comment]
**and what check should i use?**, and what is the difference between runOnContext() and a direct execution on the eventloop,

**related:**
you implemented such nice things into contextInternal.... dispatch (what is the difference to execute?) and promise-binding to that context, dont you think exposing that interfaces to the public is a good idea?
so i guess i dont have to catch the context on my self, but i i have that special promise which do this internally for me?

lg knotenpunkt

**Comment by knotenpunkt** [comment]
you can take a look for an example, where to use such equality-checks and runOnContext on "user-code" here: https://groups.google.com/d/msg/vertx/1euVCc2LbTY/mU5FVNQzCAAJ

i guess in that example i reconstruct something like your context-internal.promise() feature.

the difference here is, that i use runOnContext instead of the dispatch-method that context-internal and its promise implementation use: **so whats the different (between dispatch() and execute()/RunOnContext())?**

**and how should i make my equality checks?**

lg knotenpunkt

**Comment by vietj** [comment]
dispatch will only execute in event loop when necessary, this code is supposed to be used when this is a callback from Netty not from other code.
