### ISSUE TITLE
JsonPointer issues

### ISSUE THREAD

**Issue by xjxb21** [eclipse-vertx/vert.x#3205]
JsonPointer pointer = JsonPointer.from("/hello/world/some");
        String s = "{\n" +
                "  \"hello\": {\n" +
                "    \"world\": \"text\"\n" +
                "  },\n" +
                "  \"other\": \"other text\"\n" +
                "}";

        JsonObject jsonObject = new JsonObject(s);
        pointer.writeJson(jsonObject, new JsonObject().put("b", 2), true);
        System.out.println(jsonObject.encode());

result is : {"hello":{"world":"text"},"other":"other text"}

Then 'pointer' change : JsonPointer.from("/hello/world1/some");
result is : {"hello":{"world":"text","world1":{"some":{"b":2}}},"other":"other text"}

Is this correct?

**Comment by slinkydeveloper** [comment]
> result is : {"hello":{"world":"text"},"other":"other text"}

This is the expected result, since `world` is not an object, so no `some` keyword could be added

**Comment by vietj** [comment]
closing per @slinkydeveloper
