### ISSUE TITLE
Support HTTP/2 server worker processing

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#3216]
HTTP/2 server now supports worker processing. The implementation uses now message passing between the connection event loop and its streams.

**Comment by pantinor** [comment]
@vietj When I try this in 3.9.1 we receive a WARN message as 

WARNING: Cannot perform HTTP/2 upgrade in a worker verticle

WebClientOptions clientOptions = new WebClientOptions();
clientOptions.setProtocolVersion(HttpVersion.HTTP_2);

Is there anything else we need to set on the DeploymentOptions for the verticle besides setWorker(true) ?

Thanks.

**Comment by vietj** [comment]
that's only supported in Vert.x 4
