### ISSUE TITLE
Is that right?

### ISSUE THREAD

**Issue by javad-salehi** [eclipse-vertx/vert.x#3219]
Sorry my English is not good enough.
vertx-core : bodyHandler.
It will be called twice.
for a sample GET request called twice.
for a sample submited form , called twice.
As a result, this handle will run two thousand times if a thousand people request the page.
And I did the following, is that right ???
var buff = Buffer.buffer();
request.handler(buffer->{
buff.appendBuffer(buffer);
request.endHandler(/*TODO*/)//using endHandler inside handler
});

**Comment by BillyYccc** [comment]
If you set a `bodyHandler` for an HTTP request you don't need to set a `handler` and `endHandler` to aggregate the chunks by yourself. I believe the [documentation](https://vertx.io/docs/vertx-core/java/#_handling_requests) is quite clear.

**Comment by javad-salehi** [comment]
i used only bodyHandler inside requestHandler.
server.requestHandler(request->{
            request.setExpectMultipart(true);
            request.bodyHandler(buffer->{
                System.out.println("bodyHandler invoked");
            });
            request.response().sendFile("./webroot/index.html");
        });

**Comment by javad-salehi** [comment]
bodyHandler is called twice for every request, even for a simple GET http request.

**Comment by vietj** [comment]
can you provide a reproducer project @javad-salehi that we can try ?

**Comment by javad-salehi** [comment]
aslo uploadHandler and streamToFileSystem cant work truly with http2 , 
in secure http1.1 chunked is enable by default and i cant disable it with setChunked(false).
in secure http1.1 chunked is enable but if you dont set content-length = server exception.
While we know if chunked enbaled , no need to set content-length.
There is a complex treatment ،
