### ISSUE TITLE
eventbus cluster  in docker  Connection refused

### ISSUE THREAD

**Issue by zhengyuyzhao** [eclipse-vertx/vert.x#3229]
when i use eventbus cluster in docker  in the same computer, i got a Connection refused error
this is my config
  eventBusOptions:
#    clusterPublicPort: ${publicPort}
#    clusterPublicHost: ${publicHost}
    clusterPublicPort: 9005
    clusterPublicHost: 192.168.10.164
    port: 9000
    host: 127.0.0.1
    clustered: true

**Comment by tsegismont** [comment]
Can you give more info about your issue?

- small reproducer program
- packaging instructions
- run instructions

**Comment by zhengyuyzhao** [comment]
version: 3.8.4
and my netinfo:
        eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.164  netmask 255.255.255.0  broadcast 192.168.10.255
eventbus config:
        clusterPublicPort: 9003
        clusterPublicHost: 192.168.10.164
        port: 9000
        host: 127.0.0.1
docker config :
       port binding: 9003:9000  8003:8000

and i deploy into docker i got this
      wget 127.0.0.1:9003    connected
      wget 192.168.10.164:9003  connecting refused
      wget 127.0.0.1:8003    connected
      wget 192.168.10.164::8003    connected

how is this happen, can you help me

**Comment by zhengyuyzhao** [comment]
when i use  config
     host: 0.0.0.0
this problem resolved

**Comment by WolfgangFahl** [comment]
Why is this closed? When this workaround is not used the confusing error will still happen.
