### ISSUE TITLE
Remove clustered boolean option

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#3230]
Currently the options to build Vertx provide a `clustered` boolean with the following behavior:

- calling `vertx(options)` with `clustered` set to `false` builds a non clustered instance
- calling `vertx(options)` with `clustered` set to `true` throw an `IllegalArgumentException`
- calling `clusteredVertx(options)` with `clustered` set to `true` builds a clustered instance
- calling `clusteredVertx(options)` with `clustered` set to `false` does set `clustered` to `true` and then builds a clustered instance

Given this behaviour, the usefulness of this setting seems very low and instead it could be removed in Vert.x 4 with no actual impact other than not throwing an `IllegalStateException` when `clustered` is set to `true` and the `vertx(options)` method is called.

**Comment by wowselim** [comment]
should `vertx(options)` in this case set `clustered` to `false`?

**Comment by tsegismont** [comment]
@wowselim the idea is to remove it completely. So:

- if `vertx(options)` is called, a standalone instance is created
- if `clusteredVertx(options)` is called, a clustered instance is created

**Comment by wowselim** [comment]
I have drafted #3348 with the change discussed here

**Comment by tsegismont** [comment]
Closed via #3350
