### ISSUE TITLE
fileUpload & sendFile in HTTP2  , 

### ISSUE THREAD

**Issue by javad-salehi** [eclipse-vertx/vert.x#3238]
The following code works correctly in HTTP1.X
        server.requestHandler(request->{
            request.setExpectMultipart(true);
            request.uploadHandler(file->{
                file.streamToFileSystem("d:\\"+file.filename());
            });
            request.response().sendFile("./webroot/index.html");
        });
-----------------------------------------------------------------
But it won't work when using HTTP2 , unless :
server.requestHandler(request->{
            request.setExpectMultipart(true);
            request.uploadHandler(file->{
                file.streamToFileSystem("d:\\"+file.filename());
            });
            request.endHandler(aVoid -> {
                request.response().sendFile("./webroot/index.html");
            });
        });

**Comment by tsegismont** [comment]
Can you please post your question to the Vert.x forum? See https://vertx.io/community. Thanks
