### ISSUE TITLE
Sequential composition in vertx from list of items

### ISSUE THREAD

**Issue by onthegit** [eclipse-vertx/vert.x#3241]
I am trying to execute sequential composition of futures in Vertx Java. I have an array (it could also be a list with unknown number) that I need to loop through and call the db server via reactive mysql (that is on vertx) This is the code:
`
DbTransferRecord[] arrayData = new DbTransferRecord[4];

arrayData[0].setID(1);
arrayData[0].setName("John");
arrayData[0].setLastName("Smith");
arrayData[1].setID(2);
arrayData[1].setName("Johnas");
arrayData[1].setLastName("Smith");

int arrayDataLength = arrayData.length;

for (int i = 0; i < arrayDataLength; i++) {
dbSaveData(arrayData[i].getId(), arrayData[i].getName(). arrayData[i].getLastName());
}

public Future dbSaveData (id, name, lastName) throws Exception{
Promise = Promise.promise();
....
return promise.future();
}
`

I need to chain every call from dbSaveData sequentially,so if one of the calls to db fails, a handler should be called to clean up (rollback) the data. The documentation is very limited. I could not find how to create sequential composition from list, and I could not understand it enough from the information I found on stackoverflow and the internet. Thank you.

**Comment by tsegismont** [comment]
A solution has been proposed on SO: https://stackoverflow.com/questions/53207723/sequential-composition-for-arbitrary-number-of-calls-in-vertx-with-futures
