### ISSUE TITLE
CompositeFuture multiple handlers not working

### ISSUE THREAD

**Issue by tnolli** [eclipse-vertx/vert.x#3242]
It looks like CompositeFuture is not supporting multiple handlers as implemented for "regular" futures in #3174 

Reproduced on both 3.8.4 and 4.0.0-milestone4

The following code is calling the onSuccess handler (because it is the last that was added) and is not calling the onFailure handler.
```java
	public static void main(String[] args)
	{
		Promise<Integer> p1 = Promise.promise();
		Promise<Integer> p2 = Promise.promise();
		
		CompositeFuture.all(p1.future(), p2.future())
			.onFailure(t -> t.printStackTrace())
			.onSuccess(cf -> System.out.println("Completed"));
		
		p1.complete(1);
		p2.fail(new RuntimeException("FAILED"));
	}
```
The following code is calling the onFailure handler (because it is the last that was added) and is not calling the onSuccess handler.
```java
	public static void main(String[] args)
	{
		Promise<Integer> p1 = Promise.promise();
		Promise<Integer> p2 = Promise.promise();
		
		CompositeFuture.all(p1.future(), p2.future())
			.onSuccess(cf -> System.out.println("Completed"))
			.onFailure(t -> t.printStackTrace())
			;
		
		p1.complete(1);
		p2.complete(2);
	}
```

The invoked handlers do not print anything on screen because of these guards (example for onSuccess):
https://github.com/eclipse-vertx/vert.x/blob/5a585a1a620d4c53e1c64895e3543d09978de03a/src/main/java/io/vertx/core/Future.java#L128-L134

**Comment by vietj** [comment]
good catch :-)
