### ISSUE TITLE
HttpServer continues processing requests after closing httpconnection

### ISSUE THREAD

**Issue by AngLi2** [eclipse-vertx/vert.x#3245]
It looks like httpserver will continue processing requests after closing httpconnection in #2542 

We closes the connection in connectionHandler when a new connection happens above the limit. But the requestHandler will continue processing.

So for the client side, it won't get any response because of the closed connection but the httpServer has already handled the request, which is out of our expectations.

I want to stop processing any request after the httpconnection closed, any good idea?

Thanks

**Comment by vietj** [comment]
can you provide a reproducer example ?

**Comment by AngLi2** [comment]
Here is a example:
```java
HttpServer httpServer = createHttpServer();
httpServer.requestHandler(mainRouter);
httpServer.connectionHandler(connection -> {
    if (connectionCount > connectionLimit) {
        connection.close();
    }
});
```
We expect the requestHandler not to handle the request if the connection closed. But it will still handle the request. Any good idea to deal with that?

**Comment by vietj** [comment]
it seems like a bug, we should check the connection is not closed after the handler has been called.
