### ISSUE TITLE
OpenSSLEngineOptions Parameters

### ISSUE THREAD

**Issue by sbhv13** [eclipse-vertx/vert.x#3248]
How can we configure OpenSSLEngineOptions in a way that it calls specific openssl-engine ( such as pkcs11 from a configuration) and is it possible to give option that it establishes ssl connection with the private key stored in the hsm device. 

More information about the problem can be found in the link: 
https://stackoverflow.com/questions/59631596/ssl-connection-with-private-keys-in-hsm

Thanks.

**Comment by vietj** [comment]
can you ask this questions in vertx google group forum ? thanks
