### ISSUE TITLE
When the debug mode is running, the breakpoint does not take effect.

### ISSUE THREAD

**Issue by qinfensky** [eclipse-vertx/vert.x#3259]
### Questions

I downloaded the kotlin project on the official starter, and then I set breakpoints in IDEA with gradle, which did not take effect when debug mode was running. Could you tell me how to solve it?

### Version

4.0.0 milestone 4

### Context

None

### Do you have a reproducer?

None

### Extra

* Anything that can be relevant such as OS version, JVM version

JVM: 13 OS: MacOS 10.15.2 IDEA:2019.3.2

**Comment by vietj** [comment]
this is plain java, it should just work, can you double check ?
