### ISSUE TITLE
Eventbus error is not reported anymore to the metrics SPI

### ISSUE THREAD

**Issue by jotak** [eclipse-vertx/vert.x#3270]
I "fixed" a broken integration test in micrometer metrics because it expected an eventbus error to be reported in metrics: https://github.com/vert-x3/vertx-micrometer-metrics/pull/94

This "fix" is necessary to not block builds on master, but the root cause is not fixed and is probably in vertx-core.

To reproduce, we can just revert my change on VertxEventBusMetricsTest.java and run the test.

**Comment by vietj** [comment]
@jotak can you provide a test for vertx-core ?

**Comment by jotak** [comment]
@vietj with a little help, probably! :)
I'd need to inject a dummy/mocked metrics SPI in order to check if the error hook is called ... what's the way to do that in vertx? with mockito?

**Comment by vietj** [comment]
there are existing tests in vertx that provide something to do that, look at Fake***Metrics classes

**Comment by jotak** [comment]
Closing, as this was intentional ; see also https://github.com/vert-x3/vertx-micrometer-metrics/commit/f369f39c20c120103a65701e9f689d197c97465d
