### ISSUE TITLE
NetSocketImpl Bug

### ISSUE THREAD

**Issue by huchaogithup** [eclipse-vertx/vert.x#3271]
class NetSocketImpl.handler(Handler<Buffer> handler) handler throw Exception and  no print Exception on console

**Comment by vietj** [comment]
can you show some code ? or better provide a reproducer ?

**Comment by vietj** [comment]
or a stack trace exception

**Comment by huchaogithup** [comment]
`package com;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Vertx;
import io.vertx.core.net.NetServer;
import io.vertx.core.net.NetServerOptions;

public class NetDemo extends AbstractVerticle {

    @Override
    public void start() throws Exception {
        vertx.getOrCreateContext().exceptionHandler(Throwable::printStackTrace);
        final NetServer netServer = vertx.createNetServer(new NetServerOptions().setIdleTimeout(10).setPort(80));
        netServer.exceptionHandler(Throwable::printStackTrace);
        netServer.connectHandler(netsocket->{
            netsocket.exceptionHandler(Throwable::printStackTrace);
            netsocket.handler(data->{
                System.out.println("data.... error");
                throw new RuntimeException("error");
            });
        });
        netServer.listen();

    }

    public static void main(String[] args) {
        Vertx.vertx().deployVerticle(new NetDemo());
    }
}
`

this is demo , running it and  just print "error...data" no print any RunTimeException

**Comment by huchaogithup** [comment]
sorry  "data.... error"

**Comment by vietj** [comment]
did you configure logging properly ?

**Comment by huchaogithup** [comment]
no,but all of exceptionHandler() set Throwable::printStackTrace ， HttpServer can print  Exception and NetServer no printing。Code trace is not set exceptionHandler on class InboundBuffer by debug ,but  There's no way to configure it

**Comment by vietj** [comment]
I see what you mean, it's a good thing to indeed do.

**Comment by huchaogithup** [comment]
Thank you for your approval. I like vert. X very much. It's a very good reactive frame
