### ISSUE TITLE
Simplify EventBusMetrics message delivery callback

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#3277]
Currently when a message is delivered to an handler, two callbacks are done (before and after). This is simplified to a single callback (`messageDelivered`) to simplify since there practically not much value having two callbacks.

**Comment by vietj** [comment]
cc @jotak

**Comment by vietj** [comment]
I'll push an update in micrometer metrics that coalesces the two callback in a single and I'll let you change the timer metric for a counter metric

**Comment by praetp** [comment]
This prevents measuring how long message delivery processing took...

**Comment by vietj** [comment]
in practice the message processing is

- either very fast
- performs an asynchronous operation and in this case you are only measuring the time it takes to forward the message
- is a computation and in this case it is a problem because it will affect application performance

So there is really no much value in measuring this time.
