### ISSUE TITLE
Vert.x 4 milestone 4 Web Client maxPoolSize

### ISSUE THREAD

**Issue by qinfensky** [eclipse-vertx/vert.x#3284]
I am using Vert.x 4 milestone 4, I am using Web Client. 
My server program needs to request a third-party HTTP service in a request, and the performance index of my server program is: Requests per second: 9.44 [# / sec] (mean). In the stress test. 
I checked the configuration parameters of Web Client. Found the maxPoolSize parameter, I set it to 20 (I did not find the upper and lower limit of this value), there is no significant improvement in the performance metrics, what can I do to support more HTTP requests at the same time?

**Comment by qinfensky** [comment]
I cleared the cache and restarted the machine. MaxPoolSize took effect. I set it to 1000. what is the upper limit of this value? How much should it be set normally?

**Comment by vietj** [comment]
@qinfensky this value is limited by your local TCP ports and the remote server (some servers might restrict the number of concurrent HTTP requests you can do).

if you can use HTTP/2 then it shall improve it.
