### ISSUE TITLE
CassandraClient.executeWithFullFetch doesn't return all rows

### ISSUE THREAD

**Issue by mafa73** [eclipse-vertx/vert.x#3288]
### Version

3.8.5

### Context

I have a Cassandra database with 7000 rows. When I query them all only 2000 are returned. I've tested with different fetch sizes. When using fetch size >= 7000 it works fine.

It is the last 2000 rows that are returned.

Looking into the code I can see that CassandraClientImpl calls ResultSetImpl.all. I believe I have found the bug in this method:

`private void loadMore(Context context, List<Row> loaded, Handler<AsyncResult<List<Row>>> handler) {
    int availableWithoutFetching = resultSet.getAvailableWithoutFetching();
    List<Row> rows = new ArrayList<>(loaded.size() + availableWithoutFetching);
    for (int i = 0; i < availableWithoutFetching; i++) {
      rows.add(resultSet.one());
    }

    if (!resultSet.isFullyFetched()) {
      handleOnContext(resultSet.fetchMoreResults(), context, ar -> {
        if (ar.succeeded()) {
          loadMore(context, rows, handler);
        } else {
          handler.handle(Future.failedFuture(ar.cause()));
        }
      });
    } else {
      handler.handle(Future.succeededFuture(rows));
    }
  }`

The problem is that the loaded rows aren't added to the rows list (just the size is added).
I believe adding this row after the rows instantiation will solve this bug
`rows.addAll(loaded)`

### Do you have a reproducer?

`
import io.vertx.cassandra.CassandraClient;
import io.vertx.core.Vertx;
import lombok.SneakyThrows;

public class CassandraTest {

    @SneakyThrows
    public static void main(String[] args) {
        Vertx vertx = Vertx.vertx();
        CassandraClient cassandraClient = null;
        try {
            cassandraClient = CassandraClient.create(vertx);

            cassandraClient.executeWithFullFetch("SELECT * FROM <keyspace>.<table>", ar -> {
                if (ar.succeeded()) {
                    System.out.println("Number of rows fetched: " + ar.result().size());
                } else {
                    System.out.println("Failed to fetch: " + ar.cause());
                }
            });

            Thread.sleep(5000);
        } finally {
            if(cassandraClient != null) {
                cassandraClient.close();
            }
            vertx.close();
        }
    }
}`

### Steps to reproduce

1. Add 7000 rows to Cassandra
2. Run the CassandraTest code above
3. Number of rows fetched: 2000 is printed

**Comment by tsegismont** [comment]
Can you please file this on the Cassandra Client repo? Thanks

https://github.com/vert-x3/vertx-cassandra-client/issues/new

**Comment by mafa73** [comment]
ok, I will do that
