### ISSUE TITLE
Rename Buffer toJsonXXX() to mapToJsonXXX()

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#3289]
The `Buffer` interface defines these methods:

- `toJsonObject()`: parse the buffer content as a JSON object
- `toJsonArray()`: parse the buffer content as a JSON array
- `toJson()`: parse the buffer content as a JSON element or value

These methods are actually mapping methods a JSON element or value according whose type depends on the content of the buffer. The `toJson()` method convention is actually used to encode data objects to their JSON representation. e.g for a buffer it would actually encode a base 64 representation of the content like `JsonObject` does. The `toJson()` method will likely be changed in Vert.x 4 to return an encoded base 64 String.

**Comment by jlengrand** [comment]
Hey there,

I assume the rename should be done in two steps? Deprecation and creation of a new method with the same signature but new name, and removal later in the future?

**Comment by jlengrand** [comment]
Hey, 

I created https://github.com/eclipse-vertx/vert.x/pull/3296 as an attempt to help. 

It's my first PR on this project so feel free to let me know if I've done anything wrong. 
I chose to duplicate the logic and deprecate the current methods but I'm happy to change that if needed.

I'm also considering adding a test to the `mapToJson` method, it currently has none.

**Comment by jlengrand** [comment]
Running in some problems signing the agreement :).

`
×
Error message
There was a problem with your form submission. Please wait 11 seconds and try again.`

**Comment by jlengrand** [comment]
Problems with pre-checks fixed. Updated the PR

**Comment by vietj** [comment]
it's not yet 100% sure we will do that. In practice this is not needed, so this should be done if it makes enough sense (I believe it does some)

**Comment by vietj** [comment]
let us know what is your opinion ?

**Comment by vietj** [comment]
thanks @jlengrand actually it is not 100% needed, so we need to figure out on the issue whether we want this or not

**Comment by jlengrand** [comment]
Hey there, understood. 

This was a way for me to jump head first into vert.x so it's really ok if it doesn't get merged :).

My opinion depends mainly on how much Buffer interface is used by the users. If it's a public API, maybe it's worth living with a less than perfect naming. 
If it is not, change is rather cheap and seems to make some sense, at the cost of short term duplication :).

If you see other accessible issues to be worked on feel free to let me know :).

Cheers

**Comment by vietj** [comment]
@jlengrand thanks for your feedback, there are other issues open in https://github.com/vert-x3/ repos for you to contribute to.

As for this issue, a few weeks ago this issue was necessary because we wanted to have `toJson()` method for some vertx objects (those annotated with `@VertxGen` such as `Buffer`), but finally we implemented this PR https://github.com/vert-x3/vertx-codegen/pull/290 which allows to provide a way to use it with a declaration in a property file.

So as you said, we might keep it or change it and perhaps indeed it does not have to be perfect and avoid renaming in 4.0

**Comment by vietj** [comment]
we decided to not go forward with this change
