### ISSUE TITLE
Websocket ping message shouldn't trigger handler

### ISSUE THREAD

**Issue by korektur** [eclipse-vertx/vert.x#3290]
### Version

3.8.5

### Context

Seems that vertx websocket ping message handling changed with 3.8.0 release. 
Before 3.8.0  - ping messages weren't triggering handler to be called.
After 3.8.0 - when websocket ping message received websocket handler would be called.
Is it a bug or an intended change?

### Do you have a reproducer?

Server:
```
        vertx.createHttpServer()
                .websocketHandler(ws -> {
                    ws.handler(buf -> {
                        System.out.println("RECEIVED: " + buf.toString());
                        ws.write(buf);
                    });
                })
                .listen(8080);

```
Client:
```
       vertx.createHttpClient().websocket(8080, "localhost", "/test", ws -> {
            ws.writePing(Buffer.buffer("PING"));
            ws.writeTextMessage("MESSAGE");
        });
```

Server output with **3.8.0+**:

> RECEIVED: PING
> RECEIVED: MESSAGE

with **3.4-3.7**:

> RECEIVED: MESSAGE

### Steps to reproduce

1. run server verticle
2. run client verticle

**Comment by dgoetsch** [comment]
I think this is something I changedabout 2.5 years ago. I had to add handling for ping messages so that I could detect client timeouts and close dead connections.

Maybe this is unrelated, but that's the only real use case for these messages. If timeout can be configured elsewhere, no need to get a heboing messages here.

**Comment by dgoetsch** [comment]
Found the commit, it was in 3.5.0

https://github.com/eclipse-vertx/vert.x/commit/849bf49af35c1375b365322b9933b3bd3f4b510e

And here is the PR https://github.com/eclipse-vertx/vert.x/pull/2107

It is worth noting, that before this PR pong responses were not sent.

**Comment by korektur** [comment]
@dgoetsch Yes, ping messages were added in 3.5.0 I think, but, as I mentioned earlier, handler behaviour changed bettween 3.7 and 3.8, starting from 3.8 it's trigger for every ping message, which doesn't match ping documentation I think. I see that handling messages changed with 3.8 release.

**Comment by vietj** [comment]
@korektur I think indeed you should not receive the buffer ping, the ping only should be received if you set a frame handler

**Comment by korektur** [comment]
@vietj I can make a PR with the fix, if you agree that this is a bug.

**Comment by vietj** [comment]
@korektur thanks, I agree this is a bug, however I'll do the fix myself as I would like to actually handle a bit more than only this bug by applying the back-pressure pending queue to all handlers and not only buffers.

**Comment by vietj** [comment]
fixed by https://github.com/eclipse-vertx/vert.x/commit/763b9b55941c02df820528e311ff21c0181335d8
