### ISSUE TITLE
io.vertx.core.file.impl.FileResolver.resolveFile() has a bug

### ISSUE THREAD

**Issue by yn-tadpole** [eclipse-vertx/vert.x#3295]
Questions
io.vertx.core.file.impl.FileResolver.resolveFile(fileName) use a ClassLoader to resolve resource. It always return null when getResource() has been called. Because the fileName which send to resolveFile alway starts with '/'.

The resolveFile method will been used in StaticHandler and HttpServerResponse.

It will cause an error when sending the file to the client, the first time it is called, and the subsequent time it will not see an error because it reads from the cache and did not execute getResource
This leads to program instability.

Version
3.8.5

Context
resolveFile:143, FileResolver (io.vertx.core.file.impl)
resolveFile:805, VertxImpl (io.vertx.core.impl)
:933, FileSystemImpl$20 (io.vertx.core.file.impl)
existsInternal:932, FileSystemImpl (io.vertx.core.file.impl)
exists:340, FileSystemImpl (io.vertx.core.file.impl)
lambda$isFileExisting$2:283, StaticHandlerImpl (io.vertx.ext.web.handler.impl)
call:-1, 1512148561 (io.vertx.ext.web.handler.impl.StaticHandlerImpl$$Lambda$234)
wrapInTCCLSwitch:266, StaticHandlerImpl (io.vertx.ext.web.handler.impl)
isFileExisting:283, StaticHandlerImpl (io.vertx.ext.web.handler.impl)
sendStatic:192, StaticHandlerImpl (io.vertx.ext.web.handler.impl)
handle:145, StaticHandlerImpl (io.vertx.ext.web.handler.impl)
handle:51, StaticHandlerImpl (io.vertx.ext.web.handler.impl)

Do you have a reproducer?
See the source code, everything is there.

Extra
OS: Windows 10
JVM: OpenJDK 12

**Comment by yn-tadpole** [comment]
As mentioned earlier, it may not be a bug, but it may be worth improving.

Further analysis of the source code found that StaticHandler called getFile to convert the path before calling sendFile(), but when using the reroute of the RoutingContext, the conversion did not work properly.

At the same time, response().sendFile() doesn't work properly in the path starting with "/" is not a good choice.

It is recommended to change the path start with '/' before ClassLoader calling getResource().

**Comment by pmlopes** [comment]
This issue is addressed by the linked PR. The contract has been defined that only relative resources (or absolute in the cache directory misses) are going over the resolver.
