### ISSUE TITLE
JsonObject does not exist in node_modules/@vertx/core

### ISSUE THREAD

**Issue by UglyHobbitFeet** [eclipse-vertx/vert.x#3298]
I am trying to follow any basic example here:
   https://vertx.io/docs/vertx-config/js/#_additional_formats

If I do the following:

```
import { ConfigRetriever } from '@vertx/config';
import { ConfigStoreOptions } from '@vertx/config/options';
import { JsonObject } from '@vertx/core';
const fileStore = new ConfigStoreOptions().setType("file").setConfig(new JsonObject().put('foo', 'bar'));
```

I will get an error that JsonObject is not found.

If I look at the @vertx/core/index.js file I can clearly see it missing.

FWIW I tried another way and seem to have gotten a workaround, but JsonObject should still be exposed for other use cases.

The workaround can be found here: https://github.com/eclipse-vertx/vert.x/issues/3308

**Comment by pmlopes** [comment]
Hi, I think you're trying to use es4x. For most cases you don't need the jsonobject type, a automatic conversion should happen from native js JSON to jsonobject or jsonarray.

Can you verify that works:

```js
const fileStore = new ConfigStoreOptions()
  .setType("file")
  .setConfig({foo: 'bar'});
```

But anyway I think exposing the vert.x types could be useful too.

**Comment by UglyHobbitFeet** [comment]
Yes, your example is similar to what I've done to get around that. I seem
to recall that there was some call/method where I had to explicitly deal
with a JsonObject, but I cannot remember it offhand...   Somewhat related,
but I should point out that even though this works, it leads to the bigger
issue about the multithreading error I posted here.
https://github.com/vert-x3/vertx-config/issues/113

**Comment by pmlopes** [comment]
I've added a issue to track this here: https://github.com/reactiverse/es4x/issues/305

I'll close this one as it's not related to this repo.
