### ISSUE TITLE
Adding context-euality-check-methods

### ISSUE THREAD

**Issue by knotenpunkt** [eclipse-vertx/vert.x#3300]
vertx 4

this topic is related to this one: https://github.com/eclipse-vertx/vert.x/issues/3198

We should have methods like this:

**context.checkContextFamilyEquality(otherContext);**
-> its true if the context is related to otherContext, cause one of them is a duplicated one of the other one

**context.checkThreadEquality(otherContext)**
-> its true if both live in/on the same-eventloopthread/same-thread.

it capsulate code like this: ctx.nettyEventLoop().inEventLoop()
if it changes in the future, we dont have to adjust these code snippet in x-files of the vertx project, but only in one^^
=> And also its a better code design, not relying on concrete implementations but on abstractions^^

**context.checkEquality(otherContext)**
-> its true if context==otherContext

lg knotenpunkt

**Comment by knotenpunkt** [comment]
@vietj a comment why it should be invalid?

**Comment by hutchig** [comment]
@knotenpunkt not wishing to speak for anyone else but from
reading around this topic today and in the spirit of trying to be helpful I can point you towards:
https://groups.google.com/d/msg/vertx/LiOpb60PsVI/ue2Pg31JAAAJ which has
"you should use runOnContext() for an application because it is simple and will be performant, you don't need to check any equality in your code." which may provide an answer to your question.

**Comment by knotenpunkt** [comment]
@hutchig i think thats not correct.

the runOnContext-Method always switch the context to the context the method is called-on.
If i am on Context A and  call A.runOnContext then i have an un-necessary switch to the same context.

If you take a look into the internals, then you would see, that a runOnContext pushes the lambda to mpsc-queue. The queue has internally a volatile read/read -> flushing the cpu-caches, it also prevents compiler-optimiziations it prevens reordering code-instructions.

-> So for this reasons and other one its slower

If you take a look, on some other internal stuff from vertx then you would see these context-equality-checks too.
The reactive-sql-client for example, if you use it always from one context, then it would internally not change the context (with runOnContext) to the same Context^^

lg knotenpunkt
