### ISSUE TITLE
Invalid docs for passing options to createHttpServer

### ISSUE THREAD

**Issue by UglyHobbitFeet** [eclipse-vertx/vert.x#3304]
I'm trying to follow the basic example here: 
 https://vertx.io/docs/vertx-core/js/#_configuring_an_http_server

Which shows:
```
var options = {
  "maxWebSocketFrameSize" : 1000000
};

var server = vertx.createHttpServer(options);
```
I am using Vue, and I place that code in my index.js file.  When I do an _npm run build;npm start;_ I see the following error in the logs

```
Failed in deploying verticle caused by TypeError: invokeMember (createHttpServer) on JavaObject[io.vertx.core.impl.VertxImpl failed due to: no applicable overload found
(overloads: [
Method[public io.vertx.core.http.HttpServer io.vertx.core.impl.VertxImpl.createHttpServer(io.vertx.core.http.HttpServerOptions)],
Method[public io.vertx.core.http.HttpServer io.vertx.core.impl.VertxImpl.createHttpServer()],
], arguments: [DynamicObject<JSUserObject> (DynamicObjectBasic)])
```

It seems to work when I do:
```
import { HttpServerOptions } from '@vertx/core/options';
var server = vertx.createHttpServer(new HttpServerOptions().setMaxWebsocketFrameSize(1000000));
```

I suggest updating the docs to reflect the correct way to do it

**Comment by vietj** [comment]
can you give a link to the doc that mentions that ?

**Comment by UglyHobbitFeet** [comment]
The link is in the first line of the original post :)

**Comment by pmlopes** [comment]
the `js` docs on the main site are related to `vertx-lang-js` and not `es4x`. There's now a early attempt to generate the proper docs for es4x in the es4x site.

**Comment by UglyHobbitFeet** [comment]
Can we at least modify the top of the existing doc to state that it is only for vertx-lang-js and not ES4X? Possibly providing links for ES4X versions?  I feel like I wasted a lot of time not knowing that and that others will do the same.
