### ISSUE TITLE
Adding Timeout-(handler-based)-method to Future/Promise

### ISSUE THREAD

**Issue by knotenpunkt** [eclipse-vertx/vert.x#3307]
vertx 4 (feature request)

the following method we should add to the Future-Interface: 
**public Future<T> onComplete(Handler<AsyncResult<T>> h, long timeout)** 

its easy to implement. We wrap in that method the handler into a TimeoutHandlerWrapper.

Take a look to my detailed informations in google-groups: https://groups.google.com/forum/#!topic/vertx-dev/r-0y-SzELzU

lg knotenpunkt

**Comment by vietj** [comment]
this is not needed currently, people needing more elaborated solution can use rx-java instead or use their own timer.
