### ISSUE TITLE
Critical CVEs in jackson-databind

### ISSUE THREAD

**Issue by watzkej** [eclipse-vertx/vert.x#3321]
### Version
Vertx 3.8.5

### Context
Found via OWASP dependency check

### Do you have a reproducer?
NVD link has details on all issue from jackson-databind 2.9.9.  It appears jackson-databind 2.9.10.3 will cover all of these issues.

NVD: https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Afasterxml&cpe_product=cpe%3A%2F%3Afasterxml%3Ajackson-databind&cpe_version=cpe%3A%2F%3Afasterxml%3Ajackson-databind%3A2.9.9

**Comment by vietj** [comment]
well we should wait a little, I'm pretty sure that by a couple of weeks at least one more vuln will be discovered :-)

**Comment by vietj** [comment]
we are planning upgrade to jackson 2.10.2 for Vert.x 3.9.0, unless I'm wrong this version does not seem affected

**Comment by vietj** [comment]
see https://github.com/vert-x3/issues/issues/518
