### ISSUE TITLE
Static resources are not served when browsing through SSL/TLS

### ISSUE THREAD

**Issue by pascalav** [eclipse-vertx/vert.x#3323]
### Version

3.8.4

### Context

At work, I'm developing a web application based on Vert.x: a main verticle that spawns 2 verticles. One for a RESTful API (with internal and public endpoints), and one for UI (static resources, among which a bundled ReactJS front app).

An end-user request transits through those architecture tiers: (HTTPS) 1x Microsoft IIS SSL-enabling frontend --> (HTTP) 1x authentication gateway --> (HTTP) 1x Vert.x app.

When upgrading from Vert.x `3.7.1` to Vert.x `3.8.4` with minimal compilation-required changes (i.e. resolving the new Vert.x `Promise`s into app well-known `Future`s), I observe a consistent regression when accessing https://myhost.mydomain/myappcontextpath/foofileinsidewebroot.html from outside the Vert.x app host machine:
* Firefox states a `PR_CONNECT_RESET_ERROR`, therefore gets no response from the server
* Visually in the browser taskbar, the SSL handshake phase seems to enter a looping-behavior ("Establishing TLS connection..", "TLS connection established.", looping ~5 times, what is observed only once when page loads properly)
* (may be unrelated) In the browser network monitoring tools: the TLS handshake phase takes longer than usual, and `HSTS` (HTTP Strict Transport Security) appears disabled (in our setup, it's enabled when page loads properly)
* In the Vert.x app request logs, I see the request, I see an HTTP 200 Ok response status, and I see the proper response size
* (may be unreliable due to logging misconfiguration in my app) The app logs state no error message nor exception stacktrace. Parameterizing logging to full-verbose outputs nothing more in logs

Reverting changes and downgrading to `3.7.1` extinguishes the issue.

Alternatively, regression is worked around by replacing the `StaticHandler` (i.e. `router.route().handler(StaticHandler.create());`) with this impl: [CustomStaticHandlerServiceImpl_java.txt](https://github.com/eclipse-vertx/vert.x/files/4298008/CustomStaticHandlerServiceImpl_java.txt)

### Do you have a reproducer?

No

### Steps to reproduce

1. Build and deploy a Vert.x app using the `StaticHandler` and having a `foofileinsidewebroot.html` file dropped in the Vert.x default `webroot` directory
2. Have a Microsoft IIS front with SSL-enabled (may reproduce with any web server), ideally on another host
3. Have this front pointing to your Vert.x app HTTP (non-secured) URL
4. From a public machine, browse https://myhost.mydomain/myappcontextpath/foofileinsidewebroot.html in Firefox, and assert: that you get a PR_CONNECT_RESET_ERROR

### Extra

* I realize this _issue is not fully narrowed down and debugged, therefore not easily reproductible most probably_. It's **intended as an "heads up" ticket**, in case the Vert.x developers may think of anything related to that regressive behavior
* Updating to Vert.x 3.8.5 didn't solve the issue
* When running the Vert.x app locally and accessing it directly (i.e. http://127.0.0.1:myappport/foofileinsidewebroot.html), issue is not reproduced. The same observation is made when performing a local attempt from the deployment machine. As such, issue is definitely SSL-related
* When running in the bug context, where the UI static resource URL is not reachable, the public API endpoints still are: so the app-defined Vert.x `router` routes didn't fully regressed
* The suggested workaround duplicates parts of the `StaticHandler` (reading the static files directory, writing the HTTP response headers, writing a file in the HTTP response body). As such, it disqualifies a regression cause in Netty?
* In the Vert.x revisions, I see no changes made to the `StaticHandler` between version `3.7.1` and `3.8.4`, so the problem would occur deeper in the Vert.x classes?
* Due to a tight schedule, I didn't go deeper:
> * Didn't attempt to configure app into a debug mode in order to remotely attach a debugger, having our operations team to manage security/access/routing for the debugging port
> * Didn't attempt with in-between Vert.x releases (`3.8.0`, `3.8.1`, `3.8.2` and `3.8.3`) in order to identify when it regressed
> * Didn't attempt to monitor the network trafic on the architecture tiers (with Wireshark or any other monitoring tool)

**Comment by vietj** [comment]
can you re-open this issue on https://github.com/vert-x3/vertx-web ?

**Comment by pascalav** [comment]
Sure. Issue as reopened in the vertx-web project: https://github.com/vert-x3/vertx-web/issues/1542
