### ISSUE TITLE
a future should support cancellation

### ISSUE THREAD

**Issue by encodeering** [eclipse-vertx/vert.x#3334]
### Questions

I like the introduced state splitting between promises and futures in the upcoming 4.x version. I was just reasoning how we can escalate an exception back to the code that is running/backing the future without a signature to ask for it.

Reference to Java 

https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Future.html#cancel(boolean)

### Version

4.0.0-milestone4

### Context

We are currently (miss) using the `tryFail` signature to signal an exception to the executing code and ask for an interrupt.

Possible use cases

* resource management to abort non relevant processes
* graceful shutdown of running processes

### Do you have a reproducer?

Migration to 4.x would lead to a compilation error

**Comment by vietj** [comment]
Unfortunately this is not something we want to support in Vert.x, we cannot guarantee that cancellation can be reliably supported. Java's `Future` cancellation has been designed for local long running computations and is not much adapted to non local (i.e protocols) signals.

Your code should be adapted to support cancellation and have this be part of the API instead.

**Comment by encodeering** [comment]
You may not need to provide a mechanism to handle the `boolean mayInterruptIfRunning` cases, but may provide a more lightweight mechanism like

https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/kotlin.coroutines.-coroutine-context/cancel.html

that allows to pass an exception down the chain, to be fetched by the handlers as part of the future pipeline. Having at least one behavior compatible option compared to `tryFail` would make the application API design a way easier, especially for building blocks like facades and so on.

I think the costs are lower if vertx as toolkit provides a way to cancel or fail a future than writing this as part of all applications.

Would be glad if you could think about how to keep an exception based solution as part of the framework.

**Comment by vietj** [comment]
@encodeering it is still not clear what is the case you want to implement, can you elaborate a very simple example ?

**Comment by encodeering** [comment]
hey, yes of course, will do so - just don't have the time today.

**Comment by encodeering** [comment]
Hi @vietj,

came up with some examples, the first one showing a general approach on how this can be handled by the end users API, but still supported through a future:

```
    fun fetch (): Future<Int> {
        val promise = Promise.promise<Int> ()

        val job = GlobalScope.async {
            delay (10000)
            promise.complete (42)
        }

        return promise.future ().onComplete {
            if (it.cause () is CancellationException)
                job.cancel ()
        }
    }

    fetch ().tryFail (CancellationException ()) // future.cancel ()
```

GlobalScope is just for this example and cancellation handling needs to be implemented in a cooperative manner.

We are also using an [ExecutorService](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ExecutorService.html) as integration with other libraries, e.g Apache Camel, to offload tasks on the worker pool.

The following example is not complete, but having a cancel signature on Future would make implementations like this easier to write:

```
    class VertxExecutorService: AbstractExecutorService() {

        private val submissions = ConcurrentHashMap<Int, Future<*>> ()

        override fun shutdownNow (): List<Runnable> {
            shutdown ()

            submissions.values.forEach {
                it.tryFail (CancellationException ()) // future.cancel ()
            }

            return emptyList ()
        }

    }
```

A last example is taken from Vertx Coroutine library and modified to bridge cancellation requests, as this is currently also not fully supported:

```
    // VertxCoroutine.kt

    suspend fun <T> Future<T>.await(): T = when {
      succeeded() -> result()
      failed() -> throw cause()
      else -> suspendCancellableCoroutine { cont: CancellableContinuation<T> ->
        val future = setHandler { asyncResult ->
          if (asyncResult.succeeded()) cont.resume(asyncResult.result() as T)
          else cont.resumeWithException(asyncResult.cause())
        }
        cont.invokeOnCancellation { future.tryFail (CancellationException ()) } // future.cancel ()
      }
    }
```

Kotlin has also implemented Cancellation as [cooperative task](https://kotlinlang.org/docs/reference/coroutines/cancellation-and-timeouts.html#cancellation-is-cooperative) and handles CancellationException as part of the regular control flow.

```
typealias CancellationException = java.util.concurrent.CancellationException
```

Vertx future based API could already handle a `parent-child` relation (e.g compose,map), which means that it should be possible to add a complete handler in a similar way that is shown by the first example, as multi listener support has been implemented in 4.x. There might of course be more efficient implementations. 

I saw that 4.x will also support a conversion to the CompletableFuture API and as both implementations are covered by Vertx, it should be possible to also handle cancellation requests back and forth.

I hope this gives a bit more clarity. Cheers
