### ISSUE TITLE
Improve JavaDocs for `Future.otherwise` and `Future.recover`

### ISSUE THREAD

**Issue by InfoSec812** [eclipse-vertx/vert.x#3340]
### Version

3.8.5

### Context

When attempting to use `Future.otherwise` and `Future.recover` it was not clear what the intended differences were meant to be.

### Do you have a reproducer?

No, N/A

### Extra

I intend to submit a PR with a proposed update to the JavaDocs and perhaps the Vert.x documentation in order to make the use of these methods more clear in a broader context.

**Comment by miere** [comment]
Any feedback on this. I came across the same issue and I'm not sure which of this two methods should be the preferred one in case of doubt. 🤔

**Comment by tsegismont** [comment]
`otherwise` replaces an error with a value (fixed or computed synchronously)

`recover` replaces an error with the result of another future (asynchronously)
