### ISSUE TITLE
Add a method to the RoutingContext to allow cleanup whenever a request ends

### ISSUE THREAD

**Issue by chrispatmore** [eclipse-vertx/vert.x#3351]
#### Describe the feature

When a request is received in a Vert.x server, you might open clients to perform tasks related to the call that was made. Those clients need to be closed when the response is sent or something goes wrong to prevent leaks. The solution could be implemented as discussed in https://groups.google.com/forum/?fromgroups=#!topic/vertx/B1AQUQrOn4Y

which is:

on vertx web RoutingContext we can add a method:

```java
addEndHandler(Handler<AsyncResult<Void>> handler)
```

This handler would attach to 3 core `HttpServerResponse` handlers:

1. `closeHandler` when the client just closes the connection
2. `exceptionHandler` when there's a socket IO error
3. `endHandler` when the response cleanly ends

This way it would behave just like the other `addXXXHandler()` methods already listed on the `RoutingContext`.

Currently using endHandler is insufficient as it gets overwritten if used somewhere else in the codebase for the same routingContext. Leading to the `add` terminology and behaviour

#### Use cases

A request comes in, and a client is opened to do some processing with the request. As soon as the client is opened `routingContext.addEndHandler(v -> client.close())` is called, so now the client is guaranteed to be closed when handling of the `routingContext` ends. the handler for this context then calls `next()` and the next handler opens a different client and again calls `routingContext.addEndHandler(v -> client.close())`, so that the second client is also guaranteed to be closed.

#### Contribution

@gmcrobert and I can work on implementing it with some guidance from someone more experienced with the codebase

**Comment by vietj** [comment]
can you create this feature to the vertx-web repository instead ? https://github.com/vert-x3/vertx-web
