### ISSUE TITLE
Add `then` method in Promise for GraalJS 

### ISSUE THREAD

**Issue by laiweiwei** [eclipse-vertx/vert.x#3359]
#### Describe the feature
```
public class Db {
    public void tx(Function<Transaction, Promise> fn) {
         Transaction tx = this.beginTransaction();
         Handler resolve = v -> { tx.commit(); };
         Handler reject = e -> { tx.rollback(); throw e; };
         
         Promise p = fn.apply(tx);
         p.future().onSuccess(resolve).onFailure(reject).onComplete(r -> tx.close());
    }
} 
```
// in java, every thing is perfect because we create a `PromiseImpl` instance to handle the future callback
```
// this is java code
db.tx(tx -> {
    Promise p = Promise.promise();
    ...
    return p;
});
```

// but in js (GraalJS or Nashorn), the async/await keyword will generate and return a JS Promise object which provide a `then` member method to be callback  
```
// this is js code
db.tx(async tx => { 
    const result = await jdbc.query(...);
    ...
});
```
// we get a JS Promise object in java runtime, it has no `.future()` method
```
Promise p = fn.apply(tx);
p.future()... // will throw exception here
```

// so, if our Promise interface has `.then(resolve, reject)` method, that will be nice for both Java and JS developer.

#### Use cases

ES4X, GraalJS, Nashorn

#### Contribution

I will do it

**Comment by vietj** [comment]
this should be added to ES4X directly, not in this project.

**Comment by pmlopes** [comment]
This is already present on `es4x`. The difference is that the addition happens to the `Future` type not to `Promise` type.

It may sound strange but there is a logic explanation. A JS `Promise` is a read only result that you shall receive in the future, so in reality it maps to vert.x `Future` type. A vertx `Promise` is the writable side of the object that will be a Future later on, which is not defined in `JS` and could be seen as the `executor` function passed to a JS `Promise`. However the executor function is opaque and not accessible from JS so this vert.x class is not enhanced.

**Comment by pmlopes** [comment]
This test shows how to mix `await`, js `Promise` and vert.x `Future` all together

https://github.com/reactiverse/es4x/blob/develop/es4x/src/test/resources/future/future3.js

**Comment by laiweiwei** [comment]
@pmlopes @vietj Thanks for the reply and all your great job!
Please let me explain more about this feature.
I have a Java method like this:
```
public doSth(Function<Object, Promise> fn) {
    Promise p = fn.apply(...);
    p.future().onSuccess(...)
}
```
This method will be called both in Java or JS.
It's good in java case to call this method, but strange in JS case. 

I can use Java.type('io.vertx.core.Promise').promise() which will create ES4XFuture instance by `SPI` as a parameter passed to Java method, and then call the '.future().onSuccess' the get the result.
```
hello(obj => {
    const p = Java.type('io.vertx.core.Promise').promise();
    jdbcClient.query(..., (asyncResult) => p.complete(asyncResult.result()))
    return p;
})
```
But as usually(this is what my expected), the js code will be like this : 
```
hello(obj => {
    const p = new Promise((resolve, reject) => {
        jdbcClient.query(..., (asyncResult) => resolve(asyncResult.result()));
    });
    return p;
})
``` 
Is it possible in ES4X ?
