### ISSUE TITLE
AbstractVerticle not havr starrt(Promise<Void> startPromise)

### ISSUE THREAD

**Issue by wanghaiwei** [eclipse-vertx/vert.x#3360]
### Version

>= 3.8.0

### Context

AbstractVerticle start method not have promise version.
The docs says breaking changes that future is deprecatedm, and tell us to change to Promise<Void>. but the AbstractVerticle class still use Future<Void>

**Comment by vietj** [comment]
it does : https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/AbstractVerticle.java#L105

**Comment by wanghaiwei** [comment]
but i use gradle and add the vertx with version 3.9.0
the source still use Future

**Comment by wanghaiwei** [comment]
it truly fixed in master branch, but not between 3.8.0 and 3.9.0

**Comment by vietj** [comment]
it is fixed in 3.9.0 and 3.9.0 is released

**Comment by vietj** [comment]
ah right it has been done after 3.9.0 is released, my bad

**Comment by wanghaiwei** [comment]
so what should i do to fix it now?
i use no param blocking method start currently

**Comment by vietj** [comment]
can you show your code @wanghaiwei ? it's not clear

**Comment by jponge** [comment]
I don't understand what is the exact problem either.

**Comment by wanghaiwei** [comment]
`package com.Rayfalling.verticle;

import com.Rayfalling.Shared;
import com.Rayfalling.router.MainRouter;
import io.reactivex.Single;
import io.vertx.reactivex.core.AbstractVerticle;
import io.vertx.reactivex.core.Promise;
import io.vertx.reactivex.core.http.HttpServer;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;


/**
 * 主启动类
 */
@SuppressWarnings("ResultOfMethodCallIgnored")
public class MainVerticle extends AbstractVerticle {
    private Logger logger = LogManager.getLogger("MainVerticle");
    
    @Override
    public void stop() {
        InnerStop(Promise.promise());
    }
    
    @Override
    public void start() {
        InnerStart(Promise.promise());
    }
    
    // Called when verticle is deployed
    private void InnerStart(Promise<Void> startPromise) {
        final String listenHost = config().getString("host");
        final Integer listenPort = config().getInteger("port");
        HttpServer server = vertx.createHttpServer();
        Shared.setHttpServer(server);
        server.requestHandler(MainRouter.getInstance().getRouter())
              .rxListen(listenPort, listenHost)
              .doOnError(error -> {
                  logger.fatal("Failed to listen at host " + listenHost + " port " + listenPort);
                  error.printStackTrace();
              })
              .doOnSubscribe(res -> {
                  logger.info("VerticleInstance: " +
                              Thread.currentThread().getId() +
                              ". Creating Http Server...");
              })
              .doAfterSuccess(res -> {
                  logger.info("VerticleInstance: " +
                              Thread.currentThread().getId() +
                              ". Server listened at host " + listenHost + " port " + listenPort);
              })
              .subscribe(res -> {
                  startPromise.complete();
              }, startPromise::fail);
    }
    
    // Called when verticle is undeploy
    private void InnerStop(Promise<Void> stopPromise) {
        Single.just(Shared.getHttpServer()).map(httpServer -> {
            httpServer.close();
            
            return null;
        }).doOnSubscribe(res -> {
            logger.info("Starting close HttpServer...");
        }).doOnSuccess(res -> {
            logger.info("HttpServer closed successful.");
        }).subscribe(res -> {
            stopPromise.complete();
        }, stopPromise::fail);
    }
}`

this is my verticle code.
should this wrap for promise right

**Comment by jponge** [comment]
You should use `start(Promise<Void> startPromise)` and put the code of `InnerStart` there. You complete `startPromise` when all initialization work has been done, and the code that deployed the verticle is notified of the completion.

**Comment by wanghaiwei** [comment]
I know that, but what i mean is that in version 3.9.0, you know in this release AbstractVerticle not have the method (you fix it in next release.
so can i do this in version 3.9.0?

**Comment by jponge** [comment]
That should be fixed in 3.9.1

**Comment by wanghaiwei** [comment]
thats ok
