### ISSUE TITLE
Provide Automatic-Module-Name attribute in MANIFEST.MF

### ISSUE THREAD

**Issue by afloarea** [eclipse-vertx/vert.x#3367]
#### Feature Description

Provide Automatic-Module-Name attribute in MANIFEST.MF file.

#### Use cases

Provides a reliable module name, instead of using the name derived from the JAR file, without having to target Java 9+ and/or use module-info java/class file. This can be used until there is a module-info file.

#### Contribution

If this feature request were to be approved I would be happy to work on it.

I believe that this change would require some additional configuration in the pom.xml maven jar plugin, something of this sort:

```

<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-jar-plugin</artifactId>
    <configuration>
        <archive>
            <manifestEntries>
                <Automatic-Module-Name>io.vertx.core</Automatic-Module-Name>
            </manifestEntries>
        </archive>
    </configuration>
</plugin>

```

The 'io.vertx.core' name seems most intuitive to me, but that is just my opionion. There are some [rules](https://sormuras.github.io/blog/2018-11-16-invalid-automatic-module-names) to take into accout when deciding on the module name to use.

### Additional notes

I apologize if some issue/discussion already exists for this. I was not able to find an issue for this topic. I did find discussions about JPMS support (module-info, split packages, moditect, etc), but not automatic module name.

**Comment by vietj** [comment]
@afloarea we are planning this for Vert.x 4, but we will have this issue rather in this tracker https://github.com/vert-x3/issues/issues/ for all modules of the stack

**Comment by vietj** [comment]
I think the most important part is to settle on the name to use

**Comment by afloarea** [comment]
@vietj thank you for such a quick response. I was not aware of that tracker.

Would you like me to open this issue there after I close it here?

If no one is currently working on this I could have go at it.

**Comment by vietj** [comment]
@afloarea yes you can open an issue here - before taking any action I would like that we settle upon a naming scheme and define it.

**Comment by afloarea** [comment]
@vietj I have created a [new issue](https://github.com/vert-x3/issues/issues/524) and I have included a proposal for the naming convention in the issue description, as per your suggestion. I look forward to your feedback.
