### ISSUE TITLE
Does EventBus have a unified message decoder for non-clustered environments

### ISSUE THREAD

**Issue by lygoing** [eclipse-vertx/vert.x#3375]
Now I have to write an encoder for each pojo, but they are only used in a non-clustered environment. Is there a better way? Thank you.

**Comment by vietj** [comment]
@lygoing sending pojo over the event bus has some requirements such as immutability or copy.

Pehraps we would make this easier by allowing pojo to implement Shareable interface to make a copy of it.

**Comment by lygoing** [comment]
@vietj  Thank you for your reply.
According to your suggestion, I implemented the Shareable interface of my pojo and canceled the registration of the message decoder. But the work failed. exception: `java.lang.IllegalArgumentException: No message codec for type: class provider.CacheEntry`

I tried two versions of `3.9.0` and `4.0.0-milestone4` and got the same exception.

pojo:
```
@Data
@AllArgsConstructor
public class CacheEntry<K, V> implements Shareable {

    private K key;
    private V value;
    private int ttl;

}

```

Eventbus Handle:

```

                EventBus eventBus = vertx.eventBus();
//                eventBus.registerDefaultCodec(CacheEntry.class, new CacheEntryCodec());
                eventBus.request(Events.PUT_ROUTING_CACHE, new CacheEntry<>("test2", "test2222", 30), ar -> {
                    if (ar.succeeded()) {
                        testContext.completeNow();
                    } else {
                        testContext.failNow(ar.cause());
                    }
                });

```

exception:

```
12:00:45 947 [vert.x-eventloop-thread-3] ERROR: io.vertx.core.impl.ContextImpl Unhandled exception
java.lang.IllegalArgumentException: No message codec for type: class com.hainahuijie.provider.CacheEntry
	at io.vertx.core.eventbus.impl.CodecManager.lookupCodec(CodecManager.java:101)
	at io.vertx.core.eventbus.impl.EventBusImpl.createMessage(EventBusImpl.java:234)
	at io.vertx.core.eventbus.impl.EventBusImpl.request(EventBusImpl.java:113)
	at io.vertx.core.eventbus.EventBus.request(EventBus.java:95)
	at io.vertx.core.eventbus.EventBus.request(EventBus.java:74)

```

I think I may not have fully understood what you mean. 😜

**Comment by lygoing** [comment]
@vietj  Thanks for your reply. ☕️
According to your suggestion, I implemented the Shareable interface of my pojo and canceled the registration of the message decoder. But the work failed. exception: `java.lang.IllegalArgumentException: No message codec for type: class provider.CacheEntry`

I tried two versions of `3.9.0` and `4.0.0-milestone4` and got the same exception.

pojo:
```
@Data
@AllArgsConstructor
public class CacheEntry<K, V> implements Shareable {

    private K key;
    private V value;
    private int ttl;

}

```

Eventbus Handle:

```

                EventBus eventBus = vertx.eventBus();
//                eventBus.registerDefaultCodec(CacheEntry.class, new CacheEntryCodec());
                eventBus.request(Events.PUT_ROUTING_CACHE, new CacheEntry<>("test2", "test2222", 30), ar -> {
                    if (ar.succeeded()) {
                        testContext.completeNow();
                    } else {
                        testContext.failNow(ar.cause());
                    }
                });

```

exception:

```
12:00:45 947 [vert.x-eventloop-thread-3] ERROR: io.vertx.core.impl.ContextImpl Unhandled exception
java.lang.IllegalArgumentException: No message codec for type: class provider.CacheEntry
	at io.vertx.core.eventbus.impl.CodecManager.lookupCodec(CodecManager.java:101)
	at io.vertx.core.eventbus.impl.EventBusImpl.createMessage(EventBusImpl.java:234)
	at io.vertx.core.eventbus.impl.EventBusImpl.request(EventBusImpl.java:113)
	at io.vertx.core.eventbus.EventBus.request(EventBus.java:95)
	at io.vertx.core.eventbus.EventBus.request(EventBus.java:74)

```

I think I may not have fully understood what you mean. 😜

**Comment by vietj** [comment]
@lygoing I think for now we don't implement copying using the Shareable interface but that's something we might do to allow this case

**Comment by lygoing** [comment]
@vietj 
👌, I think it may be a very nice feature. Now I write the message codec honestly.
Thanks again.

**Comment by slinkydeveloper** [comment]
+1 with @lygoing, i think it might be nice to have a simple way to send immutable pojos over the event bus without encoding them

**Comment by slinkydeveloper** [comment]
@vietj any updates on this one? Is there some way i can help?

**Comment by vietj** [comment]
it is not clear how this could be achieved, how would the codec knows that an object is actually immutable and how would it make a copy of this object without a contract like the Shareable interface ?

**Comment by slinkydeveloper** [comment]
> how would the codec knows that an object is actually immutable and how would it make a copy of this object without a contract like the Shareable interface ?

It doesn't know. We could have an interface in the event bus like:

```
eventBus.registerImmutableClass(Class<T> clazz)
```

That just generates a codec that does nothing, hence skipping encoding and copying in case the message is sent to a local consumer.

**Comment by slinkydeveloper** [comment]
And, at the same time, we could have an interface like:

```
eventBus.registerShareable(Class<? extends Shareable> clazz)
```

That automatically generates a "local only" codec for shareable objects

**Comment by slinkydeveloper** [comment]
I'm gonna try to draft an API

**Comment by slinkydeveloper** [comment]
@vietj https://github.com/eclipse-vertx/vert.x/pull/3903

**Comment by vietj** [comment]
does it work with native image ?

overall we are trying to avoid using class object, using a Function
would be a better fit I think.

**Comment by slinkydeveloper** [comment]
@vietj I don't understand how my PR could cause issues with native images

**Comment by iekdosha** [comment]
+1, this would be very nice for passing a simple record around without using clustering.

**Comment by tsegismont** [comment]
Closing, please take a look at https://github.com/eclipse-vertx/vert.x/issues/4365

This should solve the use cases reported here
