### ISSUE TITLE
An infinite loop in VertxHttpHeader while add and remove entry in iterator

### ISSUE THREAD

**Issue by Liyixin95** [eclipse-vertx/vert.x#3377]
### Version

3.9.0

### Context

As the title said,if you remove a entry and then add another one in a iterator loop, you will encounter with an infinite loop.

### Do you have a reproducer?

a simple example to reproduce this issue :
```
MultiMap map = new VertxHttpHeaders();                              
map.add("a","a");                                                   
map.add("b","a");                                                   
map.add("c","a");                                                   
map.add("d","a");                                                   
                                                                                                                                      
for (Map.Entry<String, String> entry : map) {                       
    map.remove(entry.getKey()).add(entry.getKey(),entry.getValue());
}                                                                   
```
### Extra
I think this issue is caused by the circular linked list,just break the circular and this issue could be solved.

I would like to provide a PR if you don't mind.

**Comment by vietj** [comment]
sure @Liyixin95 that would be great

**Comment by Liyixin95** [comment]
@vietj I think such usage of iterator is wrong now...but the infinite loop still should be avoided. Should we just ignore the new added element(like the older version of Vert.x), or throw a ConcurrentModifyException?(like the jdk's LinkedList)

**Comment by vietj** [comment]
interesting indeed and that's a public API so we should indeed guard about this

**Comment by vietj** [comment]
can we capture in the iterator the next value before returning it and on a next we check that the current next is still the same next and has not changed ?

**Comment by Liyixin95** [comment]
@vietj the solution of the linkedlist in jdk is throw a ConcurrentModificationException if you modify the list in the loop, so the insert is totally forbidden.In the older version of Vert.x, the iterator is a snapshot of the multimap, so the traversal and modify was detached, and the new added element can't be visited in the loop. In the newer version, the new added element can be visited, but if you must add element with some condition ,such as 

```
MultiMap map = new VertxHttpHeaders();
    map.add("a","a");
    map.add("b","a");
    map.add("c","a");
    map.add("d","a");

    for (Map.Entry<String, String> entry : map) {
      if(entry.getKey().equals("a")) {
        map.remove(entry.getKey()).add(entry.getKey(),entry.getValue());
      }
    }
```

**Comment by Liyixin95** [comment]
@vietj in conclusion, we have three choice.

1.Completely forbide the insert operation, and throw an ConcurrentModificationException if you insert in a loop.

2.ignore the new added element, just like the older verion of vert.x. Besides , the order of visit will be reverse of insert.

3. do no thing...then modification in loop will be allowed and new added element will also be accessable too,but the example at the begining will cause infinite loop.

**Comment by vietj** [comment]
can you test with different implementations of MultiMap ?

**Comment by Liyixin95** [comment]
@vietj I test the `CaseInsensitiveHeaders` and the `DefaultHttpHeaders` int netty.They have the same behavior with the new version of vert.x.

**Comment by vietj** [comment]
This seems to happen with Netty implementation of iterator and we don't want to fix this in Vert.x (ie I don't want to work around the issue with Netty behavior). This might be seen as an acceptable behavior and I would like to check with Netty what is their opinion about this.
