### ISSUE TITLE
wmic deprecated in win10

### ISSUE THREAD

**Issue by chengenzhao** [eclipse-vertx/vert.x#3385]
#### Describe the feature

In method io.vertx.core.impl.launcher.commands.StopCommand.terminateWindowsApplication:

```java
  private void terminateWindowsApplication() {
    // Use wmic.
    List<String> cmd = Arrays.asList(
        "WMIC",
        "PROCESS",
        "WHERE",
        "CommandLine like '%vertx.id=" + id + "%'",
        "CALL",
        "TERMINATE"
    );
```

since WMIC is about to sunset in future, and already deprecated in Win 10, one of our interns are using win 10 and found this issue, so should we use Get-CimInstance to replace it?

reference: [https://stackoverflow.com/questions/57121875/what-can-i-do-about-wmic-is-deprecated](https://stackoverflow.com/questions/57121875/what-can-i-do-about-wmic-is-deprecated)

#### Use cases

We are using Windows 10 & vertx-maven-plugin to build vert.x project and it breaks when redeploying the project using vertx-maven-plugin
while it works in macOS 

#### Contribution

@tsegismont may help solve this issue

original issue: https://github.com/reactiverse/vertx-maven-plugin/issues/205

**Comment by vietj** [comment]
@chengenzhao that would be a great contribution
