### ISSUE TITLE
Message consumer is not anymore a write stream

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#3389]
In Vert.x 3, the `MessageProducer` interface extends the `WriteStream` interface and provides limited support for message back-pressure. In practice credit leak might happen leading to a depletion of credits in the producer that won't allow to emit messages.

The `MessageConsumer` will continue to extend `ReadStream` and will drop messages when the consumer is paused and the pending message queue is full. This allows to continue supporting the nice integration with Rx generators for building message consuming pipelines.

Point to point message streaming over the event-bus will be introduced in Vert.x 4 to provide a supportable solution to replace this.

**Comment by elventear** [comment]
> Point to point message streaming over the event-bus will be introduced in Vert.x 4 to provide a supportable solution to replace this.

@vietj Has the point to point API been introduced to Vert.X yet?

**Comment by vietj** [comment]
@elventear we have not yet unfortunately, there is a branch prototype though.
