### ISSUE TITLE
Json.encode(pojo) throw UnsupportedOperationException

### ISSUE THREAD

**Issue by landon30** [eclipse-vertx/vert.x#3394]
### Questions
I write a simple pojo class，and then call Json.encode but throw UnsupportedOperationException
### Version
4.0.0-milestone4
### Context
test vertx JsonObject usage

### Do you have a reproducer?
```
public class GamePlayer {

    private String rid;
    private int level;

    public GamePlayer(String rid) {
        this.rid = rid;
        this.level = 1;
    }

    public String getRid() {
        return rid;
    }

    public int getLevel() {
        return level;
    }
}

    @Test
    public void testJsonObject() {
        GamePlayer player = new GamePlayer("1");
        String json = Json.encode(player);
        System.out.println(json);
    }

```
### Steps to reproduce
just call the junit case

### Extra
jdk:1.8.0_241

**Comment by landon30** [comment]
the class `GamePlayer`，i also add the default constructor and the setters.
it still throw UnsupportedOperationException

**Comment by vietj** [comment]
you need to add the jackson-databind jar to your classpath

**Comment by vietj** [comment]
we should improve error reporting I think for this

**Comment by landon30** [comment]
> you need to add the jackson-databind jar to your classpath

it run success，thanks very much

**Comment by vietj** [comment]
See https://github.com/eclipse-vertx/vert.x/commit/fa90f94b052dd204ec38cb7216a6dd0e52370e2c
