### ISSUE TITLE
Build failure on PowerPC ppc64le architecture

### ISSUE THREAD

**Issue by aishwaryabk** [eclipse-vertx/vert.x#3402]
I am trying to build the master branch of vert.x on Ubuntu:16.04 ppc64le. I have built netty, netty-tcnative, hawtjni from source, however the build fails with 361 failures, and 659 errors.

Following is the detailed error-ed log:
[vert_error.log](https://github.com/eclipse-vertx/vert.x/files/4597008/vert_error.log)

**Comment by jponge** [comment]
Hi @aishwaryabk, most of us don't have access to this hardware, would you be able to investigate what is the issue?

Also can you run a Vert.x service on your JVM on that architecture? (using the released artefacts)

**Comment by aishwaryabk** [comment]
I have tried building vert.x on ubuntu: 16.04 and centos:7. The errors on both the OS are similar.

Detailed log(ubuntu): 
[error_ubu_vert.log](https://github.com/eclipse-vertx/vert.x/files/4621590/error_ubu_vert.log)

Detailed log(centos):
[error_cent_vert.log](https://github.com/eclipse-vertx/vert.x/files/4621593/error_cent_vert.log)

**Comment by vietj** [comment]
I'm closing this, please test with Vert.x 4 and let us know the result
