### ISSUE TITLE
CompositeFuture all(List<Future> futures) do not call onsuccess method.

### ISSUE THREAD

**Issue by GZYangKui** [eclipse-vertx/vert.x#3403]
At present, CompositeFuture#all only a handler is passed in setHandler. When all Future is finished, the Handler. is called. Because CompositeFuture inherits Future, there is onSuccess method. Do we consider calling onSuccess after all Future is completed?

**Comment by vietj** [comment]
which branch did you test with ? did you test with master ?

**Comment by GZYangKui** [comment]
@vietj Thank you for your reply. I checked the master branch and found that the problem has been fixed.


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by vietj** [comment]
does it happen on another branch ?

**Comment by GZYangKui** [comment]
@vietj I use 4.0.0-milestone 4


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by vietj** [comment]
ok then thanks
