### ISSUE TITLE
setExpectedMultipart  error

### ISSUE THREAD

**Issue by javad-salehi** [eclipse-vertx/vert.x#3407]
in vertx-core document:
server.requestHandler(request -> {
request.setExpectMultipart(true);
request.endHandler(v -> {
// The body has now been fully read, so retrieve the form attributes
MultiMap formAttributes = request.formAttributes();
});
});
-------------------------------------------------------------------------------------
SEVERE: Unhandled exception
java.lang.IllegalStateException: Request must have a content-type header to decode a multipart request
but in prev version work truly.

**Comment by vietj** [comment]
can you provide a reproducer project ?

**Comment by javad-salehi** [comment]
public class Main {
    public static void main(String[] args) {
       var vertx = Vertx.vertx();
       var server = vertx.createHttpServer();
        /*---*/
        server.requestHandler(request->{
            request.setExpectMultipart(true);
            request.response().end("hello vertx");
        });
        /*---*/
        server.listen(80, "localhost");
    }
}
------------------------------------------------------------------------------------------------------

**Comment by vietj** [comment]
what does the client send ?

**Comment by javad-salehi** [comment]
only a simple GET request from browser

**Comment by tsegismont** [comment]
@vietj this is not a regression, this was changed in https://github.com/eclipse-vertx/vert.x/issues/3346

**Comment by vietj** [comment]
@javad-salehi you need to check the ocnten type is correct before calling `request.setExpectMultipart(true);`
