### ISSUE TITLE
Restore ability to measure number of scheduled, but not yet run, EventBus handlers.

### ISSUE THREAD

**Issue by sfitts** [eclipse-vertx/vert.x#3419]
#### Describe the feature

This lies somewhere between bug and feature.  In Vert.x 3.9.x the call to `EventBusMetrics.scheduleMessage` was moved from `EventBusImpl.deliverToHander` to `HandlerRegistration.handle`.  The call to `EventBusMetrics.beginHandleMessage` remains where it was before.

With the old placement it was possible to measure the number of EventBus messages that had been received and turned into Netty tasks, but which had not yet been run by Netty (since the call to `scheduleMessage` occurred before the task was created and the call to `beginHandleMessage` occurs only once the task has started running).

With the new placement this is no longer possible.  The only thing you can measure is the depth of the internal pending queue, which will only be used if the event consumer is paused for some reason (which our application never does).

If possible we would like the old capability restored in some fashion.  If it isn't feasible to move the call to `schedule` back where it was, then perhaps a new entry point to EventBusMetrics could be added to replace it.  The inability to measure the number of backlogged tasks hampers our performance analysis.

#### Use cases

Understanding (in detail) how work is flowing through the system when running at high throughput rates (>100K/s) is critical to both application tuning and provisioning.  The Netty task backlog is an important metric in understanding when and where incoming work is overwhelming the system's ability to process it.  Netty itself provides very little in the way of instrumentation so measuring it via Vert.x was the best we could do.

#### Contribution

I would be happy to contribute this change, though I've never done any work on the actual Vert.x core (I do have a current Eclipse contributor agreement).  Beyond that I don't know who the appropriate person might be to do the implementation.

**Comment by vietj** [comment]
can you show the commit that changed that @sfitts ?

**Comment by vietj** [comment]
can we instead try to address this in Netty ? or the way Vert.x uses Netty ?

**Comment by vietj** [comment]
I would like to know what you want to measure exactly, do you want to know the latency of the execution of a task ?

**Comment by sfitts** [comment]
> can you show the commit that changed that?

42cdd34b47266e1775695da9a730f5f9008e986e

>can we instead try to address this in Netty ? or the way Vert.x uses Netty ?

Perhaps.  Our preference would be for this to be solved via some kind of SPI as it was previously.  That way we can have more control over exactly how the measurement is collected.  We've found that for our application the efficiency of the monitoring here is critical (for example, we don't use the OOB micrometer support because it performs an unacceptable amount of memory allocation which skews all of our testing).

> I would like to know what you want to measure exactly, do you want to know the latency of the execution of a task ?

Our overall goal is to have a clear picture related to the performance of EventBus message processing when running our application at/near its maximum throughput.  The metrics we are specifically gathering are:

* Message throughput
* Latency of message delivery timed from the point at which we call `send` to the point at which the handler associated with the corresponding consumer is invoked by Vert.x.
* Number of messages that are in a state where Vert.x has called "runOnContext" for the target handler, but for which the handler has yet to actually been run (the only reason for which is that Netty hasn't had a chance to schedule it yet).

Measuring the throughput is easy (we simply use the throughput from the latency timer).
We measure the latency in our application code using timing data communicated in the message header.
The last one was what we were using the SPI above to measure (as described).  

The first 2 metrics are recording using a timer (we are using Micrometer) and the 3rd is recorded in an AtomicInteger and surfaced via a gauge.

In our case we don't ever pause the Consumer, so it isn't possible for there to be any messages in its pending queue.  We also aren't using a message producer (in this case), so that queue is also out of play.

(On a side note -- currently I don't think there is any way to actually surface the depths of these queues, something that would also be nice, but isn't critical for us.)

Hope that helps.

**Comment by vietj** [comment]
are you implementing your own metrics SPI ?

**Comment by vietj** [comment]
@sfitts why can't you use then the `EventBusMetrics#messageReceived` callback that happens at the same moment the `EventBusMetrics#scheduleMessage` method was called ?

**Comment by sfitts** [comment]
Yes, we have a custom implementation of the `EventBusMetrics` interface (we don't currently use the others, but if we needed to we would likely implement them as well).

**Comment by sfitts** [comment]
> why can't you use then the `EventBusMetrics#messageReceived` callback that happens at the same moment the `EventBusMetrics#scheduleMessage` method was called ?

It doesn't provide the same context -- specifically, it doesn't pass `holder.getHandler().getMetric()` (it could since it has the holder right there, but that SPI doesn't give you the `handler`).  The `AtomicInteger` I mentioned above is in that data-structure.  Makes incrementing/decrementing the value quick and easy.

Since this is our code we can probably figure out a way to rearrange things if that's the only SPI we're going to have, but it obviously isn't as convenient and have to do some extra work on each message (since we'd have to map from the address to the value in some fashion).  The mapping won't be quite the same either since currently we can measure "queue" for each handler and here we have only the address.

Anyway, might give us an out for the short term, but longer term we'd like some way to measure what we were.

**Comment by vietj** [comment]
I will retry revert this change and add a test for it

**Comment by sfitts** [comment]
Much appreciated, ty.

**Comment by vietj** [comment]
so here is the deal, there is a race between the message delivery and the message consumer unregistration, the possible race happens:

1/ metrics is called to schedule a message and increment a counter
2/ the consumer is unregistered
3/ the message is not delivered and the counter is false

This race leads to incorrect message count in metrics, i.e we can observe a leak of message that are scheduled (increment counter) and never delivered (decrement counter). That main issue motivated this change (even though this is poorly documented in the commit, my bad).

I believe we can work around this using the new `discardMessage` callback (at least in master) by calling the sequence directly for such messages.

**Comment by vietj** [comment]
e.g this can happen too with reply handlers when they are unregistered after a timeout

**Comment by sfitts** [comment]
Doesn't `handlerUnregistered` get called when the consumer is unregistered?  In that case we clear the pending count for that handler.  Or is that not sufficient/what you are concerned about here?

**Comment by vietj** [comment]
it seems important to me that each call to schedule gets either a discard or delivery corresponding method call, without having the metrics implementation to account for such possibility

**Comment by vietj** [comment]
I think we can achieve it with the change I explained

**Comment by sfitts** [comment]
Agreed, that would best (just wanted you to know how we're accounting for that possibility now).  BTW -- big thumbs up on the addition of `discardMessage` to the SPI, saw that in 3.9.0.

**Comment by vietj** [comment]
@sfitts here is a branch that implement this behavior : https://github.com/eclipse-vertx/vert.x/tree/event-bus-metrics-schedule would you mind to check it meets your expectations ?

**Comment by sfitts** [comment]
Looks good, thanks again.

**Comment by vietj** [comment]
I'll merge tomorrow and backport to 3.9 branch

**Comment by vietj** [comment]
done in master and 3.9 branches
