### ISSUE TITLE
HttpClient/WebClient not closing connection after request done.

### ISSUE THREAD

**Issue by chinfeng** [eclipse-vertx/vert.x#3420]
### Questions

 I am using ServiceDiscovery to publish httpclient/webclient record. But find out connections is not closed. And it consume all my client ports rapidly and report "cannot assgin address" error.

### Version

3.9.1 and 4.0.0-M4

### reproducer

[https://github.com/chinfeng/vertx-conn-leaks-reproducer](https://github.com/chinfeng/vertx-conn-leaks-reproducer)

### Steps to reproduce

1. run gateway 
2. run foo
3. visit http://127.0.0.1/foo/metrics in browser
4. refresh browser, see "open-connections" counter, it grow every refresh and no release at all.

**Comment by vietj** [comment]
@chinfeng I think this is normal because the client uses connection pooling by default

**Comment by vietj** [comment]
you need to pass configuration to disable connection pooling by setting keep-alive to false instead
