### ISSUE TITLE
Extend AsyncMap supported key/values types with codecs

### ISSUE THREAD

**Issue by avgustinmm** [eclipse-vertx/vert.x#3421]
#### Describe the feature
At the moment AsyncMap-s provided by SharedData have key and value type restrictions: primitive types, java.io.Serializable and io.vertx.core.shareddata.impl.ClusterSerializable. None of these could be used for POJO objects that doesn't implement Serializable (ClusterSerializable is internal interface - so it's very unlikely someone to implement it).
Support for AsyncMap key.value types could be extended using the same approach used in EventBus - by registering codecs. Codecs in both cases could even use the same interface - after all they would serve single concept - serialize and deserialiize custom objects.

**Note**: If such support is added, vertx could auto register codecs for JsonObject/JsonArray/Buffer instead of implementing ClusterSerializable (which is not public class and seems little strange in the documentation) . Probably ClusterSerializable could be even removed. 
I don't see in current SharedData doc any notice which types are supported. And it would be little hard to explain because of internal ClusterSerializable.

**Note**: Event bus supports byte[]. There's no reason for AsymcMap to do not support byte[] as value type (at least to have similar supported types for event bus and AsyncMap)

#### Use cases
Having a cluster wide async map with key.value types that are legacy or not in developer control e.g. POJOs.

**Comment by tsegismont** [comment]
It is a mistake that `ClusterSerializable` is in implementation package. It's been added to Vert.x for a long time and there are no plans to get rid of it.

@vietj @jponge would you agree to:

- duplicate it in the public package
- deprecate the internal one (as we did for logging)
- make the public one extend the internal one for backward compatibility?

We could backport this to 3.9. And of course update the documentation,

**Comment by vietj** [comment]
@tsegismont for now I don't want to rush into that

**Comment by jponge** [comment]
That's good approach if we do like we did with logging.

**Comment by vietj** [comment]
doing this seems to be simply beyond changing a package name as the issue describes it _If such support is added, vertx could auto register codecs for JsonObject/JsonArray/Buffer instead of implementing ClusterSerializable, ...._

so a proper description is needed before scheduling any work, i.e we don't want to think it is as easy as just changing a package name and then we have more to do that was not initially planned.

**Comment by avgustinmm** [comment]
I don't think that public ClusterSerializable is good enough. If I will implement cluster serializable I could implement java Serializable interface (if documentation is clear enough). However this doesn't solve things with POJO and objects that are not under my control.  In this case I should wrap/unwrap these types. 
So, codecs are more powerful - they solve this user case. Also having same codecs pattern for event bus and cluster types makes vertx much more consistent. Why you should have 2 serialization patterns for both use cases?

**Comment by tsegismont** [comment]
@vietj my previous comment perhaps was not clear enough, sorry. I meant that there are no plans to do anything else than supporting `ClusterSerializable` and `Serializable` for `AsyncMap`. It doesn't mean we cannot, in the short term, document it properly and move the annotation to public package with proper migration path. I believe this is what @jponge agreed with.

@avgustinmm integrating EB codecs with shared data api is not something we want to do in Vert.x 4. Perhaps we can look into this for Vert.x 5. In the meantime, when you don't own the classes, you can put in the map a byte array which contains 1/ the name of the converter class that serialized the object and can deserialize it 2/ the object in serialized form.

**Comment by avgustinmm** [comment]
I've already worked around this limitation of AsyncMap by wrapping a class in an Serializable wrapper. I just propose thise enhancment because I feel it would be user friendlier to have map with exact POJO types (i.e. no need to wrap/unwrap) and will make vertx event bus and cluster more simillar.

**Comment by tsegismont** [comment]
Thanks for reporting @avgustinmm , we'll think about it for a later major version
