### ISSUE TITLE
Jackson Databind is still required for parsing json file

### ISSUE THREAD

**Issue by chengenzhao** [eclipse-vertx/vert.x#3422]
### Questions

java.lang.UnsupportedOperationException: Mapping is not available without Jackson Databind on the classpath
        at io.vertx.core.json.jackson.JacksonCodec.fromValue(JacksonCodec.java:79)
        at io.vertx.core.json.JsonObject.mapFrom(JsonObject.java:107)

Seems like JsonObject.mapFrom operation still need jackson databind dependency while vertx-core won't automatically import this dependency for 4.0 - m4

    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.9.10.3</version>
    </dependency>

if we manually add this dependency, it won't throw exceptions

### Version

4.0.0 - milestone 4

### Context

4.0.0 - milestone 4

### Do you have a reproducer?

it happens in our open source project:
https://github.com/whitewoodcity/social-vertex

https://github.com/whitewoodcity/social-vertex/blob/master/src/main/java/cn/net/polyglot/MainVerticle.java

line 42:
config.mergeIn(JsonObject.mapFrom(ar.result()));

if we place a json config file(config.json) and main verticle will load the file and then parse it into json format and it will fail without jackson-databind dependency

**Comment by vietj** [comment]
yes that is expected, you need to add the dependency yourself

I don't get why your code does : `config.mergeIn(JsonObject.mapFrom(ar.result()))` and not simply `config.mergeIn(ar.result())`
