### ISSUE TITLE
Provides feature that can be implemented using a customize Clustered-EventBus

### ISSUE THREAD

**Issue by leotu** [eclipse-vertx/vert.x#3426]
The "VertxImpl.java" constructor method force to create default ClusteredEventBus implementation, there is no way to create my specific implementation.

```java
public class VertxImpl implements VertxInternal, MetricsProvider {
...
 private final EventBusInternal eventBus;
...
 VertxImpl(VertxOptions options, ClusterManager clusterManager, NodeSelector nodeSelector, VertxMetrics metrics, VertxTracer<?, ?> tracer, Transport transport, FileResolver fileResolver) {
 ...
 ...
 this.eventBus = clusterManager != null ? new ClusteredEventBus(this, options, clusterManager, nodeSelector) : new EventBusImpl(this);
 ...
 ...
}
```

**Comment by vietj** [comment]
what is your actual use of having a different event bus implementation ?

**Comment by leotu** [comment]
I want to my ClusteredEventBus to use WebSocket instead of NetClient, and it may support retry strategy when the message pending to pickup another server ASAP.

The possible solution is to extend ClusteredEventBus & ClusteredHandlerHolder override some methods (i,e.  sendRemote , writeMessage, ...)

Or event rewrite most the package "io.vertx.core.eventbus.impl.clustered" files.

**Comment by vietj** [comment]
we will brainstorm with @tsegismont about what we could do for this

**Comment by rpax** [comment]
How about using the same factory approach that is used for creating the `Vertx` object?

**Comment by vietj** [comment]
@rpax what do you mean ?

**Comment by rpax** [comment]
> @rpax what do you mean ?

Sorry for the late response. I meant the old VertxFactory SPI. Seems that is not there anymore :D . But yes, allowing the use of SPI can do the trick
