### ISSUE TITLE
Enable service loadable external ExecutorService Factory via SPI

### ISSUE THREAD

**Issue by hutchig** [eclipse-vertx/vert.x#3434]
#### Describe the feature

Provide an SPI Interface for an executor service that can be used to fulfill executeBlocking requests and Java service load and use an implementation of the SPI that is found on the classpath at runtime.

#### Use cases

I want to be able to run a Vert.x application in a managed environment that makes use of Vert.x in its implementation to run 'blocking' work asynchronously but I need to be able to control various aspects of the threads and threadpool that is used in order to be able to maintain my requirements on system management, tuning and so on.

As I do not have direct control of the application source code I want to be able to get
Vert.x to use my executor service without making changes to the current Vert.x APIs
or requiring the application to call any new APIs.

I do not want to have a large surface area of new API's for tuning and thread control
in Vert.x that I have to get approved, implement and then call and I also want to ability to handle
more than one Vert.x application that issues executeBlocking calls in the JVM at
one time. I want to be able to externalize my configuration in a way that is idiomatic
to my environment and this can be acheived by encapsulating this in my own implementation
of the SPI.

Similarly, I do not think I have a requirement to interject at the level of the Context class
(or the class that implements executeBlocking). I want to continue to have Vert.x handle
such issues as 'ordered', metrics plug-in points, handler callbacks and so on. 

However, SPI insertion 'after' task queueing is too low level, as to maintain recognisable interfaces in the SPI we would probably 'wrap' any Callable/Runnable that gets submitted inorder to retrieve what contexts we needed when it was run.

It may make sense to have the SPI as a vanilla ExecutorService and leave in place
the Vert.x WorkerPool in order for that to handle metrics or other related requirements
but have WorkerPool::executor return the service loaded ExecutorService that has
been loaded off the classpath.

##### OpenLiberty embedding Vert.x

The first use case I have for this is to use it to enable the `@Blocking` annotation in
SmallRye Reactive Messaging 2.0+ in the context of the Liberty application server.

Note that as the service loaded ExecutorService may have a thread pool that grows
**and shrinks**, although Vert.x may schedule `ordered=true` blocking tasks one at
a time it may not be possible to run all tasks from a single Vert.x context on a the
same thread from the pool.

The SPI could be the standard j.u.c.ExecutorService but it is probably better to have 
a Vert.x specific interface that can be used to obtain the ExecutorService as well as to provide better support for 'named' worker pools being backed by the external ExecutorService.

#### Contribution

All being well with my employer, I would be happy to implement a PR for this feature along with the normal level of test and documentation assets using the standard Vert.x processes.

This is different from #1539 (apologies for typing so much text in that issue) 
as this feature is simpler and explicitly avoids API changes in Vert.x
which is a useful feature for our use case.

#### References

**Netty 5**
Of interest is that Netty 5 will [switch to using a Executor/ExecutorFactory ](https://netty.io/wiki/new-and-noteworthy-in-5.0.html#even-more-flexible-thread-model) in place of a ThreadFactory which would enable the loaded ExecutorFactory to be used for all Netty tasks.
( /netty/netty#2250 ). However, according to [this](https://github.com/netty/netty/projects?query=is%3Aopen) "There is currently no clear timeline for Netty5"!

**Comment by vietj** [comment]
@hutchig there is for now a requirement in Vert.x to have Vert.x threads (event-loop and worker) to extend `VertxThread`, is that fine for you ?

**Comment by vietj** [comment]
`ExecutorService` seems fine, this is what Vert.x `WorkerPool` delegates to.

I think the best would be a factory to provide these instead of having Vert.x create instances that allows to use a `ThreadFactory`, something like:

`ExecutorService createExecutor(ThreadFactory factory, ...)` where ... would be the configuration of the worker (like min number of threads, etc...)

**Comment by hutchig** [comment]
Dear Julien, thank you so much for responding to quickly andhelpfully.

I think that the SPI being of the form you suggest:
`ExecutorService createExecutor(ThreadFactory factory, ...)`
is a good idea and am happy to build for that sort of signature.

I think we could make the {external-ExecutorService, Vertx-ThreadFactory} [work](https://github.com/OpenLiberty/open-liberty/blob/14b07847e12d3218980626a2539de24563ed4888/dev/com.ibm.ws.threading/test/com/ibm/ws/threading/internal/ExecutorServiceImplTest.java#L229)

If I had to add in some simple decoration to VertxThread, such as [isShutdown](https://docs.oracle.com/javaee/7/api/javax/enterprise/concurrent/ManageableThread.html) that did not alter existing structures and did the work code and tests etc., would that be potentially acceptable?

**Comment by vietj** [comment]
do you mean adding new methods to VertxThread ?

**Comment by hutchig** [comment]
I was thinking of that yes, I was asking if extending VertxThread would be seen
as undesirable. 

What had came to mind was [isShutdown](https://docs.oracle.com/javaee/7/api/javax/enterprise/concurrent/ManageableThread.html) 
But actually, I am not sure if we use that at all internally on individual Threads.

I think me building the prototype using VertxThread as it is now is the best way to
proceed and resolve if anything else is needed at all.

**Comment by vietj** [comment]
I think we can add anything that gives information about thread and that is generic

**Comment by hutchig** [comment]
On the requirement of 'Vert.x threads extending VertxThread': Of interest (to me - I do understand this is not general Vert.x use case), is the environment where [Liberty is used inside CICS](http://www.redbooks.ibm.com/redbooks/pdfs/sg248418.pdf). 

In that use case we will have nested (((((Netty)Vert.x)SmallRye)Liberty)CICS) where
CICS also wants to occupy the single thread inheritance:

On z/OS, IBM CICS provides a Liberty [product extension](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/cwlp_prod_ext.html) which uses OSGi's Declarative Services to replace the Liberty ThreadFactory with a `CICSPooledThreadFactory`. The `CICSPooledThreadFactory` creates native z/OS posix threads in a z/OS XPLINK LE enclave that is fed into the CICS dispatcher and LE Unix system services to subsequently be imported into the JVM using JNI AttachCurrentThread and thus made available for the `CICSPooledThreadFactory` to return when requested by the Liberty Executor service.

Relevant here is that there is, I believe, only one JVM implementation that will be used in
the above situation. I used to own the IBM JVM's 'HPI' hardware portability component and I can remember that it was possible to control all sorts of aspects of thread creation that were used to back `j.l.Thread` (which is where, via FastThreadLocalThread inheritance, Vert.x gets its threads from). I will explore if it might be possible to do some/all of the CICS bootstrapping in a JVM feature.

(CICS also do task wrapping to bracket and make available CICS facilities to the task being run but that can remain as part of the ExecutorService ensemble.)

**Comment by hutchig** [comment]
Bookmarks:
https://objectcomputing.com/resources/publications/sett/june-2020-micronaut-2-dont-let-event-loops-own-you
