### ISSUE TITLE
`listenMulticastGroup` is not ready when the handler succeeds, tests exhibit flakiness

### ISSUE THREAD

**Issue by doctorpangloss** [eclipse-vertx/vert.x#3435]
### Version

vertx 3.8.3-3.9.1

### Context

`listenMulticastGroup` isn't ready the first time it is invoked on a `vertx` instance when its future completes. Delaying for an unusually long time seems to work around the issue.

### Do you have a reproducer?

https://github.com/hiddenswitch/udp-broadcast-reproducer

You can use `./gradlew test --tests "udp.broadcast.reproducer.AppTest.testUdpBroadcastResponseInjected"`

### Steps to reproduce

 1. Create a udp socket (socket "recipient").
 2. Listen to a multicast group.
 3. Send a packet from another udp socket to that group (socket "sender").
 4. Observe that sometimes, the recipient does not receive the message even though the future indicating it is listening has completed.
 5. Observe that injecting the vertx instance using vertx-junit5 100% reproduces the issue on the first invocation when no delay is used between completing the listening future and sending the packet.
 6. Observe that the next invocation, which also uses no delay, even when a different port (multicast group) is listened to, the test passes.
 7. Observe that on my machine, the minimum delay for the first invocation appears to be about 952 +/- 3ms. Not sure of the significance of this.

### Extra

**Platform:** macOS 10.15.5 (`Darwin MacBook-Pro.local 19.5.0 Darwin Kernel Version 19.5.0: Thu Apr 30 18:25:59 PDT 2020; root:xnu-6153.121.1~7/RELEASE_X86_64 x86_64`)

**Java:**
```
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```

**Comment by vietj** [comment]
what failure should I be looking at ?

I'm running the tests and testedListensNullInterface fails, other tests are passing

**Comment by vietj** [comment]
there might be when joining/leaving a group, the callback only signals that the operation succeeded but there is no way in practice to know when the bind will be propagated as there is no ack for such operation
