### ISSUE TITLE
Router path matching does not match documentation

### ISSUE THREAD

**Issue by gabrielguernikatdiscovery** [eclipse-vertx/vert.x#3440]
### Version

Vertx-web 3.9.1, but it seems present since 3.8.3

### Context

The documentation in https://vertx.io/docs/vertx-web/java/#_routing_by_paths_that_begin_with_something mentions that a route with path `/some/path/*` should match a request to `/some/path` but it does not. It did match before (at least in version 3.7.1) and thus this bug introduces a backwards incompatible change, in addition to the mismatch with the documentation.
I believe this was introduced in https://github.com/vert-x3/vertx-web/commit/628f49c950b864b88288bf2ca23ef126acf5be25

### Do you have a reproducer?

Can be reproduced with https://github.com/gabrielguernikatdiscovery/vertx-path-matching-issue/blob/220c7496629783e51fad90be4e24ccb541a007f2/src/test/java/io/vertx/starter/MainVerticleTest.java#L31

### Steps to reproduce

1. With vertx-web, add a route with a path ending in `/*`, eg, `router.route("/some/path/*");` and a proper handler
2. Make a request to `/some/path`
3. HTTP 200 should be returned
4. Actually, HTTP 404 is returned

### Extra

* Nothing relevant

**Comment by vietj** [comment]
can you move this issue to https://github.com/vert-x3/vertx-web/

**Comment by gabrielguernikatdiscovery** [comment]
done, https://github.com/vert-x3/vertx-web/issues/1641
