### ISSUE TITLE
Add control over websocket header case

### ISSUE THREAD

**Issue by geniusit** [eclipse-vertx/vert.x#3450]
### Questions

Add control over websocket headers case

### Version

I use quarkus 1.4.1.Final
The related vertx version is :  3.8.5
And it uses the netty-all:5.0.0.Alpha2 

### Context

Netty set all the headers with the lower case. e.g : sec-websocket-key.
I have a PHP websocket server the handle the header with a specific case : 
```php
// check Sec-WebSocket-Key header was received and decoded value length is 16
    if (!isset($headersKeyed['Sec-WebSocket-Key']))
      return false;
```

This is why I got  : [original problem](https://stackoverflow.com/questions/62391492/connection-closed-while-handshake-in-process-with-websockets)

This is related to [this post](https://stackoverflow.com/questions/50477233/issue-with-netty-websocket-headers-name-in-lowercase/62404244#62404244)

An interesting read about headers case : [this post](https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive)
### Steps to reproduce

1. Have a WebSocket server which handle the headers is specific case way (PHP in my case) 
2. Create a websocket client with vert.x
3. Try to make a connection

In whireshark I ve seen that I don't get the 101 Switch Protocol response as expected.
This is due to the wrong header case

**Comment by vietj** [comment]
It looks complicated to override the headers because the logic is hardwired in `WebSocketClientHandshaker` subclasses and there is no possibility to override it.

I think instead we should open an issue in Netty's project to allow using custom header values instead of the hardcoded constant it uses so it is possible to achieve this.

**Comment by geniusit** [comment]
Actually, I m changing the PHP server implementation. Ok to open an issue in Netty's project.
Do I have to do it or you ?

**Comment by vietj** [comment]
if you are changing the PHP server implementation then I think it's the best thing to do and we might not have to change this behavior (which is the actual desired behavior) in order to encourage more HTTP compliant implementations

**Comment by geniusit** [comment]
I ve changed the PHP implementation with this kinds of condition : 
```php
if (!isset($headersKeyed['Sec-WebSocket-Key']) && !isset($headersKeyed['sec-websocket-key']))
      return false;
```
It works and Im agree with you! Thank you for support
