### ISSUE TITLE
Same password is used for KeyStore and entry

### ISSUE THREAD

**Issue by ctron** [eclipse-vertx/vert.x#3452]
### Version

3.9.0

### Context

Using the `io.vertx.core.net.PfxOptions` it is possible to provide a "password". However, later on, in `io.vertx.core.net.impl.KeyStoreHelper.create(VertxInternal, KeyCertOptions)` this single password is being used for both opening the "key store" as well as opening the "entry" in the key store. However, this can be two different passwords.

So it is not possible to use an existing keystore, which has a different (or missing) password for one of the entries.

### Do you have a reproducer?

~~~java
import java.io.ByteArrayOutputStream;
import java.security.KeyStore;
import java.security.cert.Certificate;

import io.netty.handler.ssl.util.SelfSignedCertificate;
import io.vertx.core.Vertx;
import io.vertx.core.buffer.Buffer;
import io.vertx.core.impl.VertxInternal;
import io.vertx.core.net.KeyCertOptions;
import io.vertx.core.net.PfxOptions;
import io.vertx.core.net.impl.KeyStoreHelper;

public class Application7 {
    public static void main(String[] args) throws Exception {

        var cert = new SelfSignedCertificate();

        final KeyStore result = KeyStore.getInstance("PKCS12");
        result.load(null, null);
        result.setKeyEntry("alias", cert.key(), "foo".toCharArray(), new Certificate[] {cert.cert()});

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        result.store(out, "bar".toCharArray());

        var vertx = Vertx.factory.vertx();
        var opts = new PfxOptions()
                .setPassword("foo")
                .setValue(Buffer.buffer(out.toByteArray()));
        var ks = KeyStoreHelper.create((VertxInternal) vertx, (KeyCertOptions)opts);

    }
}
~~~

### Steps to reproduce

1. Run the reproducer

**Comment by vietj** [comment]
thanks

**Comment by vietj** [comment]
The password for the `PfxOptions` should be `bar` and not `foo`. I know that this will not solve the issue with the entry password. Can you provide a reproducer that uses Vert.x and exhibit the issue without using the internals ?

**Comment by ctron** [comment]
> The password for the `PfxOptions` should be `bar` and not `foo`. I know that this is on purpose and will not solve the issue with the entry password. But it does not show how the actual store entry is being used in a use case.

True, but as you mentioned: it doesn't make a difference. It doesn't work either way.

> 
> Can you provide a reproducer that uses Vert.x and exhibit the issue without using the internals ?

I will try, but I am not promising anything.

**Comment by vietj** [comment]
or just describe your use case that will work too.

**Comment by tsegismont** [comment]
Closing, needs more info
