### ISSUE TITLE
Remove CaseInsensitiveMultiMap

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#3454]
The `CaseInsensitiveMultiMap` implementation duplicates the logic currently in `VertxHttpHeaders`. The `VertxHttpHeaders` class is renamed to `HeadersMultiMap` and uses an optional validator for the entries and can be used instead `CaseInsensitiveMultiMap`.

**Comment by privettoli** [comment]
@vietj  No deprecation/grace period?

**Comment by vietj** [comment]
It has been already deprecated in 3.9 and advocated to use instead `MultiMap#caseInsensitiveMultiMap()` and `CaseInsensitiveHeaders` was in an implementation package already

**Comment by vietj** [comment]
so it's more a cleanup operation to remove a duplicate implementation

**Comment by privettoli** [comment]
I meant annotation @Deprecated

**Comment by vietj** [comment]
`CaseInsensitiveHeaders` is deprecated already in 3.9
