### ISSUE TITLE
Consider failing when number read from JsonObject would overflow

### ISSUE THREAD

**Issue by gabor-noenv** [eclipse-vertx/vert.x#3457]
### Version

3.9.1

### Context

When reading a big number from a JsonObject the result may overflow.
I expect it to fail when it happens. Currently it succeeds silently with wrong value returned. 
I believe this is dangerous for the majority of the use-cases. Same applies for JsonArray.
 
### Do you have a reproducer?

```
var json = new JsonObject("{\"amount\": 21474836470}");
long a1 = json.getLong("amount");    // 21474836470
int  a2 = json.getInteger("amount"); // -10

var array = new JsonArray("[21474836470]");
int a3 = array.getInteger(0); // -10
```

**Comment by vietj** [comment]
@pmlopes what's your take on this ?

**Comment by pmlopes** [comment]
@gabor-noenv this is the JVM behavior. For example:

```java
    long l = 21474836470L;
    System.out.println(l);
    int i = (int) l;
    System.out.println(i);
```

Will also print:

```
21474836470
-10
```

Without any exception being thrown. Same goes with non primitive types, for example a `Number` instance for `21474836470` when executing:

```java
Number n = new Long(21474836470);
System.out.println(n.intValue());
```

Will again print `-10`. I am of the opinion that users should know what kind of data their input is, and pick the right getter for it, plus we follow what is _"normal"_ on the JVM.

**Comment by vietj** [comment]
thanks @pmlopes that makes sense.

I think we could provide a `getNumber` method that returns a `Number` that does not make any assumption on the implementation allowing somebody to get the `Number` and be in charge of the conversion.

**Comment by vietj** [comment]
Instead we provide accessors for `java.lang.Number`
