### ISSUE TITLE
Mix between HTTP/1.1 and HTTP/2 weight in HttpChannelConnector

### ISSUE THREAD

**Issue by sauthieg** [eclipse-vertx/vert.x#3465]
I think there is an typo-kind of error in `HttpChannelConnector` when assigning `http1Weight` and `http2Weight`. HTTP/1.1 weight is using the HTTP/2 pool size, and things are inverted for HTTP/2 as well.

```java
    this.http1Weight = options.getHttp2MaxPoolSize();
    this.http2Weight = options.getMaxPoolSize();
```

https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/HttpChannelConnector.java#L86-L87

### Version

3.9.1 but seems 3.8.5 has the same code so maybe earlier versions are impacted

**Comment by vietj** [comment]
It is actually on purpose and not a typo, the weight of an HTTP/1 connection is the max pool size of HTTP/2, e.g if you have a HTTP/1 max pool size = 5 and HTTP/2 max pool size = 2 then the max weight is 5*2 = 10

so when if create an HTTP/1 connection you will consume 2 and you get weight = 8 and then if you create an HTTP/2 connection then you consume 5 and you can then only create one remaining HTTP/1 but no HTTP/2 connection.

however it creates an HTTP/2 connection then it consume 5 and the weight is 5, however if the HTTP server does not want to create an HTTP/2 connection (i.e it is HTTP/1) then the weight is corrected with a -3 and it goes back to 8.

I hope it makes sense.

**Comment by laurentvaills** [comment]
Thanks @vietj for the explanation. I completely missed the point that the weight of a connection was corrected afterwards, in case the upgrade to HTTP/2 was refused by the server.
