### ISSUE TITLE
ClassCastException in VertxHttpHeaders.add 

### ISSUE THREAD

**Issue by hjhill** [eclipse-vertx/vert.x#3477]
### Version

original encounter: 3.8.5
reproducer: 3.9.1

### Context

I encountered a suspicious "500 Internal Server Error" when trying to add a "vary" response header with multiple header names in the value using the method `add(CharSequence name, Iterable<CharSequence> values)` of the `MultiMap` interface. Trying to create a reproducer (see below) revealed the following exception:
 
```
java.lang.ClassCastException: io.netty.util.AsciiString cannot be cast to java.lang.String
        at io.vertx.core.http.impl.headers.VertxHttpHeaders.add(VertxHttpHeaders.java:93)
```

### Do you have a reproducer?

https://github.com/hjhill/vertx-maven-starter/tree/reproducer-multimap-add

`master` contains the default starter project - please take care to checkout the branch `reproducer-multimap-add`. In this branch, I have [only modified the request handler.](https://github.com/hjhill/vertx-maven-starter/commit/5a17ef10532a197e6fbaa0b961da078a845d72be).

### Steps to reproduce

1. Check out the branch `reproducer-multimap-add` of the Github repository linked above.
2. Run it with `mvn compile exec:java` (see below about using `test`)
3. Use any tool to create an HTTP request to `http://localhost:8080`.

The request will hang and you'll see the exception on the console.

Even simpler: if you use `mvn test exec:java` the exception will already show up in the test, but the test will then be hanging indefinitely.

**Comment by vietj** [comment]
fixed by https://github.com/eclipse-vertx/vert.x/issues/3479
