### ISSUE TITLE
Add ability to safely add path fragments to HttpRequest

### ISSUE THREAD

**Issue by privettoli** [eclipse-vertx/vert.x#3490]
#### Describe the feature

Add ability to safely add path params to io.vertx.ext.web.client.HttpRequest
When coming from Spring, it's possible to use uri variables / path parameters / fragments like this:
```java
webClient.get()
      .uri("https://github.com/{userName}", name)
      .exchange()
```
It's achieved internally in Spring by using org.springframework.web.util.UriComponentsBuilder
It escapes non-ASCII symbols.
Suggestion is to add methods:
`io.vertx.ext.web.client.WebClient#post(int port, String host, String requestURI, Map<String, ?> uriVariables)`
`io.vertx.ext.web.client.HttpRequest#uriVariable(String name, ? value)`
`io.vertx.ext.web.client.HttpRequest#addPathFragment(String fragment)`

#### Use cases

When the path fragment might need to be encoded or might contain / (slash symbol), we want to safely encode it instead of unsafely concatenate the string.

#### Contribution

I'm volunteering.

**Comment by vietj** [comment]
that would rather be in vertx-web-client which has an issue for this

**Comment by vietj** [comment]
See https://github.com/vert-x3/vertx-web/issues/1260
