### ISSUE TITLE
Interested in a Redisson-based Cluster Manager?

### ISSUE THREAD

**Issue by doctorpangloss** [eclipse-vertx/vert.x#3499]
#### Describe the feature

For my Vertx-based application I authored a cluster manager based on Redisson (redis). It passes 100% of the tests specified in `vertx-core:3.9.1:tests-jar`, in addition to the currently disabled `testLockReleasedForClosedNode` and `testLockReleasedForKilledNode` tests, for both graceful and ungraceful (connection lost) node shutdowns.

Visit https://github.com/hiddenswitch/Spellsource/tree/master/vertx-redis-cluster for an overview of the package.

I initially started with https://github.com/leotu/vertx-cluster-redis and rewrote all of that repo since that repo did not work and was based on an outdated Redisson feature set.

I am not good with Maven; setting up a repo in the Vertx Maven pattern; or even publishing to Maven central with gradle. My experience with all of that is quite bad, so that's really all I can't do.

Additionally, once 4.0.0 is done I would migrate to its new cluster SPI after migrating my application. However this would be a `vertx` task probably.

#### Use cases

**Pros**

 - It's a cluster manager that works for all 100% of your tests.
 - It's integration tested with a large, live, clustered application.
 - It's super simple because most of the hard work is done by Redisson.
 - Redisson is async and netty-based, so it doesn't tie up blocking threads like Hazelcast does
 - Redis is easy to run and test (with `Testcontainers`).
 - Redis is very high performance.
 - RedisRaft was written in cooperation with the Jepsen folks.

**Cons**

 - Needs more testing around transient network issues
 - Currently written with `gradle`
 - Currently written against 3.9.1
 - The approach to getting an ordered node list is not based on a proven TTL list primitive. It's likely an HA test can be authored that will not pass.
 - Serialization / deserialization story not great (uses something ad-hoc from the source I was adapting).

#### Contribution

I have implemented this feature.

**Comment by tsegismont** [comment]
Thanks for sharing @doctorpangloss .

You can start by adding your project to this the [Vert.x Awesome list](https://github.com/vert-x3/vertx-awesome).
Then you could submit your project to the [Reactiverse](https://github.com/reactiverse/reactiverse).
