### ISSUE TITLE
ClusteredEventBus 3.9 incorrectly reports No handlers for address when event bus nodes in subs map could not be connected to

### ISSUE THREAD

**Issue by doctorpangloss** [eclipse-vertx/vert.x#3504]
### Version

3.9.1

### Context

Using vertx in a cloud, containerized environment, I did not set `EventBusOptions#clusterPublicHost` and `EventBusOptions#host`. Consequently I was seeing traces for `eventBus.send` that read `(NO_HANDLERS,-1) No handlers for address`.

The actual issue was that the `ClusteredEventBus` was silently failing to deliver locally because:

 1. For all nodes, the hostname `localhost` was used as the cluster host name so
 2. `ClusterNodeInfo` was equal for all nodes, so
 3. A local delivery was attempted instead of throwing a connection error

### Do you have a reproducer?

No, but the correctness issue can be see here, in 3.9 but **not** 4.+

Consider what happens when all server IDs are the same:

**3.9.+**

https://github.com/eclipse-vertx/vert.x/blob/2064ddef0372ad885d0ef3ad2d26589632089296/src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java#L338

```
if (sendContext.message.isSend()) {
  // Choose one
  ClusterNodeInfo ci = subs.choose();
  ServerID sid = ci == null ? null : ci.serverID;
  if (sid != null && !sid.equals(serverID)) {  //We don't send to this node
    if (metrics != null) {
      metrics.messageSent(address, false, false, true);
    }
    sendRemote(sid, sendContext.message);
  } else {
    if (metrics != null) {
      metrics.messageSent(address, false, true, false);
    }
    deliverMessageLocally(sendContext);
  }
}
```

Observe that in 3.9 `vertx` will incorrectly try to deliver the message locally instead of trying to `sendRemote` and failing.

**4.0.0**:

https://github.com/eclipse-vertx/vert.x/blob/be47395c01a476c40f2973120a8e6ea21aa93eaa/src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java#L271

Conversely here we will see a connection error.

**Comment by tsegismont** [comment]
Duplicates #2696
