### ISSUE TITLE
Distributed transaction

### ISSUE THREAD

**Issue by nevenchen** [eclipse-vertx/vert.x#3508]
Currently I am tring to choose some reactive framwork to rebuild my springboot project.   

What I am care about is: porformance, transaction.   
Before Vert.x I already do some research about AxonFramword and Lagom.   
Both of them are reactive and distributed-transaction supported.   

Vert.x have more user and stars then them.    
But seems there is no topic about distribted-transaction with Vert.X.   

I don't know why?   
Does Vert.x going to provide some distributed-transaction features in the future?

**Comment by tsegismont** [comment]
Hi, there was an answer already in #2939
