### ISSUE TITLE
Proper defaults for cache directory

### ISSUE THREAD

**Issue by drexljo** [eclipse-vertx/vert.x#3510]
The default cache directory has two issues regarding system integration on Linux. 

Issue 1: It falls back to /tmp/vertx-cache, which is absolutely in the correct directory for temp files, but being solely static binds the directory to the user being first on the system to start up any vert.x based Java. Every follow-up user is being denied write-access (as is policy and correct) and greeted with a cryptic message (which does not contain the directory having the issue). 
Issue 2: This even creates a persistent problem, since vert.x seems to not care to remove the directory when its process is shutting down.

My proposal is as follows:
a) using a dynamic & unique component to the name used, like /tmp/vertx-cache-$(md5($USER$PID$TIME))
b) specifying the directory in the error message, if there's an access issue and
c) removing it in the end, for /tmp is not a trashheap, even if it is cleaned during system boot

Why $USER, $PID and $TIME?
Systemd is able to start processes simultaneously, so only using $USER and $TIME is likely to produce hash collisions. $PID is guaranteed to be different, so in theory it would be sufficient to just add the PID, but then forgetting to delete the directory during termination (or being killed with -9 and not being able to) might result in future processes reusing the PID and have the problem again. Adding $USER would mitigate that or at least only lead to the new process finding ancient stuff, but since that might not be desireable, $TIME adds that extra safety clip on top. Hashing the whole shebang is just to not blatantly giving everyone the information which process is using the directory.

**Comment by tsegismont** [comment]
Sounds good to me, although I think it would be enough to use the JDK API to create a temp directory instead of dealing with user, PID and time.

**Comment by drexljo** [comment]
Don't trust others to do things right, do it yourself. Most devs are not even aware this is an issue.

**Comment by tsegismont** [comment]
If you can't trust your platform development kit or stdlib, it's certainly a big problem :smile:

**Comment by julianladisch** [comment]
> b) specifying the directory in the error message, if there's an access issue

Fixed since 4.0.0-milestone5: https://github.com/eclipse-vertx/vert.x/commit/be7c45466adea76099f2ebd251845fac9e0d6ec0

**Comment by julianladisch** [comment]
> c) removing it in the end, for /tmp is not a trashheap, even if it is cleaned during system boot

/tmp/vertx-cache is not deleted, but all /tmp/vertx-cache/file-cache-{uuid} subdirectories: https://github.com/eclipse-vertx/vert.x/blob/4.0.0-milestone5/src/main/java/io/vertx/core/file/impl/FileResolver.java#L384

**Comment by julianladisch** [comment]
> a) using a dynamic & unique component to the name used, like /tmp/vertx-cache-$(md5($USER$PID$TIME))

The {uuid} part of /tmp/vertx-cache/file-cache-{uuid} is a dynamic and unique component, a random UUID: https://github.com/eclipse-vertx/vert.x/blob/4.0.0-milestone5/src/main/java/io/vertx/core/file/impl/FileResolver.java#L113

**Comment by drexljo** [comment]
> > c) removing it in the end, for /tmp is not a trashheap, even if it is cleaned during system boot
> 
> /tmp/vertx-cache is not deleted, but all /tmp/vertx-cache/file-cache-{uuid} subdirectories: https://github.com/eclipse-vertx/vert.x/blob/4.0.0-milestone5/src/main/java/io/vertx/core/file/impl/FileResolver.java#L384

Does not help, if system permissions forbid other users to create their own subdirectories there. And this is standard behaviour, and the root to the problem specified here.

**Comment by julianladisch** [comment]
The problem is that the `/tmp/vertx-cache` directory needs to be created with world write permissions (like `/tmp)` so that different users can create subdirectories.

**Comment by drexljo** [comment]
Don't ever do that. While it solves the problem, the owner of the directory is allowed delete rights on all subdirectories, so you create the next security problem. 

Unless you find a game breaking problem with the proposal, just go with it and stop trying to do fast-route stuff.

**Comment by tsegismont** [comment]
Perhaps instead the cache dir should have the form `/tmp/vertx-cache-dir-xxxxx` with `/tmp` not being hardcoded but resolved from `java.io.tmpdir`.

Then users who just stick to defaults wouldn't have any issues when running different Vert.x processes on the same machine.

**Comment by julianladisch** [comment]
Yes, as @drexljo pointed out the additional shared `vertx-cache` subdirectory is the problem.
`/tmp/vertx-cache/file-cache-xxxxx/` should be replaced by
`/tmp/vertx-cache-xxxxx/`

**Comment by drexljo** [comment]
Whatever the solution, defaults have to avoid collisions, system permission problems and security issues. I tried to think about all three, being a sysadmin.
How this is coded in the end is beyond my area of expertise. If you decide to reinvent the wheel to fit the criteria, fine by me, as long as the problem is solved in the end and does not create additional ones further down the road.

**Comment by vietj** [comment]
see https://github.com/eclipse-vertx/vert.x/issues/3510 that will implement the remaining parts of this issue
