### ISSUE TITLE
Doc 3.9.x deprecate the Future setHandler and it is always in the dev doc

### ISSUE THREAD

**Issue by based2** [eclipse-vertx/vert.x#3513]
### Questions

Do not use this issue tracker to ask questions, instead use one of these [channels](https://vertx.io/community/). Questions will likely be closed without notice.

### Version

Current online doc - 3.9.2

### Context

In https://vertx.io/docs/guide-for-java-devs/,
future.setHandler is used.

as per 2020-March-9 https://github.com/eclipse-vertx/vert.x/issues/3328, it is deprecated:
// Before
Future<String> fut = getSomeFuture();
fut.setHandler(ar -> ...);

// After
Future<String> fut = getSomeFuture();
fut.onComplete(ar -> ...);

### Do you have a reproducer?

A reproducer is a simple project hosted on GitHub (or another forge supporting git clone operation) that has a build file that can be executed to reproduce the issue.

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

* Link to github project/gist

### Steps to reproduce

1. ...
2. ...
3. ...
4. ...

### Extra

* Anything that can be relevant such as OS version, JVM version

**Comment by tsegismont** [comment]
Wrong repo, moved to https://github.com/vert-x3/vertx-guide-for-java-devs/issues/80
