### ISSUE TITLE
[DNS Client] Access to more DNS features via Default DNS Client

### ISSUE THREAD

**Issue by Joxit** [eclipse-vertx/vert.x#3520]
#### Describe the feature

Have the ability to send DNS queries with additional records (e.g OPT).

I am using vertx's DNS client to retrieve a list of servers. I noticed that via the client, I received a maximum of 3 servers even if there are more (with each DNS request, the IPs change).
I can achieve this with the section `DnsSection.ADDITIONAL` and the record `DefaultDnsOptEcsRecord` in the private `io.vertx.core.dns.impl.DnsClientImp.Query` class

```java
msg.addRecord(DnsSection.ADDITIONAL, DefaultDnsOptEcsRecord(4096, InternetProtocolFamily.IPv4))
```

But this class is not available... The only way to achieve this is rewrite the original DnsClient.

#### Use cases

- Increase the max payload size for responses (and get more than 3 servers)
- Add any available records

#### Contribution

If this feature is interesting for the community, I can draft something

**Comment by vietj** [comment]
@Joxit you are welcome to contribute to the DNS client and add more features
