### ISSUE TITLE
Websocket end handler not called anymore when idle timeout occurs

### ISSUE THREAD

**Issue by elR1co** [eclipse-vertx/vert.x#3527]
### Version

Since version 3.9.0.

Works with 3.8.5.

### Context

Linked to https://github.com/vert-x3/vertx-web/issues/1676

Actually, it seems the problem is on vert.x-core, in relation with the commit linked to this issue : https://github.com/eclipse-vertx/vert.x/issues/3291. Reverting this commit fixes the problem. Anyway, I am proposing a pull request.

### Do you have a reproducer?

See https://github.com/vert-x3/vertx-web/issues/1676

### Steps to reproduce

See https://github.com/vert-x3/vertx-web/issues/1676

**Comment by vietj** [comment]
I am not sure the behavior your are proposing is correct since the close handler and the exception handler should report the event and the developer should not ignore it. The stream end handler should be called only when the last frame is received and the web socket is gracefully closed

**Comment by elR1co** [comment]
I am not sure too. Anyway, as we are already in production with 3.9.1, I need to find a solution quite quickly. I am proposing this solution, as it solves the problem seen in my reproducer and on my real application.

**Comment by vietj** [comment]
we should have a close handler on SockJSSocket to release resources when the socket is closed

**Comment by elR1co** [comment]
I close this as the fix should be linked to vertx-web project instead.
