### ISSUE TITLE
Add support for X-Forwarded-Host header

### ISSUE THREAD

**Issue by cosmin-ionita** [eclipse-vertx/vert.x#3533]
Hello!

We're using Vert.x for a while now and we'd like to thank you for the great work that you put into this amazing project.

We recently came across an issue related to the fact that Vert.x does not handle the [X-Forwarded-Host](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host) header when calling `context.request().host()`.

The role of this header is to keep the original host specified by the client code. If the request goes through multiple proxies, the `Host` header may change, but the `X-Forwarded-Host` header should store the original specified by the client.

We're also using Jetty and we saw that it takes this header into account (basically if you have both `Host` and `X-Forwarded-Host` header on the same request, it will consider the value of the `X-Forwarded-Host` header)

I'd be more than happy to contribute for that feature, but first I'd like to know your opinion about it (if it makes sense to add support for it).

Thank you,
Cosmin

**Comment by vietj** [comment]
this is already supported in vert-web but only in master @cosmin-ionita

**Comment by vietj** [comment]
we could back-port this to 3.x

**Comment by vietj** [comment]
can you move this issue to vert-web ?
