### ISSUE TITLE
Unexpected behavior of Promise.future() in Groovy

### ISSUE THREAD

**Issue by tienquanutc** [eclipse-vertx/vert.x#3536]
### Questions

I use vertx 3.9.2 and run the same code bellow in Java : the console print 1, but in Groovy it prints 4 (Each time calling the future() will create a new Future).

``` java
   public static void main(String[] args) {
        Promise<Long> promise = Promise.promise();
        promise.complete(10L);

        Set<Future<Long>> futures = new HashSet<>(
            Arrays.asList(promise.future(), promise.future(), promise.future(), promise.future())
        );
        System.out.println(futures.size());
    }
```
> vertx 3.9.2, groovy: 2.5.8, gradle: 5.2.1
> Some time Groovy still prints 1, let run gradle clean.

I think it's Groovy's problem but also posting it here so that everyone can check and avoid unnecessary bugs.
You can clone and run at [my repo ](https://github.com/tienquanutc/vertx-promise-groovy-bug/).

**Comment by aaloise** [comment]
My guess is that you are trying to use Groovy directly as a dependency.

Try to replace this:

```
compile 'org.codehaus.groovy:groovy-all:2.3.11'
```
With this

```
compile 'io.vertx:vertx-lang-groovy:3.9.2'
```
Since 3.9.0 Vert.x uses Groovy 3.x

**Comment by tienquanutc** [comment]
> My guess is that you are trying to use Groovy directly as a dependency.
> 
> Try to replace this:
> 
> ```
> compile 'org.codehaus.groovy:groovy-all:2.3.11'
> ```
> 
> With this
> 
> ```
> compile 'io.vertx:vertx-lang-groovy:3.9.2'
> ```
> 
> Since 3.9.0 Vert.x uses Groovy 3.x

Thanks for pointing out problems in dependencies. But I use vertx-lang-groovy as dependency. Try clean Gradle then run, clean Gradle then run ... In some case, it still prints out 4

![image](https://user-images.githubusercontent.com/27769580/90471675-091d5180-e149-11ea-8caf-ebf48098c337.png)

**Comment by tsegismont** [comment]
This does not look related to Vert.x core. Can you please open an issue in the `vertx-lang-groovy` repo? Thank you.
