### ISSUE TITLE
New method: AsyncMap::setTtl

### ISSUE THREAD

**Issue by ruslansennov** [eclipse-vertx/vert.x#3537]
In addition to the existing method `AsyncMap::put(K k, V v, long ttl, Handler<AsyncResult<Void>> completionHandler)` it is very useful to add a new method `AsyncMap::setTtl(K k, long ttl, Handler<AsyncResult<Boolean>> completionHandler)`. There is a corresponding method in hazelcast's `IMap`, for other implementations we can return `false`.
I can try to prepare a PR if it is approved

**Comment by tsegismont** [comment]
To avoid a HZ specific feature, the new method should work with the local `AsyncMap` implementation too.

Also, can you look how this could be implemented with other cluster managers too?

**Comment by vietj** [comment]
if that's Hazelcast specific, could we have this part rather of an HZ AsyncMap in Hazelcast instead ?

**Comment by ruslansennov** [comment]
Hi @tsegismont @vietj 

> To avoid a HZ specific feature, the new method should work with the local AsyncMap implementation too.

sure

> Also, can you look how this could be implemented with other cluster managers too?

it will take some time but i will try

> if that's Hazelcast specific, could we have this part rather of an HZ AsyncMap in Hazelcast instead ?

we can also define a new method in the `AsyncMap` interface like this:

```java
    default void setTtl(K k, long ttl, Handler<AsyncResult<Boolean>> completionHandler) {
        completionHandler.handle(Future.failedFuture("Not implemented yet"));
    }
```

this will avoid casting `AsyncMap` to `HazelcastAsyncMap`/`HazelcastInternalAsyncMap`
