### ISSUE TITLE
Remove future factory

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#3538]
Vert.x provides a `FutureFactory` SPI.

With Vert.x 4 using relying more on futures, we need to precisely control the implementation of `io.vertx.core.Future` in order to deliver the most performing and reliable model.

Therefore we remove this SPI in Vert.x 4.0

**Comment by pmlopes** [comment]
This is not good for `es4x` as I implement the future SPI to add one extra method required for graaljs in order to allow handling vert.x Futures as javascript `Thenable` which means they can be used with `async` / `await` code blocks.

Removing it, means we can't use `async` / `await` anymore.

**Comment by pmlopes** [comment]
For reference here's the es4x code: https://github.com/reactiverse/es4x/tree/develop/es4x/src/main/java/io/reactiverse/es4x/impl/future

**Comment by vietj** [comment]
ok, we might make it come back but I fear this will break

**Comment by vietj** [comment]
I mean we can revert it, but it might break for ES4X
