### ISSUE TITLE
DatagramSocket multicast group listen improvement

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#3540]
The `DatagramSocket#listenMulticastGroup(String, Handler<AsyncResult<DatagramSocket>>)` is almost impossible to use because it will not be able to select a valid network interface, ending up with:

```
SEVERE: Unhandled exception
java.lang.NullPointerException: networkInterface
	at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:33)
	at io.netty.channel.socket.nio.NioDatagramChannel.joinGroup(NioDatagramChannel.java:409)
	at io.netty.channel.socket.nio.NioDatagramChannel.joinGroup(NioDatagramChannel.java:371)
	at io.netty.channel.socket.nio.NioDatagramChannel.joinGroup(NioDatagramChannel.java:365)
	at io.vertx.core.datagram.impl.DatagramSocketImpl.listenMulticastGroup(DatagramSocketImpl.java:96)
```

Vert.x delegates the call to the Netty datagram channel joinGroup(InetAddress) which fails. This method is actually not tested in Netty, which makes me think that it is error prone.

We should either

1/ keep it and do a better job at finding a valid network interface
2/ an issue should be opened in Netty to improve the behavior of this method (perhaps it is not possible)
3/ the method should be deprecated in Vert.x 3 and removed in Vert.x 4 to force users to provide a network interface

**Comment by ViToni** [comment]
Could this be a cause for https://github.com/eclipse-vertx/vert.x/issues/2206 ?

**Comment by vietj** [comment]
@ViToni indeed, I will close the issue you mentioned and we should make a decision on this before Vert.x 4.0 is released

**Comment by doctorpangloss** [comment]
Yes you might want something like what was done in the reproducer here - https://github.com/hiddenswitch/udp-broadcast-reproducer/blob/master/src/main/java/udp/broadcast/reproducer/HeuristicNetworkInterface.java - that works around these issues

Network interface names on Linux, Windows and macOS are a big to-do though. In my experience for development environments it's robust. I only deploy to Linux containers in cloud environments, but most of the time UDP broadcast is blocked there anyway so it doesn't really make sense to diagnose that. In my opinion you should see if any interfaces support multicast in the first place, then if they do, guess which one is the true primary based on heuristics on the name using common VM prefixes (vSwitch, Host, Virtual, etc.) and attributes like loopback / virtual.
