### ISSUE TITLE
`Http1xServerResponse.setStatusCode()` doesn't check `headerWritten`

### ISSUE THREAD

**Issue by blindpirate** [eclipse-vertx/vert.x#3552]
### Context

Today I noticed that if you set status code after writing to `Http1xServerResponse`, the status code will be discarded silently. Seems like `Http2ServerResponseImpl` does check if the header is already written before setting status code: https://github.com/eclipse-vertx/vert.x/blob/b8e58e5ce93aa5d36ee47beec87ce046a4b2df20/src/main/java/io/vertx/core/http/impl/Http2ServerResponseImpl.java#L158

This confuses me a lot. I think an early exception would be better in this case.

**Comment by vietj** [comment]
right, there are a few methods like this that should be changed

**Comment by vietj** [comment]
Closed by https://github.com/eclipse-vertx/vert.x/issues/3568
