### ISSUE TITLE
Stream based DSL

### ISSUE THREAD

**Issue by egelke** [eclipse-vertx/vert.x#3553]
#### Feature description

Provide a DSL (domain specific language) that can be used to execute chain sync and async methods on a context object.  The context object contains the state and provides business methods to manipulate that state.
**Sync logic** is provided in a classical methods, with the constraint that methods returns void and the outcome is reflexed in the state of the context object.
**Async logic** is split in 2 business methods.  The first method contains all logic leading up to the async call that gets a `Handler<AsyncResult>` that is needed to execute the 'technical' async method and in general stops when the technical methods is called.  The second business method is invoked when the result is ready and should processes it, not returning any value but reflex it in the state of the context object. 

An example of such an context object:

```java
class Ctx {
    private final String path;
    private String output;

    public void syncBusiness()  { ... }

    public void startAsyncBusiness(Future<HttpResponse<Buffer>> next) { 
        WebClient.create(vertx).get(path).send(next);
    }

    public void processAsyncBusinessResult(HttpResponse<Buffer> result) {
        output = result.body().toString();
    }
 }
```

Vert.x provides a interface, with implementation, to chain the operations as a simple sequence but also in more complex ways like loops, conditional, ...
  
An example of such a chaining:

```java
Sequencer.start(new TxnCtx(txn))
    .startVoid(TxnCtx::retrieveInfo)
    .startVoid(TxnCtx::setupConfigParams)
    .split(TxnCtx::getTokenContexts)
    .startAndProcessAsync(TxnTokenCtx::startCreateToken, TxnTokenCtx::processCreateTokenResult)
        .when(TxnTokenCtx::requireSignature)
            .startVoid(TxnTokenCtx::signToken)
        .end()
        .when(TxnTokenCtx::requireEncryption)
            .startVoid(TxnTokenCtx::retrievePublicKeyFromState)
            .when(TxnTokenCtx::requireFetchingOfPublicKeyFromServer)
                .startAndProcessAsync(TxnTokenCtx::startFetchPublicKeyFromServer, TxnTokenCtx::processFetchPublicKeyFromServerResult)
                .startVoid(TxnTokenCtx::savePublicKeyInState)
            .end()
            .startVoid(TxnTokenCtx::encryptToken)
        .end()
    .endForEach(TxnCtx::addTokenToParams)
    .startVoid(TxnCtx::calcBaseUrl)
    .when(TxnCtx::requiresQueryString)
        .startAndProcessAsync(TxnCtx::startCreateQueryString, TxnCtx::processCreateQueryStringResult)
    .end()
    .when(TxnCtx::requiresBody)
        .startAndProcessAsync(TxnCtx::startCreateBody, TxnCtx::processCreateBodyResult)
    .end()
    .finish(TxnCtx::toOperationResponse, response);
```

#### Use cases

Async programming is complicated, handlers do not make for very readable code.  [Async Coordination](https://vertx.io/docs/vertx-core/java/#_async_coordination) helps, but has it limitations.  [RxJava2](https://vertx.io/docs/vertx-rx/java2) is a more complete solution but (to my personal flavor) is a little too complex; both when it comes to writing code and understanding the result.  

The proposed DSL aims to _simply but rich_ async programming by levering the capabilities of Vert.x _core_.  The objective is to protect the developer using Vert.x from the difficulties of async programming and result in code that resembles regular programming as much as possible.

#### Contribution

As you can see from the examples, I have an implementation that I'm willing to share but it definitely needs some refinement and feedback on naming and extra features.

**Comment by jo5ef** [comment]
We're using Vert.x with rxjava (for years now) and I find that the code we produce is very readable and maintainable overall. I agree it is a steep learning curve though : )

**Comment by egelke** [comment]
For me, the main problem with RxJava is that it's and add-on: Most documentation needs to be "translated", some stuff isn't available withtout helpers (even inexplicable stuff like `io.vertx.ext.web.api.contract.openapi3.OpenAPI3RouterFactory.mountServiceInterface(Class, String)`).

It doesn't seem to be very intuitive, but I love to see a full and proper example project that uses Vert.x RxJava2
