### ISSUE TITLE
Evict local lock timed out waiters

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#3570]
Shared data local lock maintains a list of waiters, entries are evicted from this list when on lock release. When a lock times out, it does not remove the entry from the list and instead relies on the cooperation of the lock owners to remove the entry from the list. We can improve this and evict the waiter from the waiters list when the timeout fires.

**Comment by jkurzanski** [comment]
Thanks @vietj I'll check this

**Comment by jkurzanski** [comment]
It’s in production since few days now and this has dramatically reduced our memory footprint. Thanks a lot @vietj !
