### ISSUE TITLE
HttpClientOptions SSL setServerNameIndication API missing

### ISSUE THREAD

**Issue by pantinor** [eclipse-vertx/vert.x#3573]
### Observation
When using vertx HttpClientOptions with the SSL setForceSni option, the server name indicated in the first message of the SSL handshake is the host as specified on the request.

### Expectation
Shall be possihble to indicate the server name explicitly.  Example API usage below with "setServerNameIndicator".  This allows a single address to be used with multiple individual server certificates, while avoiding DNS server changes to provision all the different server names.
```
RequestOptions options = new RequestOptions()
.setMethod(HttpMethod.PUT)
.setHost("proxy.provider.com")
.setPort(8081)
.setURI("/proxy");

HttpClientRequest request = client.request(options);

HttpClientOptions clientOptions = new HttpClientOptions();
clientOptions.setProtocolVersion(HttpVersion.HTTP_2);
clientOptions.setSsl(true);
clientOptions.setUseAlpn(true);
clientOptions.setForceSni(true);
clientOptions.setServerNameIndicator("verizon.provider.com");
```

### Version
3.9.1 and 4.0.0 mil5

### Context
Running secure HTTP2 requests into HttpServer with SNI.

**Comment by pantinor** [comment]
This looks similar to a ticket in vertx-web #805

**Comment by vietj** [comment]
you don't need to do that, instead you can specify an host when building the request and override the host with the host(method) on HttpClientRequest:

```java
RequestOptions options = new RequestOptions()
.setMethod(HttpMethod.PUT)
.setHost("proxy.provider.com")
.setPort(8081)
.setURI("/proxy");

HttpClientRequest request = client.request(options);
request.setHost("verizon.provider.com");

// Continue with request
```

**Comment by vietj** [comment]
with Vert.x 4 you will do differently though, we simplified the API and instead you need to specify a SocketAddress, e.g

```java
RequestOptions options = new RequestOptions()
.setMethod(HttpMethod.PUT)
.setAddress(SocketAddress.inetSocketAddress("proxy.provider.com"))
.setHost("verizon.provider.com"")
.setPort(8081)
.setURI("/proxy");
```

**Comment by pantinor** [comment]
@vietj Thanks I will try it this morning and update you.  I had refactored to use WebClientOptions, i don't think we can use that for setHost.  Will refactor back.  I have been bouncing back and forth between 3.9 and 4.0 as well.

**Comment by vietj** [comment]
if you are using WebClient then you have a virtualHost method you can call
that will achieve that.

**Comment by pantinor** [comment]
For WebClientOptions I could only see setDefaultHost, there was no setVirtualHost function.  I must be missing something.

**Comment by vietj** [comment]
this is on the HttpRequest object, this is dynamic

**Comment by pantinor** [comment]
I got it working with 3.9.1 and the core http client request.  Thanks again!
