### ISSUE TITLE
Add some form of attribute storage to HttpServerRequest

### ISSUE THREAD

**Issue by stuartwdouglas** [eclipse-vertx/vert.x#3579]
At the moment there is no way to attach arbitrary data to the HttpServerRequest. If you are using Vert.x Web the RoutingContext has the ability to store arbitrary data in the context, it would be very helpful if this was also added to the HttpServerRequest (with the routing context changed so it's attributes are backed by the request, so you don't have two attribute maps).

Some of the use cases we have for this in Quarkus:
- The metrics object that is created by io.vertx.core.spi.metrics.HttpServerMetrics#requestBegin is not available to any handlers that want to add data to it, and there is no way to propagate it to these handlers. If we had an attribute map we could store it as an attribute.
- We have a QuarkusRequestWrapper that adds some extra functionality (such as configurable SameSite support for cookies), but there is no way to access this object once it has been passed into the router (as the router also wraps the request). If there was an attribute map this would be much easier (at the moment we use a fake Cookie implementation and use the cookies map as an attribute map).

**Comment by vietj** [comment]
Vert.x 4 provides a context per HttpServerRequest which can be used to do that.

When an HTTP server request is created, the current Vert.x context is duplicated (a lightweight copy that references the original context to reuse the same event loop), this context provides a local attribute map is an arbitrary storage for the use case that you describe. Such duplicate is valid until the HTTP request ends.

The use case that is supported in Vert.x 4 is provided a continuation like storage for tracing. How does that sound ?

**Comment by ebullient** [comment]
That will probably work. I am also looking forward to the HttpServerRequestMetrics.requestRouted callback. =)

I don't know how long Quarkus will be using the Vertx 3.x branches... :sigh:

**Comment by vietj** [comment]
we can add a request routed callback to the metrics, although originally it
was geared toward tracing

**Comment by ebullient** [comment]
Well. I approximated with 3.9.x this way: https://github.com/quarkusio/quarkus/pull/12209/files#diff-fa759749ee1a903c156808cd128ecea8R74 
I'm not sure how happy I am with that, but I may be stuck. 
Having context on the HttpServerRequest will definitely remove some awkwardness in that path, which is preferred.

Tracing and Metrics require some of the same data to be available (though what is read and how it is used is different).

**Comment by vietj** [comment]
See https://github.com/eclipse-vertx/vert.x/issues/3792, this provides access to the request context which provides a local data map that can be used for storing request related attributes

**Comment by ebullient** [comment]
I think the required methods were added to 4.0.3... 
#3792 was closed w/o being integrated.
https://github.com/eclipse-vertx/vert.x/commit/b7ebdcbcdf7c4284dd9489103ac514ef3e1a9253
and https://github.com/eclipse-vertx/vert.x/commit/b7ebdcbcdf7c4284dd9489103ac514ef3e1a9253
should resolve the issue
