### ISSUE TITLE
Integrate DSL-Json in vertx for default data binding instead of Jackson 

### ISSUE THREAD

**Issue by prasannajoshi2121** [eclipse-vertx/vert.x#3580]
Hi Team , 

please look DSL-JSON library as default option for data binding instead of jackson , its quite faster for serialization/deserialization 

https://github.com/ngs-doo/dsl-json

**Comment by pmlopes** [comment]
@prasannajoshi2121 please have a look at the SPI: https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/spi/json/JsonCodec.java

If you implement this SPI and add the service loader metadata you can easily plug whatever JSON library you wish in vert.x

**Comment by prasannajoshi2121** [comment]
Hi @pmlopes ,

Sure , let me try it out. thanks
