### ISSUE TITLE
Expect to configure decoders when using NetServer

### ISSUE THREAD

**Issue by wangjunniit** [eclipse-vertx/vert.x#3582]
#### Describe the feature

When I use the following code
```java
NetServer server = vertx.createNetServer();
server.connectHandler(socket -> {
  socket.handler(buffer -> {
    System.out.println("I received some bytes: " + buffer.length());
  });
});
```
The objects I receive are always of type Buffer,Is it possible to add a configuration item to be able to add netty decoders,and adding a method to the NetSocket interface to receive the decoded object.
```java
NetSocket handlerMessage(Handler<Object> obj);
```
It works like this
```java
    NetServer server = vertx.createNetServer();

    server.configureChannelPipeline(pipeline->{
      //pipeline is io.netty.channel.ChannelPipeline
      pipeline.addFirst("myDecoder", new MyDecoder());
    });

    server.connectHandler(socket -> {
      socket.handlerMessage(msg -> {
        //msg is of type Object
        if(msg instanceof CustomMessage){
          //...
        }
      });
    });
```
Or is there a way to implement this feature in the current version

**Comment by vietj** [comment]
@wangjunniit you can do that by casting `NetSocket` to `NetSocketInternal` - this is explained here http://www.julienviet.com/advanced-vertx-guide/#_using-netty-tcp-codecs
