### ISSUE TITLE
Generic keystore based KeyCert/Trust options

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#3591]
Vert.x provides specialized usage of `KeyStore` for loading `KeyCertOptions` and `TrustOptions` as `JksOptions` and `PfxOptions`.

Sometimes it can be desirable to use another implementation such as the ones provided by Bouncy Castle. We can add a more generic `KeyStoreOptions` to serve that purpose.

Fixes also https://github.com/eclipse-vertx/vert.x/issues/3262

**Comment by sberyozkin** [comment]
@vietj Hi Julien, can it be backported please to the next 3.9.x as well as I've stuck with my BC FIPS tests right now :-)
