### ISSUE TITLE
WebClient HttpRequest.sendStream() hangs when server close connection

### ISSUE THREAD

**Issue by VMalko** [eclipse-vertx/vert.x#3598]
### Version

vertx-core: 3.8.5
vertx-web: 3.8.5
vertx-web-client: 3.8.5

### Context
We have noticed that WebClient HttpRequest.sendStream() hangs when Server close connection 

There are a few steps to catch it:
1. Execute WebClient HttpRequest.sendStream (https://vertx.io/docs/kdoc/vertx/io.vertx.ext.web.client/-http-request/send-stream.html) to send body as stream to external server. In our case it is Vertx HttpServer.
2. After some time external HttpServer close connection by some reason (machine restarted/fall down or idleTimeout is reached). 
3. We expect to see that client will catch error "connection was closed". But there are no any errors and client simply hangs... and waiting for response...

That is really strange for us because other method HttpRequest.sendBuffer catch it. 

### Reproducer
See project on github. Class WebClientSendStreamTest.java and method uploadStreamRequestTest()

https://github.com/VMalko/vertx-send-stream/blob/master/src/test/java/WebClientSendStreamTest.java

### Steps to reproduce

1. Execute method uploadStreamRequestTest() of class WebClientSendStreamTest.java
2. After 2 sec HttpServer will close connection
3. Client will hangs on it...
4. ...

**Comment by vietj** [comment]
moved to vertx-web https://github.com/eclipse-vertx/vert.x/issues/3598
