### ISSUE TITLE
Vertx.deployVerticle(…); calls completion handler on different context

### ISSUE THREAD

**Issue by JojOatXGME** [eclipse-vertx/vert.x#3600]
I'm using `io.vertx:vertx-core:3.9.3` and I have some code in a *Verticle* that looks similar to this:

```java
assert Vertx.currentContext() == context;
vertx.deployVerticle(someVerticle, new DeploymentOptions().setWorker(true), result -> {
  assert Vertx.currentContext() == context; // <-- AssertionError is thrown here
  ...
});
```

The second assertion sometimes fails. I expect `deployVerticle(…)` to always call the completion handler in the context from where it was called. Was this assumption wrong or is this a bug in *Vert.x*? The *Javadoc* does not say anything about it but here is a quote from [the manual](https://vertx.io/docs/vertx-core/groovy/#_standard_verticles):

> When you call any other methods that takes a handler on a core API from an event loop then Vert.x will guarantee that those handlers, when called, will be executed on the same event loop.

I also noticed that the assertion only seems to fail when the deployment fails with the following reason.

> Verticle deployment failed.Could not be added as child of parent verticle

In my experience, this means that the Verticle where I call the method was stopped. When the assertion fails, the context returned by `Vertx.currentContext()` outside and inside the completion handler are named like `EventLoopContext@35d0ced2` and `io.vertx.core.impl.WorkerContext@1bf4c13e` respectively. (Maybe Vert.x calls the handler from the context of the worker which was about to be started?)

**Comment by tsegismont** [comment]
Thanks for the report, this looks like a bug.

When invoked from a verticle, the context of the deploy callback should be
the same as of the verticle, regardless of the result

**Comment by JojOatXGME** [comment]
I was able to reproduce the issue outside of the project were I found the issue. At least on my machine. The reproduction depends on a race condition. Not sure if it works for you.
https://github.com/JojOatXGME/vertx-issue-3600/blob/main/src/main/java/Issue3600.java

**Comment by tsegismont** [comment]
@JojOatXGME thanks. I could reproduce in a test and created a PR for 3.9. We're releasing 3.9.4 this week
