### ISSUE TITLE
Allow JsonObject.put(Entry) - or - let MultiMap.forEach return (key, value)

### ISSUE THREAD

**Issue by Stwissel** [eclipse-vertx/vert.x#3609]
#### Describe the feature

Small improvement to code readability when dealing with Maps/Multimaps

When I want to store a map (after filter, map etc) into a JsonObject I can write

```
Map myMap = .....;
JsonObject result;

myMap.forEach(result::put);
```

with a MultiMap I need to write:

```
MultiMap myMultiMap = .....;
JsonObject result;

myMultiMap.forEach(entry -> result.put(entry.getKey(), entry.getValue());
```

Letting `JsonObject.put` accept an `Entry<String, Object>` would make code for Map and Multimap look similar/nicer
Of course having MultiMap emit (k,v) would be more universal, but a breaking change (which might not be worth it_

#### Use cases
Clean code

#### Contribution

I could give it a stab

**Comment by jo5ef** [comment]
There is also a constructor you can use so you don't have to copy your map: `var result = new JsonObject(myMap);`. You'll need to convert your MultiMap to a Map first but I think doing this explicitly is good because json is by definition not compatible with a MultiMap.

**Comment by Stwissel** [comment]
@jo5ef yep. For Map we have all the options. Typically I write something like:

`map.filter(this::cleanup).map(this::convert).forEach(json::put);` , but using the Map collector works too.

From your comment I would conclude: it might be more interesting to "teach MultiMap some Map"

something like `toMap(MultiMapOptions.FirstOnly)` or `MultiMapOptions.Concatenate` or `MultiMapOptions.ListValues`

Then new JsonObject(Map<String>,List<String>) would do the trick

**Comment by Stwissel** [comment]
I use a little helper function. Might be an interesting addition to the MultiMap interface:

```java
Map<String, String> collapse(final MultiMap mm) {
    return mm.entries()
        .stream()
        .collect(Collectors.groupingBy(Entry::getKey,
            Collectors.mapping(Entry::getValue, Collectors.toList())))
        .entrySet()
        .stream()
        .collect(Collectors.toMap(Entry::getKey, e -> String.join(",", e.getValue())));
  }
```
