### ISSUE TITLE
Issue on vertx4 milestone 5 replacement of VertxFactory class.

### ISSUE THREAD

**Issue by oscarfh** [eclipse-vertx/vert.x#3610]
Hi,
I am trying to upgrade my vertx 3.6.3 app to vertx 4 and I noticed that there is one issue that might be a problem in [this vertx change](https://github.com/eclipse-vertx/vert.x/commit/2b78689ad39c565d34574354bd420ec5ebc0b397#diff-15b68f43389fc8477976ca7d14c461c556f07bfdd2ff42e14dd87f21ccb13721).
It moved `io.vertx.core.spi.VertxFactory` to `io.vertx.core.impl.VertxFactory`, but the file in `META-INF/` is still called `io.vertx.core.spi.VertxFactory`, so, whenever I call `ServiceHelper.loadFactory(VertxFactory.class)`; I get

> Cannot find META-INF/services/io.vertx.core.impl.VertxFactory on classpath

Shouldn't the file be renamed too?

**Comment by vietj** [comment]
This factory is not anymore a META-INF service, I removed the file, thanks for noticing and opening this issue.
