### ISSUE TITLE
Cut 4.0.0.Beta4 release 

### ISSUE THREAD

**Issue by jvican** [eclipse-vertx/vert.x#3614]
#### Describe the feature

Hey folks, I've seen there have been some important fixes in latest master regarding WebSockets -- I think some of the latest fixes fix some issues I've seen in production. Would it be possible to cut a new beta release? The last one, 4.0.0.Beta3, was released almost two months ago.

**Comment by vietj** [comment]
we will release 4.0.0.CR1 in the coming days

**Comment by jvican** [comment]
Thanks @vietj, looking forward to it.
