### ISSUE TITLE
Don't disable resource leak detector if netty property is set

### ISSUE THREAD

**Issue by jvican** [eclipse-vertx/vert.x#3616]
#### Describe the feature

Don't disable resource leak detector in netty if the netty system property for the resource leak detector is set. Vertx disables it in a static initializer and it would be best that before disabling it checks if [`io.netty.leakDetection.level`](https://github.com/netty/netty/blob/e9b28e76a366dadaf6da4375c503f670ec3e3ae4/common/src/main/java/io/netty/util/ResourceLeakDetector.java#L46) is set. If it is set, then vertx won't disable the resource leak detector.

#### Use cases

This is useful for those folks that want to check that no resource leaks are ever found in their code using the current vertx release as well as future releases.

**Comment by vietj** [comment]
can you contribute a patch for this @jvican ?

**Comment by jvican** [comment]
Yeah, will take care of this one
