### ISSUE TITLE
Vert.x Session issue set-cookie header at per request after session.regenerateId() method invoked

### ISSUE THREAD

**Issue by ex34toway** [eclipse-vertx/vert.x#3618]
### Questions

Vert.x Session issue set-cookie header at per request after session.regenerateId() method invoked

### Version

4.0.0.Beta3

### Context

final User user = res.result();
ctx.setUser(user);
if (session != null) {
    session.regenerateId();
    String returnUrl = session.remove(returnURLParam);
    if (returnUrl != null) {
        ResponseUtils.success(ctx, new JsonObject().put("returnUrl", returnUrl));
    }
}
ctx.end("login success");

### Steps to reproduce

1. session.regenerateId();
2. next request protected restful api always issue set-cookie header

### Extra

I think SessionHandlerImpl flush session after remove old session, should set session.renewed = false.

**Comment by vietj** [comment]
can you move this issue to Vert.x Web repository ?  https://github.com/vert-x3/vertx-web
