### ISSUE TITLE
Documentation rework

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#3626]
Vert.x documentation is based on callbacks.

While the documentation mentions futures, those are introduced mainly for composition purpose.

We need to rework the introduction to introduce futures early.

**Comment by vietj** [comment]
cc @jponge

**Comment by jponge** [comment]
The first occurence of an asynchronous operation that has a callback (and hence a `Future`) is `executeBlocking`, see https://vertx-web-site.github.io/docs/vertx-core/java/#blocking_code

I think we could have a subsection before about asynchronous operations where we do something simple (e.g., starting a HTTP server, showing first a callback (e.g., `listen`) then a `Future`-variant, and quickly discuss the 2 options without digging into the details.

Also the next section is about composing futures (see https://vertx-web-site.github.io/docs/vertx-core/java/#_concurrent_composition) and they haven't been introduce before.

**Comment by vietj** [comment]
thanks for helping @jponge
