### ISSUE TITLE
[Regression] Vertx4 HttpServerRequest.uploadHandler() erases context.

### ISSUE THREAD

**Issue by oscarfh** [eclipse-vertx/vert.x#3629]
I have a code snippet (link to the github repo below) that works on vertx4 milestone4, but not with vertx4 >= milestone5.
At first I thought it could be related to https://github.com/eclipse-vertx/vert.x/issues/3601, but this does not seem to be the case.

# Problem
Vertx context (`Vertx.currentContext()`) is lost inside `HttpServerRequest.uploadHandler()`

# Expected behavior
Vertx context (`Vertx.currentContext()`)  is kept inside `HttpServerRequest.uploadHandler()`

# Code example
```
public class MyHandler implements Handler<RoutingContext> {
    @Override
    public void handle(RoutingContext routingContext) {
        final HttpServerRequest event = routingContext.request().getDelegate();
        event.setExpectMultipart(true);

        Context context = Vertx.currentContext(); // Context is NOT null here
        event.uploadHandler(event1 -> {
            Single.create(new io.vertx.rx.java.SingleOnSubscribeAdapter<>(fut -> {
                Context context2 = Vertx.currentContext(); // Context2 is null here
            })).subscribe(o -> routingContext.end("check"));
        });

    }
}
```

As I said, with vertx4 milestone 4, both `context` and `context2` are *not* null, while from milestone 5 onward, `context2` is `null`.

# Github project with reproducible test
https://github.com/oscarfh/vertx-upload-handler-context
The test `ATest#start_server` will fail, but if you downgrade to vertx milestone 4, it passes.

**Comment by jekkel** [comment]
This is still present in 4.0.0 final. I guess because @pmlopes PR has not been merged yet, instead its milestone has been changed to 4.0.1. For the sake of consistency: this issue should be open and targeted towards 4.0.1, don't you think @vietj ?

**Comment by vietj** [comment]
which pr is that ?

**Comment by jekkel** [comment]
https://github.com/eclipse-vertx/vert.x/pull/3639

**Comment by oscarfh** [comment]
Can someone please reopen this, since it was not included in 4.0.0RC2 or 4.0.0.Final? @pmlopes and @vietj

**Comment by vietj** [comment]
this fix has not been take as is, but https://github.com/eclipse-vertx/vert.x/pull/3639 fixes it equally

**Comment by vietj** [comment]
if you found a regression then it's a new bug and you should open it with a reproducer

**Comment by oscarfh** [comment]
@vietj ok, thanks a lot!

**Comment by oscarfh** [comment]
I can confirm this still happens.
I will prepare a project to reproduce this.
I noticed that the commit db3d799bb613a4f0f5516365c5bf96cc4dadee0d is not on master, is there a reason for that?

**Comment by vietj** [comment]
which commit is it ? 

if you can provide a reproducer then it's great

**Comment by oscarfh** [comment]
This one https://github.com/eclipse-vertx/vert.x/pull/3639/commits/766a6ea3d7fc935141755b9d63c5cd5292ef450f
The commit itself and the contents are missing.
Nevertheless, I applied them my a local version of vertx and ran my system and it did not solve. I will start working on a reproducer right now.

**Comment by oscarfh** [comment]
@vietj I can confirm this still exists and that the reproducer I created for this issue is still reproducing it.
I created a new ticket #3711 as you asked, but I have not added any new information (yet) because I do not have it. I am still researching.
I will add new things in the new ticket, if I find anything.
