### ISSUE TITLE
Filesystem.readDir fail on file with space in filename

### ISSUE THREAD

**Issue by peetboy** [eclipse-vertx/vert.x#3630]
### Version

3.9.4

### Context

Filesystem methods for read directory failing when directory contains file with space character in filename.

### Root cause

The code is failing in FileResolver.getValidClassLoaderResource because isValidCachePath returns false
```
    private static URL getValidClassLoaderResource(ClassLoader cl, String fileName) {
        URL resource = cl.getResource(fileName);
        return resource != null && !isValidCachePath(fileName) ? null : resource;
    }
```
In isValidCachePath 
```
if (!CACHE_PATH_CHECKER.test(c)) { //where c = 32
     return false;
}
```

### Steps to reproduce

1. Put "some file.txt" into resources.
2. Use Filesystem.readDir(path, handler).

### Extra

Windows 7, Azul Java 11

**Comment by vietj** [comment]
The windows JDK does not seem to accept space in names, see https://github.com/frohoff/jdk8u-jdk/blob/master/src/windows/classes/sun/nio/fs/WindowsPathParser.java#L171

Do you know more about this ?
