### ISSUE TITLE
Multiple Verticles deployed in isolation If a verticle is undeployed and then deployed again 50% of the requests work

### ISSUE THREAD

**Issue by arad1994** [eclipse-vertx/vert.x#3637]
### Version

Vertx-Core -> 4.0.0-milestone5

### Context

If a container has multiple verticle deployed in isolation, if we restart one of those verticles, It was noticed that two handlers registered locally at the exact same address. It turns out that the restarted vertcile did not remove the handler registration from the address, On further debugging it was noted that the registration flow of ClusteredEventBus was not matching the unregistration flow.

### Steps to reproduce

1. Deploy multiple verticles under a single container
2. Restart one of the verticles.
3. Then only 50% of the  request would work, two handlers registered locally at the exact same address

This PR fixes the above issue->  https://github.com/eclipse-vertx/vert.x/pull/3636

**Comment by tsegismont** [comment]
Fixed in #3663
