### ISSUE TITLE
Options are not redirected to redeploy

### ISSUE THREAD

**Issue by tiparega** [eclipse-vertx/vert.x#3652]
### Version
3.9.4

### Context

I was developing a vertx verticle using redeployment. When adding metrics, it seemed to not honor options properties. If I removed redeploy, it started working.

### Steps to reproduce

1. Add dependencies `io.vertx.vertx-micrometer-metrics` and `io.micrometer.micrometer-registry-prometheus`
2. In the start of the verticle create an httpServer and add this:
> router.route("/metrics").handler(PrometheusScrapingHandler.create());
> MeterRegistry registry = BackendRegistries.getDefaultNow();
> new JvmMemoryMetrics().bindTo(registry);
> new JvmThreadMetrics().bindTo(registry);
3. start with redeploy: `run  -options "{\"metricsOptions\": {\"enabled\": true,\"prometheusOptions\": {\"enabled\": true}}}" com.package.MyVerticle --launcher-class=io.vertx.core.Launcher --redeploy=**/*.java`
4. Fails:
> 2020-11-17 18:11:47.390 [GRAVE        ] io.vertx.core.impl.ContextImpl                               Unhandled exception 
> java.lang.NullPointerException
> 	at io.micrometer.core.instrument.Gauge$Builder.register(Gauge.java:190)
> 	at io.micrometer.core.instrument.binder.jvm.JvmMemoryMetrics.bindTo(JvmMemoryMetrics.java:62)

### Extra
If you remove --redeploy:
`run  -options "{\"metricsOptions\": {\"enabled\": true,\"prometheusOptions\": {\"enabled\": true}}}" com.package.MyVerticle --launcher-class=io.vertx.core.Launcher`
It does work and you can see the metrics.

I found this could be a missing in `io.vertx.core.impl.launcher.commands.RunCommand.startAsBackgroundApplication` method. It copies "allArguments", but options are not included (maybe because they are in `BareCommand`), as others like ha, cluster, conf, etc. Those others are added manually, but not options.
I tried debugging to add options (just like conf, as two arguments) and it works. I suggest to added, don't know about what could imply, but seems to be reasonable to me.

**Comment by vietj** [comment]
can you provide a pull request for this @tiparega ?

**Comment by tsegismont** [comment]
Closed in b23ddc9f84d9dbd30e4a024b626947252ebb1cab
