### ISSUE TITLE
File resolver does partial cached class path directory listing

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#3654]
The implementation takes care of unpacking the full content of an file's parent directory to ensure that listing this directory will return all the entries in the class path.

This works only for a single level and therefore the issue happens with 2 directories, e.g resolving the file `/foo/bar/juu` leads to listing `/foo/bar` to be correct but `/foo` will only contain `/foo/bar`.

There are several possible strategies to solve this:

- simply unpack everything recursively: this is simple but can lead to performance issues, i.e it might introduce some spikes when cache is populated
- add some state to record whether the listing is full or partial, this could be saved on disk (a dot file)
- we only cache file and not directories, so directory listing would trigger a class path resolution and content listing, note this impacts the `FileResolver` API that always returns a `File` for a directory or a file.

Reproducer: modify `FileResolverTestBase`

```java
  @Test
  public void testReadFileInDirThenReadDir() {
    Buffer buff = vertx.fileSystem().readFileBlocking("webroot/subdir/subfile.html");
    assertEquals(buff.toString(), "<html><body>subfile</body></html>");
    Function<List<String>, Set<String>> fx = l -> l.stream().map(path -> {
      int idx = path.lastIndexOf(File.separator);
      return idx == -1 ? path : path.substring(idx + 1);
    }).collect(Collectors.toSet());
    Set<String> names = fx.apply(vertx.fileSystem().readDirBlocking("webroot/subdir"));
    assertEquals(names, new HashSet<>(Arrays.asList("subdir2", "subfile.html")));
    names = fx.apply(vertx.fileSystem().readDirBlocking("webroot"));
    assertEquals(names, new HashSet<>(Arrays.asList("subdir", "somefile.html", "someotherfile.html", "this+that")));
  }
```

**Comment by pmlopes** [comment]
The Linked PR will fix this issue
