### ISSUE TITLE
Generated Converters ignore base classes - JSON cannot be used to configure RabbitMQ

### ISSUE THREAD

**Issue by YaytayAtWork** [eclipse-vertx/vert.x#3661]
### Version

4.0.0.CR1

### Context
From RabbitMQClient:
```
  static RabbitMQClient create(Vertx vertx, JsonObject config) {
    return new RabbitMQClientImpl(vertx, new RabbitMQOptions(config));
  }
```
From RabbitMQOptions:
```
public class RabbitMQOptions extends NetClientOptions {

  public RabbitMQOptions(JsonObject json) {
    super(json);
    init();
    RabbitMQOptionsConverter.fromJson(json, this);
  }
```
From RabbitMQOptionsConverter:
```
  public static void fromJson(Iterable<java.util.Map.Entry<String, Object>> json, RabbitMQOptions obj) {
    // No mention of super
    // No mention of NetClientOptions 
    // No mention of reconnectAttempts (or a bunch of other properties that RabbitMQ requires)
  }
```

### Steps to reproduce

1. Create a JsonObject containing reconnectAttempts.
2. Create a RabbitMQOptions from it.
3. See that the reconnectAttempts is set to the default value (which is no reconnects)

### Extra

From a RabbitMQ point of view this means that PR [106](https://github.com/vert-x3/vertx-rabbitmq-client/pull/106) breaks JSON configuration quite terminally.
I think this is a fundamental problem with the generated Converters, but it might be felt that the fix should just be in RabbitMQOptions (calling each converter in turn).

**Comment by YaytayAtWork** [comment]
Ah, looks like the inheritConverter annotation option is supposed to solve the problem.
From looking at the DataObjectHelperGen code I think that just needs to be applied to the RabbitMQOptions, rather than to all the ancestors, to solve my specific problem - but don't we usually want ancestors considered for to/fromJson methods?

**Comment by vietj** [comment]
can you reopen this issue in the RabbitMQ project ? it does not seem to be for Vert.x Core.

**Comment by YaytayAtWork** [comment]
I can, and will, but NetClientOptions (not in RabbitMQ) has the same problem.
I can't think of a reason why you wouldn't want inheritConverter, but it's hardly used.
