### ISSUE TITLE
Connection pool exhausted when proxying with Pump and client closes connection prematurely

### ISSUE THREAD

**Issue by cartmanez** [eclipse-vertx/vert.x#3668]
### Version

3.3.3, 3.9.4

### Context

Connection pool exhausted when proxying requests with Pump and application client closes connection before it is fully processed by the server.

### Do you have a reproducer?

https://gist.github.com/cartmanez/e719e753fadec4b53058be948617a898

### Steps to reproduce

To reproduce I run 
```
ab -n 1000 -c 50 http://localhost:8080/
```
and stop it in the middle of execution. After that connection pool is exhausted and any request to demo app just hangs forever.
Output of lsof -i shows that there are unclosed by the app connections that eventually have CLOSE_WAIT status

### Extra

This issue seems to be exact duplicate of https://github.com/eclipse-vertx/vert.x/issues/1244 . The issue was closed however I doubt it was fixed.

Relevant discussions in google groups:
https://groups.google.com/g/vertx/c/77_JUc3mEuY/m/7akDHTrXCwAJ
https://groups.google.com/g/vertx/c/9x2p7AGx7kM/m/6w4mIfXQCgAJ

As far as I understand my possible solutions are a) stop using Pump or b) stop using connection pooling. I do not like both

**Comment by vietj** [comment]
@cartmanez writing a proxy is quite difficult, have you tried instead of using Pump to use the new Pipe operation ?

**Comment by vietj** [comment]
the Pipe is an improved Pump

**Comment by vietj** [comment]
also we do have a project coming in Vert.x 4 that does exactly what you are trying to achieve and takes care of all failure cases

**Comment by vietj** [comment]
https://github.com/vietj/vertx-http-proxy

**Comment by vietj** [comment]
you can find forks of this project that run on Vert.x 3 : https://github.com/hgomez/vertx-http-proxy

**Comment by vietj** [comment]
my point is that the code in the proxy should take care of properly handling failures when there is a inbound or outbound connection failure and make a best effort to serve the client proxy

**Comment by vietj** [comment]
and the pool is likely exhausted because when a client of the proxy is failing, the corresponding connection should likely be closed (which is the least to do) or reset (with HTTP/2).

**Comment by cartmanez** [comment]
HI @vietj 

Thanks for you response. Did not try vertx-http-proxy, but with Pipe I'm seeing same result.

However, I think I was able to fix the problem - please see [updated demo app](https://gist.github.com/cartmanez/2d19ad4b6c68810c150849d3dfbc8a65#file-proxyverticle-java-L33-L35). Key thing is not to create Pump if client connection is already closed.

Just wondering - can (or should) Pump check if write stream is writable and handle this case?

Regards
