### ISSUE TITLE
Throws IllegalStateException("cacheDir is null") when using filesystem in JVM shutdown hook

### ISSUE THREAD

**Issue by Leibnizhu** [eclipse-vertx/vert.x#3670]
### Questions
When using vertx filesystem operation in a JVM shutdown hook, it throws  java.lang.IllegalStateException: cacheDir is null.
My code is :  

```java
import io.vertx.core.Vertx
import org.scalatest.FunSuite
import org.slf4j.LoggerFactory

class Vertx4Test extends FunSuite {
  private val log = LoggerFactory.getLogger(getClass)

  test("vertx4ShutdownHookTest") {
    val vertx = Vertx.vertx
    Runtime.getRuntime.addShutdownHook(new Thread(() => {
      val fileName = "test.txt"
      val exist = vertx.fileSystem().existsBlocking(fileName) //other filesystem operations behave as same
      log.info("{} exists?{}", fileName, exist)
    }))
  }
}
``` 

Console output:  

```java
Exception in thread "Thread-2" java.lang.IllegalStateException: cacheDir is null
	at io.vertx.core.file.impl.FileCache.getFile(FileCache.java:138)
	at io.vertx.core.file.impl.FileResolver.resolveFile(FileResolver.java:135)
	at io.vertx.core.impl.VertxImpl.resolveFile(VertxImpl.java:825)
	at io.vertx.core.file.impl.FileSystemImpl$20.perform(FileSystemImpl.java:1110)
	at io.vertx.core.file.impl.FileSystemImpl$20.perform(FileSystemImpl.java:1108)
	at io.vertx.core.file.impl.FileSystemImpl.existsBlocking(FileSystemImpl.java:491)
	at io.github.leibnizhu.repeater.http.Vertx4Test.$anonfun$new$2(Vertx4Test.scala:18)
	at java.lang.Thread.run(Thread.java:748)
```  

### Version
When runing this test with vert.X 4.0.0.CR2 or 4.0.0.CR1, it happens;  
But it runs normally with 4.0.0-milestone5, with console output as below:  
```bash
2020-11-26_10:08:56 [Thread-2] INFO i.g.l.r.h.Vertx4Test:18: test.txt exists?false
```  

### Context
None

### Do you have a reproducer?
Refer to the code above...
or in github: https://github.com/Leibnizhu/WecomBotRepeater/blob/master/src/test/scala/io/github/leibnizhu/repeater/http/Vertx4Test.scala

### Steps to reproduce
1. clone git code in https://github.com/Leibnizhu/WecomBotRepeater/ ;
2. execute ` mvn -Dsuites=io.github.leibnizhu.repeater.http.Vertx4Test test`, and test pass ;
3. change vertx version in `pom.xml`, line 21, to '`4.0.0.CR2`' or '`4.0.0.CR1`' ;
4. execute ` mvn -Dsuites=io.github.leibnizhu.repeater.http.Vertx4Test test`, and throws `java.lang.IllegalStateException`

### Extra
Other modules/software/jvm versions:

- scala.version: 2.12.4
- scala-test.version: 3.0.5
- JVM: 1.8.0_162
- System: MacOS big sur 11.0.1

**Comment by Leibnizhu** [comment]
same bug at `4.0.0`

**Comment by pmlopes** [comment]
@Leibnizhu @vietj this is a tricky one. We use a shutdown hook to clean up the cache dir, however the example in this issue is calling the file system during the shutdown (when the cache is already clean).

I guess we could "relax" the exception and fallback to "no cache" file system (meaning no more access to resources that live on the class path).

But honestly, I'm not certain if this is a bug or a "works as intended".

**Comment by Leibnizhu** [comment]
> @Leibnizhu @vietj this is a tricky one. We use a shutdown hook to clean up the cache dir, however the example in this issue is calling the file system during the shutdown (when the cache is already clean).
> 
> I guess we could "relax" the exception and fallback to "no cache" file system (meaning no more access to resources that live on the class path).
> 
> But honestly, I'm not certain if this is a bug or a "works as intended".

@pmlopes thanks for explanation, I read the source code of `FileCache` and realize what you mean. 
I'm trying to persist something to local file when JVM shutdown; So what's the right way to do that with Vert.X ?

**Comment by vietj** [comment]
it should be done in a Verticle stop(Promise) method, the verticle stop
will be called before the filesystem is closed and the promise give you
control over asynchrony.
