### ISSUE TITLE
Native image: Issues with VertxUnsafeHeapByteBuf

### ISSUE THREAD

**Issue by smoell** [eclipse-vertx/vert.x#3676]
### Questions

My native-image.properties are

```
Args = --initialize-at-build-time=io.netty,io.vertx,com.fasterxml.jackson,org.slf4j,software.amazon.awssdk\
       --initialize-at-run-time=com.google.protobuf.ExtensionRegistryFactory,io.netty.handler.ssl.ReferenceCountedOpenSslServerContext,io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator,io.netty.handler.ssl.ReferenceCountedOpenSslEngine,io.netty.handler.ssl.ConscryptAlpnSslEngine,io.netty.handler.ssl.JettyNpnSslEngine,io.netty.handler.ssl.ReferenceCountedOpenSslClientContext,io.vertx.core.net.impl.transport.EpollTransport,io.vertx.core.net.impl.transport.KQueueTransport,io.netty.handler.ssl.ReferenceCountedOpenSslContext,io.netty.handler.ssl.JettyAlpnSslEngine$ServerEngine,io.netty.handler.ssl.JettyAlpnSslEngine$ClientEngine,io.netty.util.internal.logging.Log4JLogger\
       --enable-url-protocols=http,https \
       -H:+UseServiceLoaderFeature \
       -H:IncludeResources=(META-INF/|vertx-default-jul-logging).* \
       -H:ReflectionConfigurationFiles=classes/${.}/reflection.json
```

and I have the following error:

```
Error: Classes that should be initialized at run time got initialized during image building:
 io.vertx.core.buffer.impl.VertxUnsafeHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.vertx.core.buffer.impl.VertxUnsafeHeapByteBuf got initialized use --trace-class-initialization=io.vertx.core.buffer.impl.VertxUnsafeHeapByteBuf
```

However, if I add all listed classes to -initialize-at-run-time, I get the following error:

```
Error: Incompatible change of initialization policy for io.netty.buffer.PooledByteBufAllocator: trying to change RUN_TIME from the command line to BUILD_TIME from the command line
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1647)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1397)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1358)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1317)
        at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1829)
```

### Version

Vertx 4.0.0 CR 2

### Do you have a reproducer?

* https://github.com/aws-samples/reactive-refarch-cloudformation

### Steps to reproduce

1. Check out project
2. cd reactive-refarch-cloudformation/services/tracking-service/reactive-vertx
3. docker build . -t smoell/reactive-vertx:2.0-native -f Dockerfile-native
4. Change native-image.properties
5. Build again

**Comment by vietj** [comment]
this class is new in Vert.x 4, I'm not familiar enough with native images to explain what is wrong. @pmlopes do you have an opinion on this ?

**Comment by vietj** [comment]
@cescoffier we do have a specific new buffer class in Vert.x 4.0 (that avoid duplicating a `ByteBuf`), do you know how to handle this with GraalVM ?

**Comment by cescoffier** [comment]
That will require additional substitutions and compilator flags.

**Comment by jvican** [comment]
I'm running a native version of vert.x 4.x successfully. I think the issue you run into can be solved by adding `--initialize-at-run-time=io.vertx.core.net.impl.PartialPooledByteBufAllocator`

**Comment by pmlopes** [comment]
@jvican can you share a working example? I tried to add the suggestion you made on a simple hello world project and it doesn't seem to make it work.

**Comment by jvican** [comment]
Sure thing, you might need a few more. Here's a gist of my options for GraalVM Native 20.3.0.

```
Args = --no-server \
--no-fallback \
--enable-http \
--enable-https \
--allow-incomplete-classpath \
--enable-all-security-services \
-H:+PrintClassInitialization \
-H:+ReportExceptionStackTraces \
-H:EnableURLProtocols=http,https \
--report-unsupported-elements-at-runtime \
-H:ReflectionConfigurationResources=${.}/reflect-config.json \
-H:JNIConfigurationResources=${.}/jni-config.json \
-H:ResourceConfigurationResources=${.}/resource-config.json \
--initialize-at-build-time=scala.Symbol,\
scala.Function1,\
scala.Function2,\
scala.runtime.StructuralCallSite,\
scala.runtime.EmptyMethodCache,\
org.slf4j.LoggerFactory,\
org.slf4j.impl.StaticLoggerBinder$,\
io.netty,\
io.vertx,\
com.fasterxml.jackson \
--initialize-at-run-time=io.netty.channel.DefaultChannelId,\
io.netty.buffer.PooledByteBufAllocator,\
io.vertx.core.net.impl.PartialPooledByteBufAllocator,\
io.netty.util.NetUtil,\
io.netty.channel.socket.InternetProtocolFamily,\
io.netty.resolver.HostsFileEntriesResolver,\
io.netty.resolver.dns.DnsNameResolver,\
io.netty.resolver.dns.DnsServerAddressStreamProviders,\
io.netty.resolver.dns.PreferredAddressTypeComparator\$1,\
io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider,\
io.vertx.core.impl.AddressResolver,\
io.vertx.core.dns.AddressResolverOptions,\
io.netty.handler.codec.http.websocketx.extensions.compression.DeflateEncoder,\
io.netty.handler.codec.http.websocketx.extensions.compression.DeflateDecoder,\
io.netty.handler.codec.http.HttpObjectEncoder,\
io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder,\
io.netty.handler.codec.http2.Http2CodecUtil,\
io.netty.handler.codec.http2.Http2ConnectionHandler,\
io.netty.handler.codec.http2.DefaultHttp2FrameWriter,\
io.netty.util.internal.logging.Log4JLogger,\
io.netty.handler.ssl.ReferenceCountedOpenSslServerContext,\
io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator,\
io.netty.handler.ssl.ReferenceCountedOpenSslEngine,\
io.netty.handler.ssl.ConscryptAlpnSslEngine,\
io.netty.handler.ssl.JettyNpnSslEngine,\
io.netty.handler.ssl.JettyAlpnSslEngine$ClientEngine,\
io.netty.handler.ssl.JettyAlpnSslEngine$ServerEngine,\
io.netty.handler.ssl.ReferenceCountedOpenSslContext,\
io.netty.handler.ssl.ReferenceCountedOpenSslClientContext,\
io.netty.buffer.ByteBufUtil$HexUtil,\
io.vertx.core.net.impl.transport.EpollTransport,\
io.vertx.core.net.impl.transport.KQueueTransport,\
io.vertx.core.http.impl.VertxHttp2ClientUpgradeCodec,\
io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder,\
io.vertx.core.eventbus.impl.clustered.ClusteredEventBus,\
io.netty.channel.unix,\
io.netty.channel.epoll,\
io.netty.buffer.ByteBufUtil$HexUtil
```

You'll most likely need to remove the Scala-specific options if you're not using Scala.

Some of those options are repeated and already included in the netty GraalVM configuration because I haven't yet had the time to go through the diff between the default GraalVM run-time/build-time symbols and the ones I specify in my configuration.

**Comment by pmlopes** [comment]
@jvican great, yes once core is upgraded to the latest netty some of these can be removed safely! Thanks!!!

**Comment by pmlopes** [comment]
@smoell as a quick test I've added @jvican comment to the example we had:

a single application running:

* HTTP server
* HTTPS server
* WebClient

And it builds and runs. Perhaps you can have a look at the commit linked above and see if it works for you too.

**Comment by smoell** [comment]
Great, I'll have a look!

**Comment by smoell** [comment]
I dived deep into the init process and this list is working for me:

`Args = --trace-class-initialization=io.netty.buffer.UnpooledUnsafeHeapByteBuf,io.vertx.core.buffer.impl.VertxUnsafeHeapByteBuf,io.netty.buffer.UnpooledHeapByteBuf,io.netty.buffer.AbstractReferenceCountedByteBuf \
        --enable-http \
        --enable-https \
        --allow-incomplete-classpath \
        --enable-all-security-services \
        -H:EnableURLProtocols=http,https \
        -H:IncludeResources=(META-INF/|vertx-default-jul-logging).* \
        -H:ReflectionConfigurationFiles=classes/${.}/reflection.json \
        --report-unsupported-elements-at-runtime \
        --initialize-at-build-time=org.slf4j.LoggerFactory,\
        org.slf4j.impl.StaticLoggerBinder$,\
        io.netty,\
        io.vertx,\
        com.fasterxml.jackson,\
        org.slf4j,software.amazon.awssdk \
        --initialize-at-run-time=io.netty.channel.DefaultChannelId,\
        io.netty.buffer.PooledByteBufAllocator,\
        io.netty.buffer.AbstractReferenceCountedByteBuf,\
        io.vertx.core.net.impl.PartialPooledByteBufAllocator,\
        io.vertx.core.buffer.impl.VertxUnsafeHeapByteBuf,\
        io.netty.buffer.UnpooledUnsafeHeapByteBuf,\
        io.netty.buffer.UnpooledHeapByteBuf,\
        io.vertx.redis.client.impl.types.BulkType,\
        io.netty.util.NetUtil,\
        io.netty.channel.socket.InternetProtocolFamily,\
        io.netty.resolver.HostsFileEntriesResolver,\
        io.netty.resolver.dns.DnsNameResolver,\
        io.netty.resolver.dns.DnsServerAddressStreamProviders,\
        io.netty.resolver.dns.PreferredAddressTypeComparator\$1,\
        io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider,\
        io.vertx.core.impl.AddressResolver,\
        io.vertx.core.dns.AddressResolverOptions,\
        io.netty.handler.codec.http.websocketx.extensions.compression.DeflateEncoder,\
        io.netty.handler.codec.http.websocketx.extensions.compression.DeflateDecoder,\
        io.netty.handler.codec.http.HttpObjectEncoder,\
        io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder,\
        io.netty.handler.codec.http2.Http2CodecUtil,\
        io.netty.handler.codec.http2.Http2ConnectionHandler,\
        io.netty.handler.codec.http2.DefaultHttp2FrameWriter,\
        io.netty.util.internal.logging.Log4JLogger,\
        io.netty.handler.ssl.ReferenceCountedOpenSslServerContext,\
        io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator,\
        io.netty.handler.ssl.ReferenceCountedOpenSslEngine,\
        io.netty.handler.ssl.ConscryptAlpnSslEngine,\
        io.netty.handler.ssl.JettyNpnSslEngine,\
        io.netty.handler.ssl.JettyAlpnSslEngine$ClientEngine,\
        io.netty.handler.ssl.JettyAlpnSslEngine$ServerEngine,\
        io.netty.handler.ssl.ReferenceCountedOpenSslContext,\
        io.netty.handler.ssl.ReferenceCountedOpenSslClientContext,\
        io.netty.buffer.ByteBufUtil$HexUtil,\
        io.vertx.core.net.impl.transport.EpollTransport,\
        io.vertx.core.net.impl.transport.KQueueTransport,\
        io.vertx.core.http.impl.VertxHttp2ClientUpgradeCodec,\
        io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder,\
        io.vertx.core.eventbus.impl.clustered.ClusteredEventBus,\
        io.netty.channel.unix,\
        io.netty.channel.epoll,\
        io.netty.buffer.ByteBufUtil$HexUtil \
`

`Args = --trace-class-initialization=io.netty.buffer.UnpooledUnsafeHeapByteBuf,io.vertx.core.buffer.impl.VertxUnsafeHeapByteBuf,io.netty.buffer.UnpooledHeapByteBuf,io.netty.buffer.AbstractReferenceCountedByteBuf \
        --enable-http \
        --enable-https \
        --allow-incomplete-classpath \
        --enable-all-security-services \
        -H:EnableURLProtocols=http,https \
        -H:IncludeResources=(META-INF/|vertx-default-jul-logging).* \
        -H:ReflectionConfigurationFiles=classes/${.}/reflection.json \
        --report-unsupported-elements-at-runtime \
        --initialize-at-build-time=org.slf4j.LoggerFactory,\
        org.slf4j.impl.StaticLoggerBinder$,\
        io.netty,\
        io.vertx,\
        com.fasterxml.jackson,\
        org.slf4j,software.amazon.awssdk \
        --initialize-at-run-time=io.netty.channel.DefaultChannelId,\
        io.netty.buffer.PooledByteBufAllocator,\
        io.netty.buffer.AbstractReferenceCountedByteBuf,\
        io.vertx.core.net.impl.PartialPooledByteBufAllocator,\
        io.vertx.core.buffer.impl.VertxUnsafeHeapByteBuf,\
        io.netty.buffer.UnpooledUnsafeHeapByteBuf,\
        io.netty.buffer.UnpooledHeapByteBuf,\
        io.vertx.redis.client.impl.types.BulkType,\
        io.netty.util.NetUtil,\
        io.netty.channel.socket.InternetProtocolFamily,\
        io.netty.resolver.HostsFileEntriesResolver,\
        io.netty.resolver.dns.DnsNameResolver,\
        io.netty.resolver.dns.DnsServerAddressStreamProviders,\
        io.netty.resolver.dns.PreferredAddressTypeComparator\$1,\
        io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider,\
        io.vertx.core.impl.AddressResolver,\
        io.vertx.core.dns.AddressResolverOptions,\
        io.netty.handler.codec.http.websocketx.extensions.compression.DeflateEncoder,\
        io.netty.handler.codec.http.websocketx.extensions.compression.DeflateDecoder,\
        io.netty.handler.codec.http.HttpObjectEncoder,\
        io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder,\
        io.netty.handler.codec.http2.Http2CodecUtil,\
        io.netty.handler.codec.http2.Http2ConnectionHandler,\
        io.netty.handler.codec.http2.DefaultHttp2FrameWriter,\
        io.netty.util.internal.logging.Log4JLogger,\
        io.netty.handler.ssl.ReferenceCountedOpenSslServerContext,\
        io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator,\
        io.netty.handler.ssl.ReferenceCountedOpenSslEngine,\
        io.netty.handler.ssl.ConscryptAlpnSslEngine,\
        io.netty.handler.ssl.JettyNpnSslEngine,\
        io.netty.handler.ssl.JettyAlpnSslEngine$ClientEngine,\
        io.netty.handler.ssl.JettyAlpnSslEngine$ServerEngine,\
        io.netty.handler.ssl.ReferenceCountedOpenSslContext,\
        io.netty.handler.ssl.ReferenceCountedOpenSslClientContext,\
        io.netty.buffer.ByteBufUtil$HexUtil,\
        io.vertx.core.net.impl.transport.EpollTransport,\
        io.vertx.core.net.impl.transport.KQueueTransport,\
        io.vertx.core.http.impl.VertxHttp2ClientUpgradeCodec,\
        io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder,\
        io.vertx.core.eventbus.impl.clustered.ClusteredEventBus,\
        io.netty.channel.unix,\
        io.netty.channel.epoll,\
        io.netty.buffer.ByteBufUtil$HexUtil \`

The problem was actually io.vertx.redis.client.impl.types.BulkType
