### ISSUE TITLE
FutureBase should additionally check if the context belongs to a closed vertx instance

### ISSUE THREAD

**Issue by doctorpangloss** [eclipse-vertx/vert.x#3682]
https://github.com/eclipse-vertx/vert.x/blob/85ac0ea4f6d853e3363957b41ce43dbf94664478/src/main/java/io/vertx/core/impl/future/FutureBase.java#L49

https://github.com/eclipse-vertx/vert.x/blob/85ac0ea4f6d853e3363957b41ce43dbf94664478/src/main/java/io/vertx/core/impl/future/FutureBase.java#L66

These checks should also check if the context does not belong to a Vertx instance that has been close (i.e. a shut down event loop). `vertx.close().onComplete( ... )` will create a Future referencing a context on the Vertx instance that was just closed. Then, the lambda passed to `onComplete` will execute in that closed context, which throws a `RejectedExecutionException` since the context's event loop group is shut down.

This is very puzzling, because `vertx.close()` creates a promise without a context.

This crops up in tests of mine.

**Comment by vietj** [comment]
the purpose of creating a promise without a context is that it can be used after Vert.x is closed

**Comment by doctorpangloss** [comment]
Exactly, so I'm really puzzled how I wind up with a `Future` with a non-null context. I'll give you a repro once I minimize the test case, thank you Julien.

**Comment by doctorpangloss** [comment]
Fixing other bugs made this problem go away, so I think I will close it for now!
