### ISSUE TITLE
publish,send not work

### ISSUE THREAD

**Issue by noobthinker** [eclipse-vertx/vert.x#3684]
### Questions

EventBus publish send not work. consumer nerver target.

### Version

3.9.4,
4.0.0.Beta3
,4.0.0.CR2,
4.0.0.CR1

### Context

EventBus publish send to the address, the handler never target. but request can work.

### Do you have a reproducer?

no

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

* Link to github project/gist

### Steps to reproduce

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Vertx;
import io.vertx.core.eventbus.EventBus;

public class WhatsHappened {
  public static void main(String[] args) {
      Vertx vertx = Vertx.vertx();
      EventBus bus = vertx.eventBus();
      vertx.deployVerticle(new NerverTarget());
      // bus.consumer("",a->{});
      bus.publish("target","1");
      bus.send("target","2");
      bus.request("target","3");
  }

  static class NerverTarget extends AbstractVerticle{
      @Override
      public void start() throws Exception {
          vertx.eventBus().consumer("target",h->{
              System.out.println(h.body());
          });
      }
  }
}

result : 3 

open comment : bus.consumer("",a->{});

result: 1,2,3

**Comment by tsegismont** [comment]
Deploying a verticle or registering a consumers are asynchronous operations.

If you want to make sure the consumer is ready to get the messages, you need to use callbacks:

```
public class WhatsHappened {
  public static void main(String[] args) {
    Vertx vertx = Vertx.vertx();
    EventBus bus = vertx.eventBus();
    vertx.deployVerticle(new NerverTarget(), ar -> {
      if (ar.succeeded()) {
        bus.publish("target","1");
        bus.send("target","2");
      } else {
        // Handle error
      }
    });
  }

  static class NerverTarget extends AbstractVerticle{
    @override
    public void start(Promise<Void> startPromise) throws Exception {
      vertx.eventBus().consumer("target",h->{
        System.out.println(h.body());
      }).completionHandler(startPromise);
    }
  }
}
```

Notice that the verticle uses the `start` method variant that takes a `Promise` parameter, which allows to indicate completion. The verticle will be considered started only when the consumer registration completes.
Thanks to this, we know that when the `deployVerticle` callaback is invoked, the consumer is ready (in case of success).

Note that using a `request` without a callback does not make a lot of sense given the purpose of this method is to expect a reply.

HTH

**Comment by noobthinker** [comment]
Thank you so much.

that's help a lot.

I found that vertx is asynchronous, which is why the event is not triggered.



public class WhatsHappened {
  public static void main(String[] args) {
      Vertx vertx = Vertx.vertx();
      EventBus bus = vertx.eventBus();
      vertx.deployVerticle(new NerverTarget(),ar->{
          if(ar.succeeded()){
              System.out.println("ok");
              // here work fine
              bus.publish("target","3");
          }else{
              ar.cause().printStackTrace();
          }
      });
//      bus.consumer("",a->{});
      // the vertx is async .the consumer not deploy ready.
      bus.publish("target","1");
      bus.send("target","2");
//      bus.request("target","3");
  }

  static class NerverTarget extends AbstractVerticle{
      @Override
      public void start(Promise<Void> startPromise) throws Exception {
          vertx.eventBus().consumer("target",h->{
              System.out.println(h.body());
          }).completionHandler(startPromise);
      }
  }
}
