### ISSUE TITLE
No message codec for type should probably return a Future.failedFuture not throw

### ISSUE THREAD

**Issue by doctorpangloss** [eclipse-vertx/vert.x#3688]
### Version

4.0.0.CR2

### Context

Sending a message on the event bus with a missing codec throws an exception instead of returning a failed future.

```
java.lang.IllegalArgumentException: No message codec for type: class com.hiddenswitch.framework.impl.ConfigurationRequest
	at io.vertx.core.eventbus.impl.CodecManager.lookupCodec(CodecManager.java:101)
	at io.vertx.core.eventbus.impl.EventBusImpl.createMessage(EventBusImpl.java:232)
	at io.vertx.core.eventbus.impl.EventBusImpl.request(EventBusImpl.java:109)
	at io.vertx.core.eventbus.EventBus.request(EventBus.java:81)
```

### Do you have a reproducer?

```
class SomeClass {
}
Vertx.vertx().eventBus().publish("1", new SomeClass());
```

**Comment by vietj** [comment]
that's a fair point

**Comment by tsegismont** [comment]
I gave some thought to this and I don't believe we should change anything.

First, this is not a regression in Vert.x 4 but the usual behavior of `EventBus`.

More importantly, a missing codec is a fatal issue which can't be recovered: something wrong happened during packaging or the app initialization code is broken. Such problems are usually caught during testing.
