### ISSUE TITLE
interface io.vertx.ext.auth.User

### ISSUE THREAD

**Issue by froggengoing** [eclipse-vertx/vert.x#3690]
### Questions

```
public interface User {

  @Fluent
  @Deprecated
  User isAuthorized(String authority, Handler<AsyncResult<Boolean>> resultHandler);

  @Deprecated
  @Fluent
  default User isAuthorised(String authority, Handler<AsyncResult<Boolean>> resultHandler) {
    return isAuthorized(authority, resultHandler);
  }
}
```

### Version

vertx-auth-common:3.9.4

### Context

both ` isAuthorized(String authority, Handler<AsyncResult<Boolean>> resultHandler) ` and `isAuthorised(String authority, Handler<AsyncResult<Boolean>> resultHandler)`  declare   `@Deprecated`
so what method should i use in inteface User to authorise
the entire classpath is `io.vertx.ext.auth.User`

**Comment by froggengoing** [comment]
the entire classpath is `io.vertx.ext.auth.User`

**Comment by vietj** [comment]
can you move this issue to https://github.com/vert-x3/vertx-auth ?
