### ISSUE TITLE
An event bus consumer handler's Message<> could benefit from a .reply() promise

### ISSUE THREAD

**Issue by doctorpangloss** [eclipse-vertx/vert.x#3691]
#### Describe the feature

`Message<T>` should have an API like

```
/**
 * Completable with a reply message, or fails if isSend was false.
 */
<T> Promise<V> reply();
```

#### Use cases

```
eventBus.<T>consumer("address", message -> doAsyncWork().onComplete(message.reply()));
```

Observe it ought to infer the arguments by the `Future<V>` returned by `doAsyncWork()`.

It also gives you a handy way to tap into enhancements to `Future`, like reifying the stack for tracing or transmitting error messages via VertxException, the more APIs that look like this the better!

**Comment by vietj** [comment]
I see your point and it makes sense to some extent.

However I think that would be confusing and not be consistent with `replyAndRequest()` that returns a future.

**Comment by vietj** [comment]
Perhaps we could have something like:

```java
default static <T> Promise<T> promise(Handler<T> a, Handler<Throwable> b) {
  Promise<T> promise = promise();
  promise.future().onComplete(ar -> {
    if (ar.succeeded()) {
      a.handle(ar.result());
    } else {
      b.handle(ar.cause());
    }
  });
  return promise;
}
```

that would allow:

```java
eventBus.<T>consumer("address", message -> doAsyncWork().onComplete(Promise.promise(message::reply, message::fail)));
```
