### ISSUE TITLE
Security addition on proxy protocol (real remote and source addresses)

### ISSUE THREAD

**Issue by Joxit** [eclipse-vertx/vert.x#3700]
#### Describe the feature

Get an access to the real remote address when using Proxy Protocol. In the current implementation of proxy protocol, the field `remoteAddress` is replaced by the source IP from the proxy protocol request (and that shouldn't change). We should add the original source and destination IP somewhere in the context. 

#### Use cases

The proxy protocol is used between a Load Balancer and servers. For security, servers should only accept requests from the Load Balancers to avoid malicious requests. Anyone familiar with this protocol can create requests and pretend to have a different IP.

Here is a plain text example of the protocol:
```
PROXY TCP4 {source IP} {destination IP} {source port} {destination port}
GET / HTTP/1.1
```

![vertx-proxy-protocol](https://user-images.githubusercontent.com/5153882/101999179-b7419e00-3cda-11eb-8c46-43f74e64ef5c.png)

In this example, allowed requests from IP `x.x.x.x` should be something like : 
```
PROXY TCP4 x.x.x.x a.a.a.a 58965 443
GET / HTTP/1.1
```

But a hacker can build wrong requests, for example a requests from `h.h.h.h` to `y.y.y.y` (he stole the IP `x.x.x.x`). The application will think that it was x who made the request. Which is wrong.
```
PROXY TCP4 x.x.x.x y.y.y.y 58965 443
GET / HTTP/1.1
```

**Comment by vietj** [comment]
what do you propose @Joxit ?

**Comment by Joxit** [comment]
I see 2 solutions:

1. Add a new methods like `realRemoteAddress` and `realLocalAddress` in `HttpServerRequest` and `ConnectionBase`
2. Put the value in the routing context with a defined key like `ha-proxy-protocol:remote-address` and `ha-proxy-protocol:local-address`

The result of `realRemoteAddress` will be something like
https://github.com/eclipse-vertx/vert.x/blob/588b6f0e7bd28b22d3b4147aa9f9acafa787ef76/src/main/java/io/vertx/core/net/impl/ConnectionBase.java#L560-L563

I'm a little afraid that `realXAddress` is misunderstood :confused:...

These methods will be useful only in a proxy protocol environment and in all other use cases `realXAddress()` == `xAddress()`

Maybe the first solution is the best ? What do you think ?

**Comment by vietj** [comment]
are there existing examples of how other runtimes handle it ?

**Comment by Joxit** [comment]
other runtimes like netty or spring/spring boot ?
I don't think that spring boot supports proxy protocol, and I don't think that netty handle this use case... But they have a [AbstractRemoteAddressFilter](https://github.com/netty/netty/blob/e5951d46fc89db507ba7d2968d2ede26378f0b04/handler/src/main/java/io/netty/handler/ipfilter/AbstractRemoteAddressFilter.java).

[Zuul](https://github.com/Netflix/zuul) is also using netty and proxy protocol but the real IP is not exposed in their Request object or in their context attributes... :confused:

**Comment by yuchonghua** [comment]
I look forward to solving this problem. It has been waiting for more than a year. Is it possible to solve it in the near future?

**Comment by vietj** [comment]
that is an issue we can solve, but TBH if your proxy is compromised, that's already a major issue in your infrastructure.

**Comment by yuchonghua** [comment]
Looking forward to using it soon

**Comment by vietj** [comment]
I'm closing the issue, I'll open an issue to support x-forwarded-for in vertx-web
