### ISSUE TITLE
Docs: there is no start(Future<Void>) in the AbstractVerticle

### ISSUE THREAD

**Issue by hantsy** [eclipse-vertx/vert.x#3702]
There is a `start(Future<Void>)` in the Vertx [Core](https://vertx.io/docs/vertx-core/java/#_asynchronous_verticle_start_and_stop) docs.

But in Vertx 4.0, the `start` method in the `AbstractVerticle` and `Verticle` only accept a `Promise<Void>` paratmeter.

**Comment by vietj** [comment]
thanks for reporting
