### ISSUE TITLE
rxjava2: reactive Vertx should be injected in Junit 5

### ISSUE THREAD

**Issue by hantsy** [eclipse-vertx/vert.x#3704]
In Vertx Rxjava 2 sample, I tried to use all vertx-rx-rxjava2 APIs instead of the vertex core.

But the `io.vertx.reactivex.core.Vertx` can not be injected in the JUnit 5 methods like the normal Vertx. 

My application is based on the following stack:

* Vertx 4.0.0
* Java 11
* Windows 10

I have to wrap it [myself like this](https://github.com/hantsy/vertx-sandbox/blob/master/rxjava2/src/test/java/com/example/demo/TestMainVerticle.java#L48):

```java
WebClient client = WebClient.create(new io.vertx.reactivex.core.Vertx(vertx));
```

**Comment by vietj** [comment]
can you open this issue in the vertx-junit5 repo ? https://github.com/vert-x3/vertx-junit5
