### ISSUE TITLE
rxjava2: ValidationHandler builder `build` method should return a rxjava2 specific ValidationHandler

### ISSUE THREAD

**Issue by hantsy** [eclipse-vertx/vert.x#3705]
I added web validaiton and rxjava 2 in my Rxjava project.

I used the ` io.vertx.reactivex.ext.web.validation.ValidationHandler`.

```java
 ValidationHandler
                .builder(schemaParser)
                .body(Bodies.json(bodySchemaBuilder))
                //.body(Bodies.formUrlEncoded(bodySchemaBuilder))
                .build()
```

But the `build()` method returns `io.vertx.ext.web.validation.ValidationHandler`. I think it should be ` io.vertx.reactivex.ext.web.validation.ValidationHandler`.

Before applying it to the routing handlers, I have to [wrap it again](https://github.com/hantsy/vertx-sandbox/blob/master/rxjava2/src/main/java/com/example/demo/MainVerticle.java#L94-L100).

**Comment by vietj** [comment]
can you open this issue in the vertx-web repo ? https://github.com/vert-x3/vertx-web

**Comment by hantsy** [comment]
vertx-web is not under eclipse-vertx?

**Comment by vietj** [comment]
unfortunately no, long story :-)
