### ISSUE TITLE
ConfigRetriever doesn't load properties file + small typo in factory name

### ISSUE THREAD

**Issue by peetboy** [eclipse-vertx/vert.x#3709]
### Version
4.0.0.CR1
### Context
I have a verticle with example code for loading properties from documentation but nothing is loaded.

resources/conf/raw.properties
```
server.host=localhost
server.port=8080
multiple.values=1,2,3
```
code in verticle
```
ConfigStoreOptions propertyWithRawData = new ConfigStoreOptions()
    .setFormat("properties")
    .setType("file")
    .setConfig(new JsonObject().put("path", "conf/raw.properties").put("raw-data", true).put("hierarchical", true)
    );

ConfigRetriever configRetriever = ConfigRetriever.create(vertx, new ConfigRetrieverOptions().addStore(propertyWithRawData));
```
After handling of configRetriever.getConfig() the result is empty.

I do have another configuration config.json in resources/conf folder and that one is loaded properly by default.
I have also tried with Directory config store and "*.properties" pattern but with no luck.

Also during investigation I found a typo in **io.vertx.config.impl.spi.FileConfigtoreFactory** (missing 'S').

_Lastly, I found it a bit difficult to use json files as properties source because in case of try/catch situations you can't just quickly comment out the setting if needed or add comments which describes each setting because json doesn't allow comments. That's also reason why I need loading of standard properties. There you can easily comment out the line and have the property loaded from another file due to overloading._

**Comment by EmadAlblueshi** [comment]
Hi, 

This issue should be opened in [vertx-config](https://github.com/vert-x3/vertx-config)
