### ISSUE TITLE
[Regression] Vertx4 HttpServerRequest.uploadHandler() erases context. (2)

### ISSUE THREAD

**Issue by oscarfh** [eclipse-vertx/vert.x#3711]
This is the same issue as #3629 , where the UploadHandler erases the context.
The reproducer from the original ticket: https://github.com/oscarfh/vertx-upload-handler-context is still reproducing the issue.

I am researching to add any new findings on this.

**Comment by vietj** [comment]
thanks

**Comment by oscarfh** [comment]
I am preparing a PR to fix this.

**Comment by oscarfh** [comment]
@vietj https://github.com/eclipse-vertx/vert.x/pull/3712  :)
