### ISSUE TITLE
JsonObject.getInstant() doesn't work for timezone other than Z

### ISSUE THREAD

**Issue by champeric** [eclipse-vertx/vert.x#3713]
### Version

3.9.4

### Context

`JsonObject.getInstant()` doesn't work if the date in the JSON contains a timezone other than 'Z'.

```
JsonObject o = new JsonObject();
o.put("good", "2020-12-17T15:10:11.002Z");
o.put("bad",  "2020-12-17T10:10:11.002-05:00");
//This works...
o.getInstant("good");
//This results in a DateTimeParseException: Text '2020-12-17T10:10:11.002-05:00' could not be parsed at index 23
o.getInstant("bad");
```

The JavaDoc of the functions says it complies with RFC-7493 so it assumes the date is encoded ISO 8601. RFC-7493 refers to RFC-3339 for definition of ISO 8601, which allows for offset timezones (`time-zone = "Z" / time-numoffset`).

I see in the code that `ISO_INSTANT` is used for formatting and parsing. Looks like it cannot parse anything other than Z for timezone. Seems to me that `ISO_OFFSET_DATE_TIME` would work better for parsing, but I'm not sure I understand all the subtle details between the two.

If the change can't be done, the JavaDoc should change to make it explicit that only dates formatted with the 'Z' timezone are accepted.

**Comment by pmlopes** [comment]
The choice of the parser was made to comply with:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString

Which is the default encoding for web applications. Like @champeric wrote we should update the javadoc to state:

> The toISOString() method returns a string in simplified extended ISO format (ISO 8601), which is always 24 or 27 characters long (YYYY-MM-DDTHH:mm:ss.sssZ or ±YYYYYY-MM-DDTHH:mm:ss.sssZ, respectively). The timezone is always zero UTC offset, as denoted by the suffix "Z".
