### ISSUE TITLE
A broken link in the `RxJava interoperability documentation` section (in `vertx-lang-kotlin-coroutines` doc page)

### ISSUE THREAD

**Issue by jtonic** [eclipse-vertx/vert.x#3723]
The link `Guide to reactive streams with coroutines` in the `RxJava interoperability` is broken.

Doc link: https://vertx.io/docs/vertx-lang-kotlin-coroutines/kotlin/#_rxjava_interoperability
Broken link: [RxJava interoperability](https://github.com/Kotlin/kotlinx.coroutines/blob/master/reactive/coroutines-guide-reactive.md)

**Comment by vietj** [comment]
can you reopen this issue here https://github.com/vertx-web-site/vertx-web-site ?
