### ISSUE TITLE
Propagate HttpRequest/HttpResponse to HttpServerMetrics requestEnd/responseEnd

### ISSUE THREAD

**Issue by anatak** [eclipse-vertx/vert.x#3732]
In Vert.x version 3.9.2 `io.vertx.core.spi.metrics.HttpServerMetrics.responseEnd` method had a parameter `httpResponse` which was removed and replaced by `bytesRead`in 4.0.0 version. This was done in "Update HttpServerMetrics to use observability HttpRequest/HttpResponse" (#3587).

In our application we have a custom SPI and `responseEnd` is used to measure time of whole request process with additional info such as status code. In version 4.0.0 this information is available only in `responseBegin` method, which forces us to "change state" of `requestMetric` parameter for propagating information to `responseEnd`.

It would be very helpful if instance of new HttpResponse was available in `responseEnd`. This could be done simply by adding `response` in Http server implementations or generally by passing custom state between `responseBegin`/`responsePushed` and `reponseEnd` method.

**Comment by vietj** [comment]
we'll have a look

**Comment by vietj** [comment]
re-reading this, you indicated you can have a field on your request metric object that is assigned the `HttpResponse` instance, why is it an issue for you ?

**Comment by anatak** [comment]
Sorry if I mislead you (English is not my native language), I'll try to explain it better. 

Until 4.0.0 the `requestMetric` instance was created on `requestBegin` and served as immutable instance with start time information among other immutable things. This instance was passed into `responseEnd` method along `httpResponse`, where was finally used to our custom metric system. 

In 4.0.0 we could introduce uninitialized mutable field into `requestMetrics` in `requestBegin`, then initialize field in `responseBegin` and finally processing all information in `responseEnd`. But this is against our code style where immutable states are preferred everywhere. For example we are using Kotlin, which has many immutable features and optimizations. This is what I meant by "forcing us to change state".

**Comment by vietj** [comment]
@anatak unfortunately we prefer to avoid doing this because it would add un-necessary complexity in the SPI of the metrics that is already not simple. You should see this code as low level code that can afford to have such mutation. In fact for such code is preferable for performance reason, i.e the code for metrics (and tracing) should have a minimum overhead for your app.

**Comment by anatak** [comment]
@vietj I'm sorry but your answer does make little sense for me. I understand that changing SPI in current version is not an easy task and this is probably the "deal breaker", why adding `httpResponse` is problem and I accept that.

But performance wise passing reference to an existing instance is much faster than additional custom implementation of `responseBegin` method. From SPI design perspective, attribute `httpResponse` in `responseEnd` method is well suited and all calls `responseEnd` in vertx.core (from what I've seen) has easy access to `httpResponse`.

Is there some information or knowledge that I missing (and maybe I should know) ?

**Comment by vietj** [comment]
I see what you mean.

So you basically would like to have `responseEnd(R requestMetric, HttpResponse response, long bytesWritten)`

**Comment by anatak** [comment]
Yes, something like that :)

**Comment by vietj** [comment]
I think we can do that.

I thought you were rather asking to add another generic for the response.

**Comment by anatak** [comment]
I was trying to avoid specific suggestion like adding `response` directly, because you could have different design approach, such as generic metric for the response. This probably caused confusion instead and I'm sorry for that. 

Simple adding `HttpResponse response` to `responseEnd` is perfect solution for us :)

**Comment by anatak** [comment]
Hi @vietj, if this can be done, could you reopen this ticket or should I create another issue. And BTW thank you for your extra time and patience on this.

**Comment by ebullient** [comment]
Agree with above.. the removal of the HttpResponse from responseEnd (which was present in 3.x) is an issue for including response status in recorded metrics. Threading that through manually (via requestBegin) is awkward at best..

**Comment by vietj** [comment]
well that's a question of opinion :-)

**Comment by vietj** [comment]
it is very fine for the Dropwizard metrics that does:

```java
  @Override
  public void responseBegin(HttpRequestMetric requestMetric, HttpResponse response) {
    requestMetric.response = response;
  }
``

so I really don't get your opinionated rant
