### ISSUE TITLE
Tracing and span are not propagated and recorded when EventBusProxies or EventBus is used to communicate between multiple microservices

### ISSUE THREAD

**Issue by riftninja** [eclipse-vertx/vert.x#3737]
### Version

4.0.0

### Context

Testing zipkin tracing repository, I discovered that the traceId and spanId generated when an HTTP request is received on the server are not propagated and stored when communication between microservices are done through EventBusProxies/EventBus. 

### Steps to reproduce

1. create vertx project, enable tracing and import io.vertx:vertx-zipkin:4.0.0
2. send a request to vertx http server
3. forward request to microservices through EventBusProxies or Eventbus
4. monitor recorded traces, request sent through Eventbus will not be recorded

**Comment by ayomide101** [comment]
I also experienced this issue. Any solution?

**Comment by vietj** [comment]
can somebody provide a reproducer project to help resolving this faster ?

**Comment by LarsEckart** [comment]
I think I ran into the same issue when trying out https://github.com/tsegismont/vertx-contextual-logging from @tsegismont 

I made a reproducing project:
https://github.com/LarsEckart/vertx-local-context-data-example 

The project has a test which shows the behaviour (not by failing the test but the test produces the log output which shows the problem)

![Screen Shot 2021-01-08 at 16 19 51](https://user-images.githubusercontent.com/4414802/104025485-633cb300-51cd-11eb-819b-4ccd075e429b.png)

**Comment by tsegismont** [comment]
@LarsEckart it's a different issue. Contextual data is not propagated over the EventBus. You need to register inbound/outbound interceptors. See https://github.com/tsegismont/vertx-contextual-logging#propagation

**Comment by ayomide101** [comment]
@vietj I made a reproducing project:
https://github.com/ayomide101/vertx-eventbus-trace-span-example

I hope it helps

**Comment by vietj** [comment]
@tsegismont ping any progress on this ?

**Comment by tsegismont** [comment]
@vietj here's what I found

In `OutboundDeliveryContext`, the tracing policy is hard-coded to `PROPAGATE` (unlike in, for example, `HttpClient` where this is configurable with options).

https://github.com/eclipse-vertx/vert.x/blob/c0e7ad01a2718d2021b874a7da66da34263d1074/src/main/java/io/vertx/core/eventbus/impl/OutboundDeliveryContext.java#L121

Consequently, given there is no active span when the method is called, no new span is created.
(In the reproducer, the user invokes the `EventBus` from `setPeriodic`).

Can you remind me why the policy is hard-coded to `PROPAGATE` for the `EventBus`?

**Comment by vietj** [comment]
Client won't start automatically a span for each request by default, as multiple client usage in the same flow would result in several uncorrelated spans.

**Comment by tsegismont** [comment]
> Therefore this case should be possible only if configured explicitely.

You mean if a span is created manually?

**Comment by vietj** [comment]
I haven't spent time on this, but if you look at HttpServerOptions and
HttpClientOptions you can specify the policy.

I think one could specify the policy on DeliveryOptions too to address the
same use case.

**Comment by tsegismont** [comment]
@riftninja @ayomide101 see #3768 that addresses the issue
