### ISSUE TITLE
isNativeTransportEnabled is always false

### ISSUE THREAD

**Issue by mystdeim** [eclipse-vertx/vert.x#3741]
I use vert.x 4.0.0 java 14 and os x 11.1. 

That's a reproducer:

```
public class Main {
  public static void main(String[] args) {

    var vertx = Vertx.vertx(new VertxOptions()
      .setPreferNativeTransport(true)
    );

    boolean usingNative = vertx.isNativeTransportEnabled();
    System.out.println("Running with native: " + usingNative);
  }
}
```

Also I have a gradle build with dependencies:

```
  implementation("io.netty:netty-transport-native-epoll:4.1.49.Final")
  implementation("io.netty:netty-transport-native-kqueue:4.1.49.Final")
```

During my investigations I found out my app caught: `could not load a native library: netty_transport_native_kqueue_x86_64` exception in the io.netty.channel.kqueue.KQueue class. 
Do I need something else to add in dependencies or it's a bug?

**Comment by mystdeim** [comment]
I found workaround for me: https://github.com/ktorio/ktor/issues/1672#issue-569857300 Maybe we need to add this tip in the documentation https://vertx.io/docs/vertx-core/java/#_native_transports for gradle users?

**Comment by vietj** [comment]
@mystdeim I PR would be welcome in the documentation for this

**Comment by vietj** [comment]
I'll close this issue in the meantime
