### ISSUE TITLE
Unexpected IllegalStateException in HttpClientResponseImpl.java:150

### ISSUE THREAD

**Issue by adamdickmeiss** [eclipse-vertx/vert.x#3748]
With Vert.x 4.0.0, I have a function that reads:

```java
private Future<Void> getUrlAbsFails(String absUrl) {
    RequestOptions requestOptions = new RequestOptions()
        .setMethod(HttpMethod.GET)
        .setAbsoluteURI(absUrl);
    return client.request(requestOptions)
        .compose(req -> req.end().compose(x -> req.response()))
        .compose(res -> {
          Promise<Void> promise = Promise.promise();
          res.endHandler(d -> {
            if (res.statusCode() != 200) {
              promise.fail("expected 200");
              return;
            }
            promise.complete();
          });
          return promise.future();
        });
 }
```

This results in IllegalStateException .. checkEnded in HttpClientREsponseImpl.java:150.

The error happens at random.. Sometimes I have to run 10+ times or more.

Of course, there's a server behind an all that.

Here's a very similar method which works fine:

```java
private Future<Void> getUrlAbsOK(String absUrl) {
    RequestOptions requestOptions = new RequestOptions()
        .setMethod(HttpMethod.GET)
        .setAbsoluteURI(absUrl);
    return client.request(requestOptions)
        .compose(req -> req.end()
            .compose(x -> req.response()).compose(res -> {
              Promise<Void> promise = Promise.promise();
              res.endHandler(d -> {
                if (res.statusCode() != 200) {
                  promise.fail("expected 200");
                  return;
                }
                promise.complete();
              });
              return promise.future();
            })
        );
  }
```

To me it seems like that HttpClientRequest (req) goes out of scope.. something bad may happen. Is the first implementation really faulty?

Can make a unit test upon request, if this really appears to be a bug

**Comment by adamdickmeiss** [comment]
The first method was originally two methods .. one which simply returned Future<HttpClientResponse> .. That did not work and so I refactored it into one .. It was failing anyway.. And so I ended up with the 2nd implementation, which works better.

In what way is it dubious ?

**Comment by adamdickmeiss** [comment]
[HttpClientOptionsTest.txt](https://github.com/eclipse-vertx/vert.x/files/6043912/HttpClientOptionsTest.txt)

**Comment by tsegismont** [comment]
Cannot reproduce with 4.3.4
