### ISSUE TITLE
When does vert.x support http3?

### ISSUE THREAD

**Issue by T-baby** [eclipse-vertx/vert.x#3755]
When will vert.x support http3? Do you have a plan yet?

**Comment by vietj** [comment]
we are waiting first for HTTP/3 support in Netty for this.

**Comment by re-thc** [comment]
Netty has preliminary http3 support, see: https://github.com/netty/netty-incubator-codec-http3

**Comment by vietj** [comment]
we're going to add it to our roadmap @re-thc

**Comment by vietj** [comment]
it is actually already there as consideration https://github.com/vert-x3/issues/issues/566

we should have a quick look to see how difficult it is to implement.

for the moment, we are maintaining two implementations of HTTP because HTTP/1 and HTTP/2 have different APIs, that would be another API to support, so we might refactor things to ease this support

**Comment by larsnaesbye** [comment]
HTTP/3 in Vert.X would be absolutely great 👍🏼

**Comment by ScepticMatt** [comment]
Thumbs up for HTTP/3 support

**Comment by blackblather** [comment]
IETF standardized HTTP/3 last month in RFC9000 -> https://en.wikipedia.org/wiki/HTTP/3
Would be really cool to have vertx support it

**Comment by olenagerasimova** [comment]
hi, do not see any documentation about http3 support. Was it implemented? Maybe at least in some pre-release mode?

**Comment by vietj** [comment]
Hi,

it is not yet developped.

**Comment by larsnaesbye** [comment]
Reactor-Netty feels comfortable enough to include the Netty HTTP/3 module now...

https://github.com/reactor/reactor-netty/releases/tag/v1.2.0-M2

**Comment by indiealexh** [comment]
Following up on this feature

**Comment by vietj** [comment]
thanks for pointing this out, we are looking forward implementing it in the near future

**Comment by mikadev** [comment]
https://spring.io/blog/2024/11/26/http3-in-reactor-2024

**Comment by indiealexh** [comment]
FYI for People waiting on this:

https://github.com/eclipse-vertx/vert.x/pull/5311

It's coming 🎊
