### ISSUE TITLE
P12 Keystore for Signing JWTs

### ISSUE THREAD

**Issue by predhme** [eclipse-vertx/vert.x#3757]
I am running into issues using a P12 keystore to generate a JWT:

```
java.lang.RuntimeException: Algorithm not supported: HS384
	at io.vertx.ext.auth.impl.jose.JWT.sign(JWT.java:334) ~[vertx-auth-common-4.0.0.jar:4.0.0]
	at io.vertx.ext.auth.jwt.impl.JWTAuthProviderImpl.generateToken(JWTAuthProviderImpl.java:182) ~[vertx-auth-jwt-4.0.0.jar:4.0.0]
```

I am using Java11, Gradle 6.6 with the following dependencies:

```
implementation 'io.vertx:vertx-web:4.0.0'
implementation 'io.vertx:vertx-auth-jwt:4.0.0'
```

I have a simple verticle that is attempting to write out a user credential JSON to a JWT. I configure the JWTAuth as such:

```java
KeyStoreOptions keyStoreOptions = new KeyStoreOptions().setPath(keystore).setPassword(keystorePassword);
JWTAuthOptions authOptions = new JWTAuthOptions().setKeyStore(keyStoreOptions);
this.provider = JWTAuth.create(vertx, authOptions);
```

In a `login` handler, I am doing the following:

```java
ObjectMapper mapper = new ObjectMapper();
String entityJson = mapper.writeValueAsString(entity);
String token = this.provider.generateToken(new JsonObject(entityJson), new JWTOptions().setAlgorithm("HS384"));
```

Any suggestions?

**Comment by predhme** [comment]
As a note, I use the same keystore path and password to configure the HTTPS connector for my verticle.

**Comment by pmlopes** [comment]
@predhme assuming the key types + labels are correct are you loading the keystore with the right type?

```java
KeyStoreOptions keyStoreOptions = new KeyStoreOptions()
  .setType("PKCS12")  // <-- not doing this will assume the keystore format is the JDK system default `KeyStore.getDefaultType()`
  .setPath(keystore)
  .setPassword(keystorePassword);
```

Note that on OpenJDK >=9 `PKCS12` should the default, but other JVMs may have other defaults so it is required to be explicit in this case.

**Comment by predhme** [comment]
@pmlopes I tried setting the type, but that wasn't the problem. The problem for us seems be that it is assumed that the keys have specific aliases. We are good to go. Thanks
