### ISSUE TITLE
You think you can get away without putting one out for scala?

### ISSUE THREAD

**Issue by MironAtHome** [eclipse-vertx/vert.x#3758]
:)

**Comment by vietj** [comment]
@MironAtHome there is currently a discussion on vertx-dev about this $topic where @codepitbull explains what is going on. You are welcome to read it and become involved.

**Comment by vietj** [comment]
For the record https://groups.google.com/g/vertx-dev/c/sKW82LNdDhU/m/Rqi1ZtrcDQAJ
