### ISSUE TITLE
clientRequest not available in Interceptor

### ISSUE THREAD

**Issue by LarsEckart** [eclipse-vertx/vert.x#3763]
### Version

vertx 4.0.0

### Context

In my interceptor, I want to know (once the request was done) what the request method was. To me it looks like I should retrieve the clientRequest from the HttpContext and from that object i can ask getMethod(). But the clientRequest method always returns null (although according to documentation, this should only happen during PREPARE_REQUEST phase, not in later phases.

### Reproducer

* https://github.com/LarsEckart/vertx-local-context-data-example/blob/main/src/test/java/com/larseckart/vertx/example/example/WebClientInterceptorTest.java

this test prints

09:50:27.871 [Test worker]  INFO  c.l.v.e.e.WebClientInterceptorTest - PREPARE_REQUEST
09:50:27.871 [Test worker]  INFO  c.l.v.e.e.WebClientInterceptorTest - SEND_REQUEST
09:50:27.871 [Test worker]  ERROR c.l.v.e.e.WebClientInterceptorTest - didn't expect clientRequest to be null
09:50:27.891 [vert.x-eventloop-thread-0]  INFO  c.l.v.e.e.WebClientInterceptorTest - RECEIVE_RESPONSE
09:50:27.891 [vert.x-eventloop-thread-0]  ERROR c.l.v.e.e.WebClientInterceptorTest - didn't expect clientRequest to be null
09:50:27.897 [vert.x-eventloop-thread-0]  INFO  c.l.v.e.e.WebClientInterceptorTest - DISPATCH_RESPONSE
09:50:27.897 [vert.x-eventloop-thread-0]  ERROR c.l.v.e.e.WebClientInterceptorTest - didn't expect clientRequest to be null

ignore the rest of the project, that was for another issue.

### Extra

I debugged a bit. in HttpContext line 558, clientRequest field is assigned, and I figured that cool, it must be working. But when i let the code continue to execute, breakpoint at line 549 is hit and clientRequest is again set to null. So looks like there is a race condition or so between the request's onComplete handler and the continuation handler.

**Comment by vietj** [comment]
can you move this issue to vertx-web project ?

**Comment by LarsEckart** [comment]
done. https://github.com/vert-x3/vertx-web/issues/1851
