### ISSUE TITLE
Indeterministic JsonCodec lookup 

### ISSUE THREAD

**Issue by cescoffier** [eclipse-vertx/vert.x#3766]
At the moment the lookup for implementation of the `JsonCodec` SPI is indeterministic and depends on the classpath ordering and packaging of the application. Thus, the same application may end up with the built-in Jackson code or with a custom one. 

In my case, I must ensure that it loads the custom one regardless of the classpath ordering and packaging.

I can see two approaches:

- have the possibility to ignore the built-in codec, if there is another one available
- have a smarter way to load the SPI sorting the implementation by _priority_

In my case, the first approach is enough, but the second one allows handling situations where 3 or more implementations are available.

**Comment by vietj** [comment]
It is not clear which issue you are running into as Vert.x default codec is not declared with META-INF/services and when a META-INF codec is found and loaded then it will be the priority. Can you clarify which issue you are running into ?

**Comment by vietj** [comment]
I think we should make Vert.x json codec not loaded from SPI and instead loaded manually if no other codec is present on the classpath. This way Quarkus will end up with a single implementation and solve the issue.

**Comment by cescoffier** [comment]
Yes that would work too. But we need to make absolutely sure that the implementation is not loaded if Jackson is not present in the classpath.

**Comment by cescoffier** [comment]
> It is not clear which issue you are running into as Vert.x default codec is not declared with META-INF/services and when a META-INF codec is found and loaded then it will be the priority. Can you clarify which issue you are running into ?

It is: https://github.com/eclipse-vertx/vert.x/blob/3.9/src/main/resources/META-INF/services/io.vertx.core.spi.json.JsonCodec

**Comment by vietj** [comment]
thanks, I was assuming the issue was scoped for 4.0 and then deleted this
message as I found it was for 3.9

**Comment by vietj** [comment]
@geoand you might want to contribute to this ?
