### ISSUE TITLE
Performance problem in EventBus messages dispatch implementation

### ISSUE THREAD

**Issue by Cavallium** [eclipse-vertx/vert.x#3769]
### Version

Which version(s) did you encounter this bug ?

4.0.0

### Context

I found a performance related problem in the class ReplyHandler: the message decoding of my message codecs always happen inside the event loop, regardless on where I call .body().
When a message gets big, this bug can block the event loop for a moment.

### Do you have a reproducer?

No, the bug can be easily fixed, it involves changing just one line of code.

### Steps to reproduce

1. Create a custom MessageCodec for the event bus
2. Set a breakpoint on the decodeFromWire function
3. See from where the call originates
4. It will be from io.vertx.core.eventbus.impl.ReplyHandler, line 89

### Extra

This bug can be fixed by not calling "reply.body()" in line 89 of ReplyHandler.
That code in ReplyHandler checks if the decoded message is "ReplyException", but it can't be a ReplyException if the message codec is a custom one.

**Comment by vietj** [comment]
did you check the behavior with Vert.x 3 ?

**Comment by Cavallium** [comment]
I found [the commit](https://github.com/eclipse-vertx/vert.x/commit/00eceab7458293aad842b593a09de59925315a3b).
It's from 7 years ago

**Comment by Cavallium** [comment]
https://github.com/eclipse-vertx/vert.x/commit/00eceab7458293aad842b593a09de59925315a3b#diff-4ac931e2cce308995f6889925d17f3ed8a06dad6434a4434a1d3295cfb23e176R725

**Comment by vietj** [comment]
but it is expected to have body decoded on the event-loop. We do not recommend to send messages which are too large on the event bus. If it were not be done at this place then it would eventually occur on the event-loop too when the user calls body().

**Comment by tsegismont** [comment]
>  it can't be a ReplyException if the message codec is a custom one.

@Cavallium actually it can, although this is not documented https://github.com/eclipse-vertx/vert.x/pull/1392

One could create a custom codec for a subclass of `ReplyHandler` and use `Message#reply` with an instance of this subclass instead of `Message#fail` (that constraints the exception to be a ReplyException).

As @vietj said, the EventBus is not designed to send large payloads. For expected use cases, the penalty of decoding the body on the event loop should be minimal.

**Comment by Cavallium** [comment]
Ok, thanks.
My payload was quite big because I buffered up to 100 items into each message.
Now I resolved the problem by removing the buffering, sending one item per message.
I tried to do this because my server was receiving a huge quantity of messages (up to 50'000/s) in some circumstances, and I thought that buffering them was a good idea.

p.s. you should document the ReplyException codec feature
