### ISSUE TITLE
EventBus Tracing: change message tag name to message_bus.destination

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vert.x#3773]
`MessageTagExtractor` uses `peer.service` tag name for eventbus address. According to the [conventions doc](https://github.com/opentracing/specification/blob/master/semantic_conventions.md), it should be `message_bus.destination`.

**Comment by vietj** [comment]
I did not use messaging because I was considering that event bus is RPC and not a messaging system.

**Comment by vietj** [comment]
but I think it's fine
