### ISSUE TITLE
Service verticle factory does not rested worker setting

### ISSUE THREAD

**Issue by underkin** [eclipse-vertx/vert.x#3779]
Version 4.0

I deploy most of the vertices as services with a json service descriptor. 
When moving from 3.x to 4  I noticed that services that are marked as 'worker:true' are not being deployed as worker vertices and are executed in a even loop thread.

How to reproduce:

1.- Deploy any service verticle as a worker verticle (worker:true in the json descriptor in the 'options' section)
2.- The easiest way to verify if it is a worker verticle is to log something and check the thread name. Otherwise, you can use VertxThread.isWorker() 

Seems to be an issue with the code in the service Factory, when it merges the config from the context.

**Comment by vietj** [comment]
do you mean using https://github.com/vert-x3/vertx-service-factory project ?

**Comment by underkin** [comment]
yes. Sorry if I din't explain it correctly.

**Comment by vietj** [comment]
can you reopen this issue on this GitHub repo ?

**Comment by underkin** [comment]
Sorry. Will do now.

**Comment by vietj** [comment]
thanks
