### ISSUE TITLE
TLS Certificates hitless rotation

### ISSUE THREAD

**Issue by slinkydeveloper** [eclipse-vertx/vert.x#3780]
#### Describe the feature

We need a way to automatically reload certificates from files when they're expired.

#### Use cases

In Kubernetes and other orchestration platforms it's very common to have a system that automagically rotate self-signed TLS certificates when expired https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/. These systems simply replace the .ca and .key files with new valid values.

Prior art in Golang: https://diogomonica.com/2017/01/11/hitless-tls-certificate-rotation-in-go/

#### Possible solutions

Every time a certificate is requested during the TLS handshake, Vert.x could check if the actual certificate is expired and, if that's the case, it can try reload it from file.
Another solution could be a more generic method like `GetCertificate` in Golang that is invoked every time a new certificate is requested. Inside it, the user can do whatever it wants (reload every time from file, have some cache that refreshes the certificate asynchronously, etc)

**Comment by tsaarni** [comment]
I can work on this issue.

I would prefer approach where Vert.x handles reload on behalf of the application when it can, without modifying the application.

I have small doubt about delaying the reload to the expiration. Certificate would be typically replaced much earlier and it would be nice to confirm that the update took effect before the very last minute. It should be easier to troubleshoot when things fail fast, and the fault is more directly associated with the certificate update.

An alternative trigger could be to watch for filesystem events by using `WatchService` if having a threat(s) for watcher(s) is OK in Vert.X? Also, there can be some complexity in setting what to watch. What works with Kubernetes `Secret` volume mounts, does not necessarily work for other use cases.  We could default to watching moves on parent directory of cert/key, which works for Kubernetes `Secret` volumes, but also provide API to set the watched directory explicitely (similar approach as taken by [Envoy](https://www.envoyproxy.io/docs/envoy/latest/configuration/security/secret#key-rotation)).

What do you think?

**Comment by vietj** [comment]
I think this should be achieved in a small contrib library

**Comment by vietj** [comment]
it can be done in the vertx proiject

**Comment by tsaarni** [comment]
Would it be out of the question to implement hot-reload support inside "core" code (that is, not in contrib library)? I was hoping to avoid changes in applications.

**Comment by tsaarni** [comment]
Some background why I'm looking into this: An application I use moved from Wildfly to Quarkus and lost its capability to hot-reload certificate and key https://github.com/keycloak/keycloak/discussions/10654.  While investigating that, I found out that Quarkus uses Vert.x and implementing this issue would bring the functionality back. I think it could be beneficial to all other applications as well.

**Comment by Hakky54** [comment]
Hi everyone, I have added my input regarding reloading the ssl configuration here: https://github.com/eclipse-vertx/vert.x/issues/4452 I am curious what everyones opinion would be for the solution.

**Comment by vietj** [comment]
See https://github.com/eclipse-vertx/vert.x/pull/4568
