### ISSUE TITLE
Flood control

### ISSUE THREAD

**Issue by glcanvas** [eclipse-vertx/vert.x#3783]
I built RestEasy server under Netty and Vert.x
Now I transfer a huge file from the server's database to the client wia java stream

Client and network too slow for this huge file, and Netty consume all memory while allocating **io.netty.channel.ChannelOutboundBuffer$Entry**. It occured because RestEasy and Vert.x don't communicate with Netty about flood control.

Maybe exists some techniques for such flooding?

**Comment by vietj** [comment]
which Resteasy implementation are you using ?

I would for this use case consider using vert.x directly as it will
implement flow control with Netty.

**Comment by glcanvas** [comment]
I use vertx-3.5.2

I'll try to implement your proposal.
Thank you!
