### ISSUE TITLE
 Why did Connection was closed appear after NoStackTraceTimeoutException

### ISSUE THREAD

**Issue by fashion6years** [eclipse-vertx/vert.x#3784]
### Questions

HttpClient encounters io.vertx.core.http.impl.NoStackTraceTimeoutException (the timeout I set is 3 seconds) when sending a request. After being caught by the exceptionHandler, this exception is printed in the exceptionHandler, but then io.vertx.core is captured. VertxException: Connection was closed (the idle time I set was 10 minutes), which caused me to print two exceptions. Why did Connection was closed appear after NoStackTraceTimeoutException? 

### Version

3.9.4

```java

HttpClientRequest outgoingRequest = httpClient.requestAbs(incomingRequest.method(), fullUrl)
                .setFollowRedirects(true)
                .handler(clientResponse -> handleProxyResponse(pc, clientResponse))
                .exceptionHandler(t -> {
                    //在这里我会打印出两个日志，一个是NoStackTraceTimeoutException，另一个是Connection was closed，但是我仅仅触发了NoStackTraceTimeoutException
                    log.error("handle proxying error, traceId {}, original request {}, proxying request {}", pc.traceId(), incomingRequest.absoluteURI(), fullUrl);
                    quickCloseResponse(pc, t);
                });

**Comment by vietj** [comment]
I can''t sett the timeout set in your code, what am I missing ?

**Comment by vietj** [comment]
I was not able to reproducer, you can reopen with a small and complete reproducer.
