### ISSUE TITLE
WebSocket closeHandler not invoked when call close() when network  barrier between client and server

### ISSUE THREAD

**Issue by fangnoo** [eclipse-vertx/vert.x#3785]
### Questions

websocket conentcion:  client ->  nginx -> sever (websocket)
 when network  barrier between client and nginx.   and server call WebSocet close() function, closeHandler will not be invoked. 

in previous version, it will invoked, and i notice this issue: https://github.com/eclipse-vertx/vert.x/issues/3531

this will be fine when network is OK.  in my secene (network barrier, cannot ping to client), this will not work, due to no close frame echo back.

can i have some other close() funciton to invoke clsoeHandler directly?

### Version

 
3.9.3

**Comment by vietj** [comment]
the WebSocket should be considered close when the echo frame is received.

When the echo frame is not received in time the close socket timeout on `HttpServerOptions` or `HttpClientOptions` will consider the socket as closed. This was introduced in december and will be released in 3.9.6

**Comment by vietj** [comment]
the WebSocket should be considered close when the echo frame is received.

When the echo frame is not received in time the close socket timeout on `HttpServerOptions` or `HttpClientOptions` will consider the socket as closed. This was introduced in december and will be released in 3.9.6
