### ISSUE TITLE
SLF4JLogDelegateFactory is going to leak forever

### ISSUE THREAD

**Issue by Tibor17** [eclipse-vertx/vert.x#3791]
`System.setErr(new PrintStream(new ByteArrayOutputStream()))` has to leak. The `ByteArrayOutputStream` has a buffer `buf` which limit would always grow. In order to prevent the buffer from growing infinitelly you have to override the `write(int b)` and `write(byte b[], int off, int len)` methods to be empty.
IMO you used `ByteArrayOutputStream` because you did not want to crearte a new class. I am the Apache developer who develops Surefire Plugin. My recommendation for you is to follow the hint in Surefire and implement the same [NullOutputStream](https://github.com/apache/maven-surefire/blob/master/surefire-api/src/main/java/org/apache/maven/surefire/api/report/ConsoleOutputCapture.java#L227) and use it instead of `ByteArrayOutputStream`.

### Version
`4.0.2`

### Context

I am going to implement my own `DelegateFactory` for `slf4j-simple` and I have found the implementation of `SLF4JLogDelegateFactory` in the JAR of the core.

**Comment by vietj** [comment]
thanks @Tibor17

**Comment by vietj** [comment]
this was done in order to avoid some spurious print on the console when the swap is achieved.

as you can see the swap is temporary for the duration of the `try` block, then the stream is set of back to the original value in the `finally` clause.

**Comment by vietj** [comment]
what issue did you find in practice ?

**Comment by Tibor17** [comment]
> 
> 
> this was done in order to avoid some spurious print on the console when the swap is achieved.
> 
> as you can see the swap is temporary for the duration of the `try` block, then the stream is set of back to the original value in the `finally` clause.

@vietj 
Thx for your reply. Yes, I understand the point, we have a similar principle in Surefire. The std/err is backed up, the tests run, and renewing the stream back to the origin. I have understood that VertX wants to avoid spurious prints by setting some OutputStream which simply does nothing.

**Comment by Tibor17** [comment]
> 
> 
> what issue did you find in practice ?

no not in practice but it may happen of course. It is just a cheap improvement.
I can implement this improvement in a new PR if you agree.

**Comment by vietj** [comment]
my point is that this is done just for the duration of a single method call
and then the output is thrown away, so I'm willing to understand what I'm
missinghere

**Comment by Tibor17** [comment]
you'r right, the call `LoggerFactory.getILoggerFactory()` should not cache critically big data in practice.

**Comment by vietj** [comment]
thanks, I was afraid to have missed a critical leak
