### ISSUE TITLE
Set proxy per request

### ISSUE THREAD

**Issue by alamothe** [eclipse-vertx/vert.x#3795]
Hello,
We ported our service to use Vert.x awhile ago. While using Vert.x we still used Apache HTTP client without problems. However, now I tried to port also this functionality to Vert.x and I hit a problem.

It seems that Vert.x HttpClient does not allow to set a proxy per request, only on the client level. We use 1000+ proxies simultaneously to scrape websites. 

Is there any workaround? How feasible is to create an instance per request?

**Comment by vietj** [comment]
do you mean a forward proxy in front of a request ?

**Comment by alamothe** [comment]
Yes. I found the docs here: https://vertx.io/docs/vertx-core/java/#_using_a_proxy_for_httphttps_connections

But it has to be set before creating a client. 

How heavy it is to create a client for each request?

**Comment by vietj** [comment]
it is quite lightweight.

keep in mind to close the client.

we will likely work toward having a setting per HTTP request, however for
proxy this has consequence on the connection pooling.

**Comment by vietj** [comment]
note also that Vert.x 4.1 should allow to connect to an HTTP server without a connection pool which might make this use case easier.

**Comment by vietj** [comment]
@alamothe I think the point here is pooling because the client might cache a client connection that was established using a specific proxy. In your scenario do you intend to connect to the same server using different proxies ? or will a remote server always use the same proxy ?

**Comment by alamothe** [comment]
@vietj Thanks so much for working on this!

In our case, we will connect to the same server using different proxies. It is essential that the connection is not reused if proxies are different even though the destination is the same. Even if just proxy authentication is different, it should not reuse the proxy.

Can you please tell me if the implemented solution satisfies this?

Is there any way to attach a "token" to a connection, like in Apache HTTP client?

**Comment by vietj** [comment]
you can now have a `ProxyOptions` per `RequestOptions`

I don't understand what you mean by token

**Comment by alamothe** [comment]
In Apache HTTP client, you can add a custom "token" to a request (connection), and it will reuse only connections with the sam token.

In our scenario (same server, different proxies), will Vert.x HTTP client try to reuse the connection if it was initiated with a different proxy to the same server?

**Comment by vietj** [comment]
I think to have several tokens you should instead use one instance of
HTTP client.
