### ISSUE TITLE
TCP metrics, Active server connections with negative values

### ISSUE THREAD

**Issue by Mersenne255** [eclipse-vertx/vert.x#3796]
### Version
vertx-core 4.0.0
vertx-micrometer-metrics 4.0.0

### Context
We noticed that one of our positive-only metric is having negative values on several instances.
Using micrometer library, metric is named **vertx_http_server_active_connections**
This problem is however related to vertx-core metric abstraction. More precisely, how vertx-core handles connection opening and active connections metric increase.

### Steps to reproduce

Reproducer: https://github.com/Mersenne255/vertx_issue_3796_reproducer

We've been able to easily reproduce metric going into negative values using vertx HTTP/2.0 server with SSL enabled.
But I believe this issue is relevant for all types of connections.
Idea how to reproduce is to close the TCP connection right after it was initialized, but connection number wasn't increased yet.
Connections metric decrease is abstracted inside class io.vertx.core.net.impl.ConnectionBase, so even when the connection count wasn't increased on connection open, it would still be decreased on connection close.

1. Start HTTP/2.0 vertx server over SSL
2. Run a client of this service, with io.vertx.core.net.TCPSSLOptions#sslHandshakeTimeout of ~100-200ms (for local run) - this might take multiple tries, as client closing connection must hit precisely timeframe within server processing, when connection was already established, but metrics not yet increased

### Extra
JVM 15
OS version: fedora-coreos-31
Hosted on AWS EC2

**Comment by vietj** [comment]
can you provide a reproducer project ?

**Comment by Mersenne255** [comment]
> can you provide a reproducer project ?

https://github.com/Mersenne255/vertx_issue_3796_reproducer

It's plain vertx SSL H2 server with self signed cert.
You can run curl command (see in README.md) on top of it to get a connection timeout.
This should result in negative metric values.

**Comment by vietj** [comment]
thanks

**Comment by vietj** [comment]
I'm not able to reproducer with your reproducer, however I found indeed an issue that happens when the connection is closed after the SSL handshake and before the server receives the client connection preface.
