### ISSUE TITLE
EventBus consumer and localConsumer scalability when deployed clustered

### ISSUE THREAD

**Issue by DemonicTutor** [eclipse-vertx/vert.x#3797]
### Version

4.0.0-milestone5
[Change clustered registration model](https://github.com/eclipse-vertx/vert.x/commit/d4ba7535c807e939368ab92f9df777e8204996f9)

### Context

Clustered application crashes in production since upgrading to VertX 4.0.1.

This application uses a WebSocket to EventBus bridge creating MessageConsumers 1:1 to websocket connections.
These Websockets are used by end-user UI and therefore has to scale on both establishing connections and active connection dimensions.

In VertX 3.9.5 up to M5 this was not an issue because registration only happend on a per node basis.

### Do you have a reproducer?

https://github.com/DemonicTutor/vertx-clustereventbus-performance

### Steps to reproduce

1. clustered VertX application
2. deploy 2 or more nodes
2. create consumers / localConsumers **or** unregister them - both trigger the issue

### Extra

openJdk 15

#### previously ClusteredEventBus **ignored** localOnly 
* https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java#L128
* https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredEventBus.java#L147

a) this seems useless to me because **Selector** filters localOnly out again
b) because of this there is no easy way to simply avoid the cluster-overhead

#### Selectors implementation evaluates *all* registrations on update - does not scale if adding more consumers
https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/spi/cluster/impl/selector/Selectors.java#L75

**also** in case of adding nodes / startup of the entire cluster this approach seems wasteful ?
when one node is running and another starts up the first node would get each created consumer via update - **reading the entire clustered map** for each update.
So if we create 10 consumers in an application it would 
- update 1
- read 1
- update 2
- read 2
and so on...
**and** because the clustered Map is based on **address** it reads **every** node
so if you have a cluster of 10 nodes - add node 11 - you fetch data from all 11 nodes.

#### Update Event only allows updating all registrations
https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/spi/cluster/RegistrationUpdateEvent.java

#### SubsMapHelper does not scale - uses a LOT of network / cpu
https://github.com/vert-x3/vertx-hazelcast/blob/master/src/main/java/io/vertx/spi/cluster/hazelcast/impl/SubsMapHelper.java

While only adding a few consumers this is fine.

But if you either need "a lot" of consumers **or** need to create them dynamically (as is our case) this simply does not scale

for every single added consumer the entire map is read and triggers the update.

**Comment by tsegismont** [comment]
Thanks for the write-up @DemonicTutor

**Comment by DemonicTutor** [comment]
@tsegismont you are welcome!

If you see anything stupid i did in my reproducer that just fails to highlight the issues properly let me know.
It was the easiest i could think of to show what i am talking about.

**Comment by tsegismont** [comment]
@DemonicTutor no it's clear enough, thanks again

**Comment by DemonicTutor** [comment]
In case someone else runs into these issues. If you try to work around it by doing a N:1 MessageConsumer: **it is not that easy**

Because every ServerWebSocket creates 2 local MessageConsumers: https://github.com/eclipse-vertx/vert.x/blame/4.0.2/src/main/java/io/vertx/core/http/impl/WebSocketImplBase.java#L110-L111

**Comment by tsegismont** [comment]
@DemonicTutor FYI, I've made some progress on fixing the high CPU / delayed shutdown issue, I created two branches in [vert.x core](https://github.com/tsegismont/vert.x/commits/cluster-sub-perf) and [vertx-hazelcast](https://github.com/tsegismont/vertx-hazelcast/commits/cluster-sub-perf).

I have tested the changes on this [bench](https://github.com/tsegismont/eventbus-registration-bench) with good results.

I am confident that we can get this in the next Vert.x 4 release

**Comment by tsegismont** [comment]
Fixed in #3843, vert-x3/vertx-hazelcast#139 and vert-x3/vertx-hazelcast#140
