### ISSUE TITLE
Support for passing URL in RequestOptions

### ISSUE THREAD

**Issue by anatak** [eclipse-vertx/vert.x#3803]
#### Describe the feature

The `io.vertx.core.http.RequestOptions` in Vert.x 4.0.0 allows to set up instance with absolute Uri as a `String` via `RequestOptions().setAbsoluteUri(...)`.  Could be this extended also for providing Uri as a `java.net.URL` ? 

#### Use cases

In our calls we have a request uri directly in `java.net.URL` . For creating `RequestOptions` instance, we have to convert `URL` to `String`, enabling us to call `setAbsoluteUri`. But inside of this `String` is immediately parsed back to URL via `RequestOptions.parseUrl()` which is ineffective (as `parseUrl` correctly mentions it in `Note`).

#### Contribution

I have zero experience with contributing to any library but this could be easy done via splitting `setAbsoluteUri` into parsing and processing method:
```java
  public RequestOptions setAbsoluteURI(String absoluteURI) {
    Objects.requireNonNull(absoluteURI, "Cannot set a null absolute URI");
    return this.setAbsoluteURI(parseUrl(absoluteURI));
  }

  public RequestOptions setAbsoluteURI(URL url) {
    Objects.requireNonNull(absoluteURI, "Cannot set a null absolute URI");
    Boolean ssl = false;
    int port = url.getPort();
    String relativeUri = url.getPath().isEmpty() ? "/" + url.getFile() : url.getFile();
    String protocol = url.getProtocol();
    switch (protocol) {
      case "http":
        if (port == -1) {
          port = 80;
        }
        break;
      case "https": {
        ssl = true;
        if (port == -1) {
          port = 443;
        }
        break;
      }
      default:
        throw new IllegalArgumentException();
    }
    this.uri = relativeUri;
    this.port = port;
    this.ssl = ssl;
    this.host = url.getHost();
    return this;
  }
```

**Comment by vietj** [comment]
do you mind contributing this ?

**Comment by anatak** [comment]
@vietj I can try, if i have some spare time. 

I presume, that reading https://github.com/eclipse-vertx/vert.x/blob/master/CONTRIBUTING.md is the starting point :), then possibly there is some kind of forum where, i can ask some questions.

**Comment by vietj** [comment]
you can come on Discord, the link is on vertx.io among the top right icons
