### ISSUE TITLE
Cannot modify metrics options via sysprop or custom Launcher 

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vert.x#3804]
A custom Launcher is often used when you want to setup things like metrics options programmatically before Vert.x is started.

Since #3771 , it is no longer possible to do this because the builder init method is invoked before the Launcher callback.

Then it's too late to customize the metrics implementation.

This applies to other special options too, I think (e.g. tracing, cluster manager).

EDIT: actually, it's no longer possible to activate some metrics options with sysprops. From Dropwizard docs:

```
-Dvertx.metrics.options.enabled=true -Dvertx.metrics.options.jmxEnabled=true
```

**Comment by tsegismont** [comment]
Perhaps we should do:

```java
    configureFromSystemProperties.set(log);
    try {
      configureFromSystemProperties(options, VERTX_OPTIONS_PROP_PREFIX);
      if (options.getMetricsOptions() != null) {
        configureFromSystemProperties(options.getMetricsOptions(), METRICS_OPTIONS_PROP_PREFIX);
      }
      beforeStartingVertx(options);
      builder.init();
    } finally {
      configureFromSystemProperties.set(null);
    }
```

instead of

```java
    configureFromSystemProperties.set(log);
    try {
      configureFromSystemProperties(options, VERTX_OPTIONS_PROP_PREFIX);
      if (options.getMetricsOptions() != null) {
        configureFromSystemProperties(options.getMetricsOptions(), METRICS_OPTIONS_PROP_PREFIX);
      }
      builder.init();
    } finally {
      configureFromSystemProperties.set(null);
    }

    beforeStartingVertx(options);
```

**Comment by tsegismont** [comment]
The fix in https://github.com/eclipse-vertx/vert.x/commit/d9f1b16272c1d79828ca7d970352f3c3eb461a11 allows to use sysprop again but it's still not possible to modify options in a custom `Launcher`.

I'll send a separate PR

**Comment by vietj** [comment]
@tsegismont so it was not something that was tested right ?

**Comment by tsegismont** [comment]
It seems not. I'm pretty sure I added the test myself so perhaps the test is no longer valid after the builder changes.

**Comment by vietj** [comment]
that's the only test I removed, perhaps you can write a new one against 3.9
and port it in 4

**Comment by tsegismont** [comment]
@vietj doing it now. I went back to the test suite and I was wrong: there is no test.

I will add one to Vert.x 3 as you said and port it to Vert.x 4

**Comment by tsegismont** [comment]
@vietj so here's a test on Vert.x 3.9 that checks you can modify `VertxOptions`:

https://github.com/eclipse-vertx/vert.x/blob/5dee3511fdb41354a5381a55ad9abb5ab5d5514a/src/test/java/io/vertx/core/impl/launcher/LauncherExtensibilityTest.java#L109-L158

Unfortunately this option has been removed in 4.0 and so has the test... But the use case of customizing options programmatically remains valid.

**Comment by tsegismont** [comment]
@vietj see https://github.com/eclipse-vertx/vert.x/pull/3809
