### ISSUE TITLE
HttpClientRequest hangs on subsequent requests in worker verticle.

### ISSUE THREAD

**Issue by russthom** [eclipse-vertx/vert.x#3814]
### Version

vertx-core 4.0.2

### Context

We have encoured an issue whereby after a variable amount of subsequent reqeuests using HttpClientRequest, it appears that the subsequent response handlers are not called, and the request hangs.

We had used a variation of this pre vertx-core 4.0.0 which we cannot reproduce the issue on.

It appears to fail quicker when keep-alives are enabled, and quicker with a larger response size (256K and above).

This appears to only happen when running in a worker verticle, it is not reproducable when DeploymentOptions has worker set to false.

### Do you have a reproducer?

https://github.com/russthom/vertx-httpclientrequest-issue

### Steps to reproduce

1. mvn package
2. serve up 'testfile' on localhost:8080 (I generate a random 512K, e.g 'head -c 512K </dev/urandom > testfile')
3. run the jar (java -jar target/vertx-httpclient-test-0-jar-with-dependencies.jar)
4. it will hang on the request after 2/3rd run

### Extra

* Java 11, but also reproducable with Java 15.
* Running on RHEL 8, but also reproducable on Arch.

**Comment by vietj** [comment]
This is closed by https://github.com/eclipse-vertx/vert.x/issues/3849
