### ISSUE TITLE
Does vertx support Transaction, like akka's STM feature?

### ISSUE THREAD

**Issue by cay914** [eclipse-vertx/vert.x#3815]
Hi,  I am new to vert.x, and I want to  find out Transaction on vert.x. 
In akka's can do this. user STM, Coordinated transactions.

Scenario:
A user tranfers 100$ to B user. A's account deduct 100$, B's account increase 100$.
When B's increase fail, roll back A 's 100$.

I think transaction is very important for a reliable system. Does vertx miss this feature?
How can I do with Vertx, please help

**Comment by vietj** [comment]
@cay914 vert.x supports database transactions with the SQL client.

you can try using https://github.com/pveentjer/Multiverse as it seems to provide an STM like project easy to integrate according to the README.
