### ISSUE TITLE
config().getString is not perfect

### ISSUE THREAD

**Issue by sunqb** [eclipse-vertx/vert.x#3816]
### Question

when i do not use "put("raw-data", true)"  ,if my config is :
password=123456

I get a value "123456.0" by this method config.getString("password");

but

when I use  "put("raw-data", true)", this problem is ok ，but i have an other config  
port=80

I get an error  when i use config.getInteger("port")，because it was not supported.

### Version

4.0.2

**Comment by sunqb** [comment]
so I must use Integer.valueof(config.getString("port"))

**Comment by vietj** [comment]
what kind of config object are you talking about ? it is not clear

**Comment by sunqb** [comment]
> what kind of config object are you talking about ? it is not clear
this:

 options.addStore(new ConfigStoreOptions().setType("file").setFormat("properties").setOptional(true)
                .setConfig(new JsonObject().put("path", "conf/config.properties").put("raw-data", true)));

**Comment by vietj** [comment]
can you move this issue to this project https://github.com/vert-x3/vertx-config ?
