### ISSUE TITLE
Support RxJava2 API in Vert.x OpenAPI 

### ISSUE THREAD

**Issue by ahoora08** [eclipse-vertx/vert.x#3832]
Hi,

In version `4.0.2` the `Vert.x Web API Contract` is deprecated and the document suggested using `Vert.x OpenAPI` but I noticed it has no support for RxJava2 API.

If you consider this as a feature, please give me some information about it so I can implement and contribute.

Thanks

**Comment by vietj** [comment]
this was easy to implement on the vertx-rx, however it required some improvements done by @slinkydeveloper in vertx-web-openapi
