### ISSUE TITLE
why WebSocketFrame do not have type()?

### ISSUE THREAD

**Issue by sunqb** [eclipse-vertx/vert.x#3833]
#### Read me

the interface WebSocketFrame do not have type(),when i need to judge if a frame was a PingFrame,i can only do it like this:

 WebSocketFrameImpl webSocketFrameIml = null;
                if (webSocketFrame instanceof WebSocketFrameImpl) {
                    webSocketFrameIml = (WebSocketFrameImpl) webSocketFrame;
                }
                if (webSocketFrameIml.type().name().equals(FrameType.PING.name())) {
                    pongSocketFrameHandler(webSocket, channelId, webSocketFrameIml);
                }

#### Describe the feature

i expect to add method type() in WebSocketFrame, if i want to know pingframe i can use type() to judge.

**Comment by vietj** [comment]
we do have properties that indicate the kind of frame, e.g `isText()`, I think we should add one for each kind of frame, e.g `isPing()`

**Comment by vietj** [comment]
fixed by https://github.com/eclipse-vertx/vert.x/issues/3851 ,  the internal type enum has made it to the public API.

**Comment by sunqb** [comment]
very good , i have upgrade to 4.0.3. now i can code like this:

if (webSocketFrame.isPing()) {
                   ......
                }
                else {
                    ......
                }
