### ISSUE TITLE
the prefix of empty string in the router leading  to a blocking without any info when the server is on starting?

### ISSUE THREAD

**Issue by jxffly** [eclipse-vertx/vert.x#3835]
### Version

    <vertx.version>4.0.2</vertx.version>

JDK1.8
### code
``
    Router router = Router.router(vertx);
//noticie the empty string in the head
  router.route("   /api/wallet/v1/userInfo/byAddress").handler(context -> context.json(
      new JsonObject()
        .put("code", 0)
        .put("msg", "HELLO WORLD")
        .put("data", 854940268259348481L)
    ));
`

`

### Extra

this will leading to block on start ,

**Comment by jxffly** [comment]
if you can't recurrent the case i cant upload my test code

**Comment by jxffly** [comment]
the platform is macOS  Catalina 15.7

**Comment by tsegismont** [comment]
This is related to Vert.x Web. Please open an issue in the [corresponding repository](https://github.com/vert-x3/vertx-web).
