### ISSUE TITLE
filesystem api: expose file locking operations

### ISSUE THREAD

**Issue by phraktle** [eclipse-vertx/vert.x#3856]
The `lock` and `tryLock` methods of `AsynchronousFileChannel` should be made available for `AsyncFile` wrappers, so one can perform proper file locking operations.

**Comment by dratler** [comment]
Hi @panchmp , @vietj  is this still open for the grab ?

**Comment by vietj** [comment]
yes it is.

**Comment by muhammad-abubakar** [comment]
Hi @vietj  @tsegismont is this still available?

**Comment by tsegismont** [comment]
Yes
