### ISSUE TITLE
How to have a customized security handler in vertx4?

### ISSUE THREAD

**Issue by roostapour** [eclipse-vertx/vert.x#3869]
### Questions

How to have a customized security handler in vertx4?

### Version

vertx4

### Context

I am migrating to vertx4 and have a question about securityHandler (using openapi security scheme). In version 3.9.0 I was using `OpenAPI3RouterFactory` and with calling `addSecurityHandler` was able to pass my own customized security handler like:

```
OpenAPI3RouterFactory.create(vertx, "api.yaml", ar -> {
OpenAPI3RouterFactory rf = ar.result();
 rf.addSecurityHandler("permission1", this::permission1Handler);
 rf.addSecurityHandler("permission2", this::permission2Handler);
 rf.addSecurityHandler("permission3", this::permission3Handler);
}
```
where `permission1`, `permission2`, `permission3` are security schemes in `api.yaml` file and `permission1Handler`, `permission2Handler`, and `permission3Handler` are my customized security handler. For example one of my apis has `permission1` and `permission2` in the yaml file as follows:
```
security:
 - permission1: []
 - permission2: []
```
If both `permission1Handler` and `permission2Handler` succeed, then the rest of the logic for that api get executed. Simply in each of the permission handlers if all the conditions are met I will call `routingContext.next()` otherwise `routingContext.response().setStatusCode().end()`. This is a very simple and convenient way of having security handlers.

But in version 4 I don't know how I can do that? In the documentation it says Use the RouterBuilder.securityHandler() method instead. But this method only accepts `io.vertx.ext.web.handler.AuthenticationHandler` as a handler. How can I have customized security handlers?

**Comment by vietj** [comment]
can you reopen this issue in vertx-web repository ?
