### ISSUE TITLE
JsonArray of enums stream() emits Strings instead of Enums

### ISSUE THREAD

**Issue by ashertarno** [eclipse-vertx/vert.x#3873]
### Version

4.0.3

### Context

JsonArray stream emits expected results for all boxed primitives and String, but not for enums.

### Do you have a reproducer?

```java
public class Test {
    public static void main(String[] args) {
        JsonArray array = new JsonArray().add(TimeUnit.DAYS).add(TimeUnit.MINUTES);
        array.stream().map(t -> {
            System.out.println(t +": " + t.getClass());
            return t;
        }).collect(Collectors.toList());
    }
}
```

result:

> Task :Test.main()
DAYS: class java.lang.String
MINUTES: class java.lang.String

**Comment by pmlopes** [comment]
After inspecting the code, I believe this was the desired behavior. The `stream()` will behave just like `getValue()` which will wrap all non JSON types, for `Enum` it will return it's `name()`, `Buffer/byte[]` will return bas64 strings.

If you really want to iterate the unmodified/unwrapped values you need to:

```java
JsonArray array = new JsonArray().add(TimeUnit.DAYS).add(TimeUnit.MINUTES);
array
// get the storage holder
.getList()
// the stream will now be the unmodified data
.stream()
.map(t -> {
            System.out.println(t +": " + t.getClass());
            return t;
        }).collect(Collectors.toList());
```

We should clarify this in the JavaDoc though.

**Comment by pmlopes** [comment]
@vietj what's your oppinion, do you agree it should be a documentation fix, not a behavior bug?

**Comment by pmlopes** [comment]
Maybe we should have a generic `unwrap()` both on `JsonArray` and `JsonObject` to clearly state that using it you get the unmodified data, this would deprecate the `JsonArray.getList()` and `JsonObject.getMap()` as those names could be confusing?

**Comment by vietj** [comment]
I think that @pmlopes is right and this is what we want. If somebody wants raw value, `getList().stream()` can be called instead.

**Comment by vietj** [comment]
I think we can leave like this for now, documentation just need to precise the contract

**Comment by ashertarno** [comment]
it seems somehow inconsistent. so let's say i use getList() to get the unwrapped types, but then i have a JsonArray of JsonObjects and  i am starting to get LinkedHashMaps instead of JsonObjects?
