### ISSUE TITLE
TracingOptions handled differently in VertxOptions

### ISSUE THREAD

**Issue by kenfinnigan** [eclipse-vertx/vert.x#3875]
### Version

4.0.3

### Context

Reviewing Tracing SPI and usage I encountered a discrepancy between how `MetricsOptions` and `TracingOptions` are handled within `VertxOptions`.

`TracingOptions` is not initialized with a new instance on creation, see https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/VertxOptions.java#L123, but `MetricsOptions` is.

Also, `TracingOptions` is not present in `toString()`, see https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/VertxOptions.java#L642

### Do you have a reproducer?

No

### Extra

Happy to contribute a PR to fix, but want to make sure there aren't reasons for the differences?

**Comment by vietj** [comment]
yes this is expected to be this way because both are different.

we can fix the missing to string issue in VertxOptions

**Comment by vietj** [comment]
in `TracingOptions` we decided to have the presence/absence configure whether tracing is enabled/disabled. MetricsOptions have instead to use a boolean for this. MetricsOptions were not changed to be like TracingOptions mainly for backward compatibility reason.

**Comment by kenfinnigan** [comment]
Thanks for the explanation @vietj.

I was in the middle of doing a PR for this so I can add some javadoc around a null `TracingOptions` meaning it's disabled.

Given what you say, would I be correct in stating that https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/spi/VertxTracerFactory.java#L38 should never occur because a factory wouldn't be instantiated if it was null?

Also, should https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/impl/VertxBuilder.java#L262 be checking for the enabled state as well is it not being null?

**Comment by vietj** [comment]
@kenfinnigan it can be assumed but you to check that tests will pass in this project and in _vertx-tracing_ project

**Comment by vietj** [comment]
for the later (metrics options), I believe the user could still set a null options on the VertxOptions and that would prevent this case

**Comment by kenfinnigan** [comment]
@vietj Would you like a change, if it works, to remove the default code from the factory in the PR I've already created, or a separate one?

**Comment by vietj** [comment]
yes if it works ,  then it's better if it's simpler, and it seems fine in this PR

**Comment by kenfinnigan** [comment]
Just verified all passes in "core" and "tracing", so I updated the PR
