### ISSUE TITLE
Bug: Header names must be case insensitive

### ISSUE THREAD

**Issue by leolux** [eclipse-vertx/vert.x#3880]
Regarding https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive HTTP header names are not case sensitive. The current behaviour of vert.x is that the header name is not found if there is a "difference in the case". 

The issue affects this code (already tested the issue)::
https://github.com/eclipse-vertx/vert.x/blob/2dcbfac237aed48dd0d4dbeb58372be0ad59c4eb/src/main/java/io/vertx/core/http/HttpServerRequest.java#L144

**Comment by vietj** [comment]
do you have a reproducer ?

**Comment by vietj** [comment]
I ran this with master:

```java
  public static void main(String[] args) {
    Vertx vertx = Vertx.vertx();
    vertx.createHttpServer().requestHandler(req -> {
      System.out.println(req.getHeader("User-Agent"));
      System.out.println(req.getHeader("user-agent"));
      req.response().end();
    }).listen(8080, "localhost");
  }
}
```

it happily printed twice the same value with cURL.

**Comment by leolux** [comment]
No, but I guess it has been fixed in the meantime. I face the issue on version 3.9.0
