### ISSUE TITLE
NetServer and NetClient Communication too slow

### ISSUE THREAD

**Issue by BdmRt** [eclipse-vertx/vert.x#3881]
Hello,

I’ve build a simple Projekt with vertx for testing NetClient/NetServer Projekt to Test the Performance and the duration. It’s on my pc so on localhost. Sending and receiving takes 50-100ms, that way too slow and I don’t think this should be the case. I could not find any hint why this is the case. Example code below. 

`
public class NetServerTest extends AbstractVerticle {

    private NetServerOptions options = new NetServerOptions().setReceiveBufferSize(10000000).setSendBufferSize(1000000)
            .setTcpKeepAlive(true).setIdleTimeout(600);
    private NetServer server;

    public static void main(String[] args) throws IOException {
        Vertx.vertx().deployVerticle(new NetServerTest());
    }

    @Override
    public void start() {
        server = vertx.createNetServer(options);
        startServerSocket();
    }

    private void startServerSocket() {
        server.connectHandler(socket -> {

            socket.write(Buffer.buffer(System.currentTimeMillis() + ""));

            socket.closeHandler(v -> {
                System.out.println("The client socket has been closed");
            });

        });

        server.listen(5555, "0.0.0.0", res ->

        {
            if (res.succeeded()) {
                System.out.println("Server is now listening!");
            } else {
                System.out.println("Failed to bind!");
            }
        });
    }
}

public class NetClientTest extends AbstractVerticle {

    private static NetClientOptions options = new NetClientOptions().setConnectTimeout(10000)
            .setReconnectAttempts(Integer.MAX_VALUE).setReconnectInterval(10000).setReceiveBufferSize(1000000)
            .setSendBufferSize(10000000).setTcpKeepAlive(true).setIdleTimeout(600);

    public static void main(String[] args) throws UnknownHostException, IOException {
        Vertx.vertx().deployVerticle(new NetClientTest());
    }

    private NetClient client;

    @Override
    public void start() {
        client = vertx.createNetClient(options);

        connectClient();
    }

    private void connectClient() {
        client.connect(5555, "localhost", res -> {
            if (res.succeeded()) {
                NetSocket socket = res.result();

                socket.handler(inputBuffer -> {
                    System.out.println(
                            "took " + (System.currentTimeMillis() - Long.parseLong(inputBuffer.toString())) + "ms");
                });

                socket.closeHandler(v -> {
                    System.out.println("The server socket has been closed. Trying to connect again.");
                });

            } else {
                System.out.println("Failed to connect. Trying to connect again." + res.cause());
            }
        });
        System.out.println("connectClient end");
    }
}
`

**Comment by vietj** [comment]
you need to warm up the TCP socket and send lot of data to improve the response time.

you should read about TCP receive window size and slow start that affect performance: https://hpbn.co/building-blocks-of-tcp/
