### ISSUE TITLE
Expose cluster manager from Vert.x instance

### ISSUE THREAD

**Issue by lecogiteur** [eclipse-vertx/vert.x#3885]
#### Describe the feature

Expose the cluster manager instance from Vert.x Instance. Today, we must cast Vertx with VertxImpl in order to access to the cluster manager instance.

#### Use cases

- Avoid to pass multiple parameters in method signature
- When the cluster manager is created and configured by external file and system properties, there is no way to retrieve instance

#### Contribution

I'm volunteering for implementing this feature

**Comment by vietj** [comment]
You can access it with `VertxInternal` instead of `VertxImpl` which I think is ok.

**Comment by lecogiteur** [comment]
> You can access it with `VertxInternal` instead of `VertxImpl` which I think is ok.

Thanks, I will do.
