### ISSUE TITLE
AsyncFile: allow access to file size

### ISSUE THREAD

**Issue by FroMage** [eclipse-vertx/vert.x#3892]
In https://github.com/quarkusio/quarkus/pull/16286 we realised that `AsyncFile` does not provide access to the file count, so if we're using it to pump bytes into a response we can't set the `Content-Length` header. We can't trust the `getReadLength()` method as it defaults to `Long.MAX_SIZE` if not set, and does not reflect the file size. We also can't access the file size by asking the file system, since we have no access to the file path.

Could we get access to the file size, or if not, at least to the path?

**Comment by tsegismont** [comment]
It should be possible to expose the file length. `AsyncFileImpl` can get it from the underlying `AsynchronousFileChannel`.

**Comment by FroMage** [comment]
That would be very nice.

**Comment by FroMage** [comment]
Thanks!
