### ISSUE TITLE
HttpServer.exceptionHandler lacks basic information about attempted connection

### ISSUE THREAD

**Issue by TorRanfelt** [eclipse-vertx/vert.x#3895]
#### Describe the feature

When an exception is thrown before a connection is established you can react to it by setting a HttpServer.exceptionHandler. Here it would be nice to be able to get the IP on the other end so it can be included in the log.

#### Use cases

Nice to have IP information about a DOS attack.

#### Contribution

It's a suggestion.

**Comment by vietj** [comment]
Usually such exception is an SSL handshake error and it will not contain the IP I think. Can you exhibit a practical case that I'm not thinking of that would work ?

**Comment by TorRanfelt** [comment]
I did not know that an IP would not be available from the underlying library in case of a SSL handshake error. - Seems strange to me since the operating system must know which IP:PORT it is communicating with.

**Comment by vietj** [comment]
actually I said a mistake, sorry :-)

**Comment by vietj** [comment]
what I said is that the error rerpoted by netty will not contain the IP and we would need specific integration for this to transform the ssl handshake error and try to get the IP from the same channel.

**Comment by TorRanfelt** [comment]
@vietj That's fair. It's no different than when I suggested SameSite-cookie support which was added when Netty supported it.

Of course, it is not nearly as likely this will ever be supported by Netty, but if that happens it would be great if vertx passed the information on.
