### ISSUE TITLE
Issues with FileUpload 

### ISSUE THREAD

**Issue by vishu184** [eclipse-vertx/vert.x#3896]
### Version

Which version(s) did you encounter this bug ?
4.0.3

### Context

 i am uploading file through any library or package (RestTemplate , okHttp or any other ) i am getting different size of file than actual file size .
```
FileUpload file = ctx.fileUploads().iterator().next();
file.size() = 2* actual file size (nearly)

byte a[] = vertx.fileSystem().readFileBlocking(file.uploadedFileName()).getBytes();
a.length = actual file size 

```

```
Map<String, Object> headers = new HashMap<>();
		headers.put(S3Constants.CONTENT_LENGTH, file.size());

producerTemplate.sendBodyAndHeaders("direct:syncUploadToS3",vertx.fileSystem().readFileBlocking(file.uploadedFileName()).getBytes(), headers);
	
```
 whenever i tried to upload file from any of the resttemplate or any module i am getting this behavior.

			
com.amazonaws.SdkClientException: Data read has a different length than the expected: dataLength=116460; expectedLength=180846; includeSkipped=false; in.getClass()=class com.amazonaws.internal.ReleasableInputStream; markedSupported=true; marked=0; resetSinceLastMarked=false; markCount=1; resetCount=0

Whenever i tried with postman or curl behaviour is fine.

**Comment by vietj** [comment]
please, can you move this issue to vertx-web ?
