### ISSUE TITLE
Log (LoggerHandlerImpl) gets swallowed if client closes connection.

### ISSUE THREAD

**Issue by javadevmtl** [eclipse-vertx/vert.x#3902]
### Version

3.9.x

### Context

Log is not logged

### Do you have a reproducer?

No.

### Steps to reproduce

This is coming from conversation here: https://groups.google.com/g/vertx/c/CZaPXYk2MA0

Add LoggerHandlerImpl to your route as early as possible. Make sure immediate is false, so that the log gets loged at the end of the request to ensure that `context.addBodyEndHandler(v -> log(context, timestamp, remoteClient, version, method, uri));` is used.

Have client connect and drop close the connection before response is returned.

**Comment by pmlopes** [comment]
This is a bug. The right callback should be:

```java
ctx.addEndHandler()
```

As this one is executed regardless if the request succeeds or not like in the described case.

**Comment by vietj** [comment]
can you reopen this issue in vertx-web ?

**Comment by javadevmtl** [comment]
Done and for reference purposes: https://github.com/vert-x3/vertx-web/issues/1935
