### ISSUE TITLE
HttpServer exceptionhandler error

### ISSUE THREAD

**Issue by sunqb** [eclipse-vertx/vert.x#3905]
### Questions

when i deploy an httpserver like this:
`
HttpServer server = vertx.createHttpServer();
server.requestHandler(router).listen(80),result ->{}).exceptionHandler(hr ->{});
`
it sometimes give an error like this:
`
16:01:44.158 [vert.x-acceptor-thread-0] WARN  i.n.util.concurrent.DefaultPromise - An exception was thrown by io.vertx.core.net.impl.TCPServerBase$$Lambda$103/478839936.operationComplete()
java.lang.IllegalStateException: null
`

### Version

vertx-core-4.0.3

### Context

I encountered an exception which looks suspicious while ...

### Do you have a reproducer?

step 1：Add breakpoint at IllegalStateException line 44 
step 2：Add breakpoint at CloseHooks line 82
step 3：start application

![image](https://user-images.githubusercontent.com/5319644/116519841-87e7a280-a904-11eb-95b7-fc9c30f5a25a.png)
![image](https://user-images.githubusercontent.com/5319644/116519881-959d2800-a904-11eb-972a-5b9882135926.png)

### Extra
when i remove exceptionHandler,the error is gone,like this
`
 HttpServer server = vertx.createHttpServer();
 server.requestHandler(router).listen(Integer.parseInt(config().getString("web.http.port")),result ->{});
`

and How did I find this problem？i deploy it in Linux ，the server cannot start，so i find this problem。but in my computer , i must Add breakpoint to reproducer this problem.

**Comment by sunqb** [comment]
i tracked the code,and i find it was because exceptionhandler return an exception :
![image](https://user-images.githubusercontent.com/5319644/116528574-920e9e80-a90e-11eb-8fc8-eef41dc52dc9.png)

but,sometimes it works with no error，although it return an exception。

**Comment by baichangda** [comment]
@sunqb 
i think you should do like this、because exceptionHandler() must be call after listen() finished
in your code、sometimes  exceptionHandler() will be excute before listen
![image](https://user-images.githubusercontent.com/24662536/127281254-0496d7e5-f3bd-4462-bf0b-721012afefba.png)

**Comment by sunqb** [comment]
so i think it is not a good design，there are some problems with the framework

> @sunqb
> i think you should do like this、because exceptionHandler() must be call after listen() finished
> in your code、sometimes exceptionHandler() will be excute before listen
> ![image](https://user-images.githubusercontent.com/24662536/127281254-0496d7e5-f3bd-4462-bf0b-721012afefba.png)

**Comment by vietj** [comment]
you should call .exceptionHandler(hr ->{}) before listen in your code

**Comment by vietj** [comment]
i.e it hsould be:

```java
HttpServer server = vertx.createHttpServer(); server.requestHandler(router).exceptionHandler(hr ->{}).listen(80),result ->{});
```

**Comment by sunqb** [comment]
> i.e it hsould be:
> 
> ```java
> HttpServer server = vertx.createHttpServer();
> server.requestHandler(router).exceptionHandler(hr ->{}).listen(80),result ->{});
> ```

ok thanks!

**Comment by sunqb** [comment]
@vietj In order to avoid this problem, I think it should be limited at the framework level, but i have no idea
