### ISSUE TITLE
Add cookie maxAge getter

### ISSUE THREAD

**Issue by fbuetler** [eclipse-vertx/vert.x#3906]
#### Describe the feature

The [Cookie Interface](https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/http/Cookie.java) should have a method to access the maxAge property of a cookie. Right now, one can only set the max age of a cookie. but not read it.

#### Use cases

Give complete access to the wrapped [netty default cookie](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/DefaultCookie.java). This is the only attribute one cannot read/write.

We would use this feature in a http proxy, where only a session cookie should be sent to the user agent and all other cookies from proxied requests/responses are stored in the proxy. To comply with [RFC6265](https://tools.ietf.org/html/rfc6265#section-5.2), we have to remove cookies from the storage when the maxAge is set to 0.

#### Contribution

I'd volunteer to implement this feature.

#### Implementation suggestion
* add method `getMaxAge()` to `Cookie` interface
* implement method `getMagAge()` in `CookieImpl` class

**Comment by fbuetler** [comment]
If this feature request is accepted/approved, I am going to start implementing it.

**Comment by vietj** [comment]
@fbuetler you can go ahead and contribute this enhancement
