### ISSUE TITLE
Wrong implementation of how to identify cookies

### ISSUE THREAD

**Issue by fbuetler** [eclipse-vertx/vert.x#3916]
### Version

Version: 4.0.3

### Context

[RFC 6265 HTTP State Management Mechanism, 5.3 Storage Model, Step 11](https://datatracker.ietf.org/doc/html/rfc6265#section-5.3) defines the tuple (name, domain, path) as the cookie identifier. 
However, the implementation of [Http1xServerResponse](https://github.com/eclipse-vertx/vert.x/blob/4.0.3/src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java#L787) and [Http2ServerResponse](https://github.com/eclipse-vertx/vert.x/blob/4.0.3/src/main/java/io/vertx/core/http/impl/Http2ServerResponse.java#L716) use only the cookie name as identifier.

### Steps to reproduce

1. Set two cookies with the same name but different path in a response header with
```java
public void handle(RoutingContext ctx) {
  Cookie cookie = Cookie.cookie("SOME_NAME", "foo").setPath("/");
  Cookie sameCookieWithDifferentPath = Cookie.cookie("SOME_NAME", "bar").setPath("/somePath");

  ctx.response().addCookie(cookie);
  ctx.response().addCookie(sameCookieWithDifferentPath);
  ctx.response().end();
}
```
2. Expect 2 cookies on the client, but only get 1.

**Comment by vietj** [comment]
assigned to you @pmlopes

**Comment by pmlopes** [comment]
This one is tricky to solve. Given that the uniqueness should be the tuple (name + domain + path) and the public API exposes just a simple `Map`, we either need to break and change it to be a `MultiMap` or define a well-known format for looking up cookies. 

Say that we define that the key in the map is the string `NAME/PATH` which is trivial to split as the path begins on the first `/`, it makes the lookup and removal more expensive as we need to consider using a `TreeMap` and perform `subMap(key, key + Character.MAX_VALUE)` to create a view filtering the prefix, and then we still need to decide how to handle more than 1 entry.

**Comment by fbuetler** [comment]
I would rather not do some string magic to create a key. Simply, because these values may already contains the meta character we would use.

I would rather:
* Create a `Tuple` object, wrapping name, domain and path, that we would use as a key i.e. `Map<Tuple, ServerCookie>`.  `Tuple` would be a new class implementing the `Comparable` interface, overwriting the `equals` method and maybe the `hashCode` method.
* Create a map of maps of maps i.e. `Map<String, Map<String, Map<String, ServerCookie>>>`. A cookie retrieval would then look like `ServerCookie cookie = cookies().get(name).get(domain).get(path)` (of course with some careful checks in between when there is no such value). Actually [guava](https://github.com/google/guava/wiki/NewCollectionTypesExplained#table) does provide this functionality.

However, I don't think we can circumvent breaking the public API.

_Addendum:_
For the sake of talking about the same topic, I consider the following as the public API regarding cookies:

[HttpClientResponse.java](https://github.com/eclipse-vertx/vert.x/blob/4.0.3/src/main/java/io/vertx/core/http/HttpClientResponse.java)
```java
  /**
   * @return the Set-Cookie headers (including trailers)
   */
  @CacheReturn
  List<String> cookies();
```

[HttpServerRequest.java](https://github.com/eclipse-vertx/vert.x/blob/4.0.3/src/main/java/io/vertx/core/http/HttpServerRequest.java)
```java
  /**
   * Get the cookie with the specified name.
   *
   * @param name  the cookie name
   * @return the cookie
   */
  default @Nullable Cookie getCookie(String name) {
    return cookieMap().get(name);
  }

  /**
   * @return the number of cookieMap.
   */
  default int cookieCount() {
    return cookieMap().size();
  }

  /**
   * @return a map of all the cookies.
   */
  Map<String, Cookie> cookieMap();
```

[HttpServerResponse.java](https://github.com/eclipse-vertx/vert.x/blob/4.0.3/src/main/java/io/vertx/core/http/HttpServerResponse.java)
```java
  /**
   * Add a cookie. This will be sent back to the client in the response.
   *
   * @param cookie  the cookie
   * @return a reference to this, so the API can be used fluently
   */
  @Fluent
  HttpServerResponse addCookie(Cookie cookie);


  /**
   * Expire a cookie, notifying a User Agent to remove it from its cookie jar.
   *
   * @param name  the name of the cookie
   * @return the cookie, if it existed, or null
   */
  default @Nullable Cookie removeCookie(String name) {
    return removeCookie(name, true);
  }

  /**
   * Remove a cookie from the cookie set. If invalidate is true then it will expire a cookie, notifying a User Agent to
   * remove it from its cookie jar.
   *
   * @param name  the name of the cookie
   * @return the cookie, if it existed, or null
   */
  @Nullable Cookie removeCookie(String name, boolean invalidate);
```

**Comment by fbuetler** [comment]
Btw It would be nice to have the add/remove functionality that exists in `HttpServerResponse` in `HttpClientRequest` as well.

**Comment by pmlopes** [comment]
@fbuetler the concern here is to reduce the blast radius of the change. I do agree that a better structure would be a better fit, I am just brainstorming how we can achieve this with the last amount of breakage.

I believe that the current API works for the most general use case, the API follows the nodejs style of having a single map based on the cookie name.

However, I understand that this isn't flexible enough to comply with the official spec. Let's try to figure out a way where the breakage is the least.

If we keep the cookies internally in a `MultiMap` then we don't lose the overlap of cookie name, lookup and removal can still be complex as we need to perform the lookup internally.

If we keep the cookies in a `MultiMap` lookup by name is still trivial as all cookies with the same name are grouped into a single bucket, it only gets complex for your specific case where you need a helper that returns all cookies for a given name. e.g.: `List<Cookie> getAllCookies(String name)`.

And to avoid ambiguity in removal a `removeCookie(Cookie[, boolean])` method should be added to explicitly match, instead of removing all cookies that match the name.

**Comment by fbuetler** [comment]
Just to reiterate what you said, to ensure I understood everything correctly:

You propose to change the public API as follows (only the changes shown from the public API shown above):

HttpClientResponse.java

```java
// nothing to change here
```

HttpServerRequest.java

```java
  /**
   * Get all cookies with the specified name.
   *
   * @param name the cookie name
   * @return a list of cookies with the specified name
   */
  default @Nullable List<Cookie> getCookies(String name) {
    return cookieMultiMap().get(name);
  }

  /**
   * @return a multi map of all the cookies.
   */
  MultiMap<String, Cookie> cookieMultiMap();
```

HttpServerResponse.java

```java
  /**
   * Expire all cookies with the specified name, notifying a User Agent to remove them from its cookie jar.
   *
   * @param name  the name of the cookie
   * @return a list of removed cookies
   */
  default List<Cookie> removeCookie(String name) {
    return removeCookie(name, true);
  }

  /**
   * Remove all cookies with the specified name from the cookie set. If invalidate is true then it will expire all cookies, notifying a User Agent to
   * remove them from its cookie jar.
   *
   * @param name  the name of the cookie
   * @return a list of removed cookies
   */
  List<Cookie> removeCookie(String name, boolean invalidate);
  
  /**
   * Expire a cookie, notifying a User Agent to remove it from its cookie jar.
   *
   * @param cookie  the cookie
   * @return the cookie, if it existed, or null
   */
  default @Nullable Cookie removeCookie(Cookie cookie) {
    return removeCookie(cookie, true);
  }

  /**
   * Remove the cookie from the cookie set. If invalidate is true then it will expire the cookie, notifying a User Agent to
   * remove it from its cookie jar.
   *
   * @param cookie  the cookie
   * @return the cookie, if it existed, or null
   */
  @Nullable Cookie removeCookie(Cookie cookie, boolean invalidate);
```

The breaking change in the code would then only be the return type of some methods (i.e. `List<Cookie>` instead of `Cookie` and `MultiMap<String, Cookie>` instead of `Map<Cookie>`). 

Another breaking change would be the semantics of `removeCookie(name, invalidate)`.

**Comment by pmlopes** [comment]
I think we can reduce the break even further if we do:

**HttpServerRequest.java**

```java
// original API remains
@Nullable Cookie getCookie(String name);
int cookieCount()
Map<String, Cookie> cookieMap();

// new API
@Nullable List<Cookie> getCookies(String name);
MultiMap<String, Cookie> cookies();
```

This way no code will break for users upgrading to 4.1

**HttpServerResponse.java**

```java
// original API remains
@Fluent
HttpServerResponse addCookie(Cookie cookie);

// This one must go as we can't have override of returns in java
@Nullable Cookie removeCookie(String name);
@Nullable Cookie removeCookie(String name, boolean);

// extra API
List<Cookie> removeCookie(String name);
List<Cookie> removeCookie(String name, boolean);

@Nullable Cookie removeCookie(Cookie cookie);
@Nullable Cookie removeCookie(Cookie cookie, boolean);
```

**Comment by fbuetler** [comment]
Based on what would you then decide what cookie you need to return by `getCookie(String name)` in the original API? 

And also how would the Map returned by `cookieMap()` look like?

**Comment by pmlopes** [comment]
`getCookie()` would just return the 1st cookie matching the given name, so the behavior would be the same as before and the `cookieMap()` just hides the multimap by returning again only the 1st entry, so the behavior is again the same as before.

**Comment by fbuetler** [comment]
> getCookie() would just return the 1st cookie matching the given name, so the behavior would be the same as before and the cookieMap() just hides the multimap by returning again only the 1st entry, so the behavior is again the same as before.

This only holds when we use an implementation of `MultiMap` that preserves the ordering of values for a given key agreeing with the order in which the values were added (like `ArrayListMultimap`, `LinkedHashMultimap`, `LinkedListMultimap`). And we would need to return the last element to have the most recent one. Otherwise, some inconsistencies may appear:

```java
Cookie cookie = new Cookie("foo", "bar").setPath("/");
Cookie sameCookieWithDifferentValueAndPath = new Cookie("foo", "baz").setPath("/blub");

addCookie(cookie);
addCookie(sameCookieWithDifferentValue);

// the MutliMap would look like: "foo" -> [cookie, sameCookieWithDifferentValueAndPath]

System.out.println(getCookie("foo").encode());

// one with the old API would expect the output to be "{'foo': 'baz', 'path': '/blub'}"
// but it could return "{'foo': 'bar', 'path': '/'}", if the order is not respected.
```

Same applies to `cookieMap()`.

> Finally, the remove by String wipes the full matching list which again matches the old behavior and respects the contract of returning the list of matched cookies.

I agree with this one.

**Comment by fbuetler** [comment]
I may have made a mistake by mixing request and response methods in my argument above.

**Comment by pmlopes** [comment]
```java
// a simple multimap like this will preserve the insert order:
Map<String, List<Cookie>> map = new HashMap<>();
map.computeIfAbsent(l -> new ArrayList<Cookie>()).add(cookie);
```

also looking at the current implementation, in order to preserve the behavior instead of "first" element in the list we should return the "last":

```java
// CookieImpl
...
      Map<String, ServerCookie> cookies = new HashMap<>(nettyCookies.size());
      for (io.netty.handler.codec.http.cookie.Cookie cookie : nettyCookies) {
        ServerCookie ourCookie = new CookieImpl(cookie);
        cookies.put(ourCookie.getName(), ourCookie);
      }
```

**Comment by fbuetler** [comment]
Agreed in both points (code snippet about multimap and first vs last).

**Comment by pmlopes** [comment]
Having a second look we can avoid breaking at all by doing:

**HttpServerResponse.java**

```java
// original API

@Fluent
HttpServerResponse addCookie(Cookie cookie);
// This one should be deprecated
@Deprecated @Nullable Cookie removeCookie(String name);
@Deprecated @Nullable Cookie removeCookie(String name, boolean);

// new API

// note the plural naming here to avoid conflict with the deprecated one
// and better express the API intent as the return is now a list
List<Cookie> removeCookies(String name);
List<Cookie> removeCookies(String name, boolean);

// similar to the old API but given a Cooke to remove to explicitly remove a match, not any cookie
// whose name matches
@Nullable Cookie removeCookie(Cookie cookie);
@Nullable Cookie removeCookie(Cookie cookie, boolean);
```

This way we avoid any breaking at the API level with existing code and allow 3 releases to users to migrate to the new `removeCookie()` for the deprecated methods.

**Comment by pmlopes** [comment]
@vietj I think we have a good compromise here. We deprecate 2 methods, and introduce 6 new ones to handle all the extra cases as per RFC spec. WDYT?

**Comment by fbuetler** [comment]
actually shouldn't we move then to
```java
@Nullable boolean removeCookie(String name, String domain, String path);
```
as knowing the maxAge, secure, httpOnly attributes is quite hard.

**Comment by pmlopes** [comment]
Just to keep it all in sync:

```java
// original API

@Fluent
HttpServerResponse addCookie(Cookie cookie);
// This one should be deprecated
@Deprecated @Nullable Cookie removeCookie(String name);
@Deprecated @Nullable Cookie removeCookie(String name, boolean);

// new API

// note the plural naming here to avoid conflict with the deprecated one
// and better express the API intent as the return is now a list
List<Cookie> removeCookies(String name);
List<Cookie> removeCookies(String name, boolean);

// similar to the old API but given a Cooke to remove to explicitly remove a match, not any cookie
// whose name matches
@Nullable Cookie removeCookie(String name, String domain, String path);
@Nullable Cookie removeCookie(String name, String domain, String path, boolean invalidate);
```

Just updated the return from `boolean` to `Cookie` as we may want to work with the removed `Cookie` after removal, for example we use this during the `SessionHandler` to force a removal from the user agent.

**Comment by vietj** [comment]
I need to review this again and read the entire conversation

**Comment by vietj** [comment]
this looks good to me, I'm not sure we need to deprecate methods though as they still seem valid to me

**Comment by vietj** [comment]
this looks fine to me, however I think we don't need to deprecate `removeCookie(String name)` and instead just say that this will remove the first `Cookie` occurence and explain that this might not be correct in some situations and advocate to use the more precision implementation.

we could also overload `List<Cookies> cookies()` with `List<Cookies> cookies(String name)`
