### ISSUE TITLE
about future tryComplete

### ISSUE THREAD

**Issue by wang007** [eclipse-vertx/vert.x#3923]
### Questions

When complete error is regarded as a normal result, the Listener's complete result is inconsistent

### Version

current(4.0.3)

### Do you have a reproducer?

```
    public static void main(String[] args) {

        Promise<Object> promise = Promise.promise();
        promise.future()
                .onSuccess(v -> {
                    System.out.println("1.succeeded ");
                })
                .onFailure(v -> {
                    System.out.println("1.failed");
                });
        promise.complete(new RuntimeException());

        promise.future()
                .onSuccess(v -> {
                    System.out.println("2.succeeded ");
                })
                .onFailure(v -> {
                    System.out.println("2.failed ");
                });
    }
```

#### result
```
1.succeeded 
2.failed 
```

#### expect
```
1.succeeded 
2. succeeded
```

**Comment by vietj** [comment]
promise should not be completed with failures :-)

I think we can fix that but differently, it needs to be studied

**Comment by wang007** [comment]
but failures serve as successful result in complete method

**Comment by vietj** [comment]
yes I understand, so we'll figure out something that does not need to instantiate an object

**Comment by vietj** [comment]
actually this looks like the most reasonable fix for the moment

**Comment by wang007** [comment]
yes，the idea from netty
