### ISSUE TITLE
Please enhance JksOptions to support selection of SSL key in keystore using an alias property

### ISSUE THREAD

**Issue by peterwalkley** [eclipse-vertx/vert.x#3926]
For context, I asked this question originally for Quarkus (see:  https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Any.20way.20to.20specify.20SSL.20key.20alias.20when.20using.20a.20keystore.20.3F ) and was asked to raise an issue for a Vert.x change.

There is currently no way to choose the SSL key alias for cases where a java key store may contain more than one key, thus no way to ensure the correct key is used when presenting the server certificate for SSL.

**Comment by sberyozkin** [comment]
Hi @vietj @pmlopes - I can see KeyStoreHelper iterating over aliases so may be `KeyStoreOptions` can get an `alias` property added ? 
CC @cescoffier, thanks

**Comment by sberyozkin** [comment]
Thanks @tsegismont, @vietj

**Comment by tsegismont** [comment]
You're welcome
