### ISSUE TITLE
Add ability to enable/disable compression on a per request basis

### ISSUE THREAD

**Issue by stuartwdouglas** [eclipse-vertx/vert.x#3928]
#### Describe the feature

At the moment you can enable compression for HTTP responses, however this will compress every response. This means that responses that are already compressed such as images or videos will be doubly compressed, wasting lots of CPU cycles.

#### Use cases

This will allow end users to control which responses are compressed.

I propose that when compression is enabled we use a virtual header: X-Vertx-Disable-Compression. We can override `beginEncode` in `HttpChunkContentCompressor, and if this header is present remove it and disable compression.

#### Contribution

I can do it if you are ok, with the implementation. I don't particularly like the suggestion however I don't really see any other way to pass this info to Netty.

**Comment by vietj** [comment]
looks like a good idea

**Comment by vietj** [comment]
however this seems redundant with the use of `content-encoding` set to `identity` that allow to achieve the same

**Comment by vietj** [comment]
if you set this header on a response then netty will not compress the response

**Comment by stuartwdouglas** [comment]
Yea, but it still sends that header to the client, which is not super efficient. I wonder if we can remove the header from the response after netty has dealt with it.

**Comment by vietj** [comment]
I will try to override the compressor to do that.

**Comment by vietj** [comment]
it seems that we can override beginResponse and do something like:

```java
  protected Result beginEncode(HttpResponse httpResponse, String acceptEncoding) throws Exception {
    Result result = super.beginEncode(httpResponse, acceptEncoding);
    if (result == null && httpResponse.headers().contains(HttpHeaderNames.CONTENT_ENCODING, "identity", true)) {
      httpResponse.headers().remove(HttpHeaderNames.CONTENT_ENCODING);
    }
    return result;
  }
```

**Comment by vietj** [comment]
https://github.com/eclipse-vertx/vert.x/tree/compressor-sanitizes-identity-content-encoding

**Comment by stuartwdouglas** [comment]
Awesome, LGTM.
