### ISSUE TITLE
Make some function in command launcher is extendable

### ISSUE THREAD

**Issue by zero88** [eclipse-vertx/vert.x#3941]
#### Use cases

To extend configuration and CLI option in `BareCommand` and `RunCommand` without rewrite too much code, then I'd like to make some function is more flexible and able to extend in sub class.

https://github.com/eclipse-vertx/vert.x/blob/2f690d7d6420c3601b0d62eeb574cae6dc6b3426/src/main/java/io/vertx/core/impl/launcher/commands/BareCommand.java#L202-L214

https://github.com/eclipse-vertx/vert.x/blob/24c4e2ad5af83aa830054e4c88d2881b3e822f92/src/main/java/io/vertx/core/impl/launcher/commands/RunCommand.java#L346-L399

Also, configuration must be processed in nature order as almost the common CLI:
- From config file
- From system properties
- From environment variable (it can be switch between `system properties`, but Vert.x in default doesn't provide this option)
- From CLI option

#### Example

If I want to add some CLI option like `cluster-conf` in `BareCommand` and make it works, I have to override method `startVertx`.
https://github.com/eclipse-vertx/vert.x/blob/2f690d7d6420c3601b0d62eeb574cae6dc6b3426/src/main/java/io/vertx/core/impl/launcher/commands/BareCommand.java#L201

It is too long for implementation and if vertx changed any line this method, I will have to update over and over.
I can do a trick to update VertxOptions in `beforeStartingVertx` method but it is not nice when split build configuration in several places.
Also, if I want to do `configureFromSystemProperties`, I need to rewrite also, due to "private lock"
 https://github.com/eclipse-vertx/vert.x/blob/949d129c84462b880479a64f504402d1ebc52ef3/src/main/java/io/vertx/core/impl/launcher/commands/BareCommand.java#L351

Then I provide a set of methods to easy `buildVertxOptions` in sub class, and users can decide which part they want to override: 

```
protected VertxOptions buildVertxOptions() {
    JsonObject optionsJson = getJsonFromFileOrString(vertxOptions, "options");
    VertxOptions vertxOptions = optionsJson == null ? new VertxOptions() : new VertxOptions(optionsJson);
    configureFromSystemProperties(vertxOptions);
    // configureFromEnv(vertxOptions);
    overrideFromCommandOption(vertxOptions);
    return vertxOptions;
  }
```

#### Contribution

I will open a PR

**Comment by zero88** [comment]
One "bug" in current implementation is make a call `beforeStartingVertx` before override all `VertxOptions` properties (only `EventBusOptions`), then in `Launcher` (or `VertxLifecycleHooks`) makes confusing to user like pass `hagroup = Vertx` in CLI option, but the received option in Hooks still `__DEFAULT__`.
I don't know if whether it is expectation, but IHMO, it is a bug.

**Comment by zero88** [comment]
> One "bug" in current implementation is make a call `beforeStartingVertx` before override all `VertxOptions` properties (only `EventBusOptions`), then in `Launcher` (or `VertxLifecycleHooks`) makes confusing to user like pass `hagroup = Vertx` in CLI option, but the received option in Hooks still `__DEFAULT__`.

Ah, I found why not override all `vertx options`, because it waits for lazy initializing SPI and override custom options depends on each SPI.
However, `vertx` just only do for `MetricsOptions`
https://github.com/eclipse-vertx/vert.x/blob/a1e4ca3ecaddc703c88cb7a807a05e957ea7eb7a/src/main/java/io/vertx/core/spi/VertxMetricsFactory.java#L31-L53

But similar options `TracingOptions`, it is not 
https://github.com/eclipse-vertx/vert.x/blob/b93ebfda83d2ee6e94ba1406f6754fdd0ec55974/src/main/java/io/vertx/core/spi/VertxTracerFactory.java#L24

So, this ticket is becoming big bigger :smile:

However, I still stick with my proposal:

> Nature order as almost the common CLI:
> - From config file
> - From system properties
> - From environment variable (it can be switch between system properties, but Vert.x in default doesn't provide this option)
> - From CLI option

And
> Before init `VertxBuilder` and pass `VertxOptions` into `beforeStartingVertx` hook, should collect all properties from every source.

@viej @tsegismont any thoughts?

**Comment by tsegismont** [comment]
@zero88 sorry for the late reply and thank you for explaining your use case.

I prefer not to take the changes for the following reasons:

- you can already provide eventbus options via the command-line, using the `-vertx-options` argument
- starting with Vert.x 4, we are de-emphasizing the CLI to focus on the embedded use-case
