### ISSUE TITLE
Register Jackson module automatically?

### ISSUE THREAD

**Issue by cpdyj** [eclipse-vertx/vert.x#3943]
#### Describe the feature

Can we use `ObjectMapper::findModules()` to register Jackson module automatically? (Instead of just `new ObjectMapper()`)

#### Use cases

Now the default jackson mapper `io.vertx.core.json.jackson.DatabindCodec.prettyMapper()` and `io.vertx.core.json.jackson.DatabindCodec.mapper()` without any module registered.
When we use `vertx-lang-kotlin`, the jackson kotlin module will be added, but we have to register manually.

#### Contribution

I can create a pr for it, if it's ok.

**Comment by vietj** [comment]
we could have in vertx-lang-kotlin a Vert.x 4 `VertxServiceProvider` that would do that

**Comment by vietj** [comment]
can you reopen this issue in vertx-lang-kotlin ?

**Comment by cpdyj** [comment]
> can you reopen this issue in vertx-lang-kotlin ?

Could you transfer the issue to another repository?

**Comment by vietj** [comment]
no I cannot because it is not the same github organization

**Comment by cpdyj** [comment]
Ok, wait a moment I will do this.

在 2021/5/25 15:31, Julien Viet 写道:
> no I cannot because it is not the same github organization
>
