### ISSUE TITLE
Regression VertX 4.1.0-SNAPSHOT - HttpClient - HTTP/2 TLS - client dead when server closes socket

### ISSUE THREAD

**Issue by DemonicTutor** [eclipse-vertx/vert.x#3951]
### Version

* 4.1.0-SNAPSHOT
* 4.1.0-CR2
* 4.1.0-CR1

### Context

Using VertX HttpClient to execute Http Requests via HTTP 2.
(HTTP without SSL is not affected)

### Do you have a reproducer?

* https://github.com/DemonicTutor/vertx-httpclient-410-regression

### Steps to reproduce

* HttpClient for HTTP/2
* execute first request against WireMock returning a Fault (throws exception as expected)
* execute second request against WireMock returning 200 OK **also throws Exception**

### Extra

* OpenJDK 16.0.1
* used RxJava-3 as dependency - but you can trust me it works with VertX 4.0.0 - i tried it :)

**Comment by DemonicTutor** [comment]
updated the reproducer to use Futures and removed the RxJava 3 dep

**Comment by DemonicTutor** [comment]
@jo5ef just found out it is specifically HTTP2 + TLS that is affected.

* h1.1: green
* h2: green
* h1.1 + ssl: green
* h2 + ssl: red

also here is the code what WireMock is doing with Faults: [JettyFaultInector](https://github.com/tomakehurst/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/jetty9/JettyFaultInjector.java)

so in this case it is a:
`this.socket.close()`

**Comment by vietj** [comment]
this would indeed not happen with a clean HTTP/2 close that would send a go away frame to the client.

the abrupt socket close will remove on the vertx client the connection from the pool after the HTTP/2 stream are notified and therefore the client will reuse a closed connection from the pool. Although it is more a race issue than an actual defect, the pool should be notified of a closed connection as early as possible.

**Comment by DemonicTutor** [comment]
thanks a bunch for that fast response :)

just build it locally and my reproducer is green now!
