### ISSUE TITLE
Allow other types beyond String being used as key to store state in Context

### ISSUE THREAD

**Issue by Sanne** [eclipse-vertx/vert.x#3952]
#### Describe the feature

In class `io.vertx.core.Context` : methods `getLocal`, `putLocal`, `removeLocal` all require a key of type String.

Would be great to relax this requirement and accept any object types (Object?).

#### Use cases

We have to store a custom object with sub-scope identifiers as well; the current API is forcing us to encode additional scope as post-fixes on a shared root String, but this implies we have to allocate new String instances on each access.

Being able to use a composite object would still require allocation, but encoding of parts of scoping would be really cheap. Not leat, String comparison isn't very efficient when we have to use a shared prefix.

#### Contribution

I'm happy to contribute, if I can be guided towards which solutions are acceptable. It seems it might just be a matter of changing the signature on the API, but I'm not sure of the implications or additional requirements. For example, is this state supposed to be serializable?

**Comment by vietj** [comment]
@Sanne you can cast Context to ContextInternal and use

```java

  /**
   * @return the {@link ConcurrentMap} used to store context data
   * @see Context#get(String)
   * @see Context#put(String, Object)
   */
  ConcurrentMap<Object, Object> contextData();

  /**
   * @return the {@link ConcurrentMap} used to store local context data
   */
  ConcurrentMap<Object, Object> localContextData();
```

directly, I think it works well and it allows us to not change the signature of get/put methods in Vert.x 4.1, we might consider using Object in 4.2 that would break binary compatibility but would not be a breaking change

**Comment by Sanne** [comment]
yes that seems fine - especially if there's reasonable hope for this to be public API in the future.

And no rush! For context, this is only a performance issue in case people are using multi-tenancy - and fairly minor.

Thanks for confirming this change is reasonable.
