### ISSUE TITLE
Duplicated context executeBlocking will always order task execution

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#3954]
The implementation of `DuplicatedContext#executeBlocking(Handler<Promise<T>> block, boolean ordered)` ignores the `ordered` value and always order blocking task execution.

**Comment by ashertarno** [comment]
@vietj @tsegismont Is there any approximate ETA for 4.1.1 release? just have to know when this fix will be available to do our internal planning. thanks.
