### ISSUE TITLE
Resource not found

### ISSUE THREAD

**Issue by richard20200101** [eclipse-vertx/vert.x#3958]
I'm developing a web application base on Vertx-v4.0.3，
It is normal when running in the development environment of Intelli idea, but after packaging it into a jar, it reports an error Resource not found. The following is my configuration and package detail

router.route("/web/*").handler(StaticHandler.create("webroot"));

![image](https://user-images.githubusercontent.com/61450147/120880128-ef2afd80-c5fa-11eb-8a8c-d8562f43d06f.png)

**Comment by tsegismont** [comment]
Duplicates vert-x3/vertx-web#1968
