### ISSUE TITLE
Local consumer gets distributed event if a non-local consumer with same address is present

### ISSUE THREAD

**Issue by blindpirate** [eclipse-vertx/vert.x#3959]
### Version

4.1.0

### Context

See https://github.com/blindpirate/local-consumer-bug for reproduction

In short, if a local consumer and non-local consumer with same address are registered, the local consumer also receives message from other Vertx cluster node.

### Steps to reproduce

This is reproducible with both ZK and Hazelcast cluster manager, so I think it's more likely to be a Vertx core issue.

- ZooKeeper:
  - Run `./gradlew installDist` to package the application.
  - Start ZooKeeper at `2181`, e.g. `docker run -d -p 2181:2181 zookeeper:3.6.2`
  - Run `PORT=8080 CONSUMER=1 app/build/install/app/bin/app` start the event consumer.
  - In another terminal, run `PORT=8081 app/build/install/app/bin/app` to start the event producer.
  - No message displayed in event consumer. This is expected because now only local consumer is registered.
  - Now kill the consumer and producer.
  - Run `PORT=8080 CONSUMER=1 ENABLE_DISTRIBUTED_CONSUMER=1 app/build/install/app/bin/app` start the event consumer.
  - In another terminal, run `PORT=8081 ENABLE_DISTRIBUTED_CONSUMER=1 app/build/install/app/bin/app` to start the event producer.
  - Now you can see the local consumer gets a message from distributed event bus.
- Hazelcast:
  - Run `./gradlew installDist` to package the application. 
  - Run `PORT=8080 CONSUMER=1 MANAGER=hazelcast app/build/install/app/bin/app` start the event consumer.
  - In another terminal, run `PORT=8081 MANAGER=hazelcast app/build/install/app/bin/app` to start the event producer.
  - No message displayed in event consumer. This is expected because now only local consumer is registered.
  - Now kill the consumer and producer.
  - Run `PORT=8080 CONSUMER=1 MANAGER=hazelcast ENABLE_DISTRIBUTED_CONSUMER=1 app/build/install/app/bin/app` start the event consumer.
  - In another terminal, run `PORT=8081 MANAGER=hazelcast ENABLE_DISTRIBUTED_CONSUMER=1 app/build/install/app/bin/app` to start the event producer.
  - Now you can see the local consumer gets a message from distributed event bus.

**Comment by tsegismont** [comment]
Thanks for reporting this @blindpirate !

@vietj actually this affects 3.9 too. I'll change the milestone to 3.9.8

**Comment by vietj** [comment]
actually no, we should keep 4.1.1 and then backport with a PR that
references this issue

**Comment by tsegismont** [comment]
Fine, will do that!

**Comment by vietj** [comment]
thanks!

**Comment by tsegismont** [comment]
Fixed in #4350
