### ISSUE TITLE
Introduce support for key password (not store password!) in KeyStoreOptions

### ISSUE THREAD

**Issue by famod** [eclipse-vertx/vert.x#3970]
#### Describe the feature

There is `io.vertx.core.net.KeyStoreOptions.setPassword(String)` for the store and `.setAlias(String)` to select a specific key from the store, but there is nothing to set the _password for a specific key_.

#3452 seems closely related.

#### Use cases

In "enterprisy setups"™, more often than not you have multipe key pairs in a single key store and each of it is protected by an individual password. In such cases, just having a keystore password is not sufficient.
FWIW: Spring and WildFly both have something like `key-password` in config.

Btw, something like `.setKeyPassword(String)` would make sense to me.
In that context, maybe `.setAlias(String)` should be renamed to `.setKeyAlias(String)` to make things clearer.
See also this discussion over at Quarkus: https://github.com/quarkusio/quarkus/pull/17884#issuecomment-860579222

**Comment by vietj** [comment]
`setAliasPassword` makes sense to me

**Comment by vietj** [comment]
does it do the same ?

in this case, when the alias is selected then only one entry is used and it
makes sense to have a single password instead of a map in your case

**Comment by pmlopes** [comment]
@vietj yes. in `auth` setting a single password it then unlocks the keystore and keys with the same password, when specific passwords are added for an alias then it unlocks the store with the top level password and the key with the password from the map falling back to the file password when missing.

**Comment by famod** [comment]
FWIW: while integrating this feature via https://github.com/quarkusio/quarkus/pull/18387 I realized that the name `aliasPassword` can be a bit misleading because you don't have to set an alias at all!
E.g. imagine a keystore with a single key that has another password than the store. In that case you don't need `alias` but you do need `aliasPassword`.
