### ISSUE TITLE
Make Serializer as Public or Module with (de)serializer

### ISSUE THREAD

**Issue by Fyro-Ing** [eclipse-vertx/vert.x#3972]
#### Describe the feature
Make serializer as public 

SerializationInclusion#Include.NON_NULL mus be set before register serializers, but with DatabindCodec, this not possible

To do that, we need to redefine serializers use on DatabindCodec because they aren't define as public  https://github.com/eclipse-vertx/vert.x/tree/master/src/main/java/io/vertx/core/json/jackson

Other better solution is to add a vertx jackson Module with serializers ?

#### Use cases
```
final ObjectMapper mapper = new ObjectMapper()
      .setSerializationInclusion(JsonInclude.Include.NON_NULL)

mapper.registerModule(vertxModule);
```

**Comment by vietj** [comment]
you can access the mapper with the public and static method `mapper()`

**Comment by Fyro-Ing** [comment]
you can't add "SerializationInclusion(JsonInclude.Include.NON_NULL)" after module registration

we need that with jsonObject serilaizer

**Comment by vietj** [comment]
I see, then I think that we should have a system property to activate it on bootstrap by vertx instead because this is statically loaded

**Comment by vietj** [comment]
what does this property do ?

**Comment by Fyro-Ing** [comment]
"setSerializationInclusion(JsonInclude.Include.NON_NULL)" ignore all null values


we use other capacities, like WRITE_ENUMS_USING_TO_STRING or READ_ENUMS_USING_TO_STRING


For test purpose, on a project from my company, i've initiate a factory similarly to JacksonFactory with a MapperCodec that extends JsonCodec and Constructor with ObjectMapper, initialize from Factory (MapperCodec is similar to DatabindCodec, but without static)

```
public MapperFactory implements io.vertx.core.spi.JsonFactory {
public static final MapperCodec CODEC;

          static {
            final ObjectMapper mapper = new ObjectMapper()
              .setSerializationInclusion(JsonInclude.Include.NON_NULL)
              .enable(feature) (enum as toString)
              .disable(feature)
              .registerModules(new JavatimeModule(), ...)

            // hack trick (add a VertxModule extends SimpleModule on a 'io.vertx.core.json.jackson' package, and add serializer on contructor)
            mapper.registerModule(new VertxModule)

            CODEC = new MapperCodec(mapper);
          }

          @Override
          public MapperCodec codec() {
            return CODEC;
          }

}
```

**Comment by Fyro-Ing** [comment]
any chance to have this feature ?

This is most important because we can load our Factory with **JsonFactory** but (De)Serializer are not accessible

**Comment by vietj** [comment]
why aren't vertx serializer not accessible ?

**Comment by Fyro-Ing** [comment]
Vertx serializer aren't public so we can't use like in DatabindCodec to add (de)serializer on our mapper, only accessible from same package


The best way is to have a vertx Module with all vertx (de)serializer to avoid "duplicating" same code like in DatabindCodec

**Comment by vietj** [comment]
can you provide a PR for this ?
