### ISSUE TITLE
Can not handle exception in thread "vert.x-eventloop-thread-*" io.vertx.core.impl.NoStackTraceThrowable: Redis waiting Queue is full

### ISSUE THREAD

**Issue by shenopkss** [eclipse-vertx/vert.x#3976]
### Questions

Can not handle exception in thread "vert.x-eventloop-thread-*" io.vertx.core.impl.NoStackTraceThrowable: Redis waiting Queue is full

### Version

kotlin("jvm") version "1.4.21"

### Context

The following is invalid：

1. router.route().failureHandler
2. vertx.exceptionHandler
3. redisConnection.exceptionHandler

Hope to get your help, thank you。

**Comment by pmlopes** [comment]
Hi, this issue should be raised in the redis client repo.

There's an important aspect to notice. If the waiting queue is full it means your redis server isn't coping with the load, so the client is failing requests to avoid a snow ball effect and DDoS your vertx server app.

You can increase the queue size in the client options if you believe this is just a spike in the load. But it it isn't,then the only fix is to upgrade the redis server machine.
