### ISSUE TITLE
Let VertxInternal#sharedTCPServers  allow other server to be used

### ISSUE THREAD

**Issue by wang007** [eclipse-vertx/vert.x#3977]
#### purpose
Write netty code directly in vert.x  Reuse both vert.x threading model and vert.x components

because 
```java
public <S extends TCPServerBase> Map<ServerID, S> sharedTCPServers(Class<S> type) {
    if (NetServerImpl.class.isAssignableFrom(type)) {
      return (Map<ServerID, S>) sharedNetServers;
    } else if (HttpServerImpl.class.isAssignableFrom(type)) {
      return (Map<ServerID, S>) sharedHttpServers;
    } else {
      throw new IllegalStateException();
    }
  }
```
So you can't do it
```java
public class DemoServer extends TCPServerBase {
  
  public DemoServer(VertxInternal vertx, NetServerOptions options) {
    super(vertx, options);
  }

  @Override
  public Future<Void> close() {
    return null;
  }
}
```

#### Describe the feature

VertxInternal#sharedTCPServers(Class type) implement allow other server class to be used

#### Use cases

```java
public class DemoServer extends TCPServerBase {
  
  public DemoServer(VertxInternal vertx, NetServerOptions options) {
    super(vertx, options);
  }

  @Override
  public Future<Void> close() {
    return null;
  }
}


public class SomeVerticle extends AbstractVerticle {
  @Override
  public void start() throws Exception {
    DemoServer server = DemoServer.create(vertx, options);
    // netty codec,decode, handle
   server.listen(port);
  }

```

#### Contribution
I can contribute this feature

**Comment by vietj** [comment]
sure thing but that would remain an internal class though

**Comment by vietj** [comment]
well actually why don't you simply wrap a NetServer ?

**Comment by wang007** [comment]
> well actually why don't you simply wrap a NetServer ?

because write netty code directly in vert.x.  Netty has a rich encoder/decoder library and reuse the Netty Codec directly.

Either way, is it convenient to allow TCPServerBase to be used by the Other Server Class

**Comment by vietj** [comment]
you can reuse Netty codecs with NetSocket :
http://www.julienviet.com/advanced-vertx-guide/

**Comment by wang007** [comment]
> ChannelPipeline pipeline = so.channelHandlerContext().pipeline();
> pipeline.addFirst(codec);

That seems to work.

Under the discussion of the China user group, Some of you are familiar with Netty and want to start with Raw Netty. But they want to reuse the ver's threading model and components. 

Therefore, it is a good way to write to the server from TCPServerBase

**Comment by vietj** [comment]
I will close this issue, I think you should share with people in China this document (or translate it) so they can use Netty on top of Vert.x directly.
