### ISSUE TITLE
add OAuth2Auth.logout(User)

### ISSUE THREAD

**Issue by rzorzorzo** [eclipse-vertx/vert.x#3984]
#### Describe the feature

OAuth2API provides a logout method. However this method, nor the api object,  are not accessible from OAuth2AuthHandler.
I think there is currently no way to logout a OAuth2 user, than invoking 

context.redirect(oauth2Provider.endSessionURL(user, params))

#### Use cases

        ((OAuth2AuthProviderImpl)oauth2).logout(user, res -> {
            if (res.succeeded()) {
            	context.redirect("/");
            } else {
              // the user might not have been logged out
              // to know why:
              System.err.println(res.cause());
              context.fail(500);
            }
		});

#### Contribution

I sugest adding the following implementation to OAuth2AuthProviderImpl

  public void logout(User user, Handler<AsyncResult<Void>> callback)
  {
	  api.logout(user.principal().getString("access_token"), user.principal().getString("refresh_token"), callback);
  }

**Comment by pmlopes** [comment]
This logout isn't correct. It was a keycloak specific feature that wasn't standard and that's why it isn't public in 4.0.
