### ISSUE TITLE
Vert.x should not load its classes in IsolatedClassLoader

### ISSUE THREAD

**Issue by thomas-melusyn** [eclipse-vertx/vert.x#3987]
From this conversation: https://groups.google.com/g/vertx/c/B0hylXEpgXQ

### Version

4.0.3 & 4.1

### Context

I encountered the below exception when deploying two different verticles at the same time
A parent verticle deploys two others using Maven Service Factory 
The exception occurs when trying to access any external dependency
```
java.lang.ClassCastException: io.vertx.ext.mongo.impl.MongoClientImpl$MongoHolder cannot be cast to io.vertx.ext.mongo.impl.MongoClientImpl$MongoHolder
```

### Do you have a reproducer?
[https://github.com/thomas-melusyn/vertx-examples](https://github.com/thomas-melusyn/vertx-examples)

### Steps to reproduce
```
cd maven-service-factory-examples
mvn clean install   // to run the test in MyDeployingVerticleTest
```

**Comment by tsegismont** [comment]
Looked into this and actually it is not a bug. If the parent project does not depend on Vert.x Mongo Client, each verticle will load Vert.x Mongo Client classes via its own isolated classloader.

It's not a problem if you do not create a Mongo shared client. But if you create a Mongo Shared Client, the shared instance is stored in a Vert.x shared data map. When the second verticle is deployed, it gets this instance which class was loaded from another classloader, hence the `ClassCastException`.

If you want a shared client, you must modify the `maven-service-factory-api` POM file to add:

```xml
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-mongo-client</artifactId>
      <version>${vertx.version}</version>
    </dependency>
```

**Comment by tsegismont** [comment]
n
