### ISSUE TITLE
H2C upgrade server initial settings might not be sent when compression is enabled

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#3988]
An HTTP server performing an H2C upgrade when compression is enabled might not send the HTTP/2 initial settings frame. The upgrade handler will correctly remove the compression deflater and the chunked write handler will only be removed later. When the H2 connection handler writes the initial settings frame, the frame remains buffered in the chunked write handler and is lost when the frame is removed. The chunked write handler should be removed along with the compression deflater before the connection is upgraded.

**Comment by pradithya** [comment]
Out of curiosity, any idea why it happen only for `blockingHandler` ?

**Comment by vietj** [comment]
it happens because the response is asynchronous (i.e using setTimer would
do the same) and the ChunkedWriteHandler has been removed when the response
is sent.

in case of synchronous response, the ChunkedWriteHandler has buffered the
settings frame and the response write will cause a flush that will emit the
buffered settings frame in the ChunkedWriteHandler

**Comment by pradithya** [comment]
Make sense, thanks for clarifying!
