### ISSUE TITLE
Able to change the DefaultFullHttpResponse & behavior of HTTP response (414 and others)

### ISSUE THREAD

**Issue by mdadil-dk** [eclipse-vertx/vert.x#3990]
#### Describe the feature

By default, if we have HTTP response and status `414 Request-URI Too Long`, There is no headers, and no body in the response apart from status `414 Request-URI Too Long`. 

Currently we do not have way to change the default response behavior, where one might want to add headers or response body.

#### Minimalist reproducer
[Code and Postman Collection for test](https://groups.google.com/g/vertx/c/Sg8gZ1EGIVo/m/cj3da9cxAgAJ)

#### Use cases
This will allow to change, have more control over the default behavior and to have specific headers like `Content-Type: application/json` and certain payload in these default responses.

Reference- [Group Discussion](https://groups.google.com/g/vertx/c/Sg8gZ1EGIVo)

**Comment by vietj** [comment]
See https://github.com/eclipse-vertx/vert.x/issues/3992
