### ISSUE TITLE
Two distinct HttpServer creations with port 0 yield the same random port (usually)

### ISSUE THREAD

**Issue by famod** [eclipse-vertx/vert.x#3994]
### Summary

Two individual calls to `vertx.createHttpServer(...)` with port 0 yield the same random port (usually, see note on race condition futher down).
In context of Quarkus, this is irritating for users because Quarkus will print something like:
```
Listening on: http://localhost:40695 and https://localhost:40695
```
Furthermore, something seems to break after a very special sequence of QuarkusTests (that I'm not allowed to share due to closed source) in Quarkus 2.0.0 which uses vert.x 4.1, but that doesn't happen with Quarkus 1.13.7 which uses vert.x 3.something.
See https://github.com/quarkusio/quarkus/issues/18154 for details.
This problem vanishes if I use a fixed port for https (my tests are using http anyway, not https).

While debugging/adding logging, I think I have also found a concurrency issue in [TCPServerBase](https://github.com/eclipse-vertx/vert.x/blob/11ab144725e551be591118831377101015e1392c/src/main/java/io/vertx/core/net/impl/TCPServerBase.java#L130-L157) that I have described here: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/.5B2.2E0.2E0.2ECR3.2B.5D.20.22The.20target.20server.20failed.20to.20respond.22/near/244163648

### Version

4.1.0 (in Quarkus 2.0.0)

### Context

See:
- https://github.com/quarkusio/quarkus/issues/18154
- https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/.5B2.2E0.2E0.2ECR3.2B.5D.20.22The.20target.20server.20failed.20to.20respond.22

### Do you have a reproducer?

See Quarkus based reproducer in https://github.com/quarkusio/quarkus/issues/18154

### Extra

-

**Comment by vietj** [comment]
amusingly this _feature_ was actually implemented for Quarkus by a Quarkus [developer](https://github.com/eclipse-vertx/vert.x/pull/3494) :-)

_In context of Quarkus, this is irritating for users because Quarkus_ : I believe this is your opinion, you cannot know what how users of Quarkus will react in reality.

your concurrency issue requires to be logged to read it, can you open a clear issue for it ?

**Comment by famod** [comment]
@stuartwdouglas given that you created #3494 a year ago, what's your take on having the same random port for https as for http?

I don't really mind closing this issue.

@vietj 
> believe this is your opinion, you cannot know what how users of Quarkus will react in reality.

Sure, but a colleague was surprised as well. 🤷 As I said above, I don't have a problem if we agree to leave it like that.

The only thing that bothers me is that `the target server failed to respond` error after a specific sequence of request which will be hard to reproduce.

> your concurrency issue requires to be logged to read it, can you open a clear issue for it ?

Will do on the weekend or so.

**Comment by stuartwdouglas** [comment]
I think this is definitely a bug, I think I should have added something to ServerID to differentiate between http and https apps.

**Comment by vietj** [comment]
this prevents a person to have two HTTP server in the same verticle, so we will revert this change to have the previous behavior, we will introduce a name on the server options and when this name is set then it will be used in the server ID whatsoever, so the current behavior will be available by setting a name on the options

**Comment by vietj** [comment]
as this is somewhat breaking (although I believe nobody is relying on it), this will be in 4.2.0

**Comment by famod** [comment]
FYI @cescoffier ⬆️

**Comment by vietj** [comment]
after discussing that, we might actually use a negative number to declare a random port and this number would be used as key for binding. Zero would work like before, so setting -1 would bind to the same random port.

**Comment by vietj** [comment]
see https://github.com/eclipse-vertx/vert.x/pull/3999

**Comment by famod** [comment]
@vietj IIUC, with this we could (in Quarkus) set the HttpServer http to e.g. 0 and the HttpServer for https to e.g. -1 to separate the two ports?

**Comment by famod** [comment]
Btw,
> your concurrency issue requires to be logged to read it, can you open a clear issue for it ?

I tried to do so here: #4024
Sorry for the delay.

**Comment by vietj** [comment]
this is the idea
