### ISSUE TITLE
restore support for creating (new) SqlClient from existing DataSource

### ISSUE THREAD

**Issue by klas3000** [eclipse-vertx/vert.x#3996]
### Version
4.1.1

### Context

Pls restore the functionality to: create an SqlClient from an existing DataSource (so that I can use the oracle ucp pool).

Previously (old sql api)
```
dataSource = oracle.ucp.jdbc.PoolDataSourceFactory.getPoolDataSource()
...
io.vertx.ext.jdbc.JDBCClient.create(vertx, dataSource)
```

but, it doesn't seem to exist in the new `io.vertx.jdbcclient`, `io.vertx.sqlclient` pkgs

pls, restore this feature so that I can stay modern.

### See also
https://groups.google.com/g/vertx/c/9soZ5G2kpRM

**Comment by vietj** [comment]
can you move this to the vertx-jdbc-client repository ?

**Comment by klas3000** [comment]
ok.
or, perhaps you mean "vertx-sql-client" repo?
since that is "the new" api, right?

**Comment by pmlopes** [comment]
@klas3000 no, it's really "vertx-jdbc-client" because it's where the jdbc implementation of "sql-client" lives.

It's confusing I know :)

**Comment by klas3000** [comment]
ok:)
and, newbie double-checking...
you said "move"...
but, only "open" issues can be moved, or?
so, I technically shall: create another, right?

**Comment by pmlopes** [comment]
yes, create a new one, because github doesn't have a move function.

**Comment by klas3000** [comment]
now here
https://github.com/vert-x3/vertx-jdbc-client/issues/228
