### ISSUE TITLE
Eventbus websocket registration - repeated registration of the same address via the same websocket causes memory leak

### ISSUE THREAD

**Issue by 3mek** [eclipse-vertx/vert.x#3997]
Eventbus websocket registration - repeated registration of the same address via the same websocket causes memory leak

### Version

Which version(s) did you encounter this bug ? 3.9.4, 4.0.2

### Context

I encountered an situation which looks suspicious when I was investigating problems with sockjs / eventbus intergation. Testing was done using jmeter / websocket.

### Do you have a reproducer?

yes - see below

### Steps to reproduce

1. Start vert.x with SockJs bridge
2. open web-socket (e.g using jmeter websocket plugin / WebSocket Open Connection)
3. register listener using this message (e.g. using jmeter Websocket Single Write Sampler): 
`["{\"type\":\"register\",\"address\":\"client.msg}\",\"headers\":{\"Accept\":\"application/json\"}}"]`
4. repeat step 3 (can be repeated multiple times)
5. close websocket (WebSocket Close) this will close one of the handlers
6. check memory - instances of classes  HandlerRegistration (3.9.4) / MessageConsumerImpl (4.0.2)
-> there is a leftover handler still registered to address as in step 3. This appears to be a bug / memory leak. 

### Extra
if metrics are enabled - this will be visible under vertx_eventbus_handlers (for micrometer)

**Comment by vietj** [comment]
can you provide a reproducer without sockjs ?

**Comment by vietj** [comment]
ping @3mek

**Comment by 3mek** [comment]
Sorry - I was sick and away for few days. Let me start with a question - is this really a bug / what is the expected behaviour? If this is a bug, problem is probably somewhere around (in 4.x) io.vertx.core.http.impl.WebSocketImplBase#registerHandler:
`
  void registerHandler(EventBus eventBus) {
    Handler<Message<Buffer>> binaryHandler = msg -> writeBinaryFrameInternal(msg.body());
    Handler<Message<String>> textHandler = msg -> writeTextFrameInternal(msg.body());
    binaryHandlerRegistration = eventBus.<Buffer>localConsumer(binaryHandlerID).handler(binaryHandler);
    textHandlerRegistration = eventBus.<String>localConsumer(textHandlerID).handler(textHandler);
  }`
so there is always new 'MessageConsumer' created in io.vertx.core.eventbus.impl.EventBusImpl#localConsumer(java.lang.String)

`
  @Override
  public <T> MessageConsumer<T> localConsumer(String address) {
    checkStarted();
    Objects.requireNonNull(address, "address");
    return new MessageConsumerImpl<>(vertx, vertx.getOrCreateContext(), this, address,  true);
  }
`
rather than adding handler to existing 'MessageConsumer'.
Since it is in 'WebSocketImplBase' I would assume I can only reproduce using sockjs... (but I might have misunderstood the question).

**Comment by 3mek** [comment]
Sorry for the delay. I was away from the keyboard. 
I think it is only sockjs-reproducible. I see creation of new 'MessageConsumer' in io.vertx.ext.web.handler.sockjs.impl.EventBusBridgeImpl#internalHandleRegister
`MessageConsumer<?> reg = eb.consumer(address).handler(handler); 
registrations.put(address, reg);
` ( in 4.x code)
put overwrites previous consumer in registrations map (but it is still referenced/registered as a handler).

**Comment by vietj** [comment]
yes I would like to know if that's an event bus issue or bridge issue

**Comment by 3mek** [comment]
So the problematic code is the one I mention - io.vertx.ext.web.handler.sockjs.impl.EventBusBridgeImpl (at least that what I think). The question is now what should be the correct behaviour? The eventbus js library we use will not allow duplicate 'ws' registration - it will add another listener on js side. 
Current code means those are never cleaned up (at least from memory), and we suspect those are even registered, so when you reconnect ws and make send() on the channel (as opposed to publish()) - messages going to those orphan handlers will never be delivered.

**Comment by vietj** [comment]
I think it is not normal behavior there should be some kind of handling for this case

**Comment by 3mek** [comment]
Why not just failing this? Same as max-handlers?
`  private boolean checkMaxHandlers(SockJSSocket sock, SockInfo info) {
    if (info.handlerCount < maxHandlersPerSocket) {
      return true;
    } else {
      LOG.warn("Refusing to register as max_handlers_per_socket reached already");
      replyError(sock, "max_handlers_reached");
      return false;
    }
  }`

**Comment by pmlopes** [comment]
@3mek can you verify with 4.1.1 and `master`? We improved the registration process in the previous release, perhaps the issue is already solved?

**Comment by 3mek** [comment]
I will, as soon I am back from holidays :)

**Comment by 3mek** [comment]
Just tested with vert.x 4.1.3 and it behaves the same.

**Comment by vietj** [comment]
can you provide a reproducer ?

**Comment by 3mek** [comment]
I tried to write a test class based on WebSocketTest. But so far I did not manage to ter client.webSocket to work with SockJSHandler. Are there any tests using SockJSHandler - I can't find any in vert.x. I just found EventbusBridgeTest in other repo, but I need to make a break for today.

**Comment by 3mek** [comment]
Reproducer:
https://github.com/3mek/vertx-reproducer-ws-bridge-leak
