### ISSUE TITLE
NetClient local connectTimeout support

### ISSUE THREAD

**Issue by coding4m** [eclipse-vertx/vert.x#4001]
#### Describe the feature

NetClient now use a global connectTimeout by NetClientOptions.
is that possible set a local connectTimeout when use NetClient.connect(xx) method ?

#### Use cases

so we can use a shared NetClient for tcp health check with difference upstream connect timeout.

**Comment by vietj** [comment]
I want at some point to introduce ConnectOptions for NetClient but not right now, can you try using a different NetClient for this purpose ?
