### ISSUE TITLE
MetricsOptions Enabled Doesn't Work with SysProps

### ISSUE THREAD

**Issue by al744** [eclipse-vertx/vert.x#4008]
### Version

4.0.3

### Context

`-Dvertx.metrics.options.enabled=true` does not seem to work anymore. It appears this might be related to #3804 / #3810 .
Changing the `BareCommand.java` code to move `builder.init();` to where it originally was

```
if (options.getMetricsOptions() != null) {
    configureFromSystemProperties(options.getMetricsOptions(), METRICS_OPTIONS_PROP_PREFIX);
}
builder.init();
```
while keeping `beforeStartingVertx(options);` in the current location appears to fix the issue.

### Do you have a reproducer?

Add to [LauncherTest#testCustomMetricsOptions()](https://github.com/eclipse-vertx/vert.x/blob/4.1/src/test/java/io/vertx/core/LauncherTest.java#L500) `assertTrue(launcher.getVertx().isMetricsEnabled());` and you will see that the assert fails. After moving the `builder.init()` back to the previous location, that assert will pass.

**Comment by vietj** [comment]
thanks, it seems indeed to fix the issue, I will apply it and back port to 4.1 branch
