### ISSUE TITLE
Close long running connection

### ISSUE THREAD

**Issue by himanshumps** [eclipse-vertx/vert.x#4009]
We have implemented k8s health checks(readiness and liveness) to ensure healthy containers. The problem I am facing is that when the liveness probe fails for 2 times, I want to close all the connected connections (some of them might be long running connections) before I can restart the containers. Is there any way I get get the list of all connected connections and close/terminate them. I am using vertx-web 4.x .

**Comment by vietj** [comment]
you need to maintain a structure with all open connections
