### ISSUE TITLE
a file download bug of static handler

### ISSUE THREAD

**Issue by sosilent** [eclipse-vertx/vert.x#4017]
### Questions

StaticHandler Bug!

### Version

4.1.0

### Context

My project is running on vert.x 4.1.0.
Some mp3 files need to be downloaded by url, /donwload/*.mp3, which is a static-handler router.

But the file downloaded by /downlaod/*.mp3 has a wrong file size and failed to read.
If rename the mp3 files as jpg，the client can get the right size files.

When i change vertx form 4.1.* to 3.9.*, all run good. 

### Do you have a reproducer?

https://github.com/WengYuehTing/StaticHandler-issue

### Steps to reproduce

1. mvn package
2. java -jar target/bas-ws-0.0.1-fat.jar
3. test:
   download the 2 files by url:
    127.0.0.1:8099/test.mp3
    127.0.0.1:8099/test.jpg

test.mp3 and test.jpg are the same files expcept names.

but client gets two different size files.

**Comment by pmlopes** [comment]
The issue is not per se related to static handler. I've rewrote the reproducer to:

```java
        HttpServerOptions serverOptions = new HttpServerOptions();
        serverOptions
                .setPort(8099);

        server = vertx.createHttpServer(serverOptions).requestHandler(req -> {
            req.response().sendFile("webroot/test.mp3");
        });
```

And the file download size gets bigger. I did open the downloaded file with a hex editor and the content seems to get changed, but I don't see any specific pattern, like extra nulls, or byte widening...

@vietj perhaps you could try to see what is happening with the mp3 file in core.

**Comment by vietj** [comment]
I'll have a look, it looks awkward

**Comment by vietj** [comment]
it seems that the send file is correct because the file sent are not correct as they are copied by Maven with some kind of transformation:

```
julien:webroot julien$ ls -la
julien:StaticHandler-issue julien$ ls -l target/classes/webroot/
total 200
-rw-r--r--  1 julien  staff  35779 Jul 19 15:16 test.jpg
-rw-r--r--  1 julien  staff  64192 Jul 19 15:16 test.mp3
```

If you modify the build to remove resource filtering then it is works as expected:

```xml
<resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
            </resource>
        </resources>
```

**Comment by sosilent** [comment]
> it seems that the send file is correct because the file sent are not correct as they are copied by Maven with some kind of transformation:
> 
> ```
> julien:webroot julien$ ls -la
> julien:StaticHandler-issue julien$ ls -l target/classes/webroot/
> total 200
> -rw-r--r--  1 julien  staff  35779 Jul 19 15:16 test.jpg
> -rw-r--r--  1 julien  staff  64192 Jul 19 15:16 test.mp3
> ```
> 
> If you modify the build to remove resource filtering then it is works as expected:
> 
> ```
> <resources>
>             <resource>
>                 <directory>src/main/resources</directory>
>                 <filtering>false</filtering>
>             </resource>
>         </resources>
> ```

i tried and it worked.
but when i downgraded vert.x to 3.9.5 and had no other changes, it also worked.
