### ISSUE TITLE
Rename HTTP client option tryUseCompression to decompressionSupported

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#4022]
The client `tryUseCompression` option seems misleading as it implies that it will try to compress the request and instead it means that it will send a request with an `accepting-encoding` header set to a compression algorithm to tell the server that it supports a compressed body and will inflate it.

The server can decompress HTTP client bodies and the option is named `decompressionSupported`. We could deprecate `tryUseCompression` and rename it `decompressionSupported`.

**Comment by tsegismont** [comment]
Resolved by #4929
