### ISSUE TITLE
PKCS12 Keystore format when running in a FIPS-restricted JRE

### ISSUE THREAD

**Issue by kjrokos** [eclipse-vertx/vert.x#4031]
### Version

3.9.8, but later versions appear to have the same issue.

### Context

We are developing a number of applications that need to be able to run in a JRE that has all non-FIPS compliant encryption formats disabled/removed. We have a `BCFKS` KeyStore, and we are able to read it in, however, we get an error because Vert.x then tries to initialize an internal `PKCS12` KeyStore, which is not present in our environment:
```
io.vertx.core.VertxException: java.security.KeyStoreException: PKCS12 not found
```
We traced the issue to the `createEmptyKeyStore` function in `/src/main/java/io/vertx/core/net/impl/KeyStoreHelper.java`, which hard-codes the new empty keystore to the `PKCS12` format. We verified that we could create a custom build of Vert.x with the hard-coded value changed to `BCFKS`, and Vert.x then successfully runs on the affected environment, however this is not a practical long-term solution. 

### Do you have a reproducer?

To reproduce, you will need to remove the `PKCS12` KeyStore format from the JRE's `lib/security/java.security` file. To do this, find the list of providers and comment out the line containing `com.sun.net.ssl.internal.ssl.Provider`. Save the file, and then read in a (non-PKCS12) KeyStore using Vert.x.

**Comment by vietj** [comment]
@pmlopes do you think we could fallback on JKS type store when PKCS is not available ? (that would mean some features would not work correctly in this case, but that can be fine).

**Comment by pmlopes** [comment]
@vietj why not use:

https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/security/KeyStore.html#getDefaultType()

This will be from java9 and up `PKCS12` else `JKS` and if ` keystore.type` isn't defined in security properties falls back again to `JKS`

**Comment by pmlopes** [comment]
Also if for `FIPS` other default should be used, like in the report, replace the property:

```
# file: conf/security/java.security
keystore.type=BCFKS
```

Will then mean that using the method referred in the previous comment will return `BCFKS` as expected.

**Comment by kjrokos** [comment]
`KeyStore.getDefaultType()` works for our use case (our default is already set to `BCFKS`). The only downside is, as @pmlopes mentioned, that it will cause Java 8 to regress to using `JKS` rather than `PKCS12`.

**Comment by vietj** [comment]
@pmlopes as @kjrokos said we should fallback instead of using the default type which is not intended on Java 8

**Comment by kjrokos** [comment]
IMO, defaulting to `PKCS12` and falling back to `getDefaultType()` has the somewhat strange property that you can change the keystore format to e.g., be FIPS compliant, but only if you disable the `PKCS12` format. This is the case for us, but I'm not sure if it's the case in general. I'd prefer using `getDefaultType()` as the primary, but upgrade to `PKCS12` if `getDefaultType()` returns `jks` (and `PKCS12` exists).

Another alternative would be to use the type specified in `io.vertx.core.net.KeyStoreOptions`. The advantage being that no modification of the `java.security` file is necessary, and we could continue to use `PKCS12` as the default unless the user explicitly overrides it. I'm not sure how feasible that is, however - at first glance it looks like it would require touching a lot of code.

FWIW, I'm happy to make a PR for whichever solution is agreed upon if you'd like.

**Comment by pmlopes** [comment]
@vietj, like @kjrokos wrote I believe that we should try to be as default as possible, so if the JVM has been configured to default to something else, I don't think vert.x should be enforcing PKCS12.

In a way to we can check if PKCS12 is available with:

```java
static boolean hasPKCS12 = Security.getAlgorithms("KeyStore").contains("PKCS12");
```

We can also issue a warning that if we go with the JDK defaults, users still on JDK8 should start vert.x apps with:

```
-Dkeystore.type=pkcs12
```

To have the previous behavior.

**Comment by pmlopes** [comment]
PR cherry picked to 4.1.3
