### ISSUE TITLE
Promises/futures with context do not always use context exception handler

### ISSUE THREAD

**Issue by austin-beer** [eclipse-vertx/vert.x#4032]
### Version

4.1.2

### Description

If a promise is completed or failed, any handler attached to the associated future may throw an exception. How that exception is handled currently depends on several factors:

1. Future has a context, but the future is completed/failed on a different context:
    * Behavior: The exception is given to context.reportException() and does not bubble up.
2. Future has a context, and the future is completed/failed on that context:
    * Behavior: The exception bubbles up to whatever completed/failed the promise.
3. Future does not have a context:
    * Behavior: The exception bubbles up to whatever completed/failed the promise.

The behavior of situation 2 should match 1. But it currently matches 3. This behavior is due to the if() statement at https://github.com/eclipse-vertx/vert.x/blob/4.1.2/src/main/java/io/vertx/core/impl/future/FutureBase.java#L50.

See #1568 for the discussion that led to the creation of this issue.

**Comment by austin-beer** [comment]
@vietj, thanks for so promptly addressing this issue! One question, though. Is there a reason why the catch in emit() was left in place? https://github.com/eclipse-vertx/vert.x/blob/d07329c92ce9b981a9425d2d0a3187554414a9bf/src/main/java/io/vertx/core/impl/future/FutureBase.java#L85

**Comment by vietj** [comment]
this emit is actually from SucceededFuture and FailedFuture and is not
directly related.

perhaps it is something we need to care about as well.

also perhaps this method should be moved to another class as it seems
confusing.

**Comment by austin-beer** [comment]
Yes, I think we need to care about emit() as well since it has the same bug that this issue described.

**Comment by knotenpunkt** [comment]
@vietj arent you sure that this here is related? https://github.com/eclipse-vertx/vert.x/issues/3318

**Comment by vietj** [comment]
@austin-beer here is a follow up commit (https://github.com/eclipse-vertx/vert.x/commit/583e9a03b1a26ed41856223de42036f2d786e7e3) that fixes what you observed, thanks for finding this issue. In addition I could simplify and get rid of the emit method and use directly the context emit method in this particular case.

**Comment by austin-beer** [comment]
Thanks @vietj. The changes look great!
