### ISSUE TITLE
Metric "vertx.eventbus.messages.pending" is not decreasing.

### ISSUE THREAD

**Issue by dehypnosis** [eclipse-vertx/vert.x#4033]
### Questions

Metric `vertx.eventbus.messages.pending` is not decreasing in some cases.

![image](https://user-images.githubusercontent.com/3263661/126925579-df9a14f1-9e33-44c1-bfeb-964a601a39c3.png)

In my application, it seems exact number of handlers going up and down well as time goes. while some of pending handlers seem to forget to decrease themselves metric.
At the end of the cliff, I had restarted the application.

I think this mismatch supposed to happen at the point of rapidly unregistering consumers... maybe?
I made a reproducer for it. @vietj 

### Version

using vertx 4.1.0.

### Context

From https://github.com/eclipse-vertx/vert.x/issues/1480

### Steps to reproduce

1. to run, clone https://github.com/dehypnosis/vertx-pending-handlers
2. and execute `./run.sh`
3. check `http://localhost:8080` with browser which shows weird prometheus metrics. You can see `vertx.eventbus.messages.pending` is stuck.

**Comment by vietj** [comment]
I think you already opened an issue for this, didn't you ?

**Comment by dehypnosis** [comment]
Yeah, sure. I opened new issue because you said "can you open a new issue and link this reproducer ?" at [the old issue](https://github.com/eclipse-vertx/vert.x/issues/1480#issuecomment-884767673). 😃
