### ISSUE TITLE
Vert.x 4.x swallows exceptions in UDP listenMulticastGroup

### ISSUE THREAD

**Issue by tmulle** [eclipse-vertx/vert.x#4042]
### Version

Which version(s) did you encounter this bug ?

Version: 4.x (currently using 4.1.2)
OS: Mac OS 11.5 Big Sur
JDK: 11.0.11.fx-zulu (I've tried other jdk11s also)

### Context

When running the following code under 3.9.x I see the **NullpointerException** print out to the console.
However, when I use the same code under 4.1.2 the exception is swallowed and the "failed" method of the result is not called. I had to step through the debugger to find the exception.

I would like to listen on ALL interfaces without having to loop through the interfaces on my machine. I've done this in the past with other frameworks but was hoping that just using this method would do it.

I just wanted to make you aware of the exception handling differences between the two versions...

### Do you have a reproducer?

```
import io.vertx.core.AbstractVerticle;
import io.vertx.core.Promise;
import io.vertx.core.Vertx;
import io.vertx.core.datagram.DatagramSocket;
import io.vertx.core.datagram.DatagramSocketOptions;

public class UdpTestVerticle extends AbstractVerticle {

    public static void main(String[] args) {
        Vertx vertx = Vertx.vertx();
        vertx.deployVerticle(new UdpTestVerticle());
    }
    
    @Override
    public void start(Promise<Void> promise) throws Exception {
        
        DatagramSocketOptions options = new DatagramSocketOptions()
                .setReuseAddress(true)
                .setReusePort(true);
        
        DatagramSocket socket = vertx.createDatagramSocket(options);
        
        // Listen on the port and all interfaces
        socket.listen(35057, "0.0.0.0", ar -> {
           if (ar.failed()) {
               promise.fail(ar.cause());
               return;
           } 
           
           // Under 3.9.8 this throws an exception
           // But in 4.x it swallows the Nullpointer and the failed() never gets called
           socket.listenMulticastGroup("224.0.0.224", listen -> {
               if (listen.failed()) {
                   promise.fail(listen.cause());
                   return;
               }
              
               System.out.println("All Good!");
           });
        });
    }                
}
```

### Steps to reproduce

1. Run the above code under both 3.9.x and 4.1.x codebase and observe the differences in exception handling

### Extra
I found this issue which shows the NullPointer issue on MacOs. 
[listenMulticastGroup doesn't work with a null NetworkInterface](https://github.com/eclipse-vertx/vert.x/issues/3436)
Thanks!

**Comment by vietj** [comment]
in 4.1, the exception is thrown by the method listenMulticastGroup and the code can catch it at this time.

however I think the exception should be reported in the callback instead of being thrown directly

can you double check on your side ?
