### ISSUE TITLE
RoutingContextImpl always logs failures

### ISSUE THREAD

**Issue by stuartwdouglas** [eclipse-vertx/vert.x#4046]
io.vertx.ext.web.impl.RoutingContextImpl#fail(int, java.lang.Throwable) will always log a failure at INFO. This is a problem as it means that later failure handlers can't choose to log or not to log. 

I think this should be changed to a 'last resort' approach, where logging at error level only happens if it is not handled by the error routes. 

In addition IMHO this should be logged at DEBUG for 4xx responses, and ERROR for 5xx responses. 4xx responses can be trivially caused by the client, and it is not a good idea to allow clients to generate arbitrary amounts of log messages.

**Comment by vietj** [comment]
I'm seing this is logged with debug:

```java
    if (LOG.isDebugEnabled()) {
      LOG.debug("RoutingContext failure (" + statusCode + ")", failure);
    }
```

am I missing something?

**Comment by vietj** [comment]
do you mean we could save the throwable and later only log it if errorHandler is null ?

```
    if (errorHandler != null) {
      try {
        errorHandler.handle(this);
      } catch (Throwable t) {
        LOG.error("Error in error handler", t);
      }
    }
```

**Comment by stuartwdouglas** [comment]
Oops, I created this in the wrong repo. Looks like this has already been fixed anyway (https://github.com/vert-x3/vertx-web/commit/552733f2fbf98411237d209b912d3f6a9974ba52), sorry for the noise.
