### ISSUE TITLE
vertx-health-check does not respond properly if using mountSubRouter()

### ISSUE THREAD

**Issue by Tibor17** [eclipse-vertx/vert.x#4048]
The health check returns `{"message": "Not found"}` if you use sub-router with the application path '/'.
You want to send the request `http://127.0.0.1:8080/productsAPI/health` and you observe the JSON `{"status":"UP","checks":[{"id":"measured-data-adapter","status":"UP"}],"outcome":"UP"}` which works fine! But you observe  `{"message": "Not found"}` if the main router path turns from `productsAPI` to `/`.
Prometheus is has a very similar programming approach but it is not buggy and it works as expected with any path in the main router.

### Version

4.1.2

My code looks like this:

```
restAPI.route("/health")
    .order(1)
    .handler(HealthCheckHandler.create(vertx).register("measured-data-adapter", p -> p.complete(OK())));
Router mainRouter = Router.router(vertx);
mainRouter.mountSubRouter(serverPath, restAPI);
mainRouter.errorHandler(HTTP_NOT_FOUND, h -> invalidRequest(HTTP_NOT_FOUND, h.request()));
mainRouter.errorHandler(HTTP_INTERNAL_ERROR, h -> {
    LOG.error("Internal Server Error", h.failure());
    invalidRequest(HTTP_INTERNAL_ERROR, h.request());
});

httpServer.connectionHandler(this::handleConnection)
    .requestHandler(mainRouter)
    .listen(serverPort, serverHost, this::connectionHandler);
```

**Comment by vietj** [comment]
can you reopen this issue here https://github.com/vert-x3/vertx-health-check/ ? thanks

**Comment by Tibor17** [comment]
@vietj 
This is it https://github.com/vert-x3/vertx-health-check/issues/31
