### ISSUE TITLE
io.vertx.core.impl.logging.Logger should support parameterized messages

### ISSUE THREAD

**Issue by Tibor17** [eclipse-vertx/vert.x#4049]
The slf4j supports the log format e.g. `{} then {} and {}`, where you may log the message with var-args `LOG.info("{}{}{}", "1", 2, 3)`.
Can we have the same programming paradigm in  Vert.x?

**Comment by vietj** [comment]
we don't want to emphasize anymore on the logging in vertx 4 and will not make the API evolve. You should directly use SLF4J if you need this feature.
