### ISSUE TITLE
Use Vert.x WebClient component under macOS operating system to request warning log

### ISSUE THREAD

**Issue by zf1976** [eclipse-vertx/vert.x#4058]
I am using the WebClient component to send a request and the following log occurs. How can I solve the problem?

"2021-08-06 18:58:46.372 [vert.x-eventloop-thread-1] WARN io.netty.resolver.dns.DnsServerAddressStreamProviders-Can not find io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider in the classpath , fallback to system defaults. This may result in incorrect DNS resolutions on MacOS.

**Comment by vietj** [comment]
you need to add `io.netty:netty-resolver-dns-native-macos` with the classifier, see https://github.com/eclipse-vertx/vert.x/commit/74e9cc5b46f74f45a898530626274c18d9b05994
