### ISSUE TITLE
MacOS IPv6 UDP - No Route to Host (Works on Linux and Windows)

### ISSUE THREAD

**Issue by tmulle** [eclipse-vertx/vert.x#4059]
### Version

Which version(s) did you encounter this bug ?

Vert.x: 4.1.2

### Context

I encountered an exception which looks suspicious while trying to use UDP packet sending on MacOS.

### Do you have a reproducer?

Yes, I hope it is helpful. I spent a lot of time to make it configurable and to try to demonstrate the scenario I'm trying to accomplish and show you the error I am getting.

I tried to give as much documentation as possible..

* https://github.com/tmulle/VertxNettyUDP6Tester

### Steps to reproduce

1. Follow README in the repo

### Extra

* All information is in the README

**Comment by tmulle** [comment]
I've included a pure Java `java.net.*` version of the application as well to demonstrate that using standard Java networking works properly.

**Comment by vietj** [comment]
I've run your reproducer and I can observe this behaviour using the wifi interface. 

When I run the reproducer with the Java version I can observe with Wireshark that although packets are sent to the wifi interface, they actually use the loopback interface.

Can you check that on your side?

**Comment by tmulle** [comment]
Hi Julien,

I won’t be able to work on this for a few days. I’m about to leave for a vacation until Friday. 

That’s an interesting observation however. 

I will look when I get back if you still need me to. 

Thanks,
Tim

**Comment by vietj** [comment]
thanks, I would like just to see if we are in the same conditions.

I suspect that the packet does not get routed on OSX in my case because my
router does not handle IPV6, hence it makes sense to fail.

**Comment by tmulle** [comment]
Hi Julien,

I have updated my tester code for the regular java version so that it uses the specified interface when sending the UDP multicast traffic. I accidentally left off the part to set the interface so it was defaulting to the loopback interface. I saw the same thing in Wireshark as you did.

I also updated my Vertx version of the Sender class so that it also sets the Multicast interface when sending out the data and that seems to fix the sending of multicast UDP packets. 

However, sending plain non-multicast UDP packets in the Vertx version still gives me the same "No Route to Host" error as before.

**Comment by tmulle** [comment]
Just wondering is there anymore information on this topic?

Is there any more testing you'd like me to do? Was my tester program sufficient?

Thanks..

**Comment by tmulle** [comment]
FYI.. I just tried my tester code with 4.2.0.Beta1 and still the same issue with IPv6

**Comment by vietj** [comment]
I think we could try checking why it is not routed when it uses the non loopback interface and see if adding a multicast routing rule would make it work

**Comment by vietj** [comment]
that what I was suspecting previously afair

**Comment by jo4ever** [comment]
Hi:
I've tested your tester code on my Mac, but the test result is all right whether use Java NIO classes or Vertx code, here is my test result:

```
[main] INFO netty.udp.VertUDPTester - *** Starting Variables ***
[main] INFO netty.udp.VertUDPTester - Operation Mode = Both
[main] INFO netty.udp.VertUDPTester - Network Mode = IPv6
[main] INFO netty.udp.VertUDPTester - Network Interface = en0
[main] INFO netty.udp.VertUDPTester - Network Listen All Interface = ::
[main] INFO netty.udp.VertUDPTester - Network Multicast Group = FF02::1
[main] INFO netty.udp.VertUDPTester - Network Port = 35056
[main] INFO netty.udp.VertUDPTester - **************************
[vert.x-eventloop-thread-0] INFO netty.udp.VertUDPTester$Sender - Listening for Unicast message on IPv6 @ 0:0:0:0:0:0:0:0:56094
[vert.x-eventloop-thread-1] INFO netty.udp.VertUDPTester$Device - Listening for Multicast Messages on IPv6 Group [FF02::1] on local address (en0): 0:0:0:0:0:0:0:0:35056
[vert.x-eventloop-thread-0] INFO netty.udp.VertUDPTester$Sender - Starting to send Discovery Requests every 10 seconds
[vert.x-eventloop-thread-0] INFO netty.udp.VertUDPTester$Sender - Sending request...
[vert.x-eventloop-thread-0] INFO netty.udp.VertUDPTester$Sender - Request sent successfully
[vert.x-eventloop-thread-1] INFO netty.udp.VertUDPTester$Device - Received Discovery Packet from fe80:0:0:0:1c39:274:2260:9983%6:56095 with data {"action":"REQUEST","responsePort":56094}
[vert.x-eventloop-thread-1] INFO netty.udp.VertUDPTester$Device - Sending response back to fe80:0:0:0:1c39:274:2260:9983%6:56094 with data - {"id":"9520fdfa-e6e4-4f7d-9b7e-974d6cf83e9d","date":"2021-11-18T09:11:40.288061"}
[vert.x-eventloop-thread-0] INFO netty.udp.VertUDPTester$Sender - Got a discovery response message from fe80:0:0:0:1c39:274:2260:9983%6:35056 with data - {"id":"9520fdfa-e6e4-4f7d-9b7e-974d6cf83e9d","date":"2021-11-18T09:11:40.288061"}
[vert.x-eventloop-thread-1] INFO netty.udp.VertUDPTester$Device - Response Sent ok
[vert.x-eventloop-thread-0] INFO netty.udp.VertUDPTester$Sender - Sending request...
[vert.x-eventloop-thread-0] INFO netty.udp.VertUDPTester$Sender - Request sent successfully
[vert.x-eventloop-thread-1] INFO netty.udp.VertUDPTester$Device - Received Discovery Packet from fe80:0:0:0:1c39:274:2260:9983%6:56095 with data {"action":"REQUEST","responsePort":56094}
[vert.x-eventloop-thread-1] INFO netty.udp.VertUDPTester$Device - Sending response back to fe80:0:0:0:1c39:274:2260:9983%6:56094 with data - {"id":"9520fdfa-e6e4-4f7d-9b7e-974d6cf83e9d","date":"2021-11-18T09:11:50.229602"}
[vert.x-eventloop-thread-1] INFO netty.udp.VertUDPTester$Device - Response Sent ok
[vert.x-eventloop-thread-0] INFO netty.udp.VertUDPTester$Sender - Got a discovery response message from fe80:0:0:0:1c39:274:2260:9983%6:35056 with data - {"id":"9520fdfa-e6e4-4f7d-9b7e-974d6cf83e9d","date":"2021-11-18T09:11:50.229602"}
Disconnected from the target VM, address: '127.0.0.1:59406', transport: 'socket'
```

I have the same Java version as you use.

```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

My system is a 2020 13" Macbook Pro running Catalina (10.15.5) and use Wireless networking.
Wireless Network Settings

```
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether 90:9c:4a:b6:bf:5c
	inet6 fe80::1c39:274:2260:9983%en0 prefixlen 64 secured scopeid 0x6
	inet6 2408:8456:3244:314a:7b:59e3:3ba9:4775 prefixlen 64
	inet 192.168.43.71 netmask 0xffffff00 broadcast 192.168.43.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
```

Furthermore, when i execute the code first time, system firewall promts something like "Are you allowed to pass" and select "Allow", but i use wireshark for packet capture, it shows that no UDP packets are coming in through the en0 interface.

**Comment by tmulle** [comment]
Interesting, I've updated the code to use Vertx 4.2.1 and I still get the issue.

However, interesting finds:

IPv6 Mode
-----------
1. JDK17 works fine if both Sender and Device running on same machine - Fails once they are separated on two different machines
2. JDK8 and JDK11 fail with the error even if both Sender and Device mode running on same machine or split up.

IPv4 Mode
----------
All JDKs and combinations of local and remote Sender and Device modes work properly


The Regular Java version always works for me no matter how I run it.

**Comment by tmulle** [comment]
Any further ideas on this? Am I the only one using VertX UDP in this manner?

**Comment by tmulle** [comment]
@vietj This is fixed in Netty 4.1.74.Final. I tested by overriding the Netty dependencies in Vert.x to use version 4.1.74.Final and the issue is resolved.

Just letting you all know..that once Vert.x updates its Netty dependencies to 4.1.74.Final things will work for me.

**Comment by vietj** [comment]
thanks for checking that, can you link the corresponding netty issue ? we will upgrade to 4.1.74.Final

**Comment by tmulle** [comment]
@vietj Here's the link to the Netty issue I reported that is fixed.

https://github.com/netty/netty/issues/11563

**Comment by vietj** [comment]
I can see good investigation from your side in the Netty project !!!
