### ISSUE TITLE
Enable custom host name verifier

### ISSUE THREAD

**Issue by zqmmqz** [eclipse-vertx/vert.x#4065]
#### Describe the feature

[NetClientOptions](https://vertx.io/docs/apidocs/io/vertx/core/net/NetClientOptions.html#setHostnameVerificationAlgorithm-java.lang.String-) now support specific algorithm for host name verification. 
Is it possible to support custom host name similar to the uses of [javax.net.ssl.HostnameVerifier](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/class-use/HostnameVerifier.html)?

#### Use cases
Besides the default verification which compares the common name in the SubjectDN in the SSL server's digital certificate with the host name of the SSL server, one would want to verify other behaviors. 

My uses case is that we use a vertx client to talk to a server whose cert's common name isn't a valid host name. So we want to verify one fixed field in the SubjectDN. Currently we disable the host name verification to skip this because vertx asks a [specific algorithm for the verification](https://vertx.io/docs/apidocs/io/vertx/core/net/NetClientOptions.html#setHostnameVerificationAlgorithm-java.lang.String-), but our case needs a more complex logic.

**Comment by vietj** [comment]
not sure it is possible (depending on the hooks in Netty for this)

**Comment by tsegismont** [comment]
This might be useful for the Reactive MSSQL Client too: when a server redirects the client to another server (with TDS `ROUTING` token), the hostname provided for connection may not be the same as of the actual server.

**Comment by tsegismont** [comment]
Duplicates #3720

It is already possible to customize verification. Create a [`TrustManager`](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/TrustManager.html) instance and then custom [`TrustOptions`](https://vertx.io/docs/apidocs/io/vertx/core/net/TrustOptions.html#wrap-javax.net.ssl.TrustManager-) with `wrap`.
