### ISSUE TITLE
Change `EventBus.registerDefaultCodec` from `MessageCodec<T, ?>` to `MessageCodec<? super T, ?>`

### ISSUE THREAD

**Issue by kristian** [eclipse-vertx/vert.x#4087]
#### Describe the feature

`EventBus.registerDefaultCodec` currently allows to register a default message coded for a given class `T`. We would like to reuse the same message codec to send them over the wire. However `EventBus.registerDefaultCodec` does not have a `MessageCodec<? super T, ?>` and thus does not allow it.

#### Use cases

Imagine having multiple "Ducks" that you want to send via the wire:

- `GreatDuck`
- `SmallDuck`
- `DuckyMcDuck`

All ducks implement the `Duck` interface and a `toJson` method.

The idea would be to implement one `DuckMessageCodec` which can handle any duck by calling the `toJson` object. Currently you cannot register this one codec for all the ducks, because:

```
DuckMessageCodec duckMessageCodec = new DuckMessageCodec();
eventBus.registerDefaultCodec(GreatDuck.class, duckMessageCodec);
eventBus.registerDefaultCodec(SmallDuck.class, duckMessageCodec);
eventBus.registerDefaultCodec(DuckyMcDuck.class, duckMessageCodec);
```

#### Contribution

It is a one line change thus it could be contributed.

**Comment by lucaguada** [comment]
This could be related to another kind of issue that I was about to open: by improving this it would be possible to create a single codec for the new `record-type` in Java17, since at the moment I have to create plenty of codecs for every new defined record.

Or at least this could be a starting point for supporting record-types.

**Comment by kristian** [comment]
@lucaguada yes, this is one potential use case: generic codecs. :)

**Comment by vietj** [comment]
I think we should allow perhaps rather inheritance in the codec if the codec can handle it which would mean a single registration for all subclasses

**Comment by vietj** [comment]
see https://github.com/eclipse-vertx/vert.x/issues/2762

would this solve the problem ?

**Comment by kristian** [comment]
@vietj it is definitely a related problem, however my previous assumption was that you purposefully *did not* traverse up through the class hierarchy when trying to find a message codec, because you always want to be most-specific. Generally traversing up to find a codec _could_ be very dangerous, as a codec that can handle (staying at this example) `Animal`. might not be suited to transfer all kinds of `Duck`s, especially when decoding the payload, such generic message codecs often need some kind of special logic, because e.g. calling a `toJson` on a generic object will always work and can be overridden. However to then re-instantiate a given object, a factory of some sort will be needed that converts the JSON back to the _corresponding_ object. Not every codec might account for that. Here is my humble opinion:

- I think both approaches, the one I presented here and the one of #2762 could solve the issue
- My approach is a little more "explicit" as it requires you to specifically tell _for each class_ "that is my generic codec, that can handle you"
- On the other hand traversing up through the class hierarchy would work as well, although I would maybe recommend adding a new default method to the MessageCodec interface, to give the codecs the ability to indicate if they can handle generic types (I think a boolean could be sufficient), as otherwise this a) would need to be considered a breaking change, because it changes the current logic and b) this makes it more explicit and avoids unwanted side-effects

**Comment by vietj** [comment]
I agree it would be a breaking change if we don't allow a codec to tell whether it can handle subclasses or not, that's a good point that could lead to unexpected results.

Can you have look at https://github.com/eclipse-vertx/vert.x/pull/4117

I agree that changing the interface is also good although I'm not a fan of bounded wildcards. We can consider that in this situation.

**Comment by kristian** [comment]
👍 I like that. Also I am happy to see that you will put some "love" into the message codec logic in #4117. When looking at the code, it felt to me the whole codec stuff wasn't given much attention for quite some time, so a little overhaul definitely is well appreciated! 🥂 Thanks so much @vietj. Another additional into such a "topic related" PR, might be adding individual tests for all the default codecs.

**Comment by vietj** [comment]
@kristian if you could contribute tests for default codec it would be great

**Comment by kristian** [comment]
> @kristian if you could contribute tests for default codec it would be great

@vietj sure, I think I can do it latest on this weekend. I'll let you know.

**Comment by vietj** [comment]
@lucaguada can a record extends another record ?

**Comment by tsegismont** [comment]
Closing as won't fix. A solution could be to use a default selector https://github.com/eclipse-vertx/vert.x/issues/4365
