### ISSUE TITLE
Improve Handler<Promise<T>>

### ISSUE THREAD

**Issue by aomsweet** [eclipse-vertx/vert.x#4094]
#### Describe the feature

The Handle() method definition does not throw an exception, which sometimes makes the code look verbose and cumbersome. 

E.g:

```java
        vertx.executeBlocking(promise -> {
            try {
                File file = writeZipFile(policies);
            } catch (IOException | JAXBException e) {
                promise.fail(e);
            }
        });
```
Exception catching seems redundant here, because the promise can be automatically set to fail when the program is error.
```java
        // Concise code
        vertx.executeBlocking(promise -> writeZipFile(policies));
```

I think can use `PromiseHandler<T>` to replace `Handler<Promise<T>>`. Of course this is not a good solution, it's just my idea.

```java
public interface PromiseHandler<T> extends Handler<Promise<T>> {

    @Override
    default void handle(Promise<T> promise) {
        try {
            handle0(promise);
        } catch (Exception e) {
            promise.fail(e);
        }
    }

    void handle0(Promise<T> promise) throws Exception;
}
```

**Comment by vietj** [comment]
this seem only to apply to execute blocking.

if I were to improve execute blocking, instead I would change it so that it returns something instead of having a Promise to complete, with a Runnable or a Supplier, e.g

`Future<Void> executeBlocking(Runnable action);
`<T> Future<T> executeBlocking(Supplier<T> action);

**Comment by aomsweet** [comment]
Hi. @vietj Thanks for your reply, I'm sorry for the late reply due to other things. As you said, it is really only related to the `executeBlocking()` method. The feature proposal is invalid.

**Comment by aomsweet** [comment]
It's possible to add the following methods?

`<T> Future<T> executeBlocking(Callable<T> action);`

**Comment by vietj** [comment]
right that could be something we can do altough I'm thinking it should be somehow supported in codegen first along with Supplier
