### ISSUE TITLE
openapi gives 400 http status code, when uploading file with multipart/form-data

### ISSUE THREAD

**Issue by ebadta81** [eclipse-vertx/vert.x#4095]
### Version

Which version(s) did you encounter this bug ?
4.1.3

### Context

Vertx openapi gives 400 http status code, when uploading file with multipart/form-data

### Do you have a reproducer?

https://github.com/ebadta81/test

### Steps to reproduce

After starting the test project, load the http://localhost:8443/web/index.html#/upload/upload-image url in your browser, and  send a request with swagger ui.

You will get 400 | Error: Bad Request

### Extra

MacOs 11.5.2
openjdk 11.0.10 2021-01-19

**Comment by tsegismont** [comment]
Can you please file this to the [vert-x3/vertx-web](https://github.com/vert-x3/vertx-web/issues/new/choose) repo? Thanks
