### ISSUE TITLE
doc: DEFAULT_CACHE_MIN_TIME_TO_LIVE/DEFAULT_CACHE_MAX_TIME_TO_LIVE documentation is incorrect?

### ISSUE THREAD

**Issue by TysonAndre** [eclipse-vertx/vert.x#4097]
### Version

Latest 4.x

### Steps to reproduce

Go to https://vertx.io/docs/apidocs/io/vertx/core/dns/AddressResolverOptions.html#DEFAULT_CACHE_MAX_TIME_TO_LIVE

Observe this says 
> public static final int DEFAULT_CACHE_MIN_TIME_TO_LIVE
> The default value for the negative cache min TTL = 0

Observe that https://github.com/eclipse-vertx/vert.x/blob/11ab144725e551be591118831377101015e1392c/src/main/java/io/vertx/core/dns/AddressResolverOptions.java#L239-L259 **is actually a positive cache TTL** (positive=cache hit) to cache successful responses

Same for https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/dns/AddressResolverOptions.java#L41-L49

I believe that the `negative` part was just left over from copying and pasting the comment, it's for cache hits. **DEFAULT_CACHE_NEGATIVE_TIME_TO_LIVE** is the only constant that's actually a negative TTL for cache misses

### Desired Behavior

Update javadoc in  https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/dns/AddressResolverOptions.java#L41-L49 to remove negative from

**Comment by vietj** [comment]
that's right thanks it has been corrected
