### ISSUE TITLE
Add promise.resolve and promise.reject

### ISSUE THREAD

**Issue by boulderwebdev** [eclipse-vertx/vert.x#4101]
#### Describe the feature

In javascript, the [Promise API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#static_methods) provides two useful utility methods `Promise.resolve` and `Promise.reject` for quickly turning a value into something wrapped by a promise. It would be nice to have this feature included with the core Promise.java class.

#### Use cases

For example, I've seen the [following](https://github.com/eclipse-vertx/vert.x/blob/11ab144725e551be591118831377101015e1392c/src/main/java/io/vertx/core/shareddata/impl/AsynchronousCounter.java#L41) [code](https://github.com/eclipse-vertx/vertx-sql-client/blob/cbfcbe635cf1dae84f20c1ad47d5feab01160b07/vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SqlClientBase.java#L111) [snippet](https://github.com/eclipse-vertx/vertx-http-proxy/blob/68216557cba5cc3ad7aa309f3d2ee2c37c1cb3d1/src/main/java/io/vertx/httpproxy/impl/HttpProxyImpl.java#L263) used in the codebase

```java
protect void myFunc () {
  // ...
  Promise<String> promise = Promise.promise();
  promise.complete("Some val");
  return promise.future();
}
```

which is rather verbose. It would be nice if I could just write

```java
return Promise.resolve("Some val").future();
```
for those last three lines.

#### Contribution

Who should implement this feature ? are you volunteering for implementing this feature or
do you know that is able and willing implement this feature ?

TBD

**Comment by pmlopes** [comment]
@boulderwebdev you could just do:

```java
return Future.succeededFuture("Some Val");
```

As you don't need to define the result at a later time. A similar API is also available for failures.

**Comment by vietj** [comment]
I agree with @pmlopes no need to use a promise when what you need is a future.

JavaScript provides a dual object that server both as promise and future.

**Comment by boulderwebdev** [comment]
@pmlopes That works fine, thanks!
