### ISSUE TITLE
Client loses first body chunks if future is converted to java CompletableFuture

### ISSUE THREAD

**Issue by silmeth** [eclipse-vertx/vert.x#4106]
### Version

4.1.4

### Context

Again testing a server streaming a chunked response. When using Vertx HTTP client, if the futures from `.connect()` call and the one from `.body()` call are converted to `java.util.concurrent.CompletableFuture` by `.toCompletionStage().toCompletableFuture()`, then the client loses a few (2–3) first chunks of the response body. The same happens with just `.toCompletionStage()` – but I have included the `.toCompletableFuture()` step in the test too, as I do use that in the actual code where I first noticed this.

### Do you have a reproducer?
A modified version of the reproducer from #4072 – with new test added that does the conversion. The old tests all pass, but the new one fails on body assertions because of the lost chunks with something like
```
org.opentest4j.AssertionFailedError: expected: <chunk 1chunk 2chunk 3final chunk> but was: <final chunk>
```

[silmeth/vertx-chunked-reproducer](https://github.com/silmeth/vertx-chunked-reproducer)

### Steps to reproduce

1. Clone the repo linked above.
2. Run `./gradlew test` from the repo’s directory.

The code is in [`src/test/kotlin/chunked/reproducer/ChunkedTest.kt`](https://github.com/silmeth/vertx-chunked-reproducer/blob/main/src/test/kotlin/chunked/reproducer/ChunkedTest.kt)

**Comment by vietj** [comment]
which test is it ? there are four tests here.

can you also write them in Java ? it's easier to read

I think overall it is expected, I think you are not running your code on the event-loop and your code is therefore racy although I haven't checked (because the code is convoluated and written in Kotlin).

**Comment by silmeth** [comment]
It’s the same code as in the reproducer of #4072. It’s the new test, `chunkedResponseJavaCompletableFuture`. But you are right the code is not run on Vertx context (the actual code where I encountered it first *does run* on Vertx context though, using a fork of [`VertxCompletableFuture`](https://github.com/cescoffier/vertx-completable-future). I’ll modify it to use that instead and run all the code on the context tomorrow.

**Comment by vietj** [comment]
you should remain away completable future if you can because they make sometimes reasoning more complicated.

if you provide a reproducer that is not racy, then it's a bug we need to fix.

**Comment by silmeth** [comment]
@vietj I edited the test-case to resemble more what we do in the code. Every stage runs now on Vertx event loop (in my run even on the same thread) and yet the problem still exists. The only difference is that now instead of running `.thenApply()`, I run `.thenApplyAsync(mapping, executor)` where `executor` is one that uses `vertx.runOnContext()` to schedule the next stage on the event-loop.

The code now is:

```kotlin
    @Test
    fun chunkedResponseJavaCompletableFuture(): Unit = assertTimeoutPreemptively(Duration.ofSeconds(3L)) {
        val testFinished = CompletableFuture<Unit>()
        val executor = { cmd: java.lang.Runnable ->
            System.err.println("Scheduling async execution, thread: ${Thread.currentThread().name}")
            vertx.runOnContext { cmd.run() }
        }

        vertx.runOnContext {
            server
                .toCompletionStage()
                .toCompletableFuture()
                .thenComposeAsync({
                    System.err.println("thread: ${Thread.currentThread().name}")
                    val client = vertx.createHttpClient()
                    client.request(HttpMethod.GET, port, "localhost", "/").toCompletionStage().toCompletableFuture()
                }, executor)
                .thenApplyAsync({
                    System.err.println("thread: ${Thread.currentThread().name}")
                    it.exceptionHandler { e -> testFinished.fail(e) }
                }, executor)
                .thenComposeAsync({
                    System.err.println("thread: ${Thread.currentThread().name}")
                    it.connect().toCompletionStage().toCompletableFuture()
                }, executor)
                .thenComposeAsync({ res ->
                    System.err.println("thread: ${Thread.currentThread().name}")
                    System.err.println("chunkedResponse: received response!")
                    assertEquals(200, res.statusCode())
                    res.body().toCompletionStage().toCompletableFuture().thenApplyAsync({ res to it }, executor)
                }, executor)
                .thenAcceptAsync({ (res, body) ->
                    System.err.println("thread: ${Thread.currentThread().name}")
                    System.err.println("chunkedResponse: received body!")
                    assertEquals("true", res.getTrailer("finished"))
                    assertEquals("chunk 1chunk 2chunk 3final chunk", body.toString(Charsets.UTF_8))
                    testFinished.done()
                }, executor)
                .exceptionally { testFinished.fail(it); null }
        }

        testFinished.join()
    }
```

I added printing to each stage to show on which thread it executes:

```kotlin
Scheduling async execution, thread: vert.x-eventloop-thread-0
thread: vert.x-eventloop-thread-0
Scheduling async execution, thread: vert.x-eventloop-thread-0
thread: vert.x-eventloop-thread-0
Scheduling async execution, thread: vert.x-eventloop-thread-0
thread: vert.x-eventloop-thread-0
Scheduling async execution, thread: vert.x-eventloop-thread-0
thread: vert.x-eventloop-thread-0
chunkedResponse: received response!
Scheduling async execution, thread: vert.x-eventloop-thread-0
Scheduling async execution, thread: vert.x-eventloop-thread-0
thread: vert.x-eventloop-thread-0
chunkedResponse: received body!
```

It still fails with only last chunks received (or with timeout if it doesn’t give any chunks back and just hangs).

**Comment by vietj** [comment]
can you provide a reproducer in 100% java with a project ? I'm trying to adapt your code in Java and it takes time and I'm not able to get it right

**Comment by vietj** [comment]
I think cause in this case is the usage `thenComposeAsync` with an executor that performs a `runOnContext()` operation (async), here is what happen at this stage:

```
.thenComposeAsync({ res ->
                    System.err.println("thread: ${Thread.currentThread().name}")
                    System.err.println("chunkedResponse: received response!")
                    assertEquals(200, res.statusCode())
                    res.body().toCompletionStage().toCompletableFuture().thenApplyAsync({ res to it }, executor)
                }, executor)
```

1. Vert.x receives the HTTP server response and the `Future<HttpClientResponse>` is succeeded on the Vert.x event-loop
2. the completion stage is then completed internally
3. the lambda argument (`res -> ...`) is scheduled with the `executor`
4. the executor calls `runOnContext` and schedules the task asynchronously on the same event-loop
5. the task is finally executed returning the body

Calling `body()` will set handler for chunk and end events, but this is called too late because of the step 4.

This would work without an executor or if the response was paused and then resumed, e.g you could modify

```
.thenComposeAsync({
                    System.err.println("thread: ${Thread.currentThread().name}")
                    val res = it.connect();
                    val.onSuccess(resp -> resp.pause())
                    return.toCompletionStage().toCompletableFuture()
                }, executor)
```

with

```
.thenComposeAsync({ res ->
                    res.resume()
                    System.err.println("thread: ${Thread.currentThread().name}")
                    System.err.println("chunkedResponse: received response!")
                    assertEquals(200, res.statusCode())
                    res.body().toCompletionStage().toCompletableFuture().thenApplyAsync({ res to it }, executor)
                }, executor)
```

This is pretty much what is described here but it happens because of the extra asynchronous operation https://vertx.io/docs/vertx-core/java/#_request_and_response_composition

**Comment by silmeth** [comment]
You’re right I missed that part of documentation. Adding `.onSuccess { res -> res.pause() }` and then `res.resume()` just before setting the body handler does indeed make the test pass. Thanks.
