### ISSUE TITLE
vertx websocket WebSocket connection attempt returned HTTP status code 403

### ISSUE THREAD

**Issue by gillbates** [eclipse-vertx/vert.x#4112]
### Questions

When I try to connect a public server with no auth required, it always throws an exception with:
"WebSocket connection attempt returned HTTP status code 403"

### Version

4.0.3

### Context

I encountered an exception which looks suspicious while ...

`       Vertx vertx = Vertx.vertx();

        HttpClientOptions options = new HttpClientOptions();
        options.setTrustAll(true).setVerifyHost(false);
        options.setSsl(true);

        HttpClient client = vertx.createHttpClient(options);
        client.webSocket(443, "bsc-ws-node.nariox.org", "/").onSuccess(webSocket -> {
            webSocket.handler(data -> {
                log.debug("data:{}", data);
            });
        }).onFailure(err -> {
            log.debug("error:", err);
        });`

### Steps to reproduce

the code above will throws:

![iShot2021-10-01 16 07 10](https://user-images.githubusercontent.com/783547/135586802-f04cdc6c-794f-4c25-b064-f3ad6164648c.jpg)

### Extra

and in my nodejs code, it is working without any problem with following code:

`const WebSocket = require('ws');

async function main() {
    console.log("hallo world ...");

    const ws = new WebSocket('wss://bsc-ws-node.nariox.org:443');

    ws.on('open', function open() {
        console.log("connected ...")
    });
    
    ws.on('message', function incoming(message) {
      console.log('received: %s', message);
    });

}

main().catch(console.log)`

**Comment by vietj** [comment]
you need to dump the traffic to the host in both case, 403 means there is a security error, it does not seem related to Vert.x itself

**Comment by vietj** [comment]
for the record I found the issue, Vert.x WebSocket client does set the _origin_ header, when this header is omitted the server accepts the handshake.

## Vert.x traffic dump

```
GET / HTTP/1.1
sec-websocket-version: 13
sec-websocket-key: WeDzGR667cW+V/e2U/qC0Q==
connection: upgrade
upgrade: websocket
host: bsc-ws-node.nariox.org
origin: https://bsc-ws-node.nariox.org
```

```
HTTP/1.1 403 Forbidden
Date: Tue, 05 Oct 2021 08:50:47 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 10
Connection: keep-alive
Sec-Websocket-Version: 13
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Referrer-Policy: origin-when-cross-origin
Strict-Transport-Security: max-age=31536000; includeSubdomains

Forbidden
```

## Node traffic dump

```
GET / HTTP/1.1
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: 9JTMCIqov24Be4TBAyr4YA==
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Host: localhost:8080
```


```
HTTP/1.1 101 Switching Protocols
Date: Tue, 05 Oct 2021 08:31:15 GMT
Connection: upgrade
Upgrade: websocket
Sec-WebSocket-Accept: aCQdwqaEyVA9PPJlHtseBZ9/BJc=
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Referrer-Policy: origin-when-cross-origin
Strict-Transport-Security: max-age=31536000; includeSubdomains
```

**Comment by gillbates** [comment]
> for the record I found the issue, Vert.x WebSocket client does set the _origin_ header, when this header is omitted the server accepts the handshake.
> 
> ## Vert.x traffic dump
> ```
> GET / HTTP/1.1
> sec-websocket-version: 13
> sec-websocket-key: WeDzGR667cW+V/e2U/qC0Q==
> connection: upgrade
> upgrade: websocket
> host: bsc-ws-node.nariox.org
> origin: https://bsc-ws-node.nariox.org
> ```
> 
> ```
> HTTP/1.1 403 Forbidden
> Date: Tue, 05 Oct 2021 08:50:47 GMT
> Content-Type: text/plain; charset=utf-8
> Content-Length: 10
> Connection: keep-alive
> Sec-Websocket-Version: 13
> X-Content-Type-Options: nosniff
> X-Frame-Options: SAMEORIGIN
> X-Xss-Protection: 1; mode=block
> X-Content-Type-Options: nosniff
> Referrer-Policy: origin-when-cross-origin
> Strict-Transport-Security: max-age=31536000; includeSubdomains
> 
> Forbidden
> ```
> 
> ## Node traffic dump
> ```
> GET / HTTP/1.1
> Sec-WebSocket-Version: 13
> Sec-WebSocket-Key: 9JTMCIqov24Be4TBAyr4YA==
> Connection: Upgrade
> Upgrade: websocket
> Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
> Host: localhost:8080
> ```
> 
> ```
> HTTP/1.1 101 Switching Protocols
> Date: Tue, 05 Oct 2021 08:31:15 GMT
> Connection: upgrade
> Upgrade: websocket
> Sec-WebSocket-Accept: aCQdwqaEyVA9PPJlHtseBZ9/BJc=
> X-Frame-Options: SAMEORIGIN
> X-Xss-Protection: 1; mode=block
> X-Content-Type-Options: nosniff
> Referrer-Policy: origin-when-cross-origin
> Strict-Transport-Security: max-age=31536000; includeSubdomains
> ```

wow, thanks @vietj ...

so for the current version 4.0.3 we are using in our project, is there any workaround I could use to get this working? Or I have to wait for the release of 4.2.0 ...

big thanks !!!

**Comment by vietj** [comment]
we will try to have an option to disable the origin header (which might require a patch of Netty).

workaround is : use a client proxy that removes this header

**Comment by vietj** [comment]
I'll keep you informed

**Comment by vietj** [comment]
a workaround is to use WebSocketConnectOptions and set a different origin header, i.e connect with

```java
WebSocketConnectOptions options = new WebSocketConnectOptions()
        .setVersion(version)
        .setPort(host)
        .setHost(port)
        .setURI("/")
        .putHeader(HttpHeaders.ORIGIN, origin);
Future<WebSocket> fut = client.webSocket(options);
```

**Comment by vietj** [comment]
See https://github.com/eclipse-vertx/vert.x/issues/4121, this will be backported to Vert.x 4.1.5

**Comment by gillbates** [comment]
thx @vietj .

`
WebSocketConnectOptions options = new WebSocketConnectOptions()
        .setVersion(version)
        .setPort(host)
        .setHost(port)
        .setURI("/")
        .putHeader(HttpHeaders.ORIGIN, "whatever");
Future<WebSocket> fut = client.webSocket(options);
`


so this code will be working in coming 4.1.5 right? 

I mean it 

` Vertx vertx = Vertx.vertx();

        HttpClientOptions options = new HttpClientOptions();
        options.setTrustAll(true).setVerifyHost(false);
        options.setSsl(true);


        HttpClient client = vertx.createHttpClient(options);

        WebSocketConnectOptions webSocketConnectOptions = (WebSocketConnectOptions) new WebSocketConnectOptions().setVersion(WebsocketVersion.V13).setSsl(true).setHost("bsc-ws-node.nariox.org").setPort(443).setURI("/").putHeader(HttpHeaders.ORIGIN, "");


        client.webSocket(webSocketConnectOptions).onSuccess(webSocket -> {
            webSocket.handler(data -> {
                log.debug("data:{}", data);
            });
        }).onFailure(err -> {
            log.debug("error:", err);
        });`


this code will still meet 403 in 4.0.3 .

**Comment by vietj** [comment]
in 4.1.5 the option to disable sending origin will be available

in the mean time you can use the work around by setting a different origin header than the server

**Comment by gillbates** [comment]
> in 4.1.5 the option to disable sending origin will be available
> 
> in the mean time you can use the work around by setting a different origin header than the server

I got it working in 4.1.5, thanks @vietj very much :)
