### ISSUE TITLE
Vertx version 3.9.7, set periodic stops working after 14, 15 days of service uptime.

### ISSUE THREAD

**Issue by navi2589** [eclipse-vertx/vert.x#4118]
We have build cron framework in our service to run some task at particular time durations. 
We have used set vertx.setPeriodic for to schedule these tasks. But we are observing strange behaviour after upgrading to 3.9.7. set periodic stops working after 14, 15 days of service uptime.
Earlier we were on 3.5.2 and everything were working fine

Version 3.9.7

Which version(s) did you encounter this bug ?
Version 3.9.7

Discussion on this bug.
https://groups.google.com/g/vertx/c/meqT7zGYCsc/m/fzRQmwqsAAAJ?utm_medium=email&utm_source=footer

We are using Open JDK Java 15

**Comment by vietj** [comment]
unless there is a reproducer, this feature uses Netty scheduled task mostly.
