### ISSUE TITLE
EventBus body codec lookup performs super class lookup

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#4120]
## Motivation

Vert.x EventBus codec manager resolves a body codec based on the type of the body returned by `getClass()`. Registering a codec to multiple java types based on inheritance is not support and requires the user to register the same codec for each class or interface object with multiple instances of the same codec (since the code name needs to be unique).

## Proposal

Modify the body codec resolution based on the type returned by `getClass()` to lookup the codec with the class or interface defined by the class or its parent class.

- Resolution is performed after system codec resolution, e.g a codec for `Number` will not be used to encode `java.lang.Integer` because there is a system codec for this type
- Binding `java.lang.Object` is forbidden

The change should not introduce regression since this was not supported previously and sending a message with a body resolved with a codec on a parent class of the body would either fail or work because the class for this body is registered already.

## Non goals

- any kind of reification support (e.g `Foo<String>`)
- resolution based on implemented interfaces rather than classes

**Comment by tsegismont** [comment]
Closing as won't fix. We will revisit event bus encoding/decoding in Vert.x 5.

In the meantime, a solution could be to use a default selector https://github.com/eclipse-vertx/vert.x/issues/4365
