### ISSUE TITLE
Example code of Hibernate reactive Docs might create another new Vertx instance

### ISSUE THREAD

**Issue by codingxu97** [eclipse-vertx/vert.x#4139]
### Questions
[Hibernate reactive Docs](https://how-to.vertx.io/hibernate-reactive-howto/) seems non-rigorous.It will create a new Vertx instance when I run the example code,and it might cause some operations to be not thread-safe.

![Warn](https://user-images.githubusercontent.com/35094351/137263472-3b951dc9-7744-47d4-8a5d-355dbba82881.png)

**Comment by tsegismont** [comment]
@Mr-CodingXu actually the issue needs to be opened on [hibernate-reactive-howto](https://github.com/vertx-howtos/hibernate-reactive-howto/issues)
