### ISSUE TITLE
Automatically set `Content-Length` header on HEAD requests

### ISSUE THREAD

**Issue by Mogztter** [eclipse-vertx/vert.x#4150]
#### Describe the feature

Automatically set `Content-Length` header on HEAD requests to what the body size would have been.
The MDN Web Docs suggests that this header should be defined: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD

#### Use cases

I'm using the following code:

```java
response
  .putHeader(HttpHeaders.CONTENT_TYPE, contentType)
  .end(buffer);
```

As far as I know, Vert.x (or Netty?) will not send a body on a HEAD request (even though I'm using `end` with a non-empty buffer) which is great but I would expect the `Content-Length` to be automatically defined on the response since we provide a non-empty buffer.

Please note that we should preserve an explicit value:

```java
response
  .putHeader(HttpHeaders.CONTENT_TYPE, contentType)
  .putHeader(HttpHeaders.CONTENT_LENGTH, 1234)
  .end("");
```

If both a non-empty buffer and an `Content-Length` value are provided, I think we should keep the explicit value.

#### Contribution

I'm willing to contribute this feature. After a quick search, I think I will need to update the following chunks of code:

https://github.com/eclipse-vertx/vert.x/blob/fbd6fba5be06e49382336cba29a3e4caf01597f8/src/main/java/io/vertx/core/http/impl/Http1xServerResponse.java#L685-L714

https://github.com/eclipse-vertx/vert.x/blob/fbd6fba5be06e49382336cba29a3e4caf01597f8/src/main/java/io/vertx/core/http/impl/Http2ServerResponse.java#L473-L475

Related issue: https://github.com/eclipse-vertx/vert.x/issues/2630

> on HEAD method or NOT_MODIFIED (304) status
content-Length should not be set automatically to 0 or this header can be set to what the body size would have been

**Comment by vietj** [comment]
actually currently if you set the header, it will be preserved

**Comment by vietj** [comment]
and I think we should not set a content-length header whatsoever as it can be overridden with the putHeader as it is currently the case and it would be a breaking change.

so if I will close this issue

**Comment by Mogztter** [comment]
> actually currently if you set the header, it will be preserved

Indeed but the `Content-Length` header is not set when using:

```java
response
  .putHeader(HttpHeaders.CONTENT_TYPE, contentType)
  .end(buffer);
```

> and I think we should not set a content-length header whatsoever as it can be overridden with the putHeader as it is currently the case and it would be a breaking change.

My proposal is to set a value only if the value is not explicitly set and the buffer is not empty (see my example above). In other words, we only set a value when (currently) no value is defined. I don't see how it would be a breaking change?

**Comment by vietj** [comment]
tha'ts debatable, some users might use a buffer by mistake and would get a
content length header.

**Comment by Mogztter** [comment]
> tha'ts debatable, some users might use a buffer by mistake and would get a content length header.

As you said it's a mistake so they should probably fix it. They could also use a buffer by mistake on a GET/POST/PUT/DELETE request and, as of today, they will get a content length header.

If we want to prevent mistakes specifically on HEAD requests then `end()` with a non empty buffer should be prohibited. Otherwise, if we allow it then we should be consistent and also set the content length header.

You have the final word, if you disagree then I will close this issue and implement this logic in my code 😉

**Comment by vietj** [comment]
the other concern I have is that on a head request the expected behavior is to not set a content length header in the response and I think that adding an explicit content-length header is a fine way to use it as somebody using it can add a comment in his code saying it will force the content-length to be set in this case, so I think we are going to keep it this way

**Comment by Mogztter** [comment]
Fair enough, closing 👍🏻
