### ISSUE TITLE
vertx.cacheDirBase semantics has changed from vert.x 3.9 to 4.0

### ISSUE THREAD

**Issue by sophokles73** [eclipse-vertx/vert.x#4168]
In vert.x 3.x the value set via the `vertx.cacheDirBase` Java system property had been used to create a temporary directory for resolving files from the classpath as follows:
`"${vertx.cacheDirBase}/file-cache-" + UUID.randomUUID().toString()`

In vert.x 4.x the semantics has changed to now create a directory as:
`"${vertx.cacheDirBase}-" + UUID.randomUUID().toString()`

With vert.x 3.x it was possible to e.g. provide the vert.x process with write access to `/tmp` and set `-Dvertx.cacheDirBase=/tmp` so that vert.x would create a sub-directory under `/tmp` during startup.

Using the same system property value under vert.x 4 will fail during startup if the vert.x process does not have write access to the root file system (`/`) because vert.x will try to create folder `/tmp-UUID` instead of `/tmp/file-cache-UUID` in this case.

The online documentation regarding this system property and how its value is being used is also wrong for versions 3.9.10, 4.0.3, 4.1.6 and 4.2.1

This (breaking) change also hasn't been documented in the Migration Guide for upgrading to vert.x 4.

I see two ways of dealing with this. Either keep the breaking change in the code base and amend the Migration Guide accordingly or reinstate the vert.x 3 behavior in the vert.x 4 code base. I can provide a pull request for any of these options as you see fit.

**Comment by vietj** [comment]
@pmlopes ping

**Comment by pmlopes** [comment]
There was a change in the way we handle the cache many release ago, the new strucuture is defined here:

https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/file/FileSystemOptions.java#L39-L48

If not overriden by the end user the default cache dir is:

```
${TMPDIR:-.}/vertx-cache
```

If there's no user flags active you should end up with:

```
/tmp/vertx-cache-UUID
```

The change happened for a few reasons:

1. multiple vertx applications would override each other cache, so now there's a cache per instance.
2. the cache dir was world readable/writable, now it's process user only read/writable

Indeed the documentation still refers to `.vertx` as default for `-Dvertx.cacheDirBase` and we shoul update it to be a process read/writable directory **prefix** as:

```
-Dvertx.cacheDirBase=/tmp/vertx-cache`
```
