### ISSUE TITLE
Metric vertx_net_client_active_connections not being decreased

### ISSUE THREAD

**Issue by Mersenne255** [eclipse-vertx/vert.x#4185]
### Version

vertx 4.2.0

### Context

Values for gauge metric `vertx_net_client_active_connections` are not being decreased on http connection closed.

### Do you have a reproducer?

https://github.com/Mersenne255/vertx_issue_4185_reproducer
Reproducer submits single http request and ends afterwards.
`vertx_net_client_active_connections` keeps showing value of 1, http metric `vertx_http_client_active_connections` is correctly decreased to 0.

### Extra

JVM 17.0.1

**Comment by tsegismont** [comment]
Can you please file this to the Vert.x Micrometer Metrics repository? Thanks
