### ISSUE TITLE
addCookie method does not replace existing cookie (from browser) and fails when calling RoutingContext.cookieMap()

### ISSUE THREAD

**Issue by narras-oss** [eclipse-vertx/vert.x#4187]
### Version

4.2.1

### Context

We were using (in version 3.9.9) HttpServerResponse.addCookie to set cookie irrespective of whether the cookie was already present (came from browser) and when we iterate over cookies using RoutingContext.cookieMap() we would get a single cookie with that name (i.e. cookie info was updated)
After upgrading to 4.2.1, calling RoutingContext.cookieMap() fails with this exception stack trace

This method assumes cookies are unique by name. However the implementation for addCookie() always adds a cookie to collection (this seems to be a feature request).

```
default Map<String, Cookie> cookieMap() {
    return cookies()
      .stream()
      .collect(Collectors.toMap(Cookie::getName, cookie -> cookie));
  }
```

### Do you have a reproducer?

No. 

### Steps to reproduce

Create sample web app that renders simple form and addCookie("test", "somevalue"). On form submit, call addCookie("test", "anothervalie") to modify the cookie value without removing it first. Then invoke RoutingContext.cookieMap() to get all cookies.

**Comment by narras-oss** [comment]
It would be good to have setCookie or replaceCookie method that would have the previous semantics (add or replace by cookie name) for convenience

**Comment by pmlopes** [comment]
@narras-oss I'm not following the error:

```java
  @Test
  public void testReplaceCookie() throws Exception {
    // receive a HTTP request with a cookie header with value `test=somevalue` 
    testCookies("test=somevalue", req -> {
      // OK
      assertEquals(1, req.cookieCount());
      // is it supposed to fail here? It currently (master) doesn't
      req.response().addCookie(Cookie.cookie("test", "othervalue"));
      Map<String, Cookie> deprecatedMap = req.cookieMap();
      req.response().end();
    }, resp -> {
      // received 1 cookie back (the new one replaced the one received)
      // test=othervalue
      // ?? what was expected?
      List<String> cookies = resp.headers().getAll("set-cookie");
    });
  }
```

**Comment by narras-oss** [comment]
This is the code i am specifically using

```
Cookie cookie = Cookie.cookie("test", "othervalue")
cookie.setSecure(true);
cookie.setPath("/");
routingContext.addCookie(cookie);
```

Stack trace of the exception when calling routingContext.cookieMap() after that is below.

```
Caused by: java.lang.IllegalStateException: Duplicate key XSRF-TOKEN (attempted merging values io.vertx.core.http.impl.CookieImpl@434aa077 and io.vertx.core.http.impl.CookieImpl@4dd9a0b1)
	at java.base/java.util.stream.Collectors.duplicateKeyException(Unknown Source)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Unknown Source)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
	at java.base/java.util.ArrayList$Itr.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at io.vertx.core.http.HttpServerRequest.cookieMap(HttpServerRequest.java:518)
	at io.vertx.ext.web.impl.RoutingContextImpl.cookieMap(RoutingContextImpl.java:282)
	at io.vertx.ext.web.impl.RoutingContextDecorator.cookieMap(RoutingContextDecorator.java:84)
```

**Comment by narras-oss** [comment]
Updated steps:

Add 3 cookies with names "HZN", "CKE_COOKIE" and "XSRF-TOKEN". 
Then when you try to add "a different value for cookie "HZN", it is added again instead of be replaced. The bug seems to be here. When the list has more than one cookie already, cookieUniqueIdComparator return immediately when first one in list does not match with cmp < 0. And it add the cookie in the last statement. This logic seems flawed. It should loop through all cookies in list until it finds a match.

```
public boolean add(ServerCookie cookie) {
    if (cookie == null) {
      throw new NullPointerException("cookie cannot be null");
    }

for (int i = 0; i < list.size(); i++) {
      int cmp = cookieUniqueIdComparator(list.get(i), cookie.getName(), cookie.getDomain(), cookie.getPath());

      if (cmp > 0) {
        // insert
        list.add(i, cookie);
        return true;
      }
      if (cmp == 0) {
        // replace
        list.set(i, cookie);
        return true;
      }
    }
    // reached the end
    list.add(cookie);
```

**Comment by pmlopes** [comment]
The comparator has been fixed, regarding the "extra" methods, I'd recommend using the new API (the `Set<Cookie>`) alternative, and you can perform all the operations that a `Set` allows, add, remove, filter, etc...
