### ISSUE TITLE
Method in `CompositeFuture` missing the wildcard type parameters

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [eclipse-vertx/vert.x#4206]
#### Describe the feature
Some methods in `CompositeFuture` missing the wildcard type parameters, such as:
[static CompositeFuture all(List&lt;Future&gt; futures))](https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/CompositeFuture.java#L75)
[static CompositeFuture any(List&lt;Future&gt; futures)](https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/CompositeFuture.java#L125)

In java, raw use of parameterized class is not suggested, maybe those methods should append a wildcard type parameters?
(Unfortunately `List<Future>` could not assigned to `List<Future<?>>`, as the worst case we need another name for those methods or another `CompositeFuture` interface...)

**Comment by vietj** [comment]
this is a known issue and has already been reported
