### ISSUE TITLE
Have a dedicated exception on timed out connections

### ISSUE THREAD

**Issue by NilsRenaud** [eclipse-vertx/vert.x#4208]
#### Description

Using the Vert.x HTTP client, when a connection takes too long and reaches its time out, we get this exception : 
```
io.vertx.core.VertxException: Connection was closed
```

This does not help in understanding the connection timeout has been reached.

So I would prefer to have either : 
- a dedicated Exception carrying this information (so we can react accordingly)
- an explicit error message to be able to investigate easily

#### Use cases

- Easier bug investigation
- Ability to react to timed out connection accordingly

#### Contribution

I've investigated a bit and found out the issue was at the interface of Netty and Vertx : `io.vertx.core.net.impl.ConnectionBase`. On Idle connection event, Vert.x simply closes the connection.
```java
/**
 * Called by the Netty handler when the connection becomes idle. The default implementation closes the
 * connection.
 * <p/>
 * Subclasses can override it to prevent the idle event to happen (e.g when the connection is pooled) or
 * perform extra work when the idle event happens.
 */
protected void handleIdle(IdleStateEvent event) {
  chctx.close();
}
```

Maybe something like that would be better : 
```java
protected void handleIdle(IdleStateEvent event) {
  chctx.close(new HttpClientTimeoutException("Connection timed out"));
}
```

I may try to implement this solution. Let me know whether my solution sounds interesting to you or not.

**Comment by argenstijn** [comment]
Yes, that would be very nice to be more precise.

**Comment by vietj** [comment]
I don't think it is possible to close this with a reason, the best we could do is log a debug message that mentions the connection will be closed due to timeout.
