### ISSUE TITLE
How to execute get operation using Redis client in synchronization way in Vert.x 4.x 

### ISSUE THREAD

**Issue by yida-lxw** [eclipse-vertx/vert.x#4210]
As the title, I am using caffeine with Vert.x 4.x, I want to load the value from redis and then put it into caffeine cache after the cache vale was out of time. But All provided API in the Redis Client are asynchronous, however the load function in LoadingCache return the value of Generic V, it was synchronization operation, how can I to do that I can load the redis value using the Vert.x Redis Client API? Anyone's response will be greatly appreciated.
Here is my code as blow:
```java
public static <K, V> LoadingCache<K, V> createLoadingCache(String cacheName, Long timeToLiveSeconds, Long timeToIdleSeconds, Integer initialCapacity,
                                                               Integer maximumSize, boolean recordStats) {
        Caffeine<K, V> cacheBuilder = (Caffeine<K, V>) Caffeine.newBuilder();
        if (timeToLiveSeconds != null && timeToLiveSeconds > 0) {
            cacheBuilder.expireAfterWrite(timeToLiveSeconds, TimeUnit.SECONDS);
        }
        if (timeToIdleSeconds != null && timeToIdleSeconds > 0) {
            cacheBuilder.expireAfterAccess(timeToIdleSeconds, TimeUnit.SECONDS);
        }
        
        cacheBuilder.initialCapacity(initialCapacity);
        cacheBuilder.maximumSize(maximumSize);

        if (recordStats) {
            cacheBuilder.recordStats();
        }
        LoadingCache<K, V> loadingCache = cacheBuilder.build(new CacheLoader<K, V>() {
            @Override
            public V load(K key) throws Exception {
                //at here, I want to get a value from redis by synchronization way, how can I to do that?
                return null;
            }
        });
        return loadingCache;
```

**Comment by pmlopes** [comment]
@yida-lxw please open redis related issues in: https://github.com/vert-x3/vertx-redis-client

What you're trying to do is not possible, redis API is asynchronous, so you cannot block for a response. You can run this code on a separate thread and block it there, however it is not a very scalable solution as you need an extra thread for each call.

Perhaps you can look for an asynchronous variant of the cache. Or invert the logic. Create a wrapper for the redis client, that first looks the cache, on miss, goes to the server and caches the result.

**Comment by yida-lxw** [comment]
OK, I have try to use Jedis API to load the cache value from Redis, Even though it is asynchronous, but at least it works and meets my requirements. just deal with it for the time being. At last thanks for your reply.
@pmlopes
