### ISSUE TITLE
OAuth2AwareInterceptor always performs refresh token if user is expired is wrong when using client_credentials type

### ISSUE THREAD

**Issue by argenstijn** [eclipse-vertx/vert.x#4217]
### Questions

The OAuth2WebClient will always do a refresh if the current user is expired. But that is not correct in case of OAuth2FlowType.CLIENT.
See https://datatracker.ietf.org/doc/html/rfc6749#section-4.4.3. So that is no refresh token in this case.

I will like to see that when there is no refresh token or  type OAuth2FlowType.CLIENT that it will just authenticate itself again to get the new token.

The code that needs to be changed is al in OAuth2AwareInterceptor class.

### Version

Vert.X  4.2.1 (quarkus 2.6.1)

### Context

I encountered an exception which looks suspicious while ...

### Do you have a reproducer?

Not needed

* Link to github project/gist

### Steps to reproduce

Not needed

### Extra

* Java 11
* Quarkus 2.6.1
* Windows
* Maven 3.8.1

**Comment by argenstijn** [comment]
In the wrong repository. Should be in the vert.X web.

**Comment by vietj** [comment]
thanks!
