### ISSUE TITLE
when websockets handshake failed, the client send another request from the pooled TCP connection, the server can not be notified.

### ISSUE THREAD

**Issue by Pabears** [eclipse-vertx/vert.x#4218]
### Questions

when WebSockets handshake failed, the client send another request from the pooled TCP connection, the server can not be notified.

### Version

4.2.2

### Context

if a WebSockets handshake failed, the TCP connection becomes unreadable.

### Do you have a reproducer?

**Main.java**
      
      import io.netty.handler.codec.http.HttpResponseStatus;
      import io.vertx.core.Promise;
      import io.vertx.core.Vertx;
      import io.vertx.core.http.HttpServer;
      import io.vertx.core.http.impl.ServerWebSocketImpl;
      
      
      public class Main {
        public static void main(String[] args) {
          // crete a http server
          HttpServer server = Vertx.vertx().createHttpServer();
          // and set ws handler, that always handshake failed.
          server.webSocketHandler(
              ctx -> {
                Promise<Integer> promise = Promise.promise();
                ServerWebSocketImpl webSocket = (ServerWebSocketImpl) ctx;
                webSocket.setHandshake(promise.future());
                Vertx.vertx()
                    .setTimer(
                        1000,
                        id -> {
                          promise.complete(HttpResponseStatus.UNAUTHORIZED.code());
                        });
              });
          server.listen(8080);
        }
      }

**WSTest.java**
      
      import java.util.concurrent.TimeUnit;
      import okhttp3.OkHttpClient;
      import okhttp3.Request;
      import okhttp3.Response;
      import okhttp3.WebSocket;
      import okhttp3.WebSocketListener;
      
      public class WSTest {
        public static void main(String[] args) {
          // create a ws client and try to connect server.
          OkHttpClient client = new OkHttpClient.Builder().readTimeout(10, TimeUnit.SECONDS).build();
          Request request = new Request.Builder().url("ws://localhost:8080/").build();
          test(client, request);
        }
      
        public static void test(OkHttpClient client, Request request) {
          client.newWebSocket(
              request,
              new WebSocketListener() {
      
                @Override
                public void onFailure(WebSocket webSocket, Throwable t, Response response) {
                  t.printStackTrace();
                  try {
                    Thread.sleep(1000);
                  } catch (InterruptedException e) {
                    e.printStackTrace();
                  }
                  test(client, request);
                }
              });
        }
      }

**pom.xml**

    <properties>
      <maven.compiler.source>8</maven.compiler.source>
      <maven.compiler.target>8</maven.compiler.target>
    </properties>
  
    <dependencies>
      <dependency>
        <groupId>io.vertx</groupId>
        <artifactId>vertx-web</artifactId>
        <version>4.2.2</version>
      </dependency>
      <dependency>
        <groupId>com.squareup.okhttp3</groupId>
        <artifactId>okhttp</artifactId>
        <version>3.12.1</version>
      </dependency>
    </dependencies>

### Steps to reproduce

1. run Main.main()
2. run wsTest.main()
3. you got 401
4. wait 10 seconds, you got read timeout😂

### Extra
My service is used behind an Nginx server, they use TCP connection pool connects to me, it has the same issue 😂.

* Anything that can be relevant such as OS version, JVM version
* mac os 12.1 and Linux
* OpenJDK version "1.8.0_312"
OpenJDK Runtime Environment (Zulu 8.58.0.13-CA-macos-aarch64) (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (Zulu 8.58.0.13-CA-macos-aarch64) (build 25.312-b07, mixed mode)

**Comment by vietj** [comment]
ok, I see perhaps the connection should not be closed so it can be used again by the client.

**Comment by vietj** [comment]
what is the issue with read timeout ?

it is actually not clear what the issue is to me.

your client will get a rejection response.

do you mean that the server should close the connection afterward ?

also your code creates 2 instances of vertx and it should use the same.

**Comment by vietj** [comment]
not enough info
