### ISSUE TITLE
Pool can deliver lease with null connection

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#4221]
A race can happen in the pool when it delivers a lease. Leases are created as pool post actions and sometimes can read a connection from a slot that became null in the meantime the post action is executed.

This leads in an NPE in the `HttpClient` that instead should not get non null closed connection, instead of a null connection. (reported here https://github.com/eclipse-vertx/vert.x/issues/4220#issuecomment-1003984163)

**Comment by Sanne** [comment]
hi @vietj , @tsegismont , when do you expect this fix to reach Quarkus ?

Would be great to have it in for version 2.7 (Elektra)

**Comment by vietj** [comment]
we will release 4.2.4 next week and it should be integrated then in Quarkus @Sanne

**Comment by Sanne** [comment]
great, thanks @vietj . Please bear in mind CR1 happens on January 19th, and as usual it's best to reserve some extra 24h to clear CI and PR review delays.
