### ISSUE TITLE
Invalid header name should return an HTTP 400 by default

### ISSUE THREAD

**Issue by NilsRenaud** [eclipse-vertx/vert.x#4228]
### Version

Vert.x 4.2.2

### Context

According to the HTTP/1.1 specification, header names must be encoded in ASCII and a server should return a HTTP 400 on ill-formatted header. This is indeed enforced by [io.vertx.core.http.impl.HttpUtils#validateHeaderName](https://github.com/eclipse-vertx/vert.x/blob/bbda2447357105300701640408b1e93f7420215e/src/main/java/io/vertx/core/http/impl/HttpUtils.java#L846).

On invalid header, the `validateHeaderName` method throws an `IllegalArgumentException`, and this exception is wrapped and eventually handled by [io.vertx.core.http.HttpServerRequest.DEFAULT_INVALID_REQUEST_HANDLER](https://github.com/eclipse-vertx/vert.x/blob/366686696b8837318eb66ea7669b263ecbf4ae47/src/main/java/io/vertx/core/http/HttpServerRequest.java#L63). But since the wrapped exception is a simple `IllegalArgumentException` the method will simply close the underlying TCP connection without sending any HTTP response.

Since this is the default behavior, I would rather expect to check if the exception is an `IllegalArgumentException` and to return a HTTP 400.

### Reproducer

Create a simple http server using vertx : 
```java
Vertx.vertx().createHttpServer()
             .requestHandler(request -> request.response().end("OK"))
             .listen(8282);
```

Then run this command : 
```
$ curl -v http://localhost:8080/ -H "😱: aa"
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
> 😱: aa
>
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
* Closing connection 0
```

**Comment by vietj** [comment]
is there a way to distinguish this error from the vertx perspective ?

**Comment by NilsRenaud** [comment]
Yes, since vert.x creates the error itself we could either : 
- in the default invalid request handler : `if(request.decoderResult().cause() instanceof IllegalArgumentException) {...}`
- since vert.x produces the error, it could produce a more specific error than an `IllegalArgumentException` (something like `HttpBadRequestException` or `HttpException` with bad request somewhere)

But anyway, since we are talking about a "default invalid request handler", I'm not sure why we should do something else rather than returning a HTTP 400 by default. 
IMO, this part of [io.vertx.core.http.HttpServerRequest.DEFAULT_INVALID_REQUEST_HANDLER](https://github.com/eclipse-vertx/vert.x/blob/366686696b8837318eb66ea7669b263ecbf4ae47/src/main/java/io/vertx/core/http/HttpServerRequest.java#L63) : 
```java
if (status == null && HttpMethod.GET == request.method() &&
  HttpVersion.HTTP_1_0 == request.version() && "/bad-request".equals(request.uri())) {
  // Matches Netty's specific HttpRequest for invalid messages
  status = HttpResponseStatus.BAD_REQUEST;
}
if (status != null) {
  request.response().setStatusCode(status.code()).end();
} else {
  request.connection().close();
}
```
should be replaced by : 
```java
if (status == null) {
    status = HttpResponseStatus.BAD_REQUEST;
}
request.response().setStatusCode(status.code()).end();
```

What do you think about this last solution ?

**Comment by vietj** [comment]
I do agree, however the connection should remain closed : when the netty handler produces such error it internally switches to the `BAD_MESSAGE` state which cannot be recovered from:

```java
        case BAD_MESSAGE: {
            // Keep discarding until disconnection.
            buffer.skipBytes(buffer.readableBytes());
            break;
        }
```

**Comment by vietj** [comment]
See https://github.com/eclipse-vertx/vert.x/pull/4229
