### ISSUE TITLE
Link in documentation is incorrect

### ISSUE THREAD

**Issue by sigzero** [eclipse-vertx/vert.x#4238]
In the "Templates" section here:

https://vertx.io/docs/vertx-web/java/#_templates

There is a link in "Please consult the MVEL templates documentation for how to write MVEL templates." where the link is pointing to an invalid resource.

Points to:  http://mvel.codehaus.org/MVEL+2.0+Templating+Guide
Should be:  http://mvel.documentnode.com/

**Comment by tsegismont** [comment]
Thanks for the reporting this issue.
