### ISSUE TITLE
ClusteredEventBus/ClusteredMessage : Missing codec failure is silently ignored

### ISSUE THREAD

**Issue by d-william** [eclipse-vertx/vert.x#4243]
### Version

4.2.3

### Context

When using message sending/consuming mechanism with Clustered Vertx instances, if the MessageCodec used by the sender is not registered in the consumer's EventBus then a failure will be set in ClusteredMessage state (OK) [ClusteredMessage#L154](https://github.com/eclipse-vertx/vert.x/blob/11ab144725e551be591118831377101015e1392c/src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredMessage.java#L154)

But this failure is only traced and in default behavior it will be silently ignored : [ClusteredMessage#L278](https://github.com/eclipse-vertx/vert.x/blob/11ab144725e551be591118831377101015e1392c/src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredMessage.java#L278)

I do not know if it it would be revelant to handle this failure by the Handler specified in `MessageConsumer.exceptionHandler(Handler<Throwable>);` but it does not.

Same behavior with 'Invalid wire protocol version' failure : [ClusteredMessage#L141](https://github.com/eclipse-vertx/vert.x/blob/11ab144725e551be591118831377101015e1392c/src/main/java/io/vertx/core/eventbus/impl/clustered/ClusteredMessage.java#L141)

#### Consumer.java
```java
ClusterManager mgr = new HazelcastClusterManager();
VertxOptions options = new VertxOptions().setClusterManager(mgr);
Vertx.clusteredVertx(options, result -> {
    if (result.succeeded()) {
        Vertx vertx = result.result();
        EventBus bus = vertx.eventBus();
        // MY_CUSTOM_CODEC is not registered in EventBus
        MessageConsumer<Object> consumer = bus.consumer("test");
        consumer.handler(event -> System.out.println(event.body()));
        consumer.exceptionHandler(event -> {
            throw new RuntimeException(event); // Failure not handled
        });
    }
    else {
        throw new RuntimeException(result.cause());
    }
});
```

#### Sender.java
```java
MessageCodec<String, String> MY_CUSTOM_CODEC = ...;
ClusterManager mgr = new HazelcastClusterManager();
VertxOptions options = new VertxOptions().setClusterManager(mgr);
Vertx.clusteredVertx(options, result -> {
    if (result.succeeded()) {
        Vertx vertx = result.result();
        EventBus bus = vertx.eventBus();
        bus.registerCodec(MY_CUSTOM_CODEC);
        DeliveryOptions deliveryOptions = new DeliveryOptions().setCodecName(MY_CUSTOM_CODEC.name());
        MessageProducer<String> sender = bus.sender("test", deliveryOptions);
        Future<Void> future = sender.write("Hello world");
        future.onComplete(result1 -> {
            if (result1.succeeded()) System.out.println("Message sent");
            else throw new RuntimeException(result1.cause());
        });
    }
    else throw new RuntimeException(result.cause());
});
```

### Steps to reproduce

1. Run Consumer.java
2. Run Sender.java
3. See that there are no error/failure handled

**Comment by glassfox** [comment]
Same behavior when you send/request/publish DataObject with exception in constructor. example:
``` java
@DataObject
public class MyModel {
  public MyModel(JsonObject json){
    throw new RuntimeException("Oops");
  }
  public JsonObject toJson(){
    return new JsonObject();
  }
}
```

**Comment by tsegismont** [comment]
This is most likely not going to happen in production, but in development. When there is reply address, it is ok to notify the sender, but should we notify the consumer, which one to choose if there are more than one registered?

The best thing to do is to log this fatal error at `ERROR` level.

**Comment by glassfox** [comment]
Log is good enough.
