### ISSUE TITLE
get transaction information  just by `SqlConnection`

### ISSUE THREAD

**Issue by zhangtianxiao** [eclipse-vertx/vert.x#4259]
`val transaction =  sqlConnection().begin().await()`
I hope 'SqlConnection' can disclose 'transaction()' and 'autoCommit().
No extra place is needed to store ` transaction`
Thank you

**Comment by tsegismont** [comment]
Can you please report the issue to https://github.com/eclipse-vertx/vertx-sql-client?

Don't forget to include details about what you would like, it's not clear yet
