### ISSUE TITLE
ConnectionManager for HttpClient disregards proxyOptions

### ISSUE THREAD

**Issue by zekronium** [eclipse-vertx/vert.x#4281]
### Context

Since the merge of my PR I realized that wrong connections are picked when changing proxy per request [as per this PR](https://github.com/vert-x3/vertx-web/pull/2033)

During my investigation my assumption is that due to [EndpointKey](https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/EndpointKey.java) not checking proxyOptions in equals methods causes the wrong connection to be matched which leads to the wrong proxy being used

### Steps to reproduce

1. Create WebClient (without proxy)
2. Create a request and set a proxy to it and send
3. Create another request and set a different proxy and send
4. WebClient will use the first proxy (or any proxy that it already has a connection with that matches other EndPoint requirements)

Proposed Fix in [EndpointKey.java](https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/EndpointKey.java)
```java
  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    EndpointKey that = (EndpointKey) o;
    return ssl == that.ssl && serverAddr.equals(that.serverAddr) && peerAddr.equals(that.peerAddr) && proxyOptions.equals(that.proxyOptions);
  }

  @Override
  public int hashCode() {
    int result = ssl ? 1 : 0;
    result = 31 * result + peerAddr.hashCode();
    result = 31 * result + serverAddr.hashCode();
    result = 31 * result + proxyOptions.hashCode();
    return result;
  }
```

**Comment by vietj** [comment]
this is actually expected, one should use always the same proxy with the same host

**Comment by vietj** [comment]
well actually this is debatable, but it was thought that ppl would use the same proxy for the same host

**Comment by vietj** [comment]
i.e I'm not against changing that

**Comment by zekronium** [comment]
I think in quite a few cases for different uses "rotating" your proxy might come in handy even on the same host.

The way it is now its impossible to do so since the input is disregarded

**Comment by zekronium** [comment]
Hash code check might not suffice for this to work properly.

Due to copied objects of the proxyOptions, even while applying the same proxy it can produce a different hashcode itself. 

equals() on proxyOptions likely should be implemented to compare actual host values to improve how this works.

**Comment by zekronium** [comment]
This has been fixed by another PR, I assume safe to close?
