### ISSUE TITLE
JsonObject.put() throws UnsupportedException when initialized with Immutable Map from Kotlin

### ISSUE THREAD

**Issue by rennyahernandez** [eclipse-vertx/vert.x#4294]
### Version

Vertx Core 4.2.5

### Context

I encountered an exception when using JsonObject class from vertx and Kotlin. Specifically, when initializing a `JsonObject()` with an immutable Map.

### Do you have a reproducer?

`JsonObject(mapOf("foo" to "bar")).put("this", "that")`

throws the following exception stacktrace: 

```
java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractMap.put(AbstractMap.java:209)
	at io.vertx.core.json.JsonObject.put(JsonObject.java:642)
	at io.vertx.ext.mongo.impl.codec.json.JsonObjectCodec.generateIdIfAbsentFromDocument(JsonObjectCodec.java:52)
	at io.vertx.ext.mongo.impl.codec.json.JsonObjectCodec.generateIdIfAbsentFromDocument(JsonObjectCodec.java:26)
```

### Extra

* Kotlin JVM 1.6.10

**Comment by vietj** [comment]
that's normal, you should copy the map before

**Comment by rennyahernandez** [comment]
> that's normal, you should copy the map before

thanks for your response.  Just a question: Why is it normal? If I'm not mistaken, the nature of the passed map definition should not be a precondition for any exposed method to fail. Why not to internally copy the parameter map into a HashMap in order to always work without errors?
