### ISSUE TITLE
The log disk is full.Thread of eventloop disappears 

### ISSUE THREAD

**Issue by fanjiwang1992** [eclipse-vertx/vert.x#4295]
### Questions

The log disk is full.Thread of eventloop disappears 

### Version

version is 3.9.8

### Context

I encountered an exception which looks suspicious while ...

### Do you have a reproducer?

A reproducer is a simple project hosted on GitHub (or another forge supporting git clone operation) that has a build file that can be executed to reproduce the issue.

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

* Link to github project/gist

### Steps to reproduce

1. ...
2. ...
3. ...
4. ...

### Extra

* Anything that can be relevant such as OS version, JVM version

**Comment by fanjiwang1992** [comment]
The error log cannot be viewed because the log disk is full.

**Comment by fanjiwang1992** [comment]
We found a missing thread through the thread stack.

**Comment by fanjiwang1992** [comment]
vert.x-eventloop-thread

**Comment by tsegismont** [comment]
Without a small reproducer we can only guess. Most probably the an Error has been thrown which made the thread exit the event loop and stop.
