### ISSUE TITLE
ServerResponse endHandler is not invoked when sending a file via HTTP 1

### ISSUE THREAD

**Issue by DemonicTutor** [eclipse-vertx/vert.x#4302]
### Version

VertX 4.2.5 - did not check prior versions

### Context

Using HTTP 1 / 1.1 the endHandler of ServerResponse is not invoked.

### Steps to reproduce

```
Vertx.vertx().createHttpServer()
  .requestHandler(request -> request.response().endHandler(nothing -> System.err.println("never happens")).sendFile("file.txt"))
  .listen();
```

### Extra

* openjdk 17

**Comment by Dogs-toeight** [comment]
Hello, I don't know if my problem is the same as yours. 
I use Vertx 2.4.5, and create a http server:
`public static void main(String[] args) {
        HttpServer server = Vertx.vertx(new VertxOptions()).createHttpServer();

        server.requestHandler(request -> {

            // This handler gets called for each request that arrives on the server
            HttpServerResponse response = request.response();
            response.putHeader("content-type", "text/plain");

            // Write to the response and end it
            response.end("Hello World!");
        });

        server.listen(8080);
    }`
The code comes from official documentation, I tried to connect to the request but the browser got a prompt: ERR_EMPTY_RESPONSE.

**Comment by Dogs-toeight** [comment]
> Hello, I don't know if my problem is the same as yours. I use Vertx 2.4.5 Jdk 11, and create a http server:
> 
> ```
> public static void main(String[] args) {
>         HttpServer server = Vertx.vertx(new VertxOptions()).createHttpServer();
>         server.requestHandler(request -> {
> 
>             // This handler gets called for each request that arrives on the server
>             HttpServerResponse response = request.response();
>             response.putHeader("content-type", "text/plain");
> 
>             // Write to the response and end it
>             response.end("Hello World!");
>         });
> 
>         server.listen(8080);
>     }
> }
> ```
> 
> The code comes from official documentation, I tried to connect to the request but the browser got a prompt: ERR_EMPTY_RESPONSE.

I changed the Vertx version to 4.2.4 and code started working.

**Comment by DemonicTutor** [comment]
@Dogs-toeight Hey! 

no that's definitively  not related. 
just from your snipped i have no clue whats going wrong - for me it works perfectly fine using VertX 4.2.5 and OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)

**Comment by Dogs-toeight** [comment]
> @Dogs-toeight Hey!
> 
> no that's definitively not related. just from your snipped i have no clue whats going wrong - for me it works perfectly fine using VertX 4.2.5 and OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8) browser pointing to: `http://localhost:8080/`

@DemonicTutor Hey!
I change jdk to 17.0.2. Obviously, that doesn't seem to be the problem. I change vertx version to 4.2.4. It's work.
I have submitted an issue [#4312](https://github.com/eclipse-vertx/vert.x/issues/4312), It would be my pleasure if you could come and give me your opinion.Thanks.
