### ISSUE TITLE
No connection timeout for WebSocket

### ISSUE THREAD

**Issue by inno-steffg** [eclipse-vertx/vert.x#4310]
### Version

vert.x-core 4.2.5

### Context

I was trying to increase stability of a connection made with websockets. One of the measures is, to reliably connect to the remote server or to retry when the connection cannot be established within a specific period of time, i.e. a classic timeout.

I have found one scenario, where none of the available options work: If the server accepts the TCP connection, but does not respond in any way.

I've tried:
- HttpClientOptions.connectTimeout
- HttpClientOptions.idleTimeout
- WebSocketConnectOptions.requestTimeout

### Do you have a reproducer?

Demonstrating unit test:

* https://gist.github.com/inno-steffg/ded493b7cb6150ed42ff2b25b2258822

### Steps to reproduce

1. Start a netsocket server, which accepts any connection request, but does not respond in any way.
2. Try to connect with a Vert.x http client websocket request to this server: no async result is happening ever.

### Extra

* Windows 10 64bit
* openjdk version "17.0.2" 2022-01-18
* OpenJDK Runtime Environment (build 17.0.2+8-86)
* OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

**Comment by vietj** [comment]
see https://github.com/eclipse-vertx/vert.x/issues/4323
