### ISSUE TITLE
In the TCP program of Vert.x, how to judge the idle timeout of the client?

### ISSUE THREAD

**Issue by jr981008** [eclipse-vertx/vert.x#4316]
Use setIdleTimeout to set the client idle timeout time, but in the NetSocket .closeHandler method, how to confirm that the client's disconnection is due to the client idle timeout?

**Comment by jr981008** [comment]
It is easy to overwrite handleIdle method  calling registered error handler in netsockimple when idletimeout

@Override
  protected void handleIdle() {
    handleException(new TimeoutException());
    chctx.close();
  }

**Comment by vietj** [comment]
have you tried setting an exception handler to see if there is a TimeoutException coming through ?

otherwise the idle event might be propagated with `NetSocketInternal#eventHandler`

**Comment by vietj** [comment]
alright I just tested it and you can cast NetSocket to NetSocketInternal and set an event handler that will receive the Netty idle event.

be careful becuase you need to release any reference counted object when it happens

**Comment by jr981008** [comment]
ok，It looks a bit like  strange.

**Comment by vietj** [comment]
```java
      ((NetSocketInternal)so).eventHandler(evt -> {
        if (evt instanceof IdleStateEvent) {
          //
        }
        ReferenceCountUtil.release(evt);
      });
```

**Comment by jr981008** [comment]
Thank you very much for your patient answer.
Sorry I forgot to provide the version used, vertx 3.9.8,
 there is no such method  NetSocketInternal#eventHandler.
Is there any other solution for this version?  @vietj

**Comment by vietj** [comment]
no, the 3.9 branch is still supported for a year but for bug fixes and not features.

you should upgrade to Vert.x 4

**Comment by abdallah-sameer96** [comment]
@vietj i used **setIdleTimeout** in NetServerOptions with websocket and it return null status code of the close handler,
so it gives me response with **1006 Abnormal Closure No close frame was received.**
i need to return normal close with close frame.
