### ISSUE TITLE
monitoring  metrics

### ISSUE THREAD

**Issue by 1ssqq1lxr** [eclipse-vertx/vert.x#4322]
### Questions

Do not use this issue tracker to ask questions, instead use one of these [channels](https://vertx.io/community/). Questions will likely be closed without notice.

Some monitoring indicators are missing. For example, net only has the number of connections, and others do not,
### Version

Which version(s) did you encounter this bug ?

### Context

I encountered an exception which looks suspicious while ...

### Do you have a reproducer?

A reproducer is a simple project hosted on GitHub (or another forge supporting git clone operation) that has a build file that can be executed to reproduce the issue.

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

* Link to github project/gist

### Steps to reproduce

1. ...
2. ...
3. ...
4. ...

### Extra

* Anything that can be relevant such as OS version, JVM version

**Comment by tsegismont** [comment]
Which metrics SPI implementation do you use in your project?

Micrometer Metrics implementation has more than just the number of connections for [net client](https://vertx.io/docs/vertx-micrometer-metrics/java/#_net_client) or [net server](https://vertx.io/docs/vertx-micrometer-metrics/java/#_net_server).

**Comment by 1ssqq1lxr** [comment]
net server only connections ，other empty



---Original---
From: "Thomas ***@***.***&gt;
Date: Wed, Mar 30, 2022 23:35 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [eclipse-vertx/vert.x] monitoring  metrics (Issue #4322)




 
Which metrics SPI implementation do you use in your project?
 
Micrometer Metrics implementation has more than just the number of connections for net client or net server.
