### ISSUE TITLE
HTTP Request Handler not called on a duplicated context when requests are pipelined

### ISSUE THREAD

**Issue by cescoffier** [eclipse-vertx/vert.x#4325]
### Questions

When the HTTP server receives pipelined requests, the first request is invoked on a duplicated context, but not the second one. 

### Version

4.2.6

### Context

This is related to https://github.com/quarkusio/quarkus/issues/24626.

**Comment by cescoffier** [comment]
Trying to reproduce it with Vert.x directly, but so far I have failed. So, it may be due to having multiple verticles.

**Comment by vietj** [comment]
thanks for reporting this @cescoffier
