### ISSUE TITLE
The word 'map' misspelled as 'msp' in SharedData.java

### ISSUE THREAD

**Issue by pradeesh-kumar** [eclipse-vertx/vert.x#4336]
The word 'map' misspelled as 'msp' in SharedData.java -> getLocalMap(String name)

<img width="474" alt="image" src="https://user-images.githubusercontent.com/29938245/163973941-7f703bc1-4ff5-4f48-802a-1c7392ba3881.png">

https://github.com/eclipse-vertx/vert.x/blob/0cd6af9e9b3e5787533b38a193726bd5b4912ee9/src/main/java/io/vertx/core/shareddata/SharedData.java#L192

**Comment by vietj** [comment]
fixed thanks
