### ISSUE TITLE
Http error code 431 in case of Http/2

### ISSUE THREAD

**Issue by klalit** [eclipse-vertx/vert.x#4342]
### Issue

In the request using HTTP/2 when header size is more 8192 but less than maxHeaderSize , the status code returned is 431

### Version

Which version(s) did you encounter this bug ? 4.2.4

### Context

in Server enable setUseAlpn(true) and setMaxHeaderSize(16384) , client uses http/2 and request headerSize=12000. The response returned is 431

**Comment by vietj** [comment]
can you provide a reproducer project ?

**Comment by klalit** [comment]
@vietj - sure, working on to fix it too
