### ISSUE TITLE
Introduce a `module-info` or an automatic module name

### ISSUE THREAD

**Issue by dmlloyd** [eclipse-vertx/vert.x#4343]
#### Describe the feature

The `vert.x` core module does not have a JPMS module identifier, making it difficult to compile or use projects which depend on this one when the project in question is fully or partially modularized.

Either a `module-info` descriptor should be added, or an automatic module name should be assigned. I would recommend a module identifier of `io.vertx.core`.

If a `module-info` descriptor is added, it can be done in a couple different ways:

* Add a `module-info.java` source file which is compiled by `javac` (this requires that the project is built using Java 9 or later, and also requires a special plugin or utility to ensure that the `module-info.class` in the JAR is correctly updated with all of the necessary attributes; the `jar` utility is normally responsible for doing this, however Maven's archiver does not use `jar` (it's a reimplementation))
* Use a third-party tool to generate the `module-info.class` file directly with all of the correct information, without using `javac`
   * [ModiTect](https://github.com/moditect/moditect)
   * My own [module-info](https://github.com/dmlloyd/module-info) tool

**Comment by vietj** [comment]
Vert.x does have an automatic module name in the META-INF/MANIFEST.MF file as described here https://github.com/vert-x3/wiki/wiki/JPMS

**Comment by dmlloyd** [comment]
Ah, I didn't realize that. Thanks!
