### ISSUE TITLE
Possible resource leak with Vertx.createSharedWorkerExecutor

### ISSUE THREAD

**Issue by JojOatXGME** [eclipse-vertx/vert.x#4345]
The thread pools created by **`Vertx.createSharedWorkerExecutor(…)`** might not be shut down when Vert.x is closed. I tested version **4.2.4** and **4.2.7** on Windows with Adopt OpenJDK 15.0.1+9. I noticed the issue because a test suite which is starting and stopping a lot of Vertx instances run out of memory. There were more than 10.000 threads alive at this point. Note that our usage of `createSharedWorkerExecutor` might also have been problematic because we were calling the method whenever we needed the executor, instead of storing the executor in a field. We changed that, which already fixes the issue for us, but I thought the potential leak might still be worth reporting.

```java
@Test
void testLeak() {
  Thread[] threads = new Thread[2];
  Vertx vertx = Vertx.vertx();
  try {
    vertx.createSharedWorkerExecutor("LeakTest").executeBlocking(promise -> {
      threads[0] = Thread.currentThread();
      promise.complete();
    });
    vertx.createSharedWorkerExecutor("LeakTest").executeBlocking(promise -> {
      threads[1] = Thread.currentThread();
      promise.complete();
    });
  }
  finally {
    runGarbageCollection();
    vertx.close();
  }
  assertFalse(threads[0].isAlive()); // <-- Fails, threads are still alive
  assertFalse(threads[1].isAlive());
}

private static void runGarbageCollection() {
  WeakReference<?> ref = new WeakReference<>(new Object());
  while (ref.get() != null) {
    System.gc();
    System.runFinalization();
    try { Thread.sleep(5); } catch (InterruptedException ignore) {}
  }
}
```

The issue exists because `CloseFuture` uses a `WeakHashMap` to store the closeables.
https://github.com/eclipse-vertx/vert.x/blob/cd37704fe62f07361d536d72d4108cf87be3a1eb/src/main/java/io/vertx/core/impl/CloseFuture.java#L62-L64
This means if we are not keeping a reference to the return value, the `WorkerExecutorImpl` might be garbage collected before `close` is called. Usually, `WorkerExecutorImpl.close` would call `VertxImpl.SharedWorkerPool.close` which would decrement the reference counter and shut down the thread pool if the reference counter reaches zero.

Note that at least two instances of `WorkerExecutorImpl` for the same pool must be garbage collected to reproduce the issue. `VertxImpl.deleteCacheDirAndShutdown` will also call `VertxImpl.SharedWorkerPool.close`, although it has never incremented the reference counter.
https://github.com/eclipse-vertx/vert.x/blob/cd37704fe62f07361d536d72d4108cf87be3a1eb/src/main/java/io/vertx/core/impl/VertxImpl.java#L811

PS: While looking through the source code, I noticed that `createSharedWorkerExecutor` might pass the wrong `CloseFuture` to the constructor of `WorkerExecutorImpl`.
https://github.com/eclipse-vertx/vert.x/blob/cd37704fe62f07361d536d72d4108cf87be3a1eb/src/main/java/io/vertx/core/impl/VertxImpl.java#L1050-L1052

**Comment by tsegismont** [comment]
We'll look into it, thank you

**Comment by vietj** [comment]
thanks I'm on it

**Comment by vietj** [comment]
Can you have a look at https://github.com/eclipse-vertx/vert.x/pull/4352 @JojOatXGME ?
