### ISSUE TITLE
MongoClient::renameCollection(....)

### ISSUE THREAD

**Issue by M4ikT** [eclipse-vertx/vert.x#4347]
#### Describe the feature

`io.vertx.ext.mongo.MongoClient` should implement 

`Publisher<Void> renameCollection(MongoNamespace newCollectionNamespace);`
`Publisher<Void> renameCollection(MongoNamespace newCollectionNamespace, RenameCollectionOptions options);`
`Publisher<Void> renameCollection(ClientSession clientSession, MongoNamespace newCollectionNamespace);`
`Publisher<Void> renameCollection(ClientSession clientSession, MongoNamespace newCollectionNamespace, RenameCollectionOptions options);`

which is already implemented in `com.mongodb.reactivestreams.client.MongoCollection`.

#### Use cases

- rename a collection to replace data after `bulkWrite` etc commands

#### Contribution
I'm able to implement this feature.

**Comment by vietj** [comment]
can you recreate this issue in https://github.com/vert-x3/vertx-mongo-client ? thanks
