### ISSUE TITLE
Filename too long: java.nio.file.FileSystemException: /tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/...

### ISSUE THREAD

**Issue by c3sivanarayanagaddam** [eclipse-vertx/vert.x#4348]
### Version
vertx-core- 3.8.3

### Context
I see the following error from vertx for requests with `content-type: application/x-www-form-urlencoded`. 

java.nio.file.FileSystemException: /tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/vertx-cache/file-cache-2c514c50-8dbd-45b4-944d-89e84f778c1b/tmp/libjansi-64-1.8.so: File name too long
    at io.vertx.core.file.impl.FileResolver.unpackFromFileURL(FileResolver.java:184) ~[vertx-core-3.8.3.jar:3.8.3]
    at io.vertx.core.file.impl.FileResolver.unpackFromFileURL(FileResolver.java:192) ~[vertx-core-3.8.3.jar:3.8.3]
    at io.vertx.core.file.impl.FileResolver.unpackFromFileURL(FileResolver.java:192) ~[vertx-core-3.8.3.jar:3.8.3]
    at io.vertx.core.file.impl.FileResolver.unpackFromFileURL(FileResolver.java:192) ~[vertx-core-3.8.3.jar:3.8.3]
    at io.vertx.core.file.impl.FileResolver.unpackFromFileURL(FileResolver.java:192) ~[vertx-core-3.8.3.jar:3.8.3]
    at io.vertx.core.file.impl.FileResolver.unpackFromFileURL(FileResolver.java:192) ~[vertx-core-3.8.3.jar:3.8.3]
    at io.vertx.core.file.impl.FileResolver.unpackFromFileURL(FileResolver.java:192) ~[vertx-core-3.8.3.jar:3.8.3]
    at io.vertx.core.file.impl.FileResolver.unpackFromFileURL(FileResolver.java:192) ~[vertx-core-3.8.3.jar:3.8.3]

Not sure whether this issue is with vertx? or am I missing something?

**Comment by tsegismont** [comment]
This version of Vert.x is no longer maintained. Please upgrade to 3.9, or even better, 4.2.

**Comment by harinath2007** [comment]
@c3sivanarayanagaddam  How did u resolve this issue?  i am facing the same issue.. Appreciate if you can share how did u resolve this. Thanks
