### ISSUE TITLE
Add Documentation Describing The Duality of Future/Promise

### ISSUE THREAD

**Issue by Olamshin** [eclipse-vertx/vert.x#4366]
Following up on this [conversation](https://groups.google.com/g/vertx/c/VmPYS0JPXDc/m/PXfi99mBAAAJ) from the user group, we should emphasize the duality promise/future. Perhaps at this [location](https://vertx.io/docs/vertx-core/java/#_future_results).

**Comment by tsegismont** [comment]
Would you like to contribute this @Olamshin ? I can guide you in the process (no biggies).
