### ISSUE TITLE
Make more Vert.x classes with a `close()` function implement `Closeable`

### ISSUE THREAD

**Issue by ShreckYe** [eclipse-vertx/vert.x#4395]
#### Describe the feature

Make more Vert.x classes like `Vertx`, `HttpServer`, `HttpClient`, etc. with a `close()` function, or even all such classes, implement the `io.vertx.core.Closeable` interface.

#### Use cases

This would make it easier to add some more extensions for such `Closeable`s, for example in Kotlin, a `suspend` version of `kotlin.use` (like Java's try-with-resources syntax) for all Vert.x `Closeable`s.

#### Contribution

This doesn't look too difficult to me, either the Vert.x Maintainers can implement this or I am willing to do this too. However, I do have one question if I were to do this: is there a difference between these 2 types of function types below for `close`, and which one is better and should be made the single source of truth?
```java
void close(Promise<Void> completion);
```
```java
Future<Void> close();
```

**Comment by vietj** [comment]
vertx closeable is more like an internal interface that should have never been exposed like it is now.

java closeable is not asynchronous unfortunately.

**Comment by vietj** [comment]
if you need something for kotlin perhaps we can make a kotlin extension for that ?

**Comment by ShreckYe** [comment]
Thanks. This is exactly I want, but without implementing `io.vertx.core.Closeable` we may have to add many extensions for each one of them (`Vertx`, `HttpServer`, etc.). For an example, see [this `Vertx.use` function in a pull request I also submitted yesterday](https://github.com/vert-x3/vertx-lang-kotlin/pull/222/files#diff-162b76dc534138518a237d9a8ed527f1b3ecaca67385ea7d4357b6eff203f699R166-R176).

**Comment by vietj** [comment]
alright closing this then
