### ISSUE TITLE
[Q] Reusing BodyHandler

### ISSUE THREAD

**Issue by dodalovic** [eclipse-vertx/vert.x#4398]
I'm trying to create something like

```kotlin
router.route("foo").handler(BodyHandler.create().setBodyLimit(1024*1024))
router.route("bar").handler(BodyHandler.create().setBodyLimit(1024*1024))
router.route("baz").handler(BodyHandler.create().setBodyLimit(1024*1024))
```

Would it be ok to call `BodyHandler.create().setBodyLimit(1024*1024)` only once in the app, and reuse it all over the place I need it?
Or, more general, can I reuse handler instances?

The question has also been posted [@ stackoverflow](https://stackoverflow.com/questions/72566822/reusing-bodyhandler-instance)

**Comment by tsegismont** [comment]
Answered by Alexey https://stackoverflow.com/a/72587440/2133695
