### ISSUE TITLE
TLSv1.3 support

### ISSUE THREAD

**Issue by camproto** [eclipse-vertx/vert.x#4408]
#### Describe the feature

As a developer I would like to have TLSv1.3 support out of the box. V1.3 reduce the allowed cipher suites to only some, which are safe. 

I think it is not supported yet, becuase it's missing in TCPSSLOptions.DEFAULT_ENABLED_SECURE_TRANSPORT_PROTOCOLS.

A support in Vert.x reduce boilerplate code to configure the cipher suites manually and reduce the possibility of a wrong configuration as well. 

#### Use cases

Very helpful in environments where v1.3 is required.

#### Ho to work around manually the correct way?

How to achieve V1.3 manually? Is it enough to reduce the enabled secure transport protocols to v1.3 like this?
`        HttpServerOptions options = new HttpServerOptions()
                .setSsl(true)
                .removeEnabledSecureTransportProtocol("TLSv1")
                .removeEnabledSecureTransportProtocol("TLSv1.1")
                .removeEnabledSecureTransportProtocol("TLSv1.2")
                .addEnabledSecureTransportProtocol("TLSv1.3")`

How to handle the cipher suites? 
Unlike the protocols there is no removeCipherSuites method present?

**Comment by vietj** [comment]
TLSv1.3 is not supported on JDK 1.8 which vertx uses, it requires at least Java 11 or to use TC native with OpenSSL, so for now it needs to be manually added

**Comment by vietj** [comment]
See https://github.com/eclipse-vertx/vert.x/issues/4414

**Comment by camproto** [comment]
Thank you @vietj! Setting the protocol to just v1.3 a valid cipher suite TLS_AES_128_GCM_SHA256 is selected automatically. Therefore no manual configuration of the correct cipher suites is needed. 
Maybe the TLSv1.3 handling is it worth to mention it in the documentation.

**Comment by vietj** [comment]
I think you are right for the doc, can you submit a patch ?
