### ISSUE TITLE
HttpClient send a http2 request but the AsyncResult blocked and nothing be executed

### ISSUE THREAD

**Issue by flatychen** [eclipse-vertx/vert.x#4418]
### Questions

When the htt2 server reset/close the connection after the three-way (or 3-step) handshake immediately ,at that time use HttpClient(HttpClientImpl)  send a http2 request , the send parameter of  **AsyncResult** will be block

### Version

4.2.1+

### Context

When http2 server reset/close the connection after the three-way (or 3-step) handshake and the **it have not receive the http2 setting frame from client** , the AsyncResult of HttpClient will be block and print log "**Connection evicted**" 

### Steps to reproduce

1. Preparing the http2 server. In netty we need close the channel after channelActive, as following:
  
```
  @Override
  public void channelActive(ChannelHandlerContext ctx) throws Exception {
    log.info("channelActive start close!");
    ctx.channel().close();
  }
```
  
2. Using httpclient send a http2(H2_PRIOR_KNOWLEDGE) request , the connection can be establish success.and then will print
 log "Connection evicted" and AsyncResult will be block.

### Extra
  I read some source code of http2 client and found that the method channelInactive in VertxHttp2ConnectionHandler will be called  
in this issue , but connectFuture seems not called, it seems the root cause.
  I also make a simple wrokaround as following , but it will be cause the AsyncResult failed and i think it should be success(connection established success) in this issue.

```
  @Override
  public void channelInactive(ChannelHandlerContext chctx) throws Exception {
    if (connection != null) {
      if (removeHandler != null) {
        removeHandler.handle(connection);
      }
      super.channelInactive(chctx);
    //  connectFuture.setFailure(new HttpClosedException());  wrokaround  of call connectFuture.setFailure
      connection.handleClosed();
    } else {
      super.channelInactive(chctx);
    }
  }

```

**Comment by vietj** [comment]
do you have a reproducer test ?

**Comment by flatychen** [comment]
Hi , the reproducer steps can be visit the repo https://github.com/flatychen/vertx-http2-test. thanks!
