### ISSUE TITLE
How to limit the buffer size of the event bus and control the upstream producer rate？

### ISSUE THREAD

**Issue by jr981008** [eclipse-vertx/vert.x#4433]
Migrate from vertx3.X to 4.X， I encountered some difficulties。

      Vertx vertx = Vertx.vertx(new VertxOptions().setPreferNativeTransport(true));
        MessageProducer<Object> sender = vertx.eventBus().sender();
        **sender.setWriteQueueMaxSize()**  //how replace these in vertx4.x
        **if (sender.writeQueueFull()) {**
            // log and control the upstream producer rate 
        }else{
            sender.write()
        }
        MessageConsumer<String> consumer = vertx.eventBus().consumer();
        consumer.setMaxBufferedMessages();

**Comment by vietj** [comment]
you can replace this using a request/response instead of a simple message and count the number of inflight requests you have to queue them when the number of inflight requests is greater than the max size.

**Comment by magicprinc** [comment]
It is really sad, that MessageProducer doesn’t implement WriteStream anymore. You can’t implement back-pressure with EventBus using standard methods.

**Comment by magicprinc** [comment]
BTW.. MessageConsumer limits number of messages somehow… Can we use its internal mechanism?
