### ISSUE TITLE
Test failed due to timeout on the latest version

### ISSUE THREAD

**Issue by apanasevich** [eclipse-vertx/vert.x#4435]
After an upgrade from version 3.9.13 to the latest version 4.3.2 I have faced with some hanging tests, that worked fine before.

Here is a simple test, which reproduces the behaviour https://github.com/apanasevich/vertx-latch-example

Vert.x changed its logic. What went wrong?

**Comment by apanasevich** [comment]
Actually, the problem is reproduced even on version 4.0.0. So, something has been changed at that time

**Comment by tsegismont** [comment]
Starting with Vert.x 4, there is a single event loop context that is used when you schedule operations on the vertx instance on a non-vert.x thread.

So, in your test, Vert.x is blocked at https://github.com/apanasevich/vertx-latch-example/blob/518379d9f599562fa83ea87af32b0f50787cede5/src/test/java/org/example/LatchTest.java#L35

And thus cannot process this task https://github.com/apanasevich/vertx-latch-example/blob/518379d9f599562fa83ea87af32b0f50787cede5/src/test/java/org/example/LatchTest.java#L26-L29
