### ISSUE TITLE
 Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "vert.x-eventloop-thread-1"

### ISSUE THREAD

**Issue by Boris-code** [eclipse-vertx/vert.x#4456]
1|java -ja | Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "vertx-blocked-thread-checker"
1|java -ja | 
1|java -ja | Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "mysql-cj-abandoned-connection-cleanup"
1|java -ja | Exception in thread "Dedup0" java.lang.OutOfMemoryError: Java heap space
1|java -ja | java.lang.OutOfMemoryError: Java heap space
1|java -ja | Exception in thread "Dedup0" java.lang.OutOfMemoryError: Java heap space
1|java -ja | java.lang.OutOfMemoryError: Java heap space
1|java -ja | java.lang.OutOfMemoryError: Java heap space
1|java -ja | Exception in thread "Dedup0" java.lang.OutOfMemoryError: Java heap space
1|java -ja | java.lang.OutOfMemoryError: Java heap space
1|java -ja | 
1|java -ja | Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "commons-pool-EvictionTimer"
1|java -ja | 
1|java -ja | Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "vert.x-eventloop-thread-1"
1|java -ja | Exception in thread "vert.x-acceptor-thread-0" java.lang.OutOfMemoryError: Java heap space
1|java -ja | Exception in thread "Thread-4" java.lang.NoClassDefFoundError: io/vertx/core/file/impl/FileSystemImpl$11
1|java -ja |    at io.vertx.core.file.impl.FileSystemImpl.delete(FileSystemImpl.java:875)
1|java -ja |    at io.vertx.core.file.impl.FileCache.deleteCacheDir(FileCache.java:130)
1|java -ja |    at io.vertx.core.file.impl.FileCache.lambda$runHook$0(FileCache.java:86)
1|java -ja |    at java.base/java.lang.Thread.run(Thread.java:829)
1|java -ja | Caused by: java.lang.ClassNotFoundException: io.vertx.core.file.impl.FileSystemImpl$11
1|java -ja |    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
1|java -ja |    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
1|java -ja |    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
1|java -ja |    ... 4 more
1|java -ja | Exception in thread "Thread-4" java.lang.NoClassDefFoundError: io/vertx/core/file/impl/FileSystemImpl$11
1|java -ja |    at io.vertx.core.file.impl.FileSystemImpl.delete(FileSystemImpl.java:875)
1|java -ja |    at io.vertx.core.file.impl.FileCache.deleteCacheDir(FileCache.java:130)
1|java -ja |    at io.vertx.core.file.impl.FileCache.lambda$runHook$0(FileCache.java:86)
1|java -ja |    at java.base/java.lang.Thread.run(Thread.java:829)
1|java -ja | Caused by: java.lang.ClassNotFoundException: io.vertx.core.file.impl.FileSystemImpl$11
1|java -ja |    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
1|java -ja |    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
1|java -ja |    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
1|java -ja |    ... 4 more

**Comment by tsegismont** [comment]
Please reopen only if you can provide details about how to reproduce (small runnable application, jvm startup settings, ...etc)
