### ISSUE TITLE
Zk-based AsyncMap get() call fails silently 

### ISSUE THREAD

**Issue by yifangl** [eclipse-vertx/vert.x#4457]
### Questions

The get() method of the AsyncMap used in our app sometimes just times out without going into the callback handler. As a result we are not able to handle it in the callback handler. It looks like a silent failure and the get() call just hangs until the vertx times out. 

### Version

Current version under use is 3.9.13

### Context

Our code is using the Zk-based [AsyncMap](https://vertx.io/docs/apidocs/io/vertx/core/shareddata/AsyncMap.html) as follow:

 asyncMap.get(currentNodeId, new Handler<AsyncResult<String>>() {
        @Override
        public void handle(AsyncResult<String> findNodeInfoResult) {
          if (findNodeInfoResult.failed()) {
            LOG.error("Failed to find nodeInfo by live node id {}", currentNodeId, findNodeInfoResult.cause());
          } else {
            LOG.debug("Fetched nodeInfo {} for {}.", findNodeInfoResult.result(), currentNodeId);
            }
      });

And through the log we can see sometimes the get() just fail silently and times out, neither the LOG.error(), nor the LOG.debug() can be seen in the server log. We were expecting in case of this, it should at least go to the failed() case and so we expect to see logs like LOG.error("Failed to find nodeInfo by live node id {}", currentNodeId, findNodeInfoResult.cause());

### Do you have a reproducer?

This is currently in our private repo so cannot paste the reproducer here. But we are just using the basic get() method. It should be reproduced by setting up a zk-based AsyncMap and call get() on a periodic basis.  (Our use case calls it every 5 sec.)

Wondering if this a known issue? Could you help to review and suggest best way to solve this?

**Comment by vietj** [comment]
see https://github.com/vert-x3/vertx-zookeeper/issues/129
