### ISSUE TITLE
Support for TLS "clientAuth" option based on server SNI hostname

### ISSUE THREAD

**Issue by pavelarnost** [eclipse-vertx/vert.x#4466]
In browser environment, it's useful to have a dedicated domain for TLS certificate authentication (eg. https://login.microsoftonline.com vs https://certauth.login.microsoftonline.com).

There is currently no support for setting "clientAuth" option in HttpServer based on SNI hostname so the beforementioned scenario can only be implemented with separate TCP port or IP address.

It would be great to have "clientAuth" SNI support similar to keyManagerMapper() in KeyCertOptions or some other method to "tap" into configureEngine() in SslHelper.

**Comment by vietj** [comment]
We are working on a refactoring and cleanup + SPI of the SSLHelper : https://github.com/eclipse-vertx/vert.x/actions/runs/2974388290

The SPI allows to build a custom Netty `SslContext` and could be used to implement this with delegation and override the client auth based on the server name I think.

**Comment by vietj** [comment]
It would look like:

```java
    HttpClientOptions options = new HttpClientOptions().setSsl(true)
      .setSslEngineOptions(new JdkSSLEngineOptions() {
        @Override
        public SslProvider provider() {
          SslProviderImpl impl = new SslProviderImpl(io.netty.handler.ssl.SslProvider.JDK, false);
          return new SslProvider() {
            @Override
            public SslContextFactory contextFactory(Set<String> enabledCipherSuites, List<String> applicationProtocols) {
              return new DelegatingSslContextFactory(impl.contextFactory(enabledCipherSuites, applicationProtocols)) {
                private String serverName;
                @Override
                public SslContextFactory serverName(String serverName) {
                  this.serverName = serverName;
                  return this;
                }
                @Override
                public SslContext create() throws SSLException {
                  switch (serverName) {
                    case "https://login.microsoftonline.com":
                      super.clientAuth(io.netty.handler.ssl.ClientAuth.REQUIRE);
                      break;
                  }
                  return super.create();
                }
              };
            }
          };
        }
      });
```

**Comment by vietj** [comment]
Now it would look the same but without `SslProvider` that has been removed so the the engine options directly returns a `SslContextFactory`.

**Comment by pavelarnost** [comment]
It looks great. Is this planned for 4.4?

**Comment by vietj** [comment]
it is planned for 4.3.4

**Comment by vietj** [comment]
it is planned for 4.3.4 actually, as there is no breaking change.
