### ISSUE TITLE
HttpClient send multipart request can exhaust heap space

### ISSUE THREAD

**Issue by geoand** [eclipse-vertx/vert.x#4473]
### Version

4.3.3

### Context

When using HttpClient from multiple event loops theads that all make a "send multipart" request to the same target, then it's possible to exhaust the heap memory.
This happens because the same `Connection` is used for all requests, which leads to requests coming from a different thread than the one attached to the connection being handled like this:

https://github.com/eclipse-vertx/vert.x/blob/4.3.3/src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java#L517.

This in turn can cause the task queue of the event loop to pile up requests very quickly when the multipart requests contains a large file.

### Do you have a reproducer?

I have reproduced this in Quarkus using the Reactive REST Client which uses HttpClient under the hood. I can supply this reproducer or try and create a pure Vert.x one if needed.

### Extra

Here is a screenshot of what a memory dump looks like when this problem occurs:

![Screenshot from 2022-09-08 08-56-25](https://user-images.githubusercontent.com/4374975/189045334-034aa396-3659-41e1-877d-e2114419a0f0.png)

**Comment by geoand** [comment]
My initial thought about how to address this would be to provide an option to **not** use the connection pool i.e. every request would receive its own connection.

**Comment by cescoffier** [comment]
The root of the issue is the affinity between the connection and the target endpoint. The bodies can be mixed up if you have two concurrent calls (with multipart) using the same HTTP client, and both calls are targeting the same endpoint.

Indeed, both calls will get the same connection from the pool, while 1) the connection is not available (there is a call in progress), 2) both calls write their body into the same connection.

**Comment by vietj** [comment]
can you provide a vertx reproducer @geoand ?

**Comment by vietj** [comment]
Does this situation happens under flow control ? i.e the part that writes buffers check that the stream is writable ?

**Comment by vietj** [comment]
so the issue happens because the pending tasks will update the flow control window and since they are not executed, it fails to provide the right feedback. Is that right ?

**Comment by geoand** [comment]
That sounds correct

**Comment by vietj** [comment]
I see more clearly now what is happening, the buffers are sitting between the two event-loops and not yet written so the connection actually now nothing about them and fails to provide correct feedback.

I think I can make a reproducer myself for the case.

As workaround you can limit yourself flow control with a counter, e.g you have a counter that is incremented for every write and decremented when the write is performed, until we find provide a patch for this.

**Comment by geoand** [comment]
> I see more clearly now what is happening, the buffers are sitting between the two event-loops and not yet written so the connection actually now nothing about them and fails to provide correct feedback.

👍🏼 

> I think I can make a reproducer myself for the case.

If you don't have one today, I will do it tomorrow

**Comment by vietj** [comment]
Such situation would also happen with bare Netty, so I think we might end up with a similar fix in Vert.x HTTP client when the write is delayed for an event-loop hop.

**Comment by geoand** [comment]
>> As workaround you can limit yourself flow control with a counter, e.g you have a counter that is incremented for every write and decremented when the write is performed, until we find provide a patch for this.

> Good idea, I'll try it

I introduced a custom `Pipe` to our codebase that does exactly this. It's definitely not pretty, but it should take care of this corner case for us.

**Comment by pantinor** [comment]
@vietj Can this change account for a stream reset frame (with protocol error code) when sending multipart form?  I am doing a basic client test and seeing the reset happening.  My testing indicates it started when this 4.3.4 wass released that is why was looking at this ticket.  This is my query on the group channel  https://groups.google.com/g/vertx/c/94Ag-UhJuvI
