### ISSUE TITLE
Http2UpgradedClientConnection leaks instances of UpgradeRequestHandler in case of unsuccessful protocol upgrade

### ISSUE THREAD

**Issue by adets** [eclipse-vertx/vert.x#4476]
### Version

The issue is present at least in Vert.x 4.2.7 and 4.3.3.

### Problem Description

In case Vert.x HTTP client is setup for HTTP/2 and allows for clear text HTTP/2 upgrade (`.setProtocolVersion(HttpVersion.HTTP_2).setHttp2ClearTextUpgrade(true)`) then in case server rejects the upgrade such client leaks instances of `io.vertx.core.http.impl.Http2UpgradedClientConnection.UpgradingStream.writeHead(...).UpgradeRequestHandler` upon each subsequent HTTP request. This is 100% reproducible as long as Vert.x client is configured with the options above, connection is over clear text HTTP/1.1 (possibly 1.0 also - I didn't test this) and server part does not support upgrade to HTTP/2 (e.g. any NGINX). Leak of these handlers means that there is (1) a memory leak - by the handler itself and all the objects referenced from it, which are a lot, and (2), which is **WAY** more noticeable, hugely increased CPU utilization - after each subsequent request over this connection a new handler is added to pipeline and then all these accumulated handler instances are invoked to process all events, eventually client reaches 100% CPU utilization as there are hundreds of thousands of handlers.

I believe the issue is caused by the fact that `Http2UpgradedClientConnection` adds a new instance of `UpgradeRequestHandler` to Netty pipeline upon each request (see https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/Http2UpgradedClientConnection.java#L319) but seems to remove this instance from the pipeline only in case of receiving `HttpResponseHead` (see https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/Http2UpgradedClientConnection.java#L159) which it seems to **never** receive according to my testing: it was always either an instance of DefaultHttpResponse, in case upgrade failed, or an instance of a buffer, in case protocol successfully switched to HTTP/2. Apart from the fact that this branch of code seems to be never invoked I'm also not sure why it tries to add "Connection: close" header - the fact that upgrade failed doesn't mean that we want to close the connection???

### Potential Fix

I admit I don't 100% understand how all of this is supposed to work, so what I describe below may be not the best way to fix the issue, still it indeed fixes the problem for me with the servers that don't support clear text HTTP/2 and still allows HTTP/1.1 -> HTTP/2 upgrade to work with the servers that do support it. All Vert.x tests also pass with the change.

Change:
```
          if (evt == HttpClientUpgradeHandler.UpgradeEvent.UPGRADE_SUCCESSFUL) {
            // Upgrade handler will remove itself and remove the HttpClientCodec
            pipeline.remove(upgradingConnection.channelHandlerContext().handler());
          }
```
To:
```
          if (evt == HttpClientUpgradeHandler.UpgradeEvent.UPGRADE_SUCCESSFUL) {
            // Upgrade handler will remove itself and remove the HttpClientCodec
            pipeline.remove(upgradingConnection.channelHandlerContext().handler());
          } else if (evt == HttpClientUpgradeHandler.UpgradeEvent.UPGRADE_REJECTED) {
            pipeline.remove(this);            
          }
```

### Additional Random Thoughts
`Http2UpgradedClientConnection` class name is confusing as it is not necessary upgraded. :-) Also, it seems that there is no way to disable clear text HTTP/2 at all: if HTTP/2 is enabled then it is always enabled for **both** clear text and SSL versions. For clear text there is a choice between connecting in HTTP/2 right away (`setHttp2ClearTextUpgrade(false)`) or via upgrade process (`setHttp2ClearTextUpgrade(true)`) but there is no way to disable it for clear text completely and allow HTTP/2 only for HTTPS connections.

**Comment by vietj** [comment]
looks like a good fix, can you provide a PR with a test ?

**Comment by adets** [comment]
I can try to create a simple unit test with mocks that just verifies that pipeline.remove(this) is called from inside of UpgradeRequestHandler.userEventTriggered. This will be quite a lot of work though as there are no unit tests at all for Http2UpgradedClientConnection and any of its nested classes, so I can't just add one more test case. :-) Please, let me know if this is the kind of test you want.

As for some kind of a functional test, I'm not sure if this is possible at all. First problem is that Vert.x server part does handle protocol upgrade just fine, it always switches to HTTP/2, so the problem doesn't happen. Second, even if it would have been possible to cause server side to not switch to HTTP/2 somehow - this bug doesn't cause any immediate visible **functional** effects - everything works, just a leak of handlers happens.

**Comment by vietj** [comment]
I'm working on a fix
