### ISSUE TITLE
Should I release the ReferenceCounted msg in a custom net server?

### ISSUE THREAD

**Issue by yazinnnn** [eclipse-vertx/vert.x#4492]
### Questions

i has bootstrapped a vertx netserver and put a **Netty** codec(like HttpObjectDecoder) in channel pipeline.

After it running for a period of time, the ConnectionBase report `Cannot reserve 4194304 bytes of direct buffer memory`, 
and netty `ResourceLeakDetector` report `SEVERE: LEAK: ByteBuf.release() was not called before it's garbage-collected.`

Should i release the message's refrence count in vertx handler? 
And is that add the `-XX:MaxDirectMemorySize=XXm` vm options useful?

### Version

4.3.3

### Do you have a reproducer?

https://gist.github.com/yazinnnn/cf455487615f2d37cb5f573866e3c4f4

### Extra

* 5.15.57-2-MANJARO
* openjdk version "17.0.2" 2022-01-18 LTS

**Comment by tsegismont** [comment]
If you want to integrate Vert.x with netty decoders properly, you will find useful info here: https://vert-x3.github.io/advanced-vertx-guide/index.html#integrating-netty
