### ISSUE TITLE
Obsolete information on Embedding Vert.x on the web

### ISSUE THREAD

**Issue by dmikurube** [eclipse-vertx/vert.x#4496]
(Not about the Vert.x software implementation, but an issue about documentation.)

----

I was trying to find information about embedding Vert.x in Java application, then found this page: http://vert-x.github.io/embedding_manual.html

But unfortunately, it turned out that the information is obsolete (about Vert.x v2) after some discussion on the Google Groups.

I wonder if the obsolete information is removed (or at least shown to be "This page is obsolete!"), and we could see an up-to-date information.

Related post on the Google Groups:
* https://groups.google.com/g/vertx/c/HAhl5dJ2PMw

Thanks.

**Comment by dmikurube** [comment]
If then, I wondered if it is removed, or marked as "Obsolete - do not read this" explicitly. :)

**Comment by vietj** [comment]
now this website redirects to vertx.io
