### ISSUE TITLE
Extra fields while deserialization of request body as Json.

### ISSUE THREAD

**Issue by kailash** [eclipse-vertx/vert.x#4506]
### Questions

Extra fields are appended in Json, while using `routingContetext().body().asJsonObject()`. is this something done purposefully or some bug in the serialization/deserialization of the body as JsonObject()?

I am not sure whether its a bug or this behavior is expected.

### Version

4.3.2

### Context

While getting my request body `asJsonObject()` through RoutingContext, I encountered some extra fields returned in JsonObject. 

### Do you have a reproducer?

Sending below Json as a request body in my REST API and trying to get this JSON in my API verticle as JSON using `routingContext.body().asJsonObject()`
```
{
    "type": "Query",
    "entities": [
        {
            "id": "abc"
        }
    ],
    "geoQ": {
        "geometry": "Point",
        "coordinates": [
            72.886055,
            21.224406
        ],
        "georel": "within",
        "geoproperty": "location"
    }
}

```

The below json is returned  for `routingContext.body().asJsonObject();` call

```
{
  "type": "Query",
  "entities": [
    {
      "id": "abc"
    }
  ],
  "geoQ": {
    "geometry": "Point",
    "coordinates": [
      72.886055,
      21.224406
    ],
    "georel": "near;maxDistance=100",
    "geoproperty": "location"
  },
  "ids": [
    "abc"
  ]
}

```

> noticed extra ids field, while just calling `routingContext.asString()` returns correct json string

### Extra

Jdk 11,

**Comment by pmlopes** [comment]
@kailash I can't seem to reproduce the issue you're observing:

```java
  @Test
  public void testJsonGeoExtraIds() throws Exception {
    router.clear();
    router.route().handler(BodyHandler.create());
    Buffer buffer = Buffer.buffer("{\n" +
      "    \"type\": \"Query\",\n" +
      "    \"entities\": [\n" +
      "        {\n" +
      "            \"id\": \"abc\"\n" +
      "        }\n" +
      "    ],\n" +
      "    \"geoQ\": {\n" +
      "        \"geometry\": \"Point\",\n" +
      "        \"coordinates\": [\n" +
      "            72.886055,\n" +
      "            21.224406\n" +
      "        ],\n" +
      "        \"georel\": \"within\",\n" +
      "        \"geoproperty\": \"location\"\n" +
      "    }\n" +
      "}");
    router.route().handler(rc -> {
      try {
        assertNotNull(rc.body().asJsonObject());
        assertFalse(rc.body().asJsonObject().containsKey("ids"));
        rc.end();
      } catch (IllegalStateException e) {
        // should not reach here!
        rc.fail(500);
      }
    });
    testRequest(HttpMethod.POST, "/", req -> {
      req.setChunked(true);
      req.putHeader("content-type", "application/json");
      req.write(buffer);
    }, 200, "OK", null);
  }
```

Can you make a test case that shows it?

**Comment by kailash** [comment]
Hi @pmlopes,

Upon further investigation, I found that one of my handlers is appending this field `ids` directly to the request body before actual processing/validations take place.

I was under the impression that body/jsonobject will be immutable.

The issue is resolved by using a copy of the body in handlers.

Thanks, for helping 
we can close this issue.

**Comment by pmlopes** [comment]
@kailash, no the body isn't `final` you can see the buffer as "final" as updating it using the right api will clear any parsed representations (json/text). However the parsing helpers will be mutable objects as they are internally a simple `Map`.

What you probably saw in the past (3.x) was that it looked by the json views were immutable, because, we would never cache calls to `toJsonXYZ()` which would mean that JSON parsing was happening every single time these methods were called. This was a performance and resource waste that has been improved with the new `.body()` API.
