### ISSUE TITLE
h2c bug

### ISSUE THREAD

**Issue by cole-dda** [eclipse-vertx/vert.x#4512]
### Questions

Do not use this issue tracker to ask questions, instead use one of these [channels](https://vertx.io/community/). Questions will likely be closed without notice.

### Version

vertx 4.3.4

netty 4.1.84-final

### Context
Http1xUpgradeToH2CHandler.java

<img width="667" alt="screenshot_5479" src="https://user-images.githubusercontent.com/1077830/197077606-d2c9b793-6305-46a2-bce0-b9c6445a8e75.png">

should add:
request.headers.remove('connection');
request.headers.remove('upgrade');

<img width="816" alt="screenshot_5480" src="https://user-images.githubusercontent.com/1077830/197077875-0c7abf2f-c356-4fc1-ba42-30c9ff3b9b6d.png">

### Do you have a reproducer?

        HttpClientOptions options = new HttpClientOptions().setProtocolVersion(HttpVersion.HTTP_2);
        Vertx vertx = Vertx.vertx();
        vertx.createHttpClient(options).request(HttpMethod.GET,8888,"127.0.0.1" ,"/api/f1")

**Comment by vietj** [comment]
thanks that has been applied in master
