### ISSUE TITLE
please update jackson version

### ISSUE THREAD

**Issue by richard20200101** [eclipse-vertx/vert.x#4514]
### Questions
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/61450147/197137996-9400323e-f884-475d-9ba7-f53f8281199a.png">

Do not use this issue tracker to ask questions, instead use one of these [channels](https://vertx.io/community/). Questions will likely be closed without notice.

### Version
4.3.4
Which version(s) did you encounter this bug ?

### Context

I encountered an exception which looks suspicious while ...

### Do you have a reproducer?

A reproducer is a simple project hosted on GitHub (or another forge supporting git clone operation) that has a build file that can be executed to reproduce the issue.

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

* Link to github project/gist

### Steps to reproduce

1. ...
2. ...
3. ...
4. ...

### Extra

* Anything that can be relevant such as OS version, JVM version

**Comment by pmlopes** [comment]
@richard20200101 which modules are you speaking of? Most vert.x modules have a dependency on jackson-core which isn't affected by the CVE. This should be addressed on a module by module basis

**Comment by richard20200101** [comment]
[image: image.png]
My project inheritance uses this dependency management

**Comment by vietj** [comment]
which jackson version is that @richard20200101

**Comment by pmlopes** [comment]
You're seening the version being resolved from the "bom" included from `vertx-dependencies`. To avoid the CVE you should explicitly define your version as `2.13.4.1`.

Once https://github.com/vert-x3/vertx-dependencies/pull/107 gets merged, you can just rely on the automatic version from the BOM.
