### ISSUE TITLE
Vertx sliced buffers can be overwritten by channel writes

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#4517]
Vertx sends `ByteBuf` duplicates when a `Buffer` is written to a pipeline. In some cases, such buffer can be appended to by the `SslHandlerCoalescingBufferQueue` because a duplicate of a slice will be a duplicate and not a slice itself, leading to buffer corruption.

**Comment by liubao68** [comment]
This modification changed the meaning of the method in Buffer.  Maybe the java doc for Buffer should be updated also, or a new method should be added. 

```
  /**
   * Returns the Buffer as a Netty {@code ByteBuf}.
   *
   * <p> The returned buffer is a duplicate that maintain its own indices.
   */
  @GenIgnore(GenIgnore.PERMITTED_TYPE)
  ByteBuf getByteBuf();
```

**Comment by vietj** [comment]
this method should not actually be public, however we can update the
javadoc for it
