### ISSUE TITLE
Will DI and AOP related functions be added later?

### ISSUE THREAD

**Issue by zhouzhou19950825** [eclipse-vertx/vert.x#4522]
#### Read me

Will DI and AOP related functions be added later?

#### Describe the feature

Micronaut and quarkus frameworks already support DI and AOP . Will vertx consider adding DI and AOP later as the best non-blocking framework?

Thanks!

**Comment by tsegismont** [comment]
It's not planned. If you want to use Vert.x reactive features with DI, consider trying Quarkus. See

https://quarkus.io/guides/getting-started-reactive
https://quarkus.io/guides/vertx-reference

and a few others guide on the same website
