### ISSUE TITLE
"405 Method Not Allowed" response not adding allow header

### ISSUE THREAD

**Issue by VenkateswaranJ** [eclipse-vertx/vert.x#4526]
As per this document, https://vertx.io/docs/vertx-web/java/#_route_match_failures Vert.x-Web will signal a 405 error If a route matches the path but doesn’t match the HTTP Method, but as per Mozilla document https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405 response should contain `allow` header. Is there any reason why it's not added in response?

It only adds `content-length` header

Version - 4.3.4

**Comment by vietj** [comment]
can you create the issue here https://github.com/vert-x3/vertx-web ?
