### ISSUE TITLE
oAuth2 callback is not mounted

### ISSUE THREAD

**Issue by horak90** [eclipse-vertx/vert.x#4536]
Vertx version: 4.3.4

I am having an application using the oAuth2 authentication and after migration to Vertx 4.3.4 I got an issue with the callback. When the IDP redirects to the callback url I have HTTP 404. 

After investigation, I found out the the callback route is never mounted because of the `order` variable in `OAuth2AuthHandlerImpl` class. After setting manually the `order` to 1 `((OAuth2AuthHandlerImpl) oAuth2Handler.getDelegate()).onOrder(1);` everything seems to work fine. 

My code:

1) The creation of the oAuth2 handlers since I might have multiple IDP configurations (so one handler by IDP), in my case it does not work even if there is only one IDP configuration

```
Observable.fromIterable(config().getJsonArray("IDP_CONFIGURATIONS"))
                    .cast(JsonObject.class)
                    .flatMapSingle(idpConfig -> {
                        var oAuth2Options = getOAuth2Options(idpConfig);
                        var authProvider = createAuthProvider(oAuth2Options);
                        var idpName = idpConfig.getString("name", "default");

                        return jwkIfSetup(authProvider, oAuth2Options)
                                .andThen(Single.just(Pair.of(idpName, getHandler(router, authProvider, idpConfig))));
                    })
                    .collectInto(new HashMap<String, OAuth2AuthHandler>(), (map, pair) -> map.put(pair.getKey(), pair.getValue()))
```

2) The method which actually creates the handler

```
OAuth2AuthHandler getHandler(Router router, OAuth2Auth authProvider, JsonObject idpConfig) throws MalformedURLException {
        var callbackPath = idpConfig.getString("callbackPath");
        var callbackURL = new URL(callbackPath);
        var oAuth2Handler = OAuth2AuthHandler.create(vertx, authProvider, callbackPath)
                .setupCallback(router.get(callbackURL.getPath()))
                .extraParams(new JsonObject()
                        .put(REDIRECT_URI_PARAM, callbackPath)
                        .put(OAUTH2_SCOPE_HTTP_PARAM, idpConfig.getString(OAUTH2_SCOPE_PARAM, DEFAULT_OAUTH2_SCOPE))
                );

        return oAuth2Handler;
    }
```

3) The way how the handler is added to the route

```
public void addOpenid(Map<String, OAuth2AuthHandler> oauth2Handlers) {
        router.route("/openid/auth").handler(routingContext -> {
            var idpName = routingContext.request().getParam("name");
            var oAuth2AuthHandler = oauth2Handlers.get(idpName);
            oAuth2AuthHandler.handle(routingContext);
        });
        router.route("/openid/auth").method(GET).handler(OpenidLoginHandler.create(vertx, config));
   }
```

Thank you

**Comment by pmlopes** [comment]
This issue has been forgotten because it's on the wrong repo. It should have been added to vertx-web

**Comment by pmlopes** [comment]
The issue is now tracked on vertx-web.

**Comment by horak90** [comment]
Thank you for moving the issue, you understood well, the idea is to have a possibility to be able to authenticate with multiple IDPs, so the authentication request contains the IDP name which has a specific handler with the appropriate settings for IDP. I will try to use the `MultiTenantHandler` but even if I tried to pass directly the handler to the route without the map (so I got only one IDP) it was not working.
