### ISSUE TITLE
Which ACID performance is better, Infinispan or Ignite?

### ISSUE THREAD

**Issue by zhouzhou19950825** [eclipse-vertx/vert.x#4553]
Now I am choosing between Ignit and Infinispan cache mechanisms, which one is better?

**Comment by tsegismont** [comment]
Vert.x has a cluster manager for both data grid solutions and I believe they are equally functional / performant.

Then perhaps you may have other requirements for your projects that make you choose one or the other. Read carefully the documentation and talk with the respective communities.
