### ISSUE TITLE
Junit google toolbox library ParallelSuite hangs when we migrate Vertx 3.9.7 to 4.3.2 in a Java Vertx project

### ISSUE THREAD

**Issue by sac10nikam** [eclipse-vertx/vert.x#4559]
### Questions

Junit google toolbox library ParallelSuite hangs when we migrate Vertx 3.9.7 to 4.3.2 in a java Vertx project

### Version

4.3.2

### Context

Junit google toolbox library ParallelSuite fails when we migrate Vertx 3.9.7 to 4.3.2

### Do you have a reproducer?

NA

### Steps to reproduce

Any Vertx based java project having Vertx 4.3.2 + Junit suit using ParallelSuite from Google junit toolbox library

### Extra

* Anything that can be relevant such as OS version, JVM version
MacOs

**Comment by sac10nikam** [comment]
@marekscholle Can you please help here?

**Comment by vietj** [comment]
does it still happen ? we need more info here like a reproducer or a stack trace dump, please reopen with more info if that still happens
