### ISSUE TITLE
Add pop to InboundBuffer

### ISSUE THREAD

**Issue by He-Pin** [eclipse-vertx/vert.x#4574]
#### Describe the feature

Add pop/pollLast method to InboundBuffer.

#### Use cases

If I want to make use it with overlfowStrategy: DropTail\DropHead...
#### Contribution

Yes

**Comment by vietj** [comment]
why would you need that ? it remains an internal class. just asking it
seems legit.

**Comment by He-Pin** [comment]
I see, i was expectibg it as a public api, thanks.
