### ISSUE TITLE
nonProxyHost property ignored in Copy Constructor of ClientOptionsBase

### ISSUE THREAD

**Issue by bkoripalli** [eclipse-vertx/vert.x#4575]
### Version

Which version(s) did you encounter this bug ? 
4.3.2

### Context
nonProxyHostList value overrides to null by creating new WebClientOptions from existing WebClientOptions

```
WebClientOptions options = new WebClientOptions();
options.setNonProxyHosts(Arrays.asList("10.*","localhost"));
options.setTrustAll(true);
ProxyOptions proxyOptions = new ProxyOptions();
    proxyOptions.setHost("proxy-server");
    proxyOptions.setPort(3128);
options.setProxyOptions(proxyOptions);

//check log level and set log activity
WebClientOptions  finalOptions = new WebClientOptions(options).setLogActivity(false);
finalOptions .getNonProxyHosts() //returns null
```

https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/net/ClientOptionsBase.java#L51-L73

**Comment by vietj** [comment]
do you mind contributing a fix for this ?

**Comment by bkoripalli** [comment]
I will do

**Comment by bkoripalli** [comment]
@vietj done here is the pull request https://github.com/eclipse-vertx/vert.x/pull/4579

**Comment by vietj** [comment]
thanks for reporting this
