### ISSUE TITLE
Add Promise#completeWith(Future)

### ISSUE THREAD

**Issue by He-Pin** [eclipse-vertx/vert.x#4580]
#### Describe the feature

Promise.completeWith(future);
Promise.tryCompleteWith(future);

#### Use cases

This Api would be useful when inside a handler.

#### Contribution
Yes

**Comment by He-Pin** [comment]
Ok, I can use `future.onComplete(promise))` for this too.

**Comment by vietj** [comment]
yes you should use this API on the future.
