### ISSUE TITLE
Adding an isClose method to Vertx or VertxInternal

### ISSUE THREAD

**Issue by cescoffier** [eclipse-vertx/vert.x#4634]
There are no methods that let you know whether the vert.x instance has been closed. This leads to an issue when you have HTTP servers that you close explicitly (in parts of the application not aware of Vert.x being closed). 

The problem is that in this case, the server `close` callback is never called because the event loop is shut down and so, there is nothing to call the handler. If the code uses a latch to wait for the graceful shutdown, the latch will never be released.

**Comment by vietj** [comment]
I think we could expose a closeFuture for Vert.x instance which could be queried

**Comment by vietj** [comment]
Perhaps also we could think of having a degraded callback done on a specific thread in this case.

**Comment by vietj** [comment]
Actually this is not the right future that is exposed by we can improve that I think

**Comment by vietj** [comment]
Well it is good enough, you can do `((VertxInternal)vertx).closeFuture().future().completed()``

**Comment by cescoffier** [comment]
`((VertxInternal)vertx).closeFuture().future().completed()`` should work for me. I will check in my case.

**Comment by cescoffier** [comment]
Works! Thanks!
