### ISSUE TITLE
Website http://vertx.io/

### ISSUE THREAD

**Issue by bardiademon** [eclipse-vertx/vert.x#4642]
Hi,
Why does the website not open? Is the problem mine or yours?

[http://vertx.io/](http://vertx.io/)

**Comment by tsegismont** [comment]
Thank you for heads-up. We're aware of the issue and it's been reported to the Eclipse webmasters.

**Comment by akshatg110** [comment]
Till when the website will be restored. Any ETA?

**Comment by tsegismont** [comment]
> Till when the website will be restored. Any ETA?

We don't know yet

**Comment by akshatg110** [comment]
> > Till when the website will be restored. Any ETA?
> 
> We don't know yet

How do we know about the restoration? any channel or twitter?

**Comment by tsegismont** [comment]
We can add a comment here.

**Comment by akshatg110** [comment]
> We can add a comment here.

Sure please comment here after restoration.

**Comment by tsegismont** [comment]
It's back online.
