### ISSUE TITLE
Lose charset in application/x-www-form-urlencoded?

### ISSUE THREAD

**Issue by snpcp** [eclipse-vertx/vert.x#4646]
I use `sendForm` to request, I set a header `Content-Type: application/x-www-form-urlencoded; charset=UTF-8`, but I found actual request `Content-Type` is `application/x-www-form-urlencoded` , it's not should be.

Vertx override my header in here of `HttpContext#handleCreateRequest`:
`multipartForm.headers().forEach(header -> {
          requestOptions.putHeader(header.getKey(), header.getValue());
        });`

### Version

vertx-core:4.3.5
vertx-web-client:4.3.5
JVM:1.8

### Steps to reproduce

1. set `Content-Type: application/x-www-form-urlencoded; charset=UTF-8` to header.
2. call `sendForm`
3. look message in tcpdump.

**Comment by vietj** [comment]
please reopen here https://github.com/vert-x3/vertx-web
