### ISSUE TITLE
Headless Service HttpClient Load Balancing

### ISSUE THREAD

**Issue by lwlee2608** [eclipse-vertx/vert.x#4649]
#### The feature

Add a load balancing feature to HttpClient, similar to grpc's [ManagedChannelBuilder.defaultLoadBalancingPolicy()](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#defaultLoadBalancingPolicy-java.lang.String-)

#### Use cases

In a larger-scale system running on Kubernetes, clients need to send messages to a k8s service composed of many pods. If a long-living connection type such as HTTP/2 is used, only one connection will be established to one pod. The goal is to evenly distribute the traffic automatically to all the pods by using a headless service as the endpoint.

#### Contribution

I will attempt to contribute to this

**Comment by tsegismont** [comment]
Closed by https://github.com/eclipse-vertx/vert.x/pull/4926
