### ISSUE TITLE
WebSocket fetch and ping / pong

### ISSUE THREAD

**Issue by shawkins** [eclipse-vertx/vert.x#4660]
### Version

4.4.1

### Context

In looking at the fabric8 integration of vert.x we are using pause / fetch on websockets to control the rate at which messages are processed.  However it appears that ping / pong messages from the server count towards the fetch.  We can workaround this by not sending pings ourselves, or if we ever need to, use a pongHandler to increase the fetch.  However if the server sends a ping since the ping handling is baked-in there's nothing we can do to increase the fetch.

### Do you have a reproducer?

```
    Vertx vertx = Vertx.vertx(new VertxOptions());
    HttpServer server = vertx.createHttpServer();

    server.webSocketHandler(sws -> {
      sws.writePing(Buffer.buffer("ping"));
      sws.writeTextMessage("some message");
    }).listen(8080);

    HttpClient client = vertx.createHttpClient();
    CompletableFuture<String> message = new CompletableFuture<String>();
    client.webSocket(8080, "localhost", "/").onSuccess(ws -> {
      ws.pause();

      // demand is used for the ping instead
      ws.fetch(1);

      ws.textMessageHandler(message::complete);
    });

    // never completes
    message.get();
```

If we remove the pause / fetch, this will complete as expected.

cc @vietj the current api server implementation does not send a ping, so this isn't an issue for fabric8 yet.  However the likely resolution of the upstream issue https://github.com/kubernetes/kubernetes/pull/116778 will include using ping / pong as the heartbeat mechanism for websockets, so we'll probably have to account for this eventually.

**Comment by vietj** [comment]
Need a specific PR for 4.x

**Comment by shawkins** [comment]
#4666 should be good
