### ISSUE TITLE
Logback not working since >= 4.4.0

### ISSUE THREAD

**Issue by pendula95** [eclipse-vertx/vert.x#4687]
### Version
>= 4.4.0

### Steps to reproduce

1. Checkout maven project https://start.vertx.io/ 4.4.1
2. Add following to pom:
```
<dependency>
   <groupId>ch.qos.logback</groupId>
   <artifactId>logback-classic</artifactId>
   <version>1.4.4</version>
</dependency>

      <plugin>
        <groupId>io.reactiverse</groupId>
        <artifactId>vertx-maven-plugin</artifactId>
        <version>1.0.28</version>
        <executions>
          <execution>
            <id>vmp</id>
            <goals>
              <goal>initialize</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <redeploy>true</redeploy>
        </configuration>
      </plugin>
```
3. Run mvn clean package vertx:run
4. Logger not working
5. Revert back to 4.3.8 logger working
6. Here is reproducer: [test.zip](https://github.com/eclipse-vertx/vert.x/files/11381915/test.zip)

### Extra

* Tried on host via maven vertx plugin openjdk 11.0.18 2023-01-17 OpenJDK Runtime Environment (Red_Hat-11.0.18.0.10-1.fc38) (build 11.0.18+10)
* Tried in docker via fat jar setup

**Comment by pendula95** [comment]
I am still figuring it out. Also logback version <= 1.2.12 will work with 4.4.1

**Comment by pendula95** [comment]
I am not an expert but looks like old version of slf4j-api that is set in vertx-dependencies 
https://github.com/vert-x3/vertx-dependencies/blob/3e6007d3bf6993e63892af252d4a6c46f988e559/pom.xml#LL52C7-L52C42 is making the issue. It overrides one coming from logback-classic

**Comment by EmadAlblueshi** [comment]
Hi @pendula95 as a workaround try version 1.2.12 and this one should work 

The new version series 1.4.x still does not work I think in Vert.x

**Comment by OddsJanttu** [comment]
> Hi @pendula95 as a workaround try version 1.2.12 and this one should work
> 
> The new version series 1.4.x still does not work I think in Vert.x

I beg to differ. I'm running Vertx 4.4.2, SLF4J 2.0.7 and Logback 1.4.7. And yes, could have to do with the explicit SLF4J API dependency, as @pendula95 mentioned.

**Comment by alexlehm** [comment]
I have come across the same issue when using slf4j-api and slf4j-simple directly, the automatic version is 1.7.21 and that does not work

**Comment by vietj** [comment]
is there an issue or something documenting the reason logback does not work anymore with older version of slf4j ?

**Comment by pendula95** [comment]
> is there an issue or something indicating the reason logback does not work anymore with older version of slf4j ?

This is the message but I guess it is not relevant as you already updated the stack.
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
