### ISSUE TITLE
Error reported when using Json. decodeValue()

### ISSUE THREAD

**Issue by lgyyj** [eclipse-vertx/vert.x#4721]
The following error occurred when using code 
`  String system = """
                {
                "acctID":"5b10fbda967c3c",
                "username":"demo02",
                "password":"123456",
                "lcid":"2052"
                }
                """    
HashMap body = Json.decodeValue(system, HashMap.class);`
 to handle deserialization:
**
Exception in thread "main" io.vertx.core.json.DecodeException: Failed to decode
	at io.vertx.core.json.jackson.JacksonCodec.cast(JacksonCodec.java:350)
	at io.vertx.core.json.jackson.JacksonCodec.fromParser(JacksonCodec.java:187)
	at io.vertx.core.json.jackson.JacksonCodec.fromString(JacksonCodec.java:65)
	at io.vertx.core.json.Json.decodeValue(Json.java:83)
**

**Comment by tsegismont** [comment]
I've tried:

```java
    String system = """
      { "acctID":"5b10fbda967c3c", "username":"demo02", "password":"123456", "lcid":"2052" }""";
    HashMap body = Json.decodeValue(system, HashMap.class);
    System.out.println("body = " + body);
```

And got:

```
body = {lcid=2052, password=123456, acctID=5b10fbda967c3c, username=demo02}
```

Please reopen if you can provide a reproducer.

**Comment by lgyyj** [comment]
Sorry, I am using version 4.4.2, and there were indeed errors during local debugging. Please find attached the debugging image.


<img width="689" alt="image" src="https://github.com/eclipse-vertx/vert.x/assets/45484946/89b466f7-75b9-4fc8-8d33-9c1cb2d5abe5">
<img width="624" alt="image" src="https://github.com/eclipse-vertx/vert.x/assets/45484946/ae43ba45-6c81-4215-ae56-1d6614ecf7c3">

**Comment by tsegismont** [comment]
I've also tested with 4.4.2.

On your screenshots, I see a `HashMap` and a `LinkedHashMap`, both of which implement `Map`.

Without a reproducer it's not possible to understand the problem.
