### ISSUE TITLE
RxHelper WebSocket Subscriber Does Not Cancel Subscription On WebSocket Close  

### ISSUE THREAD

**Issue by pgalbraith** [eclipse-vertx/vert.x#4724]
### Version

4.4.2

### Context

Open a websocket and use RxHelper to create an RxJava3 FlowableSubscriber from the vert.x WebSocket.   Upon closing the websocket I expect the subscriber should cancel the subscription but it does not seem to.  

```java
import io.vertx.core.Vertx;
import io.vertx.core.http.ServerWebSocket;
import io.vertx.junit5.*;
import io.vertx.rxjava3.RxHelper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.mockito.Mockito;
import org.reactivestreams.Subscription;

import java.net.ServerSocket;

@ExtendWith(VertxExtension.class)
@Timeout(5000)
class RxJavaWebSocketSubscriberTest {
	@RegisterExtension
	static RunTestOnContext rtoc = new RunTestOnContext();

	Vertx vertx;

	@BeforeEach
	void setup(VertxTestContext vtc) {
		vertx = rtoc.vertx();
		vtc.completeNow();
	}

	@Test
	void testSubscriber(VertxTestContext vtc) throws Exception {
		Checkpoint closed = vtc.checkpoint();
		int port;
		try (ServerSocket socket = new ServerSocket(0)) {
			port = socket.getLocalPort();
		}
		vertx.createHttpServer().webSocketHandler(ServerWebSocket::accept).listen(port);
		vertx.createHttpClient().webSocket(port, "localhost", "").onSuccess(ws -> {
			Subscription subscription = Mockito.mock(Subscription.class);
			RxHelper.toSubscriber(ws).onSubscribe(subscription);
			ws.close().onSuccess(v -> {
				vtc.verify(() -> Mockito.verify(subscription).cancel());
				closed.flag();
			});
		});
	}
}
```

**Comment by pgalbraith** [comment]
Erf I think I need to rework the test case, sorry, I am suspecting the subscriber does not cancel the subscription though the above test isn't right to show that.

**Comment by tsegismont** [comment]
Actually this is not a bug.

The `RxHelper.toSubscriber` method transforms a generic `WriteStream` to a subscriber, and the `WriteStream` contract has no notion of open/closed because it could be anything which is connection-oriented.

It's the developer's responsibility in this case to manage the websocket, perhaps like this:

```Java
    ws.closeHandler(v-> {
      subscription.cancel();
    });
```

**Comment by pgalbraith** [comment]
> Actually this is not a bug.
> 
> The `RxHelper.toSubscriber` method transforms a generic `WriteStream` to a subscriber, and the `WriteStream` contract has no notion of open/closed because it could be anything which is not connection-oriented.
> 
> It's the developer's responsibility in this case to manage the websocket, perhaps like this:
> 
> ```java
>     ws.closeHandler(v-> {
>       subscription.cancel();
>     });
> ```

Hmmm but how to get a reference to the subscription?

**Comment by tsegismont** [comment]
Like this:

```java
    WriteStreamSubscriber<Buffer> subscriber = RxHelper.toSubscriber(ws);
    flowable
      .doOnSubscribe(subscription -> {
        ws.closeHandler(v-> {
          subscription.cancel();
        });
      })
      .subscribe(subscriber);
```

**Comment by pgalbraith** [comment]
Thanks very much @tsegismont, that should work nicely.  Looking at the [reactive streams specification](https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.4/README.md#specification) item #2.6, it does seem like this is a bug still but understandably it's sounds like a deep issue to address.  I think your suggest above should solve my immediate problem, however.
