### ISSUE TITLE
Loading web template from archive with "war" extension causes an error

### ISSUE THREAD

**Issue by usatenko** [eclipse-vertx/vert.x#4727]
### Questions

Do not use this issue tracker to ask questions, instead use one of these [channels](https://vertx.io/community/). Questions will likely be closed without notice.

### Version

4.3.8

### Context

I encountered an exception while running vertx that uses vertx-web
which specifically uses war file extension to start (not jar or zip)
java -jar file.war

When loading a web template using
```
FreeMarkerTemplateEngine.create(vertx).render(data, "/static/iframe.ftl", response -> {
```
vertx tries to load the template to cache
```
    private Object findTemplateSource(String path) throws IOException {
        final Object result = templateLoader.findTemplateSource(path);

```
which tries to extract the template file from archive but fails as expecting jar or zip archive extension.
```
      String path = url.getPath();
      int idx1 = path.lastIndexOf(".jar!");
      if (idx1 == -1) {
        idx1 = path.lastIndexOf(".zip!");
      }
      int idx2 = path.lastIndexOf(".jar!", idx1 - 1);
      if (idx2 == -1) {
        idx2 = path.lastIndexOf(".zip!", idx1 - 1);
      }
      if (idx2 == -1) {
        File file = new File(decodeURIComponent(path.substring(5, idx1 + 4), false));
        zip = new ZipFile(file);
      } else {
        String s = path.substring(idx2 + 6, idx1 + 4);
        File file = resolveFile(s);
        zip = new ZipFile(file);
      }

```

jar:file:/Users/.../target/wageapi-0.0.1-SNAPSHOT.war!/static

### Do you have a reproducer?

no

### Steps to reproduce

1. put FreeMarker template package in classpath e.g. /static/iframe.ftl
2. package vertx app as war (not jar or zip)
3. run package as java -jar file.war
4. call FreeMarkerTemplateEngine.create(vertx).render(data, "/static/iframe.ftl", response -> {
5. get the error (see below)

### Extra

```
Caused by: java.lang.StringIndexOutOfBoundsException: begin 5, end 3, length 34
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4602)
        at java.base/java.lang.String.substring(String.java:2705)
        at io.vertx.core.file.impl.FileResolverImpl.unpackFromJarURL(FileResolverImpl.java:291)
        at io.vertx.core.file.impl.FileResolverImpl.unpackUrlResource(FileResolverImpl.java:239)
        at io.vertx.core.file.impl.FileResolverImpl.resolveFile(FileResolverImpl.java:162)
        at io.vertx.core.impl.VertxImpl.resolveFile(VertxImpl.java:813)
        at io.vertx.core.file.impl.FileSystemImpl$20.perform(FileSystemImpl.java:1135)
```

**Comment by tsegismont** [comment]
WAR is a packaging for Java EE webapps, we don't support that in the file resolver, I think.

Can you explain why you need this packaging?

**Comment by usatenko** [comment]
the reason for it, from my point of view, the behavior should not depend on the name of the extension, it will have a problem even if it has an extension ".app" but it is actually a standard jar zip inside.

**Comment by tsegismont** [comment]
I understand why you filed the issue. My question is what is the use case which requires to put files in a WAR file.

**Comment by usatenko** [comment]
The spec from Oracle https://docs.oracle.com/en/java/javase/20/docs/specs/jar/jar.html states that:
"... There is no restriction on the name of a JAR file, it can be any legal file name on a particular platform..."
The extension "war" is a legal filename extension as any other possible extension for a jar file.

In our case, it is our internal deployment process where historically happened it has the "war" extension instead of "jar", so we noticed this Vertx behavior.

**Comment by tsegismont** [comment]
Fixed by #4748

**Comment by usatenko** [comment]
Many thanks!

**Comment by tsegismont** [comment]
You're welcome
