### ISSUE TITLE
Many Javadoc comments contain text 

### ISSUE THREAD

**Issue by wissenstein** [eclipse-vertx/vert.x#4731]
### Version

4.4.2

### Context

I can see that many Javadoc comments about deprecated TimeoutStream functionality contain text: 'Rx java like integrations should use the Vert.s scheduler integration'. I think, Vert.s should be replaced with Vert.x there.

### Do you have a reproducer?

It can be found in Javadocs at least at following links:

https://vertx.io/docs/apidocs/io/vertx/core/TimeoutStream.html

https://vertx.io/docs/apidocs/io/vertx/core/Vertx.html#periodicStream-long-

https://vertx.io/docs/apidocs/io/vertx/core/Vertx.html#periodicStream-long-long-

https://vertx.io/docs/apidocs/io/vertx/core/Vertx.html#timerStream-long-

### Steps to reproduce

Open any of the mentioned links and find a section 'Deprecated'
#### Actual result
The text mentions 'Vert.s'.
#### Expected result
The text mentions 'Vert.x' instead.

**Comment by vietj** [comment]
such classes were designed to produce Observable for RX and. are removed in vertx 5, hence the comment which indicates what to use instead.

**Comment by tsegismont** [comment]
Right @vietj . I think @wissenstein reported this only because of the typo (`Vert.s` instead of `Vert.x`).

**Comment by tsegismont** [comment]
Fixed by f4968569a9e57e8d5919173b1246b3906dbe1f01
