### ISSUE TITLE
vertx-web  often resource no find

### ISSUE THREAD

**Issue by mygitdds** [eclipse-vertx/vert.x#4744]
### Questions

There are two server instances deployed in the Vertx cluster, with multiple Vertices deployed on each instance. The Vertx hazelcast is used to deploy on the K8S. Currently, there are request handlers that have registered Vertx web, and there are frequent instances of 'route no find' in the execution function, indicating that Vertx has been restarting Vertices

### Version

vert-4.4.3 /vertx -4.3.7

### Context

I encountered an exception which looks suspicious while ...

### Do you have a reproducer?

A reproducer is a simple project hosted on GitHub (or another forge supporting git clone operation) that has a build file that can be executed to reproduce the issue.

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

* Link to github project/gist

### Steps to reproduce

1. ...
2. ...
3. ...
4. ...

### Extra

* Anything that can be relevant such as OS version, JVM version

**Comment by mygitdds** [comment]
After modifying the jvm startup parameters and the usage of the vertical deployment class, this situation no longer occurs

**Comment by tsegismont** [comment]
Thanks for letting us know
