### ISSUE TITLE
Expose expireAfterSeconds in mongo CreateCollectionOptions

### ISSUE THREAD

**Issue by matt1good** [eclipse-vertx/vert.x#4757]
Expose com.mongodb.client.model.CreateCollectionOptions.expireAfterSeconds in 
io.vertx.ext.mongo.CreateCollectionOptions.

**Comment by tsegismont** [comment]
Can you please report this feature request to the Vert.x Mongo [repo](https://github.com/vert-x3/vertx-mongo-client)? Thanks
