### ISSUE TITLE
Should io.vertx.core.streams.impl.InboundBuffer#write(E) emitPending before handleEvent?

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [eclipse-vertx/vert.x#4764]
### Questions
If the pending queue is not empty, will current implentation cause messages be handled out of order?

### Version
vertx-core: 4.3.8

### Context
When I upload a file of size 5mb, sometimes it's missing a part of it. So I read code related to file-uploading and find this code snippet suspicous.

### Do you have a reproducer?

Very hard to reproduce.

**Comment by vietj** [comment]
the queue maintains order, if you found a bug we should fix it

**Comment by Nick-The-Uncharted** [comment]
But the logic seems to process the current message first before flush the queue.



---Original---
From: "Julien ***@***.***&gt;
Date: Sat, Jul 1, 2023 15:48 PM
To: ***@***.***&gt;;
Cc: "Nick ***@***.******@***.***&gt;;
Subject: Re: [eclipse-vertx/vert.x] Shouldio.vertx.core.streams.impl.InboundBuffer#write(E) emitPending beforehandleEvent? (Issue #4764)




 
the queue maintains order, if you found a bug we should fix it

**Comment by vietj** [comment]
if you find a bug provide a reproducer, the queue is very simple and it is possible to come with a test

**Comment by Nick-The-Uncharted** [comment]
I missed that if `emitting` is true, current message will goes to queue, and emitting will be set to true when fetch.

**Comment by vietj** [comment]
yes that flag is necessary to queue message and rely on the owner
thread to emit the message on behalf of the submitter.
