### ISSUE TITLE
Unclear "host" (or ":authority") header setting

### ISSUE THREAD

**Issue by NilsRenaud** [eclipse-vertx/vert.x#4765]
### Disclamer
I'll use either "host" or ":authority" header to cover both HTTP/1.1 "host" header and HTTP/2 ":authority" pseudo header.

### Version

I used Vert.x 4.4.4

### Context

As reverse proxy builder (let's call it RP) I want to be able to set the value of the the outgoing request. Here is an example:
I could set the host with the same value as the one used for the connection:
```
User -- GET /test -----> test.com (RP) -- GET /test -----> internal.com:8080
         Host: test.com                    Host: internal.com:8080
```
Or I could reuse the host received from the end user:
```
User -- GET /test -----> test.com (RP) -- GET /test -----> internal.com:8080
         Host: test.com                    Host: test.com
```

While trying to find out how to do that, I found a couple of issues, misalignments between HTTP/1.1 and HTTP/2

### Issue 1: Unclear Host header setting in Vert.x HttpClient

When creating a new request using Vert.x HTTP Client, the `setHost` method appears at two places:
- In `RequestOptions`: this sets the host used for the connection, and will be the default value of the `Host` header
- In `HttpClientRequest`: this sets the host part of the `Host` header

Here is an example:
```java
var requestOptions = new RequestOptions().setHost("internal.com")
                                         .setPort("8081")
                                         .putHeader("headerName", "headerValue1");
httpClient.request(requestOptions)
          .map(vxRequest -> vxRequest.setHost("test.com")
                                     .setPort("8080")
                                     .putHeader("myOtherHeader", "headerValue2"));
```
Will create this request: 
- To : internal.com:8081
- with headers:
  - `Host=test.com:8080`
  - `headerName=headerValue1`
  - `myOtherHeader=headerValue2`

This emphasis that although `putHeader` method performs the same task, `setHost` and `setPort` have different meaning.

### Issue 2: Incoherence between server and client sides

From [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110#name-host-and-authority) the host header may contain the port (but if it's 80 with `http` scheme or 443 with `https` scheme 🤷 ).
So using Vert.x HTTP server, one can get the value of the `host` header using `HttpServerRequest#host()` and this will return something like `test.com:8080`. Fine.

But on client side, one can't set the port in the `HttpClientRequest#setHost()` otherwise it may produce an invalid `host` header. Example:
```java
var requestOptions = new RequestOptions().setHost("internal.com")
                                         .setPort("8081");
httpClient.request(requestOptions)
          .map(vxRequest -> vxRequest.setHost("test.com:8080"));
```
Will create this request: 
- To : internal.com:8081
- with headers:
  - `Host=test.com:8080:8081`

Which is obviously wrong.

Worst ! As an HTTP Reverse Proxy developer, if I perform TLS offloading and such transform an HTTPS connection into an HTTP one and want to pass the host header from the incoming request to the outgoing one I may encounter silly bugs.
Example:
```
           HTTPS                               HTTP
User -- GET /test -----> test.com (RP) -- GET /test -----> internal.com:8081
         Host: test.com                    Host: test.com
```
Then doing : 
```java
var requestOptions = new RequestOptions().setHost("internal.com")
                                         .setPort("8081");
httpClient.request(requestOptions)
          .map(vxRequest -> vxRequest.setHost(originalServerRequest.host()));
```
Will create this request: 
- To : internal.com:8081
- with headers:
  - `Host=test.com:8081`, which is wrong.

### Issue 3: HTTP/1.1 and HTTP/2 host setting using headers in Vert.x httpClient act differently

Using HTTP/1.1, it is possible to set the host header using `HttpClientRequest#putHeader(key, value)` or `RequestOptions#putHeader(key, value)`, and this one is never overridden by `HttpClientRequest#setHost` nor `HttpClientRequest#setPort`. That's OK.

But using HTTP/2, it is not possible to run these lines, because ":" is not accepted in header name:
```java
requestOptions.putHeader(":authority", "test.com");
httpClientRequest.putHeader(":authority", "test.com");
```
And when I set the `host` header of a request that will be sent using HTTP/2, I end up with a request having these headers:
- `:authority=internal.com:8081`
- `host=test.com:8080`
Which is considered as an invalid request (see [RFC 9113: HTTP/2](https://www.rfc-editor.org/rfc/rfc9113#section-8.3.1-2.3.3))

Since the Vert.x HTTP client may choose to use HTTP/2 on our behalf, it's hard to predict how the host will be set.

### Issue 4: HttpServerRequest.headers() will not contain Host/:authority header depending of the version

When called `HttpServerRequest.headers()`:
- For an HTTP/1.1 request, will contain the `host` header
- For an HTTP/2 request, will not contain the `:authority` header

That's just a bit weird.

### Issue 5: An HTTP/2 request with mismatching `host` and `:authority` is not rejected on client and server side

It is possible to send an HTTP/2 request containing mismatching `host` and `:authority` headers: 
```java
var requestOptions = new RequestOptions().setHost("internal.com")
                                         .setPort("8081");
httpClient.request(requestOptions)
          .map(vxRequest -> vxRequest.setHost("test.com"));
```
This behaviour is forbidden by [RFC 9113: HTTP/2](https://www.rfc-editor.org/rfc/rfc9113#section-8.3.1-2.3.3): 
> Clients MUST NOT generate a request with a Host header field that differs from the ":authority" pseudo-header field.

A Vert.x http server will not reject HTTP/2 requests having mismatching `host` and `:authority`. This behaviour is discouradged by the same [RFC 9113: HTTP/2](https://www.rfc-editor.org/rfc/rfc9113#section-8.3.1-2.3.3): 
> A server SHOULD treat a request as malformed if it contains a Host header field that identifies an entity that differs from the entity in the ":authority" pseudo-header field.

### Possible solutions

Overall, it would be to have this "authority" property stored outside from the headers (or hidden at lease, as currently done in HTTP/2 requests), but I guess we should keep the compatibility with HTTP/1.1 requests...

So here are the solutions I can think of
- **On HTTP Client side**: 
  - We should replace `HttpClientRequest`'s `setHost` and `setPort` methods in favor of `setAuthority(...)` (since it's the term used for HTTP/2 and HTTP/3), which would default to the connection host and port.
  - I would rather like to disallow to set the `host`header directly (as it is for the `:authority` one currently) but if it's impossible it should be equivalent as calling `httpClientRequest.setAuthority()` and thus set the `:authority` header in case of HTTP/2 request.
  - Anyway, it should be made impossible to have misaligned `host` and `:authority` headers. Maybe even to have both of them.

- **On HTTP Server side**:
  - We should reject requests having misaligned `host` and `:authority` headers
  - We should replace `HttpServerRequest.host()` by `HttpServerRequest.authority()` to be consistant with the client side
  - I think it would be better to remove the `host` header from the `HttpServerRequest.headers()` list. But that's maybe a too big breaking change :s

Thanks for having read that ! I hope this is clear enough to sparkle the discussion :)

**Comment by vietj** [comment]
thanks for the analysis, I agree with most of it.

Indeed we need to have a proper authority property on Vert.x HTTP stream for the developer to interact with.

we should have two related issues one for the client and one for the server.

Also you should have a look at SNI (Server Name Indication) because this interacts with the authority, so we need to make sure it aligns well with the proposal (on the client).

**Comment by vietj** [comment]
NOTE : the `HttpClientRequest` has a `setPort` which allows to set the port of the host header that you seem to have missed.

**Comment by vietj** [comment]
NOTE : "I think it would be better to remove the host header from the HttpServerRequest.headers() list. But that's maybe a too big breaking change"

The host header in HTTP/1 remains a valid HTTP header still.

**Comment by vietj** [comment]
one open concern, should we introduce an `io.vertx.core.net.HostAndPort` data object to hold the authority instead of a mere string ?

**Comment by vietj** [comment]
Please see https://github.com/eclipse-vertx/vert.x/pull/4774

**Comment by vietj** [comment]
I think we should address point 5 too, but for now I was focusing on getting right the authority property design first

I think on the server we can use the invalid request handler to handle the request, that will send an appropriate response and remain configurable

**Comment by NilsRenaud** [comment]
Should I open an other issue for point 5 ?

**Comment by vietj** [comment]
the issue has been actually implemented and referenced as
https://github.com/eclipse-vertx/vert.x/issues/4776
