### ISSUE TITLE
Add the IP address in the toString method of the implementations of SocketAddress

### ISSUE THREAD

**Issue by ivanangelov** [eclipse-vertx/vert.x#4773]
The toString method of the implementations of SocketAddress could also contain the IP address of the server.

Examples where this would be useful:

HttpClientRequestBase - timeoutEx
SharedClientHttpStreamEndpoint#Request - onConnect

Original issue in vertx-web: https://github.com/vert-x3/vertx-web/issues/2305

**Comment by vietj** [comment]
there is not guarantee that the IP address is resolved when we have a socket address (it could be an internet address)

**Comment by ivanangelov** [comment]
Hello, 

So then, can the IP address be included only if it is available?

Regards,
Ivan

**Comment by vietj** [comment]
that might break application considering they will get the host:port value from toString, so no
