### ISSUE TITLE
SSLOptions object incorrectly states objects are equal when SSL handshake timeouts are different

### ISSUE THREAD

**Issue by Kyefer** [eclipse-vertx/vert.x#4787]
### Version

4.4.3

### Context

I am trying to update the SSL options of a running `HttpServer` object using the `updateSSLOptions(SSLOptions)` method and have changed the SSL Handshake timeout. I expected the SSL settings to have been be recreated but it seems that it did not. Inspecting the code, I noticed that the `equals()` method on the `SSLOptions` class returned `true` even when the SSL handshake timeout was different.

Looking into the code, I noticed that the `equals` method uses the same `sslHandshakeTimeout` variable on both sides of the equality check instead of using the `that`'s variable.

The line in issue: https://github.com/eclipse-vertx/vert.x/blob/032f2def78d5ab334b6090c77ce35ccf0ae1cea5/src/main/java/io/vertx/core/net/SSLOptions.java#L334

### Steps to reproduce
```
SSLOptions first = new SSLOptions().setSslHandshakeTimeout(10);
SSLOptions second = new SSLOptions().setSslHandshakeTimeout(11);

assert first.equals(second) == false;
```

### Extra
Note that I actually don't care about updating the SSL Handshake Timeout variable, but instead I am looking to "trick" vertx into update the SSL context since the keystore at the given path has updated but the path has stayed the same, so vertx doesn't update the SSL context. I was hoping to simply change the handshake timeout but ran into this issue

**Comment by vietj** [comment]
can you provide a PR that fixes implements this ? initially the purpose of updating SSL options is mostly for certificates and not other settings

**Comment by Kyefer** [comment]
OK, I will make the change

**Comment by Kyefer** [comment]
Please see https://github.com/eclipse-vertx/vert.x/pull/4788

**Comment by vietj** [comment]
See https://github.com/eclipse-vertx/vert.x/pull/4789
