### ISSUE TITLE
SSL Option updates only seem to apply to a single HTTP Server when the servers are sharing a bind addresses

### ISSUE THREAD

**Issue by Kyefer** [eclipse-vertx/vert.x#4790]
### Version

4.4.3

### Context

I am deploying several `HttpServer`s that are being deployed on the same host and port and am trying to update the SSL options via the `updateSSLOptions()` method on each `HttpServer` object. However, it doesn't seem to apply to all the servers that are sharing the bind address; it seems that only the first server that has its `updateSSLOptions()` called on it will update its SSL context. The other servers still use the old context.

Please see the reproducer class that I built to show the problem:
[Kyefer/ssl-options-reproducer](https://github.com/Kyefer/ssl-options-reproducer)

The overall flow of this class is:
* Generate 2 different keystores (using bouncycastle)
* Deploy 2 instances of a verticle that each create an HTTP server on the same port
* Send a HTTP request to the server to verify that everything is working
* Update each server object with the new keystore
* Repeated send HTTP requests to the servers to make sure that the first server updated is not the only server handling the request
** This is the part of the test that fails

**Comment by vietj** [comment]
can you provide a complete reproducer with maven as a project @Kyefer ?

I created a test for this and it seems to pass in vertx test suite

```java
  @Test
  public void testConcurrentUpdateSSLOptions() throws Exception {
    server = createHttpServer(createBaseServerOptions().setSsl(true).setKeyCertOptions(Cert.SERVER_JKS.get()))
      .requestHandler(req -> {
        req.response().end("Hello World");
      });
    startServer(testAddress);
    client = createHttpClient(new HttpClientOptions().setKeepAlive(false).setSsl(true).setTrustOptions(Trust.SERVER_JKS_ROOT_CA.get()));
    List<KeyCertOptions> list = Arrays.asList(
      Cert.SERVER_PKCS12.get(),
      Cert.SERVER_PEM.get(),
      Cert.SERVER_PEM.get(),
      Cert.SERVER_JKS_ROOT_CA.get());
    AtomicInteger seq = new AtomicInteger();
    Future<Void> last = null;
    for (int i = 0;i < list.size();i++) {
      int val = i;
      last = server.updateSSLOptions(new SSLOptions().setKeyCertOptions(list.get(i)));
      last.onComplete(onSuccess(v -> {
        assertEquals(val, seq.getAndIncrement());
      }));
    }
    last.onComplete(onSuccess(v -> {
      client
        .request(requestOptions)
        .compose(req -> req.send().compose(HttpClientResponse::body))
        .onComplete(onSuccess(body -> {
        assertEquals("Hello World", body.toString());
        testComplete();
      }));
    }));
    await();
  }
```

**Comment by Kyefer** [comment]
Sure thing @vietj 
Please see my GitHub repository [Kyefer/ssl-options-reproducer](https://github.com/Kyefer/ssl-options-reproducer)

I will also update the original issue with this link instead of the gist

**Comment by Kyefer** [comment]
Ah, it seems to be broken on 4.4.3 but works with 4.4.4 - I wonder what changed, as I didn't see anything relating to this in the release notes

**Comment by vietj** [comment]
I think we are talking of this PR : https://github.com/eclipse-vertx/vert.x/pull/4742 which I can see in https://github.com/vert-x3/wiki/wiki/4.4.4-Release-Notes
