### ISSUE TITLE
The dns resolver does not re-read /etc/hosts upon change

### ISSUE THREAD

**Issue by conet** [eclipse-vertx/vert.x#4832]
#### Describe the feature

As described in the old issue #2254 the hosts file is only read on start, [this is still true](https://github.com/eclipse-vertx/vert.x/blob/5d7cc0cc7266ce2db9969821cf8fa3ed78acc0db/src/main/java/io/vertx/core/impl/resolver/DnsResolverProvider.java#L92) and should be fixed in my opinion.

#### Use cases

There are several valid use cases that rely on the hosts file being properly interpreted, if a vertx process needs a restart on every change that is a big drawback. This problem is already solved in netty, see https://github.com/netty/netty/issues/11661.

**Comment by vietj** [comment]
it is not clear how netty solve this issue

I can see there is a cache clear method, however this method still needs to be called

you can already configure the cache TTL in vertx resolver with AddressResolverOptions#cacheMaxTimeToLive

can you elaborate unless I am missing something ?

**Comment by conet** [comment]
If the hosts file is read on the constructor of `DnsResolverProvider` are you saying that if the cacheMaxTimeToLive is set then a new `DnsResolverProvider` is constructed and the hosts file is reloaded? I'm asking because I haven’t actually debugged this setup.

**Comment by vietj** [comment]
ah sorry you mean the configuration, the Netty issue you pointed out is about caching and not reloading configuration

**Comment by conet** [comment]
You're right, sorry I was looking at multiple issues and messed up the links, I mean this fix: https://github.com/netty/netty/issues/11661

**Comment by sagaxu** [comment]
solution of netty

```Kotlin
    val lastRefresh = AtomicLong(System.nanoTime())
    refreshHostsfile()
    val refreshInterval = System.getProperty("io.netty.hostsFileRefreshInterval")?.toLongOrNull() ?: 0

    fun resolve() {
        if (refreshInterval > 0) {
            val currentTime = System.nanoTime()
            val last = lastRefresh.get()

            if (currentTime - last > refreshInterval) {
                if (lastRefresh.compareAndSet(last, currentTime)) {
                    refreshHostsFile()
                }
            }
        }
        //......
    }
```

**Comment by vietj** [comment]
what does refreshHostsFile do ?

**Comment by conet** [comment]
I've tried disabling the hosts file support in vertx like this:
```
        new AddressResolverOptions()
          .setHostsPath(null)
          .setCacheMaxTimeToLive(10)
```
but unfortunately it does not work, seems like netty's `DefaultHostsFileEntriesResolver` is still active based on the debug logs.

**Comment by sagaxu** [comment]
> what does refreshHostsFile do ?

reread /etc/hosts

**Comment by conet** [comment]
> I've tried disabling the hosts file support in vertx like this:
> 
> ```
>         new AddressResolverOptions()
>           .setHostsPath(null)
>           .setCacheMaxTimeToLive(10)
> ```
> 
> but unfortunately it does not work, seems like netty's `DefaultHostsFileEntriesResolver` is still active based on the debug logs.

Never mind, I didn't know the correct meaning of `HostsFileParser.parseSilently()`, vertx hosts file support can be disabled like this: 

```
        new AddressResolverOptions()
          .setHostsValue(Buffer.buffer())
```

This way we can rely on the system dns cache like `dnsmasq` to properly handle the hosts file until reload support is added to vertx.

**Comment by vietj** [comment]
I think we could add support for an active reloading of the hosts config on `io.vertx.core.impl.AddressResolver`

**Comment by vietj** [comment]
@conet please have a look https://github.com/eclipse-vertx/vert.x/pull/4842

**Comment by conet** [comment]
Looks great to me, although in order to actually test it I would need some snapshot artifacts with this change.
