### ISSUE TITLE
Unable to disable TLS v1.3 communications

### ISSUE THREAD

**Issue by benanderson1** [eclipse-vertx/vert.x#4834]
### Version

Vert.x 4.4.4

### Context

It seems like disabling TLS v1.3 does not work or do anything. We have a Server with configuration to remove TLS v1.3 but it is still accepting TLS 1.3 requests. We expect it should reject TLS 1.3 requests when it is removed from the enabled secure transport protocols.

### Do you have a reproducer?

`httpServerOptions.removeEnabledSecureTransportProtocol("TLSv1.3");`

* Link to github project/gist

### Steps to reproduce

1. Setup HTTP Server and remove TLS v1.3 from the enabled secure transport protocol list
2. Send request with TLS v1.3 and it is processed just fine 
tested using `curl --tlsv1.2 --tls-max 1.2`
vs `curl --tlsv1.3 --tls-max 1.3`

The first request should not be accepted

So it appears TLS v1.3 is always enabled

### Extra

* before we were using Vertx 4.1.2, where 1.3 was not enabled by default, and our code was using addEnabledSecureTransportProtocol() at that point. I presume this worked at that point, but since vertx 4.4.4 it TLS1.3 is now enabled by default and removing it doesn't seem to take effect

**Comment by vietj** [comment]
I tried to reproduce this with a test in vertx and I did not succeed, I added a test for this https://github.com/eclipse-vertx/vert.x/pull/5032

**Comment by tsegismont** [comment]
I've tried to reproduce with this program and JDK 11:

```java
  public static void main(String[] args) throws Exception {
    SelfSignedCertificate ss = SelfSignedCertificate.create();

    Vertx vertx = Vertx.vertx();

    HttpServerOptions options = new HttpServerOptions()
      .setKeyCertOptions(ss.keyCertOptions())
      .setSsl(true);
    options.removeEnabledSecureTransportProtocol("TLSv1.3");

    vertx.createHttpServer(options).requestHandler(req -> {
      System.out.println("got req");
      req.response().end();
    }).listen(8080, "localhost").toCompletionStage().toCompletableFuture().get(10, TimeUnit.SECONDS);
  }
```

Then I got

```bash
curl -k -v --tlsv1.3 --tls-max 1.3 https://localhost:8080
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, protocol version (582):
* OpenSSL/3.0.9: error:0A00042E:SSL routines::tlsv1 alert protocol version
* Closing connection 0
curl: (35) OpenSSL/3.0.9: error:0A00042E:SSL routines::tlsv1 alert protocol version
```

And

```bash
curl -k -v  --tlsv1.2 --tls-max 1.2 https://localhost:8080
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: CN=localhost
*  start date: Dec 13 11:20:26 2022 GMT
*  expire date: Dec 31 23:59:59 9999 GMT
*  issuer: CN=localhost
*  SSL certificate verify result: self-signed certificate (18), continuing anyway.
* using HTTP/1.x
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.0.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-length: 0
< 
* Connection #0 to host localhost left intact
```

So it seems to be working fine

**Comment by vietj** [comment]
reopen with a more thorough reproducer if it still happens and can be demonstrated
