### ISSUE TITLE
Silly questions about MessageConsumerImpl, HandlerRegistration

### ISSUE THREAD

**Issue by magicprinc** [eclipse-vertx/vert.x#4836]
1)

io.vertx.core.eventbus.impl.**MessageConsumerImpl** is a subclass of io.vertx.core.eventbus.impl.**HandlerRegistration**

Both have the same fields:
```java
  public final ContextInternal context;
  public final EventBusImpl bus;
  public final String address;
``` 
and
```java
  private final ContextInternal context;
  private final EventBusImpl eventBus;
  private final String address;
``` 
Is there a secret byte-code optimization reason?

2) MessageConsumerImpl
```java
  private Queue<Message<T>> pending = new ArrayDeque<>(8);
```
but in unregister() it is
```java
   pending = new ArrayDeque<>();
```

3) protected boolean doReceive(... doesn't have @Override

4) Spelling
This class is **optimized**

5) header is simple comment, not javadoc
/* not /**

PR:
https://github.com/eclipse-vertx/vert.x/pull/4847

**Comment by vietj** [comment]
hi, I don't think there are any secrets, this could be optimized, feel free to provide a PR for it

**Comment by magicprinc** [comment]
Here you are
https://github.com/eclipse-vertx/vert.x/pull/4839

**Comment by vietj** [comment]
thanks!

**Comment by vietj** [comment]
btw we might queue your PR https://github.com/eclipse-vertx/vert.x/pull/4824 and ask you to rebase

**Comment by vietj** [comment]
this PR does some cleanup too in event bus

**Comment by magicprinc** [comment]
> btw we might queue your PR #4824 and ask you to rebase

I am not GitHub expert, so I need your help: how can I do it?

**Comment by vietj** [comment]
we'll take care of it when the PR has been reviewed and merged
