### ISSUE TITLE
Don’t capture a stacktrace when creating a ReplyException

### ISSUE THREAD

**Issue by magicprinc** [eclipse-vertx/vert.x#4840]
I suppose this is a mistake

```io.vertx.core.eventbus.Message#fail```
creates ```ReplyException``` with stack trace.

In this case, it is not "real" exception, but error code and error message,
so I think the stack trace disabling was simply forgotten.

How to reproduce:
```java
  @Test void testMessageReplyBug () throws InterruptedException{
    var q = new LinkedBlockingQueue<Message<String>>();

    eventBus.consumer("x.y.z", (Message<String> msg) ->q.offer(msg));

    var f = eventBus.request("x.y.z", "Hello!");

    Message<String> msg = q.take();
    assertEquals("x.y.z", msg.address());
    assertNotNull(msg.replyAddress());
    msg.fail(404, "not found");

    f.onComplete(ar -> {
      assertNotNull(ar.cause());
      assertEquals(0, ar.cause().getStackTrace().length);
// ERROR [vert.x-eventloop-thread-0] io.vertx.core.impl.ContextBase::Unhandled exception
//org.opentest4j.AssertionFailedError: expected: <0> but was: <72>
    });
  }
```

Why is it bad?

1) Throwable#fillInStackTrace() is VERY heavy operation (takes long time)
2) ReplyExceptionMessageCodec doesn't use stack trace (doesn't serialize or deserialize them)

So we lose time to collect stack trace in vain.

PR with fix:
https://github.com/eclipse-vertx/vert.x/pull/4844

**Comment by magicprinc** [comment]
Updated fix after review
https://github.com/magicprinc/vert.x/commit/673b7c78bd70bbd7b61157b7807e260c5b65c409

**Comment by magicprinc** [comment]
BTW I have signed Eclipse Contributor Agreement

**Comment by magicprinc** [comment]
finally a PR
https://github.com/eclipse-vertx/vert.x/pull/4844

**Comment by tsegismont** [comment]
Fixed by #4844

**Comment by magicprinc** [comment]
Dear reader!

If you have problems and read this, then know:

My original idea was

/** Collect stack trace (heavy operation!). Default false */
public static boolean WITH_STACK_TRACE = isTrueStr(System.getProperty("vertx.stacktrace"));
...

public ReplyException(ReplyFailure failureType, int failureCode, String message) {
  super(message, !WITH_STACK_TRACE);
  this.failureType = failureType;
  this.failureCode = failureCode;
}
so user can enable them in some rare cases if needed

**Comment by vietj** [comment]
no need for un-necessary complexity, such exception are always created from the same location @magicprinc

**Comment by abozas** [comment]
Hi, 

I am still using vert.x in version 4.16 with quarkus and following proposed idea was good for me to debug MySQLException original exception at least in my unit tests. Is there a way to enable original stacktrace in some cases so it can be used and not swallowed as it is identified in this problem : https://github.com/eclipse-vertx/vert.x/issues/4861

Sorry if it is not the right place to ask this question or if it has already answers in other places. I did not find them for my problem.

Thanks in advance for your feedback or examples you can propose :)

> Dear reader!
> 
> If you have problems and read this, then know:
> 
> My original idea was
> 
> /** Collect stack trace (heavy operation!). Default false */ public static boolean WITH_STACK_TRACE = isTrueStr(System.getProperty("vertx.stacktrace")); ...
> 
> public ReplyException(ReplyFailure failureType, int failureCode, String message) { super(message, !WITH_STACK_TRACE); this.failureType = failureType; this.failureCode = failureCode; } so user can enable them in some rare cases if needed

**Comment by tsegismont** [comment]
You can reply to the message with your own subclass of `ReplyException`. As it is your own subclass, you might capture the stacktrace upon creation.

**Comment by abozas** [comment]
I will try this. Thanks :)
