### ISSUE TITLE
High memory consumption in MpscUnboundedArrayQueue

### ISSUE THREAD

**Issue by magicprinc** [eclipse-vertx/vert.x#4849]
Test:
https://github.com/magicprinc/vert.x/blob/bugfix/compact_args/src/test/java/io/vertx/core/eventbus/impl/MessageConsumerImplTest.java

Test method: ```testHighload```

It sends 17_000_000 messages through EventBus.
Consumer disposes messages immediately.
So memory consumption shouldn't grow.

But nevertheless, memory usage grows during the test.

I received OOE and captured thread dump.
Top consumer is ```io.netty.util.internal.shaded.org.jctools.queues.MpscUnboundedArrayQueue```
full of MessageImpl.

You can increment MessageConsumerImplTest#THREADS from 17 to 30 to see as this test with short-lived Messages consumes more than 20GB RAM

**Comment by vietj** [comment]
the behaviour you observe is a direct consequence of the executed test which is to publish messages in way that is faster than the consumer can handle. If you need high level processing of messages, you should not use an event-loop based system to implement it but instead use dedicated threads (that are not sharing their queue with IO operations) and a similar queue.
