### ISSUE TITLE
Missing synchronized in Http2ServerResponse.handlerWritabilityChanged()

### ISSUE THREAD

**Issue by anders-ahlgren** [eclipse-vertx/vert.x#4858]
### Version

Freeze observed in 4.3.7

### Context

A request hanged in a Quarkus Resteasy Reactive endpoint during writing the response body. 

I debugged using thread and heap dumps and code inspection. Problem seems to be in vert.x `Http2ServerResponse` rather than Quarkus-specific code. Moreover, due to visibility issues it does not seem to be fixable without Vert.x fix.

### Steps to reproduce

This is intermittent freeze with relatively low probability to occur per request, so I don't have a runnable sequence. However, according to analysis this is a sequence.

Thread A, running Quarkus `ResteasyReactiveOutputStream.write()` has a synchronized block on the connection object, that is covering steps 1, 4, 5. Step 2 has a synchronized on the stream object. Step 3 has no synchronization.

1. (Thread A) call from `ResteasyReactiveOutputStream.awaitWritable()` to `Http2ServerResponse.writeQueueFull()` returns true
2. (Thread B) call from `Http2ServerStream.handleWritabilityChanged()` to `Http2ServerResponse.handlerWritabilityChanged()` changing the writability status
3. (Thread B) still in `handlerWritabilityChanged()`, checks for a drain handler to call, but `drainHandler` is `null`
4. (Thread A) call to `Http2ServerResponse.drainHandler()` sets up a drain handler
5. (Thread A) waits for the drain handler to be called, but it will not because the queue is no longer full

Now, if this was the only sequence, then it is not obvious that it should be fixed in Vert.x rather than Quarkus. However, there are more subtle variations too, like:

1. (Thread A) call from `ResteasyReactiveOutputStream.awaitWritable()` to `Http2ServerResponse.writeQueueFull()` returns true
2. (Thread A) call to `Http2ServerResponse.drainHandler()` sets up a drain handler
3. (Thread B) call from `Http2ServerStream.handleWritabilityChanged()` to `Http2ServerResponse.handlerWritabilityChanged()` changing the writability status
4. (Thread A) waits for the drain handler to be called
5. (Thread B) still in `handlerWritabilityChanged()`, checks for a drain handler to call, but it reads a stale `null` value for the drain handler

Here, it is clear that there is a memory visibility issue.

### Looking at the code

The fields `drainHandler` and `ended` in `Http2ServerResponse` are guarded by synchronized on the `conn` field everywhere _except_ in the`handlerWritabilityChanged()` method. Presumably, synchronized was left out by accident rather than by design.

**Comment by vietj** [comment]
normally the callback should be done in the response on the event loop thread using a specific dispatch because it should also work with worker thread and currently this is not done.

**Comment by vietj** [comment]
however indeed the visibility should be changed as you are saying @anders-ahlgren , my remark was more about how things work in vertx, specially with the changes which have been made in master with respect to the new OutboundWriteQueue that works differently and the fact we want to remove the synchronization usage in `HttpServerResponse` implementations.

I will first fix this in vertx for fixing the non respect of vertx worker threads (the callback on drain handler is done on event-loop thread when using a worker context).

I think we should have a separate discussion for this subject to see how we can best address it on the long term.
