### ISSUE TITLE
Update deployment options of a deployed verticle

### ISSUE THREAD

**Issue by elgabbouch** [eclipse-vertx/vert.x#4860]
Currently, if we deploy a verticle, we can only get the deployment ID but there is no way to update the deployment options later. For example, I want to deploy some verticle with only one instance but later, I want to change to 2 instances, the only way I can achieve this is by undeploying the existing verticle and deploying a new one configured with 2 instances in deployment options.
I think it would be great if we could have some method in vertx that returns the deployment options by deployment id
and the possibility of updating it.

**Comment by tsegismont** [comment]
Updating deployment options live would mean possibly:

- changing the worker pool executor
- changing the classloader
- switching ha on or off

That does not make much sense.

If you want more instances without interrupting the service, you can create the new deployment before undeploying the existing one.
