### ISSUE TITLE
EventBus swallows original cause and only reports failureCode and message

### ISSUE THREAD

**Issue by glains** [eclipse-vertx/vert.x#4861]
The current implementation of `Message` swallows the original `Exception` instead of wrapping them into the `ReplyException`.
I am using the `EventBus` locally to route commands in my application and plan to add an exception mapper for REST.

The code and message currently used is not suficcient for my requirements.
```
default void fail(int failureCode, String message) {
    reply(new ReplyException(ReplyFailure.RECIPIENT_FAILURE, failureCode, message));
}
```

Workaround:
* Wrap an `.onFailure()` call around consumers and replace the body of the message with the exception
* Verify if the body is indeed that exception and proceed accordingly

Would it be reasonable to add the cause of the exception to the `ReplyException`?

**Comment by tsegismont** [comment]
The `ReplyException` codec does not encode the cause/stacktrace into account (we wouldn't be able to decode it back into an Exception).

A good practice is too log the exception with an id that you send as as part of the failure message

**Comment by glains** [comment]
Yeah, I already thought that decoding the message is not possible, but I am using a local codec here. That's why I thought it was possible to add it to the cause.

**Comment by tsegismont** [comment]
Then you can create a subclass of `ReplyException` and register a custom codec for it with `io.vertx.core.eventbus.impl.CodecManager#registerDefaultCodec`.

**Comment by magicprinc** [comment]
@tsegismont Here you are
https://github.com/eclipse-vertx/vert.x/pull/4865

**Comment by jakub-bochenski** [comment]
Why is this only targeted for 5.0.0? Couldn't this be merged to the 4.x branch?

**Comment by tsegismont** [comment]
@jakub-bochenski this can be backported, indeed. I will take care of it.

**Comment by tsegismont** [comment]
@jakub-bochenski https://github.com/eclipse-vertx/vert.x/pull/5336

**Comment by ben1222** [comment]
Before 4.5.11, the `ReplyException` called `VertxException(String message)` instead of the `VertxException(String message, boolean noStackTrace)` so it was possible to call `initCause` afterwards to set the cause...
Now it actually backported both #4840 and this fix to the 4.x, which makes the `initCause` cannot be used.

That said, I do not have a better solution that can both remove the stacktrace and keep the `initCause` working... not sure why `Throwable` does not allow such use case...
