### ISSUE TITLE
Ability to configure Row for returning booleans instead of Byte in MySQL reactive client

### ISSUE THREAD

**Issue by olofumark** [eclipse-vertx/vert.x#4889]
#### Describe the feature

io.vertx.sqlclient.Row needs a way to specify preference for the retrieval of all boolean columns as booleans instead of Byte.

Currently all boolean columns are served as Byte unless you explicitly call getBoolean() for individual fields.

#### Use cases

1. Reading data and streaming without having to do extra conversions.
2. Consistency with query expectations e.g after doing SELECT * FROM ... WHERE sent = true; only to be served the Byte equivalent of the boolean fields which(though might be the low level storage format) is not very helpful unless first converted.
3.  Very helpful for migrating from the legacy JDBC client if you already have frontend systems relying on true and false where they will break if suddenly served with 0's and 1's.

#### Contribution

enhancement.

**Comment by olofumark** [comment]
This is actually a feature request NOT a bug.

i was unable to post it as a feature request when i click the submit button under feature request, it does nothing.

**Comment by tsegismont** [comment]
Thanks for filing this enhancement request @olofumark 

Actually, this is the wrong project to discuss it. Would you mind filing it to https://github.com/eclipse-vertx/vertx-sql-client ?
