### ISSUE TITLE
Is dns lookup async on vertx4.x HttpClient?

### ISSUE THREAD

**Issue by leungchao** [eclipse-vertx/vert.x#4905]
I use vertx4.x, I have found the same problem with other async HttpClient, has the vertx http client solved this problem? or still needed resolve hosts asynchronously using the Vert.x DNS client ?

_Originally posted by @leungchao in https://github.com/eclipse-vertx/vert.x/issues/1107#issuecomment-1759161604_

**Comment by vietj** [comment]
can you elaborate what you found ? check if the vertx resolver is not disabled through a system property
