### ISSUE TITLE
Metrics vertx_http_client_active_requests guage can't decrease zero

### ISSUE THREAD

**Issue by Bugxyb** [eclipse-vertx/vert.x#4936]
### Version

Vert.x 4.4.6

### Context
we use vert.x metrics to count http client active request, and we see the gauge value increase. I stop send traffic to server instance, when the active connections is zero, the  vertx_http_client_active_requests guage is not zero.

### Extra
![image](https://github.com/eclipse-vertx/vert.x/assets/6049660/aa14ad56-cd01-4a42-a4dd-7de972d7a089)

1. we scrape the vertx_http_client_active_request and vertx_http_client_active_connections.
2. find the vertx_http_client_active_connections is around 900, but vertx_http_client_active_request continue to increase.
3. we stop traffic when vertx_http_client_active_connections to zero, but vertx_http_client_active_request is equal 4873.

It seems these requests did not successfully call the metrics decrease.

**Comment by tsegismont** [comment]
Can you confirm Vert.x Micrometer is your Metrics SPI implementation? In this case, can you open the issue in the corresponding repository? https://github.com/vert-x3/vertx-micrometer-metrics/

**Comment by Bugxyb** [comment]
> Can you confirm Vert.x Micrometer is your Metrics SPI implementation? In this case, can you open the issue in the corresponding repository? https://github.com/vert-x3/vertx-micrometer-metrics/

yes, we use the vert.x micrometer. and I open the issue in Vert.x Micrometer
![image](https://github.com/eclipse-vertx/vert.x/assets/6049660/cd0faa28-cca8-4710-8f5d-98f9cceec012)

![image](https://github.com/eclipse-vertx/vert.x/assets/6049660/e5b9d1ac-87a6-43a2-bff2-d16ee5bc94f2)

**Comment by tsegismont** [comment]
Thank you
