### ISSUE TITLE
how to add netty traffic handler？

### ISSUE THREAD

**Issue by 1ssqq1lxr** [eclipse-vertx/vert.x#4981]
### Questions

Do not use this issue tracker to ask questions, instead use one of these [channels](https://vertx.io/community/). Questions will likely be closed without notice.

### Version

Which version(s) did you encounter this bug ?

### Context

I encountered an exception which looks suspicious while ...

### Do you have a reproducer?

A reproducer is a simple project hosted on GitHub (or another forge supporting git clone operation) that has a build file that can be executed to reproduce the issue.

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

* Link to github project/gist

### Steps to reproduce

1. ...
2. ...
3. ...
4. ...

### Extra

* Anything that can be relevant such as OS version, JVM version

**Comment by vietj** [comment]
Look at traffic shaping options on TCPSSLOptions
