### ISSUE TITLE
io.vertx.core.streams.impl.PumpImpl#pump: endHandler → end

### ISSUE THREAD

**Issue by magicprinc** [eclipse-vertx/vert.x#4986]
`io.vertx.core.streams.impl.PumpImpl` doesn't connect 
`ReadStream.endHandler` (source) to `WriteStream.end` (destination)

If you mix it with Reactive "bridges" It hangs in an endless wait,
because Flow.Subscriber#onComplete isn't called.

Manual wiring before pump() helps:
`readStream.endHandler(none->writeStreamToPub.end());`

**Comment by magicprinc** [comment]
@jponge @cescoffier It could affect some Mutiny/Zero/Vert.x-Bindings too

**Comment by magicprinc** [comment]
pipeTo works like a charm!
Examples show mostly Pump 🤷‍♀️
Thank You!

**Comment by vietj** [comment]
examples should be corrected :-)

**Comment by tsegismont** [comment]
Filed https://github.com/vert-x3/issues/issues/642
