### ISSUE TITLE
try catch not work with virtual threads await

### ISSUE THREAD

**Issue by zclcs** [eclipse-vertx/vert.x#5005]
### Version
4.5.0

**Comment by zclcs** [comment]
![image](https://github.com/eclipse-vertx/vert.x/assets/50291896/36d8bcbc-0cd8-4286-830f-3ae67b61bb80)
![image](https://github.com/eclipse-vertx/vert.x/assets/50291896/6e71a1b4-28e6-4557-bc7f-10671146dbf5)

**Comment by magicprinc** [comment]
@vietj see, it is the https://github.com/eclipse-vertx/vert.x/issues/4854

**Comment by magicprinc** [comment]
@zclcs You should catch Throwable, not Exception

**Comment by zclcs** [comment]
> Throwable

okay, got it, ths

**Comment by zclcs** [comment]
close
