### ISSUE TITLE
httpClientOption.setConnectTimout is not work when connectionPool is full

### ISSUE THREAD

**Issue by axeBig** [eclipse-vertx/vert.x#5019]
### Questions

httpClientOption.setConnectTimout is not work when connectionPool is full。

### Version

4.5.0

### Steps to reproduce

1. init httpclient with option connectTimeout(3000),maxPoolSize(1)
2. send request, and set OnFail and  onSuccess callback.
3. after send sevel request, when connection pool is full, i can not get onFail after 3000ms

**Comment by tsegismont** [comment]
Thanks for sharing reproduction steps, we'll look into it

**Comment by tsegismont** [comment]
In fact we have made changes in Vert.x 4.5.0 which help clarify the behavior of different timeouts (see #4937)

If you want the HTTP Client to fail a request if no data has been received in a timely manner, use `new RequestOptions().setTimeout(myValue)`
