### ISSUE TITLE
Vertx EventBus And HazelCast Scaling

### ISSUE THREAD

**Issue by Areeb-Gillani** [eclipse-vertx/vert.x#5023]
### Background
I am using Vertx 4.4.5 in my project. I have created a few services and achieved a 3k TPS with 11 microservices on an 18 core VM running on Dell R730 with OS RHEL 9. Each request cycle has multiple read and writes on database as well as on Redis. Redis and Database are on the same machine but on different VM.

### Problem
The message size was around 1kb when the TPS was 3k. Whereas, when I increase the message size to approx. 100kb which is to be considered an average production message size. The TPS dropped to 600. I checked the logs and found that event bus's consumer is getting the message after a few seconds delay. I googled and found that event bus is not designed for large messages so I used shared data to write my 100kb message on an async map and used the event bus to send the apiKey only for identification and fetching purpose. So, on my next service I fetch that data using that apiKey from the shared data map, asynchronously.

### Setup
The problem is from service A (ApiGateWay) to B (BusinessService) I write all the 100kb in shared data and upon completion of writing the data on shared data

### Config
```java
map.put(.., ..).onCompelete(res->{
if(res.succeed()){
   eventBus.request(.., .., ..);
}
});
```
I called the event buss using
```java
eventBus.request(.., .., ..);
```
to send data to next service, whereas on the other service the consumer receives this message after the same delay which was before when I was using event bus and not shared data. I have also set the message buffer of consumer as well to 10k.
```java
eventBus.consumer(.., ..).setMaxBufferedMessages(10000);
```
Am I missing something? Some other configs are:
```config
WorkerInstances on A -> 100 WorkerPoolSize on A -> 100

WorkerInstances on B -> 100 WorkerPoolSize on B -> 100
```

I have also tried to scale hazelcast when starting service A and B using
```config
 -Dhazelcast.socket.receive.buffer.size=10240 -Dhazelcast.socket.send.buffer.size=10240
```
### Load Run Details

Jmeter
7000 Threads
100 loop count
0.7s Ramp up
1000ms Constant Delay

Thanks for your help in advance. Cheers!

**Comment by tsegismont** [comment]
Sorry, it's not clear what your question is. I understand what you've tried with asyncmap, but what is the problem you've found with this solution?

**Comment by Areeb-Gillani** [comment]
Thanks for the reply. The problem is that even when I offloaded the 100KB message from the eventbus the eventbus is still slow and the consumer on the second service is getting the message from the sender on the first service after around 6 seconds. This delay nearly same as when I was using eventBus to transfer the data to second service. I am asking that does sharedData put the same load on the cluster just like eventbus which is why the delay is nearly same.

**Comment by Areeb-Gillani** [comment]
I found the issue of the delay. It was because of a memory leak as I was not evicting the record from the hazel cast memory after my request is complete. Whereas, now I have checked my code and no memory leak is available.
After a careful analysis, I have found that even after I stop the load run from the Jmeter my CPU usage stays high with some high very spikes as well. This pattern stays like this after each load run there are no new logs printing in that time. It means that the hazelcast cluster is doing something. Do you have any insight about it? BTW, thanks for the hint in your question where you said that this is the solution and what is wrong with it. Thanks for that.

**Comment by tsegismont** [comment]
I can't tell for sure what HZ does, perhaps to find more info could you activate debug logging?

Anyway, thanks for keeping us informed about the outcome.

**Comment by Areeb-Gillani** [comment]
Dear @tsegismont, 
SharedData's put is taking 6.2 seconds to write 100kb json object. All the nodes are on the same VM. Is there any performance tuning that is not enabled by default.
Thanks in advance.
