### ISSUE TITLE
Using FileSystem closes all the ressources when using an URLClassLoader

### ISSUE THREAD

**Issue by adrien-aubert-drovio** [eclipse-vertx/vert.x#5043]
### Version

4.5.1

### Context

When deploying a verticle using an URLClassLoader (when loading classes from a JAR file), using the vertx.fileSystem() to read files/directories will close the opened resources related to the JAR file once the operation completes. For example, if an InputStream is opened to read a file from the JAR file, the InputStream will be closed as well, even if it is still in use.

There is no problem with version 4.4.6 of Vertx.

### Do you have a reproducer?

https://github.com/adrien-aubert-drovio/vertx-url-class-loader-read-file/tree/main

### Extra

Tested on MacOs with Java 11 and 17.

**Comment by vietj** [comment]
thanks for reporting, this is a regression
