### ISSUE TITLE
epoll TPS test

### ISSUE THREAD

**Issue by zclcs** [eclipse-vertx/vert.x#5051]
### Questions

Why did the TPS decrease after using the epoll strategy?

### Version

4.5.1

### Context

![image](https://github.com/eclipse-vertx/vert.x/assets/50291896/d877c555-1df5-4bbf-8af1-b0594c43dea8)

### Do you have a reproducer?

https://github.com/zclcs/vertx-netty-epoll

### Extra

OS: linux
JVM: 17

**Comment by zclcs** [comment]
the first one is use epoll, second one is not

**Comment by tsegismont** [comment]
Can you please attach instructions for:

- building the application
- running with and without epoll support
- running the benchmark

Thank you

**Comment by zclcs** [comment]
> Can you please attach instructions for:
> 
> * building the application
> * running with and without epoll support
> * running the benchmark
> 
> Thank you

Already tested with jmter

**Comment by tsegismont** [comment]
If don't have all the details necessary to reproduce, we can't look into this
