### ISSUE TITLE
Metrics for Prometheus doesn't work when using Vert.x launcher

### ISSUE THREAD

**Issue by jt-aztech** [eclipse-vertx/vert.x#5067]
Tested this using: Vert.x 4.5.1 or 4.4.0

While trying to add prometheus metrics to a vert'x application the metrics doesn't work when using Vert.x launcher.

Steps to reproduce

1. Download the project here: https://how-to.vertx.io/metrics-prometheus-grafana-howto/
2. Run it normally and the metrics is exposed here: http://localhost:8080/metrics
3. No setup vert.x Launcher and run the project again and when you go to: http://localhost:8080/metrics you get a response of http code 500 with message: Invalid registry: null

Tested this on ubuntu Ubuntu 20.04.6 LTS with java 17(see attached screenshot of vert.x launcher configurations).
![Screenshot from 2024-01-13 20-01-44](https://github.com/eclipse-vertx/vert.x/assets/156491732/2ec4d455-668a-460a-9573-a5c5b2ce26c2)

**Comment by tsegismont** [comment]
Can you please report this to the repository which contains the how-to sources ? THank you

**Comment by jt-aztech** [comment]
@tsegismont sorry, which repository is that?
