### ISSUE TITLE
Pool metrics not appearing

### ISSUE THREAD

**Issue by sksamuel** [eclipse-vertx/vert.x#5073]
The docs indicate that there should be worker pool metrics
https://vertx.io/docs/vertx-micrometer-metrics/java/#_vert_x_pool_metrics

But adding micrometer metrics does not expose these:

```kotlin
  VertxOptions()
            .setMetricsOptions(
               MicrometerMetricsOptions()
                  .setEnabled(true)
                  .setMicrometerRegistry(registry)
            )
```

**Comment by tsegismont** [comment]
Can you please report this to the corresponding [repository](https://github.com/vert-x3/vertx-micrometer-metrics/) with a reproducer? Thank you
