### ISSUE TITLE
handle of SNI has a problem

### ISSUE THREAD

**Issue by zb564739784** [eclipse-vertx/vert.x#5091]
### Questions
serverNameMapping method of io.vertx.core.net.impl.SslChannelProvider Class：

```
  public AsyncMapping<? super String, ? extends SslContext> serverNameMapping() {
    return (AsyncMapping<String, SslContext>) (serverName, promise) -> {
      workerPool.execute(() -> {
              ···
          int idx = idx(useAlpn);
          SslContext sslContext = sslContextMaps[idx].computeIfAbsent(serverName, s -> sslContextProvider.createServerContext(kmf, trustManagers, s, useAlpn));
          promise.setSuccess(sslContext);
        }
      });
      return promise;
    };
```
sslContextMaps[idx] add no restrictions based on **"serverName"**，If the client keeps making fake **"serverName"** it will cause memory leaks in sslContextMaps[idx]

### Version

<vertx.version>4.5.1</vertx.version>

**Comment by vietj** [comment]
Thanks, this has been fixed by https://github.com/eclipse-vertx/vert.x/pull/5100 that will be released in Vert.x 4.5.3
