### ISSUE TITLE
Verticle getting deployed in Event Model when its setup for Worker Model using Deployment Options.

### ISSUE THREAD

**Issue by denis-mirchandani** [eclipse-vertx/vert.x#5111]
Use Case: 

We are using Deployment Options to create Worker Model specific options. 
We are using Vertx Runner to bootstrap the MainVerticle which uses Vertx Run Command to do so. 
The issue is the following : the RunCommand uses setWorker(boolean) [see below] to try to setup the worker model, but in the deployment options method the check seems to be incorrect as it is comparing the boolean (worker) parameter to thread model enum value which will always be false and hence result in Event Model being chosen. 

I can see this has been removed from the Master. 

I am currently using 4.5.3 version but the same issue  is also in 4.5.1. 

Please can you have a look. 

Thank you

Code reference  (branch 4.5.3) : 

https://github.com/eclipse-vertx/vert.x/blob/ce654726ce4c7642143258c78b3f8992be99e3c7/src/main/java/io/vertx/core/DeploymentOptions.java#L165C10-L165C25

https://github.com/eclipse-vertx/vert.x/blob/ce654726ce4c7642143258c78b3f8992be99e3c7/src/main/java/io/vertx/core/impl/launcher/commands/RunCommand.java#L258C51-L258C57

**Comment by tsegismont** [comment]
Can you provide a small reproducer please?

**Comment by tsegismont** [comment]
Closing, please reopen if you can provide a reproducer
