### ISSUE TITLE
OutOfMemoryException after CRL update

### ISSUE THREAD

**Issue by vemidjo** [eclipse-vertx/vert.x#5139]
### Questions
 
Updating SSLOptions with new CRL list Buffer causes memory leak and Java Heap OutOfMemoryException.
 
### Version
 
4.4.3
 
### Context
 
A periodic task fetches new CRLs from the server every 10 minutes. After a few days, the application crashes with OutOfMemoryException. I used VisualVM to try to detect what is a problem, and I saw there are a lot of VertxUnsafeHeapByteBuf objects and X509CRLImpl objects. Attached are the screenshots of the heap stats and heap dump file.
 
### Steps to reproduce
 
1. Create io.vertx.core.http.HttpServer object
2. Create io.vertx.core.net.SSLOptions object and call addCrlValues(someBufferWithCrlValues)
3. Pass the SSLOptions object through the HttpServer updateSSLOptions method.
4. Repeat steps 2 and 3 in while loop periodically
 
### Extra
 
I updated my Vert.x version from 4.4.0 to 4.5.3, and found this problem. After a lot of tests, I found that versions until 4.4.2 work well, but versions from 4.4.3 to the newest one have the same problem.
![img_1](https://github.com/eclipse-vertx/vert.x/assets/161595426/0b5ce70d-3f5d-47b3-9c06-b3b2b78556d6)
![img_2](https://github.com/eclipse-vertx/vert.x/assets/161595426/79621c20-b7ed-4b8f-b367-527428ab160c)

**Comment by vietj** [comment]
can you provide a reproducer project ?

**Comment by vemidjo** [comment]
Yes. This [link](https://github.com/vemidjo/vertx) contains a reproducer project. It has a main class that periodically loads a CRL from resources. In reality, the CRL will be fetched from a server that updates it after a certificate has been revoked.
