### ISSUE TITLE
Configurable socket keep alive interval

### ISSUE THREAD

**Issue by aksabg** [eclipse-vertx/vert.x#5163]
`NetServer` now supports `tcpKeepAlive` flag which is translated to Netty's `SO_KEEPALIVE` flag. However, the keepalive interval, idle time and count cannot be set through settings, which means it defaults to OS values (usually the idle time is 2 hours).

When using `NetServer` in conjuction with the AWS load balancer, the connections are closed when idle for more than 350 seconds.

The following Netty fields should be supported in `NetServerOptions`:

1. TCP_KEEPIDLE
2. TCP_KEEPINTVL
3. TCP_KEEPCNT

Reference: https://github.com/reactor/reactor-netty/issues/2167

**Comment by aksabg** [comment]
@vietj I can add this feature, just need the permission to branch.

**Comment by vietj** [comment]
@aksabg please contribute it via a pull request

**Comment by aksabg** [comment]
@vietj I don't have permissions to create a remote branch required for a pull request.

**Comment by jakub-id** [comment]
@vietj any chance to get this merged? This is a PITA to configure externally on Kubernetes < 1.29 where configuring these defaults via sysctl is considered unsafe.

**Comment by vietj** [comment]
@jakub-id the issue is that the PR does not have an eclipse agreement signed

**Comment by jakub-id** [comment]
@vietj I saw that but the Eclipse report is weird as her email is mentioned once in the green box and three times in the red box. Unless it's a different email but it doesn't look like it.

**Comment by aksabg** [comment]
@vietj @jakub-id I have signed the agreement (https://accounts.eclipse.org/users/vealrad) 
Is there anything else I need to do?

**Comment by jakub-id** [comment]
@aksabg Great! Can you remove the JavaDoc formatting changes and empty new lines as @vietj asked on the PR?

**Comment by vietj** [comment]
where is the PR ?

**Comment by aksabg** [comment]
@vietj 
https://github.com/eclipse-vertx/vert.x/pull/5183
