### ISSUE TITLE
BlockedThreadChecker does not check a parking event loop virtual thread

### ISSUE THREAD

**Issue by azurvii** [eclipse-vertx/vert.x#5175]
### Questions

Parking event loop virtual threads are not getting `Thread blocked` warning messages.

### Version

4.5.7

### Do you have a reproducer?

```java
public final class NoBlockedWarningExample extends AbstractVerticle {
  @Override
  public void start() throws Exception {
    System.out.println("Starting NoBlockedWarningExample.");
    vertx.setTimer(
        2000,
        event ->
            System.out.println(
                "This should be printed after 10s, not 2s. Since the event loop is blocked."));
    Thread.sleep(10000);
    System.out.println(
        "Ending NoBlockedWarningExample. It should have no thread blocked warning messages.");
  }

  public static void main(String[] args) throws ExecutionException, InterruptedException {
    final Vertx vertx = Vertx.vertx();
    vertx
        .deployVerticle(
            NoBlockedWarningExample.class,
            new DeploymentOptions().setThreadingModel(ThreadingModel.VIRTUAL_THREAD))
        .toCompletionStage()
        .toCompletableFuture()
        .get();
    vertx.close();
  }
}
```

### Steps to reproduce

- Run `NoBlockedWarningExample::main`
- I would expect a `Thread blocked` stack trace, since `Thread.sleep()` should park the virtual thread. But no warning messages are logged. And the 2s-timer helps to confirm that the event loop is actually blocked.
- Removing `.setThreadingModel(ThreadingModel.VIRTUAL_THREAD)` gets the blocked warning messages printed, as expected.

**Comment by vietj** [comment]
that is expected, the goal of the checker is to check threads which should not be blocked (like event-loop) or resources (worker threads) only.

**Comment by azurvii** [comment]
This *is* an event loop (I have a 2s timer example to show that the events are blocked), and should not be blocked for long. The special thing is that it's running on a virtual thread. It does provide some special powers like `Future.await()`, but should not affect its *role* as an event loop.

Virtual threads make blocking effective, and `Future.await()` makes events flow while parking. However, lots of other things are out of our control, e.g. maybe JDBC. I don't think block checker makes sense for `Future.await()`, since the events are flowing and vertx is happy, but for non-`Future.await()`ed parking/blocking, this could serve the same helpful insights as it does for non-virtual thread verticles.

**Comment by vietj** [comment]
can you print the current thread to check it is an event-loop thread ?

**Comment by azurvii** [comment]
Both the verticle `start` code and the timer handler code run on `vert.x-virtual-thread-x`, not `vert.x-eventloop-thread-x`.
Example and output:

Code adjusted from previous post:
```java
public final class NoBlockedWarningExample extends AbstractVerticle {
  @Override
  public void start() throws Exception {
    System.out.println(Instant.now() + " Starting on " + Thread.currentThread());
    vertx.setTimer(
        2000,
        event -> System.out.println(Instant.now() + " Timer handler on " + Thread.currentThread()));
    Thread.sleep(10000);
    System.out.println(Instant.now() + " Ending on " + Thread.currentThread());
  }

  public static void main(String[] args) throws ExecutionException, InterruptedException {
    final Vertx vertx = Vertx.vertx();
    vertx
        .deployVerticle(
            NoBlockedWarningExample.class,
            new DeploymentOptions().setThreadingModel(ThreadingModel.VIRTUAL_THREAD))
        .toCompletionStage()
        .toCompletableFuture()
        .get();
    vertx.close();
  }
}
```
Output:
```
2024-04-02T11:49:54.390115484Z Starting on VirtualThread[#23,vert.x-virtual-thread-0]/runnable@ForkJoinPool-1-worker-1
2024-04-02T11:50:04.412018302Z Ending on VirtualThread[#23,vert.x-virtual-thread-0]/runnable@ForkJoinPool-1-worker-1
2024-04-02T11:50:04.423519593Z Timer handler on VirtualThread[#23,vert.x-virtual-thread-0]/runnable@ForkJoinPool-1-worker-1
```

**Comment by vietj** [comment]
unfortunately a vertx virtual thread is not an event loop thread

**Comment by vietj** [comment]
@azurvii yes because those are vertx managed resources, virtual threads are fully managed by the JVM (I wish we had more control on them)

**Comment by azurvii** [comment]
I'll be very careful where `vertx.setTimer()` and friends is called. Or just make everything fast enough.

> I wish we had more control on them

My point was that `Future.await()` is already a very good control. My thinking was to reset the `BlockedThreadChecker` timer when starting `await()` and start a new timer when returning from `await()`. All other JVM managed thread parking activities are timed as if it's just running regular code. Since `BlockedThreadChecker`'s concern should be how long the event loop / task queue is blocked, when it's not `await()` parking, it does not matter whether the thread is parked by JVM or actually executing code, they are "blocked" in `BlockedThreadChecker`'s point of view. So we don't need "more control" to time them.
