### ISSUE TITLE
route BodyHandler before ProxyHandler, response [ERROR] [2024-04-17 18:57:27] ?.?(?) | Connection was closed

### ISSUE THREAD

**Issue by cloudAndMonkey** [eclipse-vertx/vert.x#5188]
### Questions
HttpClientOptions clientOptions = new HttpClientOptions();
HttpClient proxyClient = VERTX.createHttpClient(clientOptions);
HttpProxy proxy = HttpProxy.reverseProxy(proxyClient);
proxy.originSelector(request -> Future.succeededFuture(resolveOriginAddress(request)));

mainHttpRouter.route().**handler(BodyHandler.create()).handler(ProxyHandler.create(proxy));**

<img width="1019" alt="image" src="https://github.com/eclipse-vertx/vert.x/assets/12228225/6bde9c70-ee93-4cc7-ab59-ac28226020b1">
postman loading long time, console return error
[ERROR] [2024-04-17 18:57:27] ?.?(?) | Connection was closed

### Version
4.5.7

**Comment by tsegismont** [comment]
Please try again without the body handler added to the route.

**Comment by tsegismont** [comment]
Reopen with detailed steps to reproduce if the tip above does not solve the problem
