### ISSUE TITLE
Getting HttpClosedException: Connection was closed for alternate HTTP API calls

### ISSUE THREAD

**Issue by Bhuvnesh021** [eclipse-vertx/vert.x#5199]
Hi 
I am getting HttpClosedException on alternate basis.  
Basically I am doing two API calls in single context and my first time is taking around 3-4 seconds so after getting success If I am again doing same call this time request is failing with this exception. 
Below is the configurations which I am using.

IDLE_TIMEOUT=5 Seconds
KEEP_ALIVE_TIMEOUT=60 Seconds
KEEP_ALIVE=true
MAX_POOL_SIZE=50
CONNECTION_TIMEOUT=5 Seconds

### Version
4.5.3

### Do you have a reproducer?

YES

**Comment by tsegismont** [comment]
Can you please share the link to the reproducer?

**Comment by tsegismont** [comment]
Cannot reproduce
