### ISSUE TITLE
Vertx Compatibility issue

### ISSUE THREAD

**Issue by RitikaLaddha** [eclipse-vertx/vert.x#5210]
hazelcast.version: 4.4.6
quarkus.platform.version: 3.6.6
vertx.version: 4.4.5

Are these three versions compatible with each other?

[Link to community question with detailed logs](https://hazelcastcommunity.slack.com/archives/C015Q2TUBKL/p1716386923803379)

**Comment by vietj** [comment]
can you open this issue here https://github.com/vert-x3/vertx-hazelcast
