### ISSUE TITLE
Vertx in native image throws error : This java rumtime does not support virtual threads

### ISSUE THREAD

**Issue by sanIncredible** [eclipse-vertx/vert.x#5249]
### Version

vertx 4.5.8 , graalvm 21.0.3 , native-maven-plugin 0.10.2

### Do you have a reproducer?
steps to reproduce:

1. register verticle as ThreadingModel.VirtualThread
2. start the application
3. error thrown

failed to deploy verticle : verticle :: io.vertx.core.impl.NoStackTraceThrowable: This java runtime does not support virtual thread

**Comment by william-aqn** [comment]
me2
This Java runtime does not support virtual threads
io.vertx.core.impl.NoStackTraceThrowable: This Java runtime does not support virtual threads

FAILURE: Build failed with an exception.

**Comment by surajkumar** [comment]
I think it's happening because Vert.x uses reflection under the hood to determine if virtual threads are supported. What you'll have to do is figure out what goes inside `reflect-config.json` however you might be able to find this out by looking around at how Quarkus got around the issue.

**Comment by vietj** [comment]
@sanIncredible we do have a classifier image for this "native-image-jar"

**Comment by vietj** [comment]
https://repo1.maven.org/maven2/io/vertx/vertx-core/4.5.10/vertx-core-4.5.10-native-image.jar
