### ISSUE TITLE
Support Marker for Logger spi.

### ISSUE THREAD

**Issue by curtiseng** [eclipse-vertx/vert.x#5251]
#### Read me

Read this first before creating an issue:

- do not use this issue tracker to ask questions, instead use one of these [channels](https://vertx.io/community/). Questions will likely be closed without notice.
- you shall create a feature request only when it is general purpose enough.
- make sure that the feature is not already

#### Describe the feature

Logger.info(MarkerFactory.getMarker("BUSINESS"), "message: {}", params);

#### Use cases

We use marker filter to split log to different file for trace and metrics.

#### Contribution

I have no idea now, maybe i can use slf4j logger?

**Comment by vietj** [comment]
The logger SPI should only be used by vertx components and not applications which instead should use the logger of their choice.
