### ISSUE TITLE
Access the vertx instance from HttpClient objects

### ISSUE THREAD

**Issue by wzy1935** [eclipse-vertx/vert.x#5261]
Refers to https://github.com/eclipse-vertx/vertx-http-proxy/pull/92

Hi, I'm contributing the API in `vertx-http-proxy` and there's a method I need to access the `vertx` instance from the `HttpClient` object, but currently there's no way to do this.

It could if we export the `HttpClientInternal` interface, by moving it from  `io.vertx.core.internal.http.impl` to `io.vertx.core.internal.http`, then I can call it like this:

```java
// client is an instance of HttpClient
Vertx vertx = ((HttpClientInternal) client).vertx();
```

Should we perform this change? I can make a PR for it.

**Comment by vietj** [comment]
right, this has not been done yet, will do that very soon @wzy1935
