### ISSUE TITLE
HAManager couldn't see quorum if during its initialization cluster manager has all nodes joined already

### ISSUE THREAD

**Issue by apanasevich** [eclipse-vertx/vert.x#5272]
### Version

4.5.7

### Context

My app is based on Vert.x  with embedded Hazelcast cluster manager. When I run several instances of the app with HA mode enabled some instances cannot deploy HA verticles, and logs show that they have not attain quorum:  `Quorum not attained. Deployment of verticle will be delayed until there's a quorum.` 

But actually they have.

The problem is that Hazelcast cluster could be in a state when all nodes have already joined at the moment when `HAManager` initialization starts. So `HAManager`s method  `nodeAdded` will never be called. Also `checkQuorum` method called on `init` see all nodes from `clusterManager`, but `clusterMap` do not contain information from all nodes. They will put it in several milliseconds later of course, but `checkQuorum` method will be completed at that time and never be called again.

### Steps to reproduce

It just occurs in some cases.

**Comment by apanasevich** [comment]
I've created the PR, but I'm not sure that the target branch is correct. It'll be great to see a fix in some of `4.5.*` versions

**Comment by apanasevich** [comment]
Hi @vietj 

thank you for reviewing ang merging the PR to the main branch.

Should I create a new PR to fix vertion 4.5.*? It'll be great to get it fixed in production.

**Comment by vietj** [comment]
can you provide a PR for backport ?

**Comment by apanasevich** [comment]
> can you provide a PR for backport ?

Sure. Will do it a litle bit later

**Comment by apanasevich** [comment]
Hi @vietj 

I've created the PR for a backport
