### ISSUE TITLE
Instance Level Load Balancing of a  Subcriber in a PUB SUB Mode on the event bus

### ISSUE THREAD

**Issue by arunkumarck** [eclipse-vertx/vert.x#5275]
Example

- 1 Publisher Verticle P
- Vertcile Subscribers A and B
- Subscriber A has two Verticle instances

When data is received on the topic/event bus in pub sub mode, the data should be load balanced between the instances of subscriber A.

Note: 
1. Request Reply does not provide receiver agnostic programming
2. Request Reply is not the same as PUB SUB. 
3. It involves a response, even if left empty will need to be timed out which makes it a overhead.

**Comment by tsegismont** [comment]
This is by design of the eventbus.

If you require to have at most one consumer handling the published message, you must extract the consumer code in a separate verticle and deploy a single instance.
