### ISSUE TITLE
Export vert.x specific metrics when using Opentelemetry java agent.

### ISSUE THREAD

**Issue by amit-dream11** [eclipse-vertx/vert.x#5281]
Vert.x has multiple monitoring integrations like Micrometer and Dropwizard.

When using [Micrometer instrumentation](https://vertx.io/docs/vertx-micrometer-metrics/java/), we get a decent amount of vertx specific metrics like pool, sql, http and all the quantiles.
`vertx_http_server_response_time_seconds,  vertx_http_server_response_bytes, vertx_http_server_active_requests, vertx_pool_queue_pending, vertx_pool_ratio, vertx_http_server_requests_total `and many more.

On the other hand, when using [opentelemetry-java-agent](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar) jar for auto instrumentation, there are only 3 kinds of metrics which are being exported right now; i.e
`http.server.request.duration_count, http.server.request.duration_bucket and http.server.request.duration_sum`

Can we enable all the metrics (which are exported in Micrometer case) to be exported under opentelemetry-java-agent instrumentation as well ?

vert.x version used : 4.3.8

**Comment by vietj** [comment]
where is the opentelemtry java agent coming from ?

**Comment by vietj** [comment]
the vertx project does not maintain a metrics java agent (only tracing) and it seems the linked jar is coming from a third party project providing this implementation, it should be reported there
