### ISSUE TITLE
Undeployed Virtual Thread verticles cause memory leaks and/or never stop

### ISSUE THREAD

**Issue by zekronium** [eclipse-vertx/vert.x#5317]
With the current `VirtualThread` deployment model implementation few issues occur:

1. Upon context un-deployment, awaiting `virtual-threads` may not be notified of context closure/verticle undeployment
This happens when most commonly when the awaited promise is not a type of resource that throws exceptions on closure, this will leave the virtual thread waiting forever, which prevents GC from cleaning up any associated objects with it.

2. Since virtual threads can now loop on things, it would be relevant to know when a context is closed, although currently the API is slightly tedious to extract the `closeFuture` and check its close state. Also, current implementation does not employ the traditional sense of `Thread.isInterrupted` approach, which means whats typically expected from `Executors`, on shutdown to call `Thread.interrupt`, will not happen, because a shared `VirtualThreadWorkerExecutor` is used and its only shutdown when entire `Vertx` is closed or on JVM exit.

Both of these issues I think can be solved with the same approach, we need to expose a way to see when a verticle/context was closed, so we can stop looping, which can either be interrupting the `threadPerTask` executor. This also conveniently solves the first issue, since interrupting will unblock the `await`.

My creating a per `Verticle` with a per `Context` worker pool, that allows us to freely interrupt it in `DeploymentManager#doUndeploy`
```java
          context.runOnContext(v -> {
            Promise<Void> stopPromise = undeployingContext.promise();
            Future<Void> stopFuture = stopPromise.future();
            stopFuture.onComplete(ar -> {
              deployments.remove(deploymentID);
              if (context.threadingModel().equals(ThreadingModel.VIRTUAL_THREAD) &&
                context.executor() instanceof WorkerExecutor) {
                ((WorkerExecutor) context.executor()).interrupt();
              }
              verticleHolder.close(ar2 -> {
                if (ar2.failed()) {
                  // Log error but we report success anyway
                  log.error("Failed to run close hook", ar2.cause());
                }
                if (ar.succeeded()) {
                  if (context.threadingModel().equals(ThreadingModel.VIRTUAL_THREAD)
                    && context.executor() instanceof WorkerExecutor) {
                    ((WorkerExecutor) context.executor()).interrupt();
                  }
                  p.complete();
                } else if (ar.failed()) {
                  p.fail(ar.cause());
                }
              });
            });
```

Issue arrises that because there can be multiple virtual threads per context, odd race conditions occur, timers get set and that can also cause dangling resources. It is hard to pinpoint exactly what happens in my local testing. I think the `TaskQueue` needs special handling for this exit so that `VirtualThread`s that re-enter `TaskQueue` after interruption do not execute anything else.

Another option is to interrupt before running the `closeFuture`, but then making sure that no other tasks get executed is key, otherwise there will be no signal for the `VirtualThread` to stop

**Comment by vietj** [comment]
Do you have reproducers for this ? I suspect we indeed should scan the task queue to interrupt the pending threads there

**Comment by zekronium** [comment]
I can make some, although will be quite tedious due to encapsulation to query the remaining threads.

But the basic logic itself is clear, there are no interrupts. I tried in my own branch to interrupt after the close future runs, usually it is OK, but sometimes creates odd race conditions or for example triggers `.recover` future monad. In other cases interrupting before close future also allows graceful exit, but also has issues. 

Optimally if we could short circuit TaskQueue would be optimal, or completely jump the `await`

**Comment by vietj** [comment]
I would appreciate a reproducer

**Comment by zekronium** [comment]
Added some basic future tests. I can also setup more elaborate tests, especially nuances using `HttpClient` but this generally covers the base stepping stone. #5322 

https://github.com/eclipse-vertx/vert.x/blob/32d2bd834aeaaabcf13b16fd34b3056bd419a649/src/test/java/io/vertx/core/VirtualThreadContextTest.java#L244-L277

**Comment by vietj** [comment]
thank you I will look into it

**Comment by vietj** [comment]
@zekronium here is a mockup of what we should do https://github.com/eclipse-vertx/vert.x/pull/5339

**Comment by zekronium** [comment]
I will test it and report if this works in our usage aswell

**Comment by vietj** [comment]
wait a little until I provide a more robust solution @zekronium

**Comment by vietj** [comment]
@zekronium I pushed a solution that seems ok to me do you mind testing the branch ?

**Comment by zekronium** [comment]
May you rebase on 4.x?
