### ISSUE TITLE
Http1xServerConnection doesn't set the Vert.x context when recording metrics

### ISSUE THREAD

**Issue by ahus1** [eclipse-vertx/vert.x#5355]
### Version

4.5.10 (relevant code seems to be unchanged in main)

### Context

As part of Keycloak 26, I'm running Quarkus 3.15.1 which include Vert.x 4.5.10. When I enable Quarkus Metrics and OpenTelemetry, I expect Exemplars to be recorded. Unfortunately that doesn't happen, as `Http1xServerConnection` doesn't set the context, and `OpentelemetryExemplarSamplerProvider` expects it to be set.

See https://github.com/quarkusio/quarkus/issues/43845

### Do you have a reproducer?

https://github.com/ahus1/quarkus-otel-missing-examplar-example

### Steps to reproduce

See https://github.com/quarkusio/quarkus/issues/43845

1. Start Keycloak 26.0.0 and enable Metrics and OpenTelementry
2. Login to issue some HTTP requests
3. Retrieve metrics from the metrics endpoint using CURL

### Extra

Running on JDK 17 on Windows. Seems be independent of JDK version and Windows. 

In a locally patched version, I was able to fix it by updating 

https://github.com/eclipse-vertx/vert.x/blob/1e2fdf820be9628af2576c0f32828802111855b1/vertx-core/src/main/java/io/vertx/core/http/impl/Http1xServerConnection.java#L265-L270

to wrap the calls for metrics in ` request.context.dispatch()`. 

I'll prepare a draft PR to discuss this. As this is named `Http1x`, I suspect there might be other code for HTTP/2.0

**Comment by ahus1** [comment]
Added a reproducer: https://github.com/ahus1/quarkus-otel-missing-examplar-example

**Comment by ahus1** [comment]
Closing as it will be handled on the Quarkus side. Sorry for the noise!

**Comment by tsegismont** [comment]
No worries !
