### ISSUE TITLE
`JsonArray.contains(JsonObject / JsonArray)` returns `false`, in case `JsonObject` / `JsonArray` is represented as `Map` / `List` internally

### ISSUE THREAD

**Issue by kristian** [eclipse-vertx/vert.x#5397]
If you want to check whether a `JsonArray` contains a certain `JsonObject` or other `JsonArray` you may wrongly assume you can use the `contains` method. However as sometimes a `JsonObject` / `JsonArray` is represented as a `Map` or `List` in the internal `JsonArray` list, `contains` might return `false` even though semantically it should return `true`. Minimal reproducible example:

```java
JsonArray jsonArray = new JsonArray("[{\"foo\":\"bar\"}]");
System.out.println(jsonArray.contains(new JsonObject().put("foo", "bar"))); // false

System.out.println(jsonArray.contains(new JsonObject().put("foo", "bar").getMap())); // true
System.out.println(jsonArray.stream().anyMatch(obj -> obj.equals(new JsonObject().put("foo", "bar")))); // true
```

My assumption would be that the `contains` function behaves similarly to the `contains` function of the `List` interface, where it is documented that it returns `true` in case:

> Returns true if this list contains the specified element. More formally, returns true if and only if this list contains at least one element e such that (o==null ? e==null : o.equals(e)).

Which is not the case for the `contains` function of the `JsonArray`. So I would suggest this should be either treated as a bug, or the behaviour should be documented in the JavaDoc of the `contains` function.

**Comment by tsegismont** [comment]
Thanks for detailed report @kristian . Would you like to propose a PR ?

**Comment by kristian** [comment]
@tsegismont PR #5398 👍
