### ISSUE TITLE
Vert.x event bus - Unix Domain Socket Event Bridge Support Option - Which helps processes communicate within the same K8s container using event bus

### ISSUE THREAD

**Issue by arunkumarck** [eclipse-vertx/vert.x#5403]
The event bus in vert.x is extensible within the same unix k8s container using TCP.
The issue with TCP is that it has to go through an entire stack and when two processes are communicating within the same container that are polyglot like Python and Vertx itself over the event bus, tcp becomes a performance bottleneck.

Hence request that a Unix domain socket option be given for the event bus of vertx so that the performance between processes using the event bus within the same container is maximized trememdously.

This will make it more cloud friendly, the trend today

**Comment by vietj** [comment]
do you mean a bridge exposing a domain socket ?

**Comment by vietj** [comment]
e.g. https://github.com/vert-x3/vertx-tcp-eventbus-bridge

**Comment by arunkumarck** [comment]
> do you mean a bridge exposing a domain socket ?

Yes. That's correct. This will improve the performance to 4x or 6x and help do AI or other stuff for example in python using tensorflow or others using unix domain bridge for the event bus within the same container.

**Comment by vietj** [comment]
can you open the issue in the project https://github.com/vert-x3/vertx-tcp-eventbus-bridge ?
