### ISSUE TITLE
Vertx 5 migration documentation

### ISSUE THREAD

**Issue by rzorzorzo** [eclipse-vertx/vert.x#5416]
#### Describe the feature

I am trying to migrate an application from vert.x 4 to 5.
The current documentation on:
https://github.com/vert-x3/wiki/wiki/5.0.0-Deprecations-and-breaking-changes
does not include many deprecated methods and classes.

Please provide a migration documentation. This will help many users save time searching for solutions.

#### Use cases

examples: 

- RoutingContext.user() now returns ContextUser instead of User.
- RoutingContext.clearUser() has been removed. 
- io.vertx.ext.auth.AuthProvider has been removed.
- io.vertx.core.logging.Logger has been removed.
- StaticHandler.setWebRoot has been renamed.
- etc.

**Comment by vietj** [comment]
thanks can you open the issue here https://github.com/vert-x3/vertx-5-migration-guide ?

**Comment by vietj** [comment]
@rzorzorzo the points you mentioned have been addressed in the wiki page (https://github.com/vert-x3/wiki/wiki/5.0.0-Deprecations-and-breaking-changes) and the migration guide (https://github.com/vert-x3/vertx-5-migration-guide).

if you spot other issues, please open an issue in the https://github.com/vert-x3/vertx-5-migration-guide issue tracker.
