### ISSUE TITLE
Sorted Local Maps

### ISSUE THREAD

**Issue by oliver-brm** [eclipse-vertx/vert.x#5420]
#### Describe the feature

I would like to add a `SortedLocalMap` to Vert.x core. It is basically the same as `SortedMap`, the difference being that it it keeps the map's items sorted. It is backed by a `java.util.concurrent.ConcurrentNavigableMap` implementation.

#### Use cases

My main use case would be to solve an issue in Vert.x Web (vert-x3/vertx-web#2692), where the `LocalSessionStore`'s reaper algorithm keeps the CPU busy, iterating over the unordered list of open sessions.

However, there can be more such situations, in which an ordered collection provides a significant performance advantage.

#### Contribution

I will suggest a solution via PR.

**Comment by vietj** [comment]
I believe that vertx-web should stop using local map and instead use a more adapted map like you suggest, but it should just be an entry in a regular local map instead of requiring a new shared data structure only for this purpose

**Comment by oliver-brm** [comment]
Took me two reading passes to understand your approach. 🙂 It’s great. I can do that!
