### ISSUE TITLE
Encryption for EventBus

### ISSUE THREAD

**Issue by johr** [eclipse-vertx/vert.x#574]
For being able to run a vertx-cluster on a LAN, where other nodes are present (they should not be able to read the event bus communication) encryption for the server node traffic is necessary.

**Comment by cazacugmihai** [comment]
Hi,

Can we reopen this issue, please?

I added also a comment here: [Bug 415424](https://bugs.eclipse.org/bugs/show_bug.cgi?id=415424).

Thanks,
Mihai

**Comment by cescoffier** [comment]
I've opened a new one: https://github.com/eclipse/vert.x/issues/1275
