### ISSUE TITLE
add support for multipart/form-data

### ISSUE THREAD

**Issue by nemecec** [eclipse-vertx/vert.x#88]
In my project, I need to upload a file to the web server. On client side I created a web form, to **POST the file as multipart/form-data to the server**. Then I used sample code from the "upload" example to handle the file upload on the server (save it in a file, for now). 

However, this results in the following stream on the server: 

> ------WebKitFormBoundaryBacAOGLREnA3aBb1 
> Content-Disposition: form-data; name="datafile"; filename="test.txt" 
> Content-Type: text/plain 
> 123456 
> ------WebKitFormBoundaryBacAOGLREnA3aBb1-- 

As far as I can see, I need some code to reconstruct the original 
stream (e.g. Commons FileUpload). Briefly glancing through the 
documentation I could not find an immediate "vert.x way" of handling 
this. 

**Answer from Tim:**

> Cool. I will take a look, but Netty contains a multi-part form parser in 
> the master branch which hopefully will end up in the 3.4.0 branch before 
> long so hopefully we can just use that :)

**Comment by kissLife** [comment]
With the netty HttpPostMultipartRequestDecoder, we can process the multipart/form-data in real time. see the snippet code here([Handling multipart form in Vertx](https://stackoverflow.com/questions/36401510/handling-multipart-form-in-vertx/64114825#64114825)).
